# Repo-scoped stubs; see lexicon/README.md.
from collections.abc import Iterable, Iterator

from sage.categories.rings import Rings
from sage.modules.free_module import FreeModule_generic
from sage.rings.finite_rings.integer_mod_ring import IntegerModRing_generic
from sage.rings.ideal import Ideal_pid
from sage.rings.integer import Integer
from sage.structure.parent import ElementConstructorInput, MembershipInput, Parent

class IntegerRing_class(Rings.ParentMethods[Integer], Parent[Integer]):
    def __call__(
        self,
        x: ElementConstructorInput = ...,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> Integer: ...
    def prod(self, values: Iterable[ElementConstructorInput]) -> Integer: ...
    def sum(self, values: Iterable[ElementConstructorInput]) -> Integer: ...
    def zero(self) -> Integer: ...
    def one(self) -> Integer: ...
    def gen(self, i: int = ...) -> Integer: ...
    def random_element(self) -> Integer: ...
    # Native zigzag enumeration 0, 1, -1, 2, -2, ...
    def __iter__(self) -> Iterator[Integer]: ...
    def __contains__(self, x: MembershipInput) -> bool: ...
    def __rmul__(self, other: int | Integer) -> Ideal_pid: ...
    # ZZ^n is the free module over ZZ, entries in ZZ (verified: ZZ**2 is a
    # FreeModule_ambient_pid over the Integer Ring).
    def __pow__(self, n: int | Integer) -> FreeModule_generic[Integer]: ...
    def ideal(
        self,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> Ideal_pid[Integer]: ...
    def quotient(
        self,
        I: Ideal_pid,
        names: str | tuple[str, ...] | None = ...,
        **kwds: ElementConstructorInput,
    ) -> IntegerModRing_generic: ...

ZZ: IntegerRing_class
