# Repo-scoped stubs; see lexicon/README.md.
from typing import TYPE_CHECKING, overload

from sage.rings.rational import Rational
from sage.structure.element import RingElement
from sage.structure.factorization import Factorization
from sage.symbolic.expression import Expression

if TYPE_CHECKING:
    from sage.modules.free_module_element import FreeModuleElement

class Integer(RingElement):
    def __init__(self, x: object = ...) -> None: ...
    def __add__(self, other: int | Integer) -> Integer: ...
    def __radd__(self, other: int) -> Integer: ...
    def __sub__(self, other: int | Integer) -> Integer: ...
    def __rsub__(self, other: int) -> Integer: ...
    @overload
    def __mul__(self, other: int | Integer) -> Integer: ...
    @overload
    def __mul__(self, other: FreeModuleElement[Integer | Rational]) -> FreeModuleElement[Integer | Rational]: ...
    # The ZZ-action on vectors: n·m stays in the module. Stated only for
    # vector elements, not for ModuleElement generally: a Rational IS a
    # ModuleElement but the coercion pushout sends Integer * Rational to QQ,
    # so a general ModuleElement overload would falsely claim the Rational
    # case. (Verified: ZZ(2) * QQ(1)/2 is a Rational.)
    @overload
    def __mul__(self, other: Rational) -> Rational: ...
    def __rmul__(self, other: int) -> Integer: ...
    def __truediv__(self, other: int | Integer | Rational) -> Rational: ...
    def __rtruediv__(self, other: int | Integer) -> Rational: ...
    # Element.__floordiv__ (element.pyx:1766) through coercion: ZZ // ZZ is
    # floor division; against QQ the pushout is the field QQ, where a // b
    # is exact division.
    @overload
    def __floordiv__(self, other: int | Integer) -> Integer: ...
    @overload
    def __floordiv__(self, other: Rational) -> Rational: ...
    def __mod__(self, other: int | Integer) -> Integer: ...
    def __rmod__(self, other: int) -> Integer: ...
    # Integer ** Integer is Integer (positive exponent) or Rational (negative
    # exponent, e.g. 2^(-1)); Integer ** Rational is Rational when the
    # required root lies in QQ (4^(1/2) = 2 as a Rational) and symbolic
    # otherwise (2^(1/2) is an Expression). All three cases verified.
    def __pow__(self, n: int | Integer | Rational) -> Integer | Rational | Expression: ...
    def __neg__(self) -> Integer: ...
    def __abs__(self) -> Integer: ...
    def abs(self) -> Integer: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def numerator(self) -> Integer: ...
    def denominator(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def round(self) -> Integer: ...
    def sqrt(self) -> Integer | Expression: ...  # Integer when square, exact symbolic otherwise
    def is_square(self) -> bool: ...
    def is_prime(self) -> bool: ...
    def is_unit(self) -> bool: ...
    # integer.pyx:4897 — integers are integral (monic polynomial over ZZ).
    def is_integral(self) -> bool: ...
    def factor(self) -> Factorization: ...
    def divides(self, other: int | Integer) -> bool: ...
    def lcm(self, other: int | Integer) -> Integer: ...
    def prime_factors(self) -> list[Integer]: ...
    def gcd(self, other: int | Integer) -> Integer: ...
    def inverse_mod(self, n: int | Integer) -> Integer: ...
    def prime_divisors(self) -> list[Integer]: ...
    def valuation(self, p: int | Integer) -> Integer: ...
