# Repo-scoped stubs; see lexicon/README.md.
#
# The exact-real half of the lexicon noun ``RealNumber`` (INVENTORY.md II.1):
# sqrt(2) held in AA, not approximated. Distinct from
# ``sage.rings.real_mpfr.RealNumber``, which is the lexicon's
# ``RealApproximation`` and appears only at display and plot boundaries.
from typing import Literal, overload

from sage.categories.fields import Fields
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_ring import PolynomialRing_general
from sage.rings.real_mpfr import RealNumber as RealApproximation
from sage.structure.element import FieldElement
from sage.structure.parent import Parent

class AlgebraicNumber_base(FieldElement):
    def degree(self) -> Integer: ...
    # Force the exact representation to be computed (AA is lazy).
    def exactify(self) -> None: ...
    # Numerical extraction: the LATE step, at a display boundary.
    def n(self, prec: int = ...) -> RealApproximation: ...

class AlgebraicReal(AlgebraicNumber_base):
    @overload
    def sqrt(self, all: Literal[False] = ...) -> AlgebraicReal: ...
    @overload
    def sqrt(self, all: Literal[True]) -> list[AlgebraicReal]: ...
    def sign(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def round(self) -> Integer: ...
    def __float__(self) -> float: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class AlgebraicRealField(Fields.ParentMethods, Parent[AlgebraicReal]):
    def __call__(self, x: object = ..., *args: object, **kwds: object) -> AlgebraicReal: ...
    # Ring.__getitem__ polynomial-ring constructor: AA['x'].
    def __getitem__(self, name: str) -> PolynomialRing_general: ...

AA: AlgebraicRealField

# The algebraic closure of QQ: AA's complex counterpart, same laziness and
# same exact-then-approximate discipline.
class AlgebraicNumber(AlgebraicNumber_base):
    def real(self) -> AlgebraicReal: ...
    def imag(self) -> AlgebraicReal: ...

class AlgebraicField(Fields.ParentMethods, Parent[AlgebraicNumber]):
    def __call__(self, x: object = ..., *args: object, **kwds: object) -> AlgebraicNumber: ...

QQbar: AlgebraicField
