# Repo-scoped stubs; see lexicon/README.md.
from typing import TYPE_CHECKING, overload

from sage.rings.integer import Integer
from sage.structure.element import FieldElement
from sage.symbolic.expression import Expression

if TYPE_CHECKING:
    from sage.modules.free_module_element import FreeModuleElement

class Rational(FieldElement):
    def __init__(self, x: object = ...) -> None: ...
    def __add__(self, other: int | Integer | Rational) -> Rational: ...
    def __radd__(self, other: int | Integer) -> Rational: ...
    def __sub__(self, other: int | Integer | Rational) -> Rational: ...
    def __rsub__(self, other: int | Integer) -> Rational: ...
    @overload
    def __mul__(self, other: int | Integer | Rational) -> Rational: ...
    @overload
    def __mul__(self, other: FreeModuleElement[Integer | Rational]) -> FreeModuleElement[Integer | Rational]: ...
    def __rmul__(self, other: int | Integer) -> Rational: ...
    def __truediv__(self, other: int | Integer | Rational) -> Rational: ...
    def __rtruediv__(self, other: int | Integer) -> Rational: ...
    def __mod__(self, other: int | Integer | Rational) -> Rational: ...
    # Rational ** int is Rational. Rational ** Rational is Rational when the
    # required root lies in QQ, as in (1/4)^(1/2) = 1/2, and symbolic
    # otherwise, as in (1/2)^(1/2). Both cases are verified.
    def __pow__(self, n: int | Integer | Rational) -> Rational | Expression: ...
    def __neg__(self) -> Rational: ...
    def __abs__(self) -> Rational: ...
    def abs(self) -> Rational: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def numerator(self) -> Integer: ...
    def denominator(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def round(self) -> Integer: ...
    def sqrt(self) -> Rational | Expression: ...  # Rational when square, exact symbolic otherwise
    def is_square(self) -> bool: ...
    # rational.pyx:3580 — whether the rational lies in ZZ.
    def is_integral(self) -> bool: ...
    def valuation(self, p: int | Integer) -> Integer: ...
