# Repo-scoped stubs; see lexicon/README.md.
from collections.abc import Iterator

from sage.categories.fields import Fields
from sage.modules.free_module import FreeModule_generic
from sage.rings.integer import Integer
from sage.rings.rational import Rational
from sage.structure.parent import ElementConstructorInput, MembershipInput, Parent

class RationalField(Fields.ParentMethods[Rational], Parent[Rational]):
    def __call__(
        self,
        x: ElementConstructorInput = ...,
        *args: ElementConstructorInput,
        **kwds: ElementConstructorInput,
    ) -> Rational: ...
    def zero(self) -> Rational: ...
    def one(self) -> Rational: ...
    def gen(self, i: int = ...) -> Rational: ...
    def random_element(self) -> Rational: ...
    # Native height-ordered enumeration 0, 1, -1, 1/2, -1/2, 2, -2, ...
    def __iter__(self) -> Iterator[Rational]: ...
    def __contains__(self, x: MembershipInput) -> bool: ...
    # QQ^n is the free module over QQ, entries in QQ (verified: QQ**2 is a
    # free module over the Rational Field).
    def __pow__(self, n: int | Integer) -> FreeModule_generic[Rational]: ...

QQ: RationalField
