# Repo-scoped stubs; see lexicon/README.md. RealNumber is inexact: display
# and plotting boundaries only, never exact domain arithmetic (repo policy).
from sage.categories.fields import Fields
from sage.structure.element import FieldElement
from sage.structure.parent import MembershipInput

class RealField_class(Fields.ParentMethods[RealNumber]): ...

RR: RealField_class

class RealNumber(FieldElement):
    def __float__(self) -> float: ...
    def __lt__(self, other: MembershipInput) -> bool: ...
    def __le__(self, other: MembershipInput) -> bool: ...
    def __gt__(self, other: MembershipInput) -> bool: ...
    def __ge__(self, other: MembershipInput) -> bool: ...
