r"""Topological versus abstract generation of $\operatorname{Gal}(\overline{\mathbf{F}}_5/\mathbf{F}_5)$."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_frobenius_topologically_generates_zhat_which_is_not_finitely_generated() -> None:
    r"""$\operatorname{Gal}(\overline{\mathbf{F}}_5/\mathbf{F}_5) \cong \widehat{\mathbf{Z}}$.

    It is topologically generated by $x \mapsto x^5$, but it is uncountable, so
    no finite set generates it as an abstract group (Serre, *Local Fields*, XIII.1).
    """
    group = GF(5).absolute_galois_group()
    generators = group.topological_group_generators()

    assert generators.cardinality() == 1
    assert group.frobenius() in generators
    assert group.is_finitely_generated() is False
