r"""Multiplicative submonoids of $\mathbb{Z}$: the odd integers and the powers of two.

The odd integers are closed under multiplication and contain $1$, so they
form a submonoid, containing $9$ and not $4$.  The submonoid generated by
$2$ is $\{1, 2, 4, 8, \dots\}$: it contains $8$ and not $6$, it is not
contained in the odd integers since $2$ is even, and the submonoid
generated by $4$ lies inside it because $4 = 2^2$.  These follow from the
definition of the submonoid generated by a set.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_the_odd_integers_form_a_multiplicative_submonoid() -> None:
    odd = ZZ.predicate_submonoid(lambda n: n % 2 == 1, "odd integers")

    assert 9 in odd
    assert 4 not in odd
    assert odd.one() == 1


def test_the_powers_of_two_are_not_all_odd() -> None:
    powers = ZZ.generated_submonoid([2])
    odd = ZZ.predicate_submonoid(lambda n: n % 2 == 1, "odd integers")

    assert powers.one() == 1
    assert powers.inclusion().factor_through_or_none(odd.inclusion()) is None


def test_the_powers_of_two_contain_eight_and_not_six() -> None:
    powers = ZZ.generated_submonoid([2])

    assert 8 in powers
    assert 6 not in powers


def test_the_powers_of_four_lie_in_the_powers_of_two() -> None:
    powers_of_two = ZZ.generated_submonoid([2])
    powers_of_four = ZZ.generated_submonoid([4])
    factor = powers_of_four.inclusion().factor_through(powers_of_two.inclusion())

    assert powers_of_two.inclusion()(factor(powers_of_four(4))) == 4
