r"""The absolute Galois group of $\mathbb{F}_7$ is topologically generated by Frobenius."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_the_frobenius_of_f7_generates_every_finite_quotient() -> None:
    r"""$\operatorname{Gal}(\mathbb{F}_{7^n}/\mathbb{F}_7)$ is cyclic of order $n$, generated by $x \mapsto x^7$; so $G_{\mathbb{F}_7}$ is abelian and one element topologically generates it."""
    group = GF(7).absolute_galois_group()
    frobenius = group.frobenius()

    assert group.is_abelian()
    assert group.topological_generating_family().cardinality() == 1
    for degree in (2, 3, 4):
        stage = group.finite_extension(degree)
        assert group.restriction_map(stage)(frobenius).multiplicative_order() == degree
