r"""Issue 401 finite-index and subgroup-image closure specimens."""

from dzack_research.preamble.all import *  # noqa: F401,F403
from dzack_research.preamble.categories.group.groups import _matrix_group_element_matrix


def test_mod_two_kernel_of_sl2z_has_index_six_and_schreier_generators():
    from sage.modular.arithgroup.all import Gamma

    group = Groups.SL(2, ZZ)
    target = Groups.SL(2, GF(2))
    engine = target._engine_group()
    reduction = group.Mor(target)(
        lambda g: target._from_engine(engine([
            [engine.base_ring()(int(entry)) for entry in row]
            for row in _matrix_group_element_matrix(group, g).rows()
        ]))
    )
    kernel = reduction.kernel()
    generators = kernel.schreier_generators()
    assert kernel.index() == 6
    assert target.cardinality() == 6
    assert all(reduction(g) == target.one() for g in generators)
    assert len(generators) == 12
    # Independently identify the subgroup generated by these actual matrices.
    # Gamma(2) is generated by -I, T^2, and S*T^2*S^-1; the returned
    # family contains the first two and minus the third. No claim about
    # the generated subgroup's index is inferred from schreier_generators.
    matrices = {tuple(_matrix_group_element_matrix(group, g).list()) for g in generators}
    minus_identity = (-1, 0, 0, -1)
    t_squared = (1, 2, 0, 1)
    minus_lower_transvection = (-1, 0, 2, -1)
    assert {minus_identity, t_squared, minus_lower_transvection} <= matrices
    # Every returned generator reduces to I mod 2, so H <= Gamma(2).
    # These three witnesses generate Gamma(2), so Gamma(2) <= H.
    # Gamma's independent modular-coset implementation computes its index.
    assert Gamma(2).index() == 6


def test_indefinite_stable_orthogonal_kernel_with_supplied_generators():
    lattice = Lattices(ZZ)([[0, 2], [2, 0]])
    group = lattice.Aut()
    exchange = group([[0, 1], [1, 0]])
    minus_id = group([[-1, 0], [0, -1]])
    stable = lattice.stable_orthogonal_group()
    rho = lattice.discriminant_representation()
    generators = stable.schreier_generators(generators=(exchange, minus_id))
    assert generators
    assert all(rho(g) == rho.codomain().one() for g in generators)
    assert stable.image_under(rho, ambient_generators=(exchange, minus_id)).cardinality() == 1


def test_a2_discriminant_image_from_orthogonal_generators():
    lattice = Lattices(ZZ)("A2")
    rho = lattice.discriminant_representation()
    group = lattice.Aut().select_group_resolution()
    image = group.subgroup(tuple(group.group_generators())).image_under(rho)
    assert image.cardinality() == rho.codomain().cardinality() == 2


def test_unresolved_predicate_image_names_missing_inverse_algorithm():
    subset = Sets().condition_set(ZZ, lambda x: x*x == ZZ(4))
    square = Sets().Mor(ZZ, ZZ)(lambda x: x*x)
    image = Sets().image_set(square, subset)
    try:
        ZZ(4) in image
    except AssertionError as error:
        assert "source is infinite and no inverse on the image was given" in str(error)
    else:
        raise AssertionError("membership in a predicate image was decided without an algorithm")


def test_indefinite_predicate_image_with_supplied_ambient_generators():
    lattice = Lattices(ZZ)([[0, 2], [2, 0]])
    group = lattice.Aut()
    exchange = group([[0, 1], [1, 0]])
    minus_id = group([[-1, 0], [0, -1]])
    rho = lattice.discriminant_representation()
    stable = group.predicate_subgroup(
        lambda g: rho(g) == rho.codomain().one(), "stable kernel predicate"
    )
    assert stable.image_under(
        rho, index_bound=4, ambient_generators=(exchange, minus_id)
    ).cardinality() == 1
