r"""The scale and the norm of a lattice are different ideals."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_a2_has_scale_zz_and_norm_2zz() -> None:
    r"""$\mathfrak{s}(A_2) = \mathbb{Z}$ and $\mathfrak{n}(A_2) = 2\mathbb{Z}$; $\mathfrak{s}(\langle 2\rangle) = 2\mathbb{Z}$.

    The scale is generated by all values $b(x, y)$, the norm by the values
    $b(x, x)$.  $A_2$ has Gram matrix $\begin{psmallmatrix}-2&1\\1&-2\end{psmallmatrix}$,
    so it pairs to $1$ while every $b(x, x)$ is even.  Source: O'Meara,
    *Introduction to Quadratic Forms*, §82E.
    """
    a2 = Lattices(ZZ)("A2")
    two = Lattices(ZZ)([[2]])

    assert ZZ.one() in a2.scale_submodule()
    assert ZZ.one() not in a2.norm_submodule()
    assert ZZ(2) in a2.norm_submodule()
    assert ZZ.one() not in two.scale_submodule()
    assert ZZ(2) in two.scale_submodule()
