r"""Discriminant bilinear modules."""

from typing import Any

from sage.categories.category import Category
from sage.groups.additive_abelian.qmodnz import QmodnZ, QmodnZ_Element
from sage.matrix.matrix0 import Matrix
from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.modules.fg_pid.fgp_morphism import FGP_Morphism
from sage.modules.fg_pid.fgp_module import FGP_Module_class
from sage.modules.free_module import FreeModule
from sage.modules.free_module_element import FreeModuleElement
from sage.modules.free_module_morphism import FreeModuleMorphism
from sage.modules.free_quadratic_module_integer_symmetric import (
    FreeQuadraticModule_integer_symmetric,
)


class TorsionBilinearFormElement(FGP_Element):
    r"""A class $\bar x\in\operatorname{coker} c$ carrying $b$.

    Its own type so that the category's methods have a domain to speak of: an
    element of a torsion bilinear module is not interchangeable with an element
    of the quadratic one, and neither is a bare ``FGP_Element``.
    """


class TorsionBilinearForm(FGP_Module_class):
    r"""$(\operatorname{coker} c,\; b)$ for the correlation $c: L\to L^\vee$.

    Everything comes from the morphism: its matrix gives the relations, its
    codomain gives the generators the cokernel is generated by, and that
    codomain's form gives the pairings, read modulo $\mathbb Z$.

    A different generating set means a different codomain, hence a different
    morphism and a different object -- which is what ``invariant_factor_form``
    and ``normal_form`` build.

    The mirror of :func:`TorsionQuadraticForm`, and not built on Sage's
    ``TorsionQuadraticModule``: that class holds $b$ and $q$ at once and tells
    them apart by a pair of moduli, so a bilinear form living in it would have
    to carry a ``modulus_qf`` naming a value group it does not have.

    Carries no methods of its own -- they are :class:`DiscriminantBilinearModules`'s.  The type exists
    so the object has a name, for annotations and for ``isinstance``.
    """

    Element = TorsionBilinearFormElement


class DiscriminantBilinearModules(Category):
    r"""Category of discriminant bilinear modules.

    The category's ``gram_matrix`` is the bilinear Gram matrix. Quadratic
    discriminant modules expose their associated bilinear form through
    :meth:`associated_bilinear_form`.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "discriminant bilinear modules"

    def super_categories(self) -> list:
        return [TorsionModulesWithForm()]

    def cokernel(self, morphism: LatticeMorphism) -> TorsionBilinearForm:
        r"""Return $\operatorname{coker}$ of ``morphism`` as an object of this category.

        Which category is asked settles which form the answer carries, so the
        construction belongs here rather than to a free function.
        """
        cover, relations = cokernel_of(morphism)
        form = TorsionBilinearForm(cover, relations)
        form._morphism = morphism
        refine(form, self)
        subdivide_form_gram_matrix(form)
        return form

    class ParentMethods:
        r"""Methods available on discriminant bilinear modules."""

        def gram_matrix(self: Any) -> Matrix:
            r"""Return the matrix of $b$ on :meth:`gens`."""
            generators = self.gens()
            return matrix(
                QQ,
                [[(x * y).lift() for y in generators] for x in generators],
            )

        def value_module(self: Any) -> QmodnZ:
            r"""Return $\mathbb Q/\mathbb Z$, where $b$ takes its values."""
            return QmodnZ(1)

        def associated_quadratic_form(self: Any) -> "TorsionQuadraticForm":
            r"""Return the discriminant quadratic form on the same group.

            $b$ does not determine $q$: the refinement
            $q:A_L\to\mathbb Q/2\mathbb Z$ exists exactly when $L$ is even,
            because moving a lift by $\ell\in L$ shifts $b(\tilde x,\tilde x)$
            by $b(\ell,\ell)$, which lies in $2\mathbb Z$ only then.  So this
            passage goes back through the lattice, unlike
            :meth:`~DiscriminantQuadraticModules.ParentMethods.associated_bilinear_form`,
            which polarizes $q$ and needs nothing else.
            """
            return DiscriminantQuadraticModules().cokernel(self.correlation())

        def _form_matrix_latex_label(self: Any) -> str:
            r"""Return the LaTeX label for the bilinear Gram matrix."""
            return "G_{b_{A_L}}"

        def correlation(self: Any) -> LatticeMorphism:
            r"""Return the $f$ this module is the cokernel of.

            It settles the object: a morphism of lattices with generating sets has a
            unique matrix, and $\operatorname{coker} f$ takes its generating set
            from $f$'s codomain and its form from that codomain's Gram matrix.
            """
            return self._morphism

        def projection(self: Any) -> FGP_Morphism:
            r"""Return $\pi: B\to\operatorname{coker} f$, sending $g_i$ to $h_i$."""
            return self.quotient_map()

        def gens(self: Any) -> tuple[TorsionBilinearFormElement, ...]:
            r"""Return the generating set: the images of the codomain's generators.

            Shadows ``FGP_Module_class.gens``, which hands back the Smith-form
            generators -- a different generating set, so a different object.
            """
            return tuple(self(generator) for generator in self.V().gens())

        def primary_part(self: Any, p: Any) -> Subobject:
            r"""Return $A_p\hookrightarrow A$ as a subobject: the inclusion is the data.

            $A_p$ is an object of this category in its own right -- the cokernel of
            the correlation with codomain cut down to the preimage of $A_p$ -- and
            the subobject is that object together with its inclusion, not a
            predicate about which elements are $p$-primary.
            """
            multiplier = self.annihilator().gen().prime_to_m_part(p)
            images = [multiplier * generator for generator in self.gens()]
            part = DiscriminantBilinearModules().cokernel(
                regenerated_by(self, [multiplier * g.lift() for g in self.gens()])
            )
            return Subobject(form_morphism(part, images, self))

        def invariant_factor_form(self: Any) -> "TorsionBilinearForm":
            r"""Return $b$ on generators from the invariant factor decomposition.

            The same cokernel of the same $c$, so the same $b$; what changes is the
            generating set, and with it the object.  The change merges factors
            across summands -- $A_{A_2\oplus A_3}$ lands on one generator as
            $\mathbb Z/12$ rather than on two as $\mathbb Z/3\oplus\mathbb Z/4$ --
            so no decomposition of $L$ survives it.
            """
            return DiscriminantBilinearModules().cokernel(
                regenerated_by(self, [g.lift() for g in self.smith_form_gens()])
            )

        def normal_form(self: Any) -> "TorsionBilinearForm":
            r"""Return $b$ on $p$-adic Jordan generators -- again a different object.

            The generators are the Jordan ones prime by prime, cutting out their own
            orthogonal blocks (Peters--Sterk Def. 11.2.2, Prop. 11.2.3 [PS24]).  For
            odd $p$ they are unique: Prop. 11.1.3 makes the discriminant-form map a
            bijection onto $p$-primary symmetric torsion forms of that length, and
            the blocks are the $\oplus^{r-1}\langle p^{-k}\rangle\oplus\langle
            \epsilon p^{-k}\rangle$ of Prop. 9.4.1.  At $p=2$ existence holds but
            uniqueness does not -- the isometries I--IV of Sec. 11.2 still relate
            distinct normal forms, and the reduced normal form that settles them
            (Cor. C.3.2) is built from the Gauss-sum index invariants of App. C.2,
            which are defined from $q$ and have no $b$ analogue.  So this is *a*
            normal form, not *the* one.
            """
            return DiscriminantBilinearModules().cokernel(
                regenerated_by(self, p_adic_jordan_generators(self))
            )

        def source_lattice(self: Any) -> FreeQuadraticModule_integer_symmetric:
            r"""Return the lattice \(L\) whose dual basis generates this form.

            $L$ supplies a decomposition of *its* own generating set and of
            nothing else, so a form built on other generators has a synthesized
            domain carrying none, and its blocks are read off its Gram matrix.
            """
            return self._morphism.domain()

    class ElementMethods:
        r"""Methods available on elements of discriminant bilinear modules.

        An element is a coset $\bar x = x + f(L)$; $b(\bar x,\bar y)$ is the
        pairing of any two lifts, read in $\mathbb Q/\mathbb Z$ because moving
        a lift by $f(\ell)$ shifts it by $b(\ell', \ell)\in\mathbb Z$.
        """

        def b(self: Any, other: "TorsionBilinearFormElement") -> QmodnZ_Element:
            r"""Return $b(\bar x,\bar y)\in\mathbb Q/\mathbb Z$.

            A lift is a coordinate vector in $L^\vee$'s generators, so the
            pairing is $L^\vee$'s own, reduced modulo $\mathbb Z$ -- moving a
            lift by $c(\ell)$ shifts it by $\langle x,\ell\rangle\in\mathbb Z$.
            """
            return self.parent().value_module()(
                self.lift().inner_product(other.lift())
            )

        def __mul__(self: Any, other: Any) -> Any:
            r"""``x * y`` -> the pairing; anything else -> native semantics.

            Elements subclass Sage's native element type, so scalars and
            coercion keep its behaviour via ``super()``.
            """
            if isinstance(other, TorsionBilinearFormElement):
                return self.b(other)
            return super().__mul__(other)
