r"""Free resolutions that continue past the first relation module.

Over a principal ideal domain the relations of a finitely presented module are
free, so one step resolves it.  Over ``R = QQ[x,y]`` they are not: the residue
field ``k = R/(x,y)`` is presented by the two relations ``x`` and ``y``, whose
syzygies are generated by ``(y,-x)``, and only that third term closes the
Koszul complex

``0 -> R -> R^2 -> R -> k -> 0``.

So the resolution has length two, the composite of consecutive differentials
vanishes, and the tower stops on its own because the last differential is
injective.  Its degree-two term is what makes ``Tor_2(k,k)`` visible; a
resolution truncated at the relations would report the wrong module there.
"""

from dzack_research.preamble.all import (
    BasedFreeModule,
    FinitelyPresentedModule,
    PolynomialRing,
    QQ,
    ZZ,
    Tor,
    module_homset,
)
from dzack_research.preamble.categories.sets import finite_ordered_set


def _residue_field_module():
    r"""Return ``QQ[x,y]/(x,y)`` presented on one generator by ``x`` and ``y``."""
    ring = PolynomialRing(QQ, "x,y")
    x = ring.algebra_generator("x")
    y = ring.algebra_generator("y")
    free = BasedFreeModule(ring, finite_ordered_set(("g",)))
    relations = BasedFreeModule(ring, finite_ordered_set(("rx", "ry")))
    presentation = module_homset(relations, free)(
        {
            "rx": x * free.module_generator("g"),
            "ry": y * free.module_generator("g"),
        }
    )
    return FinitelyPresentedModule(presentation)


def test_the_residue_field_of_the_plane_resolves_in_two_steps() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)

    assert resolution.length() == 2
    assert resolution.degrees().cardinality() == 3
    assert resolution.term(0).rank() == 1
    assert resolution.term(1).rank() == 2
    assert resolution.term(2).rank() == 1
    assert resolution.term(3).rank() == 0


def test_the_koszul_resolution_is_exact() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)

    assert resolution.differential(2).is_injective()
    assert resolution.augmentation().is_surjective()
    assert resolution.is_exact()


def test_consecutive_differentials_compose_to_zero() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)
    second = resolution.differential(2)
    first = resolution.differential(1)

    for label in second.domain().module_generating_set():
        image = first(second(second.domain().module_generator(label)))
        assert image == first.codomain().zero()


def test_the_syzygy_term_carries_the_koszul_relation() -> None:
    module = _residue_field_module()
    ring = module.base_ring()
    x = ring.algebra_generator("x")
    y = ring.algebra_generator("y")

    resolution = module.free_resolution(3)
    second = resolution.differential(2)
    relations = second.codomain()
    labels = tuple(relations.module_generating_set())
    generator = second.domain().module_generator(
        next(iter(second.domain().module_generating_set()))
    )

    image = second(generator)
    expected_up_to_sign = y * relations.module_generator(
        labels[0]
    ) - x * relations.module_generator(labels[1])
    assert image == expected_up_to_sign or image == -expected_up_to_sign


def test_tor_of_the_residue_field_reads_the_degree_two_term() -> None:
    r"""``Tor_2(k,k)`` is computed in the Koszul complex, not in a truncation.

    ``Tor_n`` is the cohomology of ``F_• ⊗ k`` in the matching spot, so its
    complex must carry ``F_2``.  Every differential of ``F_• ⊗ k`` vanishes
    because each entry of the Koszul matrices lies in ``(x,y)``, which is why
    ``Tor_i(k,k)`` is the ``i``-th exterior power of ``k^2`` and in particular
    does not vanish in degree two.
    """
    module = _residue_field_module()

    tor = Tor(2, module, module)
    complex_ = tor.cochain_complex()
    resolution = module.free_resolution(3)

    assert complex_.graded_piece(0).tensor_factor(0) is resolution.term(2)


def test_a_principal_ideal_domain_resolves_in_one_step_however_far_it_is_asked() -> None:
    free = BasedFreeModule(ZZ, finite_ordered_set(("g",)))
    relations = BasedFreeModule(ZZ, finite_ordered_set(("r",)))
    module = FinitelyPresentedModule(
        module_homset(relations, free)({"r": ZZ(6) * free.module_generator("g")})
    )

    assert module.free_resolution(4) is module.free_resolution()
    assert module.free_resolution(4).length() == 1
