r"""Free resolutions that continue past the first relation module.

Over $R = \mathbb Q[x,y]$ the residue field $k = R/(x,y)$ has the Koszul resolution
$0 \to R \xrightarrow{(y,-x)} R^2 \xrightarrow{(x,y)} R \to k \to 0$ of length two,
and $\operatorname{Tor}_i^R(k,k) = \Lambda^i k^2$ since every Koszul differential
vanishes mod $(x,y)$ (Eisenbud, *Commutative Algebra*, 17.2 and 17.4).  Over a
principal ideal domain one step resolves every finitely generated module.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def residue_field_of_the_plane():
    R = QQ["x,y"]
    x, y = R.algebra_generator("x"), R.algebra_generator("y")
    return R, x, y, Modules(R)(R.quotient_ring(R.ideal(x, y)))


def test_the_residue_field_of_the_plane_has_resolution_ranks_1_2_1() -> None:
    R, x, y, k = residue_field_of_the_plane()
    resolution = k.free_resolution(3)
    assert resolution.length() == 2
    assert resolution.term(0).module_rank() == 1
    assert resolution.term(1).module_rank() == 2
    assert resolution.term(2).module_rank() == 1
    assert resolution.term(3).module_rank() == 0


def test_the_koszul_resolution_of_the_residue_field_is_exact() -> None:
    R, x, y, k = residue_field_of_the_plane()
    resolution = k.free_resolution(3)
    assert resolution.differential(2).is_injective()
    assert resolution.augmentation().is_surjective()
    assert resolution.is_exact()


def test_consecutive_koszul_differentials_compose_to_zero() -> None:
    R, x, y, k = residue_field_of_the_plane()
    resolution = k.free_resolution(3)
    d1, d2 = resolution.differential(1), resolution.differential(2)
    assert d1 * d2 == d2.domain().Mor(d1.codomain()).zero()
    assert d1 != d1.domain().Mor(d1.codomain()).zero()


def test_the_syzygy_of_x_and_y_is_the_koszul_relation() -> None:
    """The syzygy module of (x, y) is generated by (y, -x), up to the order and sign of the basis."""
    R, x, y, k = residue_field_of_the_plane()
    resolution = k.free_resolution(3)
    d2 = resolution.differential(2)
    F1 = d2.codomain()
    e0, e1 = F1.module_generator(0), F1.module_generator(1)
    image = d2(d2.domain().module_generator(0))
    koszul = (y * e0 - x * e1, x * e0 - y * e1, y * e0 + x * e1, x * e0 + y * e1)
    assert image in koszul or -image in koszul


def test_tor_of_the_residue_field_with_itself_is_the_exterior_algebra_of_k2() -> None:
    """Tor_0(k,k) = k, Tor_1(k,k) = k^2, Tor_2(k,k) = k, Tor_3(k,k) = 0. Source: Eisenbud 17.4."""
    R, x, y, k = residue_field_of_the_plane()
    maximal = R.ideal(x, y)
    for degree, dimension in ((0, 1), (1, 2), (2, 1)):
        tor = k.tor(k, degree=degree)
        assert tor.minimal_number_of_generators() == dimension
        assert tor.annihilator() == maximal
    assert k.tor(k, degree=3).is_zero()


def test_z_mod_6_resolves_in_one_step_however_far_it_is_asked() -> None:
    """Z is a PID, so the relation module 6Z is free. Source: Weibel 4.1.5."""
    M = Modules(ZZ)(ZZ.quotient_ring(ZZ.ideal(6)))
    assert M.free_resolution(4).length() == 1
    assert M.free_resolution(4).term(2).module_rank() == 0
