r"""Kernels and cohomology of complexes of modules over \(\mathbb Z[x]\)."""

from dzack_research.preamble.all import ZZ, CochainComplexes, Modules


def _koszul_specimen():
    r"""The complex \(R^2 \xrightarrow{(2,\ x)} R\) over \(R = \mathbb Z[x]\)."""
    ring = ZZ["x"]
    x = ring.gen()
    source = Modules(ring)(ring**2)
    target = Modules(ring)(ring**1)
    a, b = source.module_generators()
    (c,) = target.module_generators()
    differential = source.Mor(target)({a: 2 * c, b: x * c})
    complex_ = CochainComplexes(ring)({0: source, 1: target}, {0: differential})
    return ring, x, source, target, a, b, c, differential, complex_


def test_the_kernel_of_two_x_on_ZZx_squared_is_free_on_the_koszul_syzygy() -> None:
    r"""\(2 \cdot p + x \cdot q = 0\) forces \(x \mid p\), \(2 \mid q\), so
    \(\ker(2, x) = \mathbb Z[x]\,(-x, 2)\), free of rank one (Koszul complex of the
    regular sequence \(2, x\); Eisenbud, Commutative Algebra, §17.2)."""
    _ring, x, _source, _target, a, b, _c, differential, _complex = _koszul_specimen()
    kernel = differential.kernel()
    syzygy = -x * a + 2 * b

    assert kernel.is_free()
    assert kernel.module_generators().cardinality() == 1
    (generator,) = kernel.module_generators()
    assert kernel.inclusion()(generator) in (syzygy, -syzygy)
    assert differential(syzygy) == differential.codomain().zero()


def test_the_first_cohomology_of_two_x_is_ZZx_mod_two_x_which_is_F2() -> None:
    r"""\(H^1 = \mathbb Z[x]/(2, x) \cong \mathbb F_2\): \([c] \ne 0\), \(2c\) and \(xc\) are
    coboundaries."""
    _ring, x, _source, _target, _a, _b, c, _differential, complex_ = _koszul_specimen()
    h1 = complex_.cohomology(1)
    one_class = h1.class_of_cycle(c)

    assert one_class != h1.zero()
    assert h1.class_of_cycle(2 * c) == h1.zero()
    assert h1.class_of_cycle(x * c) == h1.zero()
    assert h1.cardinality() == 2


def test_the_kernel_of_ZZx_mod_2x_onto_ZZx_mod_2_is_generated_by_2a_and_killed_by_x() -> None:
    r"""\(\mathbb Z[x]/(2x) \to \mathbb Z[x]/(2)\), \(a \mapsto c\), has kernel
    \((2)/(2x)\), generated by \(2a\), and \(x \cdot 2a = 2xa = 0\)."""
    ring = ZZ["x"]
    x = ring.gen()
    free_source = Modules(ring)(ring**1)
    (free_a,) = free_source.module_generators()
    source_relations = Modules(ring)(ring**1)
    (r,) = source_relations.module_generators()
    source = source_relations.Mor(free_source)({r: 2 * x * free_a}).cokernel()

    free_target = Modules(ring)(ring**1)
    (free_c,) = free_target.module_generators()
    target_relations = Modules(ring)(ring**1)
    (s,) = target_relations.module_generators()
    target = target_relations.Mor(free_target)({s: 2 * free_c}).cokernel()
    (a,) = source.module_generators()
    (c,) = target.module_generators()
    reduction = source.Mor(target)({a: c})

    kernel = reduction.kernel()
    (generator,) = kernel.module_generators()

    assert kernel.inclusion()(generator) in (2 * a, -2 * a)
    assert x * generator == kernel.zero()
    assert generator != kernel.zero()
    assert reduction(2 * a) == target.zero()
    assert reduction(a) != target.zero()
