r"""Reconcile archived framed-module matrix helpers with their live adapter."""

import pytest
from sage.matrix.constructor import matrix
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.rational_field import QQ as SageQQ

from dzack_research.preamble.all import QQ as OwnedQQ

from dzack_research.preamble.categories.modules.module_morphisms.morphism_matrices import (
    _matrix_group,
    _row_normal_form,
)

ARCHIVE_RECONCILIATION = {
    "archive_module": "preamble/categories/modules/module_morphisms/morphism_matrices.py",
    "live_owner": "src/dzack_research/preamble/categories/modules/module_morphisms/morphism_matrices.py",
    "disposition": "reconciled-live-owner",
}


def test_row_normal_form_retains_field_and_integral_archive_algorithms() -> None:
    rational = matrix(SageQQ, [[1, 2], [2, 4], [0, 0]])
    reduced = _row_normal_form(rational)
    assert reduced == rational.echelon_form().matrix_from_rows([0])
    assert _row_normal_form(rational, include_zero_rows=True) == rational.echelon_form()

    integral = matrix(SageZZ, [[2, 4], [6, 8]])
    assert _row_normal_form(integral) == integral.hermite_form(include_zero_rows=False)
    assert _row_normal_form(integral, include_zero_rows=True) == integral.hermite_form(
        include_zero_rows=True
    )


def test_matrix_group_retains_the_generated_matrix_group_and_stronger_failures() -> None:
    involution = matrix(SageZZ, [[0, 1], [1, 0]])
    group = _matrix_group((involution,))
    assert group.order() == 2
    assert group.gen(0) == involution

    with pytest.raises(ValueError, match="at least one generator"):
        _matrix_group(())
    with pytest.raises(TypeError, match="generated by matrices"):
        _matrix_group((object(),))


def test_smith_form_stops_at_the_pid_hypothesis() -> None:
    ring = OwnedQQ.polynomial_ring(("x", "y"))
    x = ring.algebra_generator("x")
    entries = ring.matrix_space(2).from_rows(
        ((ring.one(), x), (ring.zero(), ring.one()))
    )

    with pytest.raises(AssertionError):
        entries.smith_form()
