r"""Free resolutions that continue past the first relation module.

Over a principal ideal domain the relations of a finitely presented module are
free, so one step resolves it.  Over ``R = QQ[x,y]`` they are not: the residue
field ``k = R/(x,y)`` is presented by the two relations ``x`` and ``y``, whose
syzygies are generated by ``(y,-x)``, and only that third term closes the
Koszul complex

``0 -> R -> R^2 -> R -> k -> 0``.

So the resolution has length two, the composite of consecutive differentials
vanishes, and the tower stops on its own because the last differential is
injective.  Its degree-two term is what makes ``Tor_2(k,k)`` visible; a
resolution truncated at the relations would report the wrong module there.
"""

from dzack_research.preamble.all import (
    QQ,
    ZZ,
)
from dzack_research.preamble.categories.sets import finite_ordered_set


def _residue_field_module():
    r"""Return ``QQ[x,y]/(x,y)`` presented on one generator by ``x`` and ``y``."""
    ring = QQ.polynomial_ring("x,y")
    x = ring.algebra_generator("x")
    y = ring.algebra_generator("y")
    free = ring.free_module(finite_ordered_set(("g",)))
    relations = ring.free_module(finite_ordered_set(("rx", "ry")))
    presentation = relations.module_category().Mor(relations, free)(
        {
            "rx": x * free.module_generator("g"),
            "ry": y * free.module_generator("g"),
        }
    )
    return presentation.cokernel()


def test_the_residue_field_of_the_plane_resolves_in_two_steps() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)

    assert resolution.length() == 2
    assert resolution.degrees().cardinality() == 3
    assert resolution.term(0).module_rank() == 1
    assert resolution.term(1).module_rank() == 2
    assert resolution.term(2).module_rank() == 1
    assert resolution.term(3).module_rank() == 0


def test_the_koszul_resolution_is_exact() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)

    assert resolution.differential(2).is_injective()
    assert resolution.augmentation().is_surjective()
    assert resolution.is_exact()


def test_consecutive_differentials_compose_to_zero() -> None:
    module = _residue_field_module()

    resolution = module.free_resolution(3)
    second = resolution.differential(2)
    first = resolution.differential(1)

    for label in second.domain().module_generating_set():
        image = first(second(second.domain().module_generator(label)))
        assert image == first.codomain().zero()


def test_the_syzygy_term_carries_the_koszul_relation() -> None:
    module = _residue_field_module()
    ring = module.base_ring()
    x = ring.algebra_generator("x")
    y = ring.algebra_generator("y")

    resolution = module.free_resolution(3)
    second = resolution.differential(2)
    relations = second.codomain()
    labels = tuple(relations.module_generating_set())
    generator = second.domain().module_generator(
        next(iter(second.domain().module_generating_set()))
    )

    image = second(generator)
    expected_up_to_sign = y * relations.module_generator(
        labels[0]
    ) - x * relations.module_generator(labels[1])
    assert image == expected_up_to_sign or image == -expected_up_to_sign




def test_a_principal_ideal_domain_resolves_in_one_step_however_far_it_is_asked() -> None:
    free = ZZ.free_module(finite_ordered_set(("g",)))
    relations = ZZ.free_module(finite_ordered_set(("r",)))
    module = relations.module_category().Mor(relations, free)({"r": ZZ(6) * free.module_generator("g")}).cokernel()

    assert module.free_resolution(4) is module.free_resolution()
    assert module.free_resolution(4).length() == 1
