r"""Cohomology of two-term cochain complexes of abelian groups."""

from dzack_research.preamble.all import *


def test_the_complex_ZZ_times_two_ZZ_has_H0_zero_and_H1_ZZ_mod_2() -> None:
    r"""\(\mathbb Z \xrightarrow{2} \mathbb Z\): multiplication by \(2\) is injective with
    cokernel \(\mathbb Z/2\), so \(H^0 = 0\), \(H^1 = \mathbb Z/2\) and \(2f\) is a coboundary."""
    degree_zero = Modules(ZZ)(ZZ**1)
    degree_one = Modules(ZZ)(ZZ**1)
    (e,) = degree_zero.module_generators()
    (f,) = degree_one.module_generators()
    d0 = degree_zero.Mor(degree_one)({e: 2 * f})
    complex_ = CochainComplexes(ZZ)({0: degree_zero, 1: degree_one}, {0: d0})

    assert complex_.cohomology(0).is_zero()
    h1 = complex_.cohomology(1)
    invariant_factors = h1.invariant_factors()
    assert invariant_factors.cardinality() == 1
    assert invariant_factors[0] == ZZ(2)
    assert h1.class_of_cycle(f) != h1.zero()
    assert h1.class_of_cycle(2 * f) == h1.zero()


def test_the_complex_ZZ_mod_4_onto_ZZ_mod_2_has_H0_generated_by_2x_and_H1_zero() -> None:
    r"""\(\mathbb Z/4 \to \mathbb Z/2\), \(x \mapsto y\), is onto with kernel \(2\mathbb Z/4
    \cong \mathbb Z/2\) generated by \(2x\)."""
    source_free = Modules(ZZ)(ZZ**1)
    (free_x,) = source_free.module_generators()
    source_relations = Modules(ZZ)(ZZ**1)
    (r4,) = source_relations.module_generators()
    source = source_relations.Mor(source_free)({r4: 4 * free_x}).cokernel()

    target_free = Modules(ZZ)(ZZ**1)
    (free_y,) = target_free.module_generators()
    target_relations = Modules(ZZ)(ZZ**1)
    (r2,) = target_relations.module_generators()
    target = target_relations.Mor(target_free)({r2: 2 * free_y}).cokernel()

    (x,) = source.module_generators()
    (y,) = target.module_generators()
    differential = source.Mor(target)({x: y})
    complex_ = CochainComplexes(ZZ)({0: source, 1: target}, {0: differential})

    h0 = complex_.cohomology(0)
    h1 = complex_.cohomology(1)
    invariant_factors = h0.invariant_factors()
    assert invariant_factors.cardinality() == 1
    assert invariant_factors[0] == ZZ(2)
    assert h1.is_zero()
    assert h0.class_of_cycle(2 * x) != h0.zero()
