r"""Kernels of maps of finitely presented modules over $\mathbb Z$ and over the coordinate axes.

On $A = \mathbb Q[x,y]/(xy)$ every element is uniquely $c + x p(x) + y q(y)$, so
$x \cdot a = 0$ exactly when $a \in yA$, and $y \cdot a = 0$ exactly when $a \in xA$.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def coordinate_axes():
    R = QQ["x,y"]
    x, y = R.gens()
    A = R.quotient_ring(R.ideal(x * y))
    return A, A(x), A(y)


def test_the_kernel_of_y_x_on_the_coordinate_axes_is_generated_by_x_0_and_0_y() -> None:
    r"""$\ker\big((y, x)\colon A^2 \to A\big) = A(x, 0) + A(0, y)$, minimally generated by two elements.

    Source: by hand from the normal form $c + x p(x) + y q(y)$.
    """
    A, x, y = coordinate_axes()
    F = A**2
    u, v = F.module_generator(0), F.module_generator(1)
    G = A**1
    w = G.module_generator(0)
    morphism = F.Mor(G)({0: y * w, 1: x * w})

    kernel = morphism.kernel()
    inclusion = kernel.inclusion()
    assert kernel.minimal_number_of_generators() == 2
    assert inclusion.is_in_image(x * u)
    assert inclusion.is_in_image(y * v)
    assert inclusion.is_in_image(x * u - y * v)
    assert not inclusion.is_in_image(u)
    assert not inclusion.is_in_image(y * u)
    assert inclusion(inclusion.lift(x * u - y * v)) == x * u - y * v


def test_the_kernel_of_x_on_the_coordinate_axes_is_yA_which_x_kills_and_is_not_free() -> None:
    r"""$\ker(x\colon A \to A) = yA \cong A/(x)$: cyclic, generated by $y$, annihilated by $x$, not free.

    Source: by hand from the normal form $c + x p(x) + y q(y)$.
    """
    A, x, y = coordinate_axes()
    M = A**1
    e = M.module_generator(0)
    kernel = M.End()({0: x * e}).kernel()

    assert kernel.minimal_number_of_generators() == 1
    assert kernel.inclusion().is_in_image(y * e)
    assert not kernel.inclusion().is_in_image(e)
    assert kernel.annihilator() == A.ideal(x)
    assert not kernel.is_free()


def test_the_kernel_of_z_mod_4_onto_z_mod_2_is_z_mod_2_generated_by_2x() -> None:
    """Source: by hand."""
    F = ZZ**1
    source = F / F.submodule([4 * F.module_generator(0)])
    G = ZZ**1
    target = G / G.submodule([2 * G.module_generator(0)])
    x = source.module_generator(0)
    reduction = source.Mor(target)({0: target.module_generator(0)})

    kernel = reduction.kernel()
    assert kernel.cardinality() == 2
    assert tuple(kernel.invariant_factors()) == (2,)
    assert kernel.inclusion().is_in_image(2 * x)
    assert not kernel.inclusion().is_in_image(x)
    assert kernel.inclusion()(kernel.inclusion().lift(2 * x)) == 2 * x
