r"""Archive reconciliation for coordinate matrix helpers of module morphisms.

The archive exposed two deliberately low-level operations: canonical row-span
normalization and construction of the engine matrix group generated by selected
matrices.  They remain coordinate helpers; owned module and group constructions
continue to own the mathematical kernels, images, subgroups, and morphisms.
"""

from sage.matrix.constructor import identity_matrix, matrix
from sage.rings.integer_ring import ZZ
from sage.rings.rational_field import QQ

from dzack_research.preamble.categories.modules.module_morphisms.morphism_matrices import (
    _matrix_group,
    _row_normal_form,
)


def test_row_normal_form_over_a_field_preserves_the_row_space_and_drops_zero_rows() -> None:
    entries = matrix(QQ, [[1, 2, 3], [2, 4, 6], [0, 1, 1]])
    reduced = _row_normal_form(entries)

    assert reduced.nrows() == 2
    assert reduced.row_space() == entries.row_space()
    assert reduced == entries.echelon_form().matrix_from_rows((0, 1))


def test_row_normal_form_over_the_integers_is_the_exact_row_lattice_hermite_form() -> None:
    entries = matrix(ZZ, [[2, 4], [4, 10], [0, 0]])

    assert _row_normal_form(entries) == entries.hermite_form(include_zero_rows=False)
    assert _row_normal_form(entries, include_zero_rows=True) == entries.hermite_form(
        include_zero_rows=True
    )


def test_generated_matrix_group_retains_the_selected_matrix_action() -> None:
    rotation = matrix(ZZ, [[0, -1], [1, 0]])
    negation = -identity_matrix(ZZ, 2)
    group = _matrix_group((rotation, negation))

    assert rotation in group
    assert negation in group
    assert rotation**2 == negation
    assert rotation**4 == identity_matrix(ZZ, 2)
