"""Weil divisor groups."""

from dzack_research.preamble.categories.divisors.divisor_groups import (
    DivisorGroups,
    _divisor_role_specimen,
    _module_in_role,
)
from dzack_research.preamble.categories.modules.framed.framed_free_modules import FramedFreeModules
from dzack_research.preamble.categories.rings.ring_foundation import _own_ring
from dzack_research.preamble.owned_category_bases import Category


class _WeilDivisorConstruction:
    r"""The selected scheme defining one represented Weil-divisor role."""

    def __init__(self, scheme) -> None:
        self._scheme = scheme

    def scheme(self):
        return self._scheme


class _AffineNormalWeilDivisorConstruction(_WeilDivisorConstruction):
    r"""The full Weil-divisor group of a represented normal affine scheme."""


class WeilDivisorGroups(Category):
    def an_object(self):
        return _divisor_role_specimen(self)

    @classmethod
    def _repr_object_names(cls):
        return "Weil divisor groups"

    def super_categories(self):
        return [DivisorGroups()]

    def _call_(self, module, scheme=None):
        from sage.rings.integer_ring import ZZ as SageZZ

        if module not in FramedFreeModules(_own_ring(SageZZ)):
            raise TypeError("Weil divisors are free on specified codimension-one subvarieties")
        return _module_in_role(
            module,
            self,
            "a Weil divisor group requires a represented free-module presentation",
            construction_data=(
                None
                if scheme is None
                else {"_weil_divisor_construction": _WeilDivisorConstruction(scheme)}
            ),
        )

    class ParentMethods:
        def weil_divisor_construction(self):
            r"""Return the selected geometric datum defining this Weil-divisor role."""
            construction = getattr(self, "_weil_divisor_construction", None)
            if construction is None:
                raise TypeError("this Weil-divisor role has no selected scheme")
            return construction

        def divisor_scheme(self):
            return self.weil_divisor_construction().scheme()

        def prime_divisor_locus(self):
            construction = self.weil_divisor_construction()
            if not isinstance(construction, _AffineNormalWeilDivisorConstruction):
                raise TypeError("this Weil-divisor role has no represented full prime-divisor locus")
            return self.module_generating_set()

        def affine_divisor_coordinate_ring(self):
            construction = self.weil_divisor_construction()
            if not isinstance(construction, _AffineNormalWeilDivisorConstruction):
                raise TypeError("this Weil-divisor role is not an affine-normal divisor group")
            return construction.scheme().coordinate_algebra()

        def prime_divisor(self, point):
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            if getattr(point, "parent", lambda: None)() is not spectrum:
                point = spectrum(point)
            if point not in self.prime_divisor_locus():
                raise ValueError("a Weil prime divisor is a height-one point")
            return self.module_generator(point)

        def prime_is_cartier_at(self, prime, point) -> bool:
            r"""Whether the prime Weil divisor ``V(prime)`` is Cartier at ``point``.

            For a height-one prime ``p`` of a normal Noetherian affine domain,
            the corresponding effective prime divisor is locally principal at
            ``q`` exactly when either ``p`` is not contained in ``q`` (so the
            divisor is absent near ``q``), or the localized ideal ``p R_q`` is
            generated by one element.  The latter generator count is computed
            by Nakayama in the existing finite-module localization owner.

            A failure at one point is also an obstruction for the *linear
            equivalence class* to contain any Cartier divisor: principal
            divisors are Cartier, so Cartierness is invariant under adding a
            principal divisor.
            """
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            if getattr(prime, "parent", lambda: None)() is not spectrum:
                prime = spectrum(prime)
            if prime not in self.prime_divisor_locus():
                raise ValueError("the Cartier test requires a height-one prime divisor")
            if getattr(point, "parent", lambda: None)() is not spectrum:
                point = spectrum(point)
            prime_ideal = prime.ideal()
            point_ideal = point.ideal()
            if any(generator not in point_ideal for generator in prime_ideal.ideal_generators()):
                return True
            return int(prime_ideal.local_number_of_generators(point)) == 1

        def multiplicity(self, divisor, point):
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            if getattr(point, "parent", lambda: None)() is not spectrum:
                point = spectrum(point)
            return self.framing_coefficients(divisor).get(point, self.base_ring().zero())

        def principal_divisor(self, rational_function):
            from dzack_research.preamble.categories.divisors.general_divisors import _principal_weil_divisor

            return _principal_weil_divisor(self, rational_function)
