r"""Weil divisor groups."""

from dzack_research.preamble.categories.divisors.divisor_groups import (
    DivisorGroups,
    _affine_line_over_rationals,
    _integers,
)
from dzack_research.preamble.owned_category_bases import Category


class WeilDivisorGroups(Category):
    r"""Weil divisor groups of a scheme, framed by chosen prime divisors.

    An object is the free \(\mathbb{Z}\)-module \(\bigoplus_{P \in S} \mathbb{Z}P\)
    on a set \(S\) of prime divisors of one scheme \(X\).  When \(S\) is the
    whole height-one locus of \(X\) the object is \(\operatorname{Div}(X)\)
    itself (``full_weil_divisor_group`` on an affine scheme); otherwise it is
    the subgroup generated by the chosen prime divisors.  The set \(S\) is
    consumed by the free-module level; this level adds the scheme \(X\).
    """

    def an_object(self):
        r"""\(\operatorname{Div}(\mathbb{A}^1_{\mathbb{Q}})\), on the whole height-one locus."""
        return _affine_line_over_rationals().full_weil_divisor_group()

    @classmethod
    def _repr_object_names(cls):
        return "Weil divisor groups"

    def super_categories(self):
        return [DivisorGroups()]

    def _call_(self, scheme, prime_divisors):
        r"""\(\bigoplus_{P \in S} \mathbb{Z}P\) for the set ``prime_divisors`` of prime divisors of ``scheme``."""
        return _integers()._fresh_free_module_on(
            prime_divisors,
            _extra_categories=(self,),
            _extra_construction_data={"divisor_scheme": scheme},
        )

    class ParentMethods:
        def __init__(self, divisor_scheme, **rest) -> None:
            self._divisor_scheme = divisor_scheme
            super().__init__(**rest)

        def divisor_scheme(self):
            r"""The scheme whose Weil divisors this group is framed by."""
            return self._divisor_scheme

        def prime_divisor_locus(self):
            r"""The prime divisors of the scheme that frame this group."""
            return self.module_generating_set()

        def affine_divisor_coordinate_ring(self):
            r"""The coordinate algebra of the affine scheme whose prime divisors frame this group."""
            from dzack_research.preamble.categories.schemes.schemes import Schemes

            scheme = self.divisor_scheme()
            assert scheme in Schemes(scheme.scheme_base_ring()).Affine(), (
                f"{self} has no affine coordinate ring: its scheme {scheme} is not known to "
                f"be affine"
            )
            return scheme.coordinate_algebra()

        def prime_divisor(self, point):
            r"""The generator \(1 \cdot P\) of the prime divisor at the height-one point ``point``."""
            point = self.affine_divisor_coordinate_ring().spectrum()(point)
            assert point in self.prime_divisor_locus(), (
                f"{point} is not a prime divisor of {self.divisor_scheme()}: a prime Weil "
                f"divisor is a point of height one, and {point} is not one"
            )
            return self.module_generator(point)

        def prime_is_cartier_at(self, prime, point) -> bool:
            r"""Whether the prime Weil divisor ``V(prime)`` is Cartier at ``point``.

            For a height-one prime ``p`` of a normal Noetherian affine domain,
            the corresponding effective prime divisor is locally principal at
            ``q`` exactly when either ``p`` is not contained in ``q`` (so the
            divisor is absent near ``q``), or the localized ideal ``p R_q`` is
            generated by one element.  The latter generator count is computed
            by Nakayama in the existing finite-module localization owner.

            A failure at one point is also an obstruction for the *linear
            equivalence class* to contain any Cartier divisor: principal
            divisors are Cartier, so Cartierness is invariant under adding a
            principal divisor.
            """
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            prime = spectrum(prime)
            assert prime in self.prime_divisor_locus(), (
                f"cannot test whether {prime} is Cartier at {point}: {prime} is not a prime "
                f"divisor of {self.divisor_scheme()}, i.e. not a point of height one"
            )
            point = spectrum(point)
            prime_ideal = prime.ideal()
            point_ideal = point.ideal()
            if any(generator not in point_ideal for generator in prime_ideal.ideal_generators()):
                return True
            return int(prime_ideal.local_number_of_generators(point)) == 1

        def multiplicity(self, divisor, point):
            r"""The coefficient of the prime divisor at ``point`` in ``divisor``."""
            point = self.affine_divisor_coordinate_ring().spectrum()(point)
            return self(divisor).to_vector()(point)

        def principal_divisor(self, rational_function):
            r"""\(\operatorname{div}(f)\) of a nonzero rational function on the affine scheme."""
            from dzack_research.preamble.categories.divisors.general_divisors import _principal_weil_divisor

            return _principal_weil_divisor(self, rational_function)


__all__ = ["WeilDivisorGroups"]
