"""Weil divisor groups."""

from dzack_research.preamble.categories.divisors.divisor_groups import (
    DivisorGroups,
    _integers,
    _module_in_role,
)
from dzack_research.preamble.categories.modules.framed.framed_free_modules import FramedFreeModules
from dzack_research.preamble.categories.schemes.schemes import Schemes
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.owned_category_bases import Category


class WeilDivisorGroups(Category):
    r"""Weil divisor groups \(\operatorname{Div}(X)\) framed by chosen prime divisors.

    An object is the free \(\mathbb{Z}\)-module on a chosen set of prime
    divisors of one scheme \(X\), its datum.  The framing is the whole
    height-one locus of \(X\) when the object was built on it
    (``Schemes.full_weil_divisor_group``), and a chosen finite family of
    prime divisors otherwise; every operation below is stated from the
    scheme and asks the framing for the prime divisors it names.
    """

    def an_object(self):
        r"""The divisor group of the base scheme's affine line, framed by one prime divisor."""
        integers = _integers()
        return self(
            integers.free_module(finite_ordered_set(("D",))),
            scheme=Schemes(integers).an_object(),
        )

    @classmethod
    def _repr_object_names(cls):
        return "Weil divisor groups"

    def super_categories(self):
        return [DivisorGroups()]

    def _call_(self, module, scheme):
        assert module in FramedFreeModules(_integers()), (
            "Weil divisors are free on specified codimension-one subvarieties"
        )
        return _module_in_role(module, self, divisor_scheme=scheme)

    class ParentMethods:
        def __init__(self, divisor_scheme, **rest) -> None:
            self._divisor_scheme = divisor_scheme
            super().__init__(**rest)

        def divisor_scheme(self):
            r"""The scheme whose Weil divisors this group presents."""
            return self._divisor_scheme

        def prime_divisor_locus(self):
            r"""The height-one points of the affine scheme, the prime divisors of \(X\)."""
            return self.affine_divisor_coordinate_ring().spectrum().condition_set(
                lambda point: point.height() == 1
            )

        def affine_divisor_coordinate_ring(self):
            scheme = self.divisor_scheme()
            assert scheme in Schemes(scheme.scheme_base_ring()).Affine(), (
                "the prime divisors of a Weil divisor group are read off an affine "
                "coordinate ring; this group's scheme is not affine"
            )
            return scheme.coordinate_algebra()

        def prime_divisor(self, point):
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            point = spectrum(point)
            assert point in self.prime_divisor_locus(), (
                "a Weil prime divisor is a height-one point"
            )
            return self.module_generator(point)

        def prime_is_cartier_at(self, prime, point) -> bool:
            r"""Whether the prime Weil divisor ``V(prime)`` is Cartier at ``point``.

            For a height-one prime ``p`` of a normal Noetherian affine domain,
            the corresponding effective prime divisor is locally principal at
            ``q`` exactly when either ``p`` is not contained in ``q`` (so the
            divisor is absent near ``q``), or the localized ideal ``p R_q`` is
            generated by one element.  The latter generator count is computed
            by Nakayama in the existing finite-module localization owner.

            A failure at one point is also an obstruction for the *linear
            equivalence class* to contain any Cartier divisor: principal
            divisors are Cartier, so Cartierness is invariant under adding a
            principal divisor.
            """
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            prime = spectrum(prime)
            assert prime in self.prime_divisor_locus(), (
                "the Cartier test requires a height-one prime divisor"
            )
            point = spectrum(point)
            prime_ideal = prime.ideal()
            point_ideal = point.ideal()
            if any(generator not in point_ideal for generator in prime_ideal.ideal_generators()):
                return True
            return int(prime_ideal.local_number_of_generators(point)) == 1

        def multiplicity(self, divisor, point):
            spectrum = self.affine_divisor_coordinate_ring().spectrum()
            point = spectrum(point)
            return self.framing_coefficients(divisor).get(point, self.base_ring().zero())

        def principal_divisor(self, rational_function):
            from dzack_research.preamble.categories.divisors.general_divisors import _principal_weil_divisor

            return _principal_weil_divisor(self, rational_function)
