"""Modules equipped with bilinear or quadratic forms."""

from dzack_research.preamble.categories.modules.framed.formed.discriminant_modules import (
    DiscriminantBilinearModules,
    DiscriminantModule,
    DiscriminantModules,
    DiscriminantQuadraticModules,
)
from dzack_research.preamble.categories.modules.framed.formed.form_modules import (
    BilinearForm,
    BilinearFormModules,
    FiberedFormedModuleHomset,
    FiberedFormedModuleMorphism,
    FinitelyGeneratedFormModules,
    FinitelyGeneratedFreeFormModules,
    FinitelyPresentedBilinearFormModules,
    FinitelyPresentedFormModules,
    FinitelyPresentedQuadraticFormModules,
    FormedModuleHomset,
    FormedModuleMorphism,
    FormedModules,
    FormEmbedding,
    FormModule,
    FormModules,
    FreeFormModules,
    PairedModules,
    QuadraticForm,
    QuadraticFormModules,
    SymmetricBilinearFormModules,
    fibered_formed_module_homset,
    form_embedding,
    formed_module_homset,
    is_form_morphism,
)
from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
    TorsionBilinearFormModules,
    TorsionFormIsometry,
    TorsionQuadraticFormModules,
)

__all__ = [
    "BilinearForm",
    "BilinearFormModules",
    "DiscriminantBilinearModules",
    "DiscriminantModule",
    "DiscriminantModules",
    "DiscriminantQuadraticModules",
    "FinitelyGeneratedFormModules",
    "FinitelyGeneratedFreeFormModules",
    "FinitelyPresentedBilinearFormModules",
    "FinitelyPresentedFormModules",
    "FinitelyPresentedQuadraticFormModules",
    "FormModule",
    "FormEmbedding",
    "FormedModuleHomset",
    "FormedModuleMorphism",
    "FiberedFormedModuleHomset",
    "FiberedFormedModuleMorphism",
    "FormModules",
    "FormedModules",
    "FreeFormModules",
    "PairedModules",
    "QuadraticForm",
    "QuadraticFormModules",
    "SymmetricBilinearFormModules",
    "TorsionBilinearFormModules",
    "TorsionFormIsometry",
    "TorsionQuadraticFormModules",
    "formed_module_homset",
    "form_embedding",
    "fibered_formed_module_homset",
    "is_form_morphism",
]
