'Modules equipped with bilinear or quadratic forms.'

from importlib import import_module as _import_module

_EXPORTS = {'DiscriminantBilinearModules': ('dzack_research.preamble.categories.modules.framed.formed.discriminant_modules',
                                 'DiscriminantBilinearModules'),
 'DiscriminantModule': ('dzack_research.preamble.categories.modules.framed.formed.discriminant_modules',
                        'DiscriminantModule'),
 'DiscriminantModules': ('dzack_research.preamble.categories.modules.framed.formed.discriminant_modules',
                         'DiscriminantModules'),
 'DiscriminantQuadraticModules': ('dzack_research.preamble.categories.modules.framed.formed.discriminant_modules',
                                  'DiscriminantQuadraticModules'),
 'BilinearForm': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                  'BilinearForm'),
 'BilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                         'BilinearFormModules'),
 'FiberedFormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                               'FiberedFormedModuleHomset'),
 'FiberedFormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                 'FiberedFormedModuleMorphism'),
 'FinitelyGeneratedFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                  'FinitelyGeneratedFormModules'),
 'FinitelyGeneratedFreeFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                      'FinitelyGeneratedFreeFormModules'),
 'FinitelyPresentedBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                          'FinitelyPresentedBilinearFormModules'),
 'FinitelyPresentedFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                  'FinitelyPresentedFormModules'),
 'FinitelyPresentedQuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                           'FinitelyPresentedQuadraticFormModules'),
 'FormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                        'FormedModuleHomset'),
 'FormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                          'FormedModuleMorphism'),
 'FormedModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                   'FormedModules'),
 'FormEmbedding': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                   'FormEmbedding'),
 'FormModule': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                'FormModule'),
 'FormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                 'FormModules'),
 'FreeFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                     'FreeFormModules'),
 'PairedModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                   'PairedModules'),
 'QuadraticForm': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                   'QuadraticForm'),
 'QuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                          'QuadraticFormModules'),
 'SymmetricBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                  'SymmetricBilinearFormModules'),
 'fibered_formed_module_homset': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                                  'fibered_formed_module_homset'),
 'form_embedding': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                    'form_embedding'),
 'formed_module_homset': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                          'formed_module_homset'),
 'is_form_morphism': ('dzack_research.preamble.categories.modules.framed.formed.form_modules',
                      'is_form_morphism'),
 'TorsionBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules',
                                'TorsionBilinearFormModules'),
 'TorsionFormIsometry': ('dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules',
                         'TorsionFormIsometry'),
 'TorsionQuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules',
                                 'TorsionQuadraticFormModules')}

__all__ = ['BilinearForm',
 'BilinearFormModules',
 'DiscriminantBilinearModules',
 'DiscriminantModule',
 'DiscriminantModules',
 'DiscriminantQuadraticModules',
 'FinitelyGeneratedFormModules',
 'FinitelyGeneratedFreeFormModules',
 'FinitelyPresentedBilinearFormModules',
 'FinitelyPresentedFormModules',
 'FinitelyPresentedQuadraticFormModules',
 'FormModule',
 'FormEmbedding',
 'FormedModuleHomset',
 'FormedModuleMorphism',
 'FiberedFormedModuleHomset',
 'FiberedFormedModuleMorphism',
 'FormModules',
 'FormedModules',
 'FreeFormModules',
 'PairedModules',
 'QuadraticForm',
 'QuadraticFormModules',
 'SymmetricBilinearFormModules',
 'TorsionBilinearFormModules',
 'TorsionFormIsometry',
 'TorsionQuadraticFormModules',
 'formed_module_homset',
 'form_embedding',
 'fibered_formed_module_homset',
 'is_form_morphism']

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
