r"""Discriminant modules and their quotient-valued forms."""

from dzack_research.preamble.categories.modules.pure.modules import ModuleSubobjects
from sage.categories.category import Category
from dzack_research.preamble.categories.modules.pure.modules import ModulesWithChosenFinitePresentation

from sage.misc.cachefunc import cached_method
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.modules.framed.formed.form_modules import (
    FormModules,
    TorsionBilinearFormModules,
    TorsionQuadraticFormModules,
)
from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
    _forms_are_isomorphic,
    _p_adic_jordan_decomposition,
    _p_adic_jordan_form,
    _torsion_form_automorphism_group,
    _p_adic_jordan_module_generators,
    _torsion_form_isometry,
)
from dzack_research.preamble.categories.modules.framed.fraction_field_quotients import FractionFieldQuotients
from dzack_research.preamble.categories.modules.pure.modules import Modules
from dzack_research.preamble.categories.rings.ring_foundation import _owned_engine_element
from dzack_research.preamble.categories.rings.ring_foundation import (
    OwnedCategoryOverBaseRing,
    Zmod,
    _engine_element,
    _engine_ring,
)
from dzack_research.preamble.categories.sets.finite_ordered_sets import (
    FiniteOrderedSets,
    finite_ordered_set,
)
from dzack_research.preamble.categories.sets.indexed_families import (
    finite_indexed_family,
    indexed_family,
)
from dzack_research.preamble.categories.sets.set_categories import Sets


class DiscriminantModules(OwnedCategoryOverBaseRing):
    r"""Cokernels ``A_L = coker(L -> L^#)`` of nondegenerate finite lattices."""

    def an_object(self):
        r"""The discriminant group of U with its induced form."""
        from dzack_research.preamble.categories.lattices import Lattices

        return Lattices(self.base_ring())("U").discriminant_group()

    @classmethod
    def _repr_object_names(cls):
        return "discriminant modules"

    def super_categories(self):
        return [Modules(self.base_ring()).FinitelyPresented().Torsion(), ModuleSubobjects(self.base_ring())]

    class ParentMethods:
        def __init__(self, source_lattice, dual_lattice, **rest) -> None:
            self._source_lattice = source_lattice
            self._dual_lattice = dual_lattice
            super().__init__(**rest)

        def source_lattice(self):
            return self._source_lattice

        def dual_lattice(self):
            r"""Return the selected metric dual ``L^#`` covering this quotient."""
            return self._dual_lattice

        def cover(self):
            r"""Return the metric dual lattice whose quotient gives this discriminant module."""
            return self.dual_lattice()

        def correlation(self):
            r"""Return ``L -> L^#``, the presentation defining the discriminant quotient."""
            return self.source_lattice().correlation_morphism()

        @cached_method
        def projection(self):
            r"""Return the quotient map ``L^# -> A_L`` on the selected dual basis."""

            dual_lattice = self.dual_lattice()
            return dual_lattice.module_category().Mor(dual_lattice, self)({label: self.module_generator(label) for label in self.module_generating_set()})

        def discriminant_class(self, dual_lattice_element):
            r"""Return the class of an element of ``L^#`` in ``A_L``."""
            if dual_lattice_element not in self.dual_lattice():
                raise TypeError(
                    f"a class in the discriminant group {self} is the image of an element of the dual lattice "
                    f"{self.dual_lattice()}, but {dual_lattice_element} is not in it"
                )
            return self.projection()(dual_lattice_element)

        def subgroup_on(self, generators):
            r"""Return the finite subgroup generated by ``generators`` with its inclusion."""
            return _discriminant_subgroup(self, generators)

        @cached_method
        def subgroups(self):
            r"""Return all finite subgroups, exhaustively, for the represented finite module."""
            return _all_discriminant_subgroups(self)

        def primary_components(self):
            r"""Return the family \(p\mapsto A_p\) over the primes dividing \(|A|\)."""

            components = {}
            smith_generators = tuple(self.smith_form_module_generators())
            invariants = tuple(abs(n) for n in self.invariant_factors())
            primes = sorted(
                {prime for order in invariants for prime in order.prime_divisors()}
            )
            for prime in primes:
                generators = []
                for order, generator in zip(
                    invariants, smith_generators, strict=True
                ):
                    valuation = int(order.valuation(prime))
                    if valuation:
                        primary_order = prime**valuation
                        coefficient = order // primary_order
                        generators.append(
                            self.scalar_multiple(coefficient, generator)
                        )
                components[prime] = self.subgroup_on(generators)
            # The primes are the index set, and A_p the value there: two primes
            # may carry isomorphic subgroups, which a set of subgroups would
            # collapse.
            index = finite_ordered_set(tuple(primes))
            return indexed_family(
                index,
                lambda prime: components[prime],
                name=f"Primary components of {self}",
            )

        def primary_part(self, prime):
            r"""Return the ``prime``-primary subgroup ``A_prime <= A``.

            This is the single-prime view of :meth:`primary_components`.  If
            ``prime`` does not divide ``|A|`` the primary subgroup is the zero
            subgroup, not a missing lookup.
            """
            prime = SageZZ(prime)
            components = self.primary_components()
            if prime in components.index_set():
                return components[prime]
            return self.subgroup_on(())

        def dual_lattice_lift(self, element):
            r"""Return a representative of ``element`` in the selected metric dual ``L^#``.

            Elements are engine elements, so the lift is a parent operation:
            a set-theoretic section of :meth:`projection` on the chosen framing.
            """

            coordinates = self.framing_morphism().lift(self(element))
            return self.dual_lattice().linear_combination(
                {label: coordinates(label) for label in coordinates.support().domain()}
            )


class DiscriminantBilinearModules(OwnedCategoryOverBaseRing):
    r"""Discriminant modules with ``K/R``-valued bilinear form."""

    def an_object(self):
        r"""The discriminant group of U, bilinear."""
        from dzack_research.preamble.categories.lattices import Lattices

        return Lattices(self.base_ring())("U").discriminant_group()

    @classmethod
    def _repr_object_names(cls):
        return "discriminant bilinear modules"

    def super_categories(self):

        return [
            DiscriminantModules(self.base_ring()),
            TorsionBilinearFormModules(self.base_ring()),
        ]

    class ParentMethods:
        def __init__(self, bilinear_value_module, **rest) -> None:
            self._preamble_bilinear_value_module = bilinear_value_module
            super().__init__(**rest)

        def bilinear_value_module(self):
            return self._preamble_bilinear_value_module

        def value_module(self):
            return self.bilinear_value_module()

        def b(self, left, right):
            if left not in self or right not in self:
                raise TypeError(
                    f"the discriminant form on {self} pairs two of its elements, but {left} or {right} is not in {self}"
                )
            value = self.dual_lattice().b(self.dual_lattice_lift(left), self.dual_lattice_lift(right))
            return self.bilinear_value_module()(value)

        def orthogonal_subgroup(self, subgroup):
            r"""Return ``H^perp`` for a subgroup ``H <= A``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError(
                    f"the orthogonal complement in {self} is taken of a subgroup of {self}, but {subgroup} "
                    f"is a subgroup of {subgroup.ambient_discriminant_module()}"
                )

            generators = subgroup.embedded_module_generators()
            zero = self.bilinear_value_module().zero()
            elements = self.elements().filtered(
                lambda element: all(
                    self.b(element, generator) == zero
                    for generator in generators
                ),
            )
            return self.subgroup_on(elements)

        def form_vanishes_on(self, elements) -> bool:
            r"""Return whether the bilinear form vanishes on all pairs."""
            zero = self.bilinear_value_module().zero()
            return all(
                self.b(left, right) == zero
                for left in elements
                for right in elements
            )

        @cached_method
        def isotropic_subgroups(self):
            r"""Return all subgroups on which the bilinear form vanishes."""
            return self.subgroups().filtered(
                lambda subgroup: self.form_vanishes_on(subgroup.embedded_elements()),
            )

        @cached_method
        def maximal_isotropic_subgroups(self):
            r"""Return the isotropic subgroups maximal under inclusion."""
            isotropic = self.isotropic_subgroups()

            def is_maximal(subgroup):
                subgroup_order = int(subgroup.cardinality())
                return not any(
                    int(larger.cardinality()) > subgroup_order
                    and all(
                        element in larger
                        for element in subgroup.embedded_elements()
                    )
                    for larger in isotropic
                )

            return isotropic.filtered(is_maximal)

        @cached_method
        def lagrangian_subgroups(self):
            r"""Return totally isotropic ``H`` with ``|H|^2=|A|``."""
            order = int(self.cardinality())
            return self.isotropic_subgroups().filtered(
                lambda subgroup: int(subgroup.cardinality()) ** 2 == order,
            )

        def is_metabolic(self) -> bool:
            return int(self.lagrangian_subgroups().cardinality()) != 0

        def metabolizer(self):
            r"""Return one Lagrangian subgroup, refusing a nonmetabolic form."""
            lagrangians = self.lagrangian_subgroups()
            if int(lagrangians.cardinality()) == 0:
                raise ValueError(f"the bilinear discriminant form {self} is not metabolic: it has no Lagrangian subgroup")
            return lagrangians[0]

        def associated_quadratic_form(self):
            r"""Return the canonical quadratic refinement when the source lattice is even.

            A bare bilinear torsion form does not determine a quadratic
            refinement.  A discriminant bilinear form does retain its source
            lattice, and for an even source lattice that lattice canonically
            supplies ``q : A_L -> K/2R``.  The construction therefore goes
            back through the lattice rather than reinterpreting entries of a
            ``K/R``-valued Gram matrix.
            """
            lattice = self.source_lattice()
            if not lattice.is_even():
                raise ValueError(
                    f"the discriminant quadratic form of {self} requires an even lattice, "
                    f"but its lattice {lattice} is not even"
                )
            return lattice.discriminant_quadratic_form()

        def orthogonal_quotient(self, subgroup):
            r"""Return ``H^perp/H`` with its descended bilinear form.

            This requires ``H`` to be totally isotropic for ``b``.  The
            quotient is the literal cokernel of ``H -> H^perp`` and the form
            is descended from the restriction to ``H^perp``.
            """
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError(
                    f"H^perp/H in {self} is taken for a subgroup H of {self}, but {subgroup} "
                    f"is a subgroup of {subgroup.ambient_discriminant_module()}"
                )
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError(
                    f"H^perp/H in {self} requires H totally isotropic for b, but b does not vanish on {subgroup}"
                )
            perpendicular = self.orthogonal_subgroup(subgroup)
            quotient = _subquotient_module(subgroup, perpendicular)
            generators = tuple(perpendicular.module_generators())
            gram = tuple(tuple(perpendicular.b(left, right) for right in generators) for left in generators)

            return TorsionBilinearFormModules(self.base_ring()).from_module(quotient, gram, self.bilinear_value_module())

        def overlattice_from_isotropic_subobject(self, subgroup):
            r"""Return ``L -> L'`` for bilinear-isotropic glue ``H <= A_L``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError(
                    f"an overlattice of {self.source_lattice()} is glued from a subgroup of {self}, but "
                    f"{subgroup} is a subgroup of {subgroup.ambient_discriminant_module()}"
                )
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError(
                    f"an integral overlattice of {self.source_lattice()} needs a subgroup isotropic for b, "
                    f"but b does not vanish on {subgroup}"
                )
            return self.source_lattice().overlattice(*tuple(subgroup.embedded_module_generators()))

        def discriminant_form_of_overlattice(self, subgroup):
            r"""Return the Nikulin subquotient ``H^perp/H`` for the glued lattice."""
            return self.orthogonal_quotient(subgroup)

        def pontryagin_dual_identification(self):
            r"""Return ``A -> Hom(A,QQ/ZZ)``, ``x |-> b(x,-)``.

            A discriminant pairing of a nondegenerate lattice is perfect, so
            this map is the canonical Pontryagin-dual identification rather
            than merely a homomorphism into the character group.
            """
            from sage.categories.morphism import SetMorphism


            characters = self.module_category().Mor(self, self.bilinear_value_module())

            def character(element):
                element = self(element)
                return characters(
                    {
                        label: self.b(element, self.module_generator(label))
                        for label in self.module_generating_set()
                    }
                )

            return SetMorphism(Sets().Mor(self, characters), character)

        @cached_method
        def invariant_factor_form(self):
            r"""Return the bilinear isometry to a normalized framed torsion form.

            The discriminant module itself remains the literal cokernel
            ``L^# / L`` on the selected dual-basis classes.  The codomain is a
            different formed module on the non-unit Smith generators.
            """

            generators = tuple(self.module_generators())
            gram = tuple(
                tuple(self.b(left, right) for right in generators)
                for left in generators
            )
            formed = TorsionBilinearFormModules(self.base_ring()).from_module(
                self,
                gram,
                self.bilinear_value_module(),
            )
            normalization = formed.invariant_factor_form()
            forward, inverse = _through_formed_copy(self, formed, normalization)
            return _torsion_form_isometry(
                forward,
                inverse,
                quadratic=False,
            )

        def p_adic_jordan_decomposition(self):

            return _p_adic_jordan_decomposition(self, quadratic=False)

        def p_adic_jordan_module_generators(self):

            return _p_adic_jordan_module_generators(self, quadratic=False)

        def p_adic_jordan_form(self):

            return _p_adic_jordan_form(self, quadratic=False)

        normal_form = p_adic_jordan_form

        def is_isomorphic(self, other) -> bool:


            if other not in TorsionBilinearFormModules(self.base_ring()):
                return False
            return _forms_are_isomorphic(self, other, quadratic=False)

        is_isometric_to = is_isomorphic

        def is_anti_isometric(self, other) -> bool:

            if other not in TorsionBilinearFormModules(self.base_ring()):
                return False
            return self.is_isomorphic(other.twist(-1))

        @cached_method
        def automorphism_group(self):
            r"""Return ``O(A,b)`` as live form automorphisms."""

            return _torsion_form_automorphism_group(self, quadratic=False)

        def orthogonal_group(self):
            return self.automorphism_group()

        def O(self):  # noqa: E743 - standard mathematical notation O(A,b)
            return self.automorphism_group()


class DiscriminantQuadraticModules(OwnedCategoryOverBaseRing):
    r"""Even-lattice discriminant modules with quadratic form in ``K/2R``."""

    def an_object(self):
        r"""The discriminant group of U, quadratic."""
        from dzack_research.preamble.categories.lattices import Lattices

        return Lattices(self.base_ring())("U").discriminant_group()

    @classmethod
    def _repr_object_names(cls):
        return "discriminant quadratic modules"

    def super_categories(self):

        return [
            DiscriminantBilinearModules(self.base_ring()),
            TorsionQuadraticFormModules(self.base_ring()),
        ]

    class ParentMethods:
        def __init__(self, quadratic_value_module, **rest) -> None:
            self._preamble_quadratic_value_module = quadratic_value_module
            super().__init__(**rest)

        def quadratic_value_module(self):
            return self._preamble_quadratic_value_module

        def value_module(self):
            return self.quadratic_value_module()

        def twist(self, scalar):
            r"""Return the same discriminant module equipped with ``scalar*q``."""
            return TorsionQuadraticFormModules(self.base_ring()).twist_functor(scalar)(self)

        def q(self, element):
            if element not in self:
                raise TypeError(
                    f"the discriminant quadratic form on {self} is defined on its elements, but {element} is not in {self}"
                )
            return self.quadratic_value_module()(self.dual_lattice().norm(self.dual_lattice_lift(element)))

        @cached_method
        def isotropic_elements(self):
            r"""Return the classes on which the quadratic form vanishes."""

            zero = self.quadratic_value_module().zero()
            return finite_ordered_set(self.elements()).filtered(
                lambda element: self.q(element) == zero,
            )

        def is_anisotropic(self) -> bool:
            return len(self.isotropic_elements()) == 1

        @cached_method
        def isotropic_subgroups(self):
            r"""Return all subgroups on which ``q`` vanishes identically."""

            zero = self.quadratic_value_module().zero()
            return self.subgroups().filtered(
                lambda subgroup: all(
                    self.q(element) == zero
                    for element in subgroup.embedded_elements()
                ),
            )

        @cached_method
        def maximal_isotropic_subgroups(self):
            r"""Return the quadratic-isotropic subgroups maximal under inclusion."""
            isotropic = self.isotropic_subgroups()

            def is_maximal(subgroup):
                subgroup_order = int(subgroup.cardinality())
                return not any(
                    int(larger.cardinality()) > subgroup_order
                    and all(
                        element in larger
                        for element in subgroup.embedded_elements()
                    )
                    for larger in isotropic
                )

            return isotropic.filtered(is_maximal)

        @cached_method
        def lagrangian_subgroups(self):
            r"""Return isotropic ``H`` with ``|H|^2=|A|``."""

            order = int(self.cardinality())
            return self.isotropic_subgroups().filtered(
                lambda subgroup: int(subgroup.cardinality()) ** 2 == order,
            )

        def is_metabolic(self) -> bool:
            return int(self.lagrangian_subgroups().cardinality()) != 0

        def metabolizer(self):
            r"""Return one Lagrangian subgroup, refusing a nonmetabolic form."""
            lagrangians = self.lagrangian_subgroups()
            if int(lagrangians.cardinality()) == 0:
                raise ValueError(f"the quadratic discriminant form {self} is not metabolic: it has no Lagrangian subgroup")
            return lagrangians[0]

        def form_vanishes_on(self, elements) -> bool:
            r"""Return whether ``q`` vanishes on every supplied element."""
            zero = self.quadratic_value_module().zero()
            return all(self.q(element) == zero for element in elements)

        @cached_method
        def associated_bilinear_form(self):
            r"""Return the ``QQ/ZZ``-valued polarization as a distinct object.

            Forgetting the quadratic refinement must forget structure: the
            resulting bilinear object has the same presented finite module and
            pairing ``b`` but does not remain in the quadratic category.  This
            distinction is what allows ``O(A,q)`` to be strictly smaller than
            ``O(A,b)``.
            """

            generators = tuple(self.module_generators())
            gram = tuple(
                tuple(self.b(left, right) for right in generators)
                for left in generators
            )
            unformed = self.unformed_module()
            return FormModules(unformed.base_ring())(
                unformed.bilinear_forms(self.bilinear_value_module())(gram),
                _extra_categories=(
                    TorsionBilinearFormModules(self.base_ring()),
                    DiscriminantModules(self.base_ring()),
                    DiscriminantBilinearModules(self.base_ring()),
                ),
                _extra_construction_data={
                    "source_lattice": self.source_lattice(),
                    "dual_lattice": self.dual_lattice(),
                    "bilinear_value_module": self.bilinear_value_module(),
                },
            )

        def orthogonal_quotient(self, subgroup):
            r"""Return ``H^perp/H`` with its descended quadratic form."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError(
                    f"H^perp/H in {self} is taken for a subgroup H of {self}, but {subgroup} "
                    f"is a subgroup of {subgroup.ambient_discriminant_module()}"
                )
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError(
                    f"H^perp/H in {self} requires H isotropic for q, but q does not vanish on {subgroup}"
                )
            perpendicular = DiscriminantBilinearModules.ParentMethods.orthogonal_subgroup(self, subgroup)
            quotient = _subquotient_module(subgroup, perpendicular)
            generators = tuple(perpendicular.module_generators())
            quadratic_values = self.quadratic_value_module()
            gram = []
            for i, left in enumerate(generators):
                row = []
                for j, right in enumerate(generators):
                    if i == j:
                        row.append(perpendicular.q(left))
                    else:
                        bilinear_value = perpendicular.b(left, right)
                        row.append(quadratic_values(self.bilinear_value_module().lift(bilinear_value)))
                gram.append(tuple(row))

            return TorsionQuadraticFormModules(self.base_ring()).from_module(quotient, tuple(gram), quadratic_values)

        def overlattice_from_isotropic_subobject(self, subgroup):
            r"""Return ``L -> L'`` for q-isotropic glue ``H <= A_L``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError(
                    f"an overlattice of {self.source_lattice()} is glued from a subgroup of {self}, but "
                    f"{subgroup} is a subgroup of {subgroup.ambient_discriminant_module()}"
                )
            if not subgroup.is_isotropic():
                raise ValueError(
                    f"an even overlattice of {self.source_lattice()} needs a subgroup isotropic for q, "
                    f"but q does not vanish on {subgroup}"
                )
            return self.source_lattice().overlattice(*tuple(subgroup.embedded_module_generators()))

        def discriminant_form_of_overlattice(self, subgroup):
            r"""Return ``H^perp/H``, the discriminant form of the glued overlattice."""
            return self.orthogonal_quotient(subgroup)

        @cached_method
        def invariant_factor_form(self):
            r"""Return the quadratic isometry to invariant-factor framing.

            The source remains the literal discriminant cokernel with the
            classes of the selected dual basis as its framing.  The target is
            a distinct finite quadratic module whose framing consists only of
            the non-unit Smith factors.
            """

            generators = tuple(self.module_generators())
            quadratic_values = self.quadratic_value_module()
            gram = []
            for i, left in enumerate(generators):
                row = []
                for j, right in enumerate(generators):
                    if i == j:
                        row.append(self.q(left))
                    else:
                        row.append(
                            quadratic_values(
                                self.bilinear_value_module().lift(
                                    self.b(left, right)
                                )
                            )
                        )
                gram.append(tuple(row))
            formed = TorsionQuadraticFormModules(self.base_ring()).from_module(
                self,
                tuple(gram),
                quadratic_values,
            )
            normalization = formed.invariant_factor_form()
            forward, inverse = _through_formed_copy(self, formed, normalization)
            return _torsion_form_isometry(
                forward,
                inverse,
                quadratic=True,
            )

        def p_adic_jordan_decomposition(self):

            return _p_adic_jordan_decomposition(self, quadratic=True)

        def p_adic_jordan_module_generators(self):

            return _p_adic_jordan_module_generators(self, quadratic=True)

        def p_adic_jordan_form(self):

            return _p_adic_jordan_form(self, quadratic=True)

        normal_form = p_adic_jordan_form

        def is_isomorphic(self, other) -> bool:


            if other not in TorsionQuadraticFormModules(self.base_ring()):
                return False
            return _forms_are_isomorphic(self, other, quadratic=True)

        is_isometric_to = is_isomorphic

        def is_anti_isometric(self, other) -> bool:

            if other not in TorsionQuadraticFormModules(self.base_ring()):
                return False
            return self.is_isomorphic(other.twist(-1))

        @cached_method
        def automorphism_group(self):
            r"""Return ``O(A,q)`` as live quadratic-form automorphisms."""

            return _torsion_form_automorphism_group(self, quadratic=True)

        def orthogonal_group(self):
            return self.automorphism_group()

        def O(self):  # noqa: E743 - standard mathematical notation O(A,q)
            return self.automorphism_group()

        @cached_method
        def brown_invariant(self):
            r"""Return the Brown invariant in ``ZZ/8ZZ`` from the exact Gauss sum.

            With the present convention ``q:A -> QQ/2ZZ``, the normalized
            Gauss sum is

            ``|A|^(-1/2) * sum_x exp(pi*i*q(x)) = exp(pi*i*Br(q)/4)``.

            Discriminant forms are nondegenerate, so the left side is an
            eighth root of unity.  The computation takes place in ``QQbar``;
            equality there is exact algebraic-number equality, not a floating
            phase comparison.
            """
            from sage.rings.qqbar import QQbar

            total = QQbar.zero()
            for element in self.elements():
                lifted = self.quadratic_value_module().lift(self.q(element))
                value = _engine_element(lifted.parent(), lifted)
                denominator = value.denominator()
                numerator = value.numerator()
                total += QQbar.zeta(2 * denominator) ** numerator
            scale = QQbar(int(self.cardinality())).sqrt()
            zeta8 = QQbar.zeta(8)
            residues = Zmod(8)
            for residue in range(8):
                if total == scale * zeta8**residue:
                    return residues(residue)
            raise ArithmeticError(
                f"the Brown invariant of {self} is undefined: its normalized Gauss sum {total / scale} "
                "is not an eighth root of unity, so the form is degenerate"
            )

    class ElementMethods:
        def is_characteristic(self) -> bool:
            r"""Return whether this class is characteristic for the quadratic form.

            A class ``v`` is characteristic when

            ``q(x) - b(x, v)`` lies in ``ZZ`` for every ``x`` in the
            discriminant group.  The quadratic and bilinear values live in
            quotient value modules, so the comparison is made on their
            selected rational lifts exactly as in the archived contract.
            """
            parent = self.parent()
            return all(
                parent.q(element).lift() - parent.b(element, self).lift()
                in SageZZ
                for element in parent.elements()
            )


class DiscriminantSubmodules(OwnedCategoryOverBaseRing):
    r"""Finite subgroups of a discriminant module with the restricted form."""

    @classmethod
    def _repr_object_names(cls):
        return "discriminant submodules"

    def super_categories(self):
        return [Modules(self.base_ring()).FinitelyPresented().Torsion()]

    class ParentMethods:
        def __init__(
            self,
            ambient_discriminant_module,
            discriminant_engine_subgroup,
            **rest,
        ) -> None:
            self._preamble_ambient_discriminant_module = ambient_discriminant_module
            self._preamble_discriminant_engine_subgroup = discriminant_engine_subgroup
            super().__init__(**rest)

        def ambient_discriminant_module(self):
            return self._preamble_ambient_discriminant_module

        @cached_method
        def embedded_elements(self):

            ambient = self.ambient_discriminant_module()
            engine_subgroup = self._preamble_discriminant_engine_subgroup
            return ambient.elements().filtered(
                lambda element: ambient._to_smith_engine_element(element)
                in engine_subgroup,
            )

        def b(self, left, right):
            return self.ambient_discriminant_module().b(self.inclusion()(left), self.inclusion()(right))

        def q(self, element):
            ambient = self.ambient_discriminant_module()
            if ambient not in DiscriminantQuadraticModules(ambient.base_ring()):
                raise TypeError(
                    f"q is not defined on the subgroup {self}: {ambient} is a bilinear discriminant form "
                    f"without a quadratic form, in {ambient.category()}"
                )
            return ambient.q(self.inclusion()(element))

        def is_isotropic(self) -> bool:
            ambient = self.ambient_discriminant_module()
            if ambient not in DiscriminantQuadraticModules(ambient.base_ring()):
                raise TypeError(
                    f"isotropy of the subgroup {self} is decided for q, but {ambient} has no quadratic form; "
                    f"it is in {ambient.category()}"
                )
            zero = ambient.quadratic_value_module().zero()
            return all(ambient.q(element) == zero for element in self.embedded_elements())


def _through_formed_copy(module, formed, normalization):
    r"""Read an isometry out of a formed object built on ``module`` as maps on ``module``.

    ``formed`` is built on the data of ``module``, so a generator of
    ``module`` reads in ``formed`` by coercion and the isometry's image of it
    is a generator image of ``module -> normalized``; the inverse reads back
    the same way.
    """
    normalized = normalization.forward().codomain()
    forward = module.module_category().Mor(module, normalized)(
        {
            label: normalization.forward()(formed(module.module_generator(label)))
            for label in module.module_generating_set()
        }
    )
    inverse = normalized.module_category().Mor(normalized, module)(
        {
            label: module(normalization.inverse()(normalized.module_generator(label)))
            for label in normalized.module_generating_set()
        }
    )
    return forward, inverse


def _subquotient_module(subgroup, larger):
    r"""Return the literal cokernel of ``subgroup -> larger`` inside one ambient module."""
    if subgroup.ambient_discriminant_module() is not larger.ambient_discriminant_module():
        raise ValueError(
            f"the subquotient {larger}/{subgroup} needs both subgroups in one discriminant group, but they "
            f"lie in {subgroup.ambient_discriminant_module()} and {larger.ambient_discriminant_module()}"
        )

    larger_inclusion = larger.inclusion()
    subgroup_inclusion = subgroup.inclusion()

    def lift_into_larger(element):
        for candidate in larger.elements():
            if larger_inclusion(candidate) == element:
                return candidate
        raise ValueError(
            f"the subquotient {larger}/{subgroup} needs {subgroup} contained in {larger}, "
            f"but {element} is not in {larger}"
        )

    images = {label: lift_into_larger(subgroup_inclusion(subgroup.module_generator(label))) for label in subgroup.module_generating_set()}
    return subgroup.module_category().Mor(subgroup, larger)(images).cokernel()


def _discriminant_subgroup(ambient, generators):

    # The subgroup is decomposed into cyclic summands on the Smith engine;
    # every generator is returned as an element of the owned ambient module.
    smith_engine = ambient._smith_engine()
    engine_subgroup = smith_engine.submodule(
        [ambient._to_smith_engine_element(generator) for generator in generators]
    )
    ring = ambient.base_ring()
    invariants = tuple(
        _owned_engine_element(ring, invariant)
        for invariant in engine_subgroup.invariants()
        if invariant > 1
    )
    categories = (
        Modules(ring).FinitelyPresented().Torsion(),
        DiscriminantSubmodules(ring),
    )
    construction_data = {
        "ambient_discriminant_module": ambient,
        "discriminant_engine_subgroup": engine_subgroup,
    }
    if invariants:
        prototype = Modules(ring).FinitelyPresented().Torsion().direct_sum_of_cyclics(invariants)
        ambient_generators = tuple(
            ambient._from_smith_engine_element(generator)
            for generator in engine_subgroup.smith_form_gens()
        )
        images = {
            label: image
            for label, image in zip(
                prototype.module_generating_set(), ambient_generators, strict=True
            )
        }
        source = ModulesWithChosenFinitePresentation(ring)(
            prototype.presentation(),
            subobject_ambient=ambient,
            subobject_generator_images=images,
            category=Category.join(categories),
            **construction_data,
        )
    else:
        # The zero finite module is presented by the identity on one generator.

        free = ambient.base_ring().free_module(finite_ordered_set((0,)))
        source = ModulesWithChosenFinitePresentation(ambient.base_ring())(
            free.module_category().Mor(free, free).identity(),
            subobject_ambient=ambient,
            subobject_generator_images={0: ambient.zero()},
            category=Category.join(categories),
            **construction_data,
        )
    return source


def _all_discriminant_subgroups(ambient):
    r"""Return the subgroup lattice through GAP's finite-abelian routine."""
    from sage.groups.abelian_gps.abelian_group_gap import AbelianGroupGap

    smith_engine = ambient._smith_engine()
    assert smith_engine is not None, (
        f"the subgroups of {ambient} are enumerated from its invariant factor decomposition, "
        f"which has not been computed for {ambient}, in {ambient.category()}"
    )
    additive_group = AbelianGroupGap(smith_engine.invariants())
    return finite_ordered_set(
        tuple(
            ambient.subgroup_on(
                tuple(
                    ambient._from_smith_engine_element(
                        smith_engine.linear_combination_of_smith_form_gens(
                            additive_group(generator).exponents()
                        )
                    )
                    for generator in subgroup.gens()
                )
            )
            for subgroup in additive_group.all_subgroups()
        )
    )


def _descended_bilinear_gram(dual_lattice, labels, bilinear_values):
    r"""Return ``b`` on the classes of the selected dual basis, in ``K/R``.

    A class is represented by the dual generator carrying its label, so the
    entry at ``(i,j)`` is the value ``L^#`` already pairs those two
    generators to, read in the quotient.
    """
    return tuple(
        tuple(
            bilinear_values(
                dual_lattice.b(
                    dual_lattice.module_generator(left),
                    dual_lattice.module_generator(right),
                )
            )
            for right in labels
        )
        for left in labels
    )


def _descended_quadratic_gram(dual_lattice, labels, bilinear_values, quadratic_values):
    r"""Return ``q`` on the classes of the selected dual basis, in ``K/2R``.

    The diagonal is the norm of the representative and the off-diagonal is
    the bilinear lift, which is the coordinate datum a quadratic form is
    classified by.  ``q`` is finer than ``b``: it is well defined modulo
    ``2R`` exactly when the lattice is even, which is the hypothesis under
    which this is reached.
    """
    return tuple(
        tuple(
            quadratic_values(
                dual_lattice.norm(dual_lattice.module_generator(left))
                if left == right
                else bilinear_values.lift(
                    bilinear_values(
                        dual_lattice.b(
                            dual_lattice.module_generator(left),
                            dual_lattice.module_generator(right),
                        )
                    )
                )
            )
            for right in labels
        )
        for left in labels
    )


def _discriminant_module(lattice):
    r"""Return the literal cokernel of ``L -> L^#`` with descended forms when supported.

    With a form, the discriminant module is ``FormModules(R)`` applied to the
    form descended to ``A_L = coker(L -> L^#)``: built on the data of ``A_L``,
    which it retains as ``unformed_module()``.
    """
    assert lattice.module_rank().is_finite() and lattice.is_nondegenerate()

    quotient = lattice.correlation_morphism().cokernel()
    dual_lattice = lattice.dual_lattice()
    labels = quotient.module_generating_set()
    ring = lattice.base_ring()
    categories = [DiscriminantModules(ring)]
    construction_data = {
        "source_lattice": lattice,
        "dual_lattice": dual_lattice,
    }

    # The general quotient-value abstraction is present, but the active native
    # K/R engine currently specializes to QQ/nZZ.  Do not advertise a form over
    # another PID until its fraction-field quotient engine exists.
    if _engine_ring(ring) is not SageZZ:
        return ModulesWithChosenFinitePresentation(ring)(
            quotient.presentation(),
            category=Category.join(tuple(categories)),
            **construction_data,
        )

    bilinear_values = FractionFieldQuotients(ring)(1)
    construction_data["bilinear_value_module"] = bilinear_values
    categories.append(DiscriminantBilinearModules(ring))
    # The classes are those of the selected dual basis, so the descended form
    # is read off ``L^#`` on the generators of ``A_L``.  ``q`` is the selected
    # form when the lattice is even, because it determines ``b`` and ``b``
    # does not determine it.
    if lattice.is_even():
        quadratic_values = FractionFieldQuotients(ring)(2)
        construction_data["quadratic_value_module"] = quadratic_values
        categories.append(DiscriminantQuadraticModules(ring))
        form = quotient.quadratic_forms(quadratic_values)(
            _descended_quadratic_gram(
                dual_lattice, labels, bilinear_values, quadratic_values
            )
        )
    else:
        form = quotient.bilinear_forms(bilinear_values)(
            _descended_bilinear_gram(dual_lattice, labels, bilinear_values)
        )
    return FormModules(ring)(
        form,
        _extra_categories=tuple(categories),
        _extra_construction_data=construction_data,
    )


__all__ = [
    "DiscriminantBilinearModules",
    "DiscriminantModules",
    "DiscriminantQuadraticModules",
    "DiscriminantSubmodules",
]
