r"""Discriminant modules and their quotient-valued forms."""

from sage.arith.misc import factor
from sage.misc.cachefunc import cached_method
from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_torsion_modules import (
    FinitelyPresentedTorsionModules,
)
from dzack_research.preamble.categories.rings import (
    OwnedCategoryOverBaseRing,
    engine_ring,
)
from dzack_research.preamble.refine import refine


class DiscriminantModules(OwnedCategoryOverBaseRing):
    r"""Cokernels ``A_L = coker(L -> L^#)`` of nondegenerate finite lattices."""

    @classmethod
    def _repr_object_names(cls):
        return "discriminant modules"

    def super_categories(self):
        return [FinitelyPresentedTorsionModules(self.base_ring())]

    class ParentMethods:
        def source_lattice(self):
            return self._preamble_source_lattice

        def dual_lattice(self):
            r"""Return the selected metric dual ``L^#`` covering this quotient."""
            return self._preamble_dual_lattice

        @cached_method
        def projection(self):
            r"""Return the quotient map ``L^# -> A_L`` on the selected dual basis."""
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
                module_homset,
            )

            dual_lattice = self.dual_lattice()
            return module_homset(dual_lattice, self)({label: self.module_generator(label) for label in self.module_generating_set()})

        def discriminant_class(self, dual_lattice_element):
            r"""Return the class of an element of ``L^#`` in ``A_L``."""
            if dual_lattice_element.parent() is not self.dual_lattice():
                raise TypeError(f"a discriminant class is represented by an element of {self.dual_lattice()}")
            return self.projection()(dual_lattice_element)

        def subgroup_on(self, generators):
            r"""Return the finite subgroup generated by ``generators`` with its inclusion."""
            return _discriminant_subgroup(self, tuple(generators))

        def subgroups(self):
            r"""Return all finite subgroups, exhaustively, for the represented finite module."""
            return _all_discriminant_subgroups(self)

        def primary_components(self):
            r"""Return the canonical ``p``-primary subgroups indexed by primes dividing ``|A|``."""
            components = {}
            smith_generators = tuple(self.smith_form_module_generators())
            invariants = tuple(SageZZ(n) for n in self.invariants() if SageZZ(n) > 1)
            primes = sorted({p for n in invariants for p, _e in factor(n)})
            for prime in primes:
                generators = []
                for order, generator in zip(invariants, smith_generators, strict=True):
                    valuation = order.valuation(prime)
                    if valuation:
                        primary_order = prime**valuation
                        generators.append((order // primary_order) * generator)
                components[prime] = self.subgroup_on(generators)
            return components

    class ElementMethods:
        def dual_lattice_lift(self):
            r"""Return a representative in the selected metric dual ``L^#``.

            Sage's ``FGP_Element.lift()`` is intentionally left untouched: its
            own quotient algorithms call that method internally and require a
            backend free-module vector.  This method is the mathematical lift
            from the discriminant class to the selected covering lattice.
            """
            parent = self.parent()
            raw = FGP_Element.lift(self)
            dual_lattice = parent.dual_lattice()
            return dual_lattice.linear_combination(
                {
                    label: coefficient
                    for label, coefficient in zip(
                        parent.module_generating_set(),
                        tuple(raw),
                        strict=True,
                    )
                    if coefficient
                }
            )


class DiscriminantBilinearModules(OwnedCategoryOverBaseRing):
    r"""Discriminant modules with ``K/R``-valued bilinear form."""

    @classmethod
    def _repr_object_names(cls):
        return "discriminant bilinear modules"

    def super_categories(self):
        return [DiscriminantModules(self.base_ring())]

    class ParentMethods:
        def bilinear_value_module(self):
            return self._preamble_bilinear_value_module

        def b(self, left, right):
            if left.parent() is not self or right.parent() is not self:
                raise TypeError("the discriminant form pairs two classes in one module")
            value = left.dual_lattice_lift().b(right.dual_lattice_lift())
            return self.bilinear_value_module()(value)

        def orthogonal_subgroup(self, subgroup):
            r"""Return ``H^perp`` for a subgroup ``H <= A``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError("orthogonality requires a subgroup of this discriminant module")
            generators = tuple(subgroup.embedded_module_generators())
            elements = [element for element in self.elements() if all(self.b(element, generator) == self.bilinear_value_module().zero() for generator in generators)]
            return self.subgroup_on(elements)

        def form_vanishes_on(self, elements) -> bool:
            r"""Return whether the bilinear form vanishes on all pairs."""
            elements = tuple(elements)
            zero = self.bilinear_value_module().zero()
            return all(self.b(left, right) == zero for left in elements for right in elements)

        def orthogonal_quotient(self, subgroup):
            r"""Return ``H^perp/H`` with its descended bilinear form.

            This requires ``H`` to be totally isotropic for ``b``.  The
            quotient is the literal cokernel of ``H -> H^perp`` and the form
            is descended from the restriction to ``H^perp``.
            """
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError("an orthogonal quotient uses a subgroup of this discriminant module")
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError("H^perp/H requires a totally isotropic subgroup")
            perpendicular = self.orthogonal_subgroup(subgroup)
            quotient = _subquotient_module(subgroup, perpendicular)
            generators = tuple(perpendicular.module_generators())
            gram = tuple(tuple(perpendicular.b(left, right) for right in generators) for left in generators)
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                TorsionBilinearFormModules,
            )

            return TorsionBilinearFormModules(self.base_ring()).from_module(quotient, gram, self.bilinear_value_module())

        def overlattice_from_isotropic_subobject(self, subgroup):
            r"""Return ``L -> L'`` for bilinear-isotropic glue ``H <= A_L``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError("overlattice glue is a subgroup of this discriminant module")
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError("integral overlattice glue must be bilinear-isotropic")
            return self.source_lattice().overlattice(*tuple(subgroup.embedded_module_generators()))

        def discriminant_form_of_overlattice(self, subgroup):
            r"""Return the Nikulin subquotient ``H^perp/H`` for the glued lattice."""
            return self.orthogonal_quotient(subgroup)

        def pontryagin_dual_identification(self):
            r"""Return ``A -> Hom(A,QQ/ZZ)``, ``x |-> b(x,-)``.

            A discriminant pairing of a nondegenerate lattice is perfect, so
            this map is the canonical Pontryagin-dual identification rather
            than merely a homomorphism into the character group.
            """
            from sage.categories.homset import Hom as sage_hom
            from sage.categories.morphism import SetMorphism
            from sage.categories.sets_cat import Sets as SageSets

            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
                module_homset,
            )

            characters = module_homset(self, self.bilinear_value_module())

            def character(element):
                element = self(element)
                return characters(
                    {
                        label: self.b(element, self.module_generator(label))
                        for label in self.module_generating_set()
                    }
                )

            return SetMorphism(sage_hom(self, characters, SageSets()), character)

        def invariant_factor_form(self):
            r"""Return the bilinear isometry to a normalized framed torsion form.

            The discriminant module itself remains the literal cokernel
            ``L^# / L`` on the selected dual-basis classes.  The codomain is a
            different formed module on the non-unit Smith generators.
            """
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                TorsionBilinearFormModules,
                torsion_form_isometry,
            )

            generators = tuple(self.module_generators())
            gram = tuple(
                tuple(self.b(left, right) for right in generators)
                for left in generators
            )
            formed = TorsionBilinearFormModules(self.base_ring()).from_module(
                self,
                gram,
                self.bilinear_value_module(),
            )
            normalization = formed.invariant_factor_form()
            forward = normalization.forward() * formed.equip_form_morphism()
            inverse = formed.forget_form_morphism() * normalization.inverse()
            return torsion_form_isometry(
                forward,
                inverse,
                quadratic=False,
            )

        def p_adic_jordan_decomposition(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _p_adic_jordan_decomposition,
            )

            return _p_adic_jordan_decomposition(self, quadratic=False)

        def p_adic_jordan_module_generators(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                p_adic_jordan_module_generators,
            )

            return p_adic_jordan_module_generators(self, quadratic=False)

        def p_adic_jordan_form(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _p_adic_jordan_form,
            )

            return _p_adic_jordan_form(self, quadratic=False)

        normal_form = p_adic_jordan_form

        def twist(self, scalar):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _twisted_torsion_form,
            )

            return _twisted_torsion_form(self, scalar, quadratic=False)

        def is_isomorphic(self, other) -> bool:
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _forms_are_isomorphic,
            )

            if not hasattr(other, "invariant_factor_form") or not hasattr(other, "b"):
                return False
            return _forms_are_isomorphic(self, other, quadratic=False)

        is_isometric_to = is_isomorphic

        def is_anti_isometric(self, other) -> bool:
            if not hasattr(other, "twist"):
                return False
            return self.is_isomorphic(other.twist(-1))

        @cached_method
        def automorphism_group(self):
            r"""Return ``O(A,b)`` as live form automorphisms."""
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _torsion_form_automorphism_group,
            )

            return _torsion_form_automorphism_group(self, quadratic=False)

        def orthogonal_group(self):
            return self.automorphism_group()

        def O(self):  # noqa: E743 - standard mathematical notation O(A,b)
            return self.automorphism_group()

    class ElementMethods:
        def b(self, other):
            return self.parent().b(self, other)

        def norm(self):
            return self.b(self)


class DiscriminantQuadraticModules(OwnedCategoryOverBaseRing):
    r"""Even-lattice discriminant modules with quadratic form in ``K/2R``."""

    @classmethod
    def _repr_object_names(cls):
        return "discriminant quadratic modules"

    def super_categories(self):
        return [DiscriminantBilinearModules(self.base_ring())]

    class ParentMethods:
        def quadratic_value_module(self):
            return self._preamble_quadratic_value_module

        def q(self, element):
            if element.parent() is not self:
                raise TypeError("the discriminant quadratic form is defined on this module")
            return self.quadratic_value_module()(element.dual_lattice_lift().norm())

        def isotropic_elements(self):
            r"""Return the classes on which the quadratic form vanishes."""
            from dzack_research.preamble.categories.sets import finite_ordered_set

            zero = self.quadratic_value_module().zero()
            return finite_ordered_set(element for element in self.elements() if self.q(element) == zero)

        def is_anisotropic(self) -> bool:
            return len(self.isotropic_elements()) == 1

        def isotropic_subgroups(self):
            r"""Return all subgroups on which ``q`` vanishes identically."""
            zero = self.quadratic_value_module().zero()
            return tuple(subgroup for subgroup in self.subgroups() if all(self.q(element) == zero for element in subgroup.embedded_elements()))

        def lagrangian_subgroups(self):
            r"""Return isotropic ``H`` with ``|H|^2=|A|``."""
            order = SageZZ(self.cardinality())
            return tuple(subgroup for subgroup in self.isotropic_subgroups() if SageZZ(subgroup.cardinality()) ** 2 == order)

        def is_metabolic(self) -> bool:
            return bool(self.lagrangian_subgroups())

        def form_vanishes_on(self, elements) -> bool:
            r"""Return whether ``q`` vanishes on every supplied element."""
            zero = self.quadratic_value_module().zero()
            return all(self.q(element) == zero for element in elements)

        def associated_bilinear_form(self):
            r"""Return the ``QQ/ZZ``-valued polarization as a distinct object.

            Forgetting the quadratic refinement must forget structure: the
            resulting bilinear object has the same presented finite module and
            pairing ``b`` but does not remain in the quadratic category.  This
            distinction is what allows ``O(A,q)`` to be strictly smaller than
            ``O(A,b)``.
            """
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                TorsionBilinearFormModules,
            )

            generators = tuple(self.module_generators())
            gram = tuple(
                tuple(self.b(left, right) for right in generators)
                for left in generators
            )
            return TorsionBilinearFormModules(self.base_ring()).from_module(
                self,
                gram,
                self.bilinear_value_module(),
            )

        def orthogonal_quotient(self, subgroup):
            r"""Return ``H^perp/H`` with its descended quadratic form."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError("an orthogonal quotient uses a subgroup of this discriminant module")
            embedded = tuple(subgroup.embedded_elements())
            if not self.form_vanishes_on(embedded):
                raise ValueError("H^perp/H requires a q-isotropic subgroup")
            perpendicular = DiscriminantBilinearModules.ParentMethods.orthogonal_subgroup(self, subgroup)
            quotient = _subquotient_module(subgroup, perpendicular)
            generators = tuple(perpendicular.module_generators())
            quadratic_values = self.quadratic_value_module()
            gram = []
            for i, left in enumerate(generators):
                row = []
                for j, right in enumerate(generators):
                    if i == j:
                        row.append(perpendicular.q(left))
                    else:
                        bilinear_value = perpendicular.b(left, right)
                        row.append(quadratic_values(self.bilinear_value_module().lift(bilinear_value)))
                gram.append(tuple(row))
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                TorsionQuadraticFormModules,
            )

            return TorsionQuadraticFormModules(self.base_ring()).from_module(quotient, tuple(gram), quadratic_values)

        def overlattice_from_isotropic_subobject(self, subgroup):
            r"""Return ``L -> L'`` for q-isotropic glue ``H <= A_L``."""
            if subgroup.ambient_discriminant_module() is not self:
                raise ValueError("overlattice glue is a subgroup of this discriminant module")
            if not subgroup.is_isotropic():
                raise ValueError("an even overlattice requires q-isotropic glue")
            return self.source_lattice().overlattice(*tuple(subgroup.embedded_module_generators()))

        def discriminant_form_of_overlattice(self, subgroup):
            r"""Return ``H^perp/H``, the discriminant form of the glued overlattice."""
            return self.orthogonal_quotient(subgroup)

        def invariant_factor_form(self):
            r"""Return the quadratic isometry to invariant-factor framing.

            The source remains the literal discriminant cokernel with the
            classes of the selected dual basis as its framing.  The target is
            a distinct finite quadratic module whose framing consists only of
            the non-unit Smith factors.
            """
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                TorsionQuadraticFormModules,
                torsion_form_isometry,
            )

            generators = tuple(self.module_generators())
            quadratic_values = self.quadratic_value_module()
            gram = []
            for i, left in enumerate(generators):
                row = []
                for j, right in enumerate(generators):
                    if i == j:
                        row.append(self.q(left))
                    else:
                        row.append(
                            quadratic_values(
                                self.bilinear_value_module().lift(
                                    self.b(left, right)
                                )
                            )
                        )
                gram.append(tuple(row))
            formed = TorsionQuadraticFormModules(self.base_ring()).from_module(
                self,
                tuple(gram),
                quadratic_values,
            )
            normalization = formed.invariant_factor_form()
            forward = normalization.forward() * formed.equip_form_morphism()
            inverse = formed.forget_form_morphism() * normalization.inverse()
            return torsion_form_isometry(
                forward,
                inverse,
                quadratic=True,
            )

        def p_adic_jordan_decomposition(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _p_adic_jordan_decomposition,
            )

            return _p_adic_jordan_decomposition(self, quadratic=True)

        def p_adic_jordan_module_generators(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                p_adic_jordan_module_generators,
            )

            return p_adic_jordan_module_generators(self, quadratic=True)

        def p_adic_jordan_form(self):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _p_adic_jordan_form,
            )

            return _p_adic_jordan_form(self, quadratic=True)

        normal_form = p_adic_jordan_form

        def twist(self, scalar):
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _twisted_torsion_form,
            )

            return _twisted_torsion_form(self, scalar, quadratic=True)

        def is_isomorphic(self, other) -> bool:
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _forms_are_isomorphic,
            )

            if not hasattr(other, "invariant_factor_form") or not hasattr(other, "q"):
                return False
            return _forms_are_isomorphic(self, other, quadratic=True)

        is_isometric_to = is_isomorphic

        def is_anti_isometric(self, other) -> bool:
            if not hasattr(other, "twist"):
                return False
            return self.is_isomorphic(other.twist(-1))

        @cached_method
        def automorphism_group(self):
            r"""Return ``O(A,q)`` as live quadratic-form automorphisms."""
            from dzack_research.preamble.categories.modules.framed.formed.torsion_form_modules import (
                _torsion_form_automorphism_group,
            )

            return _torsion_form_automorphism_group(self, quadratic=True)

        def orthogonal_group(self):
            return self.automorphism_group()

        def O(self):  # noqa: E743 - standard mathematical notation O(A,q)
            return self.automorphism_group()

        @cached_method
        def brown_invariant(self):
            r"""Return the Brown invariant in ``ZZ/8ZZ`` from the exact Gauss sum.

            With the present convention ``q:A -> QQ/2ZZ``, the normalized
            Gauss sum is

            ``|A|^(-1/2) * sum_x exp(pi*i*q(x)) = exp(pi*i*Br(q)/4)``.

            Discriminant forms are nondegenerate, so the left side is an
            eighth root of unity.  The computation takes place in ``QQbar``;
            equality there is exact algebraic-number equality, not a floating
            phase comparison.
            """
            from sage.rings.finite_rings.integer_mod_ring import IntegerModRing
            from sage.rings.qqbar import QQbar
            from sage.rings.rational_field import QQ as SageQQ

            total = QQbar.zero()
            for element in self.elements():
                value = SageQQ(self.quadratic_value_module().lift(self.q(element)))
                denominator = SageZZ(value.denominator())
                numerator = SageZZ(value.numerator())
                total += QQbar.zeta(2 * denominator) ** numerator
            scale = QQbar(SageZZ(self.cardinality())).sqrt()
            zeta8 = QQbar.zeta(8)
            for residue in range(8):
                if total == scale * zeta8**residue:
                    return IntegerModRing(8)(residue)
            raise ArithmeticError(
                "the normalized Gauss sum is not an eighth root of unity; the form may be degenerate"
            )

    class ElementMethods:
        def q(self):
            return self.parent().q(self)

        def norm(self):
            return self.q()


class DiscriminantSubmodules(OwnedCategoryOverBaseRing):
    r"""Finite subgroups of a discriminant module with the restricted form."""

    @classmethod
    def _repr_object_names(cls):
        return "discriminant submodules"

    def super_categories(self):
        return [FinitelyPresentedTorsionModules(self.base_ring())]

    class ParentMethods:
        def ambient_discriminant_module(self):
            return self._preamble_ambient_discriminant_module

        def embedded_elements(self):
            return tuple(self.inclusion()(element) for element in self.elements())

        def b(self, left, right):
            return self.ambient_discriminant_module().b(self.inclusion()(left), self.inclusion()(right))

        def q(self, element):
            ambient = self.ambient_discriminant_module()
            if not hasattr(ambient, "q"):
                raise TypeError("the ambient discriminant module has no quadratic form")
            return ambient.q(self.inclusion()(element))

        def is_isotropic(self) -> bool:
            ambient = self.ambient_discriminant_module()
            if not hasattr(ambient, "q"):
                raise TypeError("isotropy here requires a discriminant quadratic module")
            zero = ambient.quadratic_value_module().zero()
            return all(ambient.q(element) == zero for element in self.embedded_elements())

    class ElementMethods:
        def b(self, other):
            return self.parent().b(self, other)

        def q(self):
            return self.parent().q(self)


def _element_key(module, element):
    return tuple(module.coordinate_vector(element, reduce=True))


def _subquotient_module(subgroup, larger):
    r"""Return the literal cokernel of ``subgroup -> larger`` inside one ambient module."""
    if subgroup.ambient_discriminant_module() is not larger.ambient_discriminant_module():
        raise ValueError("a discriminant subquotient requires one ambient module")
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    larger_inclusion = larger.inclusion()
    subgroup_inclusion = subgroup.inclusion()

    def lift_into_larger(element):
        for candidate in larger.elements():
            if larger_inclusion(candidate) == element:
                return candidate
        raise ValueError("the smaller subgroup is not contained in the proposed larger subgroup")

    images = {label: lift_into_larger(subgroup_inclusion(subgroup.module_generator(label))) for label in subgroup.module_generating_set()}
    return module_homset(subgroup, larger)(images).cokernel()


def _discriminant_subgroup(ambient, generators):
    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_torsion_modules import (
        FinitelyPresentedTorsionModules,
    )
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import module_embedding
    from dzack_research.preamble.categories.modules.subobjects import ModuleSubobjects

    backend = ambient.submodule(list(generators))
    invariants = tuple(SageZZ(n) for n in backend.invariants() if SageZZ(n) > 1)
    if invariants:
        source = FinitelyPresentedTorsionModules(ambient.base_ring()).direct_sum_of_cyclics(invariants)
        backend_generators = tuple(backend.smith_form_gens())
        ambient_generators = tuple(ambient(generator.lift()) for generator in backend_generators)
        images = {label: image for label, image in zip(source.module_generating_set(), ambient_generators, strict=True)}
    else:
        # The zero finite module is presented by the identity on one generator.
        from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_generated_free_modules import BasedFreeModule
        from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import FinitelyPresentedModule
        from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import module_homset
        from dzack_research.preamble.categories.sets import finite_ordered_set

        free = BasedFreeModule(ambient.base_ring(), finite_ordered_set((0,)))
        source = FinitelyPresentedModule(module_homset(free, free).identity())
        images = {label: ambient.zero() for label in source.module_generating_set()}
    inclusion = module_embedding(source, ambient, images)
    source._preamble_inclusion = inclusion
    source._preamble_ambient_discriminant_module = ambient
    return refine(
        source,
        [source.category(), ModuleSubobjects(ambient.base_ring()), DiscriminantSubmodules(ambient.base_ring())],
    )


def _all_discriminant_subgroups(ambient):
    elements = tuple(ambient.elements())
    zero_key = frozenset((_element_key(ambient, ambient.zero()),))
    known = {zero_key: ambient.subgroup_on(())}
    frontier = [known[zero_key]]
    while frontier:
        subgroup = frontier.pop()
        subgroup_keys = {_element_key(ambient, element) for element in subgroup.embedded_elements()}
        for element in elements:
            if _element_key(ambient, element) in subgroup_keys:
                continue
            candidate = ambient.subgroup_on(tuple(subgroup.embedded_elements()) + (element,))
            key = frozenset(_element_key(ambient, x) for x in candidate.embedded_elements())
            if key not in known:
                known[key] = candidate
                frontier.append(candidate)
    return tuple(known.values())


def DiscriminantModule(lattice):
    r"""Return the literal cokernel of ``L -> L^#`` with descended forms when supported."""
    assert lattice.is_finite_rank() and lattice.is_nondegenerate()

    module = lattice.correlation_morphism().cokernel()
    module._preamble_source_lattice = lattice
    module._preamble_dual_lattice = lattice.dual_lattice()
    refine(module, DiscriminantModules(lattice.base_ring()))

    # The general quotient-value abstraction is present, but the active native
    # K/R engine currently specializes to QQ/nZZ.  Do not advertise a form over
    # another PID until its fraction-field quotient engine exists.
    if engine_ring(lattice.base_ring()) is SageZZ:
        from dzack_research.preamble.categories.modules.framed.fraction_field_quotients import (
            FractionFieldQuotient,
        )

        module._preamble_bilinear_value_module = FractionFieldQuotient(lattice.base_ring(), 1)
        refine(module, DiscriminantBilinearModules(lattice.base_ring()))
        if lattice.is_even():
            module._preamble_quadratic_value_module = FractionFieldQuotient(lattice.base_ring(), 2)
            refine(module, DiscriminantQuadraticModules(lattice.base_ring()))
    return module


__all__ = [
    "DiscriminantBilinearModules",
    "DiscriminantModule",
    "DiscriminantModules",
    "DiscriminantQuadraticModules",
    "DiscriminantSubmodules",
]
