r"""The two axioms that cut integral lattices out of ``Lattices(R)``.

``Integral``: the form takes its values in $R$ itself rather than in the
fraction field -- for an $R$-lattice $L$ with $K=\operatorname{Frac}(R)$, the
value module lies in the ring of integers of $K$.  ``Nondegenerate``:
$\operatorname{rad}(L)=0$, no vector pairs to zero with everything.

Both are declared, not composed.  Sage models "this category, plus this axiom"
as a class naming the pair and bound onto the category it refines; a category
that offers the axiom also names it in ``SubcategoryMethods``, which is what
makes ``Lattices(R).Integral()`` resolve at all.  Without both halves
``_with_axiom`` silently returns the unrefined category, which is worse than
an error -- the objects would claim an axiom nothing imposed.
"""

import sage.categories.category_with_axiom as cwa
from sage.categories.category_with_axiom import (
    CategoryWithAxiom_over_base_ring,
    axiom,
)
from sage.misc.abstract_method import abstract_method

from dzack_research.preamble.categories.modules.framed.formed.lattices import Lattices
from dzack_research.preamble.categories.modules.pure.finitely_generated.finitely_generated_modules import (
    FinitelyGeneratedModules,
)

for _axiom_name in ("FinitelyGenerated", "Integral", "Nondegenerate", "Even"):
    if _axiom_name not in cwa.all_axioms:
        cwa.all_axioms.add(_axiom_name)


class _LatticeSubcategoryMethods:
    r"""The axioms a lattice category offers.

    ``FinitelyGenerated`` names the same property as the owned category
    ``FinitelyGeneratedModules(R)``, but only as an axiom of *this* category
    is it a thing Sage can apply.  Applying an axiom yields a join category,
    and a join sees only what its members offer through
    ``SubcategoryMethods``.  Naming it here is what lets the axioms be
    applied in any order.
    """

    FinitelyGenerated = axiom("FinitelyGenerated")
    Integral = axiom("Integral")
    Nondegenerate = axiom("Nondegenerate")
    Even = axiom("Even")


setattr(Lattices, "SubcategoryMethods", _LatticeSubcategoryMethods)


class FinitelyGeneratedLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices generated by finitely many elements.

    Offering the axiom in ``SubcategoryMethods`` above is not enough: the
    application resolves through a class naming this pair, and without one
    ``_with_axiom`` returns the unrefined category and the axiom is silently
    lost.

    Admission is by predicate: ``refine`` evaluates
    ``is_finitely_generated()``, which the module surface computes from the
    framing being finite rather than declaring from membership.
    """

    _certifying_predicate = "is_finitely_generated"

    _base_category_class_and_axiom = (Lattices, "FinitelyGenerated")

    def extra_super_categories(self) -> list:
        r"""A finitely generated lattice is a finitely generated module.

        Said so that the module category's methods reach it: without this the
        join resolves ``module_generators`` to the framed version, which
        answers with an image set rather than the tuple a finite generating
        set has.
        """
        return [FinitelyGeneratedModules(self.base_ring())]

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated lattices"


class IntegralValuedLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices whose form takes its values in the base ring.

    Admission is by predicate: ``refine`` evaluates ``is_integral()`` on the
    candidate and refuses a ``False``.  A finitely generated formed module
    computes the answer from its Gram entries; any other participant must
    answer for itself -- a ``return True`` backed by a theorem is
    admissible, and it is the *participant's* auditable claim, made by name
    on the object rather than granted by placement.
    """

    _base_category_class_and_axiom = (Lattices, "Integral")
    _certifying_predicate = "is_integral"

    @classmethod
    def _repr_object_names(cls) -> str:
        return "integral-valued lattices"

    class ParentMethods:
        @abstract_method
        def is_integral(self) -> bool:
            r"""Return whether every value of the form is integral over $\mathbb Z$."""


class NondegenerateLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices whose radical is zero.

    Admission is by predicate: ``refine`` evaluates ``is_nondegenerate()``
    on the candidate and refuses a ``False``.  The finitely generated free
    formed surface computes it as the radical -- the kernel *module* of the
    correlation morphism -- being zero; an infinite lattice whose
    nondegeneracy is a theorem participates by supplying its own method,
    which is then the participant's auditable claim.
    """

    _base_category_class_and_axiom = (Lattices, "Nondegenerate")
    _certifying_predicate = "is_nondegenerate"

    @classmethod
    def _repr_object_names(cls) -> str:
        return "nondegenerate lattices"

    class ParentMethods:
        @abstract_method
        def is_nondegenerate(self) -> bool:
            r"""Return whether $\operatorname{rad}(L)=0$."""


class EvenLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices whose form has even norms: $b(x,x)\in 2R$ for every $x$.

    Even-ness is the home of the discriminant *quadratic* form: only an even
    lattice's $q$ descends to $A_L$ with values in $K/2R$ rather than $K/R$
    (Nik80, Zotero TTY9FFJS, section 1.3).  The axiom therefore refines
    ``Integral`` -- an even form is in particular integral-valued, said in
    ``extra_super_categories`` so the integral vocabulary reaches every even
    lattice without restatement.

    Admission is by predicate: ``refine`` evaluates ``is_even()``, which a
    finitely generated formed module computes from its Gram diagonal; any
    other participant answers for itself, and that answer is the
    participant's auditable claim.
    """

    _base_category_class_and_axiom = (Lattices, "Even")
    _certifying_predicate = "is_even"

    def extra_super_categories(self) -> list:
        r"""An even lattice is integral-valued: $2\mid b(x,x)$ forces
        $b(x,y)=\tfrac12(q(x+y)-q(x)-q(y))\in R$ once the norms are in $2R$
        and the form is $R$-valued on a generating set."""
        return [IntegralValuedLattices(self.base_ring())]

    @classmethod
    def _repr_object_names(cls) -> str:
        return "even lattices"

    class ParentMethods:
        @abstract_method
        def is_even(self) -> bool:
            r"""Return whether every norm $b(x,x)$ lies in $2R$."""


# ``IntegralLattices`` is ``Lattices(R).FinitelyGenerated().Integral()``, and
# declares itself so in its own file; the binding happens there, once that
# class exists.
setattr(Lattices, "FinitelyGenerated", FinitelyGeneratedLattices)
setattr(Lattices, "Integral", IntegralValuedLattices)
setattr(Lattices, "Nondegenerate", NondegenerateLattices)
setattr(Lattices, "Even", EvenLattices)
