r"""The two axioms that cut integral lattices out of ``Lattices(R)``.

``Integral``: the form takes its values in $R$ itself rather than in the
fraction field -- for an $R$-lattice $L$ with $K=\operatorname{Frac}(R)$, the
value module lies in the ring of integers of $K$.  ``Nondegenerate``:
$\operatorname{rad}(L)=0$, no vector pairs to zero with everything.

Both are declared, not composed.  Sage models "this category, plus this axiom"
as a class naming the pair and bound onto the category it refines; a category
that offers the axiom also names it in ``SubcategoryMethods``, which is what
makes ``Lattices(R).Integral()`` resolve at all.  Without both halves
``_with_axiom`` silently returns the unrefined category, which is worse than
an error -- the objects would claim an axiom nothing imposed.
"""

import sage.categories.category_with_axiom as cwa
from sage.categories.category_with_axiom import (
    CategoryWithAxiom_over_base_ring,
    axiom,
)

from sage.categories.modules import Modules

from dzack_research.preamble.categories.modules.framed.formed.lattices import Lattices
from dzack_research.preamble.categories.modules.pure.finitely_generated.finitely_generated_modules import (  # noqa: F401
    FinitelyGeneratedModules,
)

for _axiom_name in ("Integral", "Nondegenerate"):
    if _axiom_name not in cwa.all_axioms:
        cwa.all_axioms.add(_axiom_name)


class _LatticeSubcategoryMethods:
    r"""The axioms a lattice category offers.

    ``FinitelyGenerated`` is offered here as well, though it is a module
    axiom declared elsewhere.  Applying an axiom yields a join category, and a
    join sees only what its members offer through ``SubcategoryMethods`` --
    not the methods bound onto ``Category_module``.  Naming it here is what
    lets the axioms be applied in any order.
    """

    FinitelyGenerated = axiom("FinitelyGenerated")
    Integral = axiom("Integral")
    Nondegenerate = axiom("Nondegenerate")


setattr(Lattices, "SubcategoryMethods", _LatticeSubcategoryMethods)


class FinitelyGeneratedLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices generated by finitely many elements.

    The axiom is the module one, declared on ``Modules(R)``. Offering it in
    ``SubcategoryMethods`` above is not enough: the application resolves
    through a class naming this pair, and without one ``_with_axiom`` returns
    the unrefined category and the axiom is silently lost.
    """

    _base_category_class_and_axiom = (Lattices, "FinitelyGenerated")

    def extra_super_categories(self) -> list:
        r"""A finitely generated lattice is a finitely generated module.

        Said so that the module category's methods reach it: without this the
        join resolves ``module_generators`` to the framed version, which
        answers with an image set rather than the tuple a finite generating
        set has.
        """
        return [Modules(self.base_ring()).FinitelyGenerated()]

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated lattices"


class IntegralValuedLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices whose form takes its values in the base ring."""

    _base_category_class_and_axiom = (Lattices, "Integral")

    @classmethod
    def _repr_object_names(cls) -> str:
        return "integral-valued lattices"


class NondegenerateLattices(CategoryWithAxiom_over_base_ring):
    r"""Lattices whose radical is zero."""

    _base_category_class_and_axiom = (Lattices, "Nondegenerate")

    @classmethod
    def _repr_object_names(cls) -> str:
        return "nondegenerate lattices"


# ``IntegralLattices`` is ``Lattices(R).FinitelyGenerated().Integral()``, and
# declares itself so in its own file; the binding happens there, once that
# class exists.
setattr(Lattices, "FinitelyGenerated", FinitelyGeneratedLattices)
setattr(Lattices, "Integral", IntegralValuedLattices)
setattr(Lattices, "Nondegenerate", NondegenerateLattices)
