r"""Invariant rings and categorical quotients of finite linear actions on ``A^2_QQ``."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def _acted_plane(G, images_of_generator):
    A = QQ['x,y']
    X = A.affine_spectrum()
    sigma = X.Mor(X)(A.Mor(A)(images_of_generator(*A.gens())))
    return A, X, GObjects(G, Schemes(QQ))(X, G.Mor(X.automorphism_group())({G.gen(): sigma}))


def test_the_invariants_of_the_coordinate_swap_are_the_symmetric_polynomials() -> None:
    r"""``QQ[x, y]^{S_2} = QQ[x + y, x^2 + y^2] = QQ[x + y, xy]``, a polynomial ring, so ``A^2/S_2 ≅ A^2``.

    Fundamental theorem of symmetric polynomials; over ``QQ``,
    ``xy = ((x + y)^2 - (x^2 + y^2))/2`` (Chevalley--Shephard--Todd for the reflection).
    """
    A, X, acted = _acted_plane(Groups.C(2), lambda x, y: {x: y, y: x})
    x, y = A.gens()
    invariants = acted.invariant_ring()

    assert x + y in invariants
    assert x**2 + y**2 in invariants
    assert x * y in invariants
    assert x not in invariants
    assert x - y not in invariants
    assert (x - y) ** 2 in invariants
    assert invariants.is_isomorphic(QQ['u,v'])
    assert acted.quotient().is_smooth()


def test_the_invariant_map_x_plus_y_factors_uniquely_through_the_swap_quotient() -> None:
    r"""``(x, y) -> x + y`` is ``S_2``-invariant, so it factors through ``A^2 -> A^2/S_2`` (universal property)."""
    A, X, acted = _acted_plane(Groups.C(2), lambda x, y: {x: y, y: x})
    x, y = A.gens()
    T = QQ['t']
    line = T.affine_spectrum()
    f = X.Mor(line)(T.Mor(A)({T.gen(): x + y}))
    q = acted.quotient_morphism()
    h = f.factor_through(q)

    assert h * q == f
    assert h.codomain() == line


def test_the_invariants_of_minus_one_on_the_plane_form_the_a1_cone() -> None:
    r"""``QQ[x, y]^{±1} = QQ[x^2, xy, y^2] ≅ QQ[u, v, w]/(uw - v^2)``: the ``A_1`` surface singularity.

    Derivation: invariants are the even-degree polynomials, generated by the three
    quadratic monomials with the single relation ``x^2 · y^2 = (xy)^2``.
    """
    A, X, acted = _acted_plane(Groups.C(2), lambda x, y: {x: -x, y: -y})
    x, y = A.gens()
    invariants = acted.invariant_ring()
    B = QQ['u,v,w']
    u, v, w = B.gens()

    assert x**2 in invariants and x * y in invariants and y**2 in invariants
    assert x not in invariants
    assert x**3 not in invariants
    assert invariants.is_isomorphic(B.quotient(B.ideal(u * w - v**2)))
    assert acted.quotient().dimension() == 2
    assert not acted.quotient().is_smooth()


def test_x2_minus_xy_plus_y2_is_invariant_under_the_order_three_rotation_and_descends() -> None:
    r"""``sigma: x -> -y, y -> x - y`` has order 3 and fixes ``x^2 - xy + y^2``, which descends to ``A^2/C_3``.

    Derivation: ``sigma^2(x) = y - x`` and ``sigma^3(x) = x``;
    ``y^2 + y(x - y) + (x - y)^2 = x^2 - xy + y^2``.
    """
    A, X, acted = _acted_plane(Groups.C(3), lambda x, y: {x: -y, y: x - y})
    x, y = A.gens()
    q2 = x**2 - x * y + y**2
    T = QQ['t']
    line = T.affine_spectrum()
    f = X.Mor(line)(T.Mor(A)({T.gen(): q2}))
    q = acted.quotient_morphism()

    assert q2 in acted.invariant_ring()
    assert x + y not in acted.invariant_ring()
    assert x**2 + y**2 not in acted.invariant_ring()
    assert f.factor_through(q) * q == f
    assert not acted.quotient().is_smooth()
