r"""Quasi-coherent sheaves on affine schemes: restriction, refinement, stalks, direct and inverse images, relative Spec."""

from dzack_research.preamble.all import (
    AffineSpace,
    FreeModule,
    LocalRings,
    PolynomialRing,
    QQ,
    Spec,
    SpecFunctor,
    scheme_fiber_product,
)


def test_restrictions_compose_along_a_common_refinement_of_two_covers() -> None:
    algebra = PolynomialRing(QQ, ("x", "y"))
    x, y = algebra.algebra_generators()
    scheme = Spec(algebra)
    sheaf = scheme.structure_sheaf()
    first = scheme.distinguished_open_cover(x, algebra.one() - x)
    second = scheme.distinguished_open_cover(y, algebra.one() - y)
    refinement = first.common_refinement(second)
    fine = refinement.fine_cover()

    assert len(fine.opens()) == 4
    assert refinement.index_map(0, 3) == 1
    assert refinement.index_map(1, 3) == 1
    assert fine.open(3).distinguished_open_element() == (algebra.one() - x) * (algebra.one() - y)

    for fine_index in range(4):
        for which in (0, 1):
            coarse_open = refinement.coarse_cover(which).open(refinement.index_map(which, fine_index))
            inclusion = refinement.inclusion(which, fine_index)
            fine_open = fine.open(fine_index)
            assert inclusion.domain() is fine_open
            assert inclusion.codomain() is coarse_open
            assert coarse_open.inclusion() * inclusion == fine_open.inclusion()
            # Restriction along X > U > V is restriction along X > V.
            via_coarse = sheaf.restriction_map(coarse_open, fine_open) * sheaf.restriction_map(scheme, coarse_open)
            direct = sheaf.restriction_map(scheme, fine_open)
            assert via_coarse(x * y + 1) == direct(x * y + 1)
            assert inclusion.coordinate_algebra_morphism() is sheaf.restriction_map(coarse_open, fine_open)


def test_the_stalk_of_a_module_sheaf_is_the_localized_module() -> None:
    line = AffineSpace(1, QQ, names=("x",))
    algebra = line.coordinate_ring()
    x = algebra.algebra_generator("x")
    module = FreeModule(algebra, 2)
    sheaf = line.associated_module_sheaf(module)
    origin = line.underlying_space()(algebra.ideal(x))

    stalk = sheaf.stalk(origin)
    assert stalk.base_ring() is line.stalk(origin)
    assert stalk.base_ring() in LocalRings()
    assert stalk.localization_source_module() is module
    generator = stalk.fraction(module.module_generator(0), x - 1)
    assert stalk.base_ring().fraction(x - 1) * generator == stalk.fraction(module.module_generator(0))


def test_direct_and_inverse_images_along_the_cusp_parametrization() -> None:
    plane = AffineSpace(2, QQ, names=("x", "y"))
    algebra = plane.coordinate_ring()
    x = algebra.algebra_generator("x")
    y = algebra.algebra_generator("y")
    line = PolynomialRing(QQ, "t")
    t = line.algebra_generator("t")
    parametrization = SpecFunctor(QQ)(algebra.Mor(line)({"x": t**2, "y": t**3}))
    affine_line = parametrization.domain()

    # f_* of the structure sheaf of the line is QQ[t] read as a QQ[x,y]-module
    # through x -> t^2, y -> t^3: the pushforward of the free rank-one sheaf.
    structure = affine_line.associated_module_sheaf(FreeModule(line, 1))
    pushed = parametrization.direct_image(structure)
    assert pushed.scheme() is plane
    assert pushed.global_sections().base_ring() is algebra
    section = pushed.global_sections()(structure.global_sections().module_generator(0))
    scaled = pushed.global_sections().scalar_multiple(x, section)
    assert scaled.underlying_element() == structure.global_sections().scalar_multiple(
        t**2, structure.global_sections().module_generator(0)
    )
    open_x = plane.distinguished_open(x)
    assert pushed.sections_on_distinguished_open(open_x).base_ring() is open_x.coordinate_algebra()

    # f^* of the ideal sheaf of the cusp is a module whose only relation is killed:
    # y^2 - x^3 pulls back to zero, so f^*(I~) is generated by one element with zero relation.
    cusp = plane.closed_subscheme(y**2 - x**3)
    ideal_sheaf = cusp.ideal_sheaf()
    pulled = parametrization.module_pullback(ideal_sheaf)
    assert pulled.scheme() is affine_line
    pulled_module = pulled.global_sections()
    assert pulled_module.base_ring() is line
    assert pulled_module.module_generating_set().cardinality() == 1


def test_relative_spec_is_compatible_with_base_change() -> None:
    r"""``Spec_{X'}(B tensor_A A') = Spec_X(B) x_X X'`` for the double cover ``z^2 = x`` of the line."""
    line = AffineSpace(1, QQ, names=("x",))
    algebra = line.coordinate_ring()
    x = algebra.algebra_generator("x")
    cover_presentation = PolynomialRing(QQ, ("x", "z"))
    xc, z = cover_presentation.algebra_generators()
    from dzack_research.preamble.all import FinitelyPresentedAlgebra

    cover_algebra = FinitelyPresentedAlgebra(cover_presentation, (z**2 - xc,))
    structure = algebra.Mor(cover_algebra)({"x": cover_algebra.algebra_generator("x")})
    relative = line.relative_spectrum(structure)

    assert relative.arrow().codomain() is line
    assert relative.arrow().domain() is Spec(cover_algebra)
    assert relative.arrow().coordinate_algebra_morphism() is structure
    assert relative in line.scheme_category().SliceOver(line)

    # Base change along the closed point x = 1 gives Spec of QQ[z]/(z^2 - 1), two points.
    point_algebra = PolynomialRing(QQ, "u")
    u = point_algebra.algebra_generator("u")
    point_map = SpecFunctor(QQ)(algebra.Mor(point_algebra)({"x": point_algebra.one()}))
    fibre = scheme_fiber_product(relative.arrow(), point_map)
    fibre_algebra = fibre.coordinate_algebra()
    zf = fibre_algebra.algebra_generator(("left", "z"))
    assert zf**2 == fibre_algebra.one()
    changed = point_map.domain().relative_spectrum(fibre.right_projection().coordinate_algebra_morphism())
    assert changed.arrow() is fibre.right_projection()
    assert changed.arrow().domain() is fibre
