r"""Quasi-coherent sheaves on affine schemes: restriction, refinement, stalks, direct and inverse images, relative Spec."""

from dzack_research.preamble.all import (
    QQ,
    Algebras,
)








def test_direct_and_inverse_images_along_the_cusp_parametrization() -> None:
    plane = AffineSpaces(QQ)(2, names=("x", "y"))
    algebra = plane.coordinate_ring()
    x = algebra.algebra_generator("x")
    y = algebra.algebra_generator("y")
    line = QQ.polynomial_ring("t")
    t = line.algebra_generator("t")
    parametrization = Algebras(QQ).Associative().Unital().Commutative().spectrum()(algebra.Mor(line)({"x": t**2, "y": t**3}))
    affine_line = parametrization.domain()

    # f_* of the structure sheaf of the line is QQ[t] read as a QQ[x,y]-module
    # through x -> t^2, y -> t^3: the pushforward of the free rank-one sheaf.
    structure = affine_line.associated_module_sheaf(line.free_module(1))
    pushed = parametrization.direct_image(structure)
    assert pushed.scheme() is plane
    assert pushed.global_sections().base_ring() is algebra
    section = pushed.global_sections()(structure.global_sections().module_generator(0))
    scaled = pushed.global_sections().scalar_multiple(x, section)
    assert scaled.underlying_element() == structure.global_sections().scalar_multiple(
        t**2, structure.global_sections().module_generator(0)
    )
    open_x = plane.distinguished_open(x)
    assert pushed.sections_on_distinguished_open(open_x).base_ring() is open_x.coordinate_algebra()

    # f^* of the ideal sheaf of the cusp is a module whose only relation is killed:
    # y^2 - x^3 pulls back to zero, so f^*(I~) is generated by one element with zero relation.
    cusp = plane.closed_subscheme(y**2 - x**3)
    ideal_sheaf = cusp.ideal_sheaf()
    pulled = parametrization.module_pullback(ideal_sheaf)
    assert pulled.scheme() is affine_line
    pulled_module = pulled.global_sections()
    assert pulled_module.base_ring() is line
    assert pulled_module.module_generating_set().cardinality() == 1


def test_relative_spec_is_compatible_with_base_change() -> None:
    r"""``Spec_{X'}(B tensor_A A') = Spec_X(B) x_X X'`` for the double cover ``z^2 = x`` of the line."""
    line = AffineSpaces(QQ)(1, names=("x",))
    algebra = line.coordinate_ring()
    x = algebra.algebra_generator("x")
    cover_presentation = QQ.polynomial_ring(("x", "z"))
    xc, z = cover_presentation.algebra_generators()
    cover_algebra = (cover_presentation).quotient_by_relations((z**2 - xc,))
    structure = algebra.Mor(cover_algebra)({"x": cover_algebra.algebra_generator("x")})
    relative = line.relative_spectrum(structure)

    assert relative.arrow().codomain() is line
    assert relative.arrow().domain() is (cover_algebra).affine_spectrum()
    assert relative.arrow().coordinate_algebra_morphism() is structure
    assert relative in line.scheme_category().SliceOver(line)

    # Base change along the closed point x = 1 gives Spec of QQ[z]/(z^2 - 1), two points.
    point_algebra = QQ.polynomial_ring("u")
    u = point_algebra.algebra_generator("u")
    point_map = Algebras(QQ).Associative().Unital().Commutative().spectrum()(algebra.Mor(point_algebra)({"x": point_algebra.one()}))
    fibre = point_map.codomain().scheme_category().fiber_product(relative.arrow(), point_map)
    fibre_algebra = fibre.coordinate_algebra()
    zf = fibre_algebra.algebra_generator(("left", "z"))
    assert zf**2 == fibre_algebra.one()
    changed = point_map.domain().relative_spectrum(fibre.right_projection().coordinate_algebra_morphism())
    assert changed.arrow() == fibre.right_projection()
    assert changed.arrow().domain() is fibre
    assert changed.arrow().codomain() is point_map.domain()
