r"""Torus-invariant divisors on the projective plane: orders of characters, Cartier data,
positivity and complete linear systems.

``P^2`` is the toric variety of the fan with rays ``u_0 = -e_1 - e_2``, ``u_1 = e_2``,
``u_2 = e_1`` (Cox--Little--Schenck, *Toric Varieties*, Example 3.1.10).  The claims are
CLS Prop. 4.1.2 (``div(chi^m) = sum <m, u_rho> D_rho``), Thm. 4.2.8 (Cartier data),
Thm. 6.1.7 and 6.1.14 (basepoint freeness and ampleness by convexity) and
Prop. 4.3.3 (sections are the lattice points of ``P_D``).
"""

from dzack_research.preamble.all import *


def _projective_plane():
    return RationalPolyhedralFans(ZZ.free_module(2)).projective_space_fan().toric_variety(QQ)


def _ray(plane, generator):
    return next(ray for ray in plane.fan().cones(1) if ray.rays()[0] == plane.cocharacter_lattice()(generator))


def test_the_order_of_a_character_along_each_invariant_prime_is_its_pairing_with_the_ray() -> None:
    r"""For ``m = e_1^*``: ``<m, u_0> = -1``, ``<m, u_1> = 0``, ``<m, u_2> = 1``, so
    ``div(chi^m) = -D_0 + D_2`` (CLS Prop. 4.1.2)."""
    plane = _projective_plane()
    m = plane.character_lattice()((1, 0))
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))
    d2 = plane.torus_invariant_prime_divisor(_ray(plane, (1, 0)))

    assert plane.order_of_character_along_prime_divisor(m, _ray(plane, (-1, -1))) == -1
    assert plane.order_of_character_along_prime_divisor(m, _ray(plane, (0, 1))) == 0
    assert plane.order_of_character_along_prime_divisor(m, _ray(plane, (1, 0))) == 1
    assert plane.principal_divisor_of_character(m) == d2 - d0


def test_the_multiplicities_of_twice_an_invariant_line() -> None:
    r"""``2 D_0`` has multiplicity 2 along ``D_0`` and 0 along ``D_1`` and ``D_2``."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))

    assert plane.weil_multiplicity(2 * d0, _ray(plane, (-1, -1))) == 2
    assert plane.weil_multiplicity(2 * d0, _ray(plane, (0, 1))) == 0
    assert plane.weil_multiplicity(2 * d0, _ray(plane, (1, 0))) == 0


def test_the_local_restriction_of_a_line_sees_only_the_rays_of_the_chart() -> None:
    r"""The right-hand side ``sum_{rho in sigma(1)} -a_rho D_rho`` of the Cartier equations
    (CLS Thm. 4.2.8) for ``D_0`` is ``-D_0`` on a cone containing ``u_0`` and ``0`` on the cone
    ``Cone(u_1, u_2)`` that does not."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))
    u0 = _ray(plane, (-1, -1))
    containing = next(cone for cone in plane.fan().maximal_cones() if u0.is_face_of(cone))
    missing = next(cone for cone in plane.fan().maximal_cones() if not u0.is_face_of(cone))
    local_containing = plane.local_divisor_group(containing)
    local_missing = plane.local_divisor_group(missing)

    assert plane.local_divisor_restriction(d0, containing) == -local_containing.module_generator(u0)
    assert plane.local_divisor_restriction(d0, missing) == local_missing.zero()


def test_the_cartier_datum_of_a_line_on_the_chart_of_u0_and_u1_is_e1_star() -> None:
    r"""On ``sigma = Cone(u_0, u_1)`` the Cartier datum ``m_sigma`` of ``D_0`` solves
    ``<m, u_0> = -1`` and ``<m, u_1> = 0``, so ``m_sigma = e_1^*``; on ``Cone(u_1, u_2)`` it solves
    ``<m, u_1> = <m, u_2> = 0``, so ``m_sigma = 0`` (CLS Thm. 4.2.8)."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))
    u0 = _ray(plane, (-1, -1))
    u1 = _ray(plane, (0, 1))
    u2 = _ray(plane, (1, 0))
    characters = plane.character_lattice()
    chart_01 = next(cone for cone in plane.fan().maximal_cones() if u0.is_face_of(cone) and u1.is_face_of(cone))
    chart_12 = next(cone for cone in plane.fan().maximal_cones() if u1.is_face_of(cone) and u2.is_face_of(cone))

    assert plane.is_cartier(d0)
    assert plane.cartier_datum(d0, chart_01) == characters((1, 0))
    assert plane.cartier_datum(d0, chart_12) == characters.zero()


def test_a_line_on_the_projective_plane_is_basepoint_free_and_ample() -> None:
    r"""``O(1)`` on ``P^2`` is generated by its sections and ample (CLS Thm. 6.1.7, 6.1.14)."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))

    assert plane.is_basepoint_free(d0)
    assert plane.is_ample(d0)


def test_the_canonical_divisor_of_the_projective_plane_is_neither_ample_nor_basepoint_free() -> None:
    r"""``K = -D_0 - D_1 - D_2`` has degree ``-3`` (CLS Thm. 8.2.3); a divisor of negative degree on
    ``P^2`` has no sections, so it is not basepoint free and not ample."""
    plane = _projective_plane()
    canonical = plane.canonical_divisor()

    assert canonical == -plane.toric_boundary_divisor()
    assert not plane.is_basepoint_free(canonical)
    assert not plane.is_ample(canonical)


def test_the_complete_linear_system_of_conics_is_a_projective_five_space() -> None:
    r"""``h^0(P^2, O(2)) = 6``, the lattice points of ``2 P_{D_0}``, so ``|2 D_0| = P^5``."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))

    assert plane.complete_linear_system(2 * d0).dimension() == 5
    assert plane.complete_linear_system(d0).dimension() == 2


def test_the_sections_of_conics_are_the_six_lattice_points_of_twice_the_triangle() -> None:
    r"""``P_{2 D_0}`` is the triangle with vertices ``0, 2 e_1^*, 2 e_2^*`` in the coordinates where
    ``<m, u_0> >= -2``, ``<m, u_1> >= 0``, ``<m, u_2> >= 0``: six lattice points (CLS Prop. 4.3.3)."""
    plane = _projective_plane()
    d0 = plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1)))

    assert plane.divisor_section_characters(2 * d0).cardinality() == 6
    assert plane.divisor_section_space(2 * d0).dimension() == 6


def test_the_section_ring_of_a_line_is_the_homogeneous_coordinate_ring() -> None:
    r"""``bigoplus_k H^0(P^2, O(k)) = Q[x_0, x_1, x_2]``, a polynomial ring in three variables."""
    plane = _projective_plane()
    ring = plane.section_ring(plane.torus_invariant_prime_divisor(_ray(plane, (-1, -1))))

    assert ring.krull_dimension() == 3
    assert ring.algebra_generating_set().cardinality() == 3


def test_invariant_curves_of_the_projective_plane_are_its_three_rays() -> None:
    r"""The torus-invariant one-cycles on ``P^2`` are free on the three invariant lines, one for
    each ray (orbit--cone correspondence, CLS Thm. 3.2.6)."""
    plane = _projective_plane()

    assert plane.torus_orbits(1).cardinality() == 3
    assert plane.torus_orbits(0).cardinality() == 3
    assert plane.torus_orbits(2).cardinality() == 1
    assert plane.torus_invariant_cycle_group(1).module_rank() == 3
