r"""Fans in a cocharacter lattice, their cones, and the character pairing.

The stated values are Cox--Little--Schenck, *Toric Varieties*: the fan of
``P^n`` is Example 3.1.10, the Hirzebruch fans are Example 3.1.16, and the
three semigroup generators of the ``A_1`` cone are Example 1.2.22.
"""

from dzack_research.preamble.all import *


# One rank-two cocharacter lattice for the whole file: a free module is a
# fresh object on every construction, so building it twice would give two
# unrelated categories of fans.
_PLANE_FANS = RationalPolyhedralFans(ZZ.free_module(2))


def _plane_fans():
    return _PLANE_FANS


def test_the_fan_of_the_projective_plane_has_three_rays_and_seven_cones() -> None:
    fan = _plane_fans().projective_space_fan()

    assert fan.dimension() == 2
    assert fan.rays().cardinality() == 3
    assert fan.maximal_cones().cardinality() == 3
    assert fan.cones(0).cardinality() == 1
    assert fan.cones(1).cardinality() == 3
    assert fan.cones(2).cardinality() == 3
    assert fan.cardinality() == 7
    assert fan.is_complete()
    assert fan.is_smooth()






def test_the_a_one_cone_needs_three_semigroup_generators_and_is_singular() -> None:
    r"""CLS Example 1.2.22: ``Cone((0,1),(2,-1))`` has ``S_sigma`` generated by
    three characters, whose one relation presents the quadric cone."""
    fan = _plane_fans()((((0, 1), (2, -1)),))
    cone = fan.maximal_cones()[0]

    assert cone.dimension() == 2
    assert not cone.is_smooth()
    assert cone.is_simplicial()
    assert cone.semigroup_generators().cardinality() == 3








def test_hirzebruch_fans_are_smooth_complete_and_pairwise_distinguished() -> None:
    r"""``F_0`` is ``P^1 x P^1`` and ``F_1`` is the blow-up of ``P^2`` at a
    point, so no lattice isomorphism carries one fan onto the other."""
    fans = _plane_fans()
    zeroth = fans.hirzebruch_surface_fan(0)
    first = fans.hirzebruch_surface_fan(1)

    assert zeroth.rays().cardinality() == 4
    assert zeroth.maximal_cones().cardinality() == 4
    assert zeroth.is_smooth()
    assert zeroth.is_complete()
    assert first.is_smooth()
    assert first.is_complete()

    assert zeroth.is_isomorphic(fans.hirzebruch_surface_fan(0))
    assert not zeroth.is_isomorphic(first)
    assert not first.is_isomorphic(fans.projective_space_fan())


def test_the_weighted_projective_plane_of_weights_one_is_the_projective_plane() -> None:
    fans = _plane_fans()
    weighted = fans.weighted_projective_space_fan((1, 1, 1))

    assert weighted.is_isomorphic(fans.projective_space_fan())
    assert fans.weighted_projective_space_fan((1, 1, 2)).is_smooth() is False
