r"""Cyclic covers of an affine base: deck action, ramification, branch locus, quotient.

The running specimen is the double cover ``Y: z^2 = x^4 - 1`` of the affine line
over the rationals, the affine chart of a genus-one curve.  Its deck involution is
``z -> -z``; its ramification locus is ``V(z)``; its branch locus is
``V(x^4 - 1)``, a zero-dimensional subscheme of degree four; and its quotient by
the deck group is the line it covers.  The trivial cover ``z^2 = 1`` is the
unramified contrast.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def _double_cover():
    R = QQ['x']
    x = R.gen()
    Y = R.affine_spectrum().cyclic_cover(2, x**4 - 1)
    return R, x, Y


def test_the_deck_involution_of_z2_equals_x4_minus_1_negates_z_and_fixes_exactly_v_z() -> None:
    r"""The deck involution of ``z^2 = f`` is ``z -> -z``, ``x -> x``; its fixed locus is ``V(z)``.

    Derivation: ``mu_2`` acts by ``z -> zeta z``; the fixed ideal is generated by
    ``(zeta - 1) z = -2z``, which is ``(z)`` since 2 is a unit in ``QQ``.
    """
    R, x, Y = _double_cover()
    B = Y.coordinate_ring()
    z = B.algebra_generator("z")
    G = Y.deck_group()
    sigma = Y.deck_transformation(G.gen())

    assert G.cardinality() == 2
    assert sigma.pullback(z) == -z
    assert sigma.pullback(B(x)) == B(x)
    assert sigma * sigma == Y.identity_morphism()
    assert Y.fixed_locus(G).defining_ideal() == B.ideal(z)
    assert Y.fixed_locus(G).defining_ideal() != B.unit_ideal()


def test_the_branch_locus_of_z2_equals_x4_minus_1_is_v_of_x4_minus_1_of_degree_four() -> None:
    r"""The branch locus of ``z^2 = f`` is ``V(f)``; here ``QQ[x]/(x^4 - 1)`` has degree 4 over ``QQ``.

    Over ``QQ`` it has three closed points, ``x = 1``, ``x = -1`` and ``x^2 = -1``
    (residue degrees 1, 1, 2), summing to degree 4.  Derivation:
    ``x^4 - 1 = (x - 1)(x + 1)(x^2 + 1)``.
    """
    R, x, Y = _double_cover()
    branch = Y.branch_locus()

    assert branch.defining_ideal() == R.ideal(x**4 - 1)
    assert branch.dimension() == 0
    assert branch.degree() == 4
    assert Y.ramification_locus().dimension() == 0
    assert Y.dimension() == 1


def test_the_ramification_ideal_of_z3_equals_x_over_gf7_is_z_squared() -> None:
    r"""For the tame cover ``z^3 = x`` over ``GF(7)`` the different is ``(3 z^2) = (z^2)``.

    Derivation: ``B = GF(7)[z]`` over ``A = GF(7)[x]``, ``x = z^3``, so
    ``Omega_{B/A} = B dz / (3 z^2 dz)`` and 3 is a unit mod 7 (Neukirch, *Algebraic
    Number Theory*, III.2.6: the tame different has exponent ``e - 1 = 2``).
    """
    R = GF(7)['x']
    x = R.gen()
    Y = R.affine_spectrum().cyclic_cover(3, x)
    z = Y.coordinate_ring().algebra_generator("z")
    ramification = Y.ramification_locus().defining_ideal()

    assert z**2 in ramification
    assert z not in ramification


def test_the_invariant_ring_of_the_double_cover_is_the_coordinate_ring_of_the_base() -> None:
    r"""``(QQ[x, z]/(z^2 - x^4 + 1))^{mu_2} = QQ[x]``, so ``Y / mu_2`` is the affine line.

    Derivation: ``B = QQ[x] + QQ[x] z`` and the involution acts by ``+1`` and ``-1``
    on the two summands.
    """
    R, x, Y = _double_cover()
    B = Y.coordinate_ring()
    z = B.algebra_generator("z")
    invariants = B.invariant_subring(Y.deck_group())

    assert B(x) in invariants
    assert z**2 in invariants
    assert z not in invariants
    assert x * z not in invariants
    assert Y.quotient(Y.deck_group()).coordinate_ring().krull_dimension() == 1
    assert Y.quotient(Y.deck_group()).is_isomorphic(R.affine_spectrum())


def test_the_cover_z2_equals_1_is_etale_with_free_deck_action() -> None:
    r"""``z^2 = 1`` over ``QQ[x]`` is two disjoint copies of the line: étale, with free deck action.

    Derivation: ``z`` is a unit, so the fixed ideal ``(2z)`` is the unit ideal;
    ``QQ[x, z]/(z^2 - 1) = QQ[x] x QQ[x]`` by ``z -> (1, -1)``.
    """
    R = QQ['x']
    Y = R.affine_spectrum().cyclic_cover(2, R.one())
    B = Y.coordinate_ring()

    assert Y.fixed_locus(Y.deck_group()).defining_ideal() == B.unit_ideal()
    assert Y.structure_morphism().is_etale()
    assert Y.branch_locus().defining_ideal() == R.unit_ideal()
    assert Y.connected_components().cardinality() == 2
