r"""Direct and inverse images along the cusp parametrization, and relative Spec under base change."""

from dzack_research.preamble.all import QQ, AffineSpaces, Algebras, Schemes


def test_direct_and_inverse_images_along_the_cusp_parametrization() -> None:
    r"""For `f: \mathbb{A}^1 \to \mathbb{A}^2`, `t \mapsto (t^2, t^3)`:
    `f_* \mathcal{O}` is `\mathbb{Q}[t]` with `x` acting as `t^2`, minimally generated
    over `\mathbb{Q}[x, y]` by `1` and `t`; `f^*` of the ideal sheaf of the cusp
    `y^2 = x^3` is generated by one section, and since `(t^3)^2 - (t^2)^3 = 0` the
    scheme-theoretic inverse image of the cusp is all of `\mathbb{A}^1`."""
    plane = AffineSpaces(QQ)(2, names=("x", "y"))
    algebra = plane.coordinate_ring()
    x = algebra.algebra_generator("x")
    y = algebra.algebra_generator("y")
    line_ring = QQ.polynomial_ring("t")
    t = line_ring.algebra_generator("t")
    spec = Algebras(QQ).Associative().Unital().Commutative().spectrum()
    parametrization = spec(algebra.Mor(line_ring)({"x": t**2, "y": t**3}))
    line = parametrization.domain()

    pushed = parametrization.direct_image(line.structure_sheaf()).global_sections()
    one = pushed(line_ring.one())
    assert x * one == pushed(t**2)
    assert y * one == pushed(t**3)
    assert pushed.minimal_generating_set().cardinality() == 2

    cusp = plane.closed_subscheme(y**2 - x**3)
    pulled = parametrization.module_pullback(cusp.ideal_sheaf()).global_sections()
    assert pulled.minimal_generating_set().cardinality() == 1
    assert parametrization.inverse_image(cusp) == line


def test_relative_spec_of_the_double_cover_z_squared_equals_x_under_base_change() -> None:
    r"""The fibre of `\operatorname{Spec}_{\mathbb{A}^1} \mathbb{Q}[x, z]/(z^2 - x)` over
    `x = 1` is `\operatorname{Spec} \mathbb{Q}[z]/(z^2 - 1)`, two reduced points; over
    `x = 0` it is `\operatorname{Spec} \mathbb{Q}[z]/(z^2)`, not reduced."""
    line = AffineSpaces(QQ)(1, names=("x",))
    algebra = line.coordinate_ring()
    presentation = QQ.polynomial_ring(("x", "z"))
    xc, z = presentation.algebra_generators()
    cover_algebra = presentation.quotient_by_relations((z**2 - xc,))
    cover = line.relative_spectrum(
        algebra.Mor(cover_algebra)({"x": cover_algebra.algebra_generator("x")})
    )
    spec = Algebras(QQ).Associative().Unital().Commutative().spectrum()

    def fibre_over(value):
        point = spec(algebra.Mor(QQ)({"x": QQ(value)}))
        return Schemes(QQ).fiber_product(cover.arrow(), point)

    over_one = fibre_over(1)
    over_zero = fibre_over(0)
    assert over_one.coordinate_ring().dimension() == 2
    assert over_one.is_reduced()
    assert over_one.connected_components().cardinality() == 2
    assert over_zero.coordinate_ring().dimension() == 2
    assert not over_zero.is_reduced()
