r"""Fans in a cocharacter lattice, their cones, and the character pairing.

The stated values are Cox--Little--Schenck, *Toric Varieties*: the fan of
``P^n`` is Example 3.1.10, the Hirzebruch fans are Example 3.1.16, and the
three semigroup generators of the ``A_1`` cone are Example 1.2.22.
"""

from dzack_research.preamble.all import (
    BasedFreeModule,
    RationalPolyhedralFans,
    ZZ,
)


# One rank-two cocharacter lattice for the whole file: a free module is a
# fresh object on every construction, so building it twice would give two
# unrelated categories of fans.
_PLANE_FANS = RationalPolyhedralFans(BasedFreeModule(ZZ, 2))


def _plane_fans():
    return _PLANE_FANS


def test_the_fan_of_the_projective_plane_has_three_rays_and_seven_cones() -> None:
    fan = _plane_fans().projective_space_fan()

    assert fan.dimension() == 2
    assert fan.rays().cardinality() == 3
    assert fan.maximal_cones().cardinality() == 3
    assert fan.cones(0).cardinality() == 1
    assert fan.cones(1).cardinality() == 3
    assert fan.cones(2).cardinality() == 3
    assert fan.cardinality() == 7
    assert fan.is_complete()
    assert fan.is_smooth()


def test_the_trivial_fan_is_the_single_zero_cone_and_is_not_complete() -> None:
    fan = _plane_fans().trivial_fan()

    assert fan.cardinality() == 1
    assert fan.rays().cardinality() == 0
    assert fan.cones(0).cardinality() == 1
    assert not fan.is_complete()
    assert fan.is_smooth()


def test_the_character_pairing_is_the_duality_of_the_two_frames() -> None:
    fans = _plane_fans()
    cocharacters = fans.cocharacter_lattice()
    characters = fans.character_lattice()
    pairing = fans.character_cocharacter_pairing()

    assert characters is not cocharacters
    first, second = tuple(cocharacters.module_generating_set())

    assert pairing(characters.module_generator(first), cocharacters.module_generator(first)) == 1
    assert pairing(characters.module_generator(first), cocharacters.module_generator(second)) == 0
    assert pairing(characters.module_generator(second), cocharacters.module_generator(second)) == 1

    doubled = cocharacters.linear_combination({first: ZZ(3), second: ZZ(-2)})
    assert pairing(characters.module_generator(first), doubled) == 3
    assert pairing(characters.module_generator(second), doubled) == -2


def test_the_a_one_cone_needs_three_semigroup_generators_and_is_singular() -> None:
    r"""CLS Example 1.2.22: ``Cone((0,1),(2,-1))`` has ``S_sigma`` generated by
    three characters, whose one relation presents the quadric cone."""
    fan = _plane_fans()((((0, 1), (2, -1)),))
    cone = fan.maximal_cones()[0]

    assert cone.dimension() == 2
    assert not cone.is_smooth()
    assert cone.is_simplicial()
    assert cone.semigroup_generators().cardinality() == 3


def test_a_basis_cone_is_smooth_and_has_the_dual_basis_as_its_semigroup() -> None:
    fan = _plane_fans()((((1, 0), (0, 1)),))
    cone = fan.maximal_cones()[0]

    assert cone.is_smooth()
    assert cone.semigroup_generators().cardinality() == 2


def test_the_dual_cone_is_decided_by_the_pairing_on_the_rays() -> None:
    fans = _plane_fans()
    characters = fans.character_lattice()
    first, second = tuple(characters.module_generating_set())
    fan = fans((((0, 1), (2, -1)),))
    cone = fan.maximal_cones()[0]

    assert cone.dual_cone_contains(characters.module_generator(first))
    assert not cone.dual_cone_contains(characters.module_generator(second))
    assert not cone.orthogonal_contains(characters.module_generator(first))


def test_faces_of_a_two_dimensional_cone_are_its_rays_and_the_origin() -> None:
    fan = _plane_fans().projective_space_fan()
    cone = fan.maximal_cones()[0]

    assert cone.faces(1).cardinality() == 2
    assert cone.faces(0).cardinality() == 1
    for face in cone.faces(1):
        assert face.is_face_of(cone)
    assert cone.is_face_of(cone)


def test_hirzebruch_fans_are_smooth_complete_and_pairwise_distinguished() -> None:
    r"""``F_0`` is ``P^1 x P^1`` and ``F_1`` is the blow-up of ``P^2`` at a
    point, so no lattice isomorphism carries one fan onto the other."""
    fans = _plane_fans()
    zeroth = fans.hirzebruch_surface_fan(0)
    first = fans.hirzebruch_surface_fan(1)

    assert zeroth.rays().cardinality() == 4
    assert zeroth.maximal_cones().cardinality() == 4
    assert zeroth.is_smooth()
    assert zeroth.is_complete()
    assert first.is_smooth()
    assert first.is_complete()

    assert zeroth.is_isomorphic(fans.hirzebruch_surface_fan(0))
    assert not zeroth.is_isomorphic(first)
    assert not first.is_isomorphic(fans.projective_space_fan())


def test_the_weighted_projective_plane_of_weights_one_is_the_projective_plane() -> None:
    fans = _plane_fans()
    weighted = fans.weighted_projective_space_fan((1, 1, 1))

    assert weighted.is_isomorphic(fans.projective_space_fan())
    assert fans.weighted_projective_space_fan((1, 1, 2)).is_smooth() is False
