r"""Picard and class groups of the affine and projective plane over QQ.

Source: Hartshorne, *Algebraic Geometry*, II.6.2 and II.6.4: `\mathbb{Q}[x, y]` is a
UFD, so `\operatorname{Cl}(\mathbb{A}^2) = 0`; `\operatorname{Cl}(\mathbb{P}^2) =
\mathbb{Z}` generated by a line, and on these smooth schemes `\operatorname{Pic} =
\operatorname{Cl}` (II.6.16).
"""

from dzack_research.preamble.all import QQ, AffineSpaces, ProjectiveSpaces


def test_affine_plane_has_trivial_picard_and_class_groups() -> None:
    plane = AffineSpaces(QQ)(2, names=("x", "y"))

    assert plane.picard_group().module_rank() == 0
    assert plane.picard_group().cardinality() == 1
    assert plane.class_group().cardinality() == 1


def test_projective_plane_has_picard_and_class_group_z_generated_by_a_line() -> None:
    plane = ProjectiveSpaces(QQ)(2, names=("x", "y", "z"))
    picard = plane.picard_group()
    hyperplane = picard.hyperplane_class()
    x, y, z = plane.homogeneous_coordinate_generators()
    conic = plane.closed_subscheme(x * z - y**2)

    assert picard.module_rank() == 1
    assert plane.class_group().module_rank() == 1
    assert hyperplane != picard.zero()
    assert picard.module_generators() == {hyperplane}
    assert plane.divisor_class(conic) == 2 * hyperplane
