r"""Graded pieces and products of the four free constructions on a free module."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_degree_two_ranks_of_tensor_symmetric_exterior_and_divided_power_algebras() -> None:
    r"""For ``M`` free of rank 2: ``rank T^2 = 4``, ``rank Sym^2 = 3``,
    ``rank Λ^2 = 1``, ``rank Γ^2 = 3``, and ``Λ^3 = 0``.  Derivation:
    ``2^2``, ``binom(3, 2)``, ``binom(2, 2)``, ``binom(3, 2)``, ``binom(2, 3)``."""
    module = Modules(QQ).free_module(("x", "y"))

    assert module.tensor_algebra().graded_piece(2).module_rank() == 4
    assert module.symmetric_algebra().graded_piece(2).module_rank() == 3
    assert module.exterior_algebra().graded_piece(2).module_rank() == 1
    assert module.divided_power_algebra().graded_piece(2).module_rank() == 3
    assert module.exterior_algebra().graded_piece(3).module_rank() == 0
    assert module.tensor_algebra().graded_piece(3).module_rank() == 8


def test_divided_powers_and_symmetric_powers_have_equal_ranks_but_different_products() -> None:
    r"""Over ``ZZ``, ``Γ^n(ZZ^2)`` and ``Sym^n(ZZ^2)`` are both free of rank
    ``n + 1``, but ``x · x = 2 γ_2(x)`` in ``Γ`` whereas ``x · x`` is a basis
    element of ``Sym^2``."""
    module = Modules(ZZ).free_module(("x", "y"))
    divided = module.divided_power_algebra()
    symmetric = module.symmetric_algebra()

    for degree in range(4):
        assert divided.graded_piece(degree).module_rank() == degree + 1
        assert symmetric.graded_piece(degree).module_rank() == degree + 1
    x = divided.degree_one_generator("x")
    assert x * x == 2 * divided.divided_power(x, 2)
    assert x * x != divided.divided_power(x, 2)


def test_divided_power_ideal_of_2x_contains_gamma_3_of_2x_outside_the_ordinary_ideal() -> None:
    r"""In ``Γ(ZZ x)``: ``γ_3(2x) = 8 γ_3(x)`` lies in the divided power ideal
    generated by ``2x``, but the ordinary ideal meets degree 3 in
    ``2x · ZZ γ_2(x) = 6 ZZ γ_3(x)``, which does not contain ``8 γ_3(x)``."""
    divided = Modules(ZZ).free_module(("x",)).divided_power_algebra()
    x = divided.degree_one_generator("x")
    gamma_3_of_2x = divided.divided_power(2 * x, 3)

    assert gamma_3_of_2x == 8 * divided.divided_power(x, 3)
    assert gamma_3_of_2x in divided.divided_power_ideal([2 * x])
    assert gamma_3_of_2x not in divided.ideal([2 * x])
    assert 6 * divided.divided_power(x, 3) in divided.ideal([2 * x])


def test_a_map_of_polynomial_algebras_is_determined_by_generator_images() -> None:
    r"""The universal property of ``Sym``: ``x ↦ v``, ``y ↦ w`` extends uniquely
    to ``QQ[x, y] -> QQ[u, v, w]``, sending ``x^2 y + 3`` to ``v^2 w + 3``."""
    source = Modules(QQ).free_module(("x", "y")).symmetric_algebra()
    target = Modules(QQ).free_module(("u", "v", "w")).symmetric_algebra()
    x, y = source.algebra_generator("x"), source.algebra_generator("y")
    v, w = target.algebra_generator("v"), target.algebra_generator("w")
    morphism = source.Mor(target)({x: v, y: w})

    assert morphism(x * y) == v * w
    assert morphism(x**2 * y + 3) == v**2 * w + 3


def test_sign_rule_for_permuted_triple_products_in_the_exterior_algebra() -> None:
    r"""In ``Λ(QQ^3)``: ``zxy = xyz`` (a cyclic, hence even, permutation),
    ``yxz = -xyz`` (a transposition), and ``xyz ≠ 0``."""
    exterior = Modules(QQ).free_module(("x", "y", "z")).exterior_algebra()
    x, y, z = (exterior.algebra_generator(label) for label in ("x", "y", "z"))

    assert (x * y) * z == x * (y * z)
    assert z * x * y == x * y * z
    assert y * x * z == -(x * y * z)
    assert x * y * z != exterior.zero()
    assert x * y * x == exterior.zero()


def test_second_tensor_power_of_the_plane_contains_xy_but_not_x() -> None:
    r"""``T^2(QQ^2)`` has rank 4 and contains ``xy`` and ``yx`` but not ``x``."""
    tensor = Modules(QQ).free_module(("x", "y")).tensor_algebra()
    piece = tensor.graded_piece(2)
    x, y = tensor.algebra_generator("x"), tensor.algebra_generator("y")

    assert piece.module_rank() == 4
    assert x * y in piece
    assert y * x in piece
    assert x not in piece
    assert x + x * y not in piece
