r"""Cokernels of Lie algebra maps are quotients by the generated Lie ideal."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_cartan_inclusion_into_sl2_has_zero_lie_cokernel_but_module_cokernel_of_rank_two() -> None:
    r"""In ``sl_2(QQ)`` with ``[h, e] = 2e``, ``[h, f] = -2f``, ``[e, f] = h``, the
    ideal generated by ``h`` contains ``e = [h, e]/2`` and ``f = -[h, f]/2``, so it
    is all of ``sl_2``: the Lie cokernel of ``QQ h -> sl_2`` is zero, while the
    cokernel of the underlying linear map has rank ``3 - 1 = 2``."""
    module = Modules(QQ).free_module(("e", "f", "h"))
    e, f, h = (module.module_generator(label) for label in ("e", "f", "h"))
    zero = module.zero()
    sl2 = Algebras(QQ).Lie()(
        module,
        {
            ("e", "e"): zero, ("f", "f"): zero, ("h", "h"): zero,
            ("h", "e"): 2 * e, ("e", "h"): -2 * e,
            ("h", "f"): -2 * f, ("f", "h"): 2 * f,
            ("e", "f"): h, ("f", "e"): -h,
        },
    )
    line = Modules(QQ).free_module(("h",))
    cartan = Algebras(QQ).Lie()(line, {("h", "h"): line.zero()})
    inclusion = cartan.Mor(sl2)({cartan(line.module_generator("h")): sl2(h)})

    assert sl2(h) * sl2(e) == 2 * sl2(e)
    assert sl2(e) * sl2(f) == sl2(h)
    assert inclusion.cokernel().module_rank() == 0
    assert inclusion.underlying_module_morphism().cokernel().module_rank() == 2
