# General mathematical contract for Sage's element hierarchy, verified by
# lexicon/verify_against_sage.py. The linear-algebra classes are generic in
# their scalar (any RingElement regime: exact, symbolic, p-adic, real, ...);
# the type parameter DEFAULTS to its bound RingElement — the mathematically
# true statement that the entries of any Sage matrix/vector are elements of
# its base ring. Exact regimes are never assumed by the bare name: they are
# spelled where known (`Matrix[Integer | Rational]`).
import builtins
from collections.abc import Iterator, Sequence
from typing import Any, Generic, Literal, Self, TypeVar, overload

from cypari2.gen import Gen
from sage.categories.rings import Rings
from sage.modules.free_module import FreeModule_generic
from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_element import Polynomial
from sage.rings.rational import Rational
from sage.structure.parent import Parent

class Element:
    def __init__(self, parent: Parent) -> None: ...
    def parent(self) -> Parent: ...
    # Every element knows the ring its parent is based over
    # (sage/structure/element.pyx: Element.base_ring delegates to the parent).
    def base_ring(self) -> Rings.ParentMethods: ...
    def is_zero(self) -> bool: ...
    # Arithmetic enters through the coercion model on Element itself; negation
    # is parent-preserving.
    # ``Element`` and not ``Self``: negation usually stays in the element's
    # own class (subclasses narrow covariantly), but on the extended reals it
    # exchanges the poles, -(+oo) = -oo, and a Self return would outlaw that
    # true statement.
    def __neg__(self) -> Element: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ModuleElement(Element):
    # Order in the additive sense; Sage's ModuleElement.order is the alias
    # that must not be overridden (additive_order carries the implementation).
    def order(self) -> Integer: ...
    def additive_order(self) -> Integer: ...

class MonoidElement(Element): ...
class MultiplicativeGroupElement(MonoidElement): ...

class RingElement(ModuleElement):
    # An element of a ring has a ring parent (category-first: the parent's
    # type is the category's ParentMethods; INVENTORY.md II.2).
    def __neg__(self) -> RingElement: ...
    def parent(self) -> Rings.ParentMethods: ...
    # Invertibility is supplied to every element of a ring parent by
    # Rings.ElementMethods.is_unit; the element hierarchy is where this repo
    # states element-side category surface (INVENTORY.md II.2 preamble).
    def is_unit(self) -> bool: ...
    # No generic ``__add__`` here: Sage's coercion pushout has no honest
    # common signature (Integer + Rational lands in QQ), so each concrete
    # element class declares its own precise arithmetic instead of
    # LSP-overriding a vague one.
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __abs__(self) -> Self: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class CommutativeRingElement(RingElement): ...
class FieldElement(CommutativeRingElement): ...

_Scalar = TypeVar("_Scalar", bound=RingElement, default=RingElement)

class Vector(ModuleElement, Generic[_Scalar]):
    # Sage vectors iterate through the legacy __getitem__/__len__ protocol;
    # the __iter__ claim states the mathematical truth (a coordinate vector is
    # a finite family of scalars) and is verified by probing iter() on a
    # representative instance, not by dir().
    def __iter__(self) -> Iterator[_Scalar]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int | Integer) -> _Scalar: ...
    def __neg__(self) -> Vector[_Scalar]: ...
    def __add__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    def __sub__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: Matrix[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: Vector[_Scalar]) -> _Scalar: ...
    @overload
    def __mul__(self, other: int | _Scalar) -> Vector[_Scalar]: ...
    def __rmul__(self, other: int | _Scalar) -> Vector[_Scalar]: ...
    def set_immutable(self) -> None: ...
    def __setitem__(self, i: int | Integer, value: object) -> None: ...
    def list(self) -> builtins.list[_Scalar]: ...
    def denominator(self) -> Integer: ...

class Matrix(ModuleElement, Generic[_Scalar]):
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    # The two sizes read off together (matrix0.pyx: returns (nrows, ncols)).
    def dimensions(self) -> tuple[int, int]: ...
    def rank(self) -> int: ...
    def det(self) -> _Scalar: ...
    def determinant(self) -> _Scalar: ...
    def transpose(self) -> Matrix[_Scalar]: ...
    def inverse(self) -> Matrix[_Scalar]: ...
    def is_square(self) -> bool: ...
    def is_symmetric(self) -> bool: ...
    # Identity matrix (matrix2.pyx: is_scalar(one)), asked of the matrix rather
    # than by comparing it against a separately built identity.
    def is_one(self) -> bool: ...
    def is_invertible(self) -> bool: ...
    def set_immutable(self) -> None: ...
    def is_immutable(self) -> bool: ...
    # ``copy(A)``: Sage declares it on Element (element.pyx) and the matrix
    # classes implement it (matrix_dense.pyx), carrying the subdivisions over.
    # The copy is MUTABLE, which is what lets a frozen one be made from it.
    def __copy__(self) -> Matrix[_Scalar]: ...
    def change_ring(self, ring: Parent) -> Matrix[Any]: ...
    def list(self) -> builtins.list[_Scalar]: ...
    def diagonal(self) -> builtins.list[_Scalar]: ...
    def rows(self) -> builtins.list[Vector[_Scalar]]: ...
    def columns(self) -> builtins.list[FreeModuleElement[_Scalar]]: ...
    def row(self, i: int | Integer) -> Vector[_Scalar]: ...
    def column(self, j: int | Integer) -> FreeModuleElement[_Scalar]: ...
    # A matrix iterates over its rows.
    def __iter__(self) -> Iterator[Vector[_Scalar]]: ...
    def stack(self, other: Matrix[_Scalar] | Vector[_Scalar]) -> Matrix[_Scalar]: ...
    def matrix_from_columns(self, columns: Sequence[int]) -> Matrix[_Scalar]: ...
    def matrix_from_rows(self, rows: Sequence[int | Integer]) -> Matrix[_Scalar]: ...
    def matrix_from_rows_and_columns(
        self,
        rows: Sequence[int | Integer],
        columns: Sequence[int | Integer],
    ) -> Matrix[_Scalar]: ...
    def augment(self, other: Matrix[_Scalar] | Vector[_Scalar]) -> Matrix[_Scalar]: ...
    def tensor_product(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    def right_kernel(self) -> FreeModule_generic[_Scalar]: ...
    def left_kernel(self) -> FreeModule_generic[_Scalar]: ...
    # The kernel MATRIX: rows spanning the nullspace, with no ambient-module
    # bookkeeping attached. Private to morphism construction (INVENTORY.md I.4).
    def right_kernel_matrix(
        self,
        algorithm: str = ...,
        basis: str = ...,
    ) -> Matrix[_Scalar]: ...
    def left_kernel_matrix(
        self,
        algorithm: str = ...,
        basis: str = ...,
    ) -> Matrix[_Scalar]: ...
    def row_space(self) -> FreeModule_generic[_Scalar]: ...
    def trace(self) -> _Scalar: ...
    def minimal_polynomial(self, var: str = ...) -> Polynomial: ...
    # Entrywise division by a nonzero scalar lands in the fraction field;
    # stated for the exact Integer|Rational regime this overlay covers.
    def __truediv__(self, other: int | _Scalar) -> Matrix[Rational]: ...
    def __pari__(self) -> Gen: ...
    # matrix2.pyx:5656 — free module over the base ring spanned by the rows.
    def row_module(self, base_ring: Parent | None = ...) -> FreeModule_generic[_Scalar]: ...
    def LLL_gram(self) -> Matrix[Integer]: ...
    def smith_form(self) -> tuple[Matrix[_Scalar], Matrix[_Scalar], Matrix[_Scalar]]: ...
    def characteristic_polynomial(self, var: str = ...) -> Polynomial: ...
    # Eigenvalues live in the algebraic closure of the base ring, not in it,
    # so the element type is the general ring element rather than _Scalar.
    def eigenvalues(self) -> Sequence[RingElement]: ...
    # Row reduction: Hermite over a PID, echelon over a field. With
    # transformation the unimodular U with U*self == H comes back alongside.
    @overload
    def hermite_form(
        self,
        include_zero_rows: bool = ...,
        transformation: Literal[False] = ...,
    ) -> Matrix[_Scalar]: ...
    @overload
    def hermite_form(
        self,
        include_zero_rows: bool,
        transformation: Literal[True],
    ) -> tuple[Matrix[_Scalar], Matrix[_Scalar]]: ...
    def echelon_form(self, algorithm: str = ...) -> Matrix[_Scalar]: ...
    # Subdivisions are display data on the matrix, not a mathematical operation.
    def subdivide(
        self,
        row_lines: Sequence[int] | None = ...,
        col_lines: Sequence[int] | None = ...,
    ) -> None: ...
    def subdivisions(self) -> tuple[builtins.list[int], builtins.list[int]]: ...
    def elementary_divisors(self) -> builtins.list[Integer]: ...
    def solve_left(self, other: Matrix[_Scalar] | Vector[_Scalar]) -> Any: ...
    def solve_right(self, other: Matrix[_Scalar] | Vector[_Scalar]) -> Any: ...
    def apply_map(self, f: Any) -> Matrix[Any]: ...
    def denominator(self) -> Integer: ...
    def __neg__(self) -> Matrix[_Scalar]: ...
    def __add__(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    def __sub__(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    @overload
    def __mul__(self, other: Matrix[_Scalar]) -> Matrix[_Scalar]: ...
    @overload
    def __mul__(self, other: Vector[_Scalar]) -> Vector[_Scalar]: ...
    @overload
    def __mul__(self, other: int | _Scalar) -> Matrix[_Scalar]: ...
    def __rmul__(self, other: int | _Scalar) -> Matrix[_Scalar]: ...
    def __pow__(self, n: int | Integer) -> Matrix[_Scalar]: ...
    def __getitem__(self, key: tuple[int | Integer, int | Integer]) -> _Scalar: ...
    def __setitem__(self, key: tuple[int | Integer, int | Integer], value: object) -> None: ...
