L = Lattice.A(4)
assert L in RootLattices # Cateegory promotion Lattice -> RootLattice
assert L.span(L.root_system()).is_isometric_to(L) # Root system = set of simple roots, which can be used to span a sublattice
assert L.root_system().inclusion().index() == 1 # Root lattices := lattices spanned by their root systems
assert {x for x in L.root_system()} == {x for x in L.gens()} # Generators are roots.

G = L.coxeter_diagram() # Defined for any RootLattice
P = G.subdiagram_poset()
assert P in Posets
assert {G_i for G_i in P} == {Lattice.A(n).coxeter_diagram() for n in [0,1,2,3,4]} # A_n has subdiagrams of the form A_{k} for all 0 <= k <= n, some with multiplicity

# A_4: (0) -- (1) -- (2) -- (3) 
# Each node has a self-loop/weight of -2 and edges of weight 1

assert P.max() == {G} # The set of maximal elements
assert P.min() == {G.subdiagram({})} # The set of minimal elements
assert G.subdiagram({0}) <= G.subdiagram({0,1})
assert G.subdiagram({0,1}) <= G.subdiagram({0,1,2})
assert G.subdiagram({0,1,2}).is_connected() and not G.subdiagram({0,2,3}).is_connected()
assert G.adjacency_matrix(weighted=False) == matrix(ZZ, 4, [
	[1,1,0,0],
	[1,1,1,0],
	[0,1,1,1],
	[0,0,1,1]
]) # TODO: check
# TODO: assert on G.adjacency_matrix(), which includes weights

# TODO: assert a diagram is parabolic
# TODO: assert G.parabolic_subdiagrams() == .... # It's a poset
# TODO: assert G.parabolic_subdiagrams().max() == .... # Set of all maximal parabolic subdiagrams
# TODO: assert G.elliptic_subdiagrams() == ... 
# TODO: assert G.elliptic_subdiaigrams().max() == ...
# TODO: 
# 	Aut_G = G.Aut() # Weight-preserving graph automorphisms
# 	assert P / Aut_G == .... # Orbits of subdiagrams under symmetry
# 	assert P.parabolic_subdiagrams() / Aut_G == ... 
# 	assert P.parabolic_subdiagrams().max() / Aut_G == ... 
# 	assert P.elliptic_subdiagrams() / Aut_G == ...

r1, r2, r3, r4 = L.gens()
assert all(v.is_root() for v in L.gens())
H1, H2, H3, H4 = [r.orthogonal_hyerplane() for r in L.gens()]
assert H1.angle_to(H2) == cos(pi/3)
assert H1.angle_to(H3) == cos(pi/2)
assert H3.angle_to(H4) == cos(pi/3)
# TODO: QQ_pi == QQ.adjoin(pi) # For exact symbolic arithmetic
# TODO: assert L.hyperplane_angle_matrix() == matrix(QQ_pi, 4, [
# 	[0, 		pi/3, 	pi/2, 	pi/2],
# 	[pi/3,	0,			pi/3, 	pi/2],
# 	[pi/2,	pi/3,		0, 			pi/3],
# 	[pi/2, 	pi/2, 	pi/3, 	0 	],
# ])
# TODO: assert formula cos(\angle(v_i, v_j)) = (r_i * r_j) / sqrt(r_i^2 * r_j^2)

# TODO: assert folding symmetries

G.<n1, n2, n3, n4> = L.coxeter_diagram() # Allow named nodes
Aut_G = G.Aut()
assert Aut_G.is_isomorphic_to(ZZ/2)

fold_4 == G.Hom(G).from_dict({
	n1: n4,
	n2: n3,
	n3: n2,
	n4: n1
})
# Fold about central vertical line of symmetry
assert fold_4.cyclic_subgroup() == Aut_G
assert Aut_G.gens() == (fold_4,)

R.<r1, r2, r3, r4> = L.root_system() # Allow named simple roots
assert R in RootSystems # Objects: root systems \Phi
assert R.span() == L
assert all( r_i.reflection()(r_j) in R for r_i in R for r_j in R) # \Phi is closed under reflections in simple roots
assert all( r_i.reflection() in L.base_change(QQ).O() ) # Reflections are always rational isometries
assert all( r_i.reflection() in L.O() ) # But reflections in roots are always integral isometries, by definition.
assert fold_4.order() == 2


root_fold_4 = R.Aut().from_dict({
	r1: r4,
	r2: r3,
	r3: r2,
	r4: r1
})

Aut_G.element_from_root_morphism(root_fold_4) == fold_4 # Any morphism of root systems induces a morphism of diagrams
assert root_fold_4.diagram_morphism() == fold_4 # Convenience
assert L.O() == L.W()
assert L.W() == L.O().subgroup_generated_by(ri.reflection() for ri in R.gens())

# TODO: G_fold = root_fold_4.cyclic_subgroup()
# TODO: L_inv, L_coinv = G_fold.invariant_coinvariant_sublattice_pair()
# TODO: assert L_inv == ..., L_coinv == ... # Explicit isometries to known lattices

assert {1,2} <= {1,2,3} # Hook preparser optionally, these should be parsed as sage sets, and A <= B iff A.is_subset(B)

# Testing iteration
assert { vector(ZZ, l) for l in [
	[0,0,0,0],
	[1,0,0,0],
	[0,1,0,0],
	[0,0,1,0],
	[0,0,0,1],
	[-1,0,0,0],
	[0,-1,0,0],
	[0,0,-1,0],
	[0,0,0,-1],
]} <= {v for v in itertools.islice(ZZ^4, 20) }
# Not fixing a specific enumeration scheme, but whatever generator enumerates ZZ^n should "spiral" outward from "small" vectors and thus include all of these.

assert itertools.islice(ZZ^4, 20) == (ZZ^4).enumerate(bound=20) # Convenience for slicing generators

L.<e,f> = Lattice.U()
assert {L.zero(), e, -e, f, -f} <= {x for x in L.enumerate(5)} # Have coordinates [0,0], [\pm 1,0], and [0,\pm 1], so these should be the first 5 elements, in some order.

# TODO: assert that L1.Hom(L2) can be enumerated in the same way
# TODO: assert that U.O() can be enumerated to find all generators manually, knowing a priori that it is generated by 2 distinct elements.
# TODO: assert that A_4.O() can be enumerated to find an involution whose invariant sublattice is in the isometry class of the a priori known abstract presentation of the invariant sublattice of <fold_4>

