assert set == frozenset # Convenience: we never mutate sets, we construct new ones.

R = ZZ
F = R^3
T = R/2
M = F + T
assert M == F.direct_sum(T)
assert (M.free_part(), M.torsion_part()) == (F, T)


assert not F.is_finite() and T.is_finite() 
assert F.cardinality() == Infty and T.cardinality() == 3
assert M.cardinality() == Infty

assert M in Modules(R).CartesianProducts()
assert F in Modules(R).Free()
assert T in Modules(R).Torsion()

assert M.free_rank() == 3
assert M.free_rank() == M.free_part().free_rank()

assert M.invariants() == (1,1,1,2) # Allow invariant factors to include 1 to represent free summands
assert M.torsion_part().invariants() == (2,)


assert M * M == M.tensor(M)
assert M * M in Modules(ZZ).TensorProducts()
assert M.is_finitely_generated()
assert M.is_finitely_presented()

assert M == R + R/2
assert M.base_change(R/2) in Modules(R/2)
assert M.base_change(R/2) == R/2 + R/2

assert M.dual() in Modules(R).dual_objects()
assert M.dual() == M.Hom(R) # M^* := Hom_R(M, R)
assert M.dual() == R^3 # Hom_R(F+T,R) == Hom(F, R) doesn't see torsion.

# Isomorphic by a canonical isomorphism
e1, e2, e3, t1 = M.gens()
assert all(x.order() == Infty for x in [e1, e2, e3]) and t1.order() == 2

e1d, e2d, e3d = M.dual().gens()
assert all(x in M.Hom(R) for x in M.dual().gens()) # Literal functionals

assert e1d * e1 == e1d.evaluate(e1) # Multiplication := natural evaluation pairing
assert e1d(e1) == e1d.evaluate(e1) # Functionals can be called to evaluate
# Form 3x3 matrix of pairings e_i^*(e_j), assert == \delta_{ij}
assert matrix(R, 3, lambda i,j: (e1d, e2d, e3d)[i] * M.gen(j)) == identity_matrix(R, 3)

v = 2*e1 + 3*e2 + 5*e3
assert e1d(v) == 2 # e_1^*(2e_1 + 3e_2 + 5e_3) = e_1^*(2e_1) = 2 e_1^*(e_1)
assert v.to_vector() == vector(R, [2,3,5])
assert v != vector(R, [2,3,5]) # Vectors are not elements, they are REPRESENTATIONS of elements 
assert v in M and vector(R, [2,3,5]) not in M 

assert M.dual().is_free() and M.dual().is_torsionfree() #Hom_R(-,R) kills torsion.

assert 2*M == M.submodule([2*x for x in M.gens()])
assert M.dual().domain() == M and M.dual().codomain() == R # Treat M.dual() as Hom_R(M, R)
assert e1d.domain() == M and e1d.codomain() == R # Delegate to parent 
assert e1d in M.dual() and e1d in M.Hom(R) # Seamless interop with hom spaces


M = ZZ^3
assert M.is_free() and M == M.free_part()
assert M.rank() == M.free_rank() # bare rank() only makes sense in the free case
assert M in Modules(R).Free()

assert {(M*M).gens()} == {e_i.tensor(e_j) for e_i in M.gens() for e_j in M.gens()} # M\otimes_R M is generated by e_i\otimes e_j for e_i, e_j in M.gens()

e1, e2, e3 = M.gens()
assert M.dual().gens() == [e1.dual(), e2.dual(), e3.dual()]
assert e1.dual() in M.Hom(R)
assert e1(3*e1 + 2*e2) in R

M1.<a1, a2> = ZZ^2
M2.<b1, b2> = ZZ^2
f = M1.Hom(M2).from_dict({a1: b1, a2:2*b1})
M_f = matrix(R, 2, [1,0,0,2])
assert f != M_f and f.to_matrix() == M_f
assert f.is_injective() and not f.is_surjective() and not f.is_bijective()
assert f.image() == M2.span([b1, 2*b2])
assert f.image() == ZZ + ZZ/2 # Canonicaly identification
assert f.kernel() == Modules(ZZ).zero()
assert Modules(ZZ).zero() == 0 # Coerce to zero module
assert f.cokernel() == (ZZ + ZZ)/(ZZ + 2*ZZ)
assert f.cokernel() == ZZ/2
assert len( f.cokernel().gens() ) == 1 and f.cokernel.gen(0).lift() == b2 # Cokernel is generated by the class [b_2]

M, N = ZZ, ZZ

f = M.Hom(N).from_list_of_images([2]) # g_1 -> 2*g_2
assert f.image() == 2*ZZ
assert f.index() == 2 # [codom(f): im(f)]
assert f.image().is_submodule_of(N) # Submodules have witnessing inclusions
assert not (2*ZZ).is_submodule_of(N) # Print warning: need to supply an embedding of abstract modules
assert (2*ZZ).is_submodule_of(N, morphism=f) # Can supply explicit embedding
assert 2*N == N.span([2*N.gen(0)]) # By definition
assert (2*N).is_submodule_of(N) # Modules CONSTRUCTED as literal submodules automatically store and use their inclusion morphism
assert f.to_matrix() == matrix(ZZ, 1, [2])
assert not f in M.Hom(M) # Abstractly isomorphic, but no canonical isomorphism
assert not f in M.End()
assert not f in M.Aut()
assert f.lift(N(4)) == M(2) # Can find SOME preimage of anything in the image.

f = M.Hom(M).from_tuple_of_images((2,)) # Same formula
assert f.formula(["x"]) == 2*x # x -> 2*x makes sense when domain = codomain
assert M.Hom(M) == M.End()
assert M.Hom(M) != M.Aut()
assert f in M.End() and not f in M.Aut()
assert not f.is_isomorphism()
assert f.is_endomorphism()
assert f.lift(2*M.gen(0)) == M.gen(0) # Can find some lifts

R = ZZ
M = ZZ^1 # Promotes rings R to modules over themselves
assert M.base_ring() == R and M.base_ring() != M # M is no longer considered a ring.
p = M(3)

assert M.annihilator(p) == Modules(ZZ).zero()
assert M.annihilator(M(0)) == ZZ

M == ZZ/3
assert [x.annihilator() for x in M] == [ZZ, 3*ZZ, 3*ZZ]
assert 3*ZZ in ZZ.ideals() # Need containment check capabilities.


M.<a,b>= ZZ^2
f = M.End()({a: b, b: a}) # __call__ dispatches to classmethod constructors

assert f in M.Aut()
assert f.is_involution()
assert f.order() == 2
assert f.to_matrix() == matrix(ZZ, 2, [0,1,1,0])
assert M.invariant_submodule(f) == f.invariant_submodule()
assert M.coinvariant_submodule(f) == f.coinvariant_submodule()
assert f^(-1) == f

G = f.cyclic_subgroup()
assert G.is_subgroup_of(M.Aut())
assert G <= M.Aut()  # Subobject sugar

assert M.invariant_submodule(G) == G.invariant_submodule()
assert G.invariant_submodule() == f.invariant_submodules() # Taking an element automatically replaces it with its cyclic subgroup G := <f> in Aut(M)

assert M^G ==  G.invariant_submodule()
assert M^G == (a+b).span()
M_G = M.coinvariant_submodule()
assert M_G == M / (a-b).span()
assert M_Glift_generators() == {a, b}
i = M_G.projection()
assert i in M.Hom(M_G) # Quotient morphism
assert i(a) == i(b) # [a] == [b] in quotient
assert M_G.lift_generators() == {a} # Choose SOME lifts, use natural ordering on generators to select 
assert M_G.gens() == [i(a)] and M_G.gens() == [i(b)]
assert M^G.is_isomorphic_to(ZZ) and M^G == ZZ # Natural morphism: (a+b)-> 1

R.<x,y> = PolynomialRing(ZZ, 2)
M = R^3 # Free module of rank 3 on R
assert M in Modules(R)
assert M.rank() == 3 # Rank over ZZ[x,y], not ZZ!
assert M.is_free() # As a ZZ[x,y]-module!

assert M.base_ring() == R and M.base_ring() != ZZ

M = ZZ^1
M1, M2 = 2*M, 3*M
assert M1 == M.span(2) and M2 == M.span(3) # Automatically coerce elements of R into tuples, sugar
assert M1.is_submodule(M) and M2.is_submodule(M) # Natural inclusions
i1, i2 = M1.inclusion(), M2.inclusion()
assert M1.intersect(M2) == i1.intersect(i2) # Intersections are defined on morphisms and delegated; intersect only appears on actual submodules
assert {M1, M2} <= M.submodules() # Check submodule condition, <= := is_subset for sets
assert M1 & M2 == M1.intersect(M2) # Module GENERATED by the intersection
assert M1 | M2 == M1.union(M2) # Module GENERATED by the union
assert M1 & M2 == 6*M
assert M1 + M2 != M1 & M2 # Addition is not a span, it is a direct sum
assert M1.direct_sum(M2) == M1 + M2

assert 2*ZZ in ZZ^1.submodules() # lmul n*R turns R into an R-module and n*R into an R-submodule
i = (2*ZZ).inclusion()
assert i.image() <= ZZ^1
assert 2*ZZ <= ZZ^1 # Can coerce because we have an inclusion
assert i.image() & i.codomain() == i.image() # image = 2*ZZ and codomain = ZZ
assert i.index() == 2
assert (2*ZZ).index() == 2 # Have a natural inclusion
assert i.saturation() == i.codomain() # 2ZZ saturates to ZZ
assert (2*ZZ).saturation() == ZZ^1
assert i.cokernel() == ZZ/2
assert i.kernel() == 0 # Coerce to zero ZZ-module
assert not i.is_isomorphism()

R = ZZ
M.<a, b> = R^2
assert a.to_vector() == matrix(R, 1, [1,0])
assert b.to_vector() == matrix(R, 1, [0,1])
assert M == R.direct_sum(R) # Coerces to R-modules
assert M == R + R # Categorically, R^n := \oplus_{i=1}^n R is repeated summing
assert a[0] == 1 and a[1] == 0 # Indexing extracts the coefficient of the i'th generator
assert sum(a.to_vector()) == 1
assert sum(b.to_vector()) == 1
assert sum((a+b).to_vector()) == 2

M_ev = M.submodule_from_condition(lambda x: sum(x.to_vector()) in 2*ZZ )
# Could equivalently use sum(x_i) % 2 == 0, but we prefer set containment expressions
# This is the "even" submodule

assert M_ev.saturation() == M
assert a in M and a not in M_ev
assert 2*a in M_ev and 3*a not in M_ev
assert (a-b) not in M_ev and (a+b) in M_ev

assert a-a == M(0)
assert M.1 == a and M.2 == b # Standard sage sugar

# TODO: assert that submodules can express a basis matrix

M = ZZ^3
Mp = M.base_change(ZZ/3)
assert Mp == (ZZ/3)^3
assert Mp in Modules(ZZ/3) and Mp in Modules(ZZ) # Technically still has a ZZ-module structure
assert not M.is_finite() and Mp.is_finite()

swap_z = M.End().from_dict({M.1: M.2, M.2: M.1})
swap_z3 = swap_z.base_change(ZZ/3)
assert swap_z3(Mp.1) == Mp.2 and swap_z3(Mp.2) == Mp.1

assert Modules(ZZ).base_change_functor(ZZ/3).apply_to_object(M) == Mp # Should have functors!
assert Modules(ZZ).base_change_functor(ZZ/3).apply_to_morphism(swap_z) == swap_z3

assert M.base_change(Zp(3)) in Modules(Zp(3)) # p-adic rings should be supported

assert Modules(ZZ).random_module() in Modules(ZZ) # Ability to generate random elements
assert Modules(ZZ).an_object() in Modules(ZZ) # Ability to get a sample object

M1, M2, M3 = 3*[ZZ^1]
f1 = M1.Hom(M3).natural_map() # For f: R^n->R^m, always sends the first m generators of R^n to the generators of R^m
assert f1.is_identity() # In this case, n=m=3, so this is the identity matrix
assert f1.formula("x") == x

f2 = M2.Hom(M3).from_dict({M2.1: M3.2, M2.2: M3.1}) # Swap map

assert f1 + f2 in (M1 + M2).Hom(M3)
assert (f1 + f2).to_matrix() == block_matrix([f1.to_matrix(), f2.to_matrix()])
# f_1 \oplus f_2 = [A_1 | A_2]
# Direct sums should always explicit construct BLOCK matrices, not just random stacking
assert (f1.tensor(f2)) in (M1 * M2).Hom(M3) # Can tensor maps to get maps out of the tensor product

g1 = M1.Hom(M2).natural_map()
g2 = M2.Hom(M3).natural_map()
assert g2 * g1 in M1.Hom(M3) # Multiplication is function composition


M = ZZ^2
assert M.Hom(M) in Modules(ZZ)
assert M.Hom(M).ngens() == 4 # Finitely generated 

M1, M2 = 2*[ZZ^1]

f = M1.Hom(M2)([3]) # g_1 -> 3*h1
assert not f.cokernel().is_torsionfree()
assert not f.is_primitive() # coker(f) not torsionfree
assert f.is_finite_index()
assert f.index() == 3
assert f.cokernel() == ZZ/3
assert M1.Aut() in Groups


M = (1/2)*ZZ # { (1/2)*m | m in ZZ }
assert M in Modules(ZZ)
assert M not in (QQ^1).submodules() # This would return Q-submodules, not ZZ-submodules
assert M in Modules(ZZ)(QQ^1).submodules() # Can coerce to a ZZ-module

assert M/ZZ.is_isomorphic_to(ZZ/2) # (1/2)ZZ/ZZ \cong ZZ/2
# All groups should have is_isomorphic!

S = {"a", "b", "c"}
F = Modules(ZZ).element_from_set(S) # Take the free module on a set
assert F in Modules(ZZ).Free()
assert {g for g in F.gens()} == S # Literally generated by the set elements

a,b,c = F.gens()
assert a.underlying_element() == "a" # Can extract the original elements
assert b.underlying_element() == "b" #

Fp = Modules(ZZ).element_from_set({CC, ZZ, RR}) # Any set of objects is fine
assert Fp in Modules(ZZ).Free()
C, Z, R = Fp.gens()
C == CC # Compare the underlying element if the other object isn't literally an element of this module

x1 = 3*C + 2*Z -4*R 
assert x1 in Fp # Obviously can't overload 2*CC, e.g., but you can still work with corresponding formal symbols
# Mostly just used for a string representation: free module on CC's string rep, ZZ's string rep, etc


M = Modules(ZZ).from_set({'a', 'b', 'c'}) # Free module on a set
T_M = M.tensor_algebra()
assert T_M.rank() == Infinity # Rank as a ZZ-MODULE
assert T_M.algebra_rank() == 3 # Rank as a ZZ-ALGEBRA

assert T_M[0] == ZZ # Indexing returns rank n part
assert T_M[1] == ZZ^3 and {x.underlying_element() for x in T_M[1].gens()} == {'a', 'b', 'c'} # As ZZ-modules
assert T_M[1] == M  # As ZZ-modules
assert T_M[2] == M * M # Tensor over ZZ


assert {T_M.gens()}.is_infinite() # Or something similar, module generators are words in {"a", "b", "c"}

assert len(T_M.algebra_gens()) == 3 # Free ZZ-algebra on {"a", "b", "c"}

M = ZZ^2
T_M.<e,f> = M.tensor_algebra() # Algebra generators
b = (M*M).Hom(ZZ).from_dict({
	e@e: 0,
	e@f: 1,
	f@e: 1,
	f@f: 0
}) # A bilinear form clearly corresponding to U
assert b in (M*M).dual() # ZZ-linear dual
assert b(e@e) == 0 and b(e@f) == 1 and b(f@e) == 1 and b(f@f) == 0
assert b(e,e) == 0 and b(e,f) == 1 and b(f,e) == 1 and b(f,f) == 0 # Convenience: lift elements of MxM to M\otimes_ZZ M

assert Lattices(ZZ).from_tensor_pair(M, b) == Lattices.U() # Isometric by the identity
assert Lattices(ZZ).from_tensor_pair(M, b).gram_matrix() == matrix(ZZ, 2, [0,1,1,0])


assert T_M.num_graded_pieces() == Infty
assert not T_M.is_commutative()

# Should be compatible with https://doc.sagemath.org/html/en/reference/tensor_free_modules/sage/tensor/modules/free_module_tensor.html#sage.tensor.modules.free_module_tensor.FreeModuleTensor

assert M.tensor_module(2,2) == M * M * M.dual() * M.dual() # Convenience for (p,q) tensor products
assert M.tensor_module(1,0) == M
assert M.tensor_module(0,1) == M.dual()

M = ZZ^3
f = M.linear_form([1,2,3]) # Type (0,1), express b(e_i) for e_i in M.gens()
assert f( M([1,1,1]) ) == 1 + 2 + 3 # Automatically coerce lists and vectors into module elements when called
assert f.contract( M([1,1,1]) ) == 1 + 2 + 3 # Interpret elements of M as (1,0) tensors

E_M.<a,b,c> = M.exterior_algebra() # Alternating tensors
assert a*a == a.wedge(a) # Multiplication is always the algebra multiplication here
assert (a*a, b*b, c*c) == tuple(3 * [E_M.zero()])
assert E_M.num_graded_pieces() == 4
assert E_M.graded_pieces == [ZZ, M, M.wedge_power(2), M.wedge_power(3)]
assert M.determinant_module() == M.wedge_power(3)
assert {M.wedge_power(2).gens()} == {a*b,a*c,b*c} # Mult = wedge
assert {M.wedge_power(3).gens()} == {a*b*c}
assert [x.rank() for x in E_M.graded_pieces] == [1,3,3,1]
assert E_M.rank() == 8 # Finite rank as a ZZ-module
assert E_M.algebra_rank() == 3 # Finitely generated as a ZZ-algebra
assert{E_M.gens()} == {1,a,b,c,a*b,a*c,b*c,a*b*c}
assert E_M.is_anticommutative()

S_M.<a,b,c> = S.symmetric_algebra() # Always an algebra over the same base ring.
assert S_M.is_isomorphic_to(PolynomialRing(ZZ, 3)) # As ZZ-algebras
assert a*b == a.tensor(b) # Algebra multiplication is tensoring
assert S_M[0] == ZZ and S_M[1] == M
assert {S_M[2].gens()} == {a*a,a*b,a*c, b*b,b*c,c*c}
assert S_M[2].rank() == 6 # As a ZZ-module
assert S_M.rank() == Infinity # As a ZZ-module
assert S_M.algebra_rank() == 3 # As a ZZ-algebra
# S_M[n].gens() is always a^i*b^j*c^k where 0 <= i,j,k and i+j+k = n
assert all(S_M[n].rank() == choose(n+2,2) for n in [2,3,4,5])
assert S_M.is_commutative()
