r"""What the objects are, as mathematics — not as Sage currently reports them.

Every assertion below is a true statement about the object named. A failure is
not a bug in the test: it records that Sage's encoding does not yet carry the
fact, and therefore that the preamble must bridge it. This file is the gap map,
executable, so the map cannot go stale in a chat log.

Sources (Zotero item | Better-BibTeX key):

  - J. E. Humphreys, *Reflection Groups and Coxeter Groups* (1990). Hum90.
    Section 2.11 tabulates the orders of the finite Weyl groups; Section 4.1:
    a Coxeter group is generated by its simple reflections, a finite set, so
    every Coxeter group -- affine ones included -- is finitely generated.
  - Conway & Sloane, *Sphere Packings, Lattices and Groups*, 3rd ed. CS10.
    Chapter 4 tabulates the root lattices and their automorphism groups:
    Aut(A_n) = {+-1} x W(A_n) for n >= 2, |Aut(D_4)| = 1152 (triality),
    -1 in W(E_8) so Aut(E_8) = W(E_8).
  - J.-P. Serre, *Trees* (1980). Ser80. I.4.2: SL(2,ZZ) is the amalgam
    ZZ/4 *_{ZZ/2} ZZ/6, generated by S and T.

Two facts are asserted without a citation because they are definitional, not
literature: a finite group is finitely generated (its own elements generate
it), and a group presented on a finite generating set is generated by that set.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import dzack_research
import pytest

from sage.all import IntegralLattice as SageIntegralLattice
from sage.all import (
    AbelianGroup,
    CoxeterGroup,
    FreeGroup,
    GL,
    QuaternionGroup,
    SL,
    SO,
    Sp,
    WeylGroup,
)
from sage.categories.groups import Groups
from sage.misc.unknown import Unknown

# The engine's own scalars, named as such.  Sage's matrix-group constructors
# are engine constructions and take the rings the engine computes in; the
# session's ``ZZ`` is a different object, and the two are kept apart here so
# that neither question is asked of the other's ring.
from sage.rings.integer_ring import ZZ as SageIntegers
from sage.rings.qqbar import QQbar as SageAlgebraicNumbers
from sage.rings.rational_field import QQ as SageRationals

# The owned category is the surface (AGENTS.md: the preamble owns its
# categories outright); Sage's ``Groups().FinitelyGenerated()`` is a
# declaration registry the preamble consumes on intake, not the node these
# assertions ask about.
from dzack_research.preamble.categories.group.groups import OwnedFinitelyGeneratedGroups

FINITELY_GENERATED = OwnedFinitelyGeneratedGroups()

# These are claims about the preamble's universe, so the preamble is loaded:
# ``R^n``, the refinements, and the category layer are what the assertions are
# about.  The sibling ``.sage`` tests load the same file, in the same way.
#
# ``Lattices.install`` is the session boundary: it is what a notebook runs, and
# it is where the names a notebook types -- ``ZZ``, ``QQ``, ``PolynomialRing``
# -- are bound to the owned objects.  Loading ``install.sage`` alone leaves
# them as the engine's, so the ``R^n`` claims below would be asked of the wrong
# rings.
from dzack_research.preamble.install import install_preamble
install_preamble(globals())
Lattices.install(globals())


# ---------------------------------------------------------------------------
# A finite group is finitely generated.  It generates itself.
#
# QUIRK.  Sage's ``FinitelyGenerated`` is a declaration, not a decision.  A
# category is only entered when some constructor says so, and most never do:
# ``FreeGroup(2)``, ``AbelianGroup([5])``, ``GL(3,ZZ)`` and every ``O(L)``
# stand outside it while answering ``ngens`` on request.  So Sage's node
# reads as "somebody wrote it down", and its False carries no mathematics.
#
# REMEDIATION.  The preamble owns the finitely-generated-groups category and
# refines groups into it on intake, reading Sage's declaration as one
# admission source among the decidable ones.  These assertions ask the owned
# node, where membership is a decision.
# ---------------------------------------------------------------------------

FINITE_GROUPS = {
    "Q8": QuaternionGroup(),
    "W(A2)": WeylGroup(["A", 2]),
    "W(A4)": WeylGroup(["A", 4]),
    "W(D4)": WeylGroup(["D", 4]),
    "W(E6)": WeylGroup(["E", 6]),
    "W(E8)": WeylGroup(["E", 8]),
    "Coxeter H3": CoxeterGroup(["H", 3]),
    "Coxeter H4": CoxeterGroup(["H", 4]),
    "O(A2)": IntegralLattice("A2").Aut(),
    "O(A4)": IntegralLattice("A4").Aut(),
    "O(D4)": IntegralLattice("D4").Aut(),
    "O(E6)": IntegralLattice("E6").Aut(),
    "O(E7)": IntegralLattice("E7").Aut(),
    "O(E8)": IntegralLattice("E8").Aut(),
    "Z/5": AbelianGroup([5]),
}


@pytest.mark.parametrize("name", sorted(FINITE_GROUPS))
def test_a_finite_group_is_finitely_generated(name: str) -> None:
    r"""A finite group is generated by its own underlying set."""
    group = FINITE_GROUPS[name]
    assert group in FINITELY_GENERATED, (
        f"{name} is finite, so it is finitely generated"
    )


# ---------------------------------------------------------------------------
# A group whose generators are in hand is finitely generated, finite or not.
# ---------------------------------------------------------------------------

GENERATED_GROUPS = {
    "FreeGroup(2)": (FreeGroup(2), 2),
    "SL(2,ZZ)": (SL(2, SageIntegers), 2),
    "SL(3,ZZ)": (SL(3, SageIntegers), 3),
    "GL(3,ZZ)": (GL(3, SageIntegers), 4),
    "W(A2~)": (WeylGroup(["A", 2, 1]), 3),
    "W(E8~)": (WeylGroup(["E", 8, 1]), 9),
}


@pytest.mark.parametrize("name", sorted(GENERATED_GROUPS))
def test_a_group_presented_on_finite_generators_is_finitely_generated(
    name: str,
) -> None:
    r"""Sage answers ``ngens`` for each of these, so the axiom holds."""
    group, expected_generators = GENERATED_GROUPS[name]
    assert group.ngens() == expected_generators, (
        f"{name} is generated by {expected_generators} elements"
    )
    assert group in FINITELY_GENERATED, (
        f"{name} exhibits {expected_generators} generators, so it is "
        "finitely generated"
    )


def test_the_free_group_on_two_generators_is_the_definitional_case() -> None:
    r"""\(F_2\) is free ON two generators.  Nothing is more finitely generated."""
    free_group = FreeGroup(2)
    assert free_group.ngens() == 2
    assert free_group.is_finite() is False
    assert free_group in FINITELY_GENERATED


def test_refinement_repairs_an_undeclared_axiom_without_loss() -> None:
    r"""Refining supplies the fact Sage never declared, and costs nothing.

    This is the whole bridge in one assertion: the axiom is Sage's own, the
    evidence is Sage's own ``ngens``, and the object keeps every answer it had
    before.  If this fails, the preamble cannot repair category membership by
    refinement and needs a different mechanism.
    """
    group = GL(3, SageIntegers)
    generators_before = group.ngens()
    assert generators_before == 4

    group._refine_category_(FINITELY_GENERATED)

    assert group in FINITELY_GENERATED
    assert group.ngens() == generators_before, (
        "refinement adds a category; it does not disturb the group"
    )
    assert group.is_finite() is False


# ---------------------------------------------------------------------------
# Orders, from the literature.  Hum90 sec 2.11 and CS10 ch. 4.
# ---------------------------------------------------------------------------

WEYL_ORDERS = {  # Hum90, section 2.11
    ("A", 2): 6,
    ("A", 4): 120,
    ("D", 4): 192,
    ("E", 6): 51840,
    ("E", 7): 2903040,
    ("E", 8): 696729600,
}


@pytest.mark.parametrize("cartan_type", sorted(WEYL_ORDERS))
def test_finite_weyl_group_order_matches_humphreys(cartan_type: tuple) -> None:
    r"""\(|W|\) as tabulated in Humphreys, not as recomputed from Sage."""
    letter, rank = cartan_type
    group = WeylGroup([letter, rank])
    assert group.order() == WEYL_ORDERS[cartan_type], (
        f"|W({letter}{rank})| is tabulated in Hum90 section 2.11"
    )


ROOT_LATTICE_AUTOMORPHISM_ORDERS = {  # CS10, chapter 4
    "A2": 12,
    "A4": 240,
    "D4": 1152,
    "E6": 103680,
    "E7": 2903040,
    "E8": 696729600,
}


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_root_lattice_automorphism_order_matches_conway_sloane(name: str) -> None:
    r"""\(|\mathrm{Aut}(L)|\) as tabulated in Conway and Sloane."""
    orthogonal_group = IntegralLattice(name).Aut()
    assert orthogonal_group.order() == ROOT_LATTICE_AUTOMORPHISM_ORDERS[name], (
        f"|Aut({name})| is tabulated in CS10 chapter 4"
    )


# ---------------------------------------------------------------------------
# O(L): one group, dropped in eight places.
#
# QUIRK, upstream.  Sage builds the isometry group twice.  ``L.automorphisms()
# is L.orthogonal_group()`` is False on a native lattice, so the same group
# has two identities before the preamble is involved at all.  Sage's copies do
# answer ``order`` and ``ngens`` correctly -- 240 and 4 for A_4 -- and neither
# copy is in ``FinitelyGenerated``.
#
# QUIRK, preamble.  The preamble does not refine Sage's lattice; it builds its
# own ``FormModule`` and rebinds the name.  Nothing of Sage's MRO is inherited,
# so ``orthogonal_group`` and ``automorphisms`` are simply absent, and what
# ``Aut()`` returns is a third object again.  That object declares itself in
# ``Groups()`` and cannot answer ``order``, ``cardinality``,
# ``number_of_group_generators`` or ``is_finite``, and cannot be iterated --
# while holding its own ``group_generators``.  The data is present; the
# vocabulary never arrived.
#
# REMEDIATION.  One object, reached one way.  The isometry group is the units
# of ``End(L)``, so the lattice needs an endset -- it has ``Hom`` and no
# ``End`` -- and ``orthogonal_group``, ``automorphisms`` and ``Aut`` become
# one name for what that homset yields, the other spellings kept only if they
# return the identical object.  ``order`` and enumeration are not
# written on the group: they are what the groups category already supplies to
# anything refined into it, which is why the missing refinement and the
# missing methods are a single defect.  A generating set already in hand makes
# the finite-generation refinement immediate, so ``O(L)`` leaves the
# equivariance heuristic's hard branch entirely.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_the_orthogonal_group_and_the_automorphism_group_are_one_object(
    name: str,
) -> None:
    r"""\(O(L)\) and \(\mathrm{Aut}(L)\) are two names for the same group.

    A lattice is a module with a form; its automorphisms are exactly the
    isometries.  Two accessors that answer differently -- or one that answers
    and one that does not -- mean the object was built twice.
    """
    lattice = IntegralLattice(name)
    assert lattice.orthogonal_group() is lattice.Aut(), (
        f"O({name}) and Aut({name}) are the same group"
    )


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_a_finite_automorphism_group_reports_its_order(name: str) -> None:
    r"""\(|\mathrm{Aut}(L)|\) is a question every finite group answers.

    Order lives on the groups category, so a group that cannot answer it has
    not been refined into one.
    """
    automorphisms = IntegralLattice(name).Aut()
    assert automorphisms.order() == ROOT_LATTICE_AUTOMORPHISM_ORDERS[name]


def test_the_isometry_group_is_built_once() -> None:
    r"""One group, one object, however many times it is asked for.

    Sage splits \(O(L)\): ``automorphisms`` and ``orthogonal_group`` are one
    function there, and it caches nothing, so two calls are two objects.  The
    repair is not to make the lattice cache the group -- the group owns its
    own computations -- but to reach it one way, through the endset, and let
    it hold what it computes.  A generating set computed once stays computed
    only if asking again is asking the same object.
    """
    lattice = IntegralLattice("A4")
    automorphisms = lattice.Aut()
    assert lattice.Aut() is automorphisms
    assert lattice.orthogonal_group() is automorphisms
    assert lattice.automorphisms() is automorphisms
    assert automorphisms.group_generators() is automorphisms.group_generators(), (
        "a group that recomputes its generators has not held them"
    )


def test_the_isometry_group_is_finitely_presented() -> None:
    r"""\(O(L)\) is an arithmetic group, so it has a finite presentation.

    Borel and Harish-Chandra, which covers indefinite \(L\) too -- the axiom
    is a theorem about the group and not a report of what this session
    managed to compute.  Carrying it means answering for it: a finitely
    presented group exhibits generators and the relations they satisfy.
    """
    automorphisms = IntegralLattice("A4").Aut()
    assert automorphisms in OwnedFinitelyPresentedGroups()
    assert automorphisms.presenting_free_group().ngens() == 4, (
        "the presentation is written in the four generators of O(A4)"
    )
    assert automorphisms.defining_relations(), (
        "a group of order 240 on four generators satisfies relations"
    )


# The words in the preamble's own vocabulary.  ``gens`` and ``ngens`` are not
# among them: a group generates *as a group*, and the bare word leaves open
# which structure is meant, so the preamble spells it out.  What is asked of
# the object is the question, not the spelling, and the question is the same
# one Sage's ``gens`` was reaching for.
GROUP_VOCABULARY = (
    "order",
    "cardinality",
    "group_generators",
    "number_of_group_generators",
    "is_finite",
)


@pytest.mark.parametrize("question", GROUP_VOCABULARY)
def test_a_group_answers_the_group_vocabulary(question: str) -> None:
    r"""\(\mathrm{Aut}(L)\) sits in ``Groups()`` and must speak as one.

    Membership in a category is a promise about the questions the object
    answers.  ``Aut(A4)`` is in ``Groups()``, holds its generators, and is
    finite of order 240 -- so every word below has an answer.
    """
    automorphisms = IntegralLattice("A4").Aut()
    assert automorphisms in Groups()
    answer = getattr(automorphisms, question, None)
    assert callable(answer), (
        f"a group answers {question}(); the groups category owns it"
    )
    answer()


def test_a_finite_group_can_be_enumerated() -> None:
    r"""A finite group is a finite set, so its elements can be listed."""
    automorphisms = IntegralLattice("A4").Aut()
    elements = list(automorphisms)
    assert len(elements) == ROOT_LATTICE_AUTOMORPHISM_ORDERS["A4"]


def test_a_lattice_has_an_endomorphism_ring() -> None:
    r"""\(\mathrm{End}(L)\) is the homset \(O(L)\)'s units come from.

    ``Hom`` exists; the endset does not, so the automorphism group cannot be
    reached the way the audit sited it.
    """
    lattice = IntegralLattice("A4")
    endomorphisms = lattice.End()
    assert endomorphisms is lattice.Hom(lattice)


def test_aut_of_a_n_is_plus_minus_one_times_the_weyl_group() -> None:
    r"""CS10 ch. 4: \(\mathrm{Aut}(A_n)=\{\pm1\}\times W(A_n)\) for \(n\ge2\)."""
    for rank in (2, 4):
        automorphisms = IntegralLattice(f"A{rank}").Aut().order()
        weyl = WeylGroup(["A", rank]).order()
        assert automorphisms == 2 * weyl, (
            f"Aut(A{rank}) is {{+-1}} x W(A{rank})"
        )


def test_minus_one_lies_in_the_weyl_group_of_e8() -> None:
    r"""CS10 ch. 4: \(-1\in W(E_8)\), so \(\mathrm{Aut}(E_8)=W(E_8)\)."""
    assert (
        IntegralLattice("E8").Aut().order()
        == WeylGroup(["E", 8]).order()
    )


def test_sl2z_is_the_amalgam_serre_describes() -> None:
    r"""Ser80 I.4.2: \(SL_2(\ZZ)\cong\ZZ/4*_{\ZZ/2}\ZZ/6\), on two generators."""
    group = SL(2, SageIntegers)
    assert group.ngens() == 2, "S and T generate SL(2,ZZ)"
    assert group.is_finite() is False
    assert group in FINITELY_GENERATED


# ---------------------------------------------------------------------------
# Every group answers.  "I do not know" is an answer; an exception is not.
#
# QUIRK.  Sage ships the three-valued truth value ``Unknown`` and then does
# not use it here.  ``Sp(4,ZZ).ngens()`` raises ``AttributeError`` and its
# ``is_finite()`` raises ``NotImplementedError``; ``GL(2,QQbar)`` answers
# ``is_finite`` and raises for ``ngens``.  Two different absences -- no such
# method, and a method that declines to decide -- arrive as two exception
# types, neither of which is mathematics, so callers must catch to learn what
# is true.  ``bool(Unknown)`` then raises rather than collapsing, which is the
# right choice and the reason the value must be matched on, never tested.
#
# REMEDIATION.  The preamble's probes are total: a count or ``Unknown``, a
# truth value or ``Unknown``, never an exception.  Layered, because no single
# signal is sound -- the declared axiom is trusted when present, otherwise the
# object is asked, otherwise Unknown -- and separated into whether generators
# exist in principle, whether an algorithm can produce them, and whether they
# are already computed, since only the last is free.  Equivariance is then
# checked on generators when they are available, and when they are not the
# morphism records that it was not checked rather than pretending.
# ---------------------------------------------------------------------------

GROUPS_WITHOUT_KNOWN_GENERATORS = {
    "Sp(4,ZZ)": Sp(4, SageIntegers),
    "SO(3,QQ)": SO(3, SageRationals),
    "GL(2,QQbar)": GL(2, SageAlgebraicNumbers),
}


@pytest.mark.parametrize("name", sorted(GROUPS_WITHOUT_KNOWN_GENERATORS))
def test_finite_generation_is_a_value_never_an_exception(name: str) -> None:
    r"""A predicate that cannot decide returns ``Unknown``.

    Raising forces callers to use exception handling as control flow, and two
    different absences (no such method, method declines) arrive as two
    different exception types carrying no mathematics.
    """
    group = GROUPS_WITHOUT_KNOWN_GENERATORS[name]
    answer = group.is_finitely_generated()
    assert answer is True or answer is False or answer is Unknown, (
        f"{name} must answer finite generation with a truth value"
    )


@pytest.mark.parametrize("name", sorted(GROUPS_WITHOUT_KNOWN_GENERATORS))
def test_generator_count_is_a_value_never_an_exception(name: str) -> None:
    r"""``ngens`` is ``Unknown`` when unknown, not ``AttributeError``."""
    group = GROUPS_WITHOUT_KNOWN_GENERATORS[name]
    count = group.ngens()
    assert count is Unknown or count in SageIntegers, (
        f"{name} must report a generator count or Unknown"
    )


def test_finiteness_is_a_value_never_an_exception() -> None:
    r"""``Sp(4,ZZ)`` is infinite; a decision procedure that declines says so."""
    answer = Sp(4, SageIntegers).is_finite()
    assert answer is True or answer is False or answer is Unknown


def test_the_absolute_galois_group_of_the_rationals_is_constructible() -> None:
    r"""\(\mathrm{Gal}(\overline{\QQ}/\QQ)\) is a group, so it is an object.

    Profinite and not finitely generated -- the cleanest witness for the
    branch that cannot check equivariance.

    Asked of $\QQ$, which is the field it is the absolute Galois group *of*.
    $\overline{\QQ}$ has no Galois group of its own -- it is separably closed
    -- so ``QQbar.galois_group()`` was a question about the wrong field, and
    the preamble sites the answer where it belongs: on the base field.
    """
    galois_group = QQ.absolute_galois_group()
    assert galois_group in Groups()


# ---------------------------------------------------------------------------
# Restriction to a subfield, on the tower $\QQ\subset\QQ(i),\QQ(\sqrt3)\subset
# \QQ(\zeta_{12})$.
#
# $\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\cong(\ZZ/2)^2$ acts by
# $\zeta_{12}\mapsto\zeta_{12}^k$ for $k\in\{1,5,7,11\}$, and the three
# quadratic subfields are the fixed fields of its three subgroups of order 2.
# Which subfield an element moves is therefore a different fact for each
# element, and it is arithmetic anyone can redo by hand:
#
#   $i=\zeta_{12}^3$ and $\sqrt3=\zeta_{12}+\zeta_{12}^{-1}$, so
#   $k=11$ (complex conjugation) sends $i\mapsto-i$ and fixes $\sqrt3$;
#   $k=5$ fixes $i$ and sends $\sqrt3\mapsto-\sqrt3$;
#   $k=7$ moves both.
#
# The group is abelian, so these restrictions do not depend on which of the two
# embeddings of the subfield the choice policy takes.
# ---------------------------------------------------------------------------

from dzack_research.preamble.categories.group.profinite.galois_quotient import (
    extensions_along,
)

_ZETA_12 = CyclotomicField(12)
_GAUSSIAN = QuadraticField(-1, "i")
_REAL_QUADRATIC = QuadraticField(3, "r")

# Sage names the elements of a Galois group by a permutation of the roots; the
# mathematics names them by the power of $\zeta_{12}$ they produce, so that is
# how they are looked up here.
_BY_EXPONENT = {
    (_ZETA_12.gen() ** exponent): exponent
    for exponent in (1, 5, 7, 11)
}


def _automorphism_sending_zeta_to_power(exponent: int):
    r"""Return the \(\sigma\in\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\) with \(\zeta\mapsto\zeta^{e}\)."""
    generator = _ZETA_12.gen()
    matches = [
        sigma
        for sigma in _ZETA_12.galois_group()
        if sigma(generator) == generator**exponent
    ]
    assert len(matches) == 1, f"no unique automorphism for exponent {exponent}"
    return matches[0]


# Each row: the exponent $k$, and whether $\zeta_{12}\mapsto\zeta_{12}^k$ moves
# $i$ and whether it moves $\sqrt3$.
MOVES_THE_SUBFIELD_GENERATOR = {
    1: (False, False),
    5: (False, True),
    7: (True, True),
    11: (True, False),
}


@pytest.mark.parametrize("exponent", sorted(MOVES_THE_SUBFIELD_GENERATOR))
def test_restriction_to_a_subfield_is_the_arithmetic_of_that_subfield(
    exponent: int,
) -> None:
    r"""\(\zeta_{12}\mapsto\zeta_{12}^{k}\) restricts to the right automorphism of each subfield.

    Complex conjugation is the case that separates the two subfields:
    $\sqrt3=\zeta_{12}+\zeta_{12}^{-1}$ is real, so conjugation fixes it while
    sending $i$ to $-i$. A restriction computed on the wrong subfield, or with
    the two embeddings confused, gets this row wrong.
    """
    lifted = QQ.absolute_galois_group().lift(
        _automorphism_sending_zeta_to_power(exponent)
    )
    moves_i, moves_root_three = MOVES_THE_SUBFIELD_GENERATOR[exponent]

    to_gaussian = lifted.restrict(_GAUSSIAN)
    assert (to_gaussian(_GAUSSIAN.gen()) == -_GAUSSIAN.gen()) is moves_i, (
        f"zeta12 |-> zeta12^{exponent} sends i to {to_gaussian(_GAUSSIAN.gen())}"
    )

    to_real = lifted.restrict(_REAL_QUADRATIC)
    assert (
        to_real(_REAL_QUADRATIC.gen()) == -_REAL_QUADRATIC.gen()
    ) is moves_root_three, (
        f"zeta12 |-> zeta12^{exponent} sends sqrt3 to "
        f"{to_real(_REAL_QUADRATIC.gen())}"
    )


def test_restriction_to_a_subfield_is_a_group_homomorphism() -> None:
    r"""\(\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\to\mathrm{Gal}(\QQ(i)/\QQ)\) is a homomorphism.

    Restriction being multiplicative is what makes it the map in
    $1\to G_{\QQ(i)}\to G_\QQ\to\mathrm{Gal}(\QQ(i)/\QQ)\to1$ rather than an
    assignment of automorphisms one at a time.
    """
    group = QQ.absolute_galois_group()
    quotient = _ZETA_12.galois_group()
    gaussian_generator = _GAUSSIAN.gen()
    for sigma, tau in itertools.product(quotient, quotient):
        product = group.lift(sigma * tau).restrict(_GAUSSIAN)
        composite = group.lift(sigma).restrict(_GAUSSIAN)(
            group.lift(tau).restrict(_GAUSSIAN)(gaussian_generator)
        )
        assert product(gaussian_generator) == composite, (
            f"restriction of {sigma}*{tau} is not the composite of the restrictions"
        )


def test_the_extensions_of_an_automorphism_form_a_coset_of_the_open_subgroup() -> None:
    r"""The automorphisms of \(\QQ(\zeta_{12})\) extending \(i\mapsto-i\) number \([\QQ(\zeta_{12}):\QQ(i)]\).

    Galois theory: the set of extensions of $\tau$ to $M$ is a coset of
    $\mathrm{Gal}(M/L)$, hence nonempty and of size $[M:L]=2$ here. The two are
    $k=7$ and $k=11$, the elements that move $i$.
    """
    embedding = _GAUSSIAN.embeddings(_ZETA_12)[0]
    conjugation = [
        automorphism
        for automorphism in _GAUSSIAN.embeddings(_GAUSSIAN)
        if automorphism(_GAUSSIAN.gen()) == -_GAUSSIAN.gen()
    ][0]
    candidates = [sigma.as_hom() for sigma in _ZETA_12.galois_group()]

    extensions = extensions_along(conjugation, embedding, candidates)

    # $\mathrm{Gal}(M/\QQ)$ is partitioned into these cosets, one per
    # automorphism of $\QQ(i)$, so each has $|\mathrm{Gal}(M/\QQ)|/|\mathrm{Aut}
    # (\QQ(i))|$ members -- the Galois correspondence, counted.
    assert len(extensions) == len(candidates) // len(
        _GAUSSIAN.embeddings(_GAUSSIAN)
    )
    generator = _ZETA_12.gen()
    assert {_BY_EXPONENT[extension(generator)] for extension in extensions} == {7, 11}


# ---------------------------------------------------------------------------
# The preamble universe loses nothing Sage's lattices could already answer.
#
# A root lattice is one object.  Whichever constructor built it, every question
# Sage's lattice answers has an answer here, equal to Sage's or refining it.
# The surface is derived from the native lattice at import rather than listed,
# so the sweep cannot silently shrink as Sage grows.
# ---------------------------------------------------------------------------


_NATIVE_A4 = SageIntegralLattice("A4")


# Sage's question, and the word the preamble already answers it with.  A pair
# is here only if the mathematics survived the audit: the imprecise accessors
# (``dimension`` for rank, ``signature`` for the index p-q, ``determinant`` for
# the discriminant, everything about a basis) are absent on purpose.
#
# Every answer here is a *value* -- a number, a matrix, a ring, a genus symbol
# -- which is what makes comparing the two vocabularies meaningful.  The
# element-valued answers, ``zero`` and the module generators, are not in the
# table: an element belongs to a parent, the two lattices are two parents with
# no map between them, and asking whether one's zero equals the other's is not
# a question about $A_4$.  They are asserted below, in the owned vocabulary, as
# what they actually say.
CAPTURED_BY_THE_PREAMBLE = {
    "rank": "rank",
    "is_even": "is_even",
    "signature_pair": "signature_pair",
    "genus": "genus",
    "gram_matrix": "gram_matrix",
    "ngens": "number_of_module_generators",
}


@pytest.mark.parametrize("question", sorted(CAPTURED_BY_THE_PREAMBLE))
def test_the_preamble_captures_sages_answer(question: str) -> None:
    r"""One lattice, one answer, whichever vocabulary asked for it.

    The preamble may return a richer object -- a ``Cardinal`` rather than an
    ``Integer``, a ``CartanMatrix`` rather than a dense matrix -- so equality
    is the test, not identity of type.  A refinement that changed the value
    would not be a refinement.
    """
    preamble_word = CAPTURED_BY_THE_PREAMBLE[question]
    expected = getattr(_NATIVE_A4, question)()
    actual = getattr(IntegralLattice("A4"), preamble_word)()
    assert actual == expected, (
        f"A4.{question}() and A4.{preamble_word}() are one answer"
    )


def test_the_base_ring_is_the_owned_ring_and_captures_sages_answer() -> None:
    r"""$L$ is a $\ZZ$-module, in the session's word and in the engine's.

    A ring is an object, not a value, which is why it is not in the table
    above.  The two universes name one ring with two objects, and those are
    deliberately unequal: asking whether they compare equal is not a question
    about $A_4$, and answering it would be the boundary leaking.

    So the capture is stated as what it means.  The preamble answers with the
    ring the session names -- owned, always, whichever ring the lattice was
    built from -- and crossing that answer to the engine gives the ring Sage
    answers with.  Those two facts together are ``base_ring`` being captured.
    """
    base_ring = IntegralLattice("A4").base_ring()
    assert base_ring is ZZ, (
        "the lattice is a module over the integers the session names"
    )
    assert engine_ring(base_ring) is _NATIVE_A4.base_ring(), (
        "crossing that answer to the engine gives Sage's own base ring"
    )


def test_the_zero_of_a_lattice_is_its_additive_identity() -> None:
    r"""$0\in L$ is what $\mathtt{zero}$ names, and nothing else identifies it.

    Sage's lattice has a zero too, and it prints the same, but it is an
    element of a different parent: what would be compared is two objects with
    no map between them.  The identity is characterised by what it does, so
    that is what is asked.
    """
    lattice = IntegralLattice("A4")
    zero = lattice.zero()
    for generator in lattice.module_generators():
        assert zero + generator == generator, (
            "the additive identity fixes every element it is added to"
        )
        assert (-generator) + generator == zero, (
            "an element plus its negative is the identity"
        )
    assert zero.q() == 0, "the quadratic form takes the identity to 0"


def test_the_module_generators_are_a_framing_carrying_the_gram_matrix() -> None:
    r"""The generators are a rank-many family, and the form on them is $G$.

    ``gens`` on the native lattice returns the same coordinate tuples, but as
    elements of Sage's parent.  What survives the boundary is the mathematics:
    there are $\operatorname{rank}L$ of them, and the matrix of the form in
    that family is the lattice's Gram matrix -- which is what makes them a
    framing rather than an arbitrary spanning set.
    """
    lattice = IntegralLattice("A4")
    module_generators = lattice.module_generators()
    assert module_generators.cardinality() == lattice.rank(), (
        "a framing of a free module of rank n has n members"
    )
    pairings = matrix(
        [[left * right for right in module_generators] for left in module_generators]
    )
    assert pairings == lattice.gram_matrix(), (
        "the Gram matrix is the matrix of the form on the module generators"
    )


# Audited as real mathematics.  Each row is Sage's question, the owned route
# that carries the same mathematics, and the *datum* the two must agree on.
#
# Objects are never compared, and the two routes are not expected to return
# equal things.  An owned object and a Sage object are different on purpose:
# the owned one is richer -- an owned $R[x]$ is an $R$-algebra and not merely
# a ring, an owned dual is a lattice and not a set of vectors in a rational
# space -- and there is no map between the two universes for an equality to
# be asked along.  Sage's own answers are not even equal to themselves here:
# ``free_resolution`` and ``enumerate_short_vectors`` compare False against a
# second call on the same lattice, so object equality was never the question.
#
# What a regression would destroy is the mathematics, so the mathematics is
# what is compared: a Gram determinant, an invariant tuple, a group order, a
# rank.  A row whose owned route does not exist yet fails by naming the
# missing word, which is what makes this table the gap map.
AUDITED_MATHEMATICS = {
    # the object
    "discriminant": (
        lambda lattice: lattice.discriminant(),
        lambda native: native.discriminant(),
    ),
    # the object, gated on definiteness
    "minimum": (
        lambda lattice: lattice.minimum(),
        lambda native: native.minimum(),
    ),
    # the object, gated on definiteness, as a finite Set.  Sage's iterator is
    # infinite -- every vector modulo sign, shorter ones first -- so the datum
    # is how many it yields up to a bound, which is a coefficient of the theta
    # series and an invariant of the lattice.  The vectors themselves are
    # elements, and an element belongs to a parent: the twenty roots of $A_4$
    # in the owned lattice and the twenty in Sage's are not the same objects,
    # which is exactly why they are counted and not listed.
    "enumerate_short_vectors": (
        lambda lattice: lattice.enumerate_short_vectors(2).cardinality(),
        lambda native: len(
            [
                vector
                for vector in itertools.islice(native.enumerate_short_vectors(), 10r)
                if native(vector).inner_product(native(vector)) <= 2
            ]
        ),
    ),
    # coker of the canonical morphism to the dual.  The invariants, not the
    # Gram: the owned form is written on the presented module's generators
    # and Sage's on the invariant-factor ones, which is a choice of generators
    # and not a different group.
    "discriminant_group": (
        lambda lattice: lattice.discriminant_group().invariants(),
        lambda native: native.discriminant_group().invariants(),
    ),
    # an abstract object plus its canonical morphism.  The determinant, not
    # the Gram: Sage's dual is a submodule of a rational space in echelon
    # coordinates and the owned one is free on the dual generators, so the two
    # Gram matrices are two framings of one lattice and $\det$ is what both
    # framings agree on.
    "dual_lattice": (
        lambda lattice: lattice.dual_lattice().gram_matrix().det(),
        lambda native: native.dual_lattice().gram_matrix().det(),
    ),
    # the inclusion morphism -- so it is asked of one.  A bare lattice has no
    # saturation: what gets saturated is the *image* of an arrow, and asking
    # $A_4$ for its own is asking about the identity inclusion, where the
    # answer is $A_4$ whatever the notion means.  $2e_0\subset A_4$ is the
    # arrow with something to say, and it says the same thing on both sides.
    "saturation": (
        lambda lattice: lattice.subobject_on(
            [2 * lattice.module_generators()[0]]
        ).saturation().gram_matrix(),
        lambda native: native.sublattice(
            [2 * native.basis()[0]]
        ).saturation().gram_matrix(),
    ),
    # the inclusion morphism
    "index_in_saturation": (
        lambda lattice: lattice.subobject_on(
            [2 * lattice.module_generators()[0]]
        ).index_in_saturation(),
        lambda native: native.sublattice(
            [2 * native.basis()[0]]
        ).index_in_saturation(),
    ),
    # the inclusion morphism it produces
    "maximal_overlattice": (
        lambda lattice: lattice.maximal_overlattice().codomain().gram_matrix(),
        lambda native: native.maximal_overlattice().gram_matrix(),
    ),
    # End(L), the homset.  What identifies an endset is the object it is the
    # endset of, and $\operatorname{End}$ of a free module of rank $n$ is free
    # of rank $n^2$ -- which is the count Sage answers with a basis.
    "endomorphism_ring": (
        lambda lattice: lattice.End().domain().number_of_module_generators(),
        lambda native: native.endomorphism_ring().domain().rank(),
    ),
    # the units of End(L)
    "orthogonal_group": (
        lambda lattice: lattice.orthogonal_group().order(),
        lambda native: native.orthogonal_group().order(),
    ),
    "automorphisms": (
        lambda lattice: lattice.automorphisms().number_of_group_generators(),
        lambda native: native.automorphisms().ngens(),
    ),
    # the forgetful functor
    "free_module": (
        lambda lattice: lattice.forget_form().number_of_module_generators(),
        lambda native: native.free_module().rank(),
    ),
    # base change to QQ
    "vector_space": (
        lambda lattice: lattice.vector_space().gram_matrix(),
        lambda native: native.vector_space().inner_product_matrix(),
    ),
    # every R-module.  A free module resolves in one step by the identity,
    # which is the differential both sides report.
    "free_resolution": (
        lambda lattice: lattice.free_resolution().matrix(1),
        lambda native: native.free_resolution().matrix(1),
    ),
    # a finitely presented module, as a Set of combinations.  $A_4$ is free,
    # so the Set is empty and both sides say so by its size.
    "relations": (
        lambda lattice: lattice.relations().cardinality(),
        lambda native: native.relations().rank(),
    ),
}

# No ``LLL`` row.  This table asks a lattice a question and compares the two
# answers, and reduction is not a question a lattice answers: it reduces a
# *framing*, so it is defined on a submodule of a definite lattice whose
# target is $I_{n,0}$ or $I_{0,n}$ -- ``DefiniteLattices.Subobjects``.  Sage
# answering ``A4.LLL()`` is Sage conflating a lattice with a chosen basis for
# it, and porting the signature would import that conflation.  The owned
# surface is proved in ``test_subobject_lll.sage``.


@pytest.mark.parametrize("question", sorted(AUDITED_MATHEMATICS))
def test_audited_mathematics_reaches_the_preamble(question: str) -> None:
    r"""Sage answers this and the audit kept it, so the preamble must too.

    Failing here is the gap map: the answer exists in Sage, the notion is
    sound, and the owned word that carries it is missing or disagrees.
    """
    owned_datum, engine_datum = AUDITED_MATHEMATICS[question]
    assert owned_datum(IntegralLattice("A4")) == engine_datum(_NATIVE_A4)


def test_a_maximal_overlattice_is_reached_by_a_proper_inclusion() -> None:
    r"""\(A_1^{\oplus 4}\subset D_4\) has index 2 (Nik80, Prop. 1.4.1).

    $A_4$ is its own maximal overlattice, so the row above it asserts an
    identity and cannot see a search that returns its own input.  The
    discriminant form of $A_1^{\oplus 4}$ is $(\ZZ/2)^4$ with $q$ taking
    the value $-1/2$ on each generator, so the diagonal class is isotropic
    and the correspondence hands back a proper overlattice: $D_4$.
    """
    inclusion = (Lattices.A1 ** 4).maximal_overlattice()
    assert inclusion.index() == 2, (
        "an isotropic class of order 2 glues to an overlattice of index 2"
    )
    assert inclusion.codomain().genus() == Lattices.D4.genus(), (
        "the maximal even overlattice of A1^4 is D4 (CS10 chapter 4)"
    )


# ---------------------------------------------------------------------------
# Generators of the classical arithmetic groups.
#
# Not yet in the project Zotero library, so cited here in full:
#   - Hua & Reiner, "Automorphisms of the unimodular group", Trans. Amer.
#     Math. Soc. 71 (1951), 331-348.  doi:10.1090/s0002-9947-1951-0043847-x
#   - Hua & Reiner, "On the generators of the symplectic modular group",
#     Trans. Amer. Math. Soc. 65 (1949), 415-426.
#     doi:10.1090/s0002-9947-1949-0029942-0
#   - Klingen, "Charakterisierung der Siegelschen Modulgruppe durch ein
#     endliches System definierender Relationen", Math. Ann. 144 (1961),
#     64-82.  doi:10.1007/bf01396543
#   - Borel & Harish-Chandra, "Arithmetic subgroups of algebraic groups",
#     Ann. of Math. 75 (1962), 485-535.  (No DOI on the original; reprinted
#     in Collected Papers, doi:10.1007/978-1-4899-7407-5_57.)  Arithmetic
#     groups are finitely generated -- the theorem that covers Sp_2n(ZZ) and
#     O(L) for indefinite L, where no generating set is in hand.
# ---------------------------------------------------------------------------


def test_the_symplectic_modular_group_is_finitely_generated() -> None:
    r"""Hua and Reiner exhibit a finite generating set for \(Sp_{2n}(\ZZ)\).

    Borel and Harish-Chandra give the same conclusion for every arithmetic
    group, so this holds whether or not Sage can produce the generators.
    """
    assert Sp(4, SageIntegers) in FINITELY_GENERATED


def test_the_unimodular_group_is_finitely_generated() -> None:
    r"""Hua and Reiner, 1951: \(GL_n(\ZZ)\) has a finite generating set."""
    assert GL(3, SageIntegers) in FINITELY_GENERATED
    assert GL(4, SageIntegers) in FINITELY_GENERATED


# ---------------------------------------------------------------------------
# R^n is the preamble's free module, for every ring.
#
# QUIRK.  Nothing here is the preparser's business: ``^`` is exponentiation
# and lowers to ``**``, so what ``R**n`` builds is decided at runtime by the
# ring.  Sage's ``Parent.__pow__`` says as much -- it redirects to the
# category precisely because a Cython parent does not inherit ``ParentMethods``
# -- and then the ring never carries a node that answers.  The mechanical
# routes are all closed: ``ZZ`` refuses ``__class__`` assignment, being a
# non-heap extension type; ``sage.rings.ring.Ring`` refuses ``__init__``
# assignment, so no construction hook exists; and patching
# ``Rings.ParentMethods`` in place does nothing, because ``parent_class`` is
# already built and clearing those caches breaks Sage outright.
#
# REMEDIATION.  The owned scalar hierarchy carries ``__pow__`` once, on its
# ``Rings`` node, and rings are refined into it.  Placement is the whole
# subtlety: a node whose only parent is ``Rings()`` loses ZZ's linearization
# to ``EuclideanDomains``, which inherits Sage's own ``__pow__``, so the owned
# node has to sit deep enough to outrank it.  Refinement on intake covers the
# rings a session builds later, which no hook on Sage's classes could.
# ---------------------------------------------------------------------------

# The session's names, not the engine's: these are the rings a notebook types,
# bound by ``Lattices.install`` above.  ``SageIntegers`` is the same ring read
# behind the boundary, and ``SageIntegers^3`` is Sage's own free module -- so
# naming the engine's ring here would ask the question this section exists to
# distinguish itself from.
RINGS = {
    "ZZ": ZZ,
    "QQ": QQ,
    "GF(5)": GF(5),
    "QQ[x]": QQ["x"],
    "ZZ[x,y]": ZZ["x", "y"],
    "Zmod(6)": Zmod(6),
}


@pytest.mark.parametrize("name", sorted(RINGS))
def test_a_ring_raised_to_a_rank_is_the_preamble_free_module(name: str) -> None:
    r"""\(R^n\) is the free \(R\)-module of rank \(n\) in the preamble's universe.

    The rank is the invariant: whatever \(R^3\) builds, three module generators
    is what a rank-3 free module has.
    """
    ring = RINGS[name]
    module = ring^3
    assert module.base_ring() is ring, f"{name}^3 is a module over {name}"
    assert module.number_of_module_generators() == 3, (
        f"{name}^3 is free of rank 3"
    )
