r"""$K/\mathfrak a$ is a module the preamble owns, so it presents submodules.

A discriminant form takes its values in $\mathbb Q/\mathbb Z$ and a
discriminant quadratic form in $\mathbb Q/2\mathbb Z$.  Both are
$\operatorname{coker}(\mathfrak a\hookrightarrow K)$ for $K=\operatorname{Frac}
(\mathbb Z)$, and the scale of a form is the submodule of its value module
that the form's values generate -- so the value module has to be able to
present a submodule of itself, with the inclusion that exhibits it.

The submodules are cyclic.  Over a principal ideal domain the submodule of
$K/\mathfrak a$ generated by finitely many classes is $(g)/\mathfrak a$ for
$g$ a greatest common divisor of their lifts and of a generator of
$\mathfrak a$, which is cyclic of order $n/g$.  These tests fix that order and
that generator against hand-computed values, and then read the scale of the
$A_2$ discriminant forms, which is the construction the whole surface exists
for.
"""

def _ensure_preamble() -> None:
    if "Lattices" in globals():
        return
    from dzack_research.preamble.install import install_preamble

    install_preamble(globals())
    Lattices.install(globals())


def test_the_session_names_Q_mod_Z_and_lands_it_in_the_owned_category() -> None:
    r"""``QQ/ZZ`` is the value module a discriminant form already uses."""
    _ensure_preamble()
    from dzack_research.preamble.categories.modules.fraction_field_quotients import (
        FractionFieldQuotients,
    )

    rationals_mod_one = QQ / ZZ
    rationals_mod_two = QQ / (2 * ZZ)

    assert rationals_mod_one in FractionFieldQuotients()
    assert rationals_mod_two in FractionFieldQuotients()
    assert rationals_mod_one.modulus() == 1
    assert rationals_mod_two.modulus() == 2
    assert rationals_mod_one.fraction_field() == QQ
    assert rationals_mod_one.is_torsion()
    # The same object the discriminant machinery values its forms in: a
    # second copy would give the scale a codomain no form maps into.
    assert Lattices("A2").discriminant_bilinear_form().value_module() is rationals_mod_one


def test_a_finitely_generated_submodule_of_Q_mod_Z_is_cyclic() -> None:
    r"""$\langle 1/4,1/6\rangle=\langle 1/12\rangle\subset\mathbb Q/\mathbb Z$."""
    _ensure_preamble()
    rationals_mod_one = QQ / ZZ

    submodule = rationals_mod_one.subobject_on(
        [rationals_mod_one(1 / 4), rationals_mod_one(1 / 6)]
    )
    generator = submodule.embedded_module_generators()[0]

    assert submodule.cardinality() == 12
    assert submodule.ambient() is rationals_mod_one
    assert generator == rationals_mod_one(1 / 12)
    # The classification is only correct if the classes it started from are
    # the multiples of that generator the greatest common divisor says.
    assert 3 * generator == rationals_mod_one(1 / 4)
    assert 2 * generator == rationals_mod_one(1 / 6)
    assert 12 * generator == rationals_mod_one.zero()


def test_the_modulus_enters_the_submodule_of_Q_mod_2Z() -> None:
    r"""$\langle 4/3\rangle=\langle 2/3\rangle\subset\mathbb Q/2\mathbb Z$, of order 3."""
    _ensure_preamble()
    rationals_mod_two = QQ / (2 * ZZ)

    submodule = rationals_mod_two.subobject_on([rationals_mod_two(4 / 3)])
    generator = submodule.embedded_module_generators()[0]

    # 2 is the generator of the ideal quotiented out, so it joins the
    # greatest common divisor: gcd(4/3, 2) = 2/3, not 4/3.
    assert generator == rationals_mod_two(2 / 3)
    assert submodule.cardinality() == 3
    assert 2 * generator == rationals_mod_two(4 / 3)


def test_the_fraction_field_is_the_modulus_zero_object() -> None:
    r"""$\mathbb Q=\operatorname{coker}(0\hookrightarrow\mathbb Q)$, framed by $1/n!$."""
    _ensure_preamble()
    from dzack_research.preamble.categories.modules.fraction_field_quotients import (
        FractionFieldQuotients,
    )
    from dzack_research.preamble.categories.modules.pure.torsion_modules import (
        TorsionModules,
    )

    fractions = QQ / (0 * ZZ)

    assert fractions in FractionFieldQuotients()
    assert fractions.modulus() == 0
    # $\mathbb Q$ is torsion free, so it is the one object here that must not
    # be placed where its proper quotients are.
    assert fractions not in TorsionModules(ZZ)
    assert QQ / ZZ in TorsionModules(ZZ)
    assert fractions.module_generator(4).lift() == 1 / 24


def test_the_countable_framing_of_Q_mod_Z_is_surjective_on_specimens() -> None:
    r"""$e_n\mapsto[1/n!]$ frames $\mathbb Q/\mathbb Z$ on countably many labels."""
    _ensure_preamble()
    rationals_mod_one = QQ / ZZ

    framing = rationals_mod_one.framing_morphism()
    labels = framing.domain().module_generating_set()

    assert framing.codomain() is rationals_mod_one
    assert framing.is_surjective()
    assert labels in Sets().Countable()
    assert labels not in Sets().Finite()
    # $3/8=9/24$ and $24=4!$, so the class of $3/8$ is an integral multiple
    # of the fourth framed generator -- which is what surjectivity says here.
    assert 9 * rationals_mod_one.module_generator(4) == rationals_mod_one(3 / 8)
    assert framing(9 * framing.domain().module_generator(4)) == rationals_mod_one(3 / 8)


def test_the_quotient_framing_is_the_fraction_field_framing_projected() -> None:
    r"""$K/\mathfrak a$ is framed by $K$'s framing composed with $K\to K/\mathfrak a$."""
    _ensure_preamble()
    fractions = QQ / (0 * ZZ)
    rationals_mod_one = QQ / ZZ
    projection = rationals_mod_one.projection_from_fraction_field()

    for index in (1, 4, 7):
        assert projection(fractions.module_generator(index).lift()) == (
            rationals_mod_one.module_generator(index)
        )


def test_the_A2_discriminant_bilinear_scale_is_the_subgroup_of_order_three() -> None:
    r"""$\mathfrak s(b_{A_{A_2}})=\tfrac13\mathbb Z/\mathbb Z$."""
    _ensure_preamble()
    discriminant = Lattices("A2").discriminant_bilinear_form()

    scale = discriminant.scale_submodule()
    generator = scale.embedded_module_generators()[0]

    # $A_{A_2}=\mathbb Z/3$ with $b(g,g)=\pm 1/3$, so the values generate
    # the cyclic subgroup of order three and nothing smaller.
    assert scale.ambient() is discriminant.value_module()
    assert generator == discriminant.value_module()(1 / 3)
    assert scale.cardinality() == 3


def test_the_A2_discriminant_quadratic_scale_lives_in_Q_mod_2Z() -> None:
    r"""$\mathfrak s(q_{A_{A_2}})=\tfrac23\mathbb Z/2\mathbb Z$."""
    _ensure_preamble()
    discriminant = Lattices("A2").discriminant_quadratic_form()

    scale = discriminant.scale_submodule()
    generator = scale.embedded_module_generators()[0]

    # $q$ takes the value $\pm 4/3$ on a generator and $\pm 2/3$ on the
    # product of two, and both generate $\langle 2/3\rangle$ mod $2\mathbb Z$.
    assert discriminant.value_module() is QQ / (2 * ZZ)
    assert generator == discriminant.value_module()(2 / 3)
    assert scale.cardinality() == 3
