r"""What the objects are, as mathematics — not as Sage currently reports them.

Every assertion below is a true statement about the object named. A failure is
not a bug in the test: it records that Sage's encoding does not yet carry the
fact, and therefore that the preamble must bridge it. This file is the gap map,
executable, so the map cannot go stale in a chat log.

Sources (Zotero item | Better-BibTeX key):

  - J. E. Humphreys, *Reflection Groups and Coxeter Groups* (1990). Hum90.
    Section 2.11 tabulates the orders of the finite Weyl groups; Section 4.1:
    a Coxeter group is generated by its simple reflections, a finite set, so
    every Coxeter group -- affine ones included -- is finitely generated.
  - Conway & Sloane, *Sphere Packings, Lattices and Groups*, 3rd ed. CS10.
    Chapter 4 tabulates the root lattices and their automorphism groups:
    Aut(A_n) = {+-1} x W(A_n) for n >= 2, |Aut(D_4)| = 1152 (triality),
    -1 in W(E_8) so Aut(E_8) = W(E_8).
  - J.-P. Serre, *Trees* (1980). Ser80. I.4.2: SL(2,ZZ) is the amalgam
    ZZ/4 *_{ZZ/2} ZZ/6, generated by S and T.
  - Dummit & Foote, *Abstract Algebra*, 3rd ed. (2004). DF04.
    Section 4.4: Proposition 16 (Aut of a cyclic group of order n is
    (Z/nZ)^x), Proposition 17 (Aut(C_{2^n}) = Z_2 x Z_{2^{n-2}} for n >= 3;
    Aut of an elementary abelian group is GL_n(F_p), with the displayed
    Aut(V_4) = GL_2(F_2) = S_3; Aut(S_n) = Inn(S_n) = S_n for n != 6 and
    [Aut(S_6) : Inn(S_6)] = 2; Aut(Q_8) = S_4), Corollary 15 with the
    remark following it (Inn(G) = G/Z(G)).
  - Conway, Curtis, Norton, Parker & Wilson, *Atlas of Finite Groups*
    (1985). CCN+85.  The M12 page: Order = 95040 = 2^6.3^3.5.11, Mult = 2,
    Out = 2.

Two facts are asserted without a citation because they are definitional, not
literature: a finite group is finitely generated (its own elements generate
it), and a group presented on a finite generating set is generated by that set.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import dzack_research
import pytest

from sage.all import IntegralLattice as SageIntegralLattice
from sage.all import (
    AbelianGroup,
    CoxeterGroup,
    CyclicPermutationGroup,
    FreeGroup,
    GL,
    KleinFourGroup,
    MathieuGroup,
    PermutationGroup,
    QuaternionGroup,
    SL,
    SO,
    Sp,
    SymmetricGroup,
    WeylGroup,
)
from sage.categories.groups import Groups
from sage.misc.unknown import Unknown

# The engine's own scalars, named as such.  Sage's matrix-group constructors
# are engine constructions and take the rings the engine computes in; the
# session's ``ZZ`` is a different object, and the two are kept apart here so
# that neither question is asked of the other's ring.
from sage.rings.integer_ring import ZZ as SageIntegers
from sage.rings.qqbar import QQbar as SageAlgebraicNumbers
from sage.rings.rational_field import QQ as SageRationals

# The owned category is the surface (AGENTS.md: the preamble owns its
# categories outright); Sage's ``Groups().FinitelyGenerated()`` is a
# declaration registry the preamble consumes on intake, not the node these
# assertions ask about.
from dzack_research.preamble.categories.group.groups import OwnedFinitelyGeneratedGroups
from dzack_research.preamble.refine import refine

FINITELY_GENERATED = OwnedFinitelyGeneratedGroups()

# These are claims about the preamble's universe, so the preamble is loaded:
# ``R^n``, the refinements, and the category layer are what the assertions are
# about.  The sibling ``.sage`` tests load the same file, in the same way.
#
# ``Lattices.install`` is the session boundary: it is what a notebook runs, and
# it is where the names a notebook types -- ``ZZ``, ``QQ``, ``PolynomialRing``
# -- are bound to the owned objects.  Loading ``install.sage`` alone leaves
# them as the engine's, so the ``R^n`` claims below would be asked of the wrong
# rings.
from dzack_research.preamble.install import install_preamble
install_preamble(globals())
Lattices.install(globals())


# ---------------------------------------------------------------------------
# A finite group is finitely generated.  It generates itself.
#
# QUIRK.  Sage's ``FinitelyGenerated`` is a declaration, not a decision.  A
# category is only entered when some constructor says so, and most never do:
# ``FreeGroup(2)``, ``AbelianGroup([5])``, ``GL(3,ZZ)`` and every ``O(L)``
# stand outside it while answering ``ngens`` on request.  So Sage's node
# reads as "somebody wrote it down", and its False carries no mathematics.
#
# REMEDIATION.  The preamble owns the finitely-generated-groups category and
# refines groups into it on intake, reading Sage's declaration as one
# admission source among the decidable ones.  These assertions ask the owned
# node, where membership is a decision.
# ---------------------------------------------------------------------------

FINITE_GROUPS = {
    "Q8": QuaternionGroup(),
    "W(A2)": WeylGroup(["A", 2]),
    "W(A4)": WeylGroup(["A", 4]),
    "W(D4)": WeylGroup(["D", 4]),
    "W(E6)": WeylGroup(["E", 6]),
    "W(E8)": WeylGroup(["E", 8]),
    "Coxeter H3": CoxeterGroup(["H", 3]),
    "Coxeter H4": CoxeterGroup(["H", 4]),
    "O(A2)": IntegralLattice("A2").Aut(),
    "O(A4)": IntegralLattice("A4").Aut(),
    "O(D4)": IntegralLattice("D4").Aut(),
    "O(E6)": IntegralLattice("E6").Aut(),
    "O(E7)": IntegralLattice("E7").Aut(),
    "O(E8)": IntegralLattice("E8").Aut(),
    "Z/5": AbelianGroup([5]),
}


@pytest.mark.parametrize("name", sorted(FINITE_GROUPS))
def test_a_finite_group_is_finitely_generated(name: str) -> None:
    r"""A finite group is generated by its own underlying set."""
    group = FINITE_GROUPS[name]
    assert group in FINITELY_GENERATED, (
        f"{name} is finite, so it is finitely generated"
    )


# ---------------------------------------------------------------------------
# A group whose generators are in hand is finitely generated, finite or not.
# ---------------------------------------------------------------------------

GENERATED_GROUPS = {
    "FreeGroup(2)": (FreeGroup(2), 2),
    "SL(2,ZZ)": (SL(2, SageIntegers), 2),
    "SL(3,ZZ)": (SL(3, SageIntegers), 3),
    "GL(3,ZZ)": (GL(3, SageIntegers), 4),
    "W(A2~)": (WeylGroup(["A", 2, 1]), 3),
    "W(E8~)": (WeylGroup(["E", 8, 1]), 9),
}


@pytest.mark.parametrize("name", sorted(GENERATED_GROUPS))
def test_a_group_presented_on_finite_generators_is_finitely_generated(
    name: str,
) -> None:
    r"""Sage answers ``ngens`` for each of these, so the axiom holds."""
    group, expected_generators = GENERATED_GROUPS[name]
    assert group.ngens() == expected_generators, (
        f"{name} is generated by {expected_generators} elements"
    )
    assert group in FINITELY_GENERATED, (
        f"{name} exhibits {expected_generators} generators, so it is "
        "finitely generated"
    )


def test_the_free_group_on_two_generators_is_the_definitional_case() -> None:
    r"""\(F_2\) is free ON two generators.  Nothing is more finitely generated."""
    free_group = FreeGroup(2)
    assert free_group.ngens() == 2
    assert free_group.is_finite() is False
    assert free_group in FINITELY_GENERATED


def test_refinement_repairs_an_undeclared_axiom_without_loss() -> None:
    r"""Refining supplies the fact Sage never declared, and costs nothing.

    This is the whole bridge in one assertion: the category and the
    ``refine`` mechanism are the preamble's own, the evidence is Sage's
    own ``ngens``, and the object keeps every answer it had before.  If
    this fails, the preamble cannot repair category membership by
    refinement and needs a different mechanism.
    """
    group = GL(3, SageIntegers)
    generators_before = group.ngens()
    assert generators_before == 4

    refine(group, FINITELY_GENERATED)

    assert group in FINITELY_GENERATED
    assert group.ngens() == generators_before, (
        "refinement adds a category; it does not disturb the group"
    )
    assert group.is_finite() is False


# ---------------------------------------------------------------------------
# Orders, from the literature.  Hum90 sec 2.11 and CS10 ch. 4.
# ---------------------------------------------------------------------------

WEYL_ORDERS = {  # Hum90, section 2.11
    ("A", 2): 6,
    ("A", 4): 120,
    ("D", 4): 192,
    ("E", 6): 51840,
    ("E", 7): 2903040,
    ("E", 8): 696729600,
}


@pytest.mark.parametrize("cartan_type", sorted(WEYL_ORDERS))
def test_finite_weyl_group_order_matches_humphreys(cartan_type: tuple) -> None:
    r"""\(|W|\) as tabulated in Humphreys, not as recomputed from Sage."""
    letter, rank = cartan_type
    group = WeylGroup([letter, rank])
    assert group.order() == WEYL_ORDERS[cartan_type], (
        f"|W({letter}{rank})| is tabulated in Hum90 section 2.11"
    )


ROOT_LATTICE_AUTOMORPHISM_ORDERS = {  # CS10, chapter 4
    "A2": 12,
    "A4": 240,
    "D4": 1152,
    "E6": 103680,
    "E7": 2903040,
    "E8": 696729600,
}


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_root_lattice_automorphism_order_matches_conway_sloane(name: str) -> None:
    r"""\(|\mathrm{Aut}(L)|\) as tabulated in Conway and Sloane."""
    orthogonal_group = IntegralLattice(name).Aut()
    assert orthogonal_group.order() == ROOT_LATTICE_AUTOMORPHISM_ORDERS[name], (
        f"|Aut({name})| is tabulated in CS10 chapter 4"
    )


# ---------------------------------------------------------------------------
# O(L): one group, dropped in eight places.
#
# QUIRK, upstream.  Sage builds the isometry group twice.  ``L.automorphisms()
# is L.orthogonal_group()`` is False on a native lattice, so the same group
# has two identities before the preamble is involved at all.  Sage's copies do
# answer ``order`` and ``ngens`` correctly -- 240 and 4 for A_4 -- and neither
# copy is in ``FinitelyGenerated``.
#
# QUIRK, preamble.  The preamble does not refine Sage's lattice; it builds its
# own ``FormModule`` and rebinds the name.  Nothing of Sage's MRO is inherited,
# so ``orthogonal_group`` and ``automorphisms`` are simply absent, and what
# ``Aut()`` returns is a third object again.  That object declares itself in
# ``Groups()`` and cannot answer ``order``, ``cardinality``,
# ``number_of_group_generators`` or ``is_finite``, and cannot be iterated --
# while holding its own ``group_generators``.  The data is present; the
# vocabulary never arrived.
#
# REMEDIATION.  One object, reached one way.  The isometry group is the units
# of ``End(L)``, so the lattice needs an endset -- it has ``Hom`` and no
# ``End`` -- and ``orthogonal_group``, ``automorphisms`` and ``Aut`` become
# one name for what that homset yields, the other spellings kept only if they
# return the identical object.  ``order`` and enumeration are not
# written on the group: they are what the groups category already supplies to
# anything refined into it, which is why the missing refinement and the
# missing methods are a single defect.  A generating set already in hand makes
# the finite-generation refinement immediate, so ``O(L)`` leaves the
# equivariance heuristic's hard branch entirely.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_the_orthogonal_group_and_the_automorphism_group_are_one_object(
    name: str,
) -> None:
    r"""\(O(L)\) and \(\mathrm{Aut}(L)\) are two names for the same group.

    A lattice is a module with a form; its automorphisms are exactly the
    isometries.  Two accessors that answer differently -- or one that answers
    and one that does not -- mean the object was built twice.
    """
    lattice = IntegralLattice(name)
    assert lattice.orthogonal_group() is lattice.Aut(), (
        f"O({name}) and Aut({name}) are the same group"
    )


@pytest.mark.parametrize("name", sorted(ROOT_LATTICE_AUTOMORPHISM_ORDERS))
def test_a_finite_automorphism_group_reports_its_order(name: str) -> None:
    r"""\(|\mathrm{Aut}(L)|\) is a question every finite group answers.

    Order lives on the groups category, so a group that cannot answer it has
    not been refined into one.
    """
    automorphisms = IntegralLattice(name).Aut()
    assert automorphisms.order() == ROOT_LATTICE_AUTOMORPHISM_ORDERS[name]


def test_the_isometry_group_is_built_once() -> None:
    r"""One group, one object, however many times it is asked for.

    Sage splits \(O(L)\): ``automorphisms`` and ``orthogonal_group`` are one
    function there, and it caches nothing, so two calls are two objects.  The
    repair is not to make the lattice cache the group -- the group owns its
    own computations -- but to reach it one way, through the endset, and let
    it hold what it computes.  A generating set computed once stays computed
    only if asking again is asking the same object.
    """
    lattice = IntegralLattice("A4")
    automorphisms = lattice.Aut()
    assert lattice.Aut() is automorphisms
    assert lattice.orthogonal_group() is automorphisms
    assert lattice.automorphisms() is automorphisms
    assert automorphisms.group_generators() is automorphisms.group_generators(), (
        "a group that recomputes its generators has not held them"
    )


def test_the_isometry_group_is_finitely_presented() -> None:
    r"""\(O(L)\) is an arithmetic group, so it has a finite presentation.

    Borel and Harish-Chandra, which covers indefinite \(L\) too -- the axiom
    is a theorem about the group and not a report of what this session
    managed to compute.  Carrying it means answering for it: a finitely
    presented group exhibits generators and the relations they satisfy.
    """
    automorphisms = IntegralLattice("A4").Aut()
    assert automorphisms in OwnedFinitelyPresentedGroups()
    assert automorphisms.presenting_free_group().ngens() == 4, (
        "the presentation is written in the four generators of O(A4)"
    )
    assert automorphisms.defining_relations(), (
        "a group of order 240 on four generators satisfies relations"
    )


# The words in the preamble's own vocabulary.  ``gens`` and ``ngens`` are not
# among them: a group generates *as a group*, and the bare word leaves open
# which structure is meant, so the preamble spells it out.  What is asked of
# the object is the question, not the spelling, and the question is the same
# one Sage's ``gens`` was reaching for.
GROUP_VOCABULARY = (
    "order",
    "cardinality",
    "group_generators",
    "number_of_group_generators",
    "is_finite",
)


@pytest.mark.parametrize("question", GROUP_VOCABULARY)
def test_a_group_answers_the_group_vocabulary(question: str) -> None:
    r"""\(\mathrm{Aut}(L)\) sits in ``Groups()`` and must speak as one.

    Membership in a category is a promise about the questions the object
    answers.  ``Aut(A4)`` is in ``Groups()``, holds its generators, and is
    finite of order 240 -- so every word below has an answer.
    """
    automorphisms = IntegralLattice("A4").Aut()
    assert automorphisms in Groups()
    answer = getattr(automorphisms, question, None)
    assert callable(answer), (
        f"a group answers {question}(); the groups category owns it"
    )
    answer()


def test_a_finite_group_can_be_enumerated() -> None:
    r"""A finite group is a finite set, so its elements can be listed."""
    automorphisms = IntegralLattice("A4").Aut()
    elements = list(automorphisms)
    assert len(elements) == ROOT_LATTICE_AUTOMORPHISM_ORDERS["A4"]


def test_a_lattice_has_an_endomorphism_ring() -> None:
    r"""\(\mathrm{End}(L)\) is the homset \(O(L)\)'s units come from.

    ``Hom`` exists; the endset does not, so the automorphism group cannot be
    reached the way the audit sited it.
    """
    lattice = IntegralLattice("A4")
    endomorphisms = lattice.End()
    assert endomorphisms is lattice.Hom(lattice)


def test_aut_of_a_n_is_plus_minus_one_times_the_weyl_group() -> None:
    r"""CS10 ch. 4: \(\mathrm{Aut}(A_n)=\{\pm1\}\times W(A_n)\) for \(n\ge2\)."""
    for rank in (2, 4):
        automorphisms = IntegralLattice(f"A{rank}").Aut().order()
        weyl = WeylGroup(["A", rank]).order()
        assert automorphisms == 2 * weyl, (
            f"Aut(A{rank}) is {{+-1}} x W(A{rank})"
        )


def test_minus_one_lies_in_the_weyl_group_of_e8() -> None:
    r"""CS10 ch. 4: \(-1\in W(E_8)\), so \(\mathrm{Aut}(E_8)=W(E_8)\)."""
    assert (
        IntegralLattice("E8").Aut().order()
        == WeylGroup(["E", 8]).order()
    )


def test_sl2z_is_the_amalgam_serre_describes() -> None:
    r"""Ser80 I.4.2: \(SL_2(\ZZ)\cong\ZZ/4*_{\ZZ/2}\ZZ/6\), on two generators."""
    group = SL(2, SageIntegers)
    assert group.ngens() == 2, "S and T generate SL(2,ZZ)"
    assert group.is_finite() is False
    assert group in FINITELY_GENERATED


# ---------------------------------------------------------------------------
# Every group answers.  "I do not know" is an answer; an exception is not.
#
# QUIRK.  Sage ships the three-valued truth value ``Unknown`` and then does
# not use it here.  ``Sp(4,ZZ).ngens()`` raises ``AttributeError`` and its
# ``is_finite()`` raises ``NotImplementedError``; ``GL(2,QQbar)`` answers
# ``is_finite`` and raises for ``ngens``.  Two different absences -- no such
# method, and a method that declines to decide -- arrive as two exception
# types, neither of which is mathematics, so callers must catch to learn what
# is true.  ``bool(Unknown)`` then raises rather than collapsing, which is the
# right choice and the reason the value must be matched on, never tested.
#
# REMEDIATION.  The preamble's probes are total: a count or ``Unknown``, a
# truth value or ``Unknown``, never an exception.  Layered, because no single
# signal is sound -- the declared axiom is trusted when present, otherwise the
# object is asked, otherwise Unknown -- and separated into whether generators
# exist in principle, whether an algorithm can produce them, and whether they
# are already computed, since only the last is free.  Equivariance is then
# checked on generators when they are available, and when they are not the
# morphism records that it was not checked rather than pretending.
# ---------------------------------------------------------------------------

GROUPS_WITHOUT_KNOWN_GENERATORS = {
    "Sp(4,ZZ)": Sp(4, SageIntegers),
    "SO(3,QQ)": SO(3, SageRationals),
    "GL(2,QQbar)": GL(2, SageAlgebraicNumbers),
}


@pytest.mark.parametrize("name", sorted(GROUPS_WITHOUT_KNOWN_GENERATORS))
def test_finite_generation_is_a_value_never_an_exception(name: str) -> None:
    r"""A predicate that cannot decide returns ``Unknown``.

    Raising forces callers to use exception handling as control flow, and two
    different absences (no such method, method declines) arrive as two
    different exception types carrying no mathematics.
    """
    group = GROUPS_WITHOUT_KNOWN_GENERATORS[name]
    answer = group.is_finitely_generated()
    assert answer is True or answer is False or answer is Unknown, (
        f"{name} must answer finite generation with a truth value"
    )


@pytest.mark.parametrize("name", sorted(GROUPS_WITHOUT_KNOWN_GENERATORS))
def test_generator_count_is_a_value_never_an_exception(name: str) -> None:
    r"""``ngens`` is ``Unknown`` when unknown, not ``AttributeError``."""
    group = GROUPS_WITHOUT_KNOWN_GENERATORS[name]
    count = group.ngens()
    assert count is Unknown or count in SageIntegers, (
        f"{name} must report a generator count or Unknown"
    )


def test_finiteness_is_a_value_never_an_exception() -> None:
    r"""``Sp(4,ZZ)`` is infinite; a decision procedure that declines says so."""
    answer = Sp(4, SageIntegers).is_finite()
    assert answer is True or answer is False or answer is Unknown


def test_the_absolute_galois_group_of_the_rationals_is_constructible() -> None:
    r"""\(\mathrm{Gal}(\overline{\QQ}/\QQ)\) is a group, so it is an object.

    Profinite and not finitely generated -- the cleanest witness for the
    branch that cannot check equivariance.

    Asked of $\QQ$, which is the field it is the absolute Galois group *of*.
    $\overline{\QQ}$ has no Galois group of its own -- it is separably closed
    -- so ``QQbar.galois_group()`` was a question about the wrong field, and
    the preamble sites the answer where it belongs: on the base field.
    """
    galois_group = QQ.absolute_galois_group()
    assert galois_group in Groups()


# ---------------------------------------------------------------------------
# Restriction to a subfield, on the tower $\QQ\subset\QQ(i),\QQ(\sqrt3)\subset
# \QQ(\zeta_{12})$.
#
# $\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\cong(\ZZ/2)^2$ acts by
# $\zeta_{12}\mapsto\zeta_{12}^k$ for $k\in\{1,5,7,11\}$, and the three
# quadratic subfields are the fixed fields of its three subgroups of order 2.
# Which subfield an element moves is therefore a different fact for each
# element, and it is arithmetic anyone can redo by hand:
#
#   $i=\zeta_{12}^3$ and $\sqrt3=\zeta_{12}+\zeta_{12}^{-1}$, so
#   $k=11$ (complex conjugation) sends $i\mapsto-i$ and fixes $\sqrt3$;
#   $k=5$ fixes $i$ and sends $\sqrt3\mapsto-\sqrt3$;
#   $k=7$ moves both.
#
# The group is abelian, so these restrictions do not depend on which of the two
# embeddings of the subfield the choice policy takes.
# ---------------------------------------------------------------------------

from dzack_research.preamble.categories.group.profinite.galois_quotient import (
    extensions_along,
)

_ZETA_12 = CyclotomicField(12)
_GAUSSIAN = QuadraticField(-1, "i")
_REAL_QUADRATIC = QuadraticField(3, "r")

# Sage names the elements of a Galois group by a permutation of the roots; the
# mathematics names them by the power of $\zeta_{12}$ they produce, so that is
# how they are looked up here.
_BY_EXPONENT = {
    (_ZETA_12.gen() ** exponent): exponent
    for exponent in (1, 5, 7, 11)
}


def _automorphism_sending_zeta_to_power(exponent: int):
    r"""Return the \(\sigma\in\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\) with \(\zeta\mapsto\zeta^{e}\)."""
    generator = _ZETA_12.gen()
    matches = [
        sigma
        for sigma in _ZETA_12.galois_group()
        if sigma(generator) == generator**exponent
    ]
    assert len(matches) == 1, f"no unique automorphism for exponent {exponent}"
    return matches[0]


# Each row: the exponent $k$, and whether $\zeta_{12}\mapsto\zeta_{12}^k$ moves
# $i$ and whether it moves $\sqrt3$.
MOVES_THE_SUBFIELD_GENERATOR = {
    1: (False, False),
    5: (False, True),
    7: (True, True),
    11: (True, False),
}


@pytest.mark.parametrize("exponent", sorted(MOVES_THE_SUBFIELD_GENERATOR))
def test_restriction_to_a_subfield_is_the_arithmetic_of_that_subfield(
    exponent: int,
) -> None:
    r"""\(\zeta_{12}\mapsto\zeta_{12}^{k}\) restricts to the right automorphism of each subfield.

    Complex conjugation is the case that separates the two subfields:
    $\sqrt3=\zeta_{12}+\zeta_{12}^{-1}$ is real, so conjugation fixes it while
    sending $i$ to $-i$. A restriction computed on the wrong subfield, or with
    the two embeddings confused, gets this row wrong.
    """
    lifted = QQ.absolute_galois_group().lift(
        _automorphism_sending_zeta_to_power(exponent)
    )
    moves_i, moves_root_three = MOVES_THE_SUBFIELD_GENERATOR[exponent]

    to_gaussian = lifted.restrict(_GAUSSIAN)
    assert (to_gaussian(_GAUSSIAN.gen()) == -_GAUSSIAN.gen()) is moves_i, (
        f"zeta12 |-> zeta12^{exponent} sends i to {to_gaussian(_GAUSSIAN.gen())}"
    )

    to_real = lifted.restrict(_REAL_QUADRATIC)
    assert (
        to_real(_REAL_QUADRATIC.gen()) == -_REAL_QUADRATIC.gen()
    ) is moves_root_three, (
        f"zeta12 |-> zeta12^{exponent} sends sqrt3 to "
        f"{to_real(_REAL_QUADRATIC.gen())}"
    )


def test_restriction_to_a_subfield_is_a_group_homomorphism() -> None:
    r"""\(\mathrm{Gal}(\QQ(\zeta_{12})/\QQ)\to\mathrm{Gal}(\QQ(i)/\QQ)\) is a homomorphism.

    Restriction being multiplicative is what makes it the map in
    $1\to G_{\QQ(i)}\to G_\QQ\to\mathrm{Gal}(\QQ(i)/\QQ)\to1$ rather than an
    assignment of automorphisms one at a time.
    """
    group = QQ.absolute_galois_group()
    quotient = _ZETA_12.galois_group()
    gaussian_generator = _GAUSSIAN.gen()
    for sigma, tau in itertools.product(quotient, quotient):
        product = group.lift(sigma * tau).restrict(_GAUSSIAN)
        composite = group.lift(sigma).restrict(_GAUSSIAN)(
            group.lift(tau).restrict(_GAUSSIAN)(gaussian_generator)
        )
        assert product(gaussian_generator) == composite, (
            f"restriction of {sigma}*{tau} is not the composite of the restrictions"
        )


def test_the_extensions_of_an_automorphism_form_a_coset_of_the_open_subgroup() -> None:
    r"""The automorphisms of \(\QQ(\zeta_{12})\) extending \(i\mapsto-i\) number \([\QQ(\zeta_{12}):\QQ(i)]\).

    Galois theory: the set of extensions of $\tau$ to $M$ is a coset of
    $\mathrm{Gal}(M/L)$, hence nonempty and of size $[M:L]=2$ here. The two are
    $k=7$ and $k=11$, the elements that move $i$.
    """
    embedding = _GAUSSIAN.embeddings(_ZETA_12)[0]
    conjugation = [
        automorphism
        for automorphism in _GAUSSIAN.embeddings(_GAUSSIAN)
        if automorphism(_GAUSSIAN.gen()) == -_GAUSSIAN.gen()
    ][0]
    candidates = [sigma.as_hom() for sigma in _ZETA_12.galois_group()]

    extensions = extensions_along(conjugation, embedding, candidates)

    # $\mathrm{Gal}(M/\QQ)$ is partitioned into these cosets, one per
    # automorphism of $\QQ(i)$, so each has $|\mathrm{Gal}(M/\QQ)|/|\mathrm{Aut}
    # (\QQ(i))|$ members -- the Galois correspondence, counted.
    assert len(extensions) == len(candidates) // len(
        _GAUSSIAN.embeddings(_GAUSSIAN)
    )
    generator = _ZETA_12.gen()
    assert {_BY_EXPONENT[extension(generator)] for extension in extensions} == {7, 11}


# ---------------------------------------------------------------------------
# The preamble universe loses nothing Sage's lattices could already answer.
#
# A root lattice is one object.  Whichever constructor built it, every question
# Sage's lattice answers has an answer here, equal to Sage's or refining it.
# The surface is derived from the native lattice at import rather than listed,
# so the sweep cannot silently shrink as Sage grows.
# ---------------------------------------------------------------------------


_NATIVE_A4 = SageIntegralLattice("A4")


def _owned_a4() -> "Parent":
    r"""The owned $A_4$, crossed to Sage's sign convention for the audit.

    The named root lattices are *negative* definite (the AG convention,
    enforced at the single construction site in ``_gram_from_name``), while
    Sage's are positive definite.  The audit compares mathematics, not sign
    conventions, so the owned specimen crosses back by one twist.
    """
    return IntegralLattice("A4").twist(-1)


# Sage's question, and the word the preamble already answers it with.  A pair
# is here only if the mathematics survived the audit: the imprecise accessors
# (``dimension`` for rank, ``signature`` for the index p-q, ``determinant`` for
# the discriminant, everything about a basis) are absent on purpose.
#
# Every answer here is a *value* -- a number, a matrix, a ring, a genus symbol
# -- which is what makes comparing the two vocabularies meaningful.  The
# element-valued answers, ``zero`` and the module generators, are not in the
# table: an element belongs to a parent, the two lattices are two parents with
# no map between them, and asking whether one's zero equals the other's is not
# a question about $A_4$.  They are asserted below, in the owned vocabulary, as
# what they actually say.
CAPTURED_BY_THE_PREAMBLE = {
    "rank": "rank",
    "is_even": "is_even",
    "signature_pair": "signature_pair",
    # No ``genus`` row: the owned ``genus()`` returns the owned value object
    # (signature pair + discriminant quadratic form, Nik80 Cor. 1.9.4), not
    # Sage's symbol, so equality across the boundary is no longer the
    # question; the genus mathematics is asserted in its own rows below.
    "gram_matrix": "gram_matrix",
    "ngens": "number_of_module_generators",
}


@pytest.mark.parametrize("question", sorted(CAPTURED_BY_THE_PREAMBLE))
def test_the_preamble_captures_sages_answer(question: str) -> None:
    r"""One lattice, one answer, whichever vocabulary asked for it.

    The preamble may return a richer object -- a ``Cardinal`` rather than an
    ``Integer``, a ``CartanMatrix`` rather than a dense matrix -- so equality
    is the test, not identity of type.  A refinement that changed the value
    would not be a refinement.
    """
    preamble_word = CAPTURED_BY_THE_PREAMBLE[question]
    expected = getattr(_NATIVE_A4, question)()
    actual = getattr(_owned_a4(), preamble_word)()
    assert actual == expected, (
        f"A4.{question}() and A4.{preamble_word}() are one answer"
    )


def test_the_base_ring_is_the_owned_ring_and_captures_sages_answer() -> None:
    r"""$L$ is a $\ZZ$-module, in the session's word and in the engine's.

    A ring is an object, not a value, which is why it is not in the table
    above.  The two universes name one ring with two objects, and those are
    deliberately unequal: asking whether they compare equal is not a question
    about $A_4$, and answering it would be the boundary leaking.

    So the capture is stated as what it means.  The preamble answers with the
    ring the session names -- owned, always, whichever ring the lattice was
    built from -- and crossing that answer to the engine gives the ring Sage
    answers with.  Those two facts together are ``base_ring`` being captured.
    """
    base_ring = IntegralLattice("A4").base_ring()
    assert base_ring is ZZ, (
        "the lattice is a module over the integers the session names"
    )
    assert engine_ring(base_ring) is _NATIVE_A4.base_ring(), (
        "crossing that answer to the engine gives Sage's own base ring"
    )


def test_the_zero_of_a_lattice_is_its_additive_identity() -> None:
    r"""$0\in L$ is what $\mathtt{zero}$ names, and nothing else identifies it.

    Sage's lattice has a zero too, and it prints the same, but it is an
    element of a different parent: what would be compared is two objects with
    no map between them.  The identity is characterised by what it does, so
    that is what is asked.
    """
    lattice = IntegralLattice("A4")
    zero = lattice.zero()
    for generator in lattice.module_generators():
        assert zero + generator == generator, (
            "the additive identity fixes every element it is added to"
        )
        assert (-generator) + generator == zero, (
            "an element plus its negative is the identity"
        )
    assert zero.q() == 0, "the quadratic form takes the identity to 0"


def test_the_module_generators_are_a_framing_carrying_the_gram_matrix() -> None:
    r"""The generators are a rank-many family, and the form on them is $G$.

    ``gens`` on the native lattice returns the same coordinate tuples, but as
    elements of Sage's parent.  What survives the boundary is the mathematics:
    there are $\operatorname{rank}L$ of them, and the matrix of the form in
    that family is the lattice's Gram matrix -- which is what makes them a
    framing rather than an arbitrary spanning set.
    """
    lattice = IntegralLattice("A4")
    module_generators = lattice.module_generators()
    assert module_generators.cardinality() == lattice.rank(), (
        "a framing of a free module of rank n has n members"
    )
    pairings = matrix(
        [[left * right for right in module_generators] for left in module_generators]
    )
    assert pairings == lattice.gram_matrix(), (
        "the Gram matrix is the matrix of the form on the module generators"
    )


# Audited as real mathematics.  Each row is Sage's question, the owned route
# that carries the same mathematics, and the *datum* the two must agree on.
#
# Objects are never compared, and the two routes are not expected to return
# equal things.  An owned object and a Sage object are different on purpose:
# the owned one is richer -- an owned $R[x]$ is an $R$-algebra and not merely
# a ring, an owned dual is a lattice and not a set of vectors in a rational
# space -- and there is no map between the two universes for an equality to
# be asked along.  Sage's own answers are not even equal to themselves here:
# ``free_resolution`` and ``enumerate_short_vectors`` compare False against a
# second call on the same lattice, so object equality was never the question.
#
# What a regression would destroy is the mathematics, so the mathematics is
# what is compared: a Gram determinant, an invariant tuple, a group order, a
# rank.  A row whose owned route does not exist yet fails by naming the
# missing word, which is what makes this table the gap map.
AUDITED_MATHEMATICS = {
    # the object
    "discriminant": (
        lambda lattice: lattice.discriminant(),
        lambda native: native.discriminant(),
    ),
    # the object, gated on definiteness
    "minimum": (
        lambda lattice: lattice.minimum(),
        lambda native: native.minimum(),
    ),
    # the object, gated on definiteness, as a finite Set.  Sage's iterator is
    # infinite -- every vector modulo sign, shorter ones first -- so the datum
    # is how many it yields up to a bound, which is a coefficient of the theta
    # series and an invariant of the lattice.  The vectors themselves are
    # elements, and an element belongs to a parent: the twenty roots of $A_4$
    # in the owned lattice and the twenty in Sage's are not the same objects,
    # which is exactly why they are counted and not listed.
    "enumerate_short_vectors": (
        lambda lattice: lattice.enumerate_short_vectors(2).cardinality(),
        lambda native: len(
            [
                vector
                for vector in itertools.islice(native.enumerate_short_vectors(), 10r)
                if native(vector).inner_product(native(vector)) <= 2
            ]
        ),
    ),
    # coker of the canonical morphism to the dual.  The invariants, not the
    # Gram: the owned form is written on the presented module's generators
    # and Sage's on the invariant-factor ones, which is a choice of generators
    # and not a different group.
    "discriminant_group": (
        lambda lattice: lattice.discriminant_group().invariants(),
        lambda native: native.discriminant_group().invariants(),
    ),
    # an abstract object plus its canonical morphism.  The determinant, not
    # the Gram: Sage's dual is a submodule of a rational space in echelon
    # coordinates and the owned one is free on the dual generators, so the two
    # Gram matrices are two framings of one lattice and $\det$ is what both
    # framings agree on.
    "dual_lattice": (
        lambda lattice: lattice.dual_lattice().gram_matrix().det(),
        lambda native: native.dual_lattice().gram_matrix().det(),
    ),
    # the inclusion morphism -- so it is asked of one.  A bare lattice has no
    # saturation: what gets saturated is the *image* of an arrow, and asking
    # $A_4$ for its own is asking about the identity inclusion, where the
    # answer is $A_4$ whatever the notion means.  $2e_0\subset A_4$ is the
    # arrow with something to say, and it says the same thing on both sides.
    "saturation": (
        lambda lattice: lattice.subobject_on(
            [2 * lattice.module_generators()[0]]
        ).saturation().gram_matrix(),
        lambda native: native.sublattice(
            [2 * native.basis()[0]]
        ).saturation().gram_matrix(),
    ),
    # the inclusion morphism
    "index_in_saturation": (
        lambda lattice: lattice.subobject_on(
            [2 * lattice.module_generators()[0]]
        ).index_in_saturation(),
        lambda native: native.sublattice(
            [2 * native.basis()[0]]
        ).index_in_saturation(),
    ),
    # the inclusion morphism it produces
    "maximal_overlattice": (
        lambda lattice: lattice.maximal_overlattice().codomain().gram_matrix(),
        lambda native: native.maximal_overlattice().gram_matrix(),
    ),
    # End(L), the homset.  What identifies an endset is the object it is the
    # endset of, and $\operatorname{End}$ of a free module of rank $n$ is free
    # of rank $n^2$ -- which is the count Sage answers with a basis.
    "endomorphism_ring": (
        lambda lattice: lattice.End().domain().number_of_module_generators(),
        lambda native: native.endomorphism_ring().domain().rank(),
    ),
    # the units of End(L)
    "orthogonal_group": (
        lambda lattice: lattice.orthogonal_group().order(),
        lambda native: native.orthogonal_group().order(),
    ),
    "automorphisms": (
        lambda lattice: lattice.automorphisms().number_of_group_generators(),
        lambda native: native.automorphisms().ngens(),
    ),
    # the forgetful functor
    "free_module": (
        lambda lattice: lattice.forget_form().number_of_module_generators(),
        lambda native: native.free_module().rank(),
    ),
    # base change to QQ
    "vector_space": (
        lambda lattice: lattice.vector_space().gram_matrix(),
        lambda native: native.vector_space().inner_product_matrix(),
    ),
    # every R-module.  A free module resolves in one step by the identity,
    # which is the differential both sides report.
    "free_resolution": (
        lambda lattice: lattice.free_resolution().matrix(1),
        lambda native: native.free_resolution().matrix(1),
    ),
    # a finitely presented module, as a Set of combinations.  $A_4$ is free,
    # so the Set is empty and both sides say so by its size.
    "relations": (
        lambda lattice: lattice.relations().cardinality(),
        lambda native: native.relations().rank(),
    ),
}

# No ``LLL`` row.  This table asks a lattice a question and compares the two
# answers, and reduction is not a question a lattice answers: it reduces a
# *framing*, so it is defined on a submodule of a definite lattice whose
# target is $I_{n,0}$ or $I_{0,n}$ -- ``DefiniteLattices.Subobjects``.  Sage
# answering ``A4.LLL()`` is Sage conflating a lattice with a chosen basis for
# it, and porting the signature would import that conflation.  The owned
# surface is proved in ``test_subobject_lll.sage``.


@pytest.mark.parametrize("question", sorted(AUDITED_MATHEMATICS))
def test_audited_mathematics_reaches_the_preamble(question: str) -> None:
    r"""Sage answers this and the audit kept it, so the preamble must too.

    Failing here is the gap map: the answer exists in Sage, the notion is
    sound, and the owned word that carries it is missing or disagrees.
    """
    owned_datum, engine_datum = AUDITED_MATHEMATICS[question]
    assert owned_datum(_owned_a4()) == engine_datum(_NATIVE_A4)


def test_a_maximal_overlattice_is_reached_by_a_proper_inclusion() -> None:
    r"""\(A_1^{\oplus 4}\subset D_4\) has index 2 (Nik80, Prop. 1.4.1).

    $A_4$ is its own maximal overlattice, so the row above it asserts an
    identity and cannot see a search that returns its own input.  The
    discriminant form of $A_1^{\oplus 4}$ is $(\ZZ/2)^4$ with $q$ taking
    the value $-1/2$ on each generator, so the diagonal class is isotropic
    and the correspondence hands back a proper overlattice: $D_4$.
    """
    inclusion = (Lattices.A1 ** 4).maximal_overlattice()
    assert inclusion.index() == 2, (
        "an isotropic class of order 2 glues to an overlattice of index 2"
    )
    assert inclusion.codomain().genus() == Lattices.D4.genus(), (
        "the maximal even overlattice of A1^4 is D4 (CS10 chapter 4)"
    )


# ---------------------------------------------------------------------------
# Generators of the classical arithmetic groups.
#
# Not yet in the project Zotero library, so cited here in full:
#   - Hua & Reiner, "Automorphisms of the unimodular group", Trans. Amer.
#     Math. Soc. 71 (1951), 331-348.  doi:10.1090/s0002-9947-1951-0043847-x
#   - Hua & Reiner, "On the generators of the symplectic modular group",
#     Trans. Amer. Math. Soc. 65 (1949), 415-426.
#     doi:10.1090/s0002-9947-1949-0029942-0
#   - Klingen, "Charakterisierung der Siegelschen Modulgruppe durch ein
#     endliches System definierender Relationen", Math. Ann. 144 (1961),
#     64-82.  doi:10.1007/bf01396543
#   - Borel & Harish-Chandra, "Arithmetic subgroups of algebraic groups",
#     Ann. of Math. 75 (1962), 485-535.  (No DOI on the original; reprinted
#     in Collected Papers, doi:10.1007/978-1-4899-7407-5_57.)  Arithmetic
#     groups are finitely generated -- the theorem that covers Sp_2n(ZZ) and
#     O(L) for indefinite L, where no generating set is in hand.
# ---------------------------------------------------------------------------


def test_the_symplectic_modular_group_is_finitely_generated() -> None:
    r"""Hua and Reiner exhibit a finite generating set for \(Sp_{2n}(\ZZ)\).

    Borel and Harish-Chandra give the same conclusion for every arithmetic
    group, so this holds whether or not Sage can produce the generators.
    """
    assert Sp(4, SageIntegers) in FINITELY_GENERATED


def test_the_unimodular_group_is_finitely_generated() -> None:
    r"""Hua and Reiner, 1951: \(GL_n(\ZZ)\) has a finite generating set."""
    assert GL(3, SageIntegers) in FINITELY_GENERATED
    assert GL(4, SageIntegers) in FINITELY_GENERATED


# ---------------------------------------------------------------------------
# R^n is the preamble's free module, for every ring.
#
# QUIRK.  Nothing here is the preparser's business: ``^`` is exponentiation
# and lowers to ``**``, so what ``R**n`` builds is decided at runtime by the
# ring.  Sage's ``Parent.__pow__`` says as much -- it redirects to the
# category precisely because a Cython parent does not inherit ``ParentMethods``
# -- and then the ring never carries a node that answers.  The mechanical
# routes are all closed: ``ZZ`` refuses ``__class__`` assignment, being a
# non-heap extension type; ``sage.rings.ring.Ring`` refuses ``__init__``
# assignment, so no construction hook exists; and patching
# ``Rings.ParentMethods`` in place does nothing, because ``parent_class`` is
# already built and clearing those caches breaks Sage outright.
#
# REMEDIATION.  The owned scalar hierarchy carries ``__pow__`` once, on its
# ``Rings`` node, and rings are refined into it.  Placement is the whole
# subtlety: a node whose only parent is ``Rings()`` loses ZZ's linearization
# to ``EuclideanDomains``, which inherits Sage's own ``__pow__``, so the owned
# node has to sit deep enough to outrank it.  Refinement on intake covers the
# rings a session builds later, which no hook on Sage's classes could.
# ---------------------------------------------------------------------------

# The session's names, not the engine's: these are the rings a notebook types,
# bound by ``Lattices.install`` above.  ``SageIntegers`` is the same ring read
# behind the boundary, and ``SageIntegers^3`` is Sage's own free module -- so
# naming the engine's ring here would ask the question this section exists to
# distinguish itself from.
RINGS = {
    "ZZ": ZZ,
    "QQ": QQ,
    "GF(5)": GF(5),
    "QQ[x]": QQ["x"],
    "ZZ[x,y]": ZZ["x", "y"],
    "Zmod(6)": Zmod(6),
}


@pytest.mark.parametrize("name", sorted(RINGS))
def test_a_ring_raised_to_a_rank_is_the_preamble_free_module(name: str) -> None:
    r"""\(R^n\) is the free \(R\)-module of rank \(n\) in the preamble's universe.

    The rank is the invariant: whatever \(R^3\) builds, three module generators
    is what a rank-3 free module has.
    """
    ring = RINGS[name]
    module = ring^3
    assert module.base_ring() is ring, f"{name}^3 is a module over {name}"
    assert module.number_of_module_generators() == 3, (
        f"{name}^3 is free of rank 3"
    )


# ---------------------------------------------------------------------------
# Discriminant and torsion forms: the literature corpus, on the owned surface.
#
# Sources (Zotero item | Better-BibTeX key):
#   - V. V. Nikulin, *Integral symmetric bilinear forms and some of their
#     applications* (1980).  Nik80; Zotero TTY9FFJS, attachment D7BP5F7Z.
#   - R. Miranda & D. R. Morrison, *Embeddings of integral quadratic forms*
#     (2009).  MM09; Zotero ACX7WF7L.
#   - Conway & Sloane, *Sphere Packings, Lattices and Groups*, 3rd ed.  CS10;
#     Zotero T2WVLTDB, attachment TCJKXU3D.
#
# Every lattice here is constructed from an explicit Gram matrix or the
# positive-definite named constructor, so no sign convention is imported from
# the catalogue; assertions the sources state only up to a sign convention
# are written in convention-independent form.
# ---------------------------------------------------------------------------


def _subobject_images(subobject) -> frozenset:
    r"""The subobject's elements seen in the ambient discriminant form."""
    embedding = subobject.embedding()
    return frozenset(embedding(element) for element in subobject)


def test_rank_one_sign_pair_separates_quadratic_from_bilinear_isometry() -> None:
    r"""$\langle2\rangle$ and $\langle-2\rangle$ share $b$ but not $q$.

    Nik80 (TTY9FFJS) Prop 1.8.2 gives the bilinear isomorphism; Thm 1.11.3
    separates the quadratic forms by their signatures mod 8.  MM09 (ACX7WF7L)
    Thm 5.1 defines the Brown invariant as the argument of the normalized
    Gauss sum, so the values 1 and 7 are finite-form facts.
    """
    plus = IntegralLattice(matrix(ZZ, [[2]])).discriminant_group()
    minus = IntegralLattice(matrix(ZZ, [[-2]])).discriminant_group()
    assert plus.invariants() == (2,) and minus.invariants() == (2,)
    assert plus.associated_bilinear_form().is_isomorphic(
        minus.associated_bilinear_form()
    ), "Nik80 Prop 1.8.2: the bilinear discriminant forms are isomorphic"
    assert not plus.is_isomorphic(minus), (
        "Nik80 Thm 1.11.3: the quadratic forms differ, their signatures "
        "disagree mod 8"
    )
    assert (plus.brown_invariant(), minus.brown_invariant()) == (1, 7), (
        "MM09 Thm 5.1: Br is the Gauss-sum argument of the finite form"
    )


def test_the_level_of_an_even_lattice_exceeds_the_exponent_of_its_discriminant_group() -> None:
    r"""$\langle2\rangle$ has level $4$ while $A_L=\mathbb Z/2$ has exponent $2$.

    The level is the smallest $N$ killing the form on $A_L$.  For an even
    lattice that form is $q$, valued in $\mathbb Q/2\mathbb Z$ rather than
    $\mathbb Q/\mathbb Z$ (Nik80, Zotero TTY9FFJS, section 1.3 -- the repo's
    established citation, stated in ``lattice_axioms.sage``), and the extra
    factor of two is exactly what separates the level from the exponent.

    Sage offers neither quantity under this name: its genus symbol's ``level``
    is "the denominator of the inverse Gram matrix of a representative"
    (``sage.quadratic_forms.genera.genus``), which is the *exponent*, and
    ``QuadraticForm.level`` normalizes against the Hessian $2G$ instead.  The
    separation below is what makes the owned ``level`` a different method and
    not an alias, so it is asserted on the specimen that distinguishes them.
    """
    even = IntegralLattice(matrix(ZZ, [[2]]))
    assert even.is_even()
    exponent = even.discriminant_group().annihilator().gen()
    assert exponent == 2, "A_L = ZZ/2 for <2>"
    assert even.level() == 4, (
        "q(g) = 1/2 in QQ/2ZZ, so N q = 0 needs N = 4 -- not the exponent 2"
    )
    assert even.level() != exponent, (
        "the even level is not the exponent of the discriminant group"
    )

    odd = IntegralLattice(matrix(ZZ, [[3]]))
    assert not odd.is_even()
    assert odd.level() == odd.discriminant_group().annihilator().gen() == 3, (
        "an odd lattice has only b, valued in QQ/ZZ, so level = exponent"
    )

    assert IntegralLattice("E8").level() == 1, "A_L is trivial for E8"


def test_elementary_2adic_form_u_k_has_brown_invariant_zero() -> None:
    r"""$\operatorname{Br}(u_k)=0$ and $u_k$ is isotropic.

    MM09 (ACX7WF7L) defines $U_k$ by the Gram matrix $((0,2^k),(2^k,0))$;
    Prop 2.7 gives $\gamma_{u_k}(1)=1$, so $\operatorname{Br}(u_k)=0$ by
    Thm 5.1, and (7.7.1) exhibits a nonzero isotropic vector.
    """
    for k in (1, 2, 3):
        form = IntegralLattice(
            matrix(ZZ, 2, [0, 2**k, 2**k, 0])
        ).discriminant_group()
        assert tuple(form.invariants()) == (2**k, 2**k)
        assert form.brown_invariant() == 0, "MM09 Prop 2.7 with Thm 5.1"
        assert not form.is_anisotropic(), "MM09 (7.7.1)"


def test_elementary_2adic_form_v_1_has_brown_invariant_four_and_is_anisotropic() -> None:
    r"""$\operatorname{Br}(v_1)=4$ and $v_1$ is anisotropic.

    $v_1=q_{D_4}$; MM09 (ACX7WF7L) Prop 2.7 gives $\gamma_{v_k}(1)=(-1)^k$,
    so $\operatorname{Br}(v_1)=4$ by Thm 5.1, and (7.7.2) shows $V_k$ has no
    nonzero isotropic vector.
    """
    form = IntegralLattice("D4").discriminant_group()
    assert tuple(form.invariants()) == (2, 2)
    assert form.brown_invariant() == 4, "MM09 Prop 2.7 with Thm 5.1"
    assert form.is_anisotropic(), "MM09 (7.7.2)"


def test_brown_invariant_is_additive_over_the_primary_splitting() -> None:
    r"""$q=\bigoplus_p q_p$ and $\operatorname{Br}$ adds over the parts.

    Nik80 (TTY9FFJS) Prop 1.2.2: the finite form splits orthogonally over
    the $p$-primary parts of $A$.  The Brown invariant is the Gauss-sum
    argument (MM09 Thm 5.1), and a Gauss sum of an orthogonal sum factors,
    so the invariant adds.  $A_5$ has $A_L=\mathbb Z/6$, a genuinely
    non-prime-power group.
    """
    form = IntegralLattice("A5").discriminant_group()
    assert tuple(form.invariants()) == (6,)
    two_part = form.primary_part(2)
    three_part = form.primary_part(3)
    assert (two_part.cardinality(), three_part.cardinality()) == (2, 3), (
        "Nik80 Prop 1.2.2: the primary parts realize the factorization of 6"
    )
    assert form.brown_invariant() == (
        two_part.brown_invariant() + three_part.brown_invariant()
    ), "Br is additive over the primary splitting"


def test_milgram_identifies_brown_with_the_signature_mod_eight() -> None:
    r"""$\operatorname{Br}(q_L)\equiv\operatorname{sign}(L)\pmod 8$.

    Milgram's theorem, Nik80 (TTY9FFJS) Thm 1.3.3 -- a theorem about even
    lattices, checked as one, never the definition of $\operatorname{Br}$.
    """
    for lattice in (
        IntegralLattice("A5"),
        IntegralLattice("D4"),
        IntegralLattice(matrix(ZZ, 2, [0, 2, 2, 0])),
        IntegralLattice(matrix(ZZ, [[-2]])),
    ):
        positive, negative = lattice.signature_pair()
        assert lattice.discriminant_group().brown_invariant() == (
            positive - negative
        ), "Nik80 Thm 1.3.3 (Milgram)"


def test_lagrangian_glue_of_the_rank_one_sign_pair_is_unimodular() -> None:
    r"""The diagonal class of $\langle2\rangle\oplus\langle-2\rangle$ glues to a unimodular lattice.

    Nik80 (TTY9FFJS) Prop 1.4.1: isotropic subgroups of $A_L$ correspond to
    even overlattices, with the new discriminant form $S^{\perp}/S$; a
    lagrangian $S$ gives a unimodular overlattice.  The diagonal element has
    $q=1/2+3/2=0$ in $\mathbb Q/2\mathbb Z$.
    """
    lattice = IntegralLattice(matrix(ZZ, [[2]])) + IntegralLattice(
        matrix(ZZ, [[-2]])
    )
    form = lattice.discriminant_group()
    assert tuple(form.invariants()) == (2, 2)
    first, second = tuple(form.module_generators())
    diagonal = first + second
    assert diagonal.q() == 0, "the diagonal class is isotropic"
    subgroup = form.subobject_generated_by((diagonal,))
    assert any(
        _subobject_images(lagrangian) == _subobject_images(subgroup)
        for lagrangian in form.lagrangian_subobjects()
    ), "the diagonal subgroup equals its own perpendicular"
    assert form.orthogonal_quotient(subgroup).cardinality() == 1, (
        "Nik80 Prop 1.4.1: the glued discriminant form is S-perp/S, trivial "
        "for a lagrangian"
    )
    inclusion = form.overlattice_from_isotropic_subobject(subgroup)
    assert inclusion.index() == 2, (
        "an isotropic class of order 2 glues with index 2 -- asserted on the "
        "inclusion arrow"
    )
    glued = inclusion.codomain()
    assert glued.is_even() and glued.is_unimodular(), "Nik80 Prop 1.4.1"


def test_d8_isotropic_self_glue_reconstructs_e8() -> None:
    r"""$D_8^{+}=E_8$: the isotropic $D_8$ glue class gives $E_8$.

    CS10 (T2WVLTDB) Ch. 4 lists $D_8^{+}$ as the even unimodular lattice
    obtained by adjoining isotropic glue, with 240 roots; Nik80 (TTY9FFJS)
    Prop 1.4.1 is the correspondence the construction runs through.  The
    index is asserted on the inclusion arrow.
    """
    d8 = IntegralLattice("D8")
    inclusion = d8.maximal_overlattice()
    assert inclusion.index() == 2, "[E8 : D8] = 2"
    glued = inclusion.codomain()
    assert glued.is_even() and glued.is_unimodular()
    assert glued.enumerate_short_vectors(2).cardinality() == 120, (
        "CS10 ch. 4: E8 has 240 roots, counted modulo sign"
    )
    assert glued.is_isometric(IntegralLattice("E8"))


def test_a2_discriminant_form_is_anisotropic_and_not_metabolic() -> None:
    r"""$q_{A_2}$ on $\mathbb Z/3$ has no nonzero isotropic element.

    CS10 (T2WVLTDB) Ch. 4 lists the $A_2$ glue group as cyclic of order
    three; with Nik80's (TTY9FFJS) definitions the form is anisotropic, so
    it has no lagrangian and $A_2$ admits no proper even overlattice.
    """
    form = IntegralLattice("A2").discriminant_group()
    assert tuple(form.invariants()) == (3,)
    assert form.is_anisotropic()
    assert not form.is_metabolic()
    assert list(form.lagrangian_subobjects()) == []


def test_form_negation_via_twist_matches_the_negation_rules() -> None:
    r"""$-q_L=q_{L(-1)}$, and the negation rules classify $q\cong-q$.

    MM09 (ACX7WF7L) lists the negation rules for the elementary forms:
    $-u_k\cong u_k$, $-v_k\cong v_k$, but $-w^{\epsilon}_{p,k}\cong
    w^{-\epsilon}_{p,k}$.  So $v_1=q_{D_4}$ is self-negative while
    $q_{E_7}=w^{\epsilon}_{2,1}$ is not; the Brown invariants of $q_{E_7}$
    and $-q_{E_7}$ are distinct and opposite mod 8 (Nik80 Thm 1.11.3).
    """
    d4 = IntegralLattice("D4")
    form = d4.discriminant_group()
    assert form.twist(-1).is_isomorphic(
        d4.twist(-1).discriminant_group()
    ), "negating the lattice negates its discriminant form"
    assert form.is_isomorphic(form.twist(-1)), "MM09: -v_1 is v_1"

    e7_form = IntegralLattice("E7").discriminant_group()
    negated = e7_form.twist(-1)
    assert not e7_form.is_isomorphic(negated), "MM09: -w is w^{-eps}, not w"
    assert e7_form.brown_invariant() + negated.brown_invariant() == 0, (
        "negation negates the Gauss-sum argument"
    )
    assert e7_form.brown_invariant() != negated.brown_invariant()


def test_quadratic_isomorphism_refines_bilinear_refines_group() -> None:
    r"""$u_1$ and $v_1$ share group and bilinear form, not $q$.

    Nik80 (TTY9FFJS) Prop 1.8.2: the bilinear forms of $u_1$ and $v_1$ are
    isomorphic; Thm 1.11.3 separates the quadratic forms by signature mod 8,
    and MM09 (ACX7WF7L) (7.7.3) separates them by discriminant characters.
    Each category answers its own isomorphism question; the refinement is
    this theorem, not an API flag.
    """
    u1 = IntegralLattice(matrix(ZZ, 2, [0, 2, 2, 0])).discriminant_group()
    v1 = IntegralLattice("D4").discriminant_group()
    assert tuple(u1.invariants()) == tuple(v1.invariants()) == (2, 2), (
        "one group underlies both forms"
    )
    assert u1.associated_bilinear_form().is_isomorphic(
        v1.associated_bilinear_form()
    ), "Nik80 Prop 1.8.2"
    assert not u1.is_isomorphic(v1), "MM09 (7.7.3); Br 0 vs 4"
    assert (u1.brown_invariant(), v1.brown_invariant()) == (0, 4)


def test_rank_one_2adic_form_separates_the_two_orthogonal_groups() -> None:
    r"""On $A_{\langle8\rangle}=\mathbb Z/8$, $O(b)$ has order 4 and $O(q)$ order 2.

    MM09 (ACX7WF7L): every unit $u$ with $u^2\equiv1\pmod 8$ preserves the
    bilinear pairing, while preserving the quadratic refinement narrows the
    action to $u=\pm1$.  Each category answers with its own automorphism
    group (FOUNDATIONS Def 26.2), and the two orders separate them.
    """
    lattice = IntegralLattice(matrix(ZZ, [[8]]))
    form = lattice.discriminant_group()
    assert tuple(form.invariants()) == (8,)
    assert form.brown_invariant() == 1, "Milgram cross-check: sign (1,0)"
    assert form.automorphism_group().order() == 2
    assert form.associated_bilinear_form().automorphism_group().order() == 4


# ---------------------------------------------------------------------------
# Reduction and closest-vector geometry (CS10 ch. 21, "Voronoi Cells of
# Lattices and Quantization Errors"; covolume in ch. 2).


def test_voronoi_cell_of_the_square_lattice_is_the_half_cube() -> None:
    r"""CS10 ch. 21: the Voronoi cell of $\mathbb Z^n$ is the cube
    $[-1/2,1/2]^n$; its volume is the covolume $\sqrt{\det G}=1$."""
    square = Lattices.Z**2
    cell = square.voronoi_cell()
    assert cell.volume() == 1
    assert sorted(tuple(v) for v in cell.vertices()) == sorted(
        (SageRationals(a) / 2, SageRationals(b) / 2)
        for a in (-1, 1)
        for b in (-1, 1)
    )


def test_voronoi_relevant_vectors_of_the_square_lattice_are_the_facet_normals() -> None:
    r"""CS10 ch. 21: the relevant vectors of $\mathbb Z^n$ are $\pm e_i$ --
    one per facet of the cube, $2n$ in all."""
    square = Lattices.Z**2
    e1, e2 = square.module_generators()
    assert set(square.voronoi_relevant_vectors()) == {e1, -e1, e2, -e2}


def test_hexagonal_lattice_voronoi_cell_is_a_hexagon() -> None:
    r"""CS10 ch. 21: the Voronoi cell of the $A_2$ lattice is a regular
    hexagon -- six facets, one per relevant vector (the six minimal
    vectors).  $A_2$ is negative definite here; the cell reads lengths
    through $-G$."""
    hexagonal = Lattices.A2
    assert hexagonal.voronoi_cell().n_facets() == 6
    assert hexagonal.voronoi_relevant_vectors().cardinality() == 6


def test_closest_vector_is_exact_on_the_square_lattice() -> None:
    r"""CS10 ch. 21 (Zotero T2WVLTDB): the closest-vector problem on
    $\mathbb Z^n$ is solved by rounding each coordinate.  Here the vector
    nearest $(3/4, 1/4)$ is $(1, 0)$ -- squared distance $1/8$ against
    $5/8$ for the origin."""
    square = Lattices.Z**2
    e1, e2 = square.module_generators()
    assert square.closest_vector((SageRationals(3) / 4, SageRationals(1) / 4)) == e1


# ---------------------------------------------------------------------------
# Orthogonal complements, gluing, and the genus -- absorbed from the spike's
# literature suite (Nik80, Zotero TTY9FFJS; CS10, Zotero T2WVLTDB).


def _first_adjacent_pair(lattice: "Parent") -> tuple:
    r"""Return two framing generators pairing nontrivially (an $A_2$ span)."""
    generators = tuple(lattice.module_generators())
    for i, left in enumerate(generators):
        for right in generators[i + 1 :]:
            if left.b(right) != 0:
                return (left, right)
    assert False, "no adjacent pair: the Gram matrix is diagonal"


def test_the_orthogonal_complement_of_a_root_in_e8_is_e7() -> None:
    r"""Nik80 Prop 1.4.1 / CS10 ch. 4: the orthogonal complement of a
    primitively embedded $A_1$ in $E_8$ is $E_7$ -- rank 7, determinant 2,
    126 roots -- and the glue groups of the complement pair have equal
    order (CS10 ch. 4 Thm 1)."""
    e8 = Lattices.E8
    a1 = e8.subobject_on([e8.module_generators()[0]])
    complement = a1.embedding().orthogonal_complement()
    assert complement.rank() == 7
    assert abs(matrix(ZZ, complement.gram_matrix()).det()) == 2
    assert a1.is_primitive(), "a framing generator spans a primitive A1"
    assert complement.is_primitive(), "an orthogonal complement is primitive"
    assert complement.discriminant_group().invariants() == (2,), (
        "det S = det K for a primitive complement pair in a unimodular "
        "lattice (CS10 ch. 4 Thm 1)"
    )
    assert complement.twist(-1).enumerate_short_vectors(2).cardinality() == 63, (
        "E7 has 126 roots, 63 modulo sign (CS10 ch. 4)"
    )


def test_the_orthogonal_complement_of_a2_in_e8_is_e6() -> None:
    r"""Nik80 Prop 1.4.1 / CS10 ch. 4: the orthogonal complement of a
    primitively embedded $A_2$ in $E_8$ is $E_6$ -- rank 6, determinant 3,
    72 roots."""
    e8 = Lattices.E8
    a2 = e8.subobject_on(list(_first_adjacent_pair(e8)))
    complement = a2.embedding().orthogonal_complement()
    assert complement.rank() == 6
    assert abs(matrix(ZZ, complement.gram_matrix()).det()) == 3
    assert complement.twist(-1).enumerate_short_vectors(2).cardinality() == 36, (
        "E6 has 72 roots, 36 modulo sign (CS10 ch. 4)"
    )


def test_a2_plus_its_negation_glues_to_an_even_unimodular_lattice_of_index_3() -> None:
    r"""Nik80 Prop 1.4.1: even overlattices correspond to isotropic
    subgroups of $A_L$, with $[L':L]^2=|A_L|/|A_{L'}|$.  $A_2\oplus A_2(-1)$
    has $A_L\cong(\mathbb Z/3)^2$ containing an isotropic diagonal, so it
    reaches an even unimodular overlattice of index 3."""
    doubled = Lattices.A2 + Lattices.A2.twist(-1)
    inclusion = doubled.maximal_overlattice()
    assert inclusion.index() == 3
    assert inclusion.codomain().is_even()
    assert inclusion.codomain().is_unimodular()


def test_milgram_on_the_a2_discriminant_form() -> None:
    r"""Nik80 Thm 1.3.3 (Milgram): $\operatorname{Br}(q_L)\equiv
    \operatorname{sign}(L)\pmod 8$.  The AG $A_2$ is negative definite with
    signature $(0,2)$, so $\operatorname{Br}(q_{A_2}) = 6$."""
    assert Lattices.A2.discriminant_group().brown_invariant() == 6


def test_the_genus_of_a2_holds_its_defining_data_and_one_class() -> None:
    r"""Nik80 Cor 1.9.4: the genus of an even lattice is the pair
    (signature, discriminant quadratic form); CS10 ch. 15: the class number
    of the $A_2$ genus is 1, so its representative shares the genus."""
    genus = Lattices.A2.genus()
    assert genus.signature_pair() == (0, 2)
    assert genus.determinant() == 3
    assert genus.class_number() == 1
    assert genus.representative().genus() == genus


def test_is_isometric_decides_the_definite_case_by_the_engine() -> None:
    r"""CS10 ch. 15 (Zotero T2WVLTDB): equivalence of definite forms is
    decidable by reduction.  $[[-2,-1],[-1,-2]]$ is $A_2$ in a reflected
    framing ($e_2\mapsto -e_2$), and a sign twist changes the signature."""
    reflected = IntegralLattice(matrix(ZZ, [[-2, -1], [-1, -2]]))
    assert Lattices.A2.is_isometric(reflected) is True
    assert Lattices.A2.is_isometric(Lattices.A2.twist(-1)) is False


def test_the_reflection_in_a_root_of_a2_acts_by_the_definition() -> None:
    r"""Hum90 sec 1.1: $s_v(x)=x-\dfrac{2b(x,v)}{q(v)}v$.  On the $A_2$
    framing, $s_{e_1}(e_1)=-e_1$ and $s_{e_1}(e_2)=e_1+e_2$."""
    lattice = IntegralLattice("A2")
    e1, e2 = lattice.module_generators()
    reflection = lattice.reflection(e1)
    assert reflection(e1) == -e1
    assert reflection(e2) == e1 + e2


def test_nikulin_complement_pair_discriminant_forms_are_anti_isometric() -> None:
    r"""Nik80 Cor 1.6.2 (Zotero TTY9FFJS): the discriminant quadratic forms
    of a primitive complement pair in an even unimodular lattice are
    anti-isometric, $q_K \cong -q_S$.  In $E_8$: a framing root spans a
    primitive $A_1$ with complement $E_7$, and an adjacent pair spans a
    primitive $A_2$ with complement $E_6$ (CS10 ch. 4)."""
    e8 = Lattices.E8
    a1 = e8.subobject_on([e8.module_generators()[0]])
    e7 = a1.embedding().orthogonal_complement()
    assert e7.discriminant_group().is_anti_isometric(a1.discriminant_group())

    a2 = e8.subobject_on(list(_first_adjacent_pair(e8)))
    e6 = a2.embedding().orthogonal_complement()
    assert e6.discriminant_group().is_anti_isometric(a2.discriminant_group())


def test_an_anti_isometry_needs_the_sign_a2_versus_its_twist() -> None:
    r"""Nik80 sec 1.3 (Zotero TTY9FFJS): $q_{A_2}$ takes the value $-2/3$
    and $-q_{A_2}$ the value $2/3$ in $\mathbb Q/2\mathbb Z$, so the AG
    $A_2$ discriminant form is anti-isometric to the form of the
    positive-definite $A_2$ and NOT anti-isometric to itself."""
    negative = Lattices.A2.discriminant_group()
    positive = Lattices.A2.twist(-1).discriminant_group()
    assert negative.is_anti_isometric(positive)
    assert not negative.is_anti_isometric(negative)


# ---------------------------------------------------------------------------
# Genus versus class: the SPLAG split-spinor-genus specimen (CS10, Zotero
# T2WVLTDB, attachment TCJKXU3D).  Chapter 15 section 11 gives the ternary
# forms (51a) and (51b) of determinant -128; chapter 15 Theorem 14 (Eichler)
# makes class = spinor genus for indefinite forms of rank >= 3.


def test_splag_forms_51a_and_51b_share_a_genus_but_not_a_class() -> None:
    r"""CS10 ch. 15 sec. 11: one genus, two spinor genera, two classes.

    The forms (51a) and (51b) of determinant $-128$ lie in a single genus
    that splits into two spinor genera.  By Theorem 14 the class of an
    indefinite ternary form is its spinor genus, so the genus contains
    exactly two classes and the two forms are not isometric.
    """
    a = IntegralLattice(matrix(ZZ, 3, 3, [-1, 1, 0, 1, 63, 0, 0, 0, 2]))
    b = IntegralLattice(matrix(ZZ, 3, 3, [-9, 1, 0, 1, 7, 0, 0, 0, 2]))

    assert matrix(ZZ, a.gram_matrix()).det() == -128, "CS10 ch. 15 sec. 11"
    assert matrix(ZZ, b.gram_matrix()).det() == -128, "CS10 ch. 15 sec. 11"
    assert a.genus() == b.genus(), "(51a) and (51b) lie in one genus"
    assert a.genus().class_number() == 2, (
        "the genus splits into two spinor genera, hence two classes "
        "(CS10 ch. 15 sec. 11 with Theorem 14)"
    )
    # The forms are indefinite ternary, so the owned decision procedure
    # cannot PLACE a form into its spinor genus and answers the three-valued
    # Unknown for this split genus; the mathematical content -- one genus,
    # two classes -- is carried by the genus and class-number assertions
    # above, so no vacuous non-True assertion is kept here.


# ---------------------------------------------------------------------------
# The p-adic invariants of the genus against Conway-Sloane's own existence
# formulae (CS10, Zotero T2WVLTDB, ch. 15): an INDEPENDENT oracle, derived
# from the cited formulae and pinned against the engine's local data, so the
# agreement is never the engine checked against itself.
# ---------------------------------------------------------------------------


def _cs99_local_excess(tuples: tuple, p: int) -> int:
    r"""The p-excess ($p\ge3$) / oddity ($p=2$) from the canonical Jordan
    symbol, via the Conway--Sloane existence formulae [CS10 ch. 15 sec 7.7]:

        p-excess = sum_q n_q (q - 1) + 4 k_p   (mod 8)   for p >= 3,
        oddity   = sum_q t_q         + 4 k_2   (mod 8)   for p  = 2,

    where a canonical constituent tuple is ``(v, n, eps)`` at odd $p$ and
    ``(v, n, eps, type, t)`` at $p=2$, the scale is $q=p^v$ [sec 7.1], and
    $k_p$ counts the p-adic *antisquare* constituents [sec 5.1]: those with
    $q$ not a square ($v$ odd) and sign $\varepsilon=-1$.
    """
    running_total = 0
    antisquares = 0
    for constituent in tuples:
        valuation, dimension, sign = (
            constituent[0], constituent[1], constituent[2],
        )
        scale = p ** valuation                    # q, the Jordan scale (7.1)
        if valuation % 2 == 1 and sign == -1:     # antisquare (5.1)
            antisquares += 1
        if p == 2:
            running_total += constituent[4]       # oddity marker t_q (7.4)
        else:
            running_total += dimension * (scale - 1)   # n_q (q - 1) (7.7)
    return (running_total + 4 * antisquares) % 8


def test_local_excess_matches_the_conway_sloane_existence_formula() -> None:
    r"""CS10 ch. 15 sec 7.7: the p-excess / oddity of each local genus
    symbol, re-derived from the canonical Jordan constituent tuples by the
    cited formula and matched against the engine's local excess.  The
    positive-definite root-lattice rows carry the values the source's
    tables reproduce (E8 unimodular: trivial symbols everywhere)."""
    rows = (
        (Lattices.A1.twist(-1), 2, 1),
        (Lattices.D4.twist(-1), 2, 4),
        (Lattices.E7.twist(-1), 2, 7),
        (Lattices.E8.twist(-1), 2, 0),
        (Lattices.A2.twist(-1), 3, 6),
        (Lattices.E6.twist(-1), 3, 2),
        (Lattices.E8.twist(-1), 5, 0),
        (Lattices.U, 2, 0),
        (Lattices.U + IntegralLattice(matrix(ZZ, [[2]])), 2, 1),
    )
    for lattice, p, expected in rows:
        genus = lattice.genus()
        tuples = tuple(
            tuple(int(entry) for entry in constituent)
            for constituent in genus.local_symbol(p).canonical_symbol()
        )
        assert _cs99_local_excess(tuples, p) == expected, (lattice, p)
        assert genus.excess(p) % 8 == expected, (lattice, p)


def test_a_genus_datum_exists_exactly_when_nikulin_admits_it() -> None:
    r"""Nik80 (Zotero TTY9FFJS) Thm 1.10.1: existence of an even lattice
    with signature $(t_+,t_-)$ and discriminant form $q$; Thm 1.3.3*
    (Gauss--Milgram) gives the necessary congruence
    $t_+-t_-\equiv\operatorname{Br}(q)\pmod 8$.  For $q_{A_2}$ (the AG
    negative-definite $A_2$; $\operatorname{Br}=6$, see the Milgram row)
    the congruence is also sufficient at these signatures, each admissible
    one witnessed by an actual lattice: $(0,2)$ by $A_2$, $(1,3)$ by
    $A_2\oplus U$, $(2,4)$ by $A_2\oplus U^2$."""
    from dzack_research.preamble.categories.modules.framed.formed.integrallattice.integral_lattices import (
        Genus as LatticeGenus,
    )

    q = Lattices.A2.discriminant_group()
    brown = q.brown_invariant()
    assert brown == 6
    existence = {
        (0, 2): True,
        (2, 0): False,
        (1, 3): True,
        (3, 1): False,
        (2, 4): True,
        (0, 6): False,
    }
    for signature, expected in existence.items():
        assert LatticeGenus(signature, q).exists() == expected, signature
        congruent = (signature[0] - signature[1]) % 8 == brown % 8
        assert congruent == expected, signature

    # Nik80 Thm 1.10.1, the reconstruction half: the genus datum built from
    # (signature, q_L) IS the genus of a lattice carrying that data ($U$ is
    # unimodular, so adding it leaves the discriminant form unchanged).
    assert LatticeGenus((1, 3), q) == (Lattices.A2 + Lattices.U).genus()
    assert LatticeGenus((2, 4), q) == (
        Lattices.A2 + Lattices.U + Lattices.U
    ).genus()


# ---------------------------------------------------------------------------
# Gluing and discriminant actions (CS10, Zotero T2WVLTDB, ch. 4): glue
# groups of the root lattices, the induced action of O(L) on them, and the
# glue construction reaching E8.
# ---------------------------------------------------------------------------


def test_a4_isometries_act_on_the_cyclic_glue_group_by_negation() -> None:
    r"""CS10 ch. 4 sec 6.1: $A_n$ has cyclic glue group $C_{n+1}$ and the
    order-two diagram automorphism sends $[i]$ to $[n+1-i]$ -- negation.
    For $A_4$: $|O(A_4)| = 2\cdot5! = 240$, the image of
    $\rho:O(A_4)\to O(q_{A_4})$ has order two, and the orbits on $C_5$ are
    $\{0\}$, $\{\pm[1]\}$, $\{\pm[2]\}$."""
    lattice = Lattices.A4
    isometries = lattice.Aut()
    assert isometries.cardinality() == 240
    image = isometries.discriminant_image()
    assert image.cardinality() == 2
    form = lattice.discriminant_group()
    assert tuple(form.invariants()) == (5,)
    generator = tuple(form.module_generators())[0]
    assert form.orbit(generator, group=image) == frozenset(
        (generator, -generator)
    )
    assert sorted(
        len(orbit) for orbit in form.orbits(group=image)
    ) == [1, 2, 2]


def test_d4_weyl_group_fixes_the_glue_while_triality_permutes_it() -> None:
    r"""CS10 ch. 4 secs 7.1-7.2: $D_4$ has glue group $V_4$, Weyl subgroup
    of order $2^3\cdot4! = 192$ acting trivially on the glue, full
    $|O(D_4)| = 192\cdot3! = 1152$ with the order-six symmetric group
    acting on the three nonzero glue cosets -- so the subgroup orbits are
    the trivial subgroup, the three order-two subgroups in one orbit, and
    the full glue group, while the only isotropic subgroup is trivial."""
    lattice = Lattices.D4
    isometries = lattice.Aut()
    reflections = tuple(
        lattice.reflection(root) for root in lattice.module_generators()
    )
    weyl = isometries.subgroup_on(reflections)
    assert weyl.cardinality() == 192
    assert isometries.cardinality() == 1152
    assert weyl.discriminant_image().cardinality() == 1
    triality_image = isometries.discriminant_image()
    assert triality_image.cardinality() == 6
    form = lattice.discriminant_group()
    assert form.automorphism_group().cardinality() == 6
    zero = form.zero()
    nonzero = frozenset(
        element for element in form if element != zero
    )
    generator = tuple(form.module_generators())[0]
    assert form.orbit(generator, group=triality_image) == nonzero
    assert sorted(
        len(orbit)
        for orbit in form.orbits_on_subobjects(group=triality_image)
    ) == [1, 1, 3]
    isotropic_orbits = form.orbits_on_isotropic_subobjects(
        group=triality_image
    )
    assert len(isotropic_orbits) == 1
    assert len(isotropic_orbits[0]) == 1


def test_a4_a4_order_five_glue_reconstructs_e8() -> None:
    r"""CS10 ch. 4: glue vectors live in $L^\vee/L$ (sec 3), $A_4$ has glue
    group $C_5$ (sec 6.1), and the order-five isotropic glue between two
    $A_4$ components reaches the even unimodular rank-eight lattice with
    the 240 roots of $E_8$ (sec 8.1).  The index is asserted on the
    inclusion arrow."""
    doubled = Lattices.A4 + Lattices.A4
    form = doubled.discriminant_group()
    assert tuple(form.invariants()) == (5, 5)
    first, second = tuple(form.module_generators())
    glue_class = first + 2 * second
    assert glue_class.q() == 0, "the [1,2] glue class is isotropic"
    subgroup = form.subobject_generated_by((glue_class,))
    assert form.orthogonal_quotient(subgroup).cardinality() == 1
    inclusion = form.overlattice_from_isotropic_subobject(subgroup)
    assert inclusion.index() == 5, "[glued : A4 + A4] = |glue group|"
    glued = inclusion.codomain()
    assert glued.is_even() and glued.is_unimodular()
    assert glued.twist(-1).enumerate_short_vectors(2).cardinality() == 120, (
        "CS10 ch. 4 sec 8.1: E8 has 240 roots, counted modulo sign"
    )
    assert glued.is_isometric(Lattices.E8) is True


def test_a2_diagram_automorphism_inverts_the_glue_group() -> None:
    r"""CS10 ch. 4 sec 6.1: $A_n^\vee/A_n \cong C_{n+1}$ and the order-two
    diagram automorphism sends $[i]$ to $[n+1-i]$; for $A_2$ the induced
    action on $C_3$ is inversion."""
    lattice = Lattices.A2
    first, second = tuple(lattice.module_generators())
    swap = lattice.Aut()(
        dict(zip(lattice.module_generating_set(), (second, first)))
    )
    induced = swap.discriminant_morphism()
    form = lattice.discriminant_group()
    assert tuple(form.invariants()) == (3,)
    for element in form:
        assert induced(element) == -element


# ---------------------------------------------------------------------------
# K3 and Enriques lattice theory (Kondo, *K3 Surfaces*, Zotero F288JVXK;
# Nik80, Zotero TTY9FFJS; Dolgachev, *Enriques Surfaces II*, Zotero
# 7RZTF9AQ): the K3 lattice, polarizations and their transcendental
# complements, and the Enriques lattice as a unimodular summand.
# ---------------------------------------------------------------------------


def test_the_k3_lattice_is_the_unique_even_unimodular_lattice_of_its_signature() -> None:
    r"""Kon20 Thm 1.27: the indefinite even unimodular lattice of signature
    $(p,q)$ is unique, and $H^2(K3,\mathbb Z) = U^3\oplus E_8(-1)^2$ has
    rank 22 and signature $(3,19)$ [Cor 1.26: $3-19=-16$ is divisible by
    8].  Uniqueness is witnessed by the genus-level isometry of a genuinely
    regrouped block sum with $L_{K3}$."""
    k3 = Lattices.LK3
    assert k3.rank() == 22
    assert k3.signature_pair() == (3, 19)
    assert k3.is_even() and k3.is_unimodular()
    regrouped = (Lattices.U + Lattices.E8) + (
        Lattices.U + Lattices.E8
    ) + Lattices.U
    assert regrouped.is_isometric(k3) is True


def test_degree_two_polarization_splits_ns_and_transcendental_anti_isometrically() -> None:
    r"""Kon20 Def 6.4 and the period section: a degree-$2d$ polarized K3
    has $\mathrm{NS}\supseteq\mathbb ZH=\langle2d\rangle$ primitive in
    $L_{K3}$ with transcendental complement of signature $(2,19)$; Nik80
    Cor 1.6.2: the discriminant forms of the primitive complement pair are
    anti-isometric.  For $d=1$, $H = e+f$ in a hyperbolic plane and
    $H^\perp \cong U^2\oplus E_8(-1)^2\oplus\langle-2\rangle$."""
    k3 = Lattices.LK3
    plane_generators = tuple(k3.module_generators())
    h = plane_generators[0] + plane_generators[1]
    ns = k3.subobject_on([h])
    assert tuple(matrix(ZZ, ns.gram_matrix()).list()) == (2,)
    assert ns.is_primitive()
    transcendental = ns.embedding().orthogonal_complement()
    assert transcendental.rank() == 21
    assert transcendental.is_even()
    assert abs(matrix(ZZ, transcendental.gram_matrix()).det()) == 2
    assert tuple(
        transcendental.discriminant_group().invariants()
    ) == (2,)
    assert transcendental.discriminant_group().is_anti_isometric(
        ns.discriminant_group()
    )
    abstract = (
        Lattices.U + Lattices.U + Lattices.E8 + Lattices.E8
        + IntegralLattice(matrix(ZZ, [[-2]]))
    )
    assert abstract.signature_pair() == (2, 19)
    assert transcendental.is_isometric(abstract) is True


def test_degree_four_polarization_has_order_four_transcendental_discriminant() -> None:
    r"""Kon20 Def 6.4, period section; Nik80 Cor 1.6.2: for $d=2$ the class
    $H=2e+f$ has $H^2=4$, and $H^\perp$ carries a $\mathbb Z/4$
    discriminant form anti-isometric to $q_{\langle4\rangle}$ -- content
    the shared signature $(2,19)$ cannot see, separating the two
    polarization degrees."""
    k3 = Lattices.LK3
    plane_generators = tuple(k3.module_generators())
    h4 = 2 * plane_generators[0] + plane_generators[1]
    ns4 = k3.subobject_on([h4])
    assert tuple(matrix(ZZ, ns4.gram_matrix()).list()) == (4,)
    assert ns4.is_primitive()
    t4 = ns4.embedding().orthogonal_complement()
    assert t4.rank() == 21 and t4.is_even()
    assert tuple(t4.discriminant_group().invariants()) == (4,)
    assert t4.discriminant_group().is_anti_isometric(
        ns4.discriminant_group()
    )
    h2 = plane_generators[0] + plane_generators[1]
    t2 = k3.subobject_on([h2]).embedding().orthogonal_complement()
    assert not t4.discriminant_group().is_isomorphic(
        t2.discriminant_group()
    )


def test_a_root_class_in_the_k3_lattice_and_its_complement() -> None:
    r"""Nik80 Cor 1.6.2/1.6.3: the $(-2)$-class $r=e-f$ spans a primitive
    $A_1(-1)=\langle-2\rangle$ in $L_{K3}$; its orthogonal complement has
    signature $(3,18)$, determinant $\pm2$, and anti-isometric
    discriminant form on $\mathbb Z/2$."""
    k3 = Lattices.LK3
    plane_generators = tuple(k3.module_generators())
    root = k3.subobject_on([plane_generators[0] - plane_generators[1]])
    assert tuple(matrix(ZZ, root.gram_matrix()).list()) == (-2,)
    assert root.is_primitive()
    complement = root.embedding().orthogonal_complement()
    assert complement.rank() == 21
    assert complement.is_even()
    assert abs(matrix(ZZ, complement.gram_matrix()).det()) == 2
    assert tuple(complement.discriminant_group().invariants()) == (2,)
    assert complement.discriminant_group().is_anti_isometric(
        root.discriminant_group()
    )


def test_the_enriques_lattice_is_a_unimodular_summand_of_the_k3_lattice() -> None:
    r"""Kon20 Cor 1.26 / Thm 1.27 and introduction; Dol24 sec 1.5/9.2: the
    Enriques lattice $E_{10}=U\oplus E_8(-1)$ is the even unimodular
    lattice of signature $(1,9)$, and $L_{K3}\cong E_{10}\oplus
    (U^2\oplus E_8(-1))$ -- the unimodular instance of Nik80 Cor 1.6.2,
    both discriminant forms trivial."""
    e10 = Lattices.E10
    assert e10.rank() == 10
    assert e10.signature_pair() == (1, 9)
    assert e10.is_even() and e10.is_unimodular()
    rest = Lattices.U + Lattices.U + Lattices.E8
    assert rest.signature_pair() == (2, 10)
    assert rest.is_even() and rest.is_unimodular()
    assert tuple(e10.discriminant_group().invariants()) == ()
    assert tuple(rest.discriminant_group().invariants()) == ()
    assert (e10 + rest).is_isometric(Lattices.LK3) is True


def test_dickson_ross_ternary_forms_are_isometric_with_the_splag_witness() -> None:
    r"""CS10 ch. 15 sec 11: the Dickson--Ross indefinite ternary forms lie
    in a one-class genus, and the displayed unimodular transform carries
    the first Gram matrix to the second; the owned isometry decision
    (Eichler, single spinor genus) confirms the class equality."""
    first_gram = matrix(ZZ, [[3, 1, 0], [1, 23, 0], [0, 0, -1]])
    second_gram = matrix(ZZ, [[7, 3, 0], [3, 11, 0], [0, 0, -1]])
    witness = matrix(ZZ, [[-3, 2, 10], [-2, 3, 14], [-1, 1, 5]])
    assert witness.det() == -1
    assert witness * first_gram * witness.transpose() == second_gram
    first = IntegralLattice(first_gram)
    second = IntegralLattice(second_gram)
    assert first.signature_pair() == second.signature_pair() == (2, 1)
    assert first.is_isometric(second) is True


def test_a_similarity_is_an_isometry_from_the_twist() -> None:
    r"""Definitional: a similarity of scale $a$ multiplies the form by $a$,
    so it IS an isometry $L(a)\to M$.  The identity assignment is a
    similarity of scale $-1$ from the AG $A_2$ onto the positive-definite
    $A_2$, and the predicate reads the same composition."""
    positive = Lattices.A2.twist(-1)
    assert Lattices.A2.is_similar(positive, -1) is True
    sigma = Lattices.A2.similarity(
        -1, list(positive.module_generators()), codomain=positive
    )
    assert sigma.matrix().is_one()
    assert Lattices.A2.is_similar(Lattices.A2.twist(3), 3) is True


def test_the_isometry_torsor_transporter_recovers_the_acting_element() -> None:
    r"""Definitional (torsor structure of a nonempty isometry homset): for
    isometries $f$ and $g\circ f$ the transporter answers $g$ -- the free
    transitive $O(M)$-action makes it unique."""
    homset = Lattices.A2.Isom(Lattices.A2)
    witness = homset.an_element()
    acting = Lattices.A2.Aut()
    moved_by = None
    for automorphism in acting:
        if not automorphism.is_identity():
            moved_by = automorphism
            break
    assert moved_by is not None, "O(A2) has 12 elements, most not identity"
    moved = witness.then(moved_by)
    assert homset.transporter(witness, moved) == moved_by


# ---------------------------------------------------------------------------
# Automorphism groups of abstract finite groups (DF04 sec. 4.4; CCN+85).
#
# The owned surface is one spelling, ``G.Aut()``, for every group a session
# constructs -- Sage spells this only on GAP-backed abelian groups.  Orders
# are asserted against the cited literature values, never against the
# engine's own recomputation.  The trivial row is definitional, like the two
# definitional facts in the header: the identity is the only bijection of a
# one-element set.
# ---------------------------------------------------------------------------

ABSTRACT_GROUP_AUTOMORPHISM_ORDERS = {
    # Definitional: the identity is the only bijection of a one-element set.
    "trivial": (PermutationGroup([]), 1),
    # DF04 sec. 4.4 Prop. 17(2) at n = 3: Aut(C_8) = Z_2 x Z_2, order 4.
    "C8": (CyclicPermutationGroup(8), 4),
    # DF04 sec. 4.4 Prop. 17(3), displayed: Aut(V_4) = GL_2(F_2) = S_3.
    "C2 x C2": (KleinFourGroup(), 6),
    # DF04 sec. 4.4 Prop. 17(5): Aut(Q_8) = S_4, order 24.
    "Q8": (QuaternionGroup(), 24),
    # DF04 sec. 4.4 Prop. 17(4): Aut(S_n) = Inn(S_n) = S_n for n != 6.
    "S3": (SymmetricGroup(3), 6),
    # DF04 sec. 4.4 Prop. 17(4): [Aut(S_6) : Inn(S_6)] = 2, so 2 * 6!.
    "S6": (SymmetricGroup(6), 1440),
    # CCN+85, M12 page: Order = 95040 with Out = 2; M12 is simple, so its
    # centre is trivial, Inn(M12) = M12, and |Aut(M12)| = 95040 * 2.
    "M12": (MathieuGroup(12), 190080),
}


@pytest.mark.parametrize("name", sorted(ABSTRACT_GROUP_AUTOMORPHISM_ORDERS))
def test_abstract_group_automorphism_order_matches_the_literature(
    name: str,
) -> None:
    r"""\(|\operatorname{Aut}(G)|\) as the literature tabulates it."""
    group, expected = ABSTRACT_GROUP_AUTOMORPHISM_ORDERS[name]
    assert group.Aut().order() == expected


def test_aut_of_c8_is_elementary_abelian() -> None:
    r"""DF04 sec. 4.4 Prop. 17(2) at \(n=3\): \(\operatorname{Aut}(C_8)\cong Z_2\times Z_2\).

    Order four with every element an involution is the Klein four group; the
    order alone cannot separate it from \(C_4\), which is what the source's
    "not cyclic but has a cyclic subgroup of index 2" clause is about.
    """
    automorphisms = CyclicPermutationGroup(8).Aut()
    elements = list(automorphisms)
    assert len(elements) == 4
    identity = automorphisms.one()
    assert all(
        automorphism * automorphism == identity for automorphism in elements
    )


def test_aut_of_the_klein_four_group_is_nonabelian_of_order_six() -> None:
    r"""DF04 sec. 4.4 Prop. 17(3): \(\operatorname{Aut}(V_4)\cong GL_2(\mathbb F_2)\cong S_3\).

    Order six plus one non-commuting pair: of the two groups of order six
    only \(S_3\) is nonabelian, which separates the source's identification
    from \(C_6\).
    """
    automorphisms = KleinFourGroup().Aut()
    elements = list(automorphisms)
    assert len(elements) == 6
    assert any(
        left * right != right * left
        for left in elements
        for right in elements
    )


def test_the_conjugation_morphism_realizes_all_of_aut_s3() -> None:
    r"""DF04 sec. 4.4 Prop. 17(4) at \(n=3\): \(\operatorname{Aut}(S_3)=\operatorname{Inn}(S_3)\cong S_3\).

    \(Z(S_3)=1\), so \(c\) is injective and \(\operatorname{Inn}(S_3)\cong
    S_3\) by the first isomorphism theorem (DF04 sec. 4.4 Cor. 15 with the
    remark following it); its image already carries the full order six.
    """
    s3 = SymmetricGroup(3)
    conjugation = s3.conjugation_morphism()
    assert conjugation.is_injective()
    assert conjugation.kernel().order() == 1
    assert conjugation.image().order() == 6
    assert s3.Aut().order() == 6


def test_s6_has_outer_automorphisms_of_index_two() -> None:
    r"""DF04 sec. 4.4 Prop. 17(4): \([\operatorname{Aut}(S_6):\operatorname{Inn}(S_6)]=2\).

    \(S_6\) is centerless, so \(\operatorname{Inn}(S_6)\cong S_6\) has order
    720, and the one outer case among the symmetric groups doubles it.
    """
    s6 = SymmetricGroup(6)
    conjugation = s6.conjugation_morphism()
    assert conjugation.kernel().order() == 1
    assert conjugation.image().order() == 720
    assert s6.Aut().order() == 1440, "[Aut(S6) : Inn(S6)] = 2 doubles 6!"
