# Origin: gitclones/integral_lattice/cat/src/abc_specs/w_categories/one_categories/groups.py
# Copied 2026-08-20 by the integral_lattice enrichment migration
# (PLAN-corpora-audit-registry, sections R3/R4). Content below is unmodified.
#
# This is a DESIGN RECORD: it states an intended interface, not the built
# preamble. Divergences and recorded errors are listed in the INDEX.md of
# this corpus.

"""
Group ABCs.

Defines:
1. _GroupsCategory_ABC: The Category of Groups (Objects=Groups, Morphisms=Homomorphisms).
2. _GroupObject_ABC: An Object in the Category of Groups (A Group G).
3. _GroupElement_ABC: An element g ∈ G (a (-1)-cell).

Per docs/categories_to_implement.md §Groups.
"""

from __future__ import annotations

from src.local_typing import *

from src._types import BoolProof, CategoryABCs


class _GroupsCategory_ABC(CategoryABCs.Nontrivial_TwoCategory, ABC):
    """
    The Category of Groups (Grp).

    - Objects: Groups (instances of CategoryABCs.GroupObject).
    - Morphisms: Group homomorphisms.
    - Structure: Complete, Cocomplete.
    """

    @final
    @abstractmethod
    def forgetful_functor_to_sets(self) -> CategoryABCs.Functor:
        """U: Grp → Set (forgetful functor)."""
        ...

    @final
    @abstractmethod
    def free_group_functor(self) -> CategoryABCs.Functor:
        """F: Set → Grp (free group functor, left adjoint to U)."""
        ...

    @final
    @abstractmethod
    def trivial_group(self) -> CategoryABCs.GroupObject:
        """Return the trivial group {e} (zero object)."""
        ...


class _GroupObject_ABC(CategoryABCs.SetObject, ABC):
    """
    An Object in the Category of Groups (A Group G).

    Viewed as a one-object groupoid where the single object
    has Aut = G.
    
    Inherits from SetObject: cardinality(), is_finite(), __iter__, etc.
    """

    # === Forgetful functor views ===

    def as_set(self) -> CategoryABCs.SetObject:
        """
        View as underlying set (forgetful functor U: Grp → Set).
        
        Identity since GroupObject inherits from SetObject.
        """
        return self

    # === Group structure ===

    @final
    @abstractmethod
    def identity_element(self) -> CategoryABCs.GroupElement:
        """e ∈ G (identity element)."""
        ...

    @final
    @abstractmethod
    def binary_operation(
        self, x: CategoryABCs.GroupElement, y: CategoryABCs.GroupElement
    ) -> CategoryABCs.GroupElement:
        """x · y (group multiplication)."""
        ...

    @final
    @abstractmethod
    def inverse(self, x: CategoryABCs.GroupElement) -> CategoryABCs.GroupElement:
        """x^{-1} (group inverse)."""
        ...

    # === Order and generators ===

    @final
    @abstractmethod
    def order(self) -> Any:
        """|G| (order of the group)."""
        ...

    # TODO: Uncomment when implementing subgroup construction
    # @final
    # @abstractmethod
    # def cyclic_subgroup_generated_by(
    #     self, x: CategoryABCs.GroupElement
    # ) -> CategoryABCs.GroupObject:
    #     """⟨x⟩ ⊆ G (cyclic subgroup generated by x)."""
    #     ...

    # @final
    # @abstractmethod
    # def subgroup_generated_by(
    #     self, xs: list[CategoryABCs.GroupElement]
    # ) -> CategoryABCs.GroupObject:
    #     """⟨x_1, ..., x_n⟩ ⊆ G."""
    #     ...

    # @final
    # @abstractmethod
    # def generators(self) -> list[CategoryABCs.GroupElement]:
    #     """Return a generating set for G."""
    #     ...

    # === Subgroup structure ===

    @final
    @abstractmethod
    def center(self) -> CategoryABCs.GroupObject:
        """Z(G) = {z ∈ G | zg = gz ∀g ∈ G}."""
        ...

    @final
    @abstractmethod
    def commutator_subgroup(self) -> CategoryABCs.GroupObject:
        """[G, G] (derived subgroup)."""
        ...

    @final
    @abstractmethod
    def normalizer(self, H: CategoryABCs.GroupObject) -> CategoryABCs.GroupObject:
        """N_G(H) = {g ∈ G | gHg^{-1} = H}."""
        ...

    @final
    @abstractmethod
    def centralizer(self, H: CategoryABCs.GroupObject) -> CategoryABCs.GroupObject:
        """C_G(H) = {g ∈ G | gh = hg ∀h ∈ H}."""
        ...

    # === Quotients ===

    @final
    @abstractmethod
    def quotient_by(self, N: CategoryABCs.GroupObject) -> CategoryABCs.GroupObject:
        """G/N (quotient by normal subgroup)."""
        ...

    # === Predicates ===

    @final
    @abstractmethod
    def is_abelian(self) -> BoolProof:
        """Check if G is abelian."""
        ...

    # is_finite() inherited from SetObject

    @final
    @abstractmethod
    def is_finitely_generated(self) -> BoolProof:
        """Check if G is finitely generated."""
        ...

    @final
    @abstractmethod
    def is_finitely_presented(self) -> BoolProof:
        """Check if G is finitely presented."""
        ...

    @final
    @abstractmethod
    def is_cyclic(self) -> BoolProof:
        """Check if G is cyclic."""
        ...

    @final
    @abstractmethod
    def is_simple(self) -> BoolProof:
        """Check if G is simple (no proper normal subgroups)."""
        ...

    @final
    @abstractmethod
    def is_solvable(self) -> BoolProof:
        """Check if G is solvable."""
        ...

    @final
    @abstractmethod
    def is_nilpotent(self) -> BoolProof:
        """Check if G is nilpotent."""
        ...

    @final
    @abstractmethod
    def is_normal_subgroup_of(self, G: CategoryABCs.GroupObject) -> BoolProof:
        """Check if self ⊲ G."""
        ...


class _GroupElement_ABC(CategoryABCs.Element_In_A_1_Cat, ABC):
    """
    An element g ∈ G.

    Inherits from CategoryABCs.Element (the standard element interface).
    """

    def parent_group(self) -> CategoryABCs.GroupObject:
        """Alias for parent_object()."""
        ...

    @final
    @abstractmethod
    def __mul__(self, other: CategoryABCs.GroupElement) -> CategoryABCs.GroupElement:
        """g · h (group multiplication)."""
        ...

    @final
    @abstractmethod
    def __invert__(self) -> CategoryABCs.GroupElement:
        """g^{-1} (group inverse)."""
        ...

    @final
    @abstractmethod
    def __pow__(self, n: int) -> CategoryABCs.GroupElement:
        """g^n (repeated multiplication)."""
        ...

    @final
    @abstractmethod
    def order(self) -> Any:
        """ord(g) = min{n > 0 | g^n = e}."""
        ...

    @final
    @abstractmethod
    def conjugate_by(self, h: CategoryABCs.GroupElement) -> CategoryABCs.GroupElement:
        """h g h^{-1} (conjugation)."""
        ...

    @final
    @abstractmethod
    def commutator_with(self, h: CategoryABCs.GroupElement) -> CategoryABCs.GroupElement:
        """[g, h] = g h g^{-1} h^{-1}."""
        ...


class _GroupHomomorphism_ABC(CategoryABCs.OneMorphism_In_A_1_Cat, ABC):
    """
    A group homomorphism φ: G → H.

    Inherits source()/target(), is_injective()/is_surjective()/is_isomorphism(),
    compose(), is_identity(), etc. from Morphism_In_A_1_Cat.
    """


# Expose for registration in CategoryABCs
_ = _GroupsCategory_ABC
_ = _GroupObject_ABC
_ = _GroupElement_ABC
_ = _GroupHomomorphism_ABC
