r"""The preamble's ``sage.all``: importing it is what makes a scope a session.

``from dzack_research.preamble.all import *`` enters the closed preamble
mathematical universe.  The module is not a superset of ``sage.all`` and does
not publish Sage's constructor namespace.  Sage is an implementation service
used by private adapters; every public name bound here is owned mathematics or
an ordinary Python support object deliberately selected by the preamble.
"""

import sys as _sys

# The session's numeric vocabulary and its parser are one contract: decimal
# literals remain explicit MPFR approximations even though ``RealNumber`` now
# names an exact element of ``RR``.
import sageparse.preparser.research  # noqa: F401,E402
from dzack_research.preamble import language_runtime as _language_runtime

_language_runtime.install()
from sage.repl.load import load as _sage_load

from dzack_research.preamble.utilities import lmap, lzip, to_var_names, zipsum  # noqa: F401

from dzack_research.preamble.categories.abstract_categories import (  # noqa: F401
    ArrowCategory,
    AutCategoryConstruction,
    AutCategoryOf,
    AutomorphismArrowCategory,
    BiproductCategory,
    Cat,
    CategoricalIsomorphism,
    CategoryPacket,
    CategoryFunctorMorphism,
    CategoryObject,
    Cocone,
    CoconeCategory,
    ColimitsOfCategory,
    CommutativeSquare,
    Cone,
    ConeCategory,
    CoproductCoconeCategory,
    CoproductsOfCategory,
    CoreCategory,
    CosliceCategory,
    DiagramCategory,
    DirectedSystem,
    DirectSumCategory,
    DirectSumDecomposition,
    DirectSumObjects,
    EndArrowCategory,
    EndCategoryConstruction,
    EndCategoryOf,
    EpiCategoryConstruction,
    EpiCategoryOf,
    EpimorphismArrowCategory,
    FunctorCategory,
    HomCategories,
    HomCategoryConstruction,
    HomCategoryOf,
    InverseSystem,
    IsoArrowCategory,
    IsoCategoryConstruction,
    IsoCategoryOf,
    Isomorphism,
    LimitsOfCategory,
    MonoCategoryConstruction,
    MonoCategoryOf,
    MonomorphismArrowCategory,
    NaturalTransformationMorphism,
    OppositeMorphism,
    ProductConeCategory,
    ProductMorphism,
    ProductsOfCategory,
    SliceCategory,
    SubobjectCategory,
    SubobjectHomset,
    SubobjectMorphism,
    SuperobjectCategory,
    TensorProductCategory,
    WideSubcategory,
    common_category,
    category_packet,
    coproduct_cocone_category,
    product_cone_category,
)
from dzack_research.preamble.categories.abstract_categories.functors import (  # noqa: F401
    Bifunctor,
    CodomainFunctor,
    ContravariantFunctor,
    ComposedFunctor,
    ConstantDiagram,
    DiscreteCategories,
    DiscreteCategory,
    DiscreteDiagram,
    DiscreteFunctor,
    DomainFunctor,
    NaturalTransformations,
    ObjectSetFunctor,
    compose_functors,
)
from dzack_research.preamble.categories.algebras import (  # noqa: F401
    AlgebraHomset,
    AlgebraMorphism,
    Algebras,
    AlgebrasWithChosenFinitePresentation,
    AlgebrasWithChosenMultiplication,
    AlternatingAlgebraOf,
    AlternatingAlgebraOn,
    AlternatingAlgebras,
    AssociativeAlgebras,
    AssociativeAlgebrasWithChosenMultiplication,
    AugmentedAlgebras,
    CommutativeAlgebraCoproducts,
    CommutativeAlgebraPushouts,
    CommutativeAlgebras,
    CommutatorLieAlgebras,
    commutative_algebra_coproduct,
    commutative_algebra_pushout,
    CommutativeDifferentialGradedAlgebras,
    CohomologyAlgebra,
    CohomologyAlgebraElement,
    CohomologyAlgebraHomset,
    CohomologyAlgebraMorphism,
    CohomologyAlgebras,
    DeRhamAlgebra,
    DeRhamAlgebras,
    Derivation,
    DerivationSpace,
    Derivations,
    DGAHomset,
    DGAMorphism,
    DegreewiseLinearMorphism,
    Differential,
    DifferentialComponentMorphism,
    DifferentialGradedAlgebras,
    FinitelyPresentedAlgebra,
    FinitelyPresentedAlgebraOn,
    FinitelyPresentedAlgebras,
    FramedAlgebras,
    FreeAlgebraOn,
    FreeAlgebras,
    GradedAlgebras,
    GradedAlgebraHomset,
    GradedAlgebraMorphism,
    GradedAugmentedAlgebras,
    GroupAlgebra,
    GroupAlgebraFunctor,
    GroupAlgebras,
    GradedCommutativeAlgebras,
    GradedDerivation,
    GradedDerivationSpace,
    GradedDerivations,
    GradedCommutator,
    GradedFreeAlgebras,
    InteriorProduct,
    KahlerDifferentialModules,
    KahlerDifferentials,
    LieAlgebras,
    LieBracket,
    LieDerivative,
    OwnedAlgebras,
    RestrictedGradedAlgebra,
    RestrictedGradedAlgebraElement,
    RestrictedScalarsAlgebras,
    StrictlyCommutativeDifferentialGradedAlgebras,
    StrictlyGradedCommutativeAlgebras,
    SymmetricAlgebraOf,
    SymmetricAlgebraOn,
    SymmetricAlgebras,
    TensorAlgebraOf,
    TensorAlgebraOn,
    TensorAlgebras,
    VectorFields,
    algebra_from_multiplication,
    algebra_homset,
    augmented_algebra,
    cohomology_algebra_homset,
    dga_homset,
    graded_algebra_homset,
    own_algebra,
    restrict_graded_algebra_scalars,
    restrict_algebra_scalars,
)
from dzack_research.preamble.categories.algebras.algebras import MatrixAlgebras  # noqa: F401
from dzack_research.preamble.categories.modules.pure.modules import (  # noqa: F401
    MatrixEndomorphismSpaces,
    MatrixSpaces,
)
from dzack_research.preamble.categories.coxeter_diagrams import CoxeterDiagrams  # noqa: F401
from dzack_research.preamble.categories.divisors import (  # noqa: F401
    CartierDivisorGroup,
    CartierDivisorGroups,
    ClassGroup,
    ClassGroups,
    DivisorGroup,
    DivisorGroups,
    FormalDivisor,
    FormalDivisorGroups,
    InvertibleSheaf,
    PicardGroup,
    PicardGroups,
    TrivialInvertibleSheaf,
    WeilDivisorGroup,
    WeilDivisorGroups,
)
from dzack_research.preamble.categories.forms import (  # noqa: F401
    BilinearForm,
    BilinearFormMorphism,
    BilinearForms,
    PairingMorphism,
    Pairings,
    QuadraticForm,
    QuadraticFormMorphism,
    QuadraticForms,
    gram_tensor_from_graph,
    gram_tensor_graph,
    tensor_connected_component_cuts,
)
from dzack_research.preamble.categories.functions import (  # noqa: F401
    C,
    GradedLebesgueModule,
    GradedTensorProductModules,
    GradedTensorSquare,
    LebesgueGradedModules,
    Lp,
    ell,
    graded_lebesgue_algebra,
    lebesgue_convolution_algebra,
)
from dzack_research.preamble.categories.functors.abelianization import (
    AbelianGroupInclusionFunctor,
    AbelianizationAdjunction,
    AbelianizationFunctor,
    abelianization_adjunction,
)
from dzack_research.preamble.categories.functors.core import (
    Adjunction,
    CategoryInclusionFunctor,
    CompositeAdjunction,
    CompositeFunctor,
    Functor,
    IdentityFunctor,
    NaturalTransformation,
    category_inclusion,
    compose_adjunctions,
)
from dzack_research.preamble.categories.functors.algebra_scalar_change import (
    AlgebraBaseChangeAdjunction,
    AlgebraRestrictionOfScalarsFunctor,
    AlgebraScalarExtensionFunctor,
    algebra_base_change_adjunction,
)
from dzack_research.preamble.categories.functors.algebra_modules import (
    AlgebraUnderlyingModuleFunctor,
    algebra_underlying_module_functor,
)
from dzack_research.preamble.categories.functors.free_algebras import (
    AlternatingAlgebraFunctor,
    SymmetricAlgebraAdjunction,
    SymmetricAlgebraFunctor,
    TensorAlgebraAdjunction,
    TensorAlgebraFunctor,
    alternating_algebra_functor,
    symmetric_algebra_adjunction,
    symmetric_algebra_functor,
    tensor_algebra_adjunction,
    tensor_algebra_functor,
)
from dzack_research.preamble.categories.functors.scalar_change import (
    BaseChangeAdjunction,
    CoextensionOfScalarsFunctor,
    RestrictionCoextensionAdjunction,
    RestrictionOfScalarsFunctor,
    ScalarExtensionFunctor,
    base_change_adjunction,
    restriction_coextension_adjunction,
)
from dzack_research.preamble.categories.functors.free_forms import (
    BilinearFreeFormAdjunction,
    BilinearUnderlyingModuleFunctor,
    FreeBilinearFormFunctor,
    FreeQuadraticFormFunctor,
    QuadraticFreeFormAdjunction,
    QuadraticUnderlyingModuleFunctor,
    bilinear_free_form_adjunction,
    quadratic_free_form_adjunction,
)
from dzack_research.preamble.categories.functors.linear_constructions import (
    BiproductBifunctor,
    CokernelArrowFunctor,
    DualizationFunctor,
    KernelArrowFunctor,
    OrthogonalDirectSumBifunctor,
)
from dzack_research.preamble.categories.functors.cardinality import (
    CardinalityFunctor,
    cardinality_functor,
)
from dzack_research.preamble.categories.functors.group_induction import (
    CoinductionFunctor,
    InductionFunctor,
    InductionRestrictionAdjunction,
    RestrictionCoinductionAdjunction,
    RestrictionOfActingGroupFunctor,
)
from dzack_research.preamble.categories.functors.group_actions import (
    CoinvariantsFunctor,
    CoinvariantsTrivialAdjunction,
    InvariantsFunctor,
    TrivialActionFunctor,
    TrivialInvariantsAdjunction,
)
from dzack_research.preamble.categories.functors.cochain_complexes import (
    CochainUnderlyingGradedModuleFunctor,
    cochain_underlying_graded_module_functor,
)
from dzack_research.preamble.categories.functors.cohomology import (
    CohomologyAlgebraFunctor,
    CohomologyFunctor,
    DeRhamCohomologyAlgebraFunctor,
    DeRhamCohomologyFunctor,
    cohomology_algebra_functor,
    cohomology_functor,
    de_rham_cohomology_algebra_functor,
    de_rham_cohomology_functor,
)
from dzack_research.preamble.categories.functors.subobject_images import (
    DirectImageSubobjectFunctor,
    InverseImageSubobjectFunctor,
    SubobjectImageAdjunction,
    subobject_image_adjunction,
)
from dzack_research.preamble.categories.functors.de_rham import (
    DeRhamAdjunction,
    DeRhamFunctor,
    DegreeZeroDGAFunctor,
    de_rham_adjunction,
    de_rham_functor,
    degree_zero_dga_functor,
)
from dzack_research.preamble.categories.functors.set_constructions import (
    ExponentialFunctor,
    FinitePowerSetFunctor,
    FixedCardinalitySubsetFunctor,
    InverseImagePowerSetFunctor,
    exponential_functor,
    finite_power_set_functor,
    fixed_cardinality_subset_functor,
    inverse_image_power_set_functor,
)
from dzack_research.preamble.categories.functors.orders_number_fields import (
    FractionFieldFunctor,
    OrderNumberFieldAdjunction,
    RingOfIntegersFunctor,
    order_number_field_adjunction,
)
from dzack_research.preamble.categories.functors.free_forgetful import (
    FreeForgetfulAdjunction,
    FreeModuleFunctor,
    UnderlyingSetFunctor,
    free_forgetful_adjunction,
)
from dzack_research.preamble.categories.functors.free_groups import (
    FreeGroupFunctor,
    FreeGroupUnderlyingSetAdjunction,
    GroupUnderlyingSetFunctor,
    free_group_underlying_set_adjunction,
)
from dzack_research.preamble.categories.functors.group_scalar_change import (
    GroupModuleBaseChangeAdjunction,
    GroupModuleRestrictionOfScalarsFunctor,
    GroupModuleScalarExtensionFunctor,
    group_module_base_change_adjunction,
)
from dzack_research.preamble.categories.functors.tensor_hom import (
    InternalHomFromFunctor,
    TensorByFunctor,
    TensorHomAdjunction,
    tensor_hom_adjunction,
)
from dzack_research.preamble.categories.functors.hom_packets import (
    InducedAutFunctor,
    InducedEndFunctor,
    InducedHomFunctor,
    induced_aut_functor,
    induced_end_functor,
    induced_hom_functor,
)
from dzack_research.preamble.categories.functors.module_localization import (
    ModuleLocalizationFunctor,
    module_localization_functor,
)
from dzack_research.preamble.categories.group import (  # noqa: F401
    AbelianGroups,
    AbsoluteDecompositionGroup,
    AbsoluteGaloisGroup,
    AbsoluteGaloisGroupElement,
    AbsoluteGaloisGroups,
    AbsoluteGaloisGroupsOfFiniteFields,
    AbsoluteGaloisSliceAutomorphism,
    AbsoluteInertiaGroup,
    ContinuousGroupHomset,
    CyclicGroups,
    CyclotomicCharacter,
    DecompositionGroupConjugacyClass,
    ElementConjugacyClass,
    EquivariantMorphism,
    ExactFieldHomset,
    ExactFieldMorphism,
    FiniteAbelianGroups,
    FiniteElementConjugacyClass,
    FiniteGaloisAutomorphism,
    FiniteGaloisExtension,
    FiniteGaloisQuotient,
    FiniteGaloisSubgroup,
    FiniteGroupClassFunction,
    FiniteGroups,
    FiniteGSets,
    FinitelyGeneratedGroups,
    FinitelyPresentedGroups,
    FrobeniusConjugacyClass,
    FrobeniusElement,
    GaloisRestrictionMap,
    GroupAutomorphismGroup,
    GroupHomset,
    Groups,
    GroupsWithChosenFiniteGeneratingSet,
    GroupsWithChosenFinitePresentation,
    GObjectHomset,
    GObjects,
    GSetHomset,
    GSetMorphism,
    GSets,
    IndexedFreeGroupHomomorphism,
    IndexedFreeGroupHomset,
    InertiaGroupConjugacyClass,
    LiftCoset,
    OpenAbsoluteGaloisSubgroup,
    OpenAbsoluteGaloisSubgroups,
    OpenGaloisSubgroupConjugacyClass,
    OpenSubgroupInclusion,
    OrbitSets,
    OwnedAbelianGroups,
    OwnedFiniteAbelianGroups,
    OwnedFiniteGroups,
    OwnedFinitelyGeneratedGroups,
    OwnedFinitelyPresentedGroups,
    OwnedGroups,
    PredicateSubgroups,
    PrimeProlongation,
    ProfiniteCharacter,
    ProfiniteGroups,
    QuadraticCharacter,
    RestrictedProfiniteCharacter,
    Subgroups,
    Submonoids,
    Torsors,
    absolute_galois_group,
    absolute_galois_group_category,
    centralizer,
    continuous_group_homset,
    cyclic_subgroup,
    exact_embeddings,
    exact_field_homset,
    extensions_along,
    field_generators,
    finite_decomposition_group,
    finite_frobenius_class,
    finite_g_set,
    finite_inertia_group,
    first_exact_embedding,
    fixed_point_set,
    g_set_homset,
    generated_submonoid,
    group_homset,
    groups,
    open_absolute_galois_subgroup,
    predicate_subgroup,
    predicate_submonoid,
    restrict_along,
    trivial_g_set,
)
from dzack_research.preamble.categories.lattice_morphisms import (  # noqa: F401
    LatticeEmbedding,
    LatticeHomset,
    LatticeIsometry,
    LatticeMorphism,
)
from dzack_research.preamble.categories.isotropic_orbits import IsotropicFlag  # noqa: F401
from dzack_research.preamble.categories.lattices import (  # noqa: F401
    EvenLattices,
    FiniteRankLattices,
    NondegenerateLattices,
)
from dzack_research.preamble.categories.lattices import (  # noqa: F401
    Genus,
    Lattices,
    diagonal_gram,
    signature_pair,
    signature_pairs,
    nikulin_invariants,
)
from dzack_research.preamble.categories.modules import (  # noqa: F401
    BasedFreeModule,
    BilinearFormModules,
    BilinearMap,
    Boundaries,
    BiproductModules,
    CochainComplex,
    CochainComplexElement,
    CochainComplexObject,
    CochainComplexes,
    CochainDifferential,
    CochainHomset,
    CochainMorphism,
    Cohomology,
    CohomologyModules,
    Connection,
    ConnectionDeRhamDifferential,
    ConnectionDeRhamModule,
    ConnectionHomset,
    ConnectionMorphism,
    ConnectionSpace,
    Connections,
    CorrelationIsomorphism,
    DeterminantLine,
    DiscriminantBilinearModules,
    DiscriminantModule,
    DiscriminantModules,
    DiscriminantQuadraticModules,
    DifferentialGradedModules,
    DividedSquare,
    DividedSquareModules,
    FiberedFormedModuleHomset,
    FiberedFormedModuleMorphism,
    Ext,
    ExteriorForms,
    FinitelyGeneratedFormModules,
    FinitelyGeneratedFreeFormModules,
    FinitelyGeneratedFreeModules,
    FinitelyGeneratedModules,
    FinitelyPresentedBilinearFormModules,
    FinitelyPresentedFormModules,
    FinitelyPresentedModule,
    FinitelyPresentedModules,
    FinitelyPresentedQuadraticFormModules,
    FinitelyPresentedTorsionModules,
    FormedModuleHomset,
    FormedModuleMorphism,
    FormedModules,
    FormEmbedding,
    FormModule,
    FormModules,
    FractionalIdeal,
    FractionalIdeals,
    FractionFieldQuotient,
    FractionFieldQuotients,
    FramedFreeModules,
    FramedModules,
    FramingVolumeTrivialization,
    FreeFormModules,
    FreeModule,
    FreeModuleOn,
    FreeModules,
    FreeResolution,
    GeneralModule,
    GeneralModuleElement,
    GeneralModuleParent,
    GradedModules,
    GradedAlgebraModules,
    GroupModuleHomset,
    GroupModuleMorphism,
    HodgeDiscriminant,
    HodgeStar,
    HodgeStarOverFractionField,
    Ideals,
    InternalHom,
    InternalHomModules,
    LinearHomModules,
    LocalizedModules,
    ModuleEmbedding,
    MultivectorHodgeStar,
    ModuleWithConnection,
    Modules,
    ModulesWithFlatConnection,
    ModulesWithConnection,
    ModuleSubobjects,
    ModulesWithChosenFinitePresentation,
    PairedModules,
    PoincareDuality,
    ProjectiveModules,
    QuadraticFormModules,
    QuadraticSquare,
    RestrictedScalarsModules,
    RestrictedScalarsModuleView,
    SymmetricBilinearFormModules,
    TensorProductModules,
    Tor,
    TorsionBilinearFormModules,
    TorsionFormIsometry,
    TorsionModule,
    TorsionModules,
    TorsionQuadraticFormModules,
    VectorSpaces,
    VolumeTrivialization,
    AlgebraicCorrelationMorphism,
    biproduct_morphism,
    cochain_homset,
    connection_homset,
    Cycles,
    divided_square_morphism,
    fibered_formed_module_homset,
    form_embedding,
    formed_module_homset,
    free_resolution,
    internal_hom_morphism,
    module_embedding,
    module_from_action,
    module_homset,
    regular_dg_module,
    restrict_scalars,
    ring_as_module,
    tensor_product_morphism,
    twist_scalar_action,
)
from dzack_research.preamble.categories.rational_lattices import RationalLattices  # noqa: F401
from dzack_research.preamble.categories.lattices import RootLattices  # noqa: F401
from dzack_research.preamble.categories.vector_orbits import (  # noqa: F401
    VectorPrimitiveExtension,
    definite_complement_extensions,
    gluing_route_discriminant_classes,
)
from dzack_research.preamble.categories.schemes import (  # noqa: F401
    AffineSpecFunctor,
    SpecFunctor,
    affine_spec_functor,
    AffineSchemes,
    AffineSpace,
    AffineSpaces,
    ClosedEmbeddings,
    SchemeMonomorphisms,
    ConvexPolygon,
    ConvexPolygons,
    ConvexPolytope,
    ConvexPolytopes,
    Curves,
    FiberProductSchemes,
    FiniteTypeSchemes,
    IntegralSchemes,
    LatticePolygon,
    LatticePolygons,
    LatticePolytope,
    LatticePolytopes,
    LocallyRingedSpaces,
    NormalSchemes,
    OpenImmersions,
    ProjectiveSchemes,
    ProjectiveSpace,
    ProjectiveSpaces,
    ProductProjectiveSpaces,
    ProductSchemes,
    QuasiAffineSchemes,
    QuasiProjectiveSchemes,
    RingedSpaces,
    SchemeUnderlyingSpace,
    SchemeMorphism,
    Schemes,
    SeparatedSchemes,
    SmoothSchemes,
    Spec,
    StructureSheaf,
    Surfaces,
    Varieties,
    scheme_fiber_product,
    scheme_product,
)
from dzack_research.preamble.categories.sets import (  # noqa: F401
    CardinalComparison,
    Cardinalities,
    CartesianProductMorphism,
    CartesianProductOfFamily,
    CartesianProductOfSets,
    CartesianProductsOfSets,
    ConditionSet,
    CoproductMorphism,
    CoproductOfFamily,
    CoproductOfSets,
    CoproductsOfSets,
    CountableSets,
    CountablyInfiniteSets,
    DisjointUnionsOfSets,
    EnumeratedByIntegers,
    EnumeratedByNaturals,
    EnumeratedSets,
    ExponentialOfSets,
    FinitelySupportedFunctionSets,
    FinitePowerSets,
    FiniteSets,
    FiniteSubsets,
    FourierCharacters,
    FunctionEnumeratedSets,
    HermitePolynomials,
    ImageSet,
    InfiniteEnumeratedSets,
    InfiniteSets,
    LaurentMonomials,
    NN,
    ObjectSetsOfDiscreteCategories,
    Ordinals,
    OrdinalSemirings,
    PartiallyOrderedSets,
    PowerSet,
    PowerSets,
    Set,
    SetInclusion,
    SetInjection,
    Sets,
    SetSurjection,
    SincTranslates,
    SubsetsOfSize,
    TotallyOrderedSets,
    UncountableSets,
    aleph,
    aleph0,
    cardinal,
    cartesian_product_of,
    continuum,
    omega,
    omega0,
    ordinal,
    set_injection,
    set_surjection,
)
from dzack_research.preamble.catalogue import (  # noqa: F401
    Embeddings,
    Involutions,
    NamedLattices,
    NegativeDefTwoElementary,
    TwoElementary,
    signature_orthogonal_sums,
    two_elementary_orthogonal_sums,
    validate_negative_def_two_elementary_table,
    validate_two_elementary_table,
)
from dzack_research.preamble.coble import Coble  # noqa: F401
from dzack_research.preamble.logic import Predicate, Unknown, ask  # noqa: F401
from dzack_research.preamble.rings import (  # noqa: F401
    AdicallyCompleteRings,
    ArtinianRings,
    CommutativeRings,
    CompleteLocalRings,
    DualNumbers,
    FormalPowerSeriesRings,
    RR,
    CommutativeIdeal,
    CommutativeIdeals,
    DistinguishedOpenSubobject,
    DivisionRings,
    ExactRealField,
    ExactRealNumber,
    Fields,
    IntegralDomains,
    LocalRings,
    NoetherianRings,
    OrderedRings,
    NonNegativeReals,
    NumberFieldsWithChosenPrimitiveElement,
    OwnedCategoryOverBaseRing,
    OwnedDivisionRings,
    OwnedFields,
    OwnedNumberFields,
    OwnedOrders,
    OwnedRings,
    OwnedRngs,
    OwnedSemirings,
    PredicateSubrings,
    PrimeField,
    PrimeFields,
    PrincipalIdealDomains,
    PrimeSpectra,
    RealApproximation,
    RealNumber,
    ResidueField,
    Rings,
    ZariskiClosedSubobject,
    UnitInterval,
    predicate_subring,
)
from dzack_research.preamble.rings import _restore_session_ring_bindings  # noqa: F401
from dzack_research.preamble.sterk import Sterk  # noqa: F401
from dzack_research.preamble.tensors import Tensor, TensorModule, tensor  # noqa: F401


def load(filename: str, globals: dict | None = None, attach: bool = False) -> None:
    r"""Load a Sage file and restore this session's owned scalar vocabulary."""
    scope = _sys._getframe(1).f_globals if globals is None else globals
    _sage_load(filename, scope, attach)
    _restore_session_ring_bindings(scope)
    scope["GradedLebesgueAlgebra"] = graded_lebesgue_algebra()
    scope["LebesgueConvolutionAlgebra"] = lebesgue_convolution_algebra()
    scope["load"] = load


# This is deliberately last.  Internal modules may import backend names while
# they load; the public session receives only owned scalar objects, owned
# constructors, and the owned runtime names emitted by the research dialect.
_restore_session_ring_bindings(globals())
Integer = _language_runtime.Integer
RealNumber = _language_runtime.RealNumber
ComplexNumber = _language_runtime.ComplexNumber
matrix = _language_runtime.matrix
factorial = _language_runtime.factorial
ellipsis_range = _language_runtime.ellipsis_range
ellipsis_iter = _language_runtime.ellipsis_iter
var = _language_runtime.var
symbolic_expression = _language_runtime.symbolic_expression
GradedLebesgueAlgebra = graded_lebesgue_algebra()
LebesgueConvolutionAlgebra = lebesgue_convolution_algebra()
