# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.structure.element import CommutativeRingElement

class Expression(CommutativeRingElement):
    def __add__(self, other: Any) -> Expression: ...
    def __radd__(self, other: Any) -> Expression: ...
    def __sub__(self, other: Any) -> Expression: ...
    def __rsub__(self, other: Any) -> Expression: ...
    def __mul__(self, other: Any) -> Expression: ...
    def __rmul__(self, other: Any) -> Expression: ...
    def __truediv__(self, other: Any) -> Expression: ...
    def __rtruediv__(self, other: Any) -> Expression: ...
    def __pow__(self, other: Any) -> Expression: ...
    def __neg__(self) -> Expression: ...
    def sqrt(self) -> Expression: ...
    def simplify_full(self) -> Expression: ...
    def n(self, prec: int = ...) -> Any: ...
