r"""The isometry group of the discriminant form of ``A_2``."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_discriminant_form_of_a2_has_order_three_and_isometry_group_plus_minus_one() -> None:
    r"""``A_2^∨/A_2 ≅ ZZ/3`` since ``|det A_2| = 3``; its automorphisms are ``±1``,
    and both preserve the discriminant quadratic form (``q(-x) = q(x)``), so
    ``O(q_{A_2}) = {±1}`` has order 2, generated by ``-1`` with ``(-1)^2 = 1``."""
    discriminant = Lattices(ZZ)("A2").discriminant_group()
    group = discriminant.orthogonal_group()
    generator = next(iter(discriminant.module_generators()))
    negation = next(arrow for arrow in group if arrow(generator) == -generator)

    assert discriminant.cardinality() == 3
    assert group.cardinality() == 2
    assert negation != group.one()
    assert negation * negation == group.one()
