r"""The absolute Galois group of the field with two elements."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_absolute_galois_group_of_F2_is_procyclic_on_frobenius() -> None:
    r"""``Gal(F2bar/F2) = Zhat``, topologically generated by ``Frob: x |-> x^2``.

    The closure of ``<Frob^2>`` is the open subgroup of index 2, and its fixed
    field is ``F4``: every finite quotient is ``Gal(F_{2^n}/F2) = Z/n``,
    generated by the image of Frobenius.
    """
    galois = GF(2).absolute_galois_group()
    frobenius = galois.frobenius()
    topological_generators = galois.topological_group_generators()
    square = galois.subgroup((frobenius**2,))

    assert galois.is_profinite()
    assert galois.is_abelian()
    assert topological_generators.cardinality() == 1
    assert frobenius in topological_generators
    assert square.index() == 2
    assert square.fixed_field().cardinality() == 4
    assert galois.subgroup((frobenius**3,)).index() == 3
