r"""Coordinate computations extracted from morphisms of framed modules.

Matrices here are private coordinate data for represented morphisms.  They do
not replace the owned morphism, its kernel/image/cokernel, or its composition.
This module only centralizes mature matrix operations needed by those owners.
"""

from collections.abc import Iterable

from sage.structure.element import Matrix


def _row_normal_form(entries: Matrix, include_zero_rows: bool = False) -> Matrix:
    r"""Return a canonical reduced matrix with the same row span.

    Over a field this is reduced echelon form.  Over the integral coefficient
    rings used by the preamble, Sage's Hermite form is the corresponding exact
    row-lattice normal form.  Zero rows are omitted unless explicitly retained.
    """
    base_ring = entries.base_ring()
    if base_ring.is_field():
        reduced = entries.echelon_form()
        if include_zero_rows:
            return reduced
        nonzero_rows = tuple(
            index
            for index, row in enumerate(reduced.rows())
            if not row.is_zero()
        )
        return reduced.matrix_from_rows(nonzero_rows)
    return entries.hermite_form(include_zero_rows=include_zero_rows)


def _matrix_group(group_generators: Iterable[Matrix]):
    r"""Return the matrix group generated by ``group_generators``.

    Engine adapter (``OWN-06``): its callers hold Sage matrices already
    lowered from owned morphisms, and it calls Sage's ``MatrixGroup``, which
    selects the finite or infinite implementation.  The resulting matrix group
    is private computation data, not an owned replacement for a mathematical
    subgroup already represented by the preamble.
    """
    from sage.groups.matrix_gps.finitely_generated import MatrixGroup

    generating_set = tuple(group_generators)
    assert generating_set, "a generated matrix group needs at least one generator"
    return MatrixGroup(generating_set)
