"""Matrix computations used at module-morphism coordinate boundaries."""

from collections.abc import Iterable

from sage.structure.element import Matrix


def row_normal_form(entries: Matrix, include_zero_rows: bool = False) -> Matrix:
    r"""Return a canonical reduced matrix with the same row span."""
    if entries.base_ring().is_field():
        reduced = entries.echelon_form()
        if include_zero_rows:
            return reduced
        rows = [i for i, row in enumerate(reduced.rows()) if not row.is_zero()]
        return reduced.matrix_from_rows(rows)
    return entries.hermite_form(include_zero_rows=include_zero_rows)


def matrix_group(group_generators: Iterable[Matrix]):
    r"""Return the matrix group generated by the stated matrices."""
    from sage.groups.matrix_gps.finitely_generated import MatrixGroup

    generators = tuple(group_generators)
    if not generators:
        raise ValueError("a matrix group needs a generating set")
    if not all(isinstance(generator, Matrix) for generator in generators):
        raise TypeError("a matrix group is generated by matrices")
    return MatrixGroup(generators)
