r"""Coordinate computations extracted from morphisms of framed modules.

Matrices here are private coordinate data for represented morphisms.  They do
not replace the owned morphism, its kernel/image/cokernel, or its composition.
This module only centralizes mature matrix operations needed by those owners.
"""

from collections.abc import Iterable

from sage.structure.element import Matrix


def row_normal_form(entries: Matrix, include_zero_rows: bool = False) -> Matrix:
    r"""Return a canonical reduced matrix with the same row span.

    Over a field this is reduced echelon form.  Over the integral coefficient
    rings used by the preamble, Sage's Hermite form is the corresponding exact
    row-lattice normal form.  Zero rows are omitted unless explicitly retained.
    """
    base_ring = entries.base_ring()
    if base_ring.is_field():
        reduced = entries.echelon_form()
        if include_zero_rows:
            return reduced
        nonzero_rows = tuple(
            index
            for index, row in enumerate(reduced.rows())
            if not row.is_zero()
        )
        return reduced.matrix_from_rows(nonzero_rows)
    return entries.hermite_form(include_zero_rows=include_zero_rows)


def matrix_group(group_generators: Iterable[Matrix]):
    r"""Return the matrix group generated by ``group_generators``.

    The finite/infinite group implementation is selected by Sage.  This helper
    is only the coordinate crossing; the resulting matrix group is not an
    owned replacement for a mathematical subgroup already represented by the
    preamble.
    """
    from sage.groups.matrix_gps.finitely_generated import MatrixGroup

    generating_set = tuple(group_generators)
    if not generating_set:
        raise ValueError("a generated matrix group needs at least one generator")
    if any(not isinstance(generator, Matrix) for generator in generating_set):
        raise TypeError("a matrix group is generated by matrices")
    return MatrixGroup(generating_set)


__all__ = ["matrix_group", "row_normal_form"]
