r"""OSCAR routes through ``sage-julia-bridge``, run against the real engine.

Each test asks the owned lattice surface for an operation whose only
realization is OSCAR/Hecke, so the whole route is exercised: owned tensors
cross the bridge codec, OSCAR computes, and the result is crossed back into
owned isometries, subgroups and lattices.  When the bridge or its Julia
project is not provisioned, the capability registry refuses with the
provisioning remedy; nothing here substitutes another engine.
"""

from dzack_research.preamble.all import *


def test_rational_spinor_norm_sign_of_hyperbolic_plane_isometries() -> None:
    # Kneser's spinor norm of a reflection s_w is the square class of Q(w)
    # (Cassels, Rational Quadratic Forms, Ch. 10 §3).  On U with e.f = 1:
    # swap = s_{e-f} with Q(e-f) = -1; -1 = s_{e+f} s_{e-f} with product of
    # square classes (+1)(-1) = -1.  The owned character multiplies OSCAR's
    # sign by the determinant, so swap -> (-1)(-1) = +1 and -1 -> (-1)(+1) = -1.
    lattice = Lattices(ZZ)("U")
    e, f = lattice.module_generators()
    swap = lattice.Aut()((f, e))
    minus_identity = lattice.Aut()((-e, -f))

    assert swap.determinant() == -1
    assert swap.real_spinor_norm_sign() == 1
    assert minus_identity.determinant() == 1
    assert minus_identity.real_spinor_norm_sign() == -1


def test_centralizer_discriminant_image_of_negation_on_the_rank_one_even_lattice() -> None:
    # L = <4>: A_L = Z/4, and -1 acts nontrivially on A_L.  O(L) = {+-1},
    # so the centralizer of -1 is all of O(L), and its discriminant image is
    # the order-two group generated by negation.
    lattice = Lattices(ZZ)([[4]])
    (generator,) = lattice.module_generators()
    negation = lattice.Aut()((-generator,))

    image = negation.centralizer_discriminant_image()

    assert image.order() == 2
    assert image.supergroup() is lattice.discriminant_group().O()
    assert lattice.discriminant_group().O().order() == 2


def test_primitive_embedding_of_a1_into_the_even_unimodular_lattice_of_rank_8() -> None:
    # II_{8,0} is E8, the unique even unimodular positive definite lattice
    # of rank 8 (Serre, A Course in Arithmetic, Ch. V §2.3), with 240 roots
    # (Conway--Sloane, SPLAG, Ch. 4 §8.1).
    a1 = Lattices(ZZ)([[2]])

    embedding = a1.embed_in_even_unimodular(8, 0)
    target = embedding.codomain()

    assert embedding.domain() is a1
    assert embedding.is_primitive()
    assert target.module_rank() == 8
    assert target.determinant() == 1
    assert target.is_even()
    assert target.is_positive_definite()
    assert target.vectors_of_square(2).cardinality() == 240
    root = a1.module_generators()[0]
    assert embedding(root).q() == root.q()
