r"""OSCAR routes through ``sage-julia-bridge``, run against the real engine.

Each test asks the owned lattice surface for an operation whose only
realization is OSCAR/Hecke, so the whole route is exercised: owned tensors
cross the bridge codec, OSCAR computes, and the result is crossed back into
owned isometries, subgroups and lattices.  When the bridge or its Julia
project is not provisioned, the capability registry refuses with the
provisioning remedy; nothing here substitutes another engine.
"""

from dzack_research.preamble.all import Lattices, ZZ


def test_rational_spinor_norm_sign_of_hyperbolic_plane_isometries() -> None:
    # Kneser's spinor norm of a reflection s_w is the square class of Q(w)
    # (Cassels, Rational Quadratic Forms, Ch. 10 §3).  On U with e.f = 1:
    # swap = s_{e-f} with Q(e-f) = -1; -1 = s_{e+f} s_{e-f} with product of
    # square classes (+1)(-1) = -1.  The owned character multiplies OSCAR's
    # sign by the determinant, so swap -> (-1)(-1) = +1 and -1 -> (-1)(+1) = -1.
    lattice = Lattices(ZZ)("U")
    e, f = lattice.module_generators()
    swap = lattice.Aut()((f, e))
    minus_identity = lattice.Aut()((-e, -f))

    assert swap.determinant() == -1
    assert swap.real_spinor_norm_sign() == 1
    assert minus_identity.determinant() == 1
    assert minus_identity.real_spinor_norm_sign() == -1


def test_centralizer_discriminant_image_of_the_swap_on_a1_plus_a1() -> None:
    # L = <2> + <2>: A_L = (Z/2)^2 with q-values 1/2, 1/2, 1 (mod 2) on the
    # three nonzero classes, so O(A_L) is the transposition of the two
    # generator classes, of order 2.  The centralizer of the swap in O(L)
    # (the dihedral group of order 8) is {+-1, +-swap}; its image in O(A_L)
    # is generated by the image of swap, hence has order 2.
    lattice = Lattices(ZZ)([[2, 0], [0, 2]])
    e1, e2 = lattice.module_generators()
    swap = lattice.Aut()((e2, e1))

    image = swap.centralizer_discriminant_image()

    assert image.order() == 2
    assert image.supergroup() is lattice.discriminant_group().O()
    assert lattice.discriminant_group().O().order() == 2


def test_primitive_embedding_of_a1_into_the_even_unimodular_lattice_of_rank_8() -> None:
    # II_{8,0} is E8, the unique even unimodular positive definite lattice
    # of rank 8 (Serre, A Course in Arithmetic, Ch. V §2.3), with 240 roots
    # (Conway--Sloane, SPLAG, Ch. 4 §8.1).
    a1 = Lattices(ZZ)([[2]])

    embedding = a1.embed_in_even_unimodular(8, 0)
    target = embedding.codomain()

    assert embedding.domain() is a1
    assert embedding.is_primitive()
    assert target.module_rank() == 8
    assert target.determinant() == 1
    assert target.is_even()
    assert target.is_positive_definite()
    assert target.vectors_of_square(2).cardinality() == 240
    root = a1.module_generators().unrank(0)
    assert embedding(root).q() == root.q()
