r"""Isometries and automorphisms of the hyperbolic plane."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_the_hyperbolic_plane_is_isometric_to_its_negative_and_not_to_its_double() -> None:
    r"""``U = U(-1)`` by ``diag(1, -1)``; ``U != U(2)`` since ``det U = -1`` and ``det U(2) = -4``."""
    u = Lattices(ZZ)("U")
    negative = Lattices(ZZ)([[0, -1], [-1, 0]])
    doubled = Lattices(ZZ)([[0, 2], [2, 0]])
    e, f = u.basis()
    p, q = negative.basis()
    witness = u.Mor(negative)({e: p, f: -q})

    assert u.is_isometric_to(negative)
    assert witness.is_isometry()
    assert not u.is_isometric_to(doubled)
    assert u.determinant() == -1
    assert doubled.determinant() == -4


def test_the_orthogonal_group_of_the_hyperbolic_plane_is_the_klein_four_group() -> None:
    r"""``M^t G M = G`` for ``G = [[0, 1], [1, 0]]`` forces ``ac = bd = 0`` and ``ad + bc = 1``.

    The integral solutions are ``+-1`` and ``+-`` the swap, so ``O(U)`` is the
    Klein four-group: order 4, not cyclic, generated by ``-1`` and the swap.
    """
    u = Lattices(ZZ)("U")
    orthogonal_group = u.O()
    e, f = u.basis()
    minus_one = u.Mor(u)({e: -e, f: -f})
    swap = u.Mor(u)({e: f, f: e})

    assert orthogonal_group.cardinality() == 4
    assert orthogonal_group.is_isomorphic_to(Groups.C(2) * Groups.C(2))
    assert not orthogonal_group.is_isomorphic_to(Groups.C(4))
    assert orthogonal_group.subgroup((minus_one, swap)).cardinality() == 4
