r"""$R[G]$-modules: a module and an action, which is one thing.

Giving an $R$-module $M$ an action $\rho: G\to\operatorname{Aut}_R(M)$ is
giving $M$ an $R[G]$-module structure -- same data, same morphisms
($G$-equivariant $R$-maps *are* $R[G]$-maps), same category.  So this is not a
re-encoding of "module with a group action"; it is what that phrase means, and
the class below carries exactly the two things it names.

Freeness stays a fact about $R$.  A lattice of rank $22$ with a $G$-action is
essentially never free over $\mathbb Z[G]$, so what is asked of these objects is
that their restriction along $R\hookrightarrow R[G]$ be free of finite rank --
the same shape as a form module lying over a module, with restriction of
scalars in place of forgetting the form.

The supported scalar rings are $\mathbb Z$, $\mathbb Q$, $\mathbb R$, and
$\mathbb C$, and the supported groups are finite.  Isotypic decompositions add
their own semisimplicity and character-field assertions; they do not turn a
lattice inclusion into an endomorphism of the lattice.
"""

from typing import Any

from sage.categories.category_types import Category_over_base_ring
from sage.matrix.matrix0 import Matrix
from sage.rings.cc import CC
from sage.rings.integer_ring import ZZ
from sage.rings.rational_field import QQ
from sage.rings.real_mpfr import RR


_SUPPORTED_BASE_RINGS = (ZZ, QQ, RR, CC)


def _assert_supported_base_ring(base_ring: Any) -> None:
    assert base_ring in _SUPPORTED_BASE_RINGS, (
        "group modules currently require base ring ZZ, QQ, RR, or CC; "
        f"got {base_ring}"
    )


class GroupModules(Category_over_base_ring):
    r"""Category of $R[G]$-modules whose restriction to $R$ is free of finite rank."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "modules with a group action"

    def super_categories(self) -> list:
        return [FramedFreeModules(self.base_ring())]

    class ParentMethods:
        r"""What the action adds to being a free module."""

        def group(self: Any) -> Any:
            r"""Return $G$."""
            return self._group

        def action_of(self: Any, element: Any) -> Any:
            r"""Return $\rho(g)$ as an endomorphism of the underlying module."""
            return self._action[element]

        def action_matrix(self: Any, element: Any) -> Matrix:
            r"""Return the matrix of $\rho(g)$ in the chosen basis."""
            return self.action_of(element).matrix()

        def act(self: Any, element: Any, x: Any) -> Any:
            r"""Return $g\cdot x$."""
            return self.action_of(element)(x)

        def is_invariant(self: Any, x: Any) -> bool:
            r"""Return whether $g\cdot x = x$ for every $g$, i.e. $x\in M^G$."""
            return all(self.act(g, x) == x for g in self.group())

        def subobject_on(self: Any, generators: Any) -> Any:
            r"""Return the $G$-stable submodule generated by ``generators``."""
            return _group_subobject(self, generators)

        def hom(self: Any, images: Any, codomain: Any = None) -> Any:
            r"""Return the equivariant morphism with the prescribed images."""
            images = tuple(images)
            assert len(images) == self.rank(), (
                f"this module has {self.rank()} basis elements, got "
                f"{len(images)} images"
            )
            if not images:
                assert codomain is not None, (
                    "a morphism out of the zero module needs its codomain named"
                )
            else:
                codomain = images[0].parent()
            assert codomain.group() == self.group(), (
                "a morphism of group modules must use the same group on both "
                "sides"
            )
            return _equivariant_hom(self, codomain, list(images))

        def isotypic_decomposition(self: Any) -> "IsotypicDecomposition":
            r"""Return $M$ split along the irreducible characters of $G$."""
            return IsotypicDecomposition(self)

        def isotypic_component(self: Any, character: Any) -> Any:
            r"""Return the $\chi$-component, as a subobject of $M$."""
            return self.isotypic_decomposition().component(character)

        def multiplicity_space(self: Any, character: Any) -> Any:
            r"""Return the pure multiplicity space indexed by ``character``."""
            decomposition = (
                self
                if hasattr(self, "_multiplicity_space")
                else self.isotypic_decomposition()
            )
            return decomposition._multiplicity_space(character)

        def invariants(self: Any) -> Any:
            r"""Return $M^G$, as a subobject of $M$.

            This is the simultaneous kernel of $\rho(g)-1$, independently of
            semisimplicity or a character field.
            """
            return _group_subobject(self, _invariant_generators(self))

        def module_coinvariants(self: Any) -> Any:
            r"""Return the quotient module $M/I_GM$.

            The relations are the actual elements $(g-1)e_i$ for every group
            element and every chosen generator of $M$.  The result is a
            finitely presented module and need not be torsion.
            """
            return _module_coinvariants(self)


def _invariant_generators(module: Any) -> list:
    r"""Return a basis for $\bigcap_g\ker(\rho(g)-1)$ in ``module``."""
    ring = module.base_ring()
    constraints = matrix(
        ring,
        [
            row
            for element in module.group()
            for row in (
                module.action_matrix(element)
                - identity_matrix(ring, module.rank())
            ).rows()
        ],
    )
    return [
        module.linear_combination(row)
        for row in constraints.right_kernel().basis()
    ]


def _module_coinvariants(module: Any) -> Any:
    r"""Present $M/I_GM$ by the relations $(g-1)e_i$."""
    generators = tuple(module.gens())
    relations = [
        module.act(group_element, generator) - generator
        for group_element in module.group()
        for generator in generators
    ]
    relation_module = BasedFreeModule(
        module.base_ring(), standard_framing_set(len(relations))
    )
    if relations:
        presentation = _module_morphism(
            dict(zip(relation_module.gens(), relations))
        )
    else:
        presentation = ModuleMorphism.zero(relation_module, module)
    return FinitelyPresentedModule(presentation)


def _isotypic_generators(representation: Any, character: Any) -> list:
    r"""Return generators for $M\cap M_\chi$ in the original module.

    The central idempotent $e_\chi=\frac{\chi(1)}{|G|}\sum_g
    \chi(g^{-1})\rho(g)$ acts after the required scalar extension.  Its image
    is the $\chi$-part; for an integral module, intersecting back with the
    module is saturation.  The idempotent is an internal field-level
    computation, not an endomorphism promised on the lattice.

    Denominators are where the base ring matters.  The supported scalar rings
    are checked at module construction, and exact projector arithmetic is
    checked here before any image is used.
    """
    module = representation
    group = representation.group()
    size = group.order()
    field = _isotypic_field(module)
    try:
        degree = field(character(group.one()))
        terms = [
            field(character(g.inverse()))
            * matrix(field, representation.action_matrix(g))
            for g in group
        ]
    except (TypeError, ValueError, ArithmeticError):
        assert False, (
            f"the character values of {character} do not lie in {field}; "
            "choose a coefficient field containing them"
        )
    projector = sum(
        terms,
        matrix(field, module.rank(), module.rank()),
    )
    projector = (degree / field(size)) * projector
    assert projector * projector == projector, (
        "the coefficient field does not provide exact projector arithmetic; "
        "use an exact splitting field for the isotypic construction"
    )
    rows = projector.image().basis_matrix()
    if rows.nrows() == 0:
        return []
    if module.base_ring() is ZZ:
        cleared = matrix(ZZ, rows * rows.denominator())
        rows = cleared.saturation()
    return [module.linear_combination(row) for row in rows.rows()]


def _isotypic_field(module: Any) -> Any:
    r"""Return the exact field used for the character calculation."""
    return QQ if module.base_ring() is ZZ else module.base_ring()


def _fraction_field(base_ring: Any) -> Any:
    try:
        return base_ring.fraction_field()
    except (AttributeError, ValueError, NotImplementedError):
        return base_ring


def _restricted_action_matrices(module: Any, generators: list) -> list:
    r"""Return action matrices in the basis ``generators``."""
    base_ring = module.base_ring()
    if not generators:
        return [matrix(base_ring, 0, 0) for _ in module.group().gens()]

    field = _fraction_field(base_ring)
    embedding = matrix(
        field, [_coordinate_vector(generator) for generator in generators]
    )
    assert embedding.rank() == len(generators), "submodule generators are dependent"
    restricted = []
    for group_element in module.group().gens():
        images = matrix(
            field,
            [
                _coordinate_vector(module.act(group_element, generator))
                for generator in generators
            ],
        )
        coefficients = embedding.transpose().solve_right(images.transpose()).transpose()
        assert coefficients * embedding == images, (
            "the proposed submodule is not stable under the group action"
        )
        assert all(entry in base_ring for entry in coefficients.list()), (
            "the restricted action does not have coefficients in the module's base ring"
        )
        restricted.append(matrix(base_ring, coefficients))
    return restricted


def _restricted_action_automorphisms(module: Any, submodule: Any, generators: list) -> list:
    r"""Return the action on ``submodule`` by generator-image declarations."""
    if not generators:
        return [submodule.Aut()(()) for _ in module.group().gens()]
    base_ring = submodule.base_ring()
    field = _fraction_field(base_ring)
    embedding = matrix(
        field, [_coordinate_vector(generator) for generator in generators]
    )
    assert embedding.rank() == len(generators), "submodule generators are dependent"
    restricted = []
    for group_element in module.group().gens():
        images = matrix(
            field,
            [
                _coordinate_vector(module.act(group_element, generator))
                for generator in generators
            ],
        )
        coefficients = embedding.transpose().solve_right(images.transpose()).transpose()
        assert coefficients * embedding == images, (
            "the proposed submodule is not stable under the group action"
        )
        assert all(entry in base_ring for entry in coefficients.list()), (
            "the restricted action does not have coefficients in the module's base ring"
        )
        restricted.append(
            submodule.Aut()(
                [submodule.linear_combination(row) for row in coefficients.rows()]
            )
        )
    return restricted


def _equivariant_hom(domain: Any, codomain: Any, images: list) -> Any:
    r"""Build and verify a morphism of modules with group action."""
    assignment = dict(zip(domain.gens(), images))
    morphism = (
        _module_morphism(assignment)
        if assignment
        else ModuleMorphism.zero(domain, codomain)
    )
    for group_element in domain.group():
        for generator in domain.gens():
            assert morphism(domain.act(group_element, generator)) == codomain.act(
                group_element, morphism(generator)
            ), "the proposed morphism is not equivariant"
    return morphism


def _group_subobject(module: Any, generators: Any) -> Any:
    r"""Return a $G$-module subobject generated by ``generators``."""
    generators = _independent_generators(module, generators)
    submodule = BasedFreeModule(
        module.base_ring(), standard_framing_set(len(generators))
    )
    restricted = _restricted_action_automorphisms(module, submodule, generators)
    action = GroupAction.from_generators(module.group(), submodule, restricted)
    submodule = GroupModule(submodule, action)
    embedding = _equivariant_hom(submodule, module, generators)
    return Subobject(embedding)


class GroupModule(BasedFreeModule):
    r"""A free module with a $G$-action: an $R[G]$-module.

    Construct it as ``GroupModule(M, H)`` for a literal finite subgroup
    ``H <= Aut(M)``, or as ``GroupModule(M, G, rho)`` for a
    :class:`GroupAction` ``rho: G -> Aut(M)``.  The free module is the first
    argument; rings, ranks, matrices and abstract replacement groups are not
    accepted as action data.

    The action is $\rho$ on the group's elements -- a homomorphism into
    $\operatorname{Aut}_R(M)$, which is the datum -- and everything else, the
    matrices included, is read off it.  Its endomorphisms are endomorphisms of
    *this* object, not of a module it was built from: an $R[G]$-module is a
    free module with more structure, so a map of it starts and ends here.
    """

    def __init__(self, module: Any, group_or_action: Any, action: Any = None) -> None:
        assert isinstance(module, BasedFreeModule), (
            "a group module starts with the free module M, not a base ring and "
            "rank"
        )
        base_ring = module.base_ring()
        _assert_supported_base_ring(base_ring)
        if action is None and isinstance(group_or_action, ModuleAutomorphismGroup):
            assert group_or_action.module() is module, (
                "the subgroup must consist of automorphisms of the supplied M"
            )
            group = group_or_action
            values = {element: element for element in group}
        else:
            semantic_action = group_or_action if action is None else action
            assert isinstance(semantic_action, GroupAction), (
                "the action must be a semantic morphism into Aut(M), not raw "
                "matrices, a group, or numerical data"
            )
            group = semantic_action.domain()
            if action is not None:
                assert group is group_or_action, (
                    "the semantic action's domain must be the supplied group"
                )
            assert semantic_action.module() is module, (
                "the semantic action must land in Aut(M)"
            )
            values = semantic_action.values()
        assert group.is_finite(), (
            "group modules currently require a finite group; "
            f"got {group}"
        )
        source_values = values
        BasedFreeModule.__init__(self, base_ring, module.generating_set())
        self._group = group
        self._module = module
        self._action = {
            element: _transport_automorphism(automorphism, self)
            for element, automorphism in source_values.items()
        }
        refine(self, GroupModules(base_ring))

    def forget_action(self) -> BasedFreeModule:
        r"""Return the underlying $R$-module: restriction along $R\to R[G]$.

        Not "the module underneath": the $R[G]$-module lies over it, the way a
        form module lies over a module, and this is the functor that says so.
        A different object, with no action to ask about.
        """
        return self._module

    def __eq__(self, other: Any) -> bool:
        # Two actions on one module are two objects. Rank and base ring do not
        # decide it, and the inherited comparison would say they do.
        return self is other

    def __hash__(self) -> int:
        return id(self)


class IsotypicDecomposition(GroupModule):
    r"""The direct-sum $G$-module of isotypic pieces, included in $M$.

    The object returned by :meth:`GroupModules.ParentMethods.isotypic_decomposition`
    is itself a $G$-module.  Its ordered summands are the individual
    $M^\lambda$, and its structure morphism is the inclusion
    $\bigoplus_\lambda M^\lambda\hookrightarrow M$.  Over a semisimple field
    that inclusion is an isomorphism; over $\mathbb Z$ it can have finite index.
    """

    def __init__(self, representation: Any) -> None:
        group = representation.group()
        assert group.is_finite(), (
            "an isotypic decomposition is indexed by the irreducible characters "
            "of a finite group; this group is infinite"
        )
        base_ring = representation.base_ring()
        characteristic = base_ring.characteristic()
        assert characteristic == 0 or group.order() % characteristic != 0, (
            f"in characteristic {characteristic} dividing |G| = {group.order()} "
            "the group algebra is not semisimple, Maschke does not apply, and "
            "there is no decomposition into isotypic components to return"
        )

        characters = tuple(group.irreducible_characters())
        component_generators = tuple(
            tuple(_isotypic_generators(representation, character))
            for character in characters
        )
        generators = [
            generator
            for component in component_generators
            for generator in component
        ]
        decomposition_module = BasedFreeModule(
            base_ring, standard_framing_set(len(generators))
        )
        restricted = _restricted_action_automorphisms(
            representation, decomposition_module, generators
        )
        decomposition_action = GroupAction.from_generators(
            group, decomposition_module, restricted
        )
        GroupModule.__init__(self, decomposition_module, decomposition_action)
        self._source_module = representation
        self._characters = characters
        self._components = tuple(
            _group_subobject(representation, list(component))
            for component in component_generators
        )

        refine(self, [self.category(), DirectSumObjects()])
        offsets = [0]
        for component in component_generators:
            offsets.append(offsets[-1] + len(component))
        self._summands = tuple(
            self.subobject_on(self.gens()[start:stop])
            for start, stop in zip(offsets, offsets[1:])
        )
        embedding = _equivariant_hom(self, representation, generators)
        Subobject(embedding)

    def source_module(self) -> Any:
        r"""Return the module whose decomposition this is."""
        return self._source_module

    def components(self) -> tuple:
        r"""Return the isotypic summands as subobjects of the source module."""
        return self._components

    def characters(self) -> tuple:
        return self._characters

    def component(self, character: Any) -> Any:
        for candidate, component in zip(self._characters, self._components):
            if candidate == character:
                return component
        assert False, (
            f"{character} is not an irreducible character of {self.group()}"
        )

    def _multiplicity_space(self, character: Any) -> Any:
        r"""Return $\operatorname{Hom}_{K[G]}(V_\chi,M)$ by its character index.

        The returned object is the underlying pure free module.  For a lattice
        this is over $\mathbb Q$, since the isotypic calculation takes place
        after rationalization; the lattice component itself remains the
        inclusion returned by :meth:`component`.
        """
        component = self.component(character)
        degree = ZZ(character(self.group().one()))
        assert degree > 0, f"{character} has nonpositive degree {degree}"
        assert component.rank() % degree == 0, (
            f"the {character}-component has rank {component.rank()}, which is "
            f"not divisible by character degree {degree}"
        )
        return BasedFreeModule(
            _isotypic_field(self._source_module),
            standard_framing_set(component.rank() // degree),
        )

    def trivial_component(self) -> Any:
        r"""Return the trivial isotypic subobject of the source module."""
        return self.component(self.group().trivial_character())

    def nontrivial_components(self) -> tuple:
        trivial = self.trivial_component()
        return tuple(
            component for component in self._components if component is not trivial
        )

    def __iter__(self):
        return iter(self._components)

    def __len__(self) -> int:
        return len(self._components)

    def __repr__(self) -> str:
        ranks = tuple(component.rank() for component in self._components)
        return f"Isotypic decomposition with component ranks {ranks}"


def _transport_automorphism(automorphism: Any, target: Any) -> Any:
    r"""Transport an automorphism by declaring its images on ``target``'s basis."""
    source = automorphism.domain()
    assert source.base_ring() is target.base_ring()
    images = [
        target.linear_combination(_coordinate_vector(automorphism(generator)))
        for generator in source.gens()
    ]
    return target.Aut()(images)
