r"""Integral lattices equipped with a finite-group action by isometries."""

from typing import Self, TYPE_CHECKING

from sage.categories.category import Category
from sage.categories.morphism import SetMorphism

if TYPE_CHECKING:
    # The ordered-set noun is type-only: the preamble loads into one
    # shared namespace and nothing named OrderedSet may bind there.
    from sage_lattice_category_spike.lexicon import OrderedSet


class GroupLattices(Category):
    r"""The pullback of \(G\)-modules and integral lattices."""

    def __init__(self, group: "Group") -> None:
        assert group.is_finite(), "this category currently requires a finite group"
        self._group = group
        Category.__init__(self)

    def acting_group(self) -> "Group":
        return self._group

    def _repr_object_names(self) -> str:
        return f"integral lattices with an action of {self._group}"

    def super_categories(self) -> list:
        return [
            GroupModules(ZZ, self._group),
            IntegralLattices(),
        ]

    class ParentMethods:
        def Hom(self: Self, codomain: "Module", category: "Category" = None) -> "Homset":
            if codomain in GroupModules(self.base_ring(), self.group()):
                return group_lattice_homset(self, codomain)
            return Parent.Hom(self, codomain, category)

        def hom(self: Self, images: dict, codomain: "Module" = None) -> "ModuleMorphism":
            return FinitelyGeneratedFormModules.ParentMethods.hom(
                self,
                images,
                codomain,
            )

        def module_representation(self: Self) -> "Module":
            r"""Forget the form and retain the specified \(G\)-module."""
            return self.forget_form()

        @cached_method
        def forget_action(self: Self) -> "Module":
            r"""Forget the action and retain the formed module."""
            stored = self.__dict__.get("_action_forgotten_form")
            if stored is not None:
                return stored
            module = self.forget_form().forget_action()
            stored = FormModule(self.form().on_module(module))
            self._action_forgotten_form = stored
            return stored

        def action(self: Self) -> GroupAction:
            return self._formed_action

        def group(self: Self) -> "Group":
            return self._formed_action.domain()

        def action_of(self: Self, element: "Element") -> FormMorphism:
            return self._formed_action(element)

        def action_matrix(self: Self, element: "Element") -> "MorphismMatrix":
            return self.action_of(element).matrix()

        def act(self: Self, element: "Element", vector_: "ModuleElement") -> "ModuleElement":
            return self.action_of(element)(vector_)

        def is_invariant(self: Self, vector_: "ModuleElement") -> bool:
            return all(
                self.act(element, vector_) == vector_
                for element in self.group()
            )

        def subobject_on(self: Self, module_generators: "OrderedSet") -> "Subobject":
            module_generators = tuple(module_generators)
            assert all(generator.parent() is self for generator in module_generators), (
                "a subobject is generated by elements of this group lattice"
            )
            representation_subobject = self.module_representation().subobject_on(
                [generator.forget_form() for generator in module_generators]
            )
            return _formed_group_subobject(self, representation_subobject)

        def isotypic_decomposition(self: Self) -> "DirectSumObject":
            return self.module_representation().isotypic_decomposition()

        def isotypic_lattice(self: Self, character: "Character") -> "Subobject":
            return self._equip(
                self.isotypic_decomposition().summand(character)
            )

        @cached_method
        def invariant_lattice(self: Self) -> "Subobject":
            return self._equip(self.module_representation().module_invariants())

        @cached_method
        def coinvariant_lattice(self: Self) -> "Subobject":
            return self.invariant_lattice().embedding().orthogonal_complement()

        formed_coinvariants = coinvariant_lattice

        def _over_forgotten(self: Self, element: "Element") -> "Element":
            r"""Return the element of this \(G\)-lattice underlying ``element``.

            The inverse of :meth:`ElementMethods.forget_action`: forgetting
            the action does not change which elements there are, so the two
            are a bijection and this is the other half of it.
            """
            assert element.parent() is self.forget_action(), (
                f"{element} is not an element of {self.forget_action()}"
            )
            return self._over(self.forget_form()._over(element.forget_form()))

        def _equip(self: Self, submodule: "Module") -> "Module":
            assert submodule.embedding_codomain() is self.module_representation(), (
                "the group submodule belongs to a different representation"
            )
            return _formed_group_subobject(self, submodule)

    class ElementMethods:
        def forget_action(self: Self) -> "Module":
            lattice = self.parent().forget_action()
            return lattice._over(
                self.forget_form().forget_action()
            )



class GroupLatticeHomset(FormHomset):
    r"""Form-preserving equivariant maps of two lattices for one \(G\)."""

    def __init__(self, domain: "Module", codomain: "Module") -> None:
        assert codomain in GroupLattices(domain.group()), (
            "the codomain is not a lattice for the stated group"
        )
        assert domain.group() is codomain.group(), (
            "a group-lattice homset has one specified acting group"
        )
        FormHomset.__init__(
            self,
            domain,
            codomain,
            GroupLattices(domain.group()),
        )

    def _element_constructor_(self, images: dict) -> FormMorphism:
        match images:
            case FormMorphism():
                assert images.parent() is self, (
                    "an existing group-lattice morphism belongs to its own homset"
                )
                return images
            case ModuleMorphism() | SetMorphism() | dict():
                morphism = FormHomset._element_constructor_(self, images)
            case _ if callable(images):
                morphism = FormHomset._element_constructor_(self, images)
            case _:
                assert False, (
                    "a group-lattice morphism is specified by its generator "
                    "morphism or finite generator assignment"
                )
        assert all(
            morphism(
                self.domain().act(
                    group_element,
                    self.domain().module_generator(element_of_S),
                )
            )
            == self.codomain().act(
                group_element,
                morphism(self.domain().module_generator(element_of_S)),
            )
            for group_element in self.domain().group()
            for element_of_S in self.domain().module_generating_set()
        ), "the proposed lattice map is not equivariant"
        return morphism

    def _repr_(self) -> str:
        return (
            f"Isometric Hom_{self.domain().group()}("
            f"{self.domain()}, {self.codomain()})"
        )


def group_lattice_homset(domain: "Module", codomain: "Module") -> GroupLatticeHomset:
    r"""Return the canonical form-preserving equivariant homset."""
    cache = domain.__dict__.setdefault("_group_lattice_homsets", {})
    homset = cache.get(codomain)
    if homset is None:
        homset = GroupLatticeHomset(domain, codomain)
        cache[codomain] = homset
    return homset


def _action_preserves_form(formed_module: "Module") -> bool:
    module = formed_module.forget_form()
    return all(
        formed_module.form().pullback(module.action_of(element))
        == formed_module.form()
        for element in module.group()
    )


def _install_group_lattice_structure(formed_module: "Module") -> None:
    r"""Install the action on a formed \(G\)-module after invariance is known."""
    module = formed_module.forget_form()
    group = module.group()
    isometries = formed_module.Aut()
    values = {
        element: isometries(
            {
                label: formed_module._over(
                    module.action_of(element)(module.module_generator(label))
                )
                for label in module.module_generating_set()
            }
        )
        for element in group
    }
    formed_module._formed_action = group_action_homset(
        group,
        formed_module,
    )(values)


def _formed_group_subobject(
    group_lattice_: "Lattice",
    representation_subobject: "Subobject",
) -> "Subobject":
    r"""Equip a \(G\)-submodule with the pulled-back form and its inclusion."""
    module_embedding = representation_subobject.embedding()
    representation = module_embedding.domain()
    restricted = FormModule(
        group_lattice_.form().pullback(module_embedding)
    )
    assert restricted in GroupLattices(group_lattice_.group()), (
        "a stable submodule of a group lattice must inherit the isometric action"
    )
    embedding = restricted.Hom(group_lattice_)(
        {
            label: group_lattice_._over(
                module_embedding(representation.module_generator(label))
            )
            for label in representation.module_generating_set()
        }
    )
    return Subobject(embedding)


def group_lattice(lattice: "Lattice", action: GroupAction) -> FormModule:
    r"""Equip ``lattice`` with the specified action by isometries."""
    assert lattice in IntegralLattices(), (
        "a group lattice is constructed from an actual integral lattice"
    )
    assert (
        isinstance(action, GroupAction)
        and action.module() is lattice
        and action.parent() is group_action_homset(action.domain(), lattice)
    ), "the action must be an element of the lattice's action homset"

    module = lattice.forget_form()
    automorphisms = module.Aut()
    values = {
        element: automorphisms(
            {
                label: action(element)(
                    lattice.module_generator(label)
                ).forget_form()
                for label in module.module_generating_set()
            }
        )
        for element in action.domain()
    }
    representation = GroupModule(
        module,
        group_action_homset(action.domain(), module)(values),
    )
    formed_module = FormModule(
        lattice.form().on_module(representation)
    )
    assert formed_module in GroupLattices(action.domain()), (
        "the supplied action did not refine to isometries"
    )
    formed_module._action_forgotten_form = lattice
    return formed_module
