r"""Integral lattices equipped with a finite-group action by isometries."""

from typing import Any

from sage.categories.category import Category


class GroupLattices(Category):
    r"""The pullback of \(G\)-modules and integral lattices."""

    def __init__(self, group: Any) -> None:
        assert group.is_finite(), "this category currently requires a finite group"
        self._group = group
        Category.__init__(self)

    def acting_group(self) -> Any:
        return self._group

    def _repr_object_names(self) -> str:
        return f"integral lattices with an action of {self._group}"

    def super_categories(self) -> list:
        return [
            GroupModules(ZZ, self._group),
            IntegralLattices(),
        ]

    class ParentMethods:
        def Hom(self: Any, codomain: Any) -> Any:
            return group_lattice_homset(self, codomain)

        def hom(self: Any, images: Any, codomain: Any = None) -> Any:
            return FinitelyGeneratedFormModules.ParentMethods.hom(
                self,
                images,
                codomain,
            )

        def module_representation(self: Any) -> Any:
            r"""Forget the form and retain the specified \(G\)-module."""
            return self.forget_form()

        @cached_method
        def forget_action(self: Any) -> Any:
            r"""Forget the action and retain the formed module."""
            stored = self.__dict__.get("_action_forgotten_form")
            if stored is not None:
                return stored
            module = self.forget_form().forget_action()
            stored = FormModule(self.form().on_module(module))
            self._action_forgotten_form = stored
            return stored

        def action(self: Any) -> GroupAction:
            return self._formed_action

        def group(self: Any) -> Any:
            return self._formed_action.domain()

        def action_of(self: Any, element: Any) -> FormMorphism:
            return self._formed_action(element)

        def action_matrix(self: Any, element: Any) -> Any:
            return self.action_of(element).matrix()

        def act(self: Any, element: Any, vector_: Any) -> Any:
            return self.action_of(element)(vector_)

        def is_invariant(self: Any, vector_: Any) -> bool:
            return all(
                self.act(element, vector_) == vector_
                for element in self.group()
            )

        def subobject_on(self: Any, generators: Any) -> Any:
            generators = tuple(generators)
            assert all(generator.parent() is self for generator in generators), (
                "a subobject is generated by elements of this group lattice"
            )
            representation_subobject = self.module_representation().subobject_on(
                [generator.forget_form() for generator in generators]
            )
            return _formed_group_subobject(self, representation_subobject)

        def isotypic_decomposition(self: Any) -> Any:
            return self.module_representation().isotypic_decomposition()

        def isotypic_lattice(self: Any, character: Any) -> Any:
            return self._equip(
                self.isotypic_decomposition().summand(character)
            )

        @cached_method
        def invariant_lattice(self: Any) -> Any:
            return self._equip(self.module_representation().invariants())

        @cached_method
        def coinvariant_lattice(self: Any) -> Any:
            return self.invariant_lattice().embedding().orthogonal_complement()

        formed_coinvariants = coinvariant_lattice

        def _equip(self: Any, submodule: Any) -> Any:
            assert submodule.embedding_codomain() is self.module_representation(), (
                "the group submodule belongs to a different representation"
            )
            return _formed_group_subobject(self, submodule)

    class ElementMethods:
        def forget_action(self: Any) -> Any:
            lattice = self.parent().forget_action()
            return lattice._over(
                self.forget_form().forget_action()
            )


class GroupLatticeHomset(FormHomset):
    r"""Form-preserving equivariant maps of two lattices for one \(G\)."""

    def __init__(self, domain: Any, codomain: Any) -> None:
        assert codomain in GroupLattices(domain.group()), (
            "the codomain is not a lattice for the stated group"
        )
        assert domain.group() is codomain.group(), (
            "a group-lattice homset has one specified acting group"
        )
        FormHomset.__init__(
            self,
            domain,
            codomain,
            GroupLattices(domain.group()),
        )

    def _element_constructor_(self, images: Any) -> FormMorphism:
        match images:
            case FormMorphism():
                assert images.parent() is self, (
                    "an existing group-lattice morphism belongs to its own homset"
                )
                return images
            case _:
                morphism = FormHomset._element_constructor_(self, images)
        for group_element in self.domain().group():
            for label in self.domain().generating_set():
                generator = self.domain().generator(label)
                assert morphism(
                    self.domain().act(group_element, generator)
                ) == self.codomain().act(
                    group_element,
                    morphism(generator),
                ), "the proposed lattice map is not equivariant"
        return morphism

    def _repr_(self) -> str:
        return (
            f"Isometric Hom_{self.domain().group()}("
            f"{self.domain()}, {self.codomain()})"
        )


def group_lattice_homset(domain: Any, codomain: Any) -> GroupLatticeHomset:
    r"""Return the canonical form-preserving equivariant homset."""
    cache = domain.__dict__.setdefault("_group_lattice_homsets", {})
    homset = cache.get(codomain)
    if homset is None:
        homset = GroupLatticeHomset(domain, codomain)
        cache[codomain] = homset
    return homset


def _action_preserves_form(formed_module: Any) -> bool:
    module = formed_module.forget_form()
    return all(
        formed_module.form().pullback(module.action_of(element))
        == formed_module.form()
        for element in module.group()
    )


def _install_group_lattice_structure(formed_module: Any) -> None:
    r"""Install the action on a formed \(G\)-module after invariance is known."""
    module = formed_module.forget_form()
    group = module.group()
    isometries = formed_module.Aut()
    values = {
        element: isometries(
            {
                label: formed_module._over(
                    module.action_of(element)(module.generator(label))
                )
                for label in module.generating_set()
            }
        )
        for element in group
    }
    formed_module._formed_action = group_action_homset(
        group,
        formed_module,
    )(values)


def _formed_group_subobject(
    group_lattice_: Any,
    representation_subobject: Any,
) -> Any:
    r"""Equip a \(G\)-submodule with the pulled-back form and its inclusion."""
    representation = representation_subobject.underlying_object()
    module_embedding = representation_subobject.embedding()
    restricted = FormModule(
        group_lattice_.form().pullback(module_embedding)
    )
    assert restricted in GroupLattices(group_lattice_.group()), (
        "a stable submodule of a group lattice must inherit the isometric action"
    )
    embedding = restricted.Hom(group_lattice_)(
        {
            label: group_lattice_._over(
                module_embedding(representation.generator(label))
            )
            for label in representation.generating_set()
        }
    )
    return Subobject(embedding)


def group_lattice(lattice: Any, action: GroupAction) -> FormModule:
    r"""Equip ``lattice`` with the specified action by isometries."""
    assert lattice in IntegralLattices(), (
        "a group lattice is constructed from an actual integral lattice"
    )
    assert (
        isinstance(action, GroupAction)
        and action.module() is lattice
        and action.parent() is group_action_homset(action.domain(), lattice)
    ), "the action must be an element of the lattice's action homset"

    module = lattice.forget_form()
    automorphisms = module.Aut()
    values = {
        element: automorphisms(
            {
                label: action(element)(
                    lattice.generator(label)
                ).forget_form()
                for label in module.generating_set()
            }
        )
        for element in action.domain()
    }
    representation = GroupModule(
        module,
        group_action_homset(action.domain(), module)(values),
    )
    formed_module = FormModule(
        lattice.form().on_module(representation)
    )
    assert formed_module in GroupLattices(action.domain()), (
        "the supplied action did not refine to isometries"
    )
    formed_module._action_forgotten_form = lattice
    return formed_module
