r"""Public session vocabulary and rejected legacy operation globals.

These are mathematical constructors deliberately used by the construction and
archive proof surfaces.  The session exports owner/category/specimen names, but
does not publish owner-in-argument operations as free functions.
"""

import dzack_research.preamble.all as session
from dzack_research.preamble.all import (
    AdicCompletions,
    DividedPowerAlgebraOf,
    DividedPowerAlgebraOn,
    DividedPowerAlgebras,
    OwnedCategoryOverBaseRing,
    QuadraticMap,
    finite_ordered_set,
    ring_morphism,
)


def test_terminal_collection_vocabulary_is_public() -> None:
    names = (
        AdicCompletions,
        DividedPowerAlgebraOf,
        DividedPowerAlgebraOn,
        DividedPowerAlgebras,
        OwnedCategoryOverBaseRing,
        QuadraticMap,
        finite_ordered_set,
        ring_morphism,
    )

    assert all(name is not None for name in names)


def test_owner_in_argument_universal_operations_are_not_session_globals() -> None:
    forbidden = (
        "Biproduct",
        "Coproduct",
        "Product",
        "Pushout",
        "TensorProduct",
        "TensorSquare",
        "InternalHom",
        "Ext",
        "Tor",
        "ExtMap",
        "TorMap",
        "Kernel",
        "Cokernel",
        "Equalizer",
        "Coequalizer",
        "EqualizerOfFamily",
        "CoequalizerOfFamily",
        "FiberProduct",
        "Subobjects",
        "Core",
        "ProductConstruction",
        "CoproductConstruction",
        "EqualizerConstruction",
        "CoequalizerConstruction",
        "FractionField",
        "Localization",
        "PrimeLocalization",
        "QuotientRing",
        "ResidueField",
        "AdicCompletion",
        "Ideal",
        "OppositeCategory",
        "ProductCategory",
        "SliceOver",
        "CosliceUnder",
        "SubobjectsOf",
        "SuperobjectsOf",
        "CoveringObjectsOf",
        "CoveredObjectsOf",
        "ArrowCategory",
        "FunctorCategory",
        "HomCategoryOf",
        "EndCategoryOf",
        "MonoCategoryOf",
        "EpiCategoryOf",
        "IsoCategoryOf",
        "AutCategoryOf",
        "SliceCategory",
        "CosliceCategory",
        "SubobjectCategory",
        "SuperobjectCategory",
        "CoveringObjectCategory",
        "CoveredObjectCategory",
        "CochainComplex",
        "CochainComplexFromFamily",
        "Cycles",
        "Boundaries",
        "Cohomology",
        "cochain_homset",
        "algebra_homset",
        "are_in_one_stable_orbit",
        "cohomology_algebra_homset",
        "covering_discriminant_classes",
        "cusps",
        "cyclotomic_summand",
        "eichler_criterion_applies",
        "dga_homset",
        "graded_algebra_homset",
        "group_homset",
        "hyperbolic_plane_summand_count",
        "g_set_homset",
        "lie_algebra_homset",
        "isometry_primitive_extension",
        "lorentzian_reduction_complex",
        "module_localization_functor",
        "primitive_isotropic",
        "primitive_isotropic_vectors",
        "splits_two_hyperbolic_planes",
        "subobject_image_adjunction",
        "tensor_hom_adjunction",
        "transport_isotropic_object",
        "vector_configuration",
        "commutative_algebra_coproduct",
        "commutative_algebra_pushout",
        "centralizer",
        "predicate_subgroup",
        "DeRhamAlgebra",
        "KahlerDifferentials",
        "NaturalTransformations",
        "NaturalIsomorphism",
        "compose_functors",
        "category_inclusion",
        "induced_hom_functor",
        "induced_end_functor",
        "induced_aut_functor",
        "CategoryInclusionFunctor",
        "InducedHomFunctor",
        "InducedEndFunctor",
        "InducedAutFunctor",
    )

    assert all(not hasattr(session, name) for name in forbidden)
