# Repo-scoped stubs; see lexicon/README.md.
from collections.abc import Iterator

from sage.categories.rings import Rings
from sage.groups.abelian_gps.values import AbelianGroupWithValues_class
from sage.rings.integer import Integer
from sage.rings.finite_rings.integer_mod import IntegerMod_abstract

class IntegerModRing_generic(Rings.ParentMethods[IntegerMod_abstract]):
    def __iter__(self) -> Iterator[IntegerMod_abstract]: ...
    def zero(self) -> IntegerMod_abstract: ...
    def one(self) -> IntegerMod_abstract: ...
    def order(self) -> Integer: ...
    def unit_group(self) -> AbelianGroupWithValues_class: ...

def IntegerModRing(order: int | Integer = ...) -> IntegerModRing_generic: ...

# Module-level documented alias.
Integers = IntegerModRing
