# Repo-scoped stubs; see lexicon/README.md.
#
# V/W is the presentation: the module IS the quotient V/W of free modules
# over the PID, so V() and W() are the two data it is built from and every
# coordinate bridge to Sage goes through them.
from collections.abc import Iterable, Iterator

from sage.categories.modules import Modules
from sage.modules.fg_pid.fgp_element import FGP_Element
from sage.modules.fg_pid.fgp_morphism import FGP_Morphism
from sage.modules.free_module import FreeModule_generic
from sage.rings.ideal import Ideal_pid
from sage.rings.integer import Integer
from sage.structure.element import Element

class FGP_Module_class(Modules.ParentMethods[FGP_Element]):
    def V(self) -> FreeModule_generic: ...
    def W(self) -> FreeModule_generic: ...
    def gens(self) -> tuple[FGP_Element, ...]: ...
    def gen(self, i: int | Integer = ...) -> FGP_Element: ...
    def ngens(self) -> int: ...
    def zero(self) -> FGP_Element: ...
    def invariants(self, include_ones: bool = ...) -> tuple[Integer, ...]: ...
    def cardinality(self) -> Integer: ...
    # Finite iff no invariant is 0.
    def is_finite(self) -> bool: ...
    # Morphism sending gens() to im_gens; a FreeModule_generic codomain is
    # first quotiented by its zero submodule.
    def hom(
        self,
        im_gens: Iterable[Element],
        codomain: FGP_Module_class | FreeModule_generic | None = ...,
        check: bool = ...,
    ) -> FGP_Morphism: ...
    # The ideal of the base ring annihilating the module (the exponent, as an
    # ideal of the PID).
    def annihilator(self) -> Ideal_pid: ...
    def submodule(self, x: Iterable[Element] | FreeModule_generic) -> FGP_Module_class: ...
    def is_submodule(self, A: FGP_Module_class) -> bool: ...
    def __iter__(self) -> Iterator[FGP_Element]: ...
    def __contains__(self, x: object) -> bool: ...
