"""A corpus is valid exactly when the statements of a record about other records agree with those records."""

from fractions import Fraction
from pathlib import Path

import pytest
import yaml
from latticedb import arithmetic, corpus, records
from latticedb.model import Yaml


def rank_one(tag: str) -> dict[str, Yaml]:
    """The lattice <1> of rank 1 with b(e_1, e_1) = 1: its two vectors of norm 1 are roots of type A1 at scale 1/2."""
    return {
        "tag": tag,
        "name": "<1>",
        "latex": r"\langle 1 \rangle",
        "rank": 1,
        "gram_tensor": [[1]],
        "signature": [1, 0],
        "determinant": 1,
        "definiteness": "positive_definite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "odd", "discriminant_group": [], "overlattice_count": 1},
        "definite": {
            "minimum": 1,
            "kissing_number": 2,
            "theta_series": [1, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0],
            "root_system": [],
            "roots": [{"type": "A1", "scale": "1/2", "simple_roots": [[1]]}],
        },
    }


def hyperbolic_plane(summands: list[dict[str, str | int]]) -> dict[str, Yaml]:
    """U with its roots (1, 1) and (1, -1), which have b(r, r) = 2 and b(r, r) = -2 and are orthogonal: they generate <1>(2) + <1>(-2)."""
    return {
        "tag": "0016",
        "name": "U",
        "latex": "U",
        "rank": 2,
        "gram_tensor": [[0, 1], [1, 0]],
        "signature": [1, 1],
        "determinant": -1,
        "definiteness": "indefinite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "even", "discriminant_group": [], "overlattice_count": 1},
        "indefinite": {"isotropic": True},
        "root_span": {"roots": [[1, 1], [1, -1]], "summands": summands, "embedding": [[1, 1], [1, -1]]},
    }


FAMILIES = {"root-lattice": "Generated by its roots.", "even-unimodular": "Even, of determinant $\\pm 1$."}
RETIRED = {"000Z": "<3> = <1>(3)"}


def write(root: Path, *records: dict[str, Yaml]) -> Path:
    """A corpus under `root`: the records under `lattices/`, `FAMILIES` as its families and `RETIRED` as its retired tags."""
    (root / corpus.FAMILIES_FILE).write_text(yaml.safe_dump(FAMILIES))
    (root / corpus.RETIRED_FILE).write_text(yaml.safe_dump(RETIRED))
    (root / "lattices").mkdir()
    for record in records:
        (root / "lattices" / f"{record['tag']}.md").write_text("---\n" + yaml.safe_dump(record) + "---\n\nA test record.\n")
    return root


def test_a_root_span_is_accepted_when_its_embedding_has_the_gram_tensor_of_the_sum_of_its_summands(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"), hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]))
    assert [entry.lattice.tag for entry in corpus.load(directory).entries] == ["0001", "0016"]


def test_a_root_span_is_rejected_when_its_summands_are_not_isometric_to_the_image_of_its_embedding(tmp_path: Path) -> None:
    # <2> + <2> is positive definite, and the sublattice of U that (1, 1) and (1, -1) generate is <2> + <-2>.
    directory = write(tmp_path, rank_one("0001"), hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": 2}]))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def test_a_root_span_is_rejected_when_a_summand_is_not_a_record_of_the_corpus(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"), hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0008", "scale": -2}]))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def test_a_record_is_accepted_when_each_of_its_families_is_listed_and_rejected_when_one_is_not(tmp_path: Path) -> None:
    listed = rank_one("0001") | {"families": ["root-lattice", "even-unimodular"]}
    plane = hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]) | {"families": ["root-lattice"]}
    directory = write(tmp_path, listed, plane)
    assert [entry.lattice.families for entry in corpus.load(directory).entries] == [("root-lattice", "even-unimodular"), ("root-lattice",)]

    unlisted = rank_one("0001") | {"families": ["root-lattice", "hexagonal", "laminated"]}
    (directory / "lattices" / "0001.md").write_text("---\n" + yaml.safe_dump(unlisted) + "---\n\nA test record.\n")
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 2


def test_a_record_cannot_take_a_retired_tag_and_the_next_tag_counts_the_retired_ones(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"))
    loaded = corpus.load(directory)
    assert loaded.retired == RETIRED
    assert corpus.next_tag(loaded) == "0010"

    (directory / "lattices" / "000Z.md").write_text("---\n" + yaml.safe_dump(hyperbolic_plane([]) | {"tag": "000Z"}) + "---\n\nA test record.\n")
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert [problem for problem in raised.value.problems if "000Z" in problem and "retired" in problem]


def test_the_families_file_is_read_as_one_line_of_meaning_per_family(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0002"))
    assert corpus.load(directory).families == FAMILIES

    (directory / corpus.FAMILIES_FILE).write_text(yaml.safe_dump({"Root Lattice": "A family whose name is not lower-case with hyphens."}))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def rank_three(tag: str, name: str, gram_tensor: list[list[int]]) -> dict[str, Yaml]:
    """A3 or D3 in its basis of simple roots: the same lattice, since A3 and D3 are isometric."""
    return {
        "tag": tag,
        "name": name,
        "latex": name,
        "rank": 3,
        "gram_tensor": gram_tensor,
        "signature": [3, 0],
        "determinant": 4,
        "definiteness": "positive_definite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "even", "discriminant_group": [4], "overlattice_count": 2},
        "definite": {
            "minimum": 2,
            "kissing_number": 12,
            "theta_series": [1, 0, 12, 0, 6, 0, 24, 0, 12, 0, 24, 0, 8],
            "root_system": ["A3"],
            "roots": [{"type": "C3", "scale": 1, "simple_roots": [[0, 1, 0], [0, 0, 1], [1, 0, -1]] if name == "A3" else [[0, 0, 1], [0, 1, 0], [1, -1, 0]]}],
        },
    }


def test_two_definite_records_that_are_isometric_in_different_bases_are_rejected(tmp_path: Path) -> None:
    a3 = rank_three("0002", "A3", [[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    d3 = rank_three("0003", "D3", [[2, 0, -1], [0, 2, -1], [-1, -1, 2]])
    directory = write(tmp_path, a3, d3)
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1
    assert "0002" in raised.value.problems[0] and raised.value.problems[0].startswith(str(directory / "lattices" / "0003.md"))


def test_isometry_of_definite_lattices_is_decided_on_the_gram_tensors() -> None:
    a3 = tuple(tuple(Fraction(value) for value in row) for row in [[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    d3 = tuple(tuple(Fraction(value) for value in row) for row in [[2, 0, -1], [0, 2, -1], [-1, -1, 2]])
    assert arithmetic.is_isometric(a3, d3)
    # Both of determinant 3, positive definite: <1> + <3> has a vector of norm 1 and A2 does not.
    diagonal = ((Fraction(1), Fraction(0)), (Fraction(0), Fraction(3)))
    a2 = ((Fraction(2), Fraction(1)), (Fraction(1), Fraction(2)))
    assert not arithmetic.is_isometric(diagonal, a2)
    # A2 and its scaling by 1/2 have different least denominators.
    assert not arithmetic.is_isometric(a2, tuple(tuple(value / 2 for value in row) for row in a2))


def square_sum() -> dict[str, Yaml]:
    """<1> + <1>, with the fields that its Gram tensor determines computed by `records.derive`."""
    declared: dict[str, Yaml] = {"tag": "0002", "name": "<1>^2", "latex": r"\langle 1 \rangle^2", "gram_tensor": [[1, 0], [0, 1]], "provenance": {"source": "Test record."}}
    return records.derive(declared)


def write_morphisms(root: Path, source: str, target: str, morphisms: list[dict[str, Yaml]], stem: str | None = None) -> Path:
    """The file `morphisms/<stem>.md` under `root`, with `<source>-<target>` as the stem unless another is given."""
    (root / "morphisms").mkdir(exist_ok=True)
    (root / "morphisms" / f"{stem or f'{source}-{target}'}.md").write_text(records.morphisms_text(source, target, morphisms, "Test morphisms."))
    return root


VALID_U = [{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]


def morphism_problems(tmp_path: Path, source: str, target: str, morphisms: list[dict[str, Yaml]], stem: str | None = None) -> tuple[str, ...]:
    directory = write_morphisms(write(tmp_path, rank_one("0001"), square_sum(), hyperbolic_plane(VALID_U)), source, target, morphisms, stem)
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    return raised.value.problems


def test_the_identity_and_the_exchange_of_e_and_f_are_morphisms_of_u(tmp_path: Path) -> None:
    morphisms: list[dict[str, Yaml]] = [{"name": "identity", "matrix": [[1, 0], [0, 1]]}, {"name": "exchange", "matrix": [[0, 1], [1, 0]]}]
    directory = write_morphisms(write(tmp_path, rank_one("0001"), hyperbolic_plane(VALID_U)), "0016", "0016", morphisms)
    (loaded,) = corpus.load(directory).morphisms
    assert [morphism.name for morphism in loaded.morphisms.morphisms] == ["identity", "exchange"]


def test_the_inclusion_of_a_summand_is_a_morphism_whose_lines_cut_orthogonal_summands(tmp_path: Path) -> None:
    morphisms: list[dict[str, Yaml]] = [{"name": "first summand", "matrix": [[1], [0]], "row_subdivisions": [1]}]
    directory = write_morphisms(write(tmp_path, rank_one("0001"), square_sum()), "0001", "0002", morphisms)
    (loaded,) = corpus.load(directory).morphisms
    assert loaded.morphisms.morphisms[0].images == ((1, 0),)


def test_a_matrix_that_does_not_preserve_the_forms_is_rejected(tmp_path: Path) -> None:
    # The image of f is 2f, so b(e, f) = 1 goes to b(e, 2f) = 2.
    (problem,) = morphism_problems(tmp_path, "0016", "0016", [{"name": "scaling", "matrix": [[1, 0], [0, 2]]}])
    assert "does not preserve the forms" in problem


def test_a_matrix_whose_shape_is_not_the_ranks_of_target_and_source_is_rejected(tmp_path: Path) -> None:
    (problem,) = morphism_problems(tmp_path, "0016", "0016", [{"name": "short", "matrix": [[1, 0]]}])
    assert "2 rows and 2 columns" in problem


def test_a_line_that_cuts_u_is_rejected_because_e_and_f_are_not_orthogonal(tmp_path: Path) -> None:
    (problem,) = morphism_problems(tmp_path, "0016", "0016", [{"name": "identity", "matrix": [[1, 0], [0, 1]], "row_subdivisions": [1]}])
    assert "row_subdivisions are not orthogonal summands of the target" in problem


def test_a_morphism_file_is_rejected_when_a_tag_is_not_in_the_corpus_or_is_retired(tmp_path: Path) -> None:
    problems = morphism_problems(tmp_path, "0003", "000Z", [{"name": "identity", "matrix": [[1]]}])
    assert sorted(problems) == sorted(
        [
            f"{tmp_path / 'morphisms' / '0003-000Z.md'}: the tag 0003 is not in the corpus",
            f"{tmp_path / 'morphisms' / '0003-000Z.md'}: the tag 000Z is retired ({RETIRED['000Z']})",
        ]
    )


def test_a_morphism_file_is_rejected_when_its_name_is_not_source_dash_target(tmp_path: Path) -> None:
    (problem,) = morphism_problems(tmp_path, "0016", "0016", [{"name": "identity", "matrix": [[1, 0], [0, 1]]}], stem="0016-0001")
    assert "the file name must be 0016-0016" in problem
