"""A corpus is valid exactly when the statements of a record about other records agree with those records."""

from fractions import Fraction
from pathlib import Path

import pytest
import yaml
from latticedb import arithmetic, corpus
from latticedb.model import Yaml


def rank_one(tag: str, value: int) -> dict[str, Yaml]:
    """The lattice of rank 1 with b(e_1, e_1) = value, for value = 2 or value = -2."""
    return {
        "tag": tag,
        "name": f"<{value}>",
        "latex": rf"\langle {value} \rangle",
        "rank": 1,
        "gram_tensor": [[value]],
        "signature": [1, 0] if value > 0 else [0, 1],
        "determinant": value,
        "definiteness": "positive_definite" if value > 0 else "negative_definite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "even", "discriminant_group": [2]},
        "definite": {
            "minimum": 2,
            "kissing_number": 2,
            "theta_series": [1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
            "root_system": ["A1"],
            "roots": [{"type": "A1", "scale": value // 2, "simple_roots": [[1]]}],
        },
    }


def hyperbolic_plane(summands: list[str]) -> dict[str, Yaml]:
    """U with its roots (1, 1) and (1, -1), which have b(r, r) = 2 and b(r, r) = -2 and are orthogonal."""
    return {
        "tag": "0016",
        "name": "U",
        "latex": "U",
        "rank": 2,
        "gram_tensor": [[0, 1], [1, 0]],
        "signature": [1, 1],
        "determinant": -1,
        "definiteness": "indefinite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "even", "discriminant_group": []},
        "indefinite": {"isotropic": True},
        "root_span": {"roots": [[1, 1], [1, -1]], "summands": summands, "embedding": [[1, 1], [1, -1]]},
    }


FAMILIES = {"root-lattice": "Generated by its roots.", "even-unimodular": "Even, of determinant $\\pm 1$."}


def write(root: Path, *records: dict[str, Yaml]) -> Path:
    """A corpus under `root`: the records under `lattices/`, and `FAMILIES` as its families."""
    (root / corpus.FAMILIES_FILE).write_text(yaml.safe_dump(FAMILIES))
    (root / "lattices").mkdir()
    for record in records:
        (root / "lattices" / f"{record['tag']}.md").write_text("---\n" + yaml.safe_dump(record) + "---\n\nA test record.\n")
    return root


def test_a_root_span_is_accepted_when_its_embedding_has_the_gram_tensor_of_the_sum_of_its_summands(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0002", 2), rank_one("0008", -2), hyperbolic_plane(["0002", "0008"]))
    assert [entry.lattice.tag for entry in corpus.load(directory).entries] == ["0002", "0008", "0016"]


def test_a_root_span_is_rejected_when_its_summands_are_not_isometric_to_the_image_of_its_embedding(tmp_path: Path) -> None:
    # <2> + <2> is positive definite, and the sublattice of U that (1, 1) and (1, -1) generate is <2> + <-2>.
    directory = write(tmp_path, rank_one("0002", 2), rank_one("0008", -2), hyperbolic_plane(["0002", "0002"]))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def test_a_root_span_is_rejected_when_a_summand_is_not_a_record_of_the_corpus(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0002", 2), hyperbolic_plane(["0002", "0008"]))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def test_a_record_is_accepted_when_each_of_its_families_is_listed_and_rejected_when_one_is_not(tmp_path: Path) -> None:
    listed = rank_one("0002", 2) | {"families": ["root-lattice", "even-unimodular"]}
    directory = write(tmp_path, listed, rank_one("0008", -2) | {"families": ["root-lattice"]})
    assert [entry.lattice.families for entry in corpus.load(directory).entries] == [("root-lattice", "even-unimodular"), ("root-lattice",)]

    unlisted = rank_one("0002", 2) | {"families": ["root-lattice", "hexagonal", "laminated"]}
    (directory / "lattices" / "0002.md").write_text("---\n" + yaml.safe_dump(unlisted) + "---\n\nA test record.\n")
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 2


def test_the_families_file_is_read_as_one_line_of_meaning_per_family(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0002", 2))
    assert corpus.load(directory).families == FAMILIES

    (directory / corpus.FAMILIES_FILE).write_text(yaml.safe_dump({"Root Lattice": "A family whose name is not lower-case with hyphens."}))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def rank_three(tag: str, name: str, gram_tensor: list[list[int]]) -> dict[str, Yaml]:
    """A3 or D3 in its basis of simple roots: the same lattice, since A3 and D3 are isometric."""
    return {
        "tag": tag,
        "name": name,
        "latex": name,
        "rank": 3,
        "gram_tensor": gram_tensor,
        "signature": [3, 0],
        "determinant": 4,
        "definiteness": "positive_definite",
        "provenance": {"source": "Test record."},
        "integral": {"parity": "even", "discriminant_group": [4]},
        "definite": {
            "minimum": 2,
            "kissing_number": 12,
            "theta_series": [1, 0, 12, 0, 6, 0, 24, 0, 12, 0, 24, 0, 8],
            "root_system": ["A3"],
            "roots": [{"type": "C3", "scale": 1, "simple_roots": [[0, 1, 0], [0, 0, 1], [1, 0, -1]] if name == "A3" else [[0, 0, 1], [0, 1, 0], [1, -1, 0]]}],
        },
    }


def test_two_definite_records_that_are_isometric_in_different_bases_are_rejected(tmp_path: Path) -> None:
    a3 = rank_three("0002", "A3", [[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    d3 = rank_three("0003", "D3", [[2, 0, -1], [0, 2, -1], [-1, -1, 2]])
    directory = write(tmp_path, a3, d3)
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1
    assert "0002" in raised.value.problems[0] and raised.value.problems[0].startswith(str(directory / "lattices" / "0003.md"))


def test_isometry_of_definite_lattices_is_decided_on_the_gram_tensors() -> None:
    a3 = tuple(tuple(Fraction(value) for value in row) for row in [[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    d3 = tuple(tuple(Fraction(value) for value in row) for row in [[2, 0, -1], [0, 2, -1], [-1, -1, 2]])
    assert arithmetic.is_isometric(a3, d3)
    # Both of determinant 3, positive definite: <1> + <3> has a vector of norm 1 and A2 does not.
    diagonal = ((Fraction(1), Fraction(0)), (Fraction(0), Fraction(3)))
    a2 = ((Fraction(2), Fraction(1)), (Fraction(1), Fraction(2)))
    assert not arithmetic.is_isometric(diagonal, a2)
    # A2 and its scaling by 1/2 have different least denominators.
    assert not arithmetic.is_isometric(a2, tuple(tuple(value / 2 for value in row) for row in a2))
