"""A corpus is valid exactly when the tags, families and file names that its records name exist and are unique."""

from fractions import Fraction
from pathlib import Path

import frontmatter
import pytest
import yaml

from latticedb import checks, cli, corpus, records, summands
from latticedb.model import Yaml


def rank_one(tag: str) -> dict[str, Yaml]:
    """The lattice <1> of rank 1 with b(e_1, e_1) = 1: its two vectors of norm 1 are roots of type A1 at scale 1/2."""
    return {
        "tag": tag,
        "name": "<1>",
        "latex": r"\langle 1 \rangle",
        "rank": 1,
        "gram_tensor": [[1]],
        "signature": [1, 0],
        "determinant": 1,
        "definiteness": "positive_definite",
        "integral": {
            "parity": "odd",
            "discriminant_group": [],
            "overlattice_count": 1,
            "bad_reduction_primes": [2],
        },
        "definite": {
            "minimum": 1,
            "kissing_number": 2,
            "theta_series": [1, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0],
            "root_system": [],
            "roots": [{"type": "A1", "scale": "1/2", "simple_roots": [[1]]}],
        },
        "root_sublattice": {"invariant_factors": [1], "norms": [1]},
    }


def hyperbolic_plane(summands: list[dict[str, str | int]]) -> dict[str, Yaml]:
    """U with its roots (1, 1) and (1, -1), which have b(r, r) = 2 and b(r, r) = -2 and are orthogonal: they generate <1>(2) + <1>(-2)."""
    return {
        "tag": "0016",
        "name": "U",
        "latex": "U",
        "rank": 2,
        "gram_tensor": [[0, 1], [1, 0]],
        "signature": [1, 1],
        "determinant": -1,
        "definiteness": "indefinite",
        "integral": {
            "parity": "even",
            "discriminant_group": [],
            "overlattice_count": 1,
            "delta": 0,
            "bad_reduction_primes": [2],
            "quadratic_character": 1,
        },
        "indefinite": {"isotropic": True},
        "root_span": {
            "roots": [[1, 1], [1, -1]],
            "norms": [2, -2],
            "summands": summands,
            "embedding": [[1, 1], [1, -1]],
        },
        "root_sublattice": {"invariant_factors": [1, 2]},
    }


FAMILIES = {
    "root-lattice": "Generated by its roots.",
    "even-unimodular": "Even, of determinant $\\pm 1$.",
}
RETIRED = {"000Z": "<3> = <1>(3)"}


def write(root: Path, *records: dict[str, Yaml]) -> Path:
    """A corpus under `root`: the records under `lattices/`, `FAMILIES` as its families and `RETIRED` as its retired tags."""
    (root / corpus.FAMILIES_FILE).write_text(yaml.safe_dump(FAMILIES))
    (root / corpus.RETIRED_FILE).write_text(yaml.safe_dump(RETIRED))
    (root / "lattices").mkdir()
    for record in records:
        (root / "lattices" / f"{record['tag']}.md").write_text("---\n" + yaml.safe_dump(record) + "---\n\nA test record.\n")
    return root


def test_a_root_span_is_accepted_when_its_embedding_has_the_gram_tensor_of_the_sum_of_its_summands(
    tmp_path: Path,
) -> None:
    directory = write(
        tmp_path,
        rank_one("0001"),
        hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]),
    )
    assert [entry.lattice.tag for entry in corpus.load(directory).entries] == [
        "0001",
        "0016",
    ]


def test_a_root_span_is_rejected_when_a_summand_is_not_a_record_of_the_corpus(
    tmp_path: Path,
) -> None:
    directory = write(
        tmp_path,
        rank_one("0001"),
        hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0008", "scale": -2}]),
    )
    assert len(checks.report(directory)) == 1


def test_a_record_is_accepted_when_each_of_its_families_is_listed_and_rejected_when_one_is_not(
    tmp_path: Path,
) -> None:
    listed = rank_one("0001") | {"families": ["root-lattice", "even-unimodular"]}
    plane = hyperbolic_plane([{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]) | {"families": ["root-lattice"]}
    directory = write(tmp_path, listed, plane)
    assert [entry.lattice.families for entry in corpus.load(directory).entries] == [
        ("root-lattice", "even-unimodular"),
        ("root-lattice",),
    ]

    unlisted = rank_one("0001") | {"families": ["root-lattice", "hexagonal", "laminated"]}
    (directory / "lattices" / "0001.md").write_text("---\n" + yaml.safe_dump(unlisted) + "---\n\nA test record.\n")
    assert len(checks.report(directory)) == 2


def test_a_record_cannot_take_a_retired_tag_and_the_next_tag_counts_the_retired_ones(
    tmp_path: Path,
) -> None:
    directory = write(tmp_path, rank_one("0001"))
    loaded = corpus.load(directory)
    assert loaded.retired == RETIRED
    assert corpus.next_tag(directory) == "0010"

    (directory / "lattices" / "000Z.md").write_text("---\n" + yaml.safe_dump(hyperbolic_plane([]) | {"tag": "000Z"}) + "---\n\nA test record.\n")
    assert [problem for problem in checks.report(directory) if "000Z" in problem and "retired" in problem]


def test_next_tag_starts_an_empty_corpus_at_0001(tmp_path: Path) -> None:
    (tmp_path / "lattices").mkdir()
    (tmp_path / corpus.RETIRED_FILE).write_text("{}\n")
    assert corpus.next_tag(tmp_path) == "0001"


def test_source_cards_do_not_reserve_tags_and_verify_reports_them(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"))
    source = directory / "lattices" / "source"
    source.mkdir()
    (source / "0010.md").write_text("---\ntag: '0010'\nkind: source\n---\n")
    assert corpus.next_tag(directory) == "0010"
    assert any("source card has not been seeded" in problem for problem in checks.report(directory))

    (source / "0001.md").write_text("---\ntag: '0001'\nkind: source\n---\n")
    assert any("also assigned to a source card" in problem for problem in checks.report(directory))


def test_the_families_file_is_read_as_one_line_of_meaning_per_family(
    tmp_path: Path,
) -> None:
    directory = write(tmp_path, rank_one("0002"))
    assert corpus.load(directory).families == FAMILIES

    (directory / corpus.FAMILIES_FILE).write_text(yaml.safe_dump({"Root Lattice": "A family whose name is not lower-case with hyphens."}))
    with pytest.raises(corpus.CorpusInvalid) as raised:
        corpus.load(directory)
    assert len(raised.value.problems) == 1


def square_sum() -> dict[str, Yaml]:
    """<1> + <1>, with the fields that its Gram tensor determines computed by `records.derive`."""
    declared: dict[str, Yaml] = {
        "tag": "0002",
        "name": "<1>^2",
        "latex": r"\langle 1 \rangle^2",
        "gram_tensor": [[1, 0], [0, 1]],
    }
    return records.derive(declared)


def write_morphisms(
    root: Path,
    source: str,
    target: str,
    morphisms: list[dict[str, Yaml]],
) -> Path:
    """Store morphisms with domain `source` on that lattice card."""
    path = root / "lattices" / f"{source}.md"
    document = frontmatter.load(str(path))
    metadata = corpus.front_matter(document)
    metadata["morphisms"] = [
        *metadata.get("morphisms", []),
        *({"target": target, **morphism} for morphism in morphisms),
    ]
    path.write_text(records.record_text(metadata, document.content))
    return root


VALID_U = [{"tag": "0001", "scale": 2}, {"tag": "0001", "scale": -2}]


def morphism_problems(
    tmp_path: Path,
    source: str,
    target: str,
    morphisms: list[dict[str, Yaml]],
) -> tuple[str, ...]:
    directory = write_morphisms(
        write(tmp_path, rank_one("0001"), square_sum(), hyperbolic_plane(VALID_U)),
        source,
        target,
        morphisms,
    )
    return checks.report(directory)


def test_the_identity_and_the_exchange_of_e_and_f_are_morphisms_of_u(
    tmp_path: Path,
) -> None:
    morphisms: list[dict[str, Yaml]] = [
        {"name": "identity", "matrix": [[1, 0], [0, 1]]},
        {"name": "exchange", "matrix": [[0, 1], [1, 0]]},
    ]
    directory = write_morphisms(
        write(tmp_path, rank_one("0001"), hyperbolic_plane(VALID_U)),
        "0016",
        "0016",
        morphisms,
    )
    loaded = next(entry.lattice for entry in corpus.load(directory).entries if entry.lattice.tag == "0016")
    assert [morphism.name for morphism in loaded.morphisms] == [
        "identity",
        "exchange",
    ]


def test_the_inclusion_of_a_summand_is_a_morphism_whose_lines_cut_orthogonal_summands(
    tmp_path: Path,
) -> None:
    morphisms: list[dict[str, Yaml]] = [{"name": "first summand", "matrix": [[1], [0]], "row_subdivisions": [1]}]
    directory = write_morphisms(write(tmp_path, rank_one("0001"), square_sum()), "0001", "0002", morphisms)
    source = next(entry.lattice for entry in corpus.load(directory).entries if entry.lattice.tag == "0001")
    assert source.morphisms[0].images == ((1, 0),)


def test_the_summands_of_1_plus_1_give_its_inclusion_once_and_its_diagonal_at_scale_2(
    tmp_path: Path,
) -> None:
    stated: list[dict[str, Yaml]] = [{"name": "first summand", "matrix": [[1], [0]]}]
    directory = write_morphisms(write(tmp_path, rank_one("0001"), square_sum()), "0001", "0002", stated)
    assert summands.store(directory, corpus.load(directory)) == []
    assert summands.store(directory, corpus.load(directory)) == []

    loaded = next(entry.lattice for entry in corpus.load(directory).entries if entry.lattice.tag == "0001")
    morphisms = tuple(morphism for morphism in loaded.morphisms if morphism.target == "0002")
    assert [(morphism.matrix, morphism.scale) for morphism in morphisms] == [
        (((1,), (0,)), 1),
        (((1,), (1,)), 2),
    ]
    assert morphisms[1].name == "Diagonal into the summands $\\{1, 2\\}$"


def test_a_morphism_is_rejected_when_its_target_is_not_in_the_corpus_or_is_retired(
    tmp_path: Path,
) -> None:
    retired_root = tmp_path / "retired"
    retired_root.mkdir()
    retired = morphism_problems(retired_root, "0001", "000Z", [{"name": "identity", "matrix": [[1]]}])
    assert retired == (f"{retired_root / 'lattices' / '0001.md'}: morphism target 000Z is retired ({RETIRED['000Z']})",)
    missing_root = tmp_path / "missing"
    missing_root.mkdir()
    missing = morphism_problems(missing_root, "0001", "0003", [{"name": "identity", "matrix": [[1]]}])
    assert missing == (f"{missing_root / 'lattices' / '0001.md'}: morphism target 0003 is not in the corpus",)


def test_duplicate_grams_lists_the_tags_that_share_a_gram_tensor(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"), rank_one("0002"), hyperbolic_plane([]))
    loaded = corpus.load(directory)
    assert corpus.duplicate_grams(loaded.entries) == {((Fraction(1),),): ["0001", "0002"]}


def test_verification_reports_two_cards_stating_one_gram_tensor(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"), rank_one("0002"), hyperbolic_plane([]))
    assert "cards 0001, 0002 state one Gram tensor; a lattice has one card" in checks.report(directory)


def test_duplicate_grams_is_empty_when_every_gram_tensor_is_held_once(tmp_path: Path) -> None:
    directory = write(tmp_path, rank_one("0001"), hyperbolic_plane([]))
    assert corpus.duplicate_grams(corpus.load(directory).entries) == {}


def test_gram_index_lists_the_tags_stating_each_tensor(tmp_path: Path) -> None:
    (tmp_path / "lattices").mkdir()
    (tmp_path / "lattices" / "0001.md").write_text("---\ngram_tensor:\n- [2]\n---\n")
    (tmp_path / "lattices" / "0002.md").write_text("---\ngram_tensor:\n- [2]\n---\n")
    (tmp_path / "lattices" / "0003.md").write_text("---\nname: sparse\n---\n")
    assert corpus.gram_index(tmp_path) == {"2": ["0001", "0002"]}
    (tmp_path / "lattices" / "0004.md").write_text("---\ngram_tensor:\n- [2]\n---\n")
    corpus.append_index(tmp_path, "0004", ((Fraction(2),),))
    assert corpus.gram_index(tmp_path) == {"2": ["0001", "0002", "0004"]}


def test_new_refuses_a_gram_tensor_the_corpus_holds(tmp_path: Path) -> None:
    (tmp_path / "lattices").mkdir()
    (tmp_path / "lattices" / "0001.md").write_text("---\ngram_tensor:\n- [2]\n---\n")
    (tmp_path / corpus.RETIRED_FILE).write_text("{}\n")
    with pytest.raises(SystemExit):
        cli.new(gram="[[2]]", name="X", latex="X", root=tmp_path)
    assert [path.name for path in sorted((tmp_path / "lattices").glob("*.md"))] == ["0001.md"]


def test_new_writes_a_fresh_gram_tensor_and_appends_the_index(tmp_path: Path) -> None:
    (tmp_path / "lattices").mkdir()
    (tmp_path / "lattices" / "0001.md").write_text("---\ngram_tensor:\n- [2]\n---\n")
    (tmp_path / corpus.RETIRED_FILE).write_text("{}\n")
    cli.new(gram="[[3]]", name="X", latex="X", root=tmp_path)
    assert (tmp_path / "lattices" / "0002.md").exists()
    assert corpus.gram_index(tmp_path) == {"2": ["0001"], "3": ["0002"]}
