# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.structure.element import Matrix

def block_diagonal_matrix(*blocks: Any, **kwds: Any) -> Matrix: ...
def identity_matrix(ring: Any, n: Any = ..., sparse: bool = ...) -> Matrix: ...
def diagonal_matrix(ring: Any, entries: Any = ..., sparse: bool = ...) -> Matrix: ...
