# Repo-scoped stubs; see lexicon/README.md. The lexicon noun ``MatrixGroup``
# (INVENTORY.md II.2): a finitely generated matrix group behind the GAP seam.
from collections.abc import Iterator

from sage.groups.matrix_gps.group_element import MatrixGroupElement_gap
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.rings.integer import Integer
from sage.structure.parent import Parent

class FinitelyGeneratedMatrixGroup_gap(Parent[MatrixGroupElement_gap]):
    def as_permutation_group(self, algorithm: str | None = ..., seed: int | None = ...) -> PermutationGroup_generic: ...
    def order(self) -> Integer: ...
    def gens(self) -> tuple[MatrixGroupElement_gap, ...]: ...
    # Supplied by ParentLibGAP: a finitely generated group knows how many
    # generators it was presented with.
    def ngens(self) -> int: ...
    def is_finite(self) -> bool: ...
    def structure_description(self) -> str: ...
    def conjugacy_classes_representatives(self) -> tuple[MatrixGroupElement_gap, ...]: ...
    def list(self) -> list[MatrixGroupElement_gap]: ...
    def __iter__(self) -> Iterator[MatrixGroupElement_gap]: ...
    def __contains__(self, x: object) -> bool: ...
