# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.rings.integer import Integer

class Polyhedron_base:
    def is_compact(self) -> bool: ...
    def dim(self) -> Integer: ...
    def vertices(self) -> tuple[Any, ...]: ...
    def rays(self) -> tuple[Any, ...]: ...
    def volume(self, measure: Any = ..., engine: Any = ...) -> Any: ...
