'Owned algebra categories and native-backed free constructions.'

from importlib import import_module as _import_module

_EXPORTS = {'AlgebraHomset': ('dzack_research.preamble.categories.algebras.algebras', 'AlgebraHomset'),
 'AlgebraMorphism': ('dzack_research.preamble.categories.algebras.algebras', 'AlgebraMorphism'),
 'Algebras': ('dzack_research.preamble.categories.algebras.algebras', 'Algebras'),
 'AlgebrasWithChosenFinitePresentation': ('dzack_research.preamble.categories.algebras.algebras',
                                          'AlgebrasWithChosenFinitePresentation'),
 'AlgebrasWithChosenMultiplication': ('dzack_research.preamble.categories.algebras.algebras',
                                      'AlgebrasWithChosenMultiplication'),
 'AssociativeAlgebras': ('dzack_research.preamble.categories.algebras.algebras',
                         'AssociativeAlgebras'),
 'AssociativeAlgebrasWithChosenMultiplication': ('dzack_research.preamble.categories.algebras.algebras',
                                                 'AssociativeAlgebrasWithChosenMultiplication'),
 'CommutativeAlgebraCoproducts': ('dzack_research.preamble.categories.algebras.algebras',
                                  'CommutativeAlgebraCoproducts'),
 'CommutativeAlgebraPushouts': ('dzack_research.preamble.categories.algebras.algebras',
                                'CommutativeAlgebraPushouts'),
 'CommutativeAlgebras': ('dzack_research.preamble.categories.algebras.algebras',
                         'CommutativeAlgebras'),
 'CyclicCoverAlgebra': ('dzack_research.preamble.categories.algebras.cyclic_cover_algebras',
                        'CyclicCoverAlgebra'),
 'FinitelyPresentedAlgebras': ('dzack_research.preamble.categories.algebras.algebras',
                               'FinitelyPresentedAlgebras'),
 'FramedAlgebras': ('dzack_research.preamble.categories.algebras.algebras', 'FramedAlgebras'),
 'MatrixAlgebras': ('dzack_research.preamble.categories.algebras.algebras', 'MatrixAlgebras'),
 'OwnedAlgebras': ('dzack_research.preamble.categories.algebras.algebras', 'OwnedAlgebras'),
 'finite_algebra_generators': ('dzack_research.preamble.categories.algebras.algebras',
                               'finite_algebra_generators'),
 'refine_algebra': ('dzack_research.preamble.categories.algebras.algebras', 'refine_algebra'),
 'refine_matrix_algebra': ('dzack_research.preamble.categories.algebras.algebras',
                           'refine_matrix_algebra'),
 'CommutatorLieAlgebras': ('dzack_research.preamble.categories.algebras.lie_algebras',
                           'CommutatorLieAlgebras'),
 'LieAlgebraHomset': ('dzack_research.preamble.categories.algebras.lie_algebras',
                      'LieAlgebraHomset'),
 'LieAlgebraMorphism': ('dzack_research.preamble.categories.algebras.lie_algebras',
                        'LieAlgebraMorphism'),
 'LieAlgebras': ('dzack_research.preamble.categories.algebras.lie_algebras', 'LieAlgebras'),
 'AlternatingAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                         'AlternatingAlgebras'),
 'DividedPowerAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                          'DividedPowerAlgebras'),
 'FinitelyPresentedAlgebra': ('dzack_research.preamble.categories.algebras.free_algebras',
                              'FinitelyPresentedAlgebra'),
 'FreeAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras', 'FreeAlgebras'),
 'GradedFreeAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                        'GradedFreeAlgebras'),
 'SymmetricAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                       'SymmetricAlgebras'),
 'TensorAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras', 'TensorAlgebras'),
 'AlternatingAlgebraOn': ('dzack_research.preamble.categories.algebras.power_algebras',
                          'AlternatingAlgebraOn'),
 'DividedPowerAlgebraOn': ('dzack_research.preamble.categories.algebras.power_algebras',
                           'DividedPowerAlgebraOn'),
 'FreeAlgebraOn': ('dzack_research.preamble.categories.algebras.free_algebras',
                   'FreeAlgebraOn'),
 'SymmetricAlgebraOn': ('dzack_research.preamble.categories.algebras.free_algebras',
                        'SymmetricAlgebraOn'),
 'TensorAlgebraOn': ('dzack_research.preamble.categories.algebras.free_algebras',
                     'TensorAlgebraOn'),
 'polynomial_ring': ('dzack_research.preamble.categories.algebras.framed_free_algebras',
                     'polynomial_ring'),
 'PowerAlgebra': ('dzack_research.preamble.categories.algebras.power_algebras', 'PowerAlgebra'),
 'PowerAlgebraHomset': ('dzack_research.preamble.categories.algebras.power_algebras',
                        'PowerAlgebraHomset'),
 'PowerAlgebraMorphism': ('dzack_research.preamble.categories.algebras.power_algebras',
                          'PowerAlgebraMorphism'),
 'FinitelyPresentedAlgebraOn': ('dzack_research.preamble.categories.algebras.finitely_presented_algebras',
                                'FinitelyPresentedAlgebraOn'),
 'AugmentedAlgebras': ('dzack_research.preamble.categories.algebras.augmented_algebras',
                       'AugmentedAlgebras'),
 'GradedAugmentedAlgebras': ('dzack_research.preamble.categories.algebras.augmented_algebras',
                             'GradedAugmentedAlgebras'),
 'AffineSemigroupAlgebra': ('dzack_research.preamble.categories.algebras.semigroup_algebras',
                            'AffineSemigroupAlgebra'),
 'AffineSemigroupAlgebras': ('dzack_research.preamble.categories.algebras.semigroup_algebras',
                             'AffineSemigroupAlgebras'),
 'GroupAlgebra': ('dzack_research.preamble.categories.algebras.group_algebras', 'GroupAlgebra'),
 'GroupAlgebraFunctor': ('dzack_research.preamble.categories.algebras.group_algebras',
                         'GroupAlgebraFunctor'),
 'GroupAlgebraUnderlyingModuleFunctor': ('dzack_research.preamble.categories.algebras.group_algebras',
                                         'GroupAlgebraUnderlyingModuleFunctor'),
 'GroupAlgebras': ('dzack_research.preamble.categories.algebras.group_algebras', 'GroupAlgebras'),
 'FreeModuleOnGroupFunctor': ('dzack_research.preamble.categories.algebras.group_algebras',
                              'FreeModuleOnGroupFunctor'),
 'GradedAlgebraHomset': ('dzack_research.preamble.categories.algebras.graded_algebras',
                         'GradedAlgebraHomset'),
 'GradedAlgebraMorphism': ('dzack_research.preamble.categories.algebras.graded_algebras',
                           'GradedAlgebraMorphism'),
 'GradedAlgebras': ('dzack_research.preamble.categories.algebras.graded_algebras',
                    'GradedAlgebras'),
 'GradedCommutativeAlgebras': ('dzack_research.preamble.categories.algebras.graded_commutative_algebras',
                               'GradedCommutativeAlgebras'),
 'StrictlyGradedCommutativeAlgebras': ('dzack_research.preamble.categories.algebras.graded_commutative_algebras',
                                       'StrictlyGradedCommutativeAlgebras'),
 'RestrictedScalarsAlgebras': ('dzack_research.preamble.categories.algebras.restricted_scalars',
                               'RestrictedScalarsAlgebras'),
 'Derivation': ('dzack_research.preamble.categories.algebras.derivations', 'Derivation'),
 'DerivationSpace': ('dzack_research.preamble.categories.algebras.derivations', 'DerivationSpace'),
 'GradedDerivation': ('dzack_research.preamble.categories.algebras.derivations',
                      'GradedDerivation'),
 'GradedDerivationSpace': ('dzack_research.preamble.categories.algebras.derivations',
                           'GradedDerivationSpace'),
 'KahlerDifferentialModules': ('dzack_research.preamble.categories.algebras.kahler_differentials',
                               'KahlerDifferentialModules'),
 'RestrictedGradedAlgebra': ('dzack_research.preamble.categories.algebras.restricted_graded_algebras',
                             'RestrictedGradedAlgebra'),
 'RestrictedGradedAlgebraElement': ('dzack_research.preamble.categories.algebras.restricted_graded_algebras',
                                    'RestrictedGradedAlgebraElement'),
 'CommutativeDifferentialGradedAlgebras': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                           'CommutativeDifferentialGradedAlgebras'),
 'DGAHomset': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
               'DGAHomset'),
 'DGAMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                 'DGAMorphism'),
 'DegreewiseLinearMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                              'DegreewiseLinearMorphism'),
 'Differential': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                  'Differential'),
 'DifferentialComponentMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                   'DifferentialComponentMorphism'),
 'DifferentialGradedAlgebras': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                'DifferentialGradedAlgebras'),
 'StrictlyCommutativeDifferentialGradedAlgebras': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                                   'StrictlyCommutativeDifferentialGradedAlgebras'),
 'DeRhamAlgebras': ('dzack_research.preamble.categories.algebras.de_rham_algebras',
                    'DeRhamAlgebras'),
 'CohomologyAlgebra': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                       'CohomologyAlgebra'),
 'CohomologyAlgebraElement': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                              'CohomologyAlgebraElement'),
 'CohomologyAlgebraHomset': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                             'CohomologyAlgebraHomset'),
 'CohomologyAlgebraMorphism': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                               'CohomologyAlgebraMorphism'),
 'CohomologyAlgebras': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                        'CohomologyAlgebras')}

__all__ = ['AugmentedAlgebras',
 'AffineSemigroupAlgebra',
 'AffineSemigroupAlgebras',
 'AlgebraHomset',
 'AlgebraMorphism',
 'Algebras',
 'AlgebrasWithChosenMultiplication',
 'AssociativeAlgebras',
 'AssociativeAlgebrasWithChosenMultiplication',
 'CommutativeAlgebraCoproducts',
 'CommutativeAlgebraPushouts',
 'CommutativeAlgebras',
 'CommutatorLieAlgebras',
 'CyclicCoverAlgebra',
 'CommutativeDifferentialGradedAlgebras',
 'CohomologyAlgebra',
 'CohomologyAlgebraElement',
 'CohomologyAlgebraHomset',
 'CohomologyAlgebraMorphism',
 'CohomologyAlgebras',
 'AlgebrasWithChosenFinitePresentation',
 'AlternatingAlgebraOn',
 'AlternatingAlgebras',
 'DividedPowerAlgebraOn',
 'DividedPowerAlgebras',
 'Derivation',
 'DerivationSpace',
 'GradedDerivation',
 'GradedDerivationSpace',
 'LieAlgebraHomset',
 'LieAlgebraMorphism',
 'LieAlgebras',
 'DeRhamAlgebras',
 'DGAHomset',
 'DGAMorphism',
 'DegreewiseLinearMorphism',
 'Differential',
 'DifferentialComponentMorphism',
 'DifferentialGradedAlgebras',
 'FramedAlgebras',
 'FinitelyPresentedAlgebra',
 'FinitelyPresentedAlgebraOn',
 'FinitelyPresentedAlgebras',
 'OwnedAlgebras',
 'PowerAlgebra',
 'PowerAlgebraHomset',
 'PowerAlgebraMorphism',
 'KahlerDifferentialModules',
 'RestrictedScalarsAlgebras',
 'RestrictedGradedAlgebra',
 'RestrictedGradedAlgebraElement',
 'FreeAlgebraOn',
 'FreeAlgebras',
 'GradedAlgebras',
 'GradedAlgebraHomset',
 'GradedAlgebraMorphism',
 'GradedCommutativeAlgebras',
 'GradedAugmentedAlgebras',
 'GroupAlgebra',
 'GroupAlgebraFunctor',
 'GroupAlgebraUnderlyingModuleFunctor',
 'GroupAlgebras',
 'FreeModuleOnGroupFunctor',
 'GradedFreeAlgebras',
 'SymmetricAlgebraOn',
 'SymmetricAlgebras',
 'TensorAlgebraOn',
 'TensorAlgebras',
 'StrictlyGradedCommutativeAlgebras',
 'StrictlyCommutativeDifferentialGradedAlgebras',
 'finite_algebra_generators',
 'polynomial_ring',
 'refine_algebra',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
