'Owned algebra categories and native-backed free constructions.'

from importlib import import_module as _import_module

_EXPORTS = {'AlgebraMor': ('dzack_research.preamble.categories.algebras.algebras', 'AlgebraMor'),
 'AlgebraMorphism': ('dzack_research.preamble.categories.algebras.algebras', 'AlgebraMorphism'),
 'Algebras': ('dzack_research.preamble.categories.algebras.algebras', 'Algebras'),
 'AlgebrasWithChosenFinitePresentation': ('dzack_research.preamble.categories.algebras.algebras',
                                          'AlgebrasWithChosenFinitePresentation'),
 'CommutativeAlgebraCoproducts': ('dzack_research.preamble.categories.algebras.algebras',
                                  'CommutativeAlgebraCoproducts'),
 'CommutativeAlgebraPushouts': ('dzack_research.preamble.categories.algebras.algebras',
                                'CommutativeAlgebraPushouts'),
 'CyclicCoverAlgebra': ('dzack_research.preamble.categories.algebras.cyclic_cover_algebras',
                        'CyclicCoverAlgebra'),
 'FinitelyPresentedAlgebras': ('dzack_research.preamble.categories.algebras.algebras',
                               'FinitelyPresentedAlgebras'),
 'FramedAlgebras': ('dzack_research.preamble.categories.algebras.algebras', 'FramedAlgebras'),
 'MatrixAlgebras': ('dzack_research.preamble.categories.algebras.algebras', 'MatrixAlgebras'),
 'CommutatorLieAlgebras': ('dzack_research.preamble.categories.algebras.lie_algebras',
                           'CommutatorLieAlgebras'),
 'LieAlgebraMor': ('dzack_research.preamble.categories.algebras.lie_algebras',
                      'LieAlgebraMor'),
 'LieAlgebraMorphism': ('dzack_research.preamble.categories.algebras.lie_algebras',
                        'LieAlgebraMorphism'),
 'LieAlgebras': ('dzack_research.preamble.categories.algebras.lie_algebras', 'LieAlgebras'),
 'AlternatingAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                         'AlternatingAlgebras'),
 'DividedPowerAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                          'DividedPowerAlgebras'),
 'FreeAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras', 'FreeAlgebras'),
 'GradedFreeAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                        'GradedFreeAlgebras'),
 'SymmetricAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras',
                       'SymmetricAlgebras'),
 'TensorAlgebras': ('dzack_research.preamble.categories.algebras.free_algebras', 'TensorAlgebras'),
 'PowerAlgebra': ('dzack_research.preamble.categories.algebras.power_algebras', 'PowerAlgebra'),
 'PowerAlgebraMor': ('dzack_research.preamble.categories.algebras.power_algebras',
                        'PowerAlgebraMor'),
 'PowerAlgebraMorphism': ('dzack_research.preamble.categories.algebras.power_algebras',
                          'PowerAlgebraMorphism'),
 'AugmentedAlgebras': ('dzack_research.preamble.categories.algebras.augmented_algebras',
                       'AugmentedAlgebras'),
 'GradedAugmentedAlgebras': ('dzack_research.preamble.categories.algebras.augmented_algebras',
                             'GradedAugmentedAlgebras'),
 'AffineSemigroupAlgebras': ('dzack_research.preamble.categories.algebras.semigroup_algebras',
                             'AffineSemigroupAlgebras'),
 'GroupAlgebraUnderlyingModuleFunctor': ('dzack_research.preamble.categories.algebras.group_algebras',
                                         'GroupAlgebraUnderlyingModuleFunctor'),
 'GroupAlgebras': ('dzack_research.preamble.categories.algebras.group_algebras', 'GroupAlgebras'),
 'FreeModuleOnGroupFunctor': ('dzack_research.preamble.categories.algebras.group_algebras',
                              'FreeModuleOnGroupFunctor'),
 'GradedAlgebraMor': ('dzack_research.preamble.categories.algebras.graded_algebras',
                         'GradedAlgebraMor'),
 'GradedAlgebraMorphism': ('dzack_research.preamble.categories.algebras.graded_algebras',
                           'GradedAlgebraMorphism'),
 'GradedAlgebras': ('dzack_research.preamble.categories.algebras.graded_algebras',
                    'GradedAlgebras'),
 'GradedCommutativeAlgebras': ('dzack_research.preamble.categories.algebras.graded_commutative_algebras',
                               'GradedCommutativeAlgebras'),
 'StrictlyGradedCommutativeAlgebras': ('dzack_research.preamble.categories.algebras.graded_commutative_algebras',
                                       'StrictlyGradedCommutativeAlgebras'),
 'RestrictedScalarsAlgebras': ('dzack_research.preamble.categories.algebras.restricted_scalars',
                               'RestrictedScalarsAlgebras'),
 'Derivation': ('dzack_research.preamble.categories.algebras.derivations', 'Derivation'),
 'DerivationSpace': ('dzack_research.preamble.categories.algebras.derivations', 'DerivationSpace'),
 'GradedDerivation': ('dzack_research.preamble.categories.algebras.derivations',
                      'GradedDerivation'),
 'GradedDerivationSpace': ('dzack_research.preamble.categories.algebras.derivations',
                           'GradedDerivationSpace'),
 'KahlerDifferentialModules': ('dzack_research.preamble.categories.algebras.kahler_differentials',
                               'KahlerDifferentialModules'),
 'RestrictedGradedAlgebra': ('dzack_research.preamble.categories.algebras.restricted_graded_algebras',
                             'RestrictedGradedAlgebra'),
 'RestrictedGradedAlgebraElement': ('dzack_research.preamble.categories.algebras.restricted_graded_algebras',
                                    'RestrictedGradedAlgebraElement'),
 'DGAMor': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
               'DGAMor'),
 'DGAMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                 'DGAMorphism'),
 'DegreewiseLinearMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                              'DegreewiseLinearMorphism'),
 'Differential': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                  'Differential'),
 'DifferentialComponentMorphism': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                   'DifferentialComponentMorphism'),
 'DifferentialGradedAlgebras': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                'DifferentialGradedAlgebras'),
 'StrictlyCommutativeDifferentialGradedAlgebras': ('dzack_research.preamble.categories.algebras.differential_graded_algebras',
                                                   'StrictlyCommutativeDifferentialGradedAlgebras'),
 'DeRhamAlgebras': ('dzack_research.preamble.categories.algebras.de_rham_algebras',
                    'DeRhamAlgebras'),
 'CohomologyAlgebraElement': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                              'CohomologyAlgebraElement'),
 'CohomologyAlgebraMor': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                             'CohomologyAlgebraMor'),
 'CohomologyAlgebraMorphism': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                               'CohomologyAlgebraMorphism'),
 'CohomologyAlgebras': ('dzack_research.preamble.categories.algebras.cohomology_algebras',
                        'CohomologyAlgebras')}

__all__ = ['AugmentedAlgebras',
 'AffineSemigroupAlgebras',
 'AlgebraMor',
 'AlgebraMorphism',
 'Algebras',
 'CommutativeAlgebraCoproducts',
 'CommutativeAlgebraPushouts',
 'CommutatorLieAlgebras',
 'CyclicCoverAlgebra',
 'CohomologyAlgebraElement',
 'CohomologyAlgebraMor',
 'CohomologyAlgebraMorphism',
 'CohomologyAlgebras',
 'AlgebrasWithChosenFinitePresentation',
 'AlternatingAlgebras',
 'DividedPowerAlgebras',
 'Derivation',
 'DerivationSpace',
 'GradedDerivation',
 'GradedDerivationSpace',
 'LieAlgebraMor',
 'LieAlgebraMorphism',
 'LieAlgebras',
 'DeRhamAlgebras',
 'DGAMor',
 'DGAMorphism',
 'DegreewiseLinearMorphism',
 'Differential',
 'DifferentialComponentMorphism',
 'DifferentialGradedAlgebras',
 'FramedAlgebras',
 'FinitelyPresentedAlgebras',
 'PowerAlgebra',
 'PowerAlgebraMor',
 'PowerAlgebraMorphism',
 'KahlerDifferentialModules',
 'RestrictedScalarsAlgebras',
 'RestrictedGradedAlgebra',
 'RestrictedGradedAlgebraElement',
 'FreeAlgebras',
 'GradedAlgebras',
 'GradedAlgebraMor',
 'GradedAlgebraMorphism',
 'GradedCommutativeAlgebras',
 'GradedAugmentedAlgebras',
 'GroupAlgebraUnderlyingModuleFunctor',
 'GroupAlgebras',
 'FreeModuleOnGroupFunctor',
 'GradedFreeAlgebras',
 'SymmetricAlgebras',
 'TensorAlgebras',
 'StrictlyGradedCommutativeAlgebras',
 'StrictlyCommutativeDifferentialGradedAlgebras',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
