"""Owned algebra categories and native-backed free constructions."""

from dzack_research.preamble.categories.algebras.algebras import (
    AlgebraHomset,
    AlgebraMorphism,
    Algebras,
    AlgebrasWithChosenFinitePresentation,
    AlgebrasWithChosenMultiplication,
    AssociativeAlgebras,
    AssociativeAlgebrasWithChosenMultiplication,
    CommutativeAlgebraCoproducts,
    CommutativeAlgebraPushouts,
    CommutativeAlgebras,
    FinitelyPresentedAlgebras,
    FramedAlgebras,
    MatrixAlgebras,
    OwnedAlgebras,
    algebra_from_multiplication,
    algebra_homset,
    commutative_algebra_coproduct,
    commutative_algebra_pushout,
    finite_algebra_generators,
    own_algebra,
    refine_algebra,
    refine_matrix_algebra,
)
from dzack_research.preamble.categories.algebras.lie_algebras import (
    CommutatorLieAlgebras,
    LieAlgebras,
)
from dzack_research.preamble.categories.algebras.free_algebras import (
    AlternatingAlgebras,
    DividedPowerAlgebras,
    FinitelyPresentedAlgebra,
    FreeAlgebras,
    GradedFreeAlgebras,
    SymmetricAlgebras,
    TensorAlgebras,
)
from dzack_research.preamble.categories.algebras.framed_free_algebras import (
    AlternatingAlgebraOf,
    AlternatingAlgebraOn,
    DividedPowerAlgebraOf,
    DividedPowerAlgebraOn,
    FreeAlgebraOn,
    SymmetricAlgebraOf,
    SymmetricAlgebraOn,
    TensorAlgebraOf,
    TensorAlgebraOn,
    polynomial_ring,
)
from dzack_research.preamble.categories.algebras.power_algebras import (
    PowerAlgebra,
    PowerAlgebraHomset,
    PowerAlgebraMorphism,
    power_algebra_homset,
)
from dzack_research.preamble.categories.algebras.comparison_maps import (
    divided_to_symmetric,
    symmetric_to_divided,
    tensor_to_alternating,
    tensor_to_symmetric,
)
from dzack_research.preamble.categories.algebras.finitely_presented_algebras import (
    FinitelyPresentedAlgebraOn,
)
from dzack_research.preamble.categories.algebras.augmented_algebras import (
    AugmentedAlgebras,
    GradedAugmentedAlgebras,
    augmented_algebra,
)
from dzack_research.preamble.categories.algebras.graded_algebras import (
    GradedAlgebraHomset,
    GradedAlgebraMorphism,
    GradedAlgebras,
    graded_algebra_homset,
)
from dzack_research.preamble.categories.algebras.graded_commutative_algebras import (
    GradedCommutativeAlgebras,
    StrictlyGradedCommutativeAlgebras,
)
from dzack_research.preamble.categories.algebras.restricted_scalars import (
    RestrictedScalarsAlgebras,
    restrict_algebra_scalars,
)
from dzack_research.preamble.categories.algebras.derivations import (
    Derivation,
    DerivationSpace,
    Derivations,
    GradedDerivation,
    GradedDerivationSpace,
    GradedDerivations,
)
from dzack_research.preamble.categories.algebras.kahler_differentials import (
    KahlerDifferentialModules,
    KahlerDifferentials,
)
from dzack_research.preamble.categories.algebras.restricted_graded_algebras import (
    RestrictedGradedAlgebra,
    RestrictedGradedAlgebraElement,
    restrict_graded_algebra_scalars,
)
from dzack_research.preamble.categories.algebras.differential_graded_algebras import (
    CommutativeDifferentialGradedAlgebras,
    DGAHomset,
    DGAMorphism,
    DegreewiseLinearMorphism,
    Differential,
    DifferentialComponentMorphism,
    DifferentialGradedAlgebras,
    StrictlyCommutativeDifferentialGradedAlgebras,
    dga_homset,
)
from dzack_research.preamble.categories.algebras.de_rham_algebras import (
    DeRhamAlgebra,
    DeRhamAlgebras,
)
from dzack_research.preamble.categories.algebras.cartan_calculus import (
    GradedCommutator,
    InteriorProduct,
    LieBracket,
    LieDerivative,
    VectorFields,
)
from dzack_research.preamble.categories.algebras.cohomology_algebras import (
    CohomologyAlgebra,
    CohomologyAlgebraElement,
    CohomologyAlgebraHomset,
    CohomologyAlgebraMorphism,
    CohomologyAlgebras,
    cohomology_algebra_homset,
)

__all__ = [
    "AugmentedAlgebras",
    "AlgebraHomset",
    "AlgebraMorphism",
    "Algebras",
    "AlgebrasWithChosenMultiplication",
    "AssociativeAlgebras",
    "AssociativeAlgebrasWithChosenMultiplication",
    "CommutativeAlgebraCoproducts",
    "commutative_algebra_pushout",
    "CommutativeAlgebraPushouts",
    "commutative_algebra_coproduct",
    "CommutativeAlgebras",
    "CommutatorLieAlgebras",
    "CommutativeDifferentialGradedAlgebras",
    "CohomologyAlgebra",
    "CohomologyAlgebraElement",
    "CohomologyAlgebraHomset",
    "CohomologyAlgebraMorphism",
    "CohomologyAlgebras",
    "AlgebrasWithChosenFinitePresentation",
    "AlternatingAlgebraOf",
    "AlternatingAlgebraOn",
    "AlternatingAlgebras",
    "DividedPowerAlgebraOf",
    "DividedPowerAlgebraOn",
    "DividedPowerAlgebras",
    "Derivation",
    "DerivationSpace",
    "Derivations",
    "GradedDerivation",
    "GradedDerivationSpace",
    "GradedDerivations",
    "GradedCommutator",
    "InteriorProduct",
    "LieBracket",
    "LieDerivative",
    "LieAlgebras",
    "VectorFields",
    "DeRhamAlgebra",
    "DeRhamAlgebras",
    "DGAHomset",
    "DGAMorphism",
    "DegreewiseLinearMorphism",
    "Differential",
    "DifferentialComponentMorphism",
    "DifferentialGradedAlgebras",
    "FramedAlgebras",
    "FinitelyPresentedAlgebra",
    "FinitelyPresentedAlgebraOn",
    "FinitelyPresentedAlgebras",
    "OwnedAlgebras",
    "PowerAlgebra",
    "PowerAlgebraHomset",
    "PowerAlgebraMorphism",
    "KahlerDifferentialModules",
    "KahlerDifferentials",
    "RestrictedScalarsAlgebras",
    "RestrictedGradedAlgebra",
    "RestrictedGradedAlgebraElement",
    "algebra_from_multiplication",
    "algebra_homset",
    "augmented_algebra",
    "FreeAlgebraOn",
    "FreeAlgebras",
    "GradedAlgebras",
    "GradedAlgebraHomset",
    "GradedAlgebraMorphism",
    "GradedCommutativeAlgebras",
    "GradedAugmentedAlgebras",
    "GradedFreeAlgebras",
    "SymmetricAlgebraOf",
    "SymmetricAlgebraOn",
    "SymmetricAlgebras",
    "TensorAlgebraOf",
    "TensorAlgebraOn",
    "TensorAlgebras",
    "StrictlyGradedCommutativeAlgebras",
    "StrictlyCommutativeDifferentialGradedAlgebras",
    "finite_algebra_generators",
    "own_algebra",
    "polynomial_ring",
    "power_algebra_homset",
    "divided_to_symmetric",
    "symmetric_to_divided",
    "tensor_to_alternating",
    "tensor_to_symmetric",
    "refine_algebra",
    "restrict_algebra_scalars",
    "restrict_graded_algebra_scalars",
    "dga_homset",
    "cohomology_algebra_homset",
    "graded_algebra_homset",
]
