r"""Framed algebras over a base ring R.

A framed R-algebra is equipped with a chosen surjection from a free R-algebra on
a set S, exactly as a framed R-module is equipped with a surjection from a free
R-module on S.
"""

from typing import Protocol, TYPE_CHECKING
if TYPE_CHECKING:
    from sage.structure.parent import ElementConstructorInput, MembershipInput
    from dzack_research.preamble.owned_category import ConstructionData
if TYPE_CHECKING:
    from dzack_research.preamble.lexicon import Element
    from sage.categories.modules import Module
    from dzack_research.preamble.lexicon import OrderedSet

from sage.categories.morphism import Morphism
if TYPE_CHECKING:
    from sage.rings.ring import Ring

from dzack_research.preamble.owned_category import object_of
from dzack_research.preamble.owned_category_bases import HomsetsCategory
from dzack_research.preamble.categories.rings.rings import OwnedCategoryOverBaseRing
from sage.categories.algebras import Algebras as SageAlgebras
from sage.categories.category import Category
from sage.categories.category_types import Category_over_base_ring
from sage.categories.homset import Hom
from sage.categories.map import Map
from sage.categories.morphism import SetMorphism
from sage.categories.rings import Rings as SageRings
from sage.misc.abstract_method import abstract_method
from sage.structure.parent import Parent

if TYPE_CHECKING:
    # What this node requires of the objects it is about.  Sage binds
    # ``ParentMethods`` onto a parent and ``SubcategoryMethods`` onto a
    # category by COPYING the methods into a dynamic class, so the object a
    # method runs on is never an instance of the class the method is written
    # in; ``self`` is annotated with what its placement gives it.

    class AlgebraParent(Protocol):
        r"""A parent in ``Algebras(R)``.

        ``change_ring`` is this category's own requirement, not a ring's:
        :meth:`Algebras.ParentMethods.base_change` is written against it, so
        an algebra that cannot move its base cannot answer base change.
        """

        def base_ring(self) -> "Ring": ...
        def coerce_map_from(
            self,
            S: "ElementConstructorInput",
        ) -> "Morphism | None": ...
        def _ring_morphism_defining_algebra_structure(self) -> "Morphism": ...
        def _coerce_map_from_base_ring(self) -> "Morphism": ...
        def change_ring(self, ring: "Ring") -> "AlgebraParent": ...

    class FramedAlgebraParent(AlgebraParent, Protocol):
        r"""An algebra parent that names the set \(S\) it is generated by."""

        def algebra_generating_set(self) -> "OrderedSet": ...
        def algebra_generator(self, label: "Element") -> "Element": ...

    class AlgebraCategory(Protocol):
        r"""The category itself, which ``SubcategoryMethods`` are bound onto."""

        def base_ring(self) -> "Ring": ...


class Algebras(OwnedCategoryOverBaseRing):
    r"""Associative unital algebras over a base ring (R)."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "algebras"

    def __contains__(self, algebra: "MembershipInput") -> bool:
        """Return whether ``algebra`` is an explicit ``R``-algebra witness."""
        # Asked of Sage's category, not of its method with this category as
        # ``self``: this one is not one of Sage's, so its ``super()`` is not
        # Sage's either.
        if algebra in SageAlgebras(self.base_ring()):
            return True

        if not isinstance(algebra, Parent):
            return False

        return bool(algebra.coerce_map_from(self.base_ring()))

    def super_categories(self) -> list:
        # Local: importing the ring node here would close a cycle, and the
        # module is built by the time this method runs.
        from dzack_research.preamble.categories.rings.rings import OwnedRings

        # An associative unital algebra is a ring, and it joins the owned
        # hierarchy at that node like any other: this is what makes
        # \(R[x]^n\) the preamble's free module rather than Sage's.  Sage's
        # own algebra node says the same thing to Sage; saying it here is
        # what puts the owned ``__pow__`` ahead of the inherited one.
        return [SageAlgebras(self.base_ring()), OwnedRings()]

    class ParentMethods:
        @abstract_method
        def _ring_morphism_defining_algebra_structure(self) -> "Morphism":
            r"""Return $R\to Z(A)$, which is what makes $A$ an $R$-algebra.

            Into the *centre*, not merely into $A$: that is what forces the
            scalars to commute past everything, which is what an algebra over
            a commutative ring means.  A map into $A$ alone would not say it.

            The obligation of this category, parallel to a module's
            $\rho:R\to\operatorname{End}(M)$.  Every construction supplies it
            rather than declaring membership and hoping: a module with a
            multiplication $m:A\otimes_R A\to A$ supplies $r\mapsto r\cdot 1_A$,
            a free construction supplies the same, and $R$ over itself
            supplies the identity $R\to Z(R)=R$.

            The containment of the image in $Z(A)$ is trusted where it cannot
            be decided -- for an algebra given by a multiplication tensor the
            centre is not computable -- and checked where it can.
            """
            ...

        def base_change(self: "AlgebraParent", ring_hom: "Morphism") -> "Module":
            r"""Base change this algebra along a ring morphism."""
            # Local: importing the ring node here would close a cycle, and the
            # module is built by the time this method runs.
            from dzack_research.preamble.categories.rings.rings import engine_ring

            # A coercion is a ring map that Sage spells as a ``Map`` and not
            # as a ``Morphism`` -- ``QQ -> CC`` arrives as a composite -- and
            # base change is along a ring map however it was obtained.
            assert isinstance(ring_hom, Map), (
                "base_change requires a ring map"
            )
            # Both ends of the map cross to the engine to be compared: a
            # session names owned rings, so the map it obtained runs between
            # them, and only the engine's name is common to both spellings.
            assert engine_ring(ring_hom.domain()) == engine_ring(self.base_ring()), (
                "the map must have this algebra's base ring as domain"
            )
            if engine_ring(ring_hom.codomain()) == engine_ring(self.base_ring()):
                return self
            return self.change_ring(ring_hom.codomain())

        def is_algebra(self) -> bool:
            r"""Return whether this parent is declared to be an (R)-algebra."""
            return True

    class SubcategoryMethods:
        def Free(self: "AlgebraCategory") -> Category:
            r"""Return the free-algebra subcategory over this base ring."""
            # Local: free_algebras imports this module, so a module-level
            # import here would close that cycle.
            from dzack_research.preamble.categories.algebras.free_algebras import FreeAlgebras

            free_algebras: Category = FreeAlgebras(self.base_ring())
            return free_algebras

        def FinitelyPresented(self: "AlgebraCategory") -> Category:
            from dzack_research.preamble.categories.algebras.finitely_presented_algebras import (
                FinitelyPresentedAlgebras,
            )

            finitely_presented: Category = FinitelyPresentedAlgebras(self.base_ring())
            return finitely_presented

class FramedAlgebras(OwnedCategoryOverBaseRing):
    r"""R-algebras carrying a specified surjection \(\operatorname{FreeAlg}_R(S) \to A\)."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "framed algebras"

    def super_categories(self) -> list:
        # Local: importing the framed-module node here would close a cycle,
        # and the module is built by the time this method runs.
        from dzack_research.preamble.categories.modules.framed.framed_modules import FramedModules

        return [Algebras(self.base_ring()), FramedModules(self.base_ring())]

    class ParentMethods:

        @abstract_method
        def product_on_algebra_generators(
            self, s: "Element", t: "Element"
        ) -> "Element":
            r"""Return the product of algebra_generators labelled by s and t in S."""
            ...

    class Homsets(HomsetsCategory):
        r"""Homsets of algebras with specified algebra generating sets."""

        def extra_super_categories(self) -> list:
            from dzack_research.preamble.categories.modules.pure.modules import (
                Modules,
            )

            return [Modules(self.base_category().base_ring()).Homsets()]

        class ParentMethods:
            def __init__(
                self,
                domain: "Parent",
                codomain: "Parent",
                **rest: "ConstructionData",
            ) -> None:
                assert domain.base_ring() == codomain.base_ring(), (
                    "an algebra morphism is linear over one base ring"
                )
                super().__init__(
                    domain=domain,
                    codomain=codomain,
                    base=domain.base_ring(),
                    check=False,
                    **rest,
                )

        class ElementMethods:
            def corestrict_to_center(self: "Morphism") -> "Morphism":
                r"""Return \(f:A\to Z(S)\) when the image is central."""
                domain = self.domain()
                codomain = self.codomain()
                centre = codomain.ring_center()
                for generator in finite_algebra_generators(domain):
                    image = self(generator)
                    assert image in centre, (
                        f"{image} is not central in {codomain}, so {self} "
                        "does not corestrict to the centre"
                    )
                return SetMorphism(Hom(domain, centre, SageRings()), self)


class OwnedAlgebras(OwnedCategoryOverBaseRing):
    r"""The \(R\)-algebras a ring map \(R\to A\) presents.

    An \(R\)-algebra *is* that map, so it is the construction's argument: one
    ring is an algebra over many bases, and \(\mathbb Q\) over \(\mathbb Z\)
    and \(\mathbb Q\) over \(\mathbb Q\) are two algebras that differ in
    nothing but their structure map.

    Constructed from the structure map rather than refined onto its codomain.
    One ring is an algebra over different base rings through different maps,
    so the map is additional structure and must remain part of the object.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "owned algebras"

    def super_categories(self) -> list:
        return [Algebras(self.base_ring())]

    class ParentMethods:
        r"""A ring the engine holds, read as an \(R\)-algebra through a map."""

        def __init__(
            self, structure_map: "Map", **rest: "ConstructionData"
        ) -> None:
            r"""Build the \(R\)-algebra the ring map ``structure_map`` presents."""
            # Local: importing the ring node here would close a cycle, and the
            # module is built by the time this constructor runs.
            from dzack_research.preamble.categories.rings.rings import engine_ring
            from dzack_research.preamble.categories.rings.rings import owned_ring_view

            assert isinstance(structure_map, Map), (
                "an algebra is presented by a ring map into it"
            )
            # Intake: the codomain crosses to the engine, which is what
            # computes.  The domain is named the way the category over it is
            # named, so ``CategoryObject.base_ring`` answers with that ring.
            self._structure_map = structure_map
            self._engine = engine_ring(structure_map.codomain())
            super().__init__(
                base=owned_ring_view(structure_map.domain()), **rest
            )

        def _ring_morphism_defining_algebra_structure(self) -> "Map":
            return self._structure_map

        def change_ring(self, ring: "Ring") -> "Parent":
            return own_algebra(self._engine.base_extend(ring).coerce_map_from(ring))

        def _element_constructor_(self, value: "Element") -> "Element":
            return self._engine(value)

        def __hash__(self) -> int:
            return hash((type(self), self._structure_map))

        def __eq__(self, other: "MembershipInput") -> bool:
            return (
                type(other) is type(self)
                and other._structure_map == self._structure_map
            )

        def _repr_(self) -> str:
            return f"{self._engine} as an algebra over {self.base_ring()}"


def own_algebra(structure_map: "Map") -> Parent:
    r"""Return the owned \(R\)-algebra the ring map ``structure_map`` presents."""
    # Local: importing the ring node here would close a cycle, and the module
    # is built by the time this function runs.
    from dzack_research.preamble.categories.rings.rings import engine_ring

    return object_of(
        OwnedAlgebras(engine_ring(structure_map.domain())),
        structure_map=structure_map,
    )


def finite_algebra_generators(algebra: "FramedAlgebraParent") -> tuple:
    r"""Return the finitely many elements generating ``algebra`` over its base.

    The refusal is the point: a ring that cannot name a generating set cannot
    decide centrality in itself either, and a predicate that answered anyway
    would be answering on trust.

    Asked for the generating *set* -- the preamble's own word for it, and one
    Sage has no method of.  Sage's ``algebra_generators`` resolves on rings
    that cannot produce it: \(M_n(R)\) as this preamble receives it inherits
    the name from a category and then fails on the engine's internals, which
    is an accident reported as a missing attribute rather than the
    mathematical refusal this owes its caller.
    """
    from dzack_research.preamble.categories.sets.owned_sets import Sets

    labels = algebra.algebra_generating_set()
    assert labels in Sets().Finite(), (
        f"{algebra} is generated by {labels}, which is infinite: commuting "
        "with every generator is not a finite check"
    )
    return tuple(algebra.algebra_generator(label) for label in labels)


_ALGEBRAS_INSTALLED = False


def install_algebras() -> None:
    r"""Register post-init hooks and installation for algebras."""
    global _ALGEBRAS_INSTALLED

    if _ALGEBRAS_INSTALLED:
        return

    _ALGEBRAS_INSTALLED = True


install_algebras()
