r"""Finite algebra presentations backed by Sage polynomial quotients."""

from collections.abc import Iterable

from sage.rings.noncommutative_ideals import Ideal_nc

from dzack_research.preamble.categories.algebras.algebras import (
    Algebras,
    AlgebrasWithChosenFinitePresentation,
    FinitelyPresentedAlgebras,
    FramedAlgebras,
    OwnedAlgebras,
    algebra_homset,
)
from dzack_research.preamble.categories.algebras.free_algebras import (
    FinitelyPresentedAlgebra,
    GradedFreeAlgebras,
    SymmetricAlgebraOn,
    TensorAlgebras,
    _PresentedAlgebraParent,
)
from dzack_research.preamble.categories.algebras.graded_algebras import GradedAlgebras
from dzack_research.preamble.categories.rings.ring_foundation import (
    _engine_element,
    _engine_ring,
)


from dzack_research.preamble.categories.modules.tensor_products import (
    _flatten_tensor_label,
    _nested_tensor_label,
)
from dzack_research.preamble.categories.abstract_categories.constructions import TensorProduct
from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import _presentation_matrix
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import module_coefficients
from dzack_research.preamble.categories.sets.indexed_families import indexed_family
from dzack_research.preamble.categories.sets.set_categories import Sets


def _canonical_smith_representative(module, element):
    r"""Choose the Smith-coordinate representative used by quotient reduction.

    The module itself remains the mathematical quotient.  This function only
    chooses a deterministic computation representative of one element, using
    the invariant-factor quotients already computed by the live finitely
    presented module implementation.
    """

    smith_engine = module._smith_engine()
    if smith_engine is None:
        raise NotImplementedError(
            "a canonical representative is currently chosen from a PID Smith engine"
        )
    coordinates = tuple(
        smith_engine.coordinate_vector(
            module._to_smith_engine_element(element),
            reduce=False,
        )
    )
    invariants = tuple(smith_engine.invariants())
    engine = _engine_ring(module.base_ring())
    reduced = [
        coordinate
        if invariant == 0
        else engine.ideal(invariant).reduce(coordinate)
        for coordinate, invariant in zip(coordinates, invariants, strict=True)
    ]
    if not reduced:
        return module.zero()
    return module._from_smith_engine_element(
        smith_engine.linear_combination_of_smith_form_gens(reduced)
    )


class _LinearPresentationTensorIdeal(Ideal_nc):
    r"""Two-sided linear-relation ideal reduced by tensor powers of a module.

    Sage's generic noncommutative quotient ring delegates normal forms to the
    ideal.  For the ideal generated by the linear relations of a finitely
    presented module ``M``, its homogeneous degree-``d`` quotient is exactly
    ``M^{tensor d}``.  The live categorical :func:`TensorProduct` therefore
    supplies the normal form; this class is only the adapter from free-algebra
    words to those tensor-product coordinates.
    """

    def __init__(self, presentation_ring, module, relations) -> None:
        engine = _engine_ring(presentation_ring)
        Ideal_nc.__init__(self, engine, relations, side="twosided")
        self._module = module
        self._labels = module.module_generating_set()
        self._monoid_generator_labels = dict(
            zip(engine.monoid().gens(), self._labels, strict=True)
        )
        self._tensor_powers = {1: module}

    def _tensor_power(self, degree):
        power = self._tensor_powers.get(degree)
        if power is not None:
            return power

        power = TensorProduct(self._tensor_power(degree - 1), self._module)
        self._tensor_powers[degree] = power
        return power

    def _word_labels(self, monomial):
        return tuple(
            self._monoid_generator_labels[generator]
            for generator, exponent in monomial
            for _ in range(int(exponent))
        )

    def _free_word(self, word):
        engine = self.ring()
        result = engine.one()
        for label in word:
            result *= engine.gen(self._labels.index(label))
        return result

    def reduce(self, element):

        engine = self.ring()
        homogeneous_terms = {}
        for monomial, coefficient in engine(element).monomial_coefficients().items():
            word = self._word_labels(monomial)
            homogeneous_terms.setdefault(len(word), []).append((word, coefficient))

        result = engine.zero()
        for degree, terms in homogeneous_terms.items():
            if degree == 0:
                result += sum(
                    (coefficient for _word, coefficient in terms),
                    engine.base_ring().zero(),
                )
                continue

            tensor_power = self._tensor_power(degree)
            tensor_ring = tensor_power.base_ring()
            tensor_element = sum(
                (
                    tensor_ring._from_engine_element(
                        _engine_ring(tensor_ring)(coefficient)
                    )
                    * tensor_power.module_generator(
                        _nested_tensor_label(self._module, word)
                    )
                    for word, coefficient in terms
                ),
                tensor_power.zero(),
            )
            representative = _canonical_smith_representative(
                tensor_power,
                tensor_element,
            )
            for tensor_label, coefficient in module_coefficients(
                representative,
                tensor_power,
            ).items():
                result += _engine_element(
                    tensor_power.base_ring(), coefficient
                ) * self._free_word(
                    _flatten_tensor_label(tensor_label, degree)
                )
        return result

    def _contains_(self, element) -> bool:
        return self.reduce(element) == self.ring().zero()


def _tensor_algebra_from_module_presentation(presentation_ring, module):
    r"""Quotient a free associative algebra by ``module``'s linear relations."""

    engine = _engine_ring(presentation_ring)
    relation_matrix = _presentation_matrix(module)
    relation_indices = Sets.Δ[relation_matrix.nrows() - 1]
    base = presentation_ring.base_ring()

    def backend_relation(index):
        row_position = int(index)
        result = engine.zero()
        for position in range(relation_matrix.ncols()):
            coefficient = relation_matrix[row_position, position]
            if coefficient:
                result += _engine_element(base, coefficient) * engine.gen(position)
        return result

    selected_relations = indexed_family(
        relation_indices,
        lambda index: presentation_ring._from_engine_element(
            backend_relation(index)
        ),
        name="Tensor-algebra defining relations",
    )
    if all(relation == presentation_ring.zero() for relation in selected_relations):
        return presentation_ring

    # Private serialization for Sage's noncommutative ideal object.
    backend_relations = [
        _engine_element(presentation_ring, relation)
        for relation in selected_relations
    ]
    presentation_ideal = _LinearPresentationTensorIdeal(
        presentation_ring,
        module,
        backend_relations,
    )
    quotient_engine = engine.quotient(presentation_ideal)
    labels = presentation_ring.algebra_generating_set()
    presented = _PresentedAlgebraParent(
        quotient_engine,
        base,
        labels,
        presentation_ring,
        selected_relations,
        presentation_ideal,
        extra_categories=(
            GradedFreeAlgebras(base),
            TensorAlgebras(base),
            GradedAlgebras(base),
        ),
        free_source_module=module,
    )
    return presented


def FinitelyPresentedAlgebraOn(base_ring, algebra_generating_set, relations):
    r"""Construct ``R[S] / (relations)`` with the displayed finite presentation."""
    return FinitelyPresentedAlgebra(
        SymmetricAlgebraOn(base_ring, algebra_generating_set),
        relations,
    )


__all__ = [
    "AlgebrasWithChosenFinitePresentation",
    "FinitelyPresentedAlgebra",
    "FinitelyPresentedAlgebraOn",
    "FinitelyPresentedAlgebras",
]
