r"""Finite algebra presentations backed by Sage polynomial quotients."""

from collections.abc import Iterable

from sage.categories.map import Map
from sage.rings.ideal import Ideal_generic
from sage.rings.noncommutative_ideals import Ideal_nc

from dzack_research.preamble.categories.algebras.algebras import (
    Algebras,
    CommutativeAlgebras,
    FramedAlgebras,
    OwnedAlgebraView,
    OwnedAlgebras,
    _default_structure_map,
    algebra_homset,
)
from dzack_research.preamble.categories.algebras.free_algebras import SymmetricAlgebras
from dzack_research.preamble.categories.rings import (
    OwnedCategoryOverBaseRing,
    engine_ring,
    owned_ring_view,
)
from dzack_research.preamble.refine import refine


def _nested_tensor_label(word):
    iterator = iter(word)
    label = next(iterator)
    for next_label in iterator:
        label = (label, next_label)
    return label


def _flatten_tensor_label(label, degree):
    if degree == 1:
        return (label,)
    left, right = label
    return _flatten_tensor_label(left, degree - 1) + (right,)


def _canonical_smith_representative(module, element):
    r"""Choose the Smith-coordinate representative used by quotient reduction.

    The module itself remains the mathematical quotient.  This function only
    chooses a deterministic computation representative of one element, using
    the invariant-factor quotients already computed by the live finitely
    presented module implementation.
    """
    from dzack_research.preamble.tensors import tensor

    coordinates = tuple(module.coordinate_vector(element, reduce=False))
    invariants = tuple(module.invariants())
    engine = engine_ring(module.base_ring())
    reduced = [
        coordinate
        if invariant == 0
        else engine.ideal(invariant).reduce(coordinate)
        for coordinate, invariant in zip(coordinates, invariants, strict=True)
    ]
    if not reduced:
        return module.zero()
    return module.linear_combination_of_smith_form_gens(
        tensor.vector(engine, reduced)
    )


class _LinearPresentationTensorIdeal(Ideal_nc):
    r"""Two-sided linear-relation ideal reduced by tensor powers of a module.

    Sage's generic noncommutative quotient ring delegates normal forms to the
    ideal.  For the ideal generated by the linear relations of a finitely
    presented module ``M``, its homogeneous degree-``d`` quotient is exactly
    ``M^{tensor d}``.  The live categorical :func:`TensorProduct` therefore
    supplies the normal form; this class is only the adapter from free-algebra
    words to those tensor-product coordinates.
    """

    def __init__(self, presentation_ring, module, relations) -> None:
        engine = engine_ring(presentation_ring)
        Ideal_nc.__init__(self, engine, relations, side="twosided")
        self._module = module
        self._labels = tuple(module.module_generating_set())
        self._monoid_generator_labels = dict(
            zip(engine.monoid().gens(), self._labels, strict=True)
        )
        self._tensor_powers = {1: module}

    def _tensor_power(self, degree):
        power = self._tensor_powers.get(degree)
        if power is not None:
            return power
        from dzack_research.preamble.categories.abstract_categories import TensorProduct

        power = TensorProduct(self._tensor_power(degree - 1), self._module)
        self._tensor_powers[degree] = power
        return power

    def _word_labels(self, monomial):
        return tuple(
            self._monoid_generator_labels[generator]
            for generator, exponent in monomial
            for _ in range(int(exponent))
        )

    def _free_word(self, word):
        engine = self.ring()
        result = engine.one()
        for label in word:
            result *= engine.gen(self._labels.index(label))
        return result

    def reduce(self, element):
        from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
            module_coefficients,
        )

        engine = self.ring()
        homogeneous_terms = {}
        for monomial, coefficient in engine(element).monomial_coefficients().items():
            word = self._word_labels(monomial)
            homogeneous_terms.setdefault(len(word), []).append((word, coefficient))

        result = engine.zero()
        for degree, terms in homogeneous_terms.items():
            if degree == 0:
                result += sum(
                    (coefficient for _word, coefficient in terms),
                    engine.base_ring().zero(),
                )
                continue

            tensor_power = self._tensor_power(degree)
            tensor_element = sum(
                (
                    coefficient
                    * tensor_power.module_generator(_nested_tensor_label(word))
                    for word, coefficient in terms
                ),
                tensor_power.zero(),
            )
            representative = _canonical_smith_representative(
                tensor_power,
                tensor_element,
            )
            for tensor_label, coefficient in module_coefficients(
                representative,
                tensor_power,
            ).items():
                result += coefficient * self._free_word(
                    _flatten_tensor_label(tensor_label, degree)
                )
        return result

    def _contains_(self, element) -> bool:
        return self.reduce(element) == self.ring().zero()


class FinitelyPresentedAlgebras(OwnedCategoryOverBaseRing):
    r"""Algebras that admit a finite algebra presentation."""

    @classmethod
    def _repr_object_names(cls):
        return "finitely presented algebras"

    def super_categories(self):
        return [Algebras(self.base_ring())]

    class ParentMethods:
        def is_finitely_presented(self) -> bool:
            return True


class AlgebrasWithChosenFinitePresentation(OwnedCategoryOverBaseRing):
    r"""Finitely presented algebras carrying one selected finite presentation."""

    @classmethod
    def _repr_object_names(cls):
        return "algebras with a chosen finite presentation"

    def super_categories(self):
        return [
            FinitelyPresentedAlgebras(self.base_ring()),
            FramedAlgebras(self.base_ring()),
        ]

    class ParentMethods:
        def presentation_ring(self):
            return self._preamble_presentation_ring

        def relations(self):
            r"""Return the selected ordered tuple of defining relations."""
            return self._preamble_presentation_relations

        def presentation_ideal(self):
            r"""Return the ideal generated by the selected defining relations."""
            return self._preamble_presentation_ideal

        def presentation(self):
            r"""Return the selected free algebra and selected relation tuple."""
            return (self.presentation_ring(), self.relations())

        def algebra_presentation_morphism(self):
            return self._preamble_algebra_presentation_morphism

        def lift_to_presentation(self, element):
            r"""Return the selected exact representative in the presentation ring."""
            return self._preamble_lift_to_presentation(element)

        def base_change(self, ring_map):
            r"""Transport this selected presentation along ``R -> S``."""
            if not isinstance(ring_map, Map):
                raise TypeError("algebra base change is specified by a ring morphism")
            if engine_ring(ring_map.domain()) is not engine_ring(self.base_ring()):
                raise ValueError(
                    f"the scalar map starts at {ring_map.domain()}, not {self.base_ring()}"
                )

            from dzack_research.preamble.categories.algebras.free_algebras import (
                TensorAlgebras,
            )

            if self in TensorAlgebras(self.base_ring()):
                from dzack_research.preamble.categories.algebras.framed_free_algebras import (
                    TensorAlgebraOf,
                )

                return TensorAlgebraOf(
                    self._preamble_tensor_algebra_source_module.base_change(ring_map)
                )

            from dzack_research.preamble.categories.algebras.framed_free_algebras import (
                SymmetricAlgebraOn,
            )

            target_base = owned_ring_view(ring_map.codomain())
            target_presentation_ring = SymmetricAlgebraOn(
                target_base, self.algebra_generating_set()
            )
            target_engine = engine_ring(target_presentation_ring)
            mapped_relations = tuple(
                target_engine(
                    relation.map_coefficients(
                        ring_map,
                        new_base_ring=engine_ring(target_base),
                    )
                )
                for relation in self.relations()
            )
            return FinitelyPresentedAlgebra(
                target_presentation_ring,
                mapped_relations,
            )


def _relations_to_ideal(presentation_ring, relations):
    engine = engine_ring(presentation_ring)
    if isinstance(relations, Ideal_generic):
        if relations.ring() is not engine:
            raise ValueError("the relation ideal belongs to a different presenting algebra")
        selected_relations = tuple(relations.gens())
        return relations, selected_relations
    if not isinstance(relations, Iterable):
        raise TypeError("relations must be an ideal or a finite iterable of relation elements")
    selected_relations = tuple(engine(relation) for relation in relations)
    return engine.ideal(selected_relations), selected_relations


def FinitelyPresentedAlgebra(presentation_ring, relations):
    r"""Return the selected quotient ``R[S] / (relations)``.

    The current native adapter deliberately accepts a symmetric/free
    commutative presenting algebra.  Sage's free-associative ``quotient``
    constructor represents a different, finite-dimensional matrix-action
    problem and is not used as a substitute for a general two-sided ideal
    quotient.
    """
    base = presentation_ring.base_ring()
    if presentation_ring not in SymmetricAlgebras(base):
        raise NotImplementedError(
            "the active native finite-presentation adapter currently handles commutative polynomial presentations"
        )

    presentation_ideal, selected_relations = _relations_to_ideal(
        presentation_ring, relations
    )
    quotient_engine = engine_ring(presentation_ring).quotient(presentation_ideal)
    labels = presentation_ring.algebra_generating_set()

    # This view is intentionally not the cached ``refine_algebra`` view:
    # two selected relation systems may generate the same native quotient
    # ideal while still being different presentations.
    presented = OwnedAlgebraView(
        quotient_engine,
        base,
        tuple(labels),
        quotient_engine.coerce_map_from(engine_ring(base)),
    )
    presented._preamble_structure_map = _default_structure_map(base, presented)
    presented._preamble_presentation_ring = presentation_ring
    presented._preamble_presentation_relations = selected_relations
    presented._preamble_presentation_ideal = presentation_ideal
    presented._preamble_lift_to_presentation = lambda element: engine_ring(
        presentation_ring
    )(quotient_engine(element).lift())

    module_categories = []
    if len(tuple(labels)) == 1 and hasattr(quotient_engine, "modulus"):
        modulus = quotient_engine.modulus()
        degree = int(modulus.degree())
        if degree > 0:
            from dzack_research.preamble.categories.modules import (
                FinitelyGeneratedFreeModules,
            )
            from dzack_research.preamble.categories.sets import finite_ordered_set

            module_labels = finite_ordered_set(range(degree))
            quotient_generator = quotient_engine.gen()
            presented._preamble_base_ring = base
            presented._preamble_module_generating_set = module_labels
            presented._preamble_module_generator_values = {
                exponent: quotient_generator**exponent
                for exponent in module_labels
            }
            presented._preamble_module_coordinate_function = (
                lambda element: tuple(quotient_engine(element))
            )
            module_categories.append(FinitelyGeneratedFreeModules(base))

    presented = refine(
        presented,
        [
            Algebras(base),
            OwnedAlgebras(base),
            CommutativeAlgebras(base),
            FramedAlgebras(base),
            FinitelyPresentedAlgebras(base),
            AlgebrasWithChosenFinitePresentation(base),
        ]
        + module_categories,
    )
    presented._preamble_algebra_presentation_morphism = algebra_homset(
        presentation_ring,
        presented,
    )(
        lambda label: presented.algebra_generator(label)
    )
    return presented


def _tensor_algebra_from_module_presentation(presentation_ring, module):
    r"""Quotient a free associative algebra by ``module``'s linear relations."""
    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
        _presentation_matrix,
    )

    engine = engine_ring(presentation_ring)
    generators = tuple(engine.gens())
    relation_rows = tuple(_presentation_matrix(module).rows())
    selected_relations = tuple(
        sum(
            (
                coefficient * generator
                for coefficient, generator in zip(row, generators, strict=True)
                if coefficient
            ),
            engine.zero(),
        )
        for row in relation_rows
    )
    if not any(selected_relations):
        return presentation_ring

    presentation_ideal = _LinearPresentationTensorIdeal(
        presentation_ring,
        module,
        selected_relations,
    )
    quotient_engine = engine.quotient(presentation_ideal)
    base = presentation_ring.base_ring()
    labels = presentation_ring.algebra_generating_set()
    presented = OwnedAlgebraView(
        quotient_engine,
        base,
        tuple(labels),
        quotient_engine.coerce_map_from(engine_ring(base)),
    )
    presented._preamble_structure_map = _default_structure_map(base, presented)
    presented._preamble_presentation_ring = presentation_ring
    presented._preamble_presentation_relations = selected_relations
    presented._preamble_presentation_ideal = presentation_ideal
    presented._preamble_lift_to_presentation = lambda element: engine(
        quotient_engine(element).lift()
    )
    presented._preamble_tensor_algebra_source_module = module
    presented = refine(
        presented,
        [
            Algebras(base),
            OwnedAlgebras(base),
            FramedAlgebras(base),
            FinitelyPresentedAlgebras(base),
            AlgebrasWithChosenFinitePresentation(base),
        ],
    )
    presented._preamble_algebra_presentation_morphism = algebra_homset(
        presentation_ring,
        presented,
    )(
        lambda label: presented.algebra_generator(label)
    )
    return presented


def FinitelyPresentedAlgebraOn(base_ring, algebra_generating_set, relations):
    r"""Construct ``R[S] / (relations)`` with the displayed finite presentation."""
    from dzack_research.preamble.categories.algebras.framed_free_algebras import (
        SymmetricAlgebraOn,
    )

    return FinitelyPresentedAlgebra(
        SymmetricAlgebraOn(base_ring, algebra_generating_set),
        relations,
    )


__all__ = [
    "AlgebrasWithChosenFinitePresentation",
    "FinitelyPresentedAlgebra",
    "FinitelyPresentedAlgebraOn",
    "FinitelyPresentedAlgebras",
]
