'Owned algebraic-geometry and polyhedral categories.'

from importlib import import_module as _import_module

_EXPORTS = {
    'AffineOverlapRefinement': ('dzack_research.preamble.categories.schemes.covering_families',
     'AffineOverlapRefinement'),
    'RingedCoveringFamily': ('dzack_research.preamble.categories.schemes.covering_families',
     'RingedCoveringFamily'),
    'RingedCoveringOverlap': ('dzack_research.preamble.categories.schemes.covering_families',
     'RingedCoveringOverlap'),
    'AffineSpecFunctor': ('dzack_research.preamble.categories.schemes.affine_spec',
     'AffineSpecFunctor'),
    'AffineModuleSheaf': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'AffineModuleSheaf'),
    'AffineSpaceAnalytificationFunctor': ('dzack_research.preamble.categories.schemes.analytic_families', 'AffineSpaceAnalytificationFunctor'),
    'AnalyticDiscFamily': ('dzack_research.preamble.categories.schemes.analytic_families', 'AnalyticDiscFamily'),
    'CyclicCoverBaseChangeComparison': ('dzack_research.preamble.categories.schemes.cyclic_covers', 'CyclicCoverBaseChangeComparison'),
    'RelativeCyclicCoverLift': ('dzack_research.preamble.categories.schemes.cyclic_covers', 'RelativeCyclicCoverLift'),
    'HorikawaK3DoubleCover': ('dzack_research.preamble.categories.schemes.k3_families', 'HorikawaK3DoubleCover'),
    'HorikawaK3Family': ('dzack_research.preamble.categories.schemes.k3_families', 'HorikawaK3Family'),
    'HigherDirectImageSheaf': ('dzack_research.preamble.categories.schemes.monodromy', 'HigherDirectImageSheaf'),
    'IntegralLocalSystem': ('dzack_research.preamble.categories.schemes.monodromy', 'IntegralLocalSystem'),
    'LegendreMonodromyFamily': ('dzack_research.preamble.categories.schemes.monodromy', 'LegendreMonodromyFamily'),
    'PointedAnalyticFundamentalGroup': ('dzack_research.preamble.categories.schemes.monodromy', 'PointedAnalyticFundamentalGroup'),
    'legendre_monodromy_family': ('dzack_research.preamble.categories.schemes.monodromy', 'legendre_monodromy_family'),
    'CoverRefinement': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'CoverRefinement'),
    'DistinguishedAffineCover': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'DistinguishedAffineCover'),
    'LocallyRingedSpaces': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'LocallyRingedSpaces'),
    'QuasiCoherentSheaves': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'QuasiCoherentSheaves'),
    'RingedSpaces': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'RingedSpaces'),
    'SchemeUnderlyingSpace': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'SchemeUnderlyingSpace'),
    'StructureSheaf': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'StructureSheaf'),
    'AffineInvariantQuotientBaseChangeComparison': ('dzack_research.preamble.categories.schemes.quotients', 'AffineInvariantQuotientBaseChangeComparison'),
    'AffineSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSchemes'),
    'AffineGSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineGSchemes'),
    'AffineGroupSchemes': ('dzack_research.preamble.categories.schemes.group_schemes',
     'AffineGroupSchemes'),
    'AffineGroupSchemeActions': ('dzack_research.preamble.categories.schemes.group_schemes',
     'AffineGroupSchemeActions'),
    'AffineSpace': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSpace'),
    'AffineSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSpaces'),
    'ClosedEmbeddings': ('dzack_research.preamble.categories.schemes.schemes',
     'ClosedEmbeddings'),
    'ClosedSubschemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ClosedSubschemes'),
    'SchemeMonomorphisms': ('dzack_research.preamble.categories.schemes.schemes',
     'SchemeMonomorphisms'),
    'FiberProductSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'FiberProductSchemes'),
    'FiniteTypeSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'FiniteTypeSchemes'),
    'IntegralSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'IntegralSchemes'),
    'IsolatedHypersurfaceSingularity': ('dzack_research.preamble.categories.schemes.singularities',
     'IsolatedHypersurfaceSingularity'),
    'NormalSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'NormalSchemes'),
    'OpenImmersions': ('dzack_research.preamble.categories.schemes.schemes',
     'OpenImmersions'),
    'ProjectivePointBlowups': ('dzack_research.preamble.categories.schemes.blowups', 'ProjectivePointBlowups'),
    'ProjectiveCompleteIntersections': ('dzack_research.preamble.categories.schemes.complete_intersections',
     'ProjectiveCompleteIntersections'),
    'ProjectiveSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSchemes'),
    'ProjectiveSpace': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSpace'),
    'ProjectiveSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSpaces'),
    'ProductProjectiveSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'ProductProjectiveSpaces'),
    'ProductSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ProductSchemes'),
    'QuasiAffineSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'QuasiAffineSchemes'),
    'QuasiProjectiveSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'QuasiProjectiveSchemes'),
    'Schemes': ('dzack_research.preamble.categories.schemes.schemes',
     'Schemes'),
    'SchemeMorphism': ('dzack_research.preamble.categories.schemes.schemes',
     'SchemeMorphism'),
    'SeparatedSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'SeparatedSchemes'),
    'SmoothSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'SmoothSchemes'),
    'Spec': ('dzack_research.preamble.categories.schemes.schemes',
     'Spec'),
    'SchemeBaseChangeFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SchemeBaseChangeFunctor'),
    'SliceBaseChangeAdjunction': ('dzack_research.preamble.categories.schemes.base_change',
     'SliceBaseChangeAdjunction'),
    'SliceCompositionFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SliceCompositionFunctor'),
    'SlicePullbackFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SlicePullbackFunctor'),
    'Curves': ('dzack_research.preamble.categories.schemes.varieties',
     'Curves'),
    'CurveLocalDeltaContribution': ('dzack_research.preamble.categories.schemes.curve_genus', 'CurveLocalDeltaContribution'),
    'ProjectiveCurveNormalizationData': ('dzack_research.preamble.categories.schemes.curve_genus', 'ProjectiveCurveNormalizationData'),
    'rational_quintic_with_nonrational_node_normalization': ('dzack_research.preamble.categories.schemes.curve_genus', 'rational_quintic_with_nonrational_node_normalization'),
    'rational_quintic_with_two_nodes_normalization': ('dzack_research.preamble.categories.schemes.curve_genus', 'rational_quintic_with_two_nodes_normalization'),
    'Curve': ('dzack_research.preamble.categories.schemes.varieties',
     'Curve'),
    'Surfaces': ('dzack_research.preamble.categories.schemes.varieties',
     'Surfaces'),
    'Varieties': ('dzack_research.preamble.categories.schemes.varieties',
     'Varieties'),
    'ConvexPolygon': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolygon'),
    'ConvexPolygons': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolygons'),
    'ConvexPolytope': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolytope'),
    'ConvexPolytopes': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolytopes'),
    'LatticePolygon': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolygon'),
    'LatticePolygons': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolygons'),
    'LatticePolytope': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolytope'),
    'LatticePolytopes': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolytopes'),
    'RegularPolytopes': ('dzack_research.preamble.categories.schemes.polytopes',
     'RegularPolytopes'),
    'ADELogPair': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'ADELogPair'),
    'ADELogPairs': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'ADELogPairs'),
    'SideDecoration': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'SideDecoration'),
    'LogPairs': ('dzack_research.preamble.categories.schemes.log_pairs',
     'LogPairs'),
    'ToricLogPairs': ('dzack_research.preamble.categories.schemes.log_pairs',
     'ToricLogPairs'),
    'ToricFixedPointBlowups': ('dzack_research.preamble.categories.schemes.toric.blowups',
     'ToricFixedPointBlowups'),
    'RationalPolyhedralFans': ('dzack_research.preamble.categories.schemes.toric.fans',
     'RationalPolyhedralFans'),
    'ToricSchemes': ('dzack_research.preamble.categories.schemes.toric.toric_schemes',
     'ToricSchemes'),
    'FiniteGluedInvariantQuotient': ('dzack_research.preamble.categories.schemes.invariant_quotient_gluing',
     'FiniteGluedInvariantQuotient'),
    'glued_invariant_quotient': ('dzack_research.preamble.categories.schemes.invariant_quotient_gluing',
     'glued_invariant_quotient'),
    'ToricGeometricLineBundleCohomologySpaces': ('dzack_research.preamble.categories.schemes.geometric_cohomology',
     'ToricGeometricLineBundleCohomologySpaces'),
    'GeometricFundamentalGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'GeometricFundamentalGroups'),
    'IntegralTopologicalCohomologyGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'IntegralTopologicalCohomologyGroups'),
    'ResolutionIntegralCohomologyGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'ResolutionIntegralCohomologyGroups'),
    'NodalCubic': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'NodalCubic'),
    'NodalCubicNormalization': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'NodalCubicNormalization'),
    'NodalCubicIntegralTopology': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'NodalCubicIntegralTopology'),
    'IntegralSingularCohomologyGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'IntegralSingularCohomologyGroups'),
    'PGL2IntegralTopology': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'PGL2IntegralTopology'),
    'ProjectiveGeneralLinearGroup2': ('dzack_research.preamble.categories.schemes.geometric_cohomology', 'ProjectiveGeneralLinearGroup2'),
    'ToricIntegralSingularCohomologyGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology',
     'ToricIntegralSingularCohomologyGroups'),
    'ToricFundamentalGroups': ('dzack_research.preamble.categories.schemes.geometric_cohomology',
     'ToricFundamentalGroups'),
    'ToricWeightCohomologyComplexes': ('dzack_research.preamble.categories.schemes.geometric_cohomology',
     'ToricWeightCohomologyComplexes'),
    'RelativeAffineFamily': ('dzack_research.preamble.categories.schemes.families',
     'RelativeAffineFamily'),
    'affine_equation_family': ('dzack_research.preamble.categories.schemes.families',
     'affine_equation_family'),
    'HorikawaEnriquesSurface': ('dzack_research.preamble.categories.schemes.enriques_families', 'HorikawaEnriquesSurface'),
    'AT21ADEPair': ('dzack_research.preamble.categories.schemes.ade_surfaces', 'AT21ADEPair'),
    'AT21ToricADEPair': ('dzack_research.preamble.categories.schemes.ade_surfaces', 'AT21ToricADEPair'),
    'AT21ADEDoubleCover': ('dzack_research.preamble.categories.schemes.ade_surfaces', 'AT21ADEDoubleCover'),
    'HesseBertiniFamily': ('dzack_research.preamble.categories.schemes.bertini_families', 'HesseBertiniFamily'),
    'hesse_bertini_family': ('dzack_research.preamble.categories.schemes.bertini_families', 'hesse_bertini_family'),

}

__all__ = [
    'HesseBertiniFamily',
    'hesse_bertini_family',
    'AT21ADEDoubleCover',
    'AT21ADEPair',
    'AT21ToricADEPair',
    'HorikawaEnriquesSurface',
    'ADELogPair',
    'ADELogPairs',
    'SideDecoration',
    'AffineOverlapRefinement',
    'AffineModuleSheaf',
    'AffineSpaceAnalytificationFunctor',
    'AnalyticDiscFamily',
    'CyclicCoverBaseChangeComparison',
    'RelativeCyclicCoverLift',
    'HorikawaK3DoubleCover',
    'HorikawaK3Family',
    'HigherDirectImageSheaf',
    'IntegralLocalSystem',
    'LegendreMonodromyFamily',
    'PointedAnalyticFundamentalGroup',
    'legendre_monodromy_family',
    'AffineSpecFunctor',
    'AffineInvariantQuotientBaseChangeComparison',
    'AffineSchemes',
    'AffineGSchemes',
    'AffineGroupSchemes',
    'AffineGroupSchemeActions',
    'AffineSpace',
    'AffineSpaces',
    'ClosedEmbeddings',
    'ClosedSubschemes',
    'ConvexPolygon',
    'ConvexPolygons',
    'ConvexPolytope',
    'ConvexPolytopes',
    'CoverRefinement',
    'DistinguishedAffineCover',
    'Curves',
    'CurveLocalDeltaContribution',
    'ProjectiveCurveNormalizationData',
    'rational_quintic_with_nonrational_node_normalization',
    'rational_quintic_with_two_nodes_normalization',
    'Curve',
    'SchemeMonomorphisms',
    'FiberProductSchemes',
    'FiniteTypeSchemes',
    'IntegralSchemes',
    'IsolatedHypersurfaceSingularity',
    'LatticePolygon',
    'LatticePolygons',
    'LatticePolytope',
    'LatticePolytopes',
    'RegularPolytopes',
    'LocallyRingedSpaces',
    'RingedCoveringFamily',
    'RingedCoveringOverlap',
    'LogPairs',
    'NormalSchemes',
    'OpenImmersions',
    'ProjectivePointBlowups',
    'ProjectiveCompleteIntersections',
    'ProjectiveSchemes',
    'ProjectiveSpace',
    'ProjectiveSpaces',
    'ProductProjectiveSpaces',
    'ProductSchemes',
    'QuasiAffineSchemes',
    'QuasiCoherentSheaves',
    'QuasiProjectiveSchemes',
    'RationalPolyhedralFans',
    'RingedSpaces',
    'SchemeBaseChangeFunctor',
    'SchemeUnderlyingSpace',
    'SchemeMorphism',
    'Schemes',
    'SeparatedSchemes',
    'SliceBaseChangeAdjunction',
    'SliceCompositionFunctor',
    'SlicePullbackFunctor',
    'SmoothSchemes',
    'Spec',
    'StructureSheaf',
    'Surfaces',
    'ToricLogPairs',
    'ToricFixedPointBlowups',
    'ToricSchemes',
    'ToricGeometricLineBundleCohomologySpaces',
    'GeometricFundamentalGroups',
    'IntegralTopologicalCohomologyGroups',
    'ResolutionIntegralCohomologyGroups',
    'NodalCubic',
    'NodalCubicNormalization',
    'NodalCubicIntegralTopology',
    'IntegralSingularCohomologyGroups',
    'PGL2IntegralTopology',
    'ProjectiveGeneralLinearGroup2',
    'ToricIntegralSingularCohomologyGroups',
    'ToricFundamentalGroups',
    'ToricWeightCohomologyComplexes',
    'RelativeAffineFamily',
    'affine_equation_family',
    'Varieties',
    'FiniteGluedInvariantQuotient',
    'glued_invariant_quotient',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
