'Owned algebraic-geometry and polyhedral categories.'

from importlib import import_module as _import_module

_EXPORTS = {
    'AffineSpecFunctor': ('dzack_research.preamble.categories.schemes.affine_spec',
     'AffineSpecFunctor'),
    'SpecFunctor': ('dzack_research.preamble.categories.schemes.affine_spec',
     'SpecFunctor'),
    'affine_spec_functor': ('dzack_research.preamble.categories.schemes.affine_spec',
     'affine_spec_functor'),
    'AffineModuleSheaf': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'AffineModuleSheaf'),
    'CoverRefinement': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'CoverRefinement'),
    'DistinguishedAffineCover': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'DistinguishedAffineCover'),
    'LocallyRingedSpaces': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'LocallyRingedSpaces'),
    'QuasiCoherentSheaves': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'QuasiCoherentSheaves'),
    'RingedSpaces': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'RingedSpaces'),
    'SchemeUnderlyingSpace': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'SchemeUnderlyingSpace'),
    'StructureSheaf': ('dzack_research.preamble.categories.schemes.ringed_spaces',
     'StructureSheaf'),
    'AffineSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSchemes'),
    'AffineSpace': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSpace'),
    'AffineSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'AffineSpaces'),
    'ClosedEmbeddings': ('dzack_research.preamble.categories.schemes.schemes',
     'ClosedEmbeddings'),
    'ClosedSubschemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ClosedSubschemes'),
    'SchemeMonomorphisms': ('dzack_research.preamble.categories.schemes.schemes',
     'SchemeMonomorphisms'),
    'FiberProductSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'FiberProductSchemes'),
    'FiniteTypeSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'FiniteTypeSchemes'),
    'IntegralSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'IntegralSchemes'),
    'NormalSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'NormalSchemes'),
    'OpenImmersions': ('dzack_research.preamble.categories.schemes.schemes',
     'OpenImmersions'),
    'ProjectiveSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSchemes'),
    'ProjectiveSpace': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSpace'),
    'ProjectiveSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'ProjectiveSpaces'),
    'ProductProjectiveSpaces': ('dzack_research.preamble.categories.schemes.schemes',
     'ProductProjectiveSpaces'),
    'ProductSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'ProductSchemes'),
    'QuasiAffineSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'QuasiAffineSchemes'),
    'QuasiProjectiveSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'QuasiProjectiveSchemes'),
    'Schemes': ('dzack_research.preamble.categories.schemes.schemes',
     'Schemes'),
    'SchemeMorphism': ('dzack_research.preamble.categories.schemes.schemes',
     'SchemeMorphism'),
    'SeparatedSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'SeparatedSchemes'),
    'SmoothSchemes': ('dzack_research.preamble.categories.schemes.schemes',
     'SmoothSchemes'),
    'Spec': ('dzack_research.preamble.categories.schemes.schemes',
     'Spec'),
    'refine_scheme': ('dzack_research.preamble.categories.schemes.schemes',
     'refine_scheme'),
    'refine_scheme_morphism': ('dzack_research.preamble.categories.schemes.schemes',
     'refine_scheme_morphism'),
    'refine_closed_subscheme': ('dzack_research.preamble.categories.schemes.schemes',
     'refine_closed_subscheme'),
    'scheme_fiber_product': ('dzack_research.preamble.categories.schemes.schemes',
     'scheme_fiber_product'),
    'scheme_product': ('dzack_research.preamble.categories.schemes.schemes',
     'scheme_product'),
    'SchemeBaseChangeFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SchemeBaseChangeFunctor'),
    'SliceBaseChangeAdjunction': ('dzack_research.preamble.categories.schemes.base_change',
     'SliceBaseChangeAdjunction'),
    'SliceCompositionFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SliceCompositionFunctor'),
    'SlicePullbackFunctor': ('dzack_research.preamble.categories.schemes.base_change',
     'SlicePullbackFunctor'),
    'scheme_base_change_functor': ('dzack_research.preamble.categories.schemes.base_change',
     'scheme_base_change_functor'),
    'slice_base_change_adjunction': ('dzack_research.preamble.categories.schemes.base_change',
     'slice_base_change_adjunction'),
    'Curves': ('dzack_research.preamble.categories.schemes.varieties',
     'Curves'),
    'Surfaces': ('dzack_research.preamble.categories.schemes.varieties',
     'Surfaces'),
    'Varieties': ('dzack_research.preamble.categories.schemes.varieties',
     'Varieties'),
    'ConvexPolygon': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolygon'),
    'ConvexPolygons': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolygons'),
    'ConvexPolytope': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolytope'),
    'ConvexPolytopes': ('dzack_research.preamble.categories.schemes.polytopes',
     'ConvexPolytopes'),
    'LatticePolygon': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolygon'),
    'LatticePolygons': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolygons'),
    'LatticePolytope': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolytope'),
    'LatticePolytopes': ('dzack_research.preamble.categories.schemes.polytopes',
     'LatticePolytopes'),
    'ADELogPair': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'ADELogPair'),
    'ADELogPairs': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'ADELogPairs'),
    'SideDecoration': ('dzack_research.preamble.categories.schemes.ade_surfaces',
     'SideDecoration'),
    'LogPair': ('dzack_research.preamble.categories.schemes.log_pairs',
     'LogPair'),
    'LogPairs': ('dzack_research.preamble.categories.schemes.log_pairs',
     'LogPairs'),
    'ToricLogPair': ('dzack_research.preamble.categories.schemes.log_pairs',
     'ToricLogPair'),
    'ToricLogPairs': ('dzack_research.preamble.categories.schemes.log_pairs',
     'ToricLogPairs'),
    'RationalPolyhedralFans': ('dzack_research.preamble.categories.schemes.toric.fans',
     'RationalPolyhedralFans'),
    'ToricSchemes': ('dzack_research.preamble.categories.schemes.toric.toric_schemes',
     'ToricSchemes'),
    'ToricVariety': ('dzack_research.preamble.categories.schemes.toric.toric_schemes',
     'ToricVariety'),
    'FiniteGluedInvariantQuotient': ('dzack_research.preamble.categories.schemes.invariant_quotient_gluing',
     'FiniteGluedInvariantQuotient'),
    'glued_invariant_quotient': ('dzack_research.preamble.categories.schemes.invariant_quotient_gluing',
     'glued_invariant_quotient'),
}

__all__ = [
    'ADELogPair',
    'ADELogPairs',
    'SideDecoration',
    'AffineModuleSheaf',
    'AffineSpecFunctor',
    'SpecFunctor',
    'affine_spec_functor',
    'AffineSchemes',
    'AffineSpace',
    'AffineSpaces',
    'ClosedEmbeddings',
    'ClosedSubschemes',
    'ConvexPolygon',
    'ConvexPolygons',
    'ConvexPolytope',
    'ConvexPolytopes',
    'CoverRefinement',
    'DistinguishedAffineCover',
    'Curves',
    'SchemeMonomorphisms',
    'FiberProductSchemes',
    'FiniteTypeSchemes',
    'IntegralSchemes',
    'LatticePolygon',
    'LatticePolygons',
    'LatticePolytope',
    'LatticePolytopes',
    'LocallyRingedSpaces',
    'LogPair',
    'LogPairs',
    'NormalSchemes',
    'OpenImmersions',
    'ProjectiveSchemes',
    'ProjectiveSpace',
    'ProjectiveSpaces',
    'ProductProjectiveSpaces',
    'ProductSchemes',
    'QuasiAffineSchemes',
    'QuasiCoherentSheaves',
    'QuasiProjectiveSchemes',
    'RationalPolyhedralFans',
    'RingedSpaces',
    'SchemeBaseChangeFunctor',
    'SchemeUnderlyingSpace',
    'SchemeMorphism',
    'Schemes',
    'SeparatedSchemes',
    'SliceBaseChangeAdjunction',
    'SliceCompositionFunctor',
    'SlicePullbackFunctor',
    'SmoothSchemes',
    'Spec',
    'StructureSheaf',
    'Surfaces',
    'ToricLogPair',
    'ToricLogPairs',
    'ToricSchemes',
    'ToricVariety',
    'Varieties',
    'refine_closed_subscheme',
    'refine_scheme',
    'refine_scheme_morphism',
    'scheme_base_change_functor',
    'scheme_fiber_product',
    'scheme_product',
    'slice_base_change_adjunction',
    'FiniteGluedInvariantQuotient',
    'glued_invariant_quotient',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
