r"""Projective complete intersections with their selected regular sequence.

A complete intersection ``X = V_+(f_1, ..., f_r) <= P^n_R`` is a closed
subscheme of projective space together with the homogeneous equations cutting
it out, where ``f_1, ..., f_r`` is a regular sequence.  It is constructed by
the closed-subscheme construction of ``P^n_R`` with the placement
``ProjectiveCompleteIntersections(R)``; the category adds no datum of its own:
its codimension, multidegree and ambient are read off the equations and the
inclusion.

The base change ``X_{R'} = X x_{Spec R} Spec R'`` along ``g: R -> R'`` is the
closed subscheme of ``P^n_{R'}`` cut out by the base-changed equations, and it
is constructed as an object of ``FiberProductSchemes(R')``: its left projection
is ``X_{R'} -> X`` and its right projection is the structure morphism.
"""

from sage.misc.cachefunc import cached_method
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.algebras.free_algebras import SymmetricAlgebras
from dzack_research.preamble.categories.rings.ring_foundation import (
    LocalizationRings,
    OwnedCategoryOverBaseRing,
    OwnedFields,
    _engine_ring,
    _own_ring,
)
from dzack_research.preamble.categories.schemes.schemes import (
    ClosedSubschemes,
    FiberProductSchemes,
    ProjectiveSpaces,
    SchemeFiberProductConstruction,
    SchemeMorphism,
    Schemes,
    _engine_projective_subscheme,
    _projective_closed_subscheme,
    _projective_equation_family,
    _engine_scheme,
    _equation_family,
    _native_scheme_mor,
    _scheme_mor_category,
    _structure_morphism_rule,
)
from dzack_research.preamble.categories.sets.finite_families import finite_family


def _complete_intersection_base_supported(base) -> bool:
    r"""Whether the base is a field, a localization of one, or a polynomial algebra over one.

    Over these bases the homogeneous coordinate ring is regular.  The selected
    sequence is checked by successive nonzerodivisors, not just final height.
    """
    match base:
        case _ if base in OwnedFields():
            return True
        case _ if base in LocalizationRings():
            return _complete_intersection_base_supported(base.localization_source())
        case _ if base.base_ring() in OwnedFields():
            return base in SymmetricAlgebras(base.base_ring())
        case _:
            return False


def _projective_complete_intersection(ambient, equations, placements=(), **level_data):
    r"""``V_+(f_1, ..., f_r) <= P^n_R`` as a complete intersection.

    The equations are the selected regular sequence.  The closed subscheme is
    constructed once, with its complete-intersection placement and any further
    placement a construction states (the fibre-product placement of a base
    change); the regular-sequence criterion is checked on the native ideal
    before the object is constructed.
    """
    base = ambient.scheme_base_ring()
    assert ambient in ProjectiveSpaces(base), (
        f"a complete intersection V_+(f_1, ..., f_r) is constructed here only inside projective "
        f"space P^n over {base}, but {ambient} is in {ambient.category()}"
    )
    assert _complete_intersection_base_supported(base), (
        f"the regular-sequence test for a complete intersection in {ambient} is implemented only "
        f"over a field, a localization of a supported ring, or a polynomial ring over a field, "
        f"but the base ring is {base}"
    )
    family = _projective_equation_family(_equation_family(equations))
    assert family.cardinality() > 0, (
        f"a complete intersection in {ambient} needs at least one equation, but none were given"
    )
    engine = _engine_projective_subscheme(_engine_scheme(ambient), family)
    assert _is_regular_sequence(engine), (
        f"the equations {family} do not form a regular sequence in the homogeneous coordinate "
        f"ring of {ambient}, so V_+ of them is not a complete intersection"
    )
    return _projective_closed_subscheme(
        ambient, family, placements=(ProjectiveCompleteIntersections(base), *placements),
        _engine=engine, **level_data,
    )


def _is_regular_sequence(engine):
    r"""Decide regularity of the selected equations before allocating the scheme.

    Engine adapter (``OWN-06``): flatten a polynomial coefficient tower by
    Sage's polynomial-ring isomorphism, then use its ideal-quotient engine.
    No parameter is inverted: this tests the sequence over the stated base,
    not over its fraction field.

    If ``I`` is generated by the preceding equations, multiplication by
    ``f`` on ``S/I`` has kernel ``(I : (f))/I``.  It is injective exactly when
    ``I : (f) = I``.  The final quotient must also be nonzero (Stacks, 00LF).
    Final height alone does not suffice for a chosen global sequence:
    ``t*x, t*y, 1-t`` has height three, but ``x`` annihilates ``t*y`` modulo
    ``(t*x)``.  Sage's maintained ``MPolynomialIdeal.quotient`` computes each
    colon ideal; no local Groebner or regular-sequence algorithm is copied.
    """
    original = engine.ambient_space().coordinate_ring()
    flatten = original.flattening_morphism()
    ring = flatten.codomain()
    prefix = ring.ideal(ring.zero())
    for equation in engine.defining_polynomials():
        principal = ring.ideal(flatten(equation))
        match prefix.quotient(principal) == prefix:
            case False:
                return False
            case True:
                prefix = prefix + principal
    return ring.one() not in prefix


class ProjectiveCompleteIntersections(OwnedCategoryOverBaseRing):
    r"""Closed complete intersections in projective space over a regular base.

    Over a field, a localization, and a polynomial parameter algebra over a
    field, the homogeneous coordinate ring is regular.  Each selected equation
    must be a nonzerodivisor modulo its predecessors, and the final quotient
    must be nonzero; the engine checks those exact conditions before placement.
    """

    def an_object(self):
        r"""The point ``V_+(x) <= P^1``, cut out by one linear form."""
        line = ProjectiveSpaces(self.base_ring())(1)
        x, _y = line.homogeneous_coordinate_generators()
        return self(line, x)

    def _call_(self, ambient, *equations):
        r"""``V_+(f_1, ..., f_r) <= P^n_R`` for a regular sequence of homogeneous equations.

        The equations are given one by one or as one finite family.
        """
        assert ambient.scheme_base_ring() is self.base_ring(), (
            f"cannot construct a complete intersection of {self} in {ambient}: it lies over "
            f"{ambient.scheme_base_ring()}, not over {self.base_ring()}"
        )
        return _projective_complete_intersection(ambient, equations)

    def _repr_object_names(self):
        return f"projective complete intersections over {self.base_ring()}"

    def super_categories(self):
        return [Schemes(self.base_ring()).Projective(), ClosedSubschemes(self.base_ring())]

    class ParentMethods:
        def is_complete_intersection(self) -> bool:
            return True

        def complete_intersection_ambient(self):
            r"""The projective space ``P^n_R`` this complete intersection is cut out of."""
            return self.inclusion().codomain()

        def defining_degrees(self):
            r"""The degrees ``d_1, ..., d_r`` of the selected regular sequence."""
            integers = _own_ring(SageZZ)
            return finite_family(
                tuple(
                    integers(int(equation.degree()))
                    for equation in self.defining_equations()
                ),
                name="Complete-intersection defining degrees",
            )

        def complete_intersection_codimension(self):
            return self.defining_equations().cardinality()

        def expected_dimension(self):
            return self.complete_intersection_ambient().relative_dimension() - _own_ring(
                SageZZ
            )(int(self.complete_intersection_codimension()))

        def family_base_scheme(self):
            return self.base_scheme()

        def family_morphism(self):
            r"""Return the relative projective complete-intersection morphism to its base."""
            return self.structure_morphism()

        def base_change_source_complete_intersection(self):
            r"""``X`` for ``X_{R'} = X x_{Spec R} Spec R'``: the domain of the left cospan leg."""
            assert self in FiberProductSchemes(self.scheme_base_ring()), (
                f"{self} was not constructed as a base change X x_(Spec R) Spec R', so it has "
                "no original complete intersection X"
            )
            return self.fiber_product_cospan()[0].domain()

        def base_change_projection(self):
            r"""The projection ``X_{R'} -> X`` of the scalar base-change pullback."""
            assert self in FiberProductSchemes(self.scheme_base_ring()), (
                f"{self} was not constructed as a base change X x_(Spec R) Spec R', so it has "
                "no projection to an original complete intersection X"
            )
            return self.left_projection()

        def base_change(self, ring_map):
            r"""Base change through the scheme owner; the new equations decide regularity.

            A regular sequence need not stay regular under nonflat base
            change.  The scheme owner always constructs the base-changed
            closed subscheme, and keeps complete-intersection placement only
            when the new homogeneous ideal satisfies the criterion.
            """
            return self.scheme_category().base_change_functor(ring_map)(self)

        def adjunction_twist_degree(self):
            r"""Return ``sum(d_i) - n - 1`` in ``K_X = O_X(sum d_i-n-1)``.

            This is the integer in the projective complete-intersection
            adjunction formula.  The canonical bundle and the adjunction
            isomorphism are returned by :meth:`canonical_line_bundle` and
            :meth:`adjunction_isomorphism`.
            """
            integers = _own_ring(SageZZ)
            ambient_dimension = integers(
                int(self.complete_intersection_ambient().relative_dimension())
            )
            return (
                sum(self.defining_degrees(), integers.zero())
                - ambient_dimension
                - integers.one()
            )

        def is_gorenstein(self) -> bool:
            r"""Return ``True``: a quotient of a regular ring by a regular sequence is Gorenstein."""
            return True

        def is_normal(self) -> bool:
            r"""Decide normality by Serre's criterion in characteristic zero.

            A complete intersection is Cohen--Macaulay, hence satisfies ``S_2``.
            Thus normality is equivalent to ``R_1``.  Sage's projective
            Jacobian ideal is computed on the affine cone: if ``X`` has
            dimension ``d >= 1``, ``R_1`` says its projective singular locus
            has dimension at most ``d-2``, equivalently the affine-cone
            Jacobian locus has dimension at most ``d-1``.  In dimension zero,
            characteristic zero makes normality equivalent to smoothness.
            """
            base = self.scheme_base_ring()
            assert base in OwnedFields(), (
                f"normality of the complete intersection {self} is decided here only over a field, "
                f"but its base ring {base} is not a field"
            )
            assert int(_engine_ring(base).characteristic()) == 0, (
                f"normality of the complete intersection {self} is decided here only in "
                f"characteristic zero, but {base} has characteristic {_engine_ring(base).characteristic()}"
            )
            dimension = int(self.expected_dimension())
            if dimension == 0:
                return bool(self.is_smooth())
            singular_cone_dimension = int(_engine_scheme(self).Jacobian().dimension())
            return singular_cone_dimension <= dimension - 1

        def projective_degree(self):
            r"""Return the complete-intersection degree ``prod d_i``."""
            degree = _own_ring(SageZZ).one()
            for value in self.defining_degrees():
                degree *= value
            return degree

        def anticanonical_twist_degree(self):
            r"""Return ``n + 1 - sum(d_i)`` for ``-K_X``."""
            return -self.adjunction_twist_degree()

        @cached_method
        def restricted_ambient_canonical_bundle(self):
            r"""``omega_P|_X = O_X(-n-1)``, the restricted canonical bundle of the ambient."""
            return self.complete_intersection_ambient().canonical_line_bundle().restrict_to(self)

        @cached_method
        def normal_determinant_line_bundle(self):
            r"""``det N_{X/P} = O_X(sum d_i)`` for the selected regular sequence."""
            return self.O(sum(self.defining_degrees()))

        @cached_method
        def adjunction_isomorphism(self):
            r"""The adjunction isomorphism ``omega_X ~= omega_P|_X tensor det N_{X/P}``.

            Its domain is the canonical bundle ``O_X(sum d_i - n - 1)`` and its
            codomain is the tensor product of the restricted ambient canonical
            bundle with the determinant of the normal bundle.
            """
            canonical = self.O(self.adjunction_twist_degree())
            target = self.restricted_ambient_canonical_bundle().tensor_product(
                self.normal_determinant_line_bundle()
            )
            return canonical.canonical_isomorphism_to(target)

        def adjunction_target(self):
            r"""``omega_P|_X tensor det N_{X/P}``, the codomain of the adjunction isomorphism."""
            return self.adjunction_isomorphism().codomain()

        def canonical_line_bundle(self):
            return self.adjunction_isomorphism().domain()

        canonical_bundle = canonical_line_bundle

        @cached_method
        def anticanonical_line_bundle(self):
            return self.canonical_line_bundle().dual_sheaf()

        def anticanonical_bundle(self, *args, **kwargs):
            return self.anticanonical_line_bundle(*args, **kwargs)

        def is_del_pezzo(self) -> bool:
            r"""Decide the del Pezzo condition for a smooth complete-intersection surface.

            In this represented regime adjunction constructs ``-K_X`` as an
            actual restricted projective line bundle.  Smoothness is decided
            by Sage's exact projective-subscheme Jacobian calculation and the
            ampleness question is delegated to that line-bundle object.
            """
            assert self.scheme_base_ring() in OwnedFields(), (
                f"whether {self} is a del Pezzo surface is decided here only over a field, but its "
                f"base ring {self.scheme_base_ring()} is not a field"
            )
            if int(self.expected_dimension()) != 2:
                return False
            if not bool(self.is_smooth()):
                return False
            return bool(self.anticanonical_line_bundle().is_ample())

        @cached_method
        def integral_topology(self):
            from dzack_research.preamble.categories.schemes.geometric_cohomology import (
                _QuarticK3IntegralTopology,
            )

            return _QuarticK3IntegralTopology(self)

        def integral_singular_cohomology(self, degree):
            return self.integral_topology().integral_cohomology(degree)

        @cached_method
        def hodge_structure(self):
            from dzack_research.preamble.categories.schemes.geometric_cohomology import (
                _QuarticK3HodgeData,
            )

            return _QuarticK3HodgeData(self)

        def del_pezzo_degree(self):
            r"""Return ``(-K_X)^2 = (n + 1 - sum d_i)^2 prod d_i`` for a del Pezzo complete intersection."""
            assert self.is_del_pezzo(), (
                f"the degree (-K)^2 of a del Pezzo surface is undefined for {self}: it is not a "
                "del Pezzo surface"
            )
            coefficient = self.anticanonical_twist_degree()
            return coefficient**2 * self.projective_degree()


__all__ = [
    "ProjectiveCompleteIntersections",
]
