r"""Relative projectivization of represented quasi-coherent modules.

For an affine scheme ``X = Spec(A)`` and a finitely presented ``A``-module
``M``, this constructs

``P_X(M~) = Proj_X(Sym_A(M))``

from the standard opens determined by the selected generators of ``M``.  If
``M = A^n / R`` on generators ``e_i``, then on ``D_+(e_i)`` the coordinate
algebra is generated by the ratios ``e_j/e_i`` and the relations are obtained
by dehomogenizing the selected linear relations of ``M``.  Thus the
construction uses the existing symmetric-algebra presentation and affine
gluing owners rather than a second projective-space algorithm.

The normalization is the quotient convention of Stacks Project, Tag 01OA:
``P(M)`` carries ``O(1)`` and the universal surjection
``pi^* M~ -> O(1)``.
"""

from sage.misc.cachefunc import cached_function, cached_method
from sage.structure.sage_object import SageObject

from dzack_research.preamble.categories.algebras.algebras import Algebras
from dzack_research.preamble.categories.modules.fibered_modules import (
    ModulesOverCommutativeRings,
)
from dzack_research.preamble.categories.modules.framed.framed_free_modules import (
    FramedFreeModules,
)
from dzack_research.preamble.categories.modules.pure.modules import (
    ModulesWithChosenFinitePresentation,
)
from dzack_research.preamble.categories.schemes.schemes import (
    Schemes,
    _affine_morphism_from_pullback,
)
from dzack_research.preamble.categories.rings.ring_foundation import OwnedRings
from dzack_research.preamble.categories.sets.indexed_families import (
    finite_indexed_family,
)
from dzack_research.preamble.categories.sets.finite_ordered_sets import (
    finite_ordered_set,
)


def _ratio_name(module, denominator_label, numerator_label) -> str:
    ranking = module.module_generating_set().ranking_map()
    return (
        f"p{int(ranking(numerator_label))}_over_"
        f"p{int(ranking(denominator_label))}"
    )


def _chart_polynomial_algebra(module, chart_label):
    base = module.base_ring()
    labels = tuple(module.module_generating_set())
    names = tuple(
        _ratio_name(module, chart_label, label)
        for label in labels
        if label != chart_label
    )
    return base.free_module(names).symmetric_algebra()


def _chart_algebra(module, chart_label):
    r"""Return the degree-zero standard-open algebra on ``D_+(chart_label)``."""
    polynomial = _chart_polynomial_algebra(module, chart_label)
    labels = tuple(module.module_generating_set())
    ranking = module.module_generating_set().ranking_map()
    chart_position = int(ranking(chart_label))
    structure = polynomial.algebra_structure_morphism()
    relations = []
    if module in ModulesWithChosenFinitePresentation(module.base_ring()):
        matrix = module.presentation_matrix()
        for row in range(matrix.nrows()):
            relation = structure(module.base_ring()(matrix[row, chart_position]))
            for label in labels:
                if label == chart_label:
                    continue
                position = int(ranking(label))
                coefficient = module.base_ring()(matrix[row, position])
                if coefficient:
                    relation += structure(coefficient) * polynomial.algebra_generator(
                        _ratio_name(module, chart_label, label)
                    )
            if relation != polynomial.zero():
                relations.append(relation)
    return (
        polynomial
        if not relations
        else polynomial.quotient_by_relations(tuple(relations))
    )


def _chart_ratio(module, chart_algebra, denominator_label, numerator_label):
    if denominator_label == numerator_label:
        return chart_algebra.one()
    return chart_algebra.algebra_generator(
        _ratio_name(module, denominator_label, numerator_label)
    )


def _chart_transition(module, charts, source_label, target_label, scheme_base_ring):
    r"""Return the standard ratio-coordinate isomorphism on two Proj charts."""
    source_chart = charts[source_label]
    target_chart = charts[target_label]
    source_algebra = source_chart.coordinate_algebra()
    target_algebra = target_chart.coordinate_algebra()
    source_ratio = _chart_ratio(
        module, source_algebra, source_label, target_label
    )
    target_ratio = _chart_ratio(
        module, target_algebra, target_label, source_label
    )
    source_overlap = source_chart.distinguished_open(source_ratio)
    target_overlap = target_chart.distinguished_open(target_ratio)
    source_restriction = source_overlap.inclusion().coordinate_algebra_morphism()
    inverse_ratio = source_restriction(source_ratio).inverse_of_unit()

    images = {}
    for label in module.module_generating_set():
        if label == target_label:
            continue
        target_name = _ratio_name(module, target_label, label)
        images[target_name] = (
            inverse_ratio
            if label == source_label
            else source_restriction(
                _chart_ratio(module, source_algebra, source_label, label)
            )
            * inverse_ratio
        )
    into_source = target_algebra.Mor(source_overlap.coordinate_algebra())(images)
    pullback = target_overlap.coordinate_algebra().induced_morphism(into_source)
    forward = Schemes(scheme_base_ring).Mor(source_overlap, target_overlap)(pullback)

    target_restriction = target_overlap.inclusion().coordinate_algebra_morphism()
    inverse_target_ratio = target_restriction(target_ratio).inverse_of_unit()
    inverse_images = {}
    for label in module.module_generating_set():
        if label == source_label:
            continue
        source_name = _ratio_name(module, source_label, label)
        inverse_images[source_name] = (
            inverse_target_ratio
            if label == target_label
            else target_restriction(
                _chart_ratio(module, target_algebra, target_label, label)
            )
            * inverse_target_ratio
        )
    into_target = source_algebra.Mor(target_overlap.coordinate_algebra())(
        inverse_images
    )
    inverse_pullback = source_overlap.coordinate_algebra().induced_morphism(
        into_target
    )
    inverse = Schemes(scheme_base_ring).Mor(target_overlap, source_overlap)(
        inverse_pullback
    )
    return Schemes(scheme_base_ring).Core().Mor(
        source_overlap,
        target_overlap,
    )(forward, inverse)


def _chart_base_change_pullback(source_chart, target_chart, ring_map):
    r"""Return ``O(source_chart) -> O(target_chart)`` for coefficient base change.

    The intermediate scalar extension is owned by the algebra base-change
    adjunction.  Its ratio generators map to the identically labelled ratio
    generators of the projectivization constructed from the base-changed
    module; this is the standard ``Proj(Sym(M))`` base-change comparison.
    """
    source = source_chart.coordinate_algebra()
    target = target_chart.coordinate_algebra()
    algebras = Algebras(source.base_ring()).Associative().Unital().Commutative()
    adjunction = algebras.base_change_adjunction(ring_map)
    extended = adjunction.left_adjoint()(source)
    unit = adjunction.unit(source)
    target_algebras = Algebras(target.base_ring()).Associative().Unital().Commutative()
    if extended is target:
        comparison = target_algebras.Mor(target, target).identity()
    else:
        source_labels = extended.algebra_generating_set()
        target_labels = target.algebra_generating_set()
        if source_labels != target_labels:
            raise ValueError(
                "projectivization base change must preserve the standard ratio generators"
            )
        comparison = target_algebras.Mor(extended, target)(
            {
                label: target.algebra_generator(label)
                for label in source_labels
            }
        )

    def image(element):
        restricted_value = unit(source(element))
        return target(comparison(extended(restricted_value)))

    return OwnedRings().Mor(source, target).elementwise(image)


class AffineProjectivizationBaseChangeComparison(SageObject):
    r"""The represented base-change square for one affine projectivization."""

    def __init__(self, projectivization, ring_map) -> None:
        self._projectivization = projectivization
        self._ring_map = ring_map
        source_sheaf = projectivization.projectivization_source_sheaf()
        source_scheme = source_sheaf.scheme()
        source_module = projectivization.projectivization_module()
        if ring_map.domain() is not source_module.base_ring():
            raise ValueError(
                "projectivization base change starts at the affine source coordinate ring"
            )
        changed_ring = ring_map.codomain()
        changed_scheme = changed_ring.affine_spectrum(
            base_ring=source_scheme.scheme_base_ring()
        )
        changed_module = source_module.base_change(ring_map)
        changed_sheaf = changed_scheme.associated_module_sheaf(changed_module)
        changed_family = changed_sheaf.projectivization()
        changed_total = changed_family.arrow().domain()

        source_atlas = projectivization.finite_affine_atlas()
        changed_atlas = changed_total.finite_affine_atlas()
        if source_atlas.chart_index_set() != changed_atlas.chart_index_set():
            raise ValueError(
                "projectivization base change must retain the standard chart index set"
            )
        local_maps = finite_indexed_family(
            changed_atlas.chart_index_set(),
            lambda label: source_atlas.chart_embedding(label)
            * _affine_morphism_from_pullback(
                changed_atlas.chart(label),
                source_atlas.chart(label),
                _chart_base_change_pullback(
                    source_atlas.chart(label),
                    changed_atlas.chart(label),
                    ring_map,
                ),
            ),
            name="Chart maps of projectivization base change",
        )
        to_original = changed_total.Mor(projectivization)(local_maps)
        base_morphism = _affine_morphism_from_pullback(
            changed_scheme,
            source_scheme,
            ring_map,
        )
        changed_projection = changed_family.arrow()
        if (
            projectivization.projectivization_projection() * to_original
            != base_morphism * changed_projection
        ):
            raise ArithmeticError(
                "the projectivization base-change comparison does not commute over the affine base"
            )

        self._changed_source_sheaf = changed_sheaf
        self._changed_projectivization = changed_family
        self._base_morphism = base_morphism
        self._projection_to_original = to_original

    def projectivization(self):
        return self._projectivization

    def ring_map(self):
        return self._ring_map

    def base_morphism(self):
        return self._base_morphism

    def changed_source_sheaf(self):
        return self._changed_source_sheaf

    def changed_projectivization(self):
        return self._changed_projectivization

    def projection_to_original(self):
        r"""Return ``P(F_A') -> P(F)`` in the base-change square."""
        return self._projection_to_original

    def projection_to_changed_base(self):
        r"""Return ``P(F_A') -> Spec(A')`` in the base-change square."""
        return self.changed_projectivization().arrow()

    def universal_quotient(self):
        r"""Return the universal quotient on the base-changed projectivization."""
        return self.changed_projectivization().arrow().domain().universal_quotient()


class _AffineProjectivizationSchemeEngine:
    r"""The retained relative-Proj data on the glued standard-open scheme."""

    def __init__(
        self,
        projectivization_source_sheaf,
        projectivization_module,
        projectivization_symmetric_algebra,
        **rest,
    ) -> None:
        self._projectivization_source_sheaf = projectivization_source_sheaf
        self._projectivization_module = projectivization_module
        self._projectivization_symmetric_algebra = projectivization_symmetric_algebra
        super().__init__(**rest)

    def projectivization_source_sheaf(self):
        return self._projectivization_source_sheaf

    def projectivization_module(self):
        return self._projectivization_module

    def symmetric_algebra(self):
        r"""Return ``Sym(M)``, the graded algebra defining this relative Proj."""
        return self._projectivization_symmetric_algebra

    @cached_method
    def projectivization_projection(self):
        r"""Return ``pi : P(M~) -> Spec(A)`` from the chart algebra structures."""
        base_scheme = self.projectivization_source_sheaf().scheme()
        datum = self.gluing_datum()
        local_maps = finite_indexed_family(
            datum.chart_index_set(),
            lambda label: _affine_morphism_from_pullback(
                datum.chart(label),
                base_scheme,
                datum.chart(label).coordinate_algebra().algebra_structure_morphism(),
            ),
            name="Relative-projectivization chart maps to the base",
        )
        return self.Mor(base_scheme)(local_maps)

    @cached_method
    def tautological_line_bundle(self):
        r"""Return ``O_{P(M)}(1)`` on the selected standard affine atlas."""
        from dzack_research.preamble.categories.schemes.ringed_spaces import (
            QuasiCoherentSheaves,
        )

        atlas = self.finite_affine_atlas()
        module = self.projectivization_module()
        units = {}
        for source_label, target_label in atlas.transition_index_set():
            overlap = atlas.overlap(source_label, target_label)
            restriction = overlap.inclusion().coordinate_algebra_morphism()
            units[source_label, target_label] = restriction(
                _chart_ratio(
                    module,
                    atlas.chart(source_label).coordinate_algebra(),
                    source_label,
                    target_label,
                )
            )
        return (
            QuasiCoherentSheaves(self)
            .Invertible()
            .WithChosenTrivialization()(atlas, units)
        )

    @cached_method
    def pulled_source_sheaf(self):
        r"""Return the represented pullback ``pi^*M~`` on the standard atlas."""
        from dzack_research.preamble.categories.schemes.gluing import (
            FiniteAtlasModuleGluingData,
        )

        atlas = self.finite_affine_atlas()
        module = self.projectivization_module()
        fibered = ModulesOverCommutativeRings()
        local_modules = {
            label: fibered.cocartesian_transport(
                atlas.chart(label).coordinate_algebra().algebra_structure_morphism()
            )(module)
            for label in atlas.chart_indices()
        }

        def identity_images(label, _domain, codomain):
            return codomain.module_generator(label)

        transitions = {
            pair: (identity_images, identity_images)
            for pair in atlas.transition_index_set()
        }
        return FiniteAtlasModuleGluingData(atlas)(
            local_modules,
            transitions,
        ).sheaf()

    @cached_method
    def universal_quotient(self):
        r"""Return the universal quotient ``pi^*M~ -> O(1)`` as a QCoh morphism."""
        from dzack_research.preamble.categories.schemes.ringed_spaces import (
            QuasiCoherentSheaves,
        )

        atlas = self.finite_affine_atlas()
        module = self.projectivization_module()
        pulled = self.pulled_source_sheaf()
        line_bundle = self.tautological_line_bundle()
        line = line_bundle.module_sheaf()
        source_datum = pulled.gluing_datum()
        target_datum = line.gluing_datum()

        local_maps = {}
        for chart_label in atlas.chart_indices():
            source = source_datum.local_module(chart_label)
            target = target_datum.local_module(chart_label)
            basis_label = next(iter(target.module_generating_set()))
            basis = target.module_generator(basis_label)
            chart_algebra = atlas.chart(chart_label).coordinate_algebra()
            local_maps[chart_label] = source.module_category().Mor(source, target)(
                {
                    label: target.scalar_multiple(
                        _chart_ratio(module, chart_algebra, chart_label, label),
                        basis,
                    )
                    for label in module.module_generating_set()
                }
            )
        return QuasiCoherentSheaves(self).Mor(pulled, line)(local_maps)

    @cached_method(key=lambda self, ring_map: id(ring_map))
    def projectivization_base_change(self, ring_map):
        r"""Return the represented affine base-change comparison along ``ring_map``."""
        return AffineProjectivizationBaseChangeComparison(self, ring_map)


@cached_function(key=lambda sheaf: id(sheaf))
def _affine_projectivization(sheaf):
    r"""Construct ``P_X(F) -> X`` for an affine represented quasi-coherent sheaf."""
    scheme = sheaf.scheme()
    base = scheme.scheme_base_ring()
    if scheme not in Schemes(base).Affine():
        raise TypeError("the affine projectivization constructor requires an affine base scheme")
    module = sheaf.module()
    represented = (
        module in ModulesWithChosenFinitePresentation(module.base_ring())
        or module in FramedFreeModules(module.base_ring())
    )
    if not represented:
        raise AssertionError(
            "relative Proj is presently materialized for affine sheaves with a finite free framing or chosen finite module presentation"
        )
    labels = module.module_generating_set()
    if labels.cardinality().is_finite() is not True:
        raise AssertionError(
            "the represented standard-open Proj cover presently requires a finite module framing"
        )
    symmetric = module.symmetric_algebra()
    match int(labels.cardinality()):
        case 0:
            empty_labels = finite_ordered_set(("empty",))
            empty = scheme.closed_subscheme(scheme.coordinate_algebra().one())
            charts = finite_indexed_family(
                empty_labels,
                lambda _label: empty,
                name="The empty standard atlas of the zero-module projectivization",
            )
            label_values = ()
        case _:
            charts = finite_indexed_family(
                labels,
                lambda label: _chart_algebra(module, label).affine_spectrum(base_ring=base),
                name="Standard affine charts of the relative projectivization",
            )
            label_values = tuple(labels)
    transitions = {
        (left, right): _chart_transition(module, charts, left, right, base)
        for position, left in enumerate(label_values)
        for right in label_values[position + 1 :]
    }
    total = Schemes(base).glue_affine_atlas(
        charts,
        transitions,
        _object_engine=_AffineProjectivizationSchemeEngine,
        projectivization_source_sheaf=sheaf,
        projectivization_module=module,
        projectivization_symmetric_algebra=symmetric,
    )
    projection = total.projectivization_projection()
    return Schemes(base).SliceOver(scheme)(projection)


def _projectivization(sheaf):
    r"""Return the represented quotient projectivization ``P_quot(sheaf)``."""
    return _affine_projectivization(sheaf)


__all__ = []
