'Lazy public aggregation for profinite.'

from importlib import import_module as _import_module

_EXPORTS = {'AbsoluteGaloisGroup': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                         'AbsoluteGaloisGroup'),
 'AbsoluteGaloisGroupElement': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                                'AbsoluteGaloisGroupElement'),
 'AbsoluteGaloisSliceAutomorphism': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                                     'AbsoluteGaloisSliceAutomorphism'),
 'ElementConjugacyClass': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                           'ElementConjugacyClass'),
 'FrobeniusElement': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                      'FrobeniusElement'),
 'OpenAbsoluteGaloisSubgroup': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                                'OpenAbsoluteGaloisSubgroup'),
 'OpenGaloisSubgroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                                      'OpenGaloisSubgroupConjugacyClass'),
 'OpenSubgroupInclusion': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                           'OpenSubgroupInclusion'),
 'absolute_galois_group': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                           'absolute_galois_group'),
 'open_absolute_galois_subgroup': ('dzack_research.preamble.categories.group.profinite.absolute_galois_group',
                                   'open_absolute_galois_subgroup'),
 'AbsoluteGaloisGroups': ('dzack_research.preamble.categories.group.profinite.absolute_galois_groups',
                          'AbsoluteGaloisGroups'),
 'AbsoluteGaloisGroupsOfFiniteFields': ('dzack_research.preamble.categories.group.profinite.absolute_galois_groups',
                                        'AbsoluteGaloisGroupsOfFiniteFields'),
 'OpenAbsoluteGaloisSubgroups': ('dzack_research.preamble.categories.group.profinite.absolute_galois_groups',
                                 'OpenAbsoluteGaloisSubgroups'),
 'absolute_galois_group_category': ('dzack_research.preamble.categories.group.profinite.absolute_galois_groups',
                                    'absolute_galois_group_category'),
 'ExactFieldHomset': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                      'ExactFieldHomset'),
 'ExactFieldMorphism': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                        'ExactFieldMorphism'),
 'exact_embeddings': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                      'exact_embeddings'),
 'exact_field_homset': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                        'exact_field_homset'),
 'field_generators': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                      'field_generators'),
 'first_exact_embedding': ('dzack_research.preamble.categories.group.profinite.field_morphisms',
                           'first_exact_embedding'),
 'CyclotomicCharacter': ('dzack_research.preamble.categories.group.profinite.galois_characters',
                         'CyclotomicCharacter'),
 'ProfiniteCharacter': ('dzack_research.preamble.categories.group.profinite.galois_characters',
                        'ProfiniteCharacter'),
 'QuadraticCharacter': ('dzack_research.preamble.categories.group.profinite.galois_characters',
                        'QuadraticCharacter'),
 'RestrictedProfiniteCharacter': ('dzack_research.preamble.categories.group.profinite.galois_characters',
                                  'RestrictedProfiniteCharacter'),
 'AbsoluteDecompositionGroup': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                                'AbsoluteDecompositionGroup'),
 'AbsoluteInertiaGroup': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                          'AbsoluteInertiaGroup'),
 'DecompositionGroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                                      'DecompositionGroupConjugacyClass'),
 'FiniteElementConjugacyClass': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                                 'FiniteElementConjugacyClass'),
 'FiniteGaloisSubgroup': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                          'FiniteGaloisSubgroup'),
 'FrobeniusConjugacyClass': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                             'FrobeniusConjugacyClass'),
 'InertiaGroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                                'InertiaGroupConjugacyClass'),
 'PrimeProlongation': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                       'PrimeProlongation'),
 'finite_decomposition_group': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                                'finite_decomposition_group'),
 'finite_frobenius_class': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                            'finite_frobenius_class'),
 'finite_inertia_group': ('dzack_research.preamble.categories.group.profinite.galois_decomposition',
                          'finite_inertia_group'),
 'ContinuousGroupHomset': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                           'ContinuousGroupHomset'),
 'FiniteGaloisAutomorphism': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                              'FiniteGaloisAutomorphism'),
 'FiniteGaloisExtension': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                           'FiniteGaloisExtension'),
 'FiniteGaloisQuotient': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                          'FiniteGaloisQuotient'),
 'GaloisRestrictionMap': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                          'GaloisRestrictionMap'),
 'LiftCoset': ('dzack_research.preamble.categories.group.profinite.galois_quotient', 'LiftCoset'),
 'continuous_group_homset': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                             'continuous_group_homset'),
 'extensions_along': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                      'extensions_along'),
 'restrict_along': ('dzack_research.preamble.categories.group.profinite.galois_quotient',
                    'restrict_along'),
 'ProfiniteGroups': ('dzack_research.preamble.categories.group.profinite.profinite_groups',
                     'ProfiniteGroups')}

__all__ = ['AbsoluteDecompositionGroup',
 'AbsoluteGaloisGroup',
 'AbsoluteGaloisGroupElement',
 'AbsoluteGaloisGroups',
 'AbsoluteGaloisGroupsOfFiniteFields',
 'AbsoluteGaloisSliceAutomorphism',
 'AbsoluteInertiaGroup',
 'ContinuousGroupHomset',
 'CyclotomicCharacter',
 'DecompositionGroupConjugacyClass',
 'ElementConjugacyClass',
 'ExactFieldHomset',
 'ExactFieldMorphism',
 'FiniteElementConjugacyClass',
 'FiniteGaloisAutomorphism',
 'FiniteGaloisExtension',
 'FiniteGaloisQuotient',
 'FiniteGaloisSubgroup',
 'FrobeniusConjugacyClass',
 'FrobeniusElement',
 'GaloisRestrictionMap',
 'InertiaGroupConjugacyClass',
 'LiftCoset',
 'OpenAbsoluteGaloisSubgroup',
 'OpenAbsoluteGaloisSubgroups',
 'OpenGaloisSubgroupConjugacyClass',
 'OpenSubgroupInclusion',
 'PrimeProlongation',
 'ProfiniteCharacter',
 'ProfiniteGroups',
 'QuadraticCharacter',
 'RestrictedProfiniteCharacter',
 'absolute_galois_group',
 'absolute_galois_group_category',
 'continuous_group_homset',
 'exact_embeddings',
 'exact_field_homset',
 'extensions_along',
 'field_generators',
 'finite_decomposition_group',
 'finite_frobenius_class',
 'finite_inertia_group',
 'first_exact_embedding',
 'open_absolute_galois_subgroup',
 'restrict_along']

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
