r"""The category of absolute Galois groups.

\[
G_K=\operatorname{Gal}(\bar K/K)=\varprojlim_{L/K\ \mathrm{finite\ Galois}}
\operatorname{Gal}(L/K)
\]

The category :class:`AbsoluteGaloisGroups` sits under
``ProfiniteGroups()``.  That category supplies
:meth:`is_profinite` and :meth:`topological_group_generators`; this
category adds the absolute-Galois-specific interface.

A concrete realization is the default.  The parent chooses
\(\bar K\), \(\iota:K\hookrightarrow\bar K\), and a
:class:`GaloisChoicePolicy` at construction, and records them.  The
choice-independent conjugacy classes are first-class *projections* of
the concrete objects, available via ``_class`` variants.

The constructor is installed on every field via
``Fields().ParentMethods.absolute_galois_group()``, so::

    sage: G = QQ.absolute_galois_group()
    sage: G.base_field()
    Rational Field
    sage: G.algebraic_closure()
    Algebraic Field
    sage: G.base_embedding()
    ...
    sage: G.category()
    Category of absolute Galois groups
"""

from sage.categories.category_singleton import Category_singleton
from sage.categories.fields import Fields as SageFields
from sage.categories.groups import Groups as SageGroups
from sage.categories.number_fields import NumberFields
from sage.misc.unknown import Unknown
from sage.rings.rational_field import QQ as SageQQ
from sage.misc.cachefunc import cached_method


class AbsoluteGaloisGroups(Category_singleton):
    r"""Category of absolute Galois groups \(G_K=\operatorname{Gal}(\bar K/K)\).

    A subcategory of profinite topological groups.  The profinite axiom
    supplies :meth:`is_profinite` and
    :meth:`topological_group_generators`; this category adds the
    absolute-Galois-specific interface.
    """

    def super_categories(self) -> list:
        return [ProfiniteGroups()]

    class ParentMethods:
        def characteristic(self):
            r"""Return the characteristic of the base field \(K\)."""
            return self.base_field().characteristic()

        def is_profinite(self) -> bool:
            r"""Return ``True``; an absolute Galois group is profinite."""
            return True

        def is_finitely_generated(self) -> "bool | Unknown":
            r"""Return whether \(G_K\) is finitely generated.

            ``False`` for a number field: \(G_{\QQ}\) surjects onto
            \(\operatorname{Gal}(L/\QQ)\) for symmetric groups of every
            degree, so no finite set generates it, topologically or
            otherwise.  ``True`` for a finite field, where \(\hat{\ZZ}\) is
            topologically generated by Frobenius alone.  Otherwise the honest
            answer is that this object does not know.
            """
            field = self.base_field()
            if field in SageFields().Finite():
                return True
            if field is SageQQ or field in NumberFields():
                return False
            return Unknown

        def group_generators_are_computable(self) -> "bool | Unknown":
            r"""Return whether generators can be produced.

            Only the finite-field case: Frobenius is a generator and is
            written down.  For every other field this object holds no
            algorithm, and says so rather than raising when asked.
            """
            if self.base_field() in SageFields().Finite():
                return True
            return False

        def has_computed_group_generators(self) -> "bool | Unknown":
            r"""Return whether generators are already in hand."""
            return self.base_field() in SageFields().Finite()

        def finite_quotient(self, L):
            r"""Return \(\operatorname{Gal}(L/K)\) as a finite quotient of \(G_K\).

            \(L/K\) is a finite Galois extension inside \(K^{\mathrm{sep}}\).
            The quotient \(G_K\twoheadrightarrow\operatorname{Gal}(L/K)\) is
            literally one of the defining coordinates of the profinite
            group, not an approximation.
            """
            return self.base_field()._absolute_galois_finite_quotient_(L)

        def restriction_map(self, L):
            r"""Return the continuous surjection \(G_K\twoheadrightarrow\operatorname{Gal}(L/K)\)."""
            quotient = self.finite_quotient(L)
            return GaloisRestrictionMap(self, quotient, L)

        def open_subgroup(self, E, embedding=None):
            r"""Return the actual open subgroup \(G_E\subset G_K\) for \(E/K\).

            Given \(E/K\), embed \(E\) into the chosen \(\bar K\) via the
            parent's choice policy (or a supplied ``embedding``).  Then
            \(H=\operatorname{Gal}(\bar K/E)\) is an actual subgroup of
            the realized \(G_K\).
            """
            return OpenAbsoluteGaloisSubgroup(self, E, embedding)

        def open_subgroup_class(self, E):
            r"""Return the conjugacy class of open subgroups determined by \(E/K\).

            Choice-independent: forgetting the embedding yields the
            conjugacy class.  Available as ``G.open_subgroup(E).conjugacy_class()``
            or directly here.
            """
            return OpenGaloisSubgroupConjugacyClass(self, E)

        def cyclotomic_character(self, n):
            r"""Return the cyclotomic character \(\chi_n:G_K\to(\mathbb Z/n\mathbb Z)^\times\)."""
            K = self.base_field()
            L = K.cyclotomic_extension(n)
            pi = self.restriction_map(L)
            aut_mu = Integers(n).unit_group()
            return CyclotomicCharacter(pi, aut_mu)

        def quadratic_character(self, a):
            r"""Return the quadratic character attached to \(K(\sqrt a)/K\)."""
            K = self.base_field()
            L = K.extension(K.gen()**2 - a, "sqrt_a")
            pi = self.restriction_map(L)
            return QuadraticCharacter(pi)

        def decomposition_group(self, prime):
            r"""Return \(D_{\bar v}\subseteq G_K\) at a chosen prolongation of ``prime``."""
            return AbsoluteDecompositionGroup(self, prime)

        def decomposition_group_class(self, prime):
            r"""Return the conjugacy class of decomposition groups at ``prime``."""
            return DecompositionGroupConjugacyClass(self, prime)

        def inertia_group(self, prime):
            r"""Return \(I_{\bar v}\subseteq G_K\) at a chosen prolongation of ``prime``."""
            return AbsoluteInertiaGroup(self, prime)

        def inertia_group_class(self, prime):
            r"""Return the conjugacy class of inertia groups at ``prime``."""
            return InertiaGroupConjugacyClass(self, prime)

        def frobenius(self, prime):
            r"""Return the Frobenius conjugacy class at ``prime`` (choices made)."""
            return FrobeniusConjugacyClass(self, prime)

        def frobenius_class(self, prime):
            r"""Return the canonical Frobenius conjugacy class at ``prime``."""
            return FrobeniusConjugacyClass(self, prime)

        def lift(self, sigma):
            r"""Lift \(\sigma\in\operatorname{Gal}(L/K)\) to a lazy element of \(G_K\)."""
            L = sigma.parent().domain() if hasattr(sigma, "parent") else None
            return AbsoluteGaloisGroupElement(self, L, sigma)

        def lifts(self, sigma):
            r"""Return the open coset \(g\cdot G_L\) of all lifts of \(\sigma\)."""
            L = sigma.parent().domain() if hasattr(sigma, "parent") else None
            return LiftCoset(self, sigma, L)

        def topological_generating_family(self):
            r"""Return a lazy family topologically generating \(G_K\)."""
            from sage.sets.family import Family

            def _generators():
                for L in self._finite_galois_extensions():
                    Q = self.finite_quotient(L)
                    for sigma in Q.gens():
                        yield self.lift(sigma)

            return Family(list(_generators()))


# ``absolute_galois_group`` is declared on ``OwnedFields.ParentMethods``, in
# the scalar hierarchy.  It stood here as an assignment onto Sage's own
# ``Fields().ParentMethods``, made while the preamble installed itself -- by
# which time Sage has built and cached every ``parent_class`` that would have
# inherited it, so no field ever answered.


def absolute_galois_group_factory(field, **kwargs):
    r"""Dispatch to the right :class:`AbsoluteGaloisGroup` subclass for ``field``."""
    from sage.rings.finite_rings.finite_field_base import FiniteField

    if isinstance(field, FiniteField):
        return AbsoluteGaloisGroup_finite_field(field, **kwargs)
    return AbsoluteGaloisGroup(field, **kwargs)