r"""Owned categories for absolute Galois groups."""

from sage.categories.number_fields import NumberFields
from sage.misc.cachefunc import cached_method
from sage.rings.rational_field import QQ as SageQQ

from dzack_research.preamble.categories.abstract_categories.cat import Cat
from dzack_research.preamble.categories.abstract_categories.objects import (
    OwnedCategory,
    OwnedParameterizedCategory,
)
from dzack_research.preamble.categories.group.groups import (
    OwnedAbelianGroups,
    OwnedInfiniteGroups,
    Subgroups,
)
from dzack_research.preamble.categories.group.profinite.profinite_groups import (
    ProfiniteGroups,
)
from dzack_research.preamble.categories.rings.ring_foundation import (
    _engine_ring,
    _own_ring,
)
from dzack_research.preamble.categories.sets.cardinals import continuum
from dzack_research.preamble.categories.sets.finite_ordered_sets import (
    finite_ordered_set,
)


def _finite_field_absolute_galois_group():
    r"""Return the selected finite-field specimen used by these categories."""
    from sage.rings.finite_rings.finite_field_constructor import GF as SageGF

    from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
        AbsoluteGaloisGroup,
    )
    from dzack_research.preamble.categories.rings.ring_foundation import _own_ring

    return AbsoluteGaloisGroup(_own_ring(SageGF(2)))


class AbsoluteGaloisGroups(OwnedCategory):
    r"""Groups (G_K=\operatorname{Aut}_K(\bar K)) with a chosen base point."""

    def an_object(self):
        r"""The absolute Galois group of ``GF(2)`` with its canonical realization."""
        return _finite_field_absolute_galois_group()

    @classmethod
    def _repr_object_names(cls) -> str:
        return "absolute Galois groups"

    def super_categories(self):
        return [ProfiniteGroups()]

    class ParentMethods:
        def characteristic(self):
            return self.base_field().characteristic()

        def group_generators_are_computable(self) -> bool:
            r"""Whether an algebraic generating set is computable here.

            This is deliberately distinct from topological generation.  Even
            ``G_{F_q} = \widehat{ZZ}`` is not algebraically generated by its
            Frobenius element, although Frobenius topologically generates it.
            """
            return False

        def has_computed_group_generators(self) -> bool:
            r"""Whether an algebraic generating set has been materialized."""
            return False

        def _finite_quotient_witnesses(self):
            r"""Yield restrictions ``G_K -> Gal(L/K)`` to cubic splitting fields over ``K``.

            Implements the protected contract of
            ``ProfiniteGroups.ParentMethods._finite_quotient_witnesses``.  For
            a number field ``K``, the splitting field ``L`` over ``K`` of a
            cubic with coefficients in ``K`` is a finite Galois extension of
            ``K``, so restriction ``G_K -> Gal(L/K)`` is a continuous
            surjection onto a finite group.  The cubics are ``x^3 - 2`` and
            ``x^3 - x - 1``, taken over ``K`` itself.  ``Gal(L/K)`` is ``S_3``
            when the cubic is irreducible over ``K`` and its discriminant is
            not a square in ``K``.  Over ``QQ`` the first cubic gives
            ``Gal(QQ(2^{1/3}, zeta_3)/QQ) = S_3``.  The Kummer cubic
            ``x^3 - 2`` has an abelian group over a field containing
            ``zeta_3``; the second cubic is not of Kummer form.  Other base
            fields select no quotient here.
            """
            computation_field = _engine_ring(self.base_field())
            match computation_field:
                case _ if computation_field is SageQQ or (
                    computation_field in NumberFields()
                    and computation_field.is_absolute()
                ):
                    x = computation_field["x"].gen()
                    yield self._cubic_splitting_field_restriction(x**3 - 2)
                    yield self._cubic_splitting_field_restriction(x**3 - x - 1)
                case _:
                    return

        @cached_method
        def _cubic_splitting_field_restriction(self, polynomial):
            r"""Return the restriction ``G_K -> Gal(L/K)`` to the splitting field ``L`` of ``polynomial``.

            ``polynomial`` has coefficients in the computation field of ``K``.
            The stage ``K -> L`` is the base map the splitting-field
            construction returns.
            """
            splitting_field, base_backend = polynomial.splitting_field(
                "s", map=True
            )
            splitting_field = _own_ring(splitting_field)
            base_embedding = self.base_field().Mor(splitting_field)(base_backend)
            stage = self.extension_data(
                splitting_field, base_embedding=base_embedding
            )
            return self.restriction_map(stage)


class AbsoluteGaloisGroupsOfFiniteFields(OwnedCategory):
    r"""The procyclic absolute Galois groups of finite fields."""

    def an_object(self):
        r"""The procyclic absolute Galois group of ``GF(2)``."""
        return _finite_field_absolute_galois_group()

    @classmethod
    def _repr_object_names(cls) -> str:
        return "absolute Galois groups of finite fields"

    def super_categories(self):
        return [
            AbsoluteGaloisGroups(),
            OwnedAbelianGroups(),
            OwnedInfiniteGroups(),
        ]

    class ParentMethods:
        def topological_group_generators(self):
            return finite_ordered_set((self.frobenius(),))

        def topological_generating_family(self):
            r"""Return the selected owned family topologically generating ``G_K``.

            For a finite field this is the singleton family containing
            Frobenius.  It is topological generating data, not an algebraic
            finite generating set.
            """
            return self.topological_group_generators()

        def _cardinality_decision(self):
            r"""``|G_{F_q}| = 2^{aleph_0}``.

            ``G_{F_q}`` is the profinite completion ``\widehat{ZZ} =
            \prod_p ZZ_p``, and ``ZZ_2`` alone already has the continuum
            of elements, its ``2``-adic digit sequences.
            """
            return continuum


class OpenAbsoluteGaloisSubgroups(OwnedParameterizedCategory):
    r"""Open subgroups (G_E\subseteq G_K) carrying the embedding (E\to\bar K)."""

    @staticmethod
    def __classcall__(cls, supergroup):
        if supergroup not in AbsoluteGaloisGroups():
            raise TypeError(
                f"cannot form open subgroups of {supergroup}: open subgroups G_E of G_K "
                f"are taken inside an absolute Galois group G_K, but {supergroup} is not one"
            )
        return OwnedParameterizedCategory.__classcall__(cls, supergroup)

    def parameter_category(self):
        return AbsoluteGaloisGroups()

    def supergroup(self):
        return self.base()

    def an_object(self):
        r"""The whole ambient group, viewed as its index-one open subgroup."""
        group = self.supergroup()
        return self(group.extension_data(group.base_field()))

    @classmethod
    def _repr_object_names(cls) -> str:
        return "open subgroups of absolute Galois groups"

    def super_categories(self):
        return [AbsoluteGaloisGroups(), Subgroups(self.supergroup())]

    def _call_(self, extension):
        from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
            _OpenAbsoluteGaloisSubgroupEngine,
            _realized_absolute_galois_group,
        )

        group = self.supergroup()
        extension = group.extension_data(extension)
        category = Cat().meet(
            (self, _absolute_galois_group_category(extension.field()))
        )
        return _realized_absolute_galois_group(
            extension.field(),
            closure=group.algebraic_closure(),
            embedding=extension.embedding(),
            category=category,
            engine=_OpenAbsoluteGaloisSubgroupEngine,
            supergroup=group,
            fixed_extension=extension,
        )

    class ParentMethods:
        def ambient(self):
            r"""Return the ambient absolute Galois group ``G_K``."""
            return self.supergroup()

        def fixed_field(self):
            return self._fixed_extension.field()

        def fixed_extension(self):
            return self._fixed_extension

        def embedding(self):
            return self._fixed_extension.embedding()

        def index(self):
            return self._fixed_extension.degree()

        @cached_method
        def inclusion(self):
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
                _open_subgroup_inclusion_rule,
            )

            return self.Mor(self.supergroup())._from_realization_rule(
                _open_subgroup_inclusion_rule
            )


def _absolute_galois_group_category(field):
    from sage.categories.finite_fields import FiniteFields

    return (
        AbsoluteGaloisGroupsOfFiniteFields()
        if _engine_ring(field) in FiniteFields()
        else AbsoluteGaloisGroups()
    )


__all__ = [
    "AbsoluteGaloisGroups",
    "AbsoluteGaloisGroupsOfFiniteFields",
    "OpenAbsoluteGaloisSubgroups",
]
