r"""Owned categories for absolute Galois groups."""

from sage.misc.cachefunc import cached_method
from sage.misc.unknown import Unknown

from dzack_research.preamble.categories.abstract_categories.cat import Cat
from dzack_research.preamble.categories.abstract_categories.objects import (
    OwnedCategory,
    OwnedParameterizedCategory,
)
from dzack_research.preamble.categories.group.groups import OwnedAbelianGroups, Subgroups
from dzack_research.preamble.categories.group.profinite.profinite_groups import (
    ProfiniteGroups,
)
from dzack_research.preamble.categories.rings.ring_foundation import _engine_ring
from dzack_research.preamble.categories.sets.cardinals import continuum
from dzack_research.preamble.categories.sets.finite_ordered_sets import (
    finite_ordered_set,
)


def _finite_field_absolute_galois_group():
    r"""Return the selected finite-field specimen used by these categories."""
    from sage.rings.finite_rings.finite_field_constructor import GF as SageGF

    from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
        AbsoluteGaloisGroup,
    )
    from dzack_research.preamble.categories.rings.ring_foundation import _own_ring

    return AbsoluteGaloisGroup(_own_ring(SageGF(2)))


class AbsoluteGaloisGroups(OwnedCategory):
    r"""Groups (G_K=\operatorname{Aut}_K(\bar K)) with a chosen base point."""

    def an_object(self):
        r"""The absolute Galois group of ``GF(2)`` with its canonical realization."""
        return _finite_field_absolute_galois_group()

    @classmethod
    def _repr_object_names(cls) -> str:
        return "absolute Galois groups"

    def super_categories(self):
        return [ProfiniteGroups()]

    class ParentMethods:
        def characteristic(self):
            return self.base_field().characteristic()

        def is_profinite(self) -> bool:
            return True

        def is_abelian(self):
            return Unknown

        def group_generators_are_computable(self) -> bool:
            r"""Whether an algebraic generating set is computable here.

            This is deliberately distinct from topological generation.  Even
            ``G_{F_q} = \widehat{ZZ}`` is not algebraically generated by its
            Frobenius element, although Frobenius topologically generates it.
            """
            return False

        def has_computed_group_generators(self) -> bool:
            r"""Whether an algebraic generating set has been materialized."""
            return False


class AbsoluteGaloisGroupsOfFiniteFields(OwnedCategory):
    r"""The procyclic absolute Galois groups of finite fields."""

    def an_object(self):
        r"""The procyclic absolute Galois group of ``GF(2)``."""
        return _finite_field_absolute_galois_group()

    @classmethod
    def _repr_object_names(cls) -> str:
        return "absolute Galois groups of finite fields"

    def super_categories(self):
        return [AbsoluteGaloisGroups(), OwnedAbelianGroups()]

    class ParentMethods:
        def is_finite(self) -> bool:
            return False

        def order(self):
            from sage.rings.infinity import Infinity

            return Infinity

        def cardinality(self):
            return continuum

        def is_abelian(self) -> bool:
            return True

        def is_finitely_generated(self) -> bool:
            return False

        def topological_group_generators(self):
            return finite_ordered_set((self.frobenius(),))

        def topological_generating_family(self):
            r"""Return the selected owned family topologically generating ``G_K``.

            For a finite field this is the singleton family containing
            Frobenius.  It is topological generating data, not an algebraic
            finite generating set.
            """
            return self.topological_group_generators()


class OpenAbsoluteGaloisSubgroups(OwnedParameterizedCategory):
    r"""Open subgroups (G_E\subseteq G_K) carrying the embedding (E\to\bar K)."""

    @staticmethod
    def __classcall__(cls, supergroup):
        if supergroup not in AbsoluteGaloisGroups():
            raise TypeError(
                "an open absolute-Galois subgroup requires an ambient absolute Galois group"
            )
        return OwnedParameterizedCategory.__classcall__(cls, supergroup)

    def parameter_category(self):
        return AbsoluteGaloisGroups()

    def supergroup(self):
        return self.base()

    def an_object(self):
        r"""The whole ambient group, viewed as its index-one open subgroup."""
        group = self.supergroup()
        return self(group.extension_data(group.base_field()))

    @classmethod
    def _repr_object_names(cls) -> str:
        return "open subgroups of absolute Galois groups"

    def super_categories(self):
        return [AbsoluteGaloisGroups(), Subgroups(self.supergroup())]

    def _call_(self, extension):
        from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
            _OpenAbsoluteGaloisSubgroupEngine,
            _realized_absolute_galois_group,
        )

        group = self.supergroup()
        extension = group.extension_data(extension)
        category = Cat().meet(
            (self, _absolute_galois_group_category(extension.field()))
        )
        return _realized_absolute_galois_group(
            extension.field(),
            closure=group.algebraic_closure(),
            embedding=extension.embedding(),
            category=category,
            engine=_OpenAbsoluteGaloisSubgroupEngine,
            supergroup=group,
            fixed_extension=extension,
        )

    class ParentMethods:
        def ambient(self):
            r"""Return the ambient absolute Galois group ``G_K``."""
            return self.supergroup()

        def fixed_field(self):
            return self._fixed_extension.field()

        def fixed_extension(self):
            return self._fixed_extension

        def embedding(self):
            return self._fixed_extension.embedding()

        def index(self):
            return self._fixed_extension.degree()

        @cached_method
        def inclusion(self):
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group import (
                OpenSubgroupInclusion,
            )

            return OpenSubgroupInclusion(self)


def _absolute_galois_group_category(field):
    from sage.categories.finite_fields import FiniteFields

    return (
        AbsoluteGaloisGroupsOfFiniteFields()
        if _engine_ring(field) in FiniteFields()
        else AbsoluteGaloisGroups()
    )


__all__ = [
    "AbsoluteGaloisGroups",
    "AbsoluteGaloisGroupsOfFiniteFields",
    "OpenAbsoluteGaloisSubgroups",
]
