r"""The category of absolute Galois groups.

\[
G_K=\operatorname{Gal}(\bar K/K)=\varprojlim_{L/K\ \mathrm{finite\ Galois}}
\operatorname{Gal}(L/K)
\]

The category :class:`AbsoluteGaloisGroups` sits under
``ProfiniteGroups()``.  That category supplies
:meth:`is_profinite` and :meth:`topological_group_generators`; this
category adds the absolute-Galois-specific interface.

A concrete realization is the default.  The parent chooses
\(\bar K\), \(\iota:K\hookrightarrow\bar K\), and a
:class:`GaloisChoicePolicy` at construction, and records them.  The
choice-independent conjugacy classes are first-class *projections* of
the concrete objects, available via ``_class`` variants.

The constructor is installed on every field via
``Fields().ParentMethods.absolute_galois_group()``, so::

    sage: G = QQ.absolute_galois_group()
    sage: G.base_field()
    Rational Field
    sage: G.algebraic_closure()
    Algebraic Field
    sage: G.base_embedding()
    ...
    sage: G.category()
    Category of absolute Galois groups
"""

from collections.abc import Iterator
from typing import TYPE_CHECKING

from sage.rings.finite_rings.integer_mod_ring import Integers
from dzack_research.preamble.owned_category_bases import Category_singleton
from sage.categories.fields import Fields as SageFields
from sage.categories.groups import Groups as SageGroups
from sage.categories.number_fields import NumberFields
from sage.misc.unknown import Unknown
from sage.rings.rational_field import QQ as SageQQ
from sage.misc.cachefunc import cached_method

if TYPE_CHECKING:
    from sage.rings.number_field.galois_group import GaloisGroup_v2, GaloisGroupElement
    from sage.rings.number_field.number_field_ideal import NumberFieldFractionalIdeal
    from sage.sets.family import Family
    from sage.categories.morphism import Morphism
    from sage.categories.rings import Ring
    from sage.structure.parent import Parent
    from dzack_research.preamble.lexicon import RingElement

    from typing import Protocol

    class AbsoluteGaloisGroupParent(Protocol):
        r"""What \(G_K\) has from its own class rather than from this
        category: the base field, and the supply of finite Galois extensions
        the finite coordinates run over."""

        def base_field(self) -> "Ring": ...
        def _finite_galois_extensions(self) -> "Iterator[Ring | None]": ...
        def finite_quotient(self: "AbsoluteGaloisGroupParent", L: "Ring") -> "GaloisGroup_v2": ...
        def restriction_map(self: "AbsoluteGaloisGroupParent", L: "Ring") -> "GaloisRestrictionMap": ...
        def lift(self: "AbsoluteGaloisGroupParent", sigma: "GaloisGroupElement") -> "AbsoluteGaloisGroupElement": ...


class AbsoluteGaloisGroups(Category_singleton):
    r"""Category of absolute Galois groups \(G_K=\operatorname{Gal}(\bar K/K)\).

    A subcategory of profinite topological groups.  The profinite axiom
    supplies :meth:`is_profinite` and
    :meth:`topological_group_generators`; this category adds the
    absolute-Galois-specific interface.
    """

    def super_categories(self) -> list:
        # Local: a module-level import would close a cycle; the module is built by the time this runs.
        from dzack_research.preamble.categories.group.profinite.profinite_groups import ProfiniteGroups

        return [ProfiniteGroups()]

    class ParentMethods:
        def characteristic(self: "AbsoluteGaloisGroupParent") -> "Integer":
            r"""Return the characteristic of the base field \(K\)."""
            characteristic: "Integer" = self.base_field().characteristic()
            return characteristic

        def is_profinite(self) -> bool:
            r"""Return ``True``; an absolute Galois group is profinite."""
            return True

        def is_abelian(self) -> "bool | Unknown":
            r"""Return whether \(G_K\) is abelian when this category decides it."""
            return Unknown

        def is_finitely_generated(
            self: "AbsoluteGaloisGroupParent",
        ) -> "bool | Unknown":
            r"""Return whether \(G_K\) is finitely generated.

            ``False`` for a finite field because \(\widehat{\ZZ}\) is only
            topologically generated by Frobenius.  Also ``False`` for a
            number field: \(G_{\QQ}\) surjects onto
            \(\operatorname{Gal}(L/\QQ)\) for symmetric groups of every
            degree.  Otherwise this object does not decide the question.
            """
            field = self.base_field()
            if field in SageFields().Finite():
                return False
            if field is SageQQ or field in NumberFields():
                return False
            return Unknown

        def group_generators_are_computable(
            self: "AbsoluteGaloisGroupParent",
        ) -> "bool | Unknown":
            r"""Return whether generators can be produced.

            Frobenius topologically generates the finite-field case.  It does
            not algebraically generate \(\widehat{\ZZ}\), so no case here has
            an algebraic generating-set algorithm.
            """
            return False

        def has_computed_group_generators(
            self: "AbsoluteGaloisGroupParent",
        ) -> "bool | Unknown":
            r"""Return whether generators are already in hand."""
            return False

        def finite_quotient(self: "AbsoluteGaloisGroupParent", L: "Ring") -> "GaloisGroup_v2":
            r"""Return \(\operatorname{Gal}(L/K)\) as a finite quotient of \(G_K\).

            \(L/K\) is a finite Galois extension inside \(K^{\mathrm{sep}}\).
            The quotient \(G_K\twoheadrightarrow\operatorname{Gal}(L/K)\) is
            literally one of the defining coordinates of the profinite
            group, not an approximation.
            """
            quotient: "GaloisGroup_v2" = (
                self.base_field()._absolute_galois_finite_quotient_(L)
            )
            return quotient

        def restriction_map(self: "AbsoluteGaloisGroupParent", L: "Ring") -> "GaloisRestrictionMap":
            r"""Return the continuous surjection \(G_K\twoheadrightarrow\operatorname{Gal}(L/K)\)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_quotient import GaloisRestrictionMap

            quotient = self.finite_quotient(L)
            return GaloisRestrictionMap(self, quotient, L)

        def open_subgroup(
            self: "AbsoluteGaloisGroupParent", E: "Ring", embedding: "Morphism | None" = None
        ) -> "Parent":
            r"""Return the actual open subgroup \(G_E\subset G_K\) for \(E/K\).

            Given \(E/K\), embed \(E\) into the chosen \(\bar K\) via the
            parent's choice policy (or a supplied ``embedding``).  Then
            \(H=\operatorname{Gal}(\bar K/E)\) is an actual subgroup of
            the realized \(G_K\).
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group_subgroup import open_absolute_galois_subgroup

            return open_absolute_galois_subgroup(self, E, embedding)

        def open_subgroup_class(self: "AbsoluteGaloisGroupParent", E: "Ring") -> "OpenGaloisSubgroupConjugacyClass":
            r"""Return the conjugacy class of open subgroups determined by \(E/K\).

            Choice-independent: forgetting the embedding yields the
            conjugacy class.  Available as ``G.open_subgroup(E).conjugacy_class()``
            or directly here.
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group_subgroup import OpenGaloisSubgroupConjugacyClass

            return OpenGaloisSubgroupConjugacyClass(self, E)

        def cyclotomic_character(self: "AbsoluteGaloisGroupParent", n: "Integer") -> "CyclotomicCharacter":
            r"""Return the cyclotomic character \(\chi_n:G_K\to(\mathbb Z/n\mathbb Z)^\times\)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_characters import CyclotomicCharacter

            K = self.base_field()
            L = K.cyclotomic_extension(n)
            pi = self.restriction_map(L)
            aut_mu = Integers(n).unit_group()
            return CyclotomicCharacter(pi, aut_mu)

        def quadratic_character(self: "AbsoluteGaloisGroupParent", a: "RingElement") -> "QuadraticCharacter":
            r"""Return the quadratic character attached to \(K(\sqrt a)/K\)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_characters import QuadraticCharacter

            K = self.base_field()
            L = K.extension(K.gen()**2 - a, "sqrt_a")
            pi = self.restriction_map(L)
            return QuadraticCharacter(pi)

        def decomposition_group(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "AbsoluteDecompositionGroup":
            r"""Return \(D_{\bar v}\subseteq G_K\) at a chosen prolongation of ``prime``."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import AbsoluteDecompositionGroup

            return AbsoluteDecompositionGroup(self, prime)

        def decomposition_group_class(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "DecompositionGroupConjugacyClass":
            r"""Return the conjugacy class of decomposition groups at ``prime``."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import DecompositionGroupConjugacyClass

            return DecompositionGroupConjugacyClass(self, prime)

        def inertia_group(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "AbsoluteInertiaGroup":
            r"""Return \(I_{\bar v}\subseteq G_K\) at a chosen prolongation of ``prime``."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import AbsoluteInertiaGroup

            return AbsoluteInertiaGroup(self, prime)

        def inertia_group_class(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "InertiaGroupConjugacyClass":
            r"""Return the conjugacy class of inertia groups at ``prime``."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import InertiaGroupConjugacyClass

            return InertiaGroupConjugacyClass(self, prime)

        def frobenius(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "FrobeniusConjugacyClass":
            r"""Return the Frobenius conjugacy class at ``prime`` (choices made)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import FrobeniusConjugacyClass

            return FrobeniusConjugacyClass(self, prime)

        def frobenius_class(
            self: "AbsoluteGaloisGroupParent", prime: "NumberFieldFractionalIdeal"
        ) -> "FrobeniusConjugacyClass":
            r"""Return the canonical Frobenius conjugacy class at ``prime``."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.galois_decomposition import FrobeniusConjugacyClass

            return FrobeniusConjugacyClass(self, prime)

        def lift(self: "AbsoluteGaloisGroupParent", sigma: "GaloisGroupElement") -> "AbsoluteGaloisGroupElement":
            r"""Lift \(\sigma\in\operatorname{Gal}(L/K)\) to a lazy element of \(G_K\)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group_element import AbsoluteGaloisGroupElement

            return AbsoluteGaloisGroupElement(
                self, sigma.parent().top_field(), sigma.as_hom()
            )

        def lifts(self: "AbsoluteGaloisGroupParent", sigma: "GaloisGroupElement") -> "LiftCoset":
            r"""Return the open coset \(g\cdot G_L\) of all lifts of \(\sigma\)."""
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.group.profinite.absolute_galois_group import LiftCoset

            return LiftCoset(self, sigma, sigma.parent().top_field())

        def topological_generating_family(
            self: "AbsoluteGaloisGroupParent",
        ) -> "Family":
            r"""Return a lazy family topologically generating \(G_K\)."""
            from sage.sets.family import Family

            def _generators() -> "Iterator[AbsoluteGaloisGroupElement]":
                for L in self._finite_galois_extensions():
                    Q = self.finite_quotient(L)
                    for sigma in Q.gens():
                        yield self.lift(sigma)

            family: "Family" = Family(list(_generators()))
            return family


# ``absolute_galois_group`` is declared on ``OwnedFields.ParentMethods``, in
# the scalar hierarchy.  It stood here as an assignment onto Sage's own
# ``Fields().ParentMethods``, made while the preamble installed itself -- by
# which time Sage has built and cached every ``parent_class`` that would have
# inherited it, so no field ever answered.


def absolute_galois_group_factory(
    field: "Ring", **kwargs: "Ring | Morphism | GaloisChoicePolicy | None"
) -> "Parent":
    r"""Return \(G_K\) for ``field``, in the category the field decides."""
    # Local: a module-level import would close a cycle; the module is built by the time this runs.
    from dzack_research.preamble.categories.group.profinite.absolute_galois_group import absolute_galois_group

    return absolute_galois_group(field, **kwargs)
