r"""Free modules on finite totally ordered sets."""

from collections.abc import Iterable, Iterator
from typing import Any, Self, TYPE_CHECKING

from sage.rings.integer import Integer
from sage.categories.category_types import Category_over_base_ring
from sage.categories.morphism import SetMorphism
from sage.modules.free_module_element import vector
from sage.rings.integer import Integer as SageInteger
from sage.structure.element import Element, ModuleElement
from sage.structure.parent import Parent
from sage.structure.richcmp import richcmp
from sage_lattice_category_spike.objects.cardinals import Cardinal

from sage_lattice_category_spike.objects.sets import Sets

if TYPE_CHECKING:
    # The ordered-set noun is type-only: the preamble loads into one
    # shared namespace and nothing named OrderedSet may bind there.
    from sage_lattice_category_spike.lexicon import OrderedSet


def _finite_rank(module_generating_set: "OrderedSet") -> int:
    size = module_generating_set.cardinality()
    if isinstance(size, Cardinal):
        assert size.is_finite(), "a finitely generated module has finite rank"
        return int(size.finite_value())
    return int(size)


class FinitelyGeneratedFreeModules(Category_over_base_ring):
    r"""Finite free modules whose framing set has a chosen total order."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated framed free modules"

    def super_categories(self: Self) -> list:
        return [
            FramedFreeModules(self.base_ring()),
            FinitelyGeneratedModules(self.base_ring()),
        ]

    class ParentMethods:

        def rank(self: Self) -> "Cardinal":
            r"""Return the cardinality of the finite generating set."""
            return self.module_generating_set().cardinality()

        def number_of_module_generators(self: Self) -> "Integer":
            return self.module_generating_set().cardinality()

        def is_torsion(self: Self) -> bool:
            return bool(self.is_zero())

        def Aut(self: Self) -> "ModuleAutomorphismGroup":
            cached = self.__dict__.get("_preamble_Aut")
            if cached is None:
                cached = ModuleAutomorphismGroup(self)
                self._preamble_Aut = cached
            return cached

        def subobject_on(self: Self, module_generators: "OrderedSet") -> "Subobject":
            module_generators = tuple(
                generator if isinstance(generator, Element)
                and generator.parent() is self
                else self._from_coordinates(generator)
                for generator in module_generators
            )
            assert all(generator.parent() is self for generator in module_generators), (
                "a subobject is generated by elements of this module"
            )
            module_generators = _independent_module_generators(self, module_generators)
            # The submodule's module_generators are abstract: it is a free module on
            # its own labels, knowing nothing about this one.  How each of its
            # module_generators is written as a combination of these module_generators is
            # exactly what the inclusion morphism records -- so a subobject
            # never needs an ambient module to be expressed inside.
            labels = Sets.Δ[len(module_generators) - 1]
            submodule = BasedFreeModule(self.base_ring(), labels)
            embedding = module_homset(submodule, self)(
                dict(zip(labels, module_generators))
            )
            return Subobject(embedding)

        def submodule(self: Self, module_generators: "OrderedSet") -> "Subobject":
            r"""Return the submodule generated by ``module_generators``."""
            return self.subobject_on(module_generators)

        def hom(self: Self, images: dict, codomain: "Module" = None) -> "ModuleMorphism":
            r"""Construct the map specified on the finite generating set."""
            match images:
                case SetMorphism():
                    assert isinstance(images.codomain(), UnderlyingSet), (
                        "a generator morphism lands in the underlying set of "
                        "its module codomain"
                    )
                    target = images.codomain().structured_parent()
                    assignment = images
                case dict() if images:
                    target = next(iter(images.values())).parent()
                    assignment = images
                case dict():
                    assert codomain is not None, (
                        "the empty assignment requires an explicitly named codomain"
                    )
                    target = codomain
                    assignment = images
                case list() | tuple():
                    target, assignment = _finite_module_generator_assignment(
                        self,
                        images,
                        codomain,
                    )
                case _:
                    assert False, (
                        "a homomorphism is specified by a generator morphism, "
                        "a finite assignment, or an ordered list of images"
                    )
            return self.Hom(target)(assignment)


class BasedFreeModuleElement(ModuleElement):
    r"""An element represented in its parent's chosen ordered basis."""

    def __init__(self, parent: "Parent", coordinates: "Vector") -> None:
        ModuleElement.__init__(self, parent)
        self._coordinates_ = vector(parent.base_ring(), list(coordinates))
        assert len(self._coordinates_) == parent.number_of_module_generators(), (
            f"{parent} has rank {parent.number_of_module_generators()}, got "
            f"{len(self._coordinates_)} coordinates"
        )

    def _coordinates(self) -> "Vector":
        return self._coordinates_

    def coefficients(self) -> dict:
        return {
            element_of_S: coefficient
            for element_of_S, coefficient in zip(
                self.parent().module_generating_set(), self._coordinates_
            )
            if coefficient != 0
        }

    def underlying_set_element(self) -> "Element":
        r"""Recover \(s\) when this element is the canonical generator \([s]\)."""
        nonzero = tuple(self.coefficients().items())
        assert len(nonzero) == 1, (
            "only an element in the image of the canonical generator morphism "
            "has one underlying element of S"
        )
        element_of_S, coefficient = nonzero[0]
        assert coefficient == self.parent().base_ring().one(), (
            "only an element in the image of the canonical generator morphism "
            "has one underlying element of S"
        )
        return element_of_S

    def _add_(self, other: object) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
                self._coordinates_ + other._coordinates_
            )

    def _sub_(self, other: object) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
                self._coordinates_ - other._coordinates_
            )

    def _neg_(self) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(-self._coordinates_)

    def _lmul_(self, factor: "RingElement") -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
                self.parent().base_ring()(factor) * self._coordinates_
            )

    _rmul_ = _lmul_

    def _richcmp_(self, other: object, op: int) -> bool:
        return bool(richcmp(self._coordinates_, other._coordinates_, op))

    def __hash__(self) -> int:
        return hash(tuple(self._coordinates_))

    def __iter__(self) -> Iterator[Any]:
        return iter(self._coordinates_)

    def _repr_(self) -> str:
        return repr(self._coordinates_)


class BasedFreeModule(FreeModuleOnSet):
    r"""The finite specialization of \(F_R(S)\) for a totally ordered \(S\)."""

    Element = BasedFreeModuleElement

    def __init__(self, base_ring: "Ring", module_generating_set: "OrderedSet") -> None:
        match module_generating_set:
            case int() | SageInteger():
                assert module_generating_set >= 0, (
                    "the canonical finite framing has nonnegative cardinality"
                )
                module_generating_set = Sets.Δ[module_generating_set - 1]
            case Parent():
                pass
            case Iterable():
                module_generating_set = _as_set(module_generating_set)
            case _:
                assert False, (
                    "a generating set is a finite set, a finite iterable, or "
                    "a nonnegative cardinality"
                )
        if module_generating_set in Sets().Finite():
            module_generating_set = finite_ordered_set(module_generating_set)
        else:
            module_generating_set = _as_set(module_generating_set)
        FreeModuleOnSet.__init__(self, base_ring, module_generating_set)

    def _module_generator_element(self, element_of_S: "Element") -> BasedFreeModuleElement:
        module_generating_set = self.__dict__.get("_module_generating_set")
        assert module_generating_set is not None, (
            "a framed free module stores its canonical generating set"
        )
        assert element_of_S in module_generating_set, (
            f"{element_of_S!r} is not in {module_generating_set}"
        )
        index = module_generating_set.index(element_of_S)
        return self._from_coordinates(
            [self.base_ring()(position == index) for position in range(self.number_of_module_generators())]
        )

    def number_of_module_generators(self) -> int:
        return _finite_rank(self.module_generating_set())

    def zero(self) -> BasedFreeModuleElement:
        return self._from_coordinates([self.base_ring().zero()] * self.number_of_module_generators())

    def _from_coordinates(self, coordinates: "Vector") -> BasedFreeModuleElement:
        return self.element_class(self, coordinates)

    def rank(self) -> "Cardinal":
        return self.module_generating_set().cardinality()

    def _element_constructor_(self, value: "Element") -> BasedFreeModuleElement:
        assert isinstance(value, BasedFreeModuleElement) and value.parent() is self, (
            f"{value} is not an element of {self}"
        )
        return value

    def __contains__(self, value: "Element") -> bool:
        return isinstance(value, BasedFreeModuleElement) and value.parent() is self

    def _stored_module_generating_set(self) -> "OrderedSet":
        r"""Return the generating set the constructor stored.

        Identity reads the stored set rather than
        ``module_generating_set()``, which derives it from the generator
        morphism.  Building that morphism constructs ``UnderlyingSet(self)``,
        a ``UniqueRepresentation`` whose cache looks ``self`` up by hash and
        equality -- so identity computed through the accessor would ask for
        identity to answer.
        """
        module_generating_set = self.__dict__.get("_module_generating_set")
        assert module_generating_set is not None, (
            "a based free module stores its canonical generating set"
        )
        return module_generating_set

    def __eq__(self, other: object) -> bool:
        return (
            type(other) is type(self)
            and self.base_ring() == other.base_ring()
            and tuple(self._stored_module_generating_set())
            == tuple(other._stored_module_generating_set())
        )

    def __hash__(self) -> int:
        return hash(
            (
                type(self),
                self.base_ring(),
                tuple(self._stored_module_generating_set()),
            )
        )

    def _repr_(self) -> str:
        return (
            f"Free {self.base_ring()}-module on the ordered set "
            f"{self.module_generating_set()}"
        )

def Free_ZZ(module_generating_set: "OrderedSet") -> FreeModuleOnSet:
    r"""Construct the free \(\mathbb Z\)-module on ``module_generating_set``."""
    return FreeModuleOn(ZZ, module_generating_set)
