r"""Finite free modules with a chosen ordered basis-indexing set."""

from typing import Any

from sage.categories.category_types import Category_over_base_ring
from sage.modules.free_module_element import vector
from sage.rings.integer import Integer as SageInteger
from sage.sets.set import Set
from sage.structure.element import ModuleElement
from sage.structure.parent import Parent
from sage.structure.richcmp import richcmp


class FinitelyGeneratedFreeModules(Category_over_base_ring):
    r"""Finite free modules whose framing set has a chosen total order."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated framed free modules"

    def super_categories(self) -> list:
        return [
            FramedFreeModules(self.base_ring()),
            FinitelyGeneratedModules(self.base_ring()),
        ]

    class ParentMethods:
        def rank(self: Any) -> Any:
            r"""Return the cardinality of the basis-indexing set."""
            return ZZ(self.generating_set().cardinality())

        def ngens(self: Any) -> int:
            return int(self.generating_set().cardinality())

        def is_torsion(self: Any) -> bool:
            return self.is_zero()

        def Aut(self: Any) -> Any:
            cached = self.__dict__.get("_preamble_Aut")
            if cached is None:
                cached = ModuleAutomorphismGroup(self)
                self._preamble_Aut = cached
            return cached

        def subobject_on(self: Any, generators: Any) -> Any:
            generators = tuple(generators)
            assert all(generator.parent() is self for generator in generators), (
                "a subobject is generated by elements of this module"
            )
            generators = _independent_generators(self, generators)
            labels = finite_ordered_set(tuple(generators))
            submodule = BasedFreeModule(self.base_ring(), labels)
            embedding = module_homset(submodule, self)(
                {generator: generator for generator in labels}
            )
            return Subobject(embedding)

        def linear_combination(self: Any, coefficients: Any) -> Any:
            r"""Read a finite coefficient vector in the chosen ordered basis."""
            match coefficients:
                case dict():
                    total = self.zero()
                    for label, coefficient in coefficients.items():
                        total += self.base_ring()(coefficient) * self.monomial(label)
                    return total
                case _:
                    coefficients = tuple(coefficients)
                    assert len(coefficients) == self.ngens(), (
                        f"this module has {self.ngens()} basis elements, got "
                        f"{len(coefficients)} coefficients"
                    )
                    return self._from_coordinates(coefficients)

        def hom(self: Any, images: Any, codomain: Any = None) -> Any:
            r"""Construct the map specified on the ordered basis labels."""
            match images:
                case dict() if images:
                    target = next(iter(images.values())).parent()
                    assignment = images
                case dict():
                    assert codomain is not None, (
                        "the empty assignment requires an explicitly named codomain"
                    )
                    target = codomain
                    assignment = images
                case _:
                    images = tuple(images)
                    assert len(images) == self.ngens(), (
                        f"this module has {self.ngens()} basis elements, got "
                        f"{len(images)} images"
                    )
                    if images:
                        target = images[0].parent()
                    else:
                        assert codomain is not None, (
                            "the empty assignment requires an explicitly named codomain"
                        )
                        target = codomain
                    assignment = dict(zip(self.generating_set(), images))
            return self.Hom(target)(assignment)


class BasedFreeModuleElement(ModuleElement):
    r"""An element represented in its parent's chosen ordered basis."""

    def __init__(self, parent: Any, coordinates: Any) -> None:
        ModuleElement.__init__(self, parent)
        self._coordinates_ = vector(parent.base_ring(), list(coordinates))
        assert len(self._coordinates_) == parent.ngens(), (
            f"{parent} has rank {parent.ngens()}, got "
            f"{len(self._coordinates_)} coordinates"
        )

    def _coordinates(self) -> Any:
        return self._coordinates_

    def coefficients(self) -> dict:
        return {
            label: coefficient
            for label, coefficient in zip(
                self.parent().basis_index_set(), self._coordinates_
            )
            if coefficient != 0
        }

    def _add_(self, other: Any) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
            self._coordinates_ + other._coordinates_
        )

    def _sub_(self, other: Any) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
            self._coordinates_ - other._coordinates_
        )

    def _neg_(self) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(-self._coordinates_)

    def _lmul_(self, factor: Any) -> "BasedFreeModuleElement":
        return self.parent()._from_coordinates(
            self.parent().base_ring()(factor) * self._coordinates_
        )

    _rmul_ = _lmul_

    def _richcmp_(self, other: Any, op: int) -> bool:
        return richcmp(self._coordinates_, other._coordinates_, op)

    def __hash__(self) -> int:
        return hash(tuple(self._coordinates_))

    def __iter__(self):
        return iter(self._coordinates_)

    def _repr_(self) -> str:
        return repr(self._coordinates_)


class BasedFreeModule(FreeModuleOnSet):
    r"""The finite specialization of \(F_R(S)\) for a totally ordered \(S\)."""

    Element = BasedFreeModuleElement

    def __init__(self, base_ring: Any, generating_set: Any) -> None:
        match generating_set:
            case int() | SageInteger():
                assert generating_set >= 0, (
                    "the canonical finite framing has nonnegative cardinality"
                )
                generating_set = Sets.Δ[generating_set - 1]
            case Parent():
                pass
            case _:
                generating_set = Set(generating_set)
        generating_set = finite_ordered_set(generating_set)
        FreeModuleOnSet.__init__(self, base_ring, generating_set)
        refine(self, FinitelyGeneratedFreeModules(base_ring))

    def monomial(self, label: Any) -> BasedFreeModuleElement:
        labels = self.basis_index_set()
        assert label in labels, f"{label!r} is not in {labels}"
        index = labels.index(label)
        return self._from_coordinates(
            [self.base_ring()(position == index) for position in range(self.ngens())]
        )

    def ngens(self) -> int:
        return int(self.basis_index_set().cardinality())

    def rank(self) -> Any:
        return ZZ(self.basis_index_set().cardinality())

    def zero(self) -> BasedFreeModuleElement:
        return self._from_coordinates([self.base_ring().zero()] * self.ngens())

    def _from_coordinates(self, coordinates: Any) -> BasedFreeModuleElement:
        return self.element_class(self, coordinates)

    def _element_constructor_(self, value: Any) -> BasedFreeModuleElement:
        assert isinstance(value, BasedFreeModuleElement) and value.parent() is self, (
            f"{value} is not an element of {self}"
        )
        return value

    def __contains__(self, value: Any) -> bool:
        return isinstance(value, BasedFreeModuleElement) and value.parent() is self

    def __eq__(self, other: Any) -> bool:
        return (
            isinstance(other, BasedFreeModule)
            and self.base_ring() == other.base_ring()
            and tuple(self.basis_index_set())
            == tuple(other.basis_index_set())
        )

    def __hash__(self) -> int:
        return hash(
            (
                type(self),
                self.base_ring(),
                tuple(self.basis_index_set()),
            )
        )

    def _repr_(self) -> str:
        return (
            f"Free {self.base_ring()}-module on the ordered set "
            f"{self.basis_index_set()}"
        )

def Free_ZZ(generating_set: Any) -> FreeModuleOnSet:
    r"""Construct the free \(\mathbb Z\)-module on ``generating_set``."""
    return FreeModuleOn(ZZ, generating_set)
