# Repo-scoped stubs; see lexicon/README.md.
from typing import Any, Literal, overload

from sage.modules.free_module_element import FreeModuleElement
from sage.rings.integer import Integer
from sage.structure.element import Matrix

class QuadraticForm:
    def __init__(self, *args: Any, **kwds: Any) -> None: ...
    def signature_vector(self) -> tuple[int, int, int]: ...
    def short_vector_list_up_to_length(self, len_bound: int | Integer, up_to_sign_flag: bool = ...) -> list[list[FreeModuleElement]]: ...
    @overload
    def is_globally_equivalent_to(self, other: QuadraticForm, return_matrix: Literal[False] = ...) -> bool: ...
    @overload
    def is_globally_equivalent_to(self, other: QuadraticForm, return_matrix: Literal[True]) -> Matrix: ...
    def is_rationally_isometric(self, other: QuadraticForm) -> bool: ...
    def Gram_matrix(self) -> Matrix: ...
