r"""Localizing Z at (7) gives a local ring with maximal ideal generated by seven."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_z_localized_at_seven_is_local() -> None:
    local = ZZ.localize_at_prime(7)

    assert local in LocalRings()
    assert local.maximal_ideal() == local.ideal(local(7))
    assert local.residue_field().cardinality() == cardinal(7)
    assert local(3).is_unit()
    assert not local(7).is_unit()

