r"""Isotropic reductions retain the cusp data that presents ``I^perp / I``.

For the hyperbolic plane ``U`` and ``I = Ze`` generated by an isotropic basis
vector, ``I^perp = I`` and hence ``K_I = I^perp/I`` is the zero lattice.  Its
orthogonal group and both Levi images are trivial; the pointwise parabolic and
unipotent kernel are also trivial.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def _zero_reduction_of_u():
    lattice = NamedLattices.U
    isotropic = lattice.module_generator(0)
    reduction = lattice.I_perp_mod_I((isotropic,))
    return lattice, isotropic, reduction


def test_isotropic_reduction_retains_embedding_complement_quotient_and_lifts() -> None:
    lattice, isotropic, reduction = _zero_reduction_of_u()
    sublattice = reduction.isotropic_sublattice()
    perpendicular = reduction.orthogonal_complement()
    embedding = reduction.isotropic_embedding()
    inclusion = reduction.isotropic_inclusion()
    projection = reduction.projection()

    assert reduction in IsotropicReductions(ZZ)
    assert reduction in Lattices(ZZ)
    assert reduction.module_rank() == 0
    assert isinstance(reduction.zero(), reduction.ElementType)
    assert reduction.quotient_lattice() is reduction
    assert embedding.domain() is sublattice
    assert embedding.codomain() is lattice
    assert embedding(sublattice.module_generator(0)) == isotropic
    assert inclusion == reduction.inclusion()
    assert inclusion.domain() is sublattice
    assert inclusion.codomain() is perpendicular
    assert perpendicular.module_rank() == 1
    assert projection.domain() is perpendicular
    assert projection.codomain() is reduction
    assert projection(perpendicular.module_generator(0)) == reduction.zero()
    assert tuple(reduction.reduction_lifts()) == ()


def test_zero_reduction_has_trivial_levi_images_and_unipotent_kernel() -> None:
    _lattice, _isotropic, reduction = _zero_reduction_of_u()
    parabolic = reduction.parabolic_subgroup()
    pointwise = reduction.pointwise_parabolic_subgroup()
    levi = reduction.levi_action()
    image = reduction.levi_image()
    pointwise_image = reduction.pointwise_levi_image()
    kernel = reduction.unipotent_kernel()

    assert parabolic.order() == 2
    assert pointwise.order() == 1
    assert levi.domain() is parabolic
    assert levi.codomain() is reduction.O()
    assert image.order() == 1
    assert pointwise_image.order() == 1
    assert kernel.order() == 1
    assert tuple(reduction.levi_image_generators()) == ()


def test_identity_of_zero_reduction_has_parabolic_and_pointwise_levi_lifts() -> None:
    _lattice, _isotropic, reduction = _zero_reduction_of_u()
    identity = reduction.O().identity()
    lift = reduction.levi_lift(identity)
    split_lift = reduction.lift_isometry(identity)
    pointwise_lift = reduction.pointwise_levi_lift(identity)

    assert lift in reduction.parabolic_subgroup()
    assert split_lift in reduction.parabolic_subgroup()
    assert pointwise_lift in reduction.pointwise_parabolic_subgroup()
    assert reduction.levi_action()(lift) == identity
    assert reduction.levi_action()(split_lift) == identity


def test_rank_one_zero_reduction_builds_its_exact_sequence_and_witt_decomposition() -> None:
    _lattice, _isotropic, reduction = _zero_reduction_of_u()

    assert reduction.parabolic_levi_exact_sequence() is not None
    assert reduction.rational_witt_decomposition() is not None


def test_isotropic_reduction_morphisms_have_identity() -> None:
    _lattice, _isotropic, reduction = _zero_reduction_of_u()
    identity = reduction.Mor(reduction).identity()

    assert identity(reduction.zero()) == reduction.zero()
    assert identity * identity == identity
