r"""A root lattice is generated by its roots as a lattice subobject."""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_a2_root_sublattice_contains_its_simple_roots() -> None:
    lattice = NamedLattices.A2
    root_sublattice = lattice.root_sublattice()

    assert lattice.basis_vector(0) in root_sublattice
    assert lattice.basis_vector(1) in root_sublattice


def test_a2_root_sublattice_has_full_rank() -> None:
    lattice = NamedLattices.A2
    root_sublattice = lattice.root_sublattice()

    assert root_sublattice.rank() == lattice.rank()
