r"""Modules of functions, as a check that nothing here needs coordinates.

$C^\infty(\RR)$ and $L^2(\RR)$ are $\RR$-modules whose elements are functions.
They have no finite generating set, no Gram matrix, and no coordinates, so
they exercise the parts of this preamble that are about being a module rather
than about being a finitely generated one.

Membership is decided where it can be, and admitted as trusted where it
cannot.  A proposed element is a callable; when it is a symbolic expression in
one variable the module reads it and one of three things happens.  It is
*certified*, silently, because a theorem applies.  It is *refused*, loudly,
because a theorem applies the other way.  Or it is *trusted*, with the log
saying what was not checked -- which is what an opaque Python function always
gets, since nothing here can read one.

Smoothness is settled by one structural fact: sums, products, nonnegative
integer powers and compositions of polynomials, $\exp$, $\sin$ and $\cos$ are
$C^\infty$.

Square-integrability over $\RR$ is settled by a ladder of theorems, ordered by
what they cost, and the first one that decides is the answer:

1. rational functions, completely, by the $p$-test;
2. a sine or cosine of $ax+b$, refused for being periodic;
3. a polynomially bounded multiple of a Gaussian, certified for being Schwartz;
4. a sum, from its summands, by Minkowski's inequality;
5. a product, from its factors, by the comparison test;
6. a continuous function whose tail $|x|f(x)$ vanishes at both ends, certified
   by the $p$-test again, this time through a symbolic limit;
7. $\int_\RR f^2$ itself.

The last two tiers are the ones that call a computer algebra system.

Membership is asked once, when an element is built from a function.  An
element built by the module's own arithmetic goes around all of this: a sum,
a negative or a scalar multiple of members is a member because the module is a
module, and re-deciding a theorem is not a check.

The bilinearity of $\langle f,g\rangle=\int fg$ is still not checked; that is a
statement about an arbitrary pairing rather than about a recognizable function.
What *is* checked besides membership is the module structure -- that $\rho(r)$
scales, that addition is addition -- and that the form is a morphism out of the
tensor square with values in $\RR$.
"""

import logging
import operator as _operator
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable

    from sage.categories.morphism import Morphism
    from sage.rings.polynomial.polynomial_element import Polynomial
    from sage.categories.modules import Module
    from sage.rings.ring import Ring
    from dzack_research.preamble.lexicon import Element
    from dzack_research.preamble.owned_category import ConstructionData

from typing import Self

from sage.categories.homset import Hom
from sage.categories.morphism import SetMorphism
from sage.calculus.calculus import limit
from sage.categories.rings import Rings
from sage.functions.error import erf
from sage.functions.hyperbolic import cosh, sech, sinh, tanh
from sage.functions.log import exp
from sage.functions.other import abs_symbolic
from sage.functions.trig import arctan, cos, sin
from sage.rings.infinity import Infinity
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.qqbar import AA
from sage.misc.cachefunc import cached_function
from sage.structure.element import Element as SageElement
from sage.structure.parent import Parent
from sage.symbolic.expression import Expression
from sage.symbolic.integration.integral import integrate
from sage.symbolic.operators import add_vararg, mul_vararg
from sage.symbolic.ring import SR

from dzack_research.preamble.categories.modules.pure.modules import Modules
from dzack_research.preamble.owned_category import object_of
from dzack_research.preamble.owned_category_bases import Category_over_base_ring

if TYPE_CHECKING:
    # What a module of functions is offered as an element: a symbolic
    # expression, which the certifier can read, or an opaque Python callable,
    # which it cannot.  The whole membership ladder is the case distinction
    # between these two.  Type-only; nothing constructs it.
    Function = Expression | Callable

_SMOOTH = "C^infty"
_SQUARE_INTEGRABLE = "L^2"
_THE_REAL_LINE = "RR"

_MEMBER = "a member"
_NOT_MEMBER = "not a member"
_UNDECIDED = "undecided"

# Generators of the two classes recognized structurally, each closed under the
# operations of _is_built_from: the first three are $C^\infty$, and all of
# these are continuous on the whole line.  Neither $\tan$ nor $\log$ is here,
# and neither is continuous on $\RR$.
_SMOOTH_FUNCTIONS = (exp, sin, cos)
_CONTINUOUS_FUNCTIONS = _SMOOTH_FUNCTIONS + (sinh, cosh, tanh, sech, arctan, erf, abs_symbolic)


def _is_built_from(expression: Expression, functions: tuple) -> bool:
    r"""Is ``expression`` a polynomial in ``functions`` and compositions of them?

    The class generated by the polynomials and ``functions`` under sums,
    products, nonnegative integer powers and composition.  Each caller passes
    the functions whose property it wants, and gets it for the whole class:
    both $C^\infty$ and continuity on $\RR$ are preserved by exactly these
    operations, so recognizing the class is a proof of the property.

    A power is admitted only for a nonnegative integer exponent, which is what
    keeps $x^{-1}$ and $\sqrt{x}$ out of both classes.
    """
    operation = expression.operator()
    if operation is None:
        return True  # a variable or a constant
    if operation in (add_vararg, mul_vararg):
        return all(_is_built_from(operand, functions) for operand in expression.operands())
    if operation is _operator.pow:
        base, exponent = expression.operands()
        return (
            _is_built_from(base, functions) and exponent in SageZZ and bool(exponent >= 0)
        )
    if operation in functions:
        return all(_is_built_from(operand, functions) for operand in expression.operands())
    return False


def _decays_like_a_gaussian(expression: Expression, variable: Expression) -> bool:
    r"""Is ``expression`` $e^{-ax^2+bx+c}$ with $a>0$?"""
    if expression.operator() is not exp:
        return False
    exponent = expression.operands()[0]
    return (
        exponent.is_polynomial(variable)
        and exponent.degree(variable) == 2
        and bool(exponent.coefficient(variable, 2r) < 0)
    )


def _is_polynomially_bounded(expression: Expression, variable: Expression) -> bool:
    r"""A polynomial, or a sine or cosine of one, which is bounded by $1$."""
    if expression.is_polynomial(variable):
        return True
    if expression.operator() in (sin, cos):
        argument: Expression = expression.operands()[0]
        return argument.is_polynomial(variable)
    return False


def _is_schwartz(expression: Expression, variable: Expression) -> bool:
    r"""Is ``expression`` a Schwartz function of the recognized shape?

    A Gaussian factor decays faster than any polynomial grows, so a product of
    one with polynomially bounded factors is a Schwartz function, and every
    Schwartz function is in $L^2(\RR)$.
    """
    factors = expression.operands() if expression.operator() is mul_vararg else [expression]
    return any(_decays_like_a_gaussian(factor, variable) for factor in factors) and all(
        _decays_like_a_gaussian(factor, variable) or _is_polynomially_bounded(factor, variable)
        for factor in factors
    )


def _real_polynomial(expression: Expression, variable: Expression) -> "Polynomial | None":
    r"""Return ``expression`` as an exact real polynomial, or ``None``.

    Exact means coefficients in the real algebraic numbers, which is what makes
    the root count below a theorem rather than a numerical impression.  A
    coefficient like $\pi$ leaves that field, and the caller falls through to a
    later tier rather than rounding and guessing.
    """
    if not expression.is_polynomial(variable):
        return None
    coefficients = expression.coefficients(variable, sparse=False)
    if not all(coefficient in AA for coefficient in coefficients):
        return None
    return AA[str(variable)](coefficients)


def _as_rational_function(
    expression: Expression, variable: Expression
) -> "tuple[Polynomial, Polynomial] | None":
    r"""Return $(p,q)$ in lowest terms with $p/q$ the expression, or ``None``.

    Lowest terms matters for what the caller does with it: an uncancelled
    common factor puts a root in $q$ where the function has no pole, and
    $x/(x(1+x^2))$ would be refused for a pole that is not there.
    """
    numerator = _real_polynomial(expression.numerator(), variable)
    denominator = _real_polynomial(expression.denominator(), variable)
    if numerator is None or denominator is None:
        return None
    common = numerator.gcd(denominator)
    return numerator // common, denominator // common


def _rational_verdict(expression: Expression, variable: Expression) -> str:
    r"""Decide $p/q$ completely, by the $p$-test.

    For real polynomials in lowest terms, $p/q\in L^2(\RR)$ exactly when $q$
    has no real root and $\deg q\ge\deg p+1$.  A real root is a pole of some
    order $m\ge1$, near which $(p/q)^2$ grows like $|x-r|^{-2m}$, and that is
    not integrable.  Away from poles the tail of $(p/q)^2$ is $x^{-2d}$ for
    $d=\deg q-\deg p$, and the $p$-test -- the comparison test giving
    $\int^\infty x^{-s}$ convergent exactly for $s>1$ -- makes the tail finite
    exactly when $2d>1$, that is when $d\ge1$.

    This is the whole theorem, so the two familiar cases fall out of it rather
    than being listed: a nonzero polynomial has $q=1$ and $d\le0$, so it is
    refused, and the zero polynomial has $\deg p=-1$, so it is a member.
    """
    fraction = _as_rational_function(expression, variable)
    if fraction is None:
        return _UNDECIDED
    numerator, denominator = fraction
    if denominator.roots(AA):
        return _NOT_MEMBER
    return _MEMBER if denominator.degree() >= numerator.degree() + 1 else _NOT_MEMBER


def _is_bounded(expression: Expression, variable: Expression) -> bool:
    r"""Is ``expression`` bounded on the whole line?

    A sine or cosine is bounded by $1$ wherever its argument is real.  A
    rational function with no real pole and $\deg q\ge\deg p$ is continuous on
    $\RR$ with a finite limit at either end, so it is bounded; a constant is
    the case $\deg q=\deg p=0$.
    """
    if expression.operator() in (sin, cos):
        return True
    fraction = _as_rational_function(expression, variable)
    if fraction is None:
        return False
    numerator, denominator = fraction
    return not denominator.roots(AA) and denominator.degree() >= numerator.degree()


def _sum_verdict(expression: Expression, variable: Expression) -> str:
    r"""Decide a sum from its summands, using that $L^2$ is a vector space.

    All summands in puts the sum in, by Minkowski's inequality
    $\|f+g\|_2\le\|f\|_2+\|g\|_2$.  Exactly one summand out, with the rest in,
    puts the sum out: were the sum a member, subtracting the others would make
    the odd one a member too.
    """
    verdicts = [_square_integrability(summand, variable) for summand in expression.operands()]
    if all(verdict == _MEMBER for verdict in verdicts):
        return _MEMBER
    if verdicts.count(_NOT_MEMBER) == 1 and verdicts.count(_UNDECIDED) == 0:
        return _NOT_MEMBER
    return _UNDECIDED


def _product_verdict(expression: Expression, variable: Expression) -> str:
    r"""Decide a product by the comparison test.

    If $|h|\le C$ and $g\in L^2$ then $(hg)^2\le C^2g^2$ pointwise, so the
    integral is finite.  One factor a member and every other factor bounded is
    therefore enough, and that is the general form of the Gaussian rule.
    """
    factors = expression.operands()
    for position, factor in enumerate(factors):
        others = factors[:position] + factors[position + 1:]
        if all(_is_bounded(other, variable) for other in others) and (
            _square_integrability(factor, variable) == _MEMBER
        ):
            return _MEMBER
    return _UNDECIDED


def _limit_verdict(expression: Expression, variable: Expression) -> str:
    r"""Certify from the tail, by the $p$-test again, when the tail is the question.

    If $f$ is continuous on $\RR$ and $|x|f(x)\to0$ at both ends, then
    eventually $|f|\le|x|^{-1}$, so $f^2\le x^{-2}$, and the $p$-test makes
    both tails finite; continuity makes the bounded middle finite, and
    together that is $f\in L^2(\RR)$.  Continuity is what the middle needs and
    is not optional: $1/x$ has the same tails and a pole.

    Any exponent above $1/2$ would serve, since the $p$-test needs $2k>1$;
    $k=1$ is one probe rather than a search.  A tail limit that is not zero
    proves nothing either way, so this tier never refuses.

    The limit goes to giac, which answers ``undef`` for an oscillating tail
    where the other backends raise instead.  That keeps a computer algebra
    system that cannot answer from becoming an exception to handle.
    """
    if not _is_built_from(expression, _CONTINUOUS_FUNCTIONS):
        return _UNDECIDED
    tails = [
        limit(abs(variable) * expression, algorithm="giac", **{str(variable): direction})
        for direction in (Infinity, -Infinity)
    ]
    return _MEMBER if all(bool(tail == 0) for tail in tails) else _UNDECIDED


def _integral_verdict(expression: Expression, variable: Expression) -> str:
    r"""Ask for $\int_\RR f^2$ and read the answer.

    The last tier, because it is the one that calls the computer algebra
    system.  Sage answers in three distinguishable ways and this reads all
    three: an infinite value is a divergence certificate and refuses, a value
    free of the integration variable is a finite number and certifies, and an
    integral still carrying its variable came back unevaluated and decides
    nothing.

    No exception boundary is needed: this Sage *returns* ``+Infinity`` for a
    divergent integral rather than raising.
    """
    value = integrate(expression**2, variable, -Infinity, Infinity)
    if value.is_infinity():
        return _NOT_MEMBER
    if value.variables():
        return _UNDECIDED
    return _MEMBER


def _square_integrability(expression: Expression, variable: Expression) -> str:
    r"""Decide membership in $L^2(\RR)$ by the cheapest test that settles it.

    Every tier is a theorem and they are ordered by what they cost: rational
    functions by the $p$-test, a wave by its periodicity, a Schwartz shape by
    its decay, a sum by Minkowski, a product by comparison, and only then the
    integral itself.
    """
    verdict = _rational_verdict(expression, variable)
    if verdict != _UNDECIDED:
        return verdict
    if expression.operator() in (sin, cos):
        argument = expression.operands()[0]
        if argument.is_polynomial(variable) and argument.degree(variable) == 1:
            # Periodic and not identically zero: every period adds the same amount.
            return _NOT_MEMBER
    if _is_schwartz(expression, variable):
        return _MEMBER
    if expression.operator() is add_vararg:
        verdict = _sum_verdict(expression, variable)
        if verdict != _UNDECIDED:
            return verdict
    if expression.operator() is mul_vararg:
        verdict = _product_verdict(expression, variable)
        if verdict != _UNDECIDED:
            return verdict
    verdict = _limit_verdict(expression, variable)
    if verdict != _UNDECIDED:
        return verdict
    return _integral_verdict(expression, variable)


def _certify_membership(kind: str, domain_name: str, function: "Function") -> None:
    r"""Certify, refuse, or record that the proposed element is trusted.

    The refusal is an assertion because it is a theorem about the function
    offered: the module can prove this one is not an element.  The trust is a
    log line because the module can prove nothing either way, and saying so is
    the honest form of admitting it.
    """
    if not isinstance(function, Expression):
        logging.info(
            "%r is an opaque callable; membership in %s(%s) is trusted, not checked",
            function, kind, domain_name,
        )
        return

    variables = function.variables()
    if len(variables) > 1:
        logging.info(
            "%s has several variables; membership in %s(%s) is trusted, not checked",
            function, kind, domain_name,
        )
        return
    variable = variables[0] if variables else SR.var("x")

    if kind == _SMOOTH and _is_built_from(function, _SMOOTH_FUNCTIONS):
        return
    if kind == _SQUARE_INTEGRABLE and domain_name == _THE_REAL_LINE:
        verdict = _square_integrability(function, variable)
        assert verdict != _NOT_MEMBER, (
            f"{function} is not square-integrable over RR: the integral of its "
            "square over the line diverges"
        )
        if verdict == _MEMBER:
            return

    logging.info(
        "%s is not of a shape this module can decide; membership in %s(%s) is "
        "trusted, not checked",
        function, kind, domain_name,
    )


class FunctionModules(Category_over_base_ring):
    r"""Modules whose elements are functions of a stated kind on a stated domain."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "function modules"

    def super_categories(self) -> list:
        return [Modules(self.base_ring())]

    class ParentMethods:
        r"""One module of functions: the kind, and the domain they live on."""

        def __init__(
            self: Self,
            kind: str,
            domain_name: str,
            **rest: "ConstructionData",
        ) -> None:
            r"""Add the kind and the domain to the module below.

            The ring is not named here.  ``FunctionModules(R)`` says which
            ring, and the module level reads it off the category and assigns
            the base; naming it again arrives there twice.
            """
            self._kind = kind
            self._domain_name = domain_name
            super().__init__(**rest)

        def base_ring(self: Self) -> "Ring":
            return self.base()

        def _element_constructor_(
            self: Self, function: "Function | Element"
        ) -> "Element":
            if isinstance(function, SageElement) and function.parent() is self:
                return function
            _certify_membership(self._kind, self._domain_name, function)
            member: "Element" = self.element_class(self, function)
            return member

        def zero(self: Self) -> "Element":
            r"""Return the zero function, a member of anything by closure."""
            zero_function: "Element" = self.element_class(self, SR.zero())
            return zero_function

        def _ring_morphism_defining_module_action(self: Self) -> "Morphism":
            r"""Return $\rho:R\to\operatorname{End}(M)$, $r\mapsto(f\mapsto rf)$.

            The action a module of functions has for free: scaling a function is
            scaling its values.  No generating set is consulted, which is the
            point -- the obligation is about being a module, and this module has
            no generators to read it off.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import module_homset

            endomorphisms = module_homset(self, self)
            return SetMorphism(
                Hom(self.base_ring(), endomorphisms, Rings()),
                lambda scalar: SetMorphism(
                    endomorphisms, lambda element: scalar * element
                ),
            )

        def _repr_(self: Self) -> str:
            return (
                f"{self._kind}({self._domain_name}) as a module over "
                f"{self.base_ring()}"
            )

    class ElementMethods:
        r"""A function, as an element of a module of functions."""

        def __init__(
            self: Self,
            parent: Parent,
            function: "Function",
            **rest: "ConstructionData",
        ) -> None:
            assert callable(function), (
                f"an element of {parent} is a function, got {function!r}"
            )
            self._function = function
            super().__init__(parent, **rest)

        def __call__(self: Self, point: "Element") -> "Element":
            r"""Return the value at ``point``; such an element is a function.

            A symbolic expression is evaluated by substituting for its variable,
            which is how Sage evaluates one -- calling it with a bare argument was
            removed from Sage, so an expression is not a callable in the sense the
            other branch means.
            """
            if isinstance(self._function, Expression):
                return self._function.subs({
                    variable: point for variable in self._function.variables()
                })
            return self._function(point)

        def _by_closure(self: Self, function: "Function") -> "Element":
            r"""Return an element of the same module, without certifying it.

            A module is closed under its own operations, so a sum, a negative or a
            scalar multiple of members is a member -- by a theorem, which is why
            this goes around the certifier instead of asking it again.
            """
            parent = self.parent()
            member: "Element" = parent.element_class(parent, function)
            return member

        def _add_(self: Self, other: Self) -> "Element":
            if isinstance(self._function, Expression) and isinstance(other._function, Expression):
                return self._by_closure(self._function + other._function)
            return self._by_closure(lambda point: self(point) + other(point))

        def _neg_(self: Self) -> "Element":
            if isinstance(self._function, Expression):
                return self._by_closure(-self._function)
            return self._by_closure(lambda point: -self(point))

        def _lmul_(self: Self, scalar: "Element") -> "Element":
            if isinstance(self._function, Expression):
                return self._by_closure(scalar * self._function)
            return self._by_closure(lambda point: scalar * self(point))

        _rmul_ = _lmul_

        def _repr_(self: Self) -> str:
            return f"function in {self.parent()}"


@cached_function
def FunctionModule(base_ring: "Ring", kind: str, domain_name: str) -> Parent:
    r"""Return the $R$-module of functions of a stated kind on a stated domain.

    Cached on its arguments: one module per $(R,\text{kind},\text{domain})$, or
    two parents print alike and their elements refuse to add.
    """
    return object_of(
        FunctionModules(base_ring),
        kind=kind,
        domain_name=domain_name,
    )


def smooth_functions(base_ring: "Ring", domain_name: str = _THE_REAL_LINE) -> Parent:
    r"""Return $C^\infty$ on the named domain, as an $R$-module."""
    return FunctionModule(base_ring, _SMOOTH, domain_name)


def square_integrable_functions(
    base_ring: "Ring", domain_name: str = _THE_REAL_LINE
) -> Parent:
    r"""Return $L^2$ on the named domain, as an $R$-module."""
    return FunctionModule(base_ring, _SQUARE_INTEGRABLE, domain_name)
