# Sage reference implementation: sage/categories/enumerated_sets.py.
from collections.abc import Iterator
from typing import Generic, TypeVar

from sage.categories.category_with_axiom import CategoryWithAxiom
from sage.categories.sets_cat import Sets
from sage.rings.infinity import PlusInfinity
from sage.rings.integer import Integer

_E = TypeVar("_E")

class EnumeratedSets(CategoryWithAxiom):
    class ParentMethods(Sets.ParentMethods[_E], Generic[_E]):
        def __iter__(self) -> Iterator[_E]: ...
        def first(self) -> _E: ...
        def next(self, element: _E) -> _E | None: ...
        def unrank(self, rank: int | Integer) -> _E: ...
        def rank(self, element: _E) -> int | Integer | None: ...
        def list(self) -> list[_E]: ...
        def cardinality(self) -> Integer | PlusInfinity: ...
