# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.categories.category import Category
from sage.categories.morphism import Morphism

class Functor:
    def __init__(self, domain: Category, codomain: Category) -> None: ...
    def __call__(self, value: Any) -> Any: ...
    def domain(self) -> Category: ...
    def codomain(self) -> Category: ...
    def _apply_functor_to_morphism(self, f: Morphism) -> Morphism: ...

class ForgetfulFunctor_generic(Functor): ...

def ForgetfulFunctor(domain: Category, codomain: Category) -> Functor: ...
