# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.structure.element import Element

class Morphism(Element):
    def __init__(self, parent: Any) -> None: ...
    def domain(self) -> Any: ...
    def codomain(self) -> Any: ...
    def category_for(self) -> Any: ...
    # Map.__call__ (map.pyx:683) converts into the domain and dispatches to
    # _call_/_call_with_args, both `cpdef Element`.
    def __call__(self, x: object, *args: object, **kwds: object) -> Element: ...
    # The coercion-free hooks (map.pyx:830): _call_ assumes x already lives in
    # the domain; __call__ converts first. They are NOT interchangeable.
    def _call_(self, x: Element) -> Element: ...
    def _call_with_args(
        self, x: Element, args: tuple[object, ...] = ..., kwds: dict[str, object] = ...
    ) -> Element: ...
    # Map.__mul__ is composition.
    def __mul__(self, right: Morphism) -> Morphism: ...

class IdentityMorphism(Morphism): ...

class SetMorphism(Morphism):
    def __init__(self, parent: Any, function: Any) -> None: ...
    def __call__(self, x: object, *args: object, **kwds: object) -> Element: ...
