# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.categories.category import Category
from sage.structure.element import Element
from sage.structure.parent import Parent

class Morphism(Element):
    def __init__(self, parent: Any) -> None: ...
    # The domain and codomain of a morphism are objects of its ambient
    # category, realized as Sage parents (verified on ring homs).
    def domain(self) -> Parent: ...
    def codomain(self) -> Parent: ...
    def category_for(self) -> Category: ...
    # Map.__call__ (map.pyx:683) converts into the domain and dispatches to
    # _call_/_call_with_args, both `cpdef Element`.
    def __call__(self, x: object, *args: object, **kwds: object) -> Element: ...
    # The coercion-free hooks (map.pyx:830): _call_ assumes x already lives in
    # the domain; __call__ converts first. They are NOT interchangeable.
    def _call_(self, x: Element) -> Element: ...
    def _call_with_args(self, x: Element, args: tuple[object, ...] = ..., kwds: dict[str, object] = ...) -> Element: ...
    # Map.__mul__ is composition.
    def __mul__(self, right: Morphism) -> Morphism: ...

class IdentityMorphism(Morphism): ...

class SetMorphism(Morphism):
    def __init__(self, parent: Any, function: Any) -> None: ...
    def __call__(self, x: object, *args: object, **kwds: object) -> Element: ...
