from collections.abc import Sequence
from typing import Self

from sage.categories.groups import Group, GroupElement
from sage.rings.integer import Integer
from sage.structure.element import RingElement

class ClassFunction:
    def __init__(self, group: Group, values: Sequence[RingElement]) -> None: ...
    def domain(self) -> Group: ...
    def degree(self) -> Integer: ...
    def values(self) -> list[RingElement]: ...
    def irreducible_constituents(self) -> tuple[ClassFunction, ...]: ...
    def __call__(self, element: GroupElement) -> RingElement: ...
    def __add__(self, other: ClassFunction) -> Self: ...
