# Repo-scoped stubs; see lexicon/README.md.
#
# O(q) for a finite quadratic form: the orthogonal group of a torsion
# quadratic module, returned by TorsionQuadraticModule.orthogonal_group. Its
# elements are automorphisms of the finite abelian group preserving the form,
# and each is read as the matrix of its action on the generators.
from collections.abc import Iterator

from sage.categories.groups import Groups
from sage.groups.abelian_gps.abelian_aut import AbelianGroupAutomorphism
from sage.rings.integer import Integer

class FqfIsometry(AbelianGroupAutomorphism):
    def parent(self) -> FqfOrthogonalGroup: ...

class FqfOrthogonalGroup(Groups.ParentMethods[FqfIsometry]):
    def gens(self) -> tuple[FqfIsometry, ...]: ...
    def ngens(self) -> int: ...
    def order(self) -> Integer: ...
    def is_finite(self) -> bool: ...
    def __iter__(self) -> Iterator[FqfIsometry]: ...
    def __contains__(self, x: object) -> bool: ...
