"""Lazy public aggregation for owned Set-side constructions.

The defining modules must remain independently importable. Python executes a
package ``__init__`` before any submodule, so eager re-exports here create
artificial defining-module cycles. Public names are resolved lazily instead.
"""

from importlib import import_module as _import_module

_EXPORTS = {'CountableSets': ('dzack_research.preamble.categories.sets.set_categories', 'CountableSets'),
 'CountablyInfiniteSets': ('dzack_research.preamble.categories.sets.set_categories',
                           'CountablyInfiniteSets'),
 'FiniteSets': ('dzack_research.preamble.categories.sets.set_categories', 'FiniteSets'),
 'FinitelySupportedFunctionSets': ('dzack_research.preamble.categories.sets.set_categories',
                                   'FinitelySupportedFunctionSets'),
 'InfiniteSets': ('dzack_research.preamble.categories.sets.set_categories', 'InfiniteSets'),
 'NaturalNumber': ('dzack_research.preamble.categories.sets.set_categories', 'NaturalNumber'),
 'NaturalNumbers': ('dzack_research.preamble.categories.sets.set_categories', 'NaturalNumbers'),
 'NN': ('dzack_research.preamble.categories.sets.set_categories', 'NN'),
 'PartiallyOrderedSets': ('dzack_research.preamble.categories.sets.set_categories',
                          'PartiallyOrderedSets'),
 'Sets': ('dzack_research.preamble.categories.sets.set_categories', 'Sets'),
 'TotallyOrderedSets': ('dzack_research.preamble.categories.sets.set_categories',
                        'TotallyOrderedSets'),
 'UncountableSets': ('dzack_research.preamble.categories.sets.set_categories', 'UncountableSets'),
 'placement_of': ('dzack_research.preamble.categories.sets.set_categories', 'placement_of'),
 'register_set_axioms': ('dzack_research.preamble.categories.sets.set_categories',
                         'register_set_axioms'),
 'cartesian_product_of': ('dzack_research.preamble.categories.sets.set_categories',
                          'cartesian_product_of'),
 'PowerSets': ('dzack_research.preamble.categories.sets.set_categories', 'PowerSets'),
 'ObjectSetsOfDiscreteCategories': ('dzack_research.preamble.categories.sets.set_categories',
                                    'ObjectSetsOfDiscreteCategories'),
 'FinitePowerSets': ('dzack_research.preamble.categories.sets.set_categories', 'FinitePowerSets'),
 'DisjointUnionsOfSets': ('dzack_research.preamble.categories.sets.set_categories',
                          'DisjointUnionsOfSets'),
 'CoproductsOfSets': ('dzack_research.preamble.categories.sets.set_categories', 'CoproductsOfSets'),
 'CoproductOfSets': ('dzack_research.preamble.categories.sets.set_categories', 'CoproductOfSets'),
 'CoproductOfFamily': ('dzack_research.preamble.categories.sets.set_categories',
                       'CoproductOfFamily'),
 'CoproductMorphism': ('dzack_research.preamble.categories.sets.set_categories',
                       'CoproductMorphism'),
 'CartesianProductsOfSets': ('dzack_research.preamble.categories.sets.set_categories',
                             'CartesianProductsOfSets'),
 'CartesianProductOfSets': ('dzack_research.preamble.categories.sets.set_categories',
                            'CartesianProductOfSets'),
 'CartesianProductOfFamily': ('dzack_research.preamble.categories.sets.set_categories',
                              'CartesianProductOfFamily'),
 'CartesianProductMorphism': ('dzack_research.preamble.categories.sets.set_categories',
                              'CartesianProductMorphism'),
 'ConditionSet': ('dzack_research.preamble.categories.sets.set_categories', 'ConditionSet'),
 'ExponentialOfSets': ('dzack_research.preamble.categories.sets.set_categories',
                       'ExponentialOfSets'),
 'FiniteSubsets': ('dzack_research.preamble.categories.sets.set_categories', 'FiniteSubsets'),
 'ImageSet': ('dzack_research.preamble.categories.sets.set_categories', 'ImageSet'),
 'PowerSet': ('dzack_research.preamble.categories.sets.set_categories', 'PowerSet'),
 'Set': ('dzack_research.preamble.categories.sets.set_categories', 'Set'),
 'SetInclusion': ('dzack_research.preamble.categories.sets.set_categories', 'SetInclusion'),
 'SetInjection': ('dzack_research.preamble.categories.sets.set_categories', 'SetInjection'),
 'SetSurjection': ('dzack_research.preamble.categories.sets.set_categories', 'SetSurjection'),
 'SubsetsOfSize': ('dzack_research.preamble.categories.sets.set_categories', 'SubsetsOfSize'),
 'set_injection': ('dzack_research.preamble.categories.sets.set_categories', 'set_injection'),
 'set_surjection': ('dzack_research.preamble.categories.sets.set_categories', 'set_surjection'),
 'CardinalComparison': ('dzack_research.preamble.categories.sets.cardinals', 'CardinalComparison'),
 'Cardinalities': ('dzack_research.preamble.categories.sets.cardinals', 'Cardinalities'),
 'OrdinalSemirings': ('dzack_research.preamble.categories.sets.cardinals', 'OrdinalSemirings'),
 'Ordinals': ('dzack_research.preamble.categories.sets.cardinals', 'Ordinals'),
 'aleph': ('dzack_research.preamble.categories.sets.cardinals', 'aleph'),
 'aleph0': ('dzack_research.preamble.categories.sets.cardinals', 'aleph0'),
 'cardinal': ('dzack_research.preamble.categories.sets.cardinals', 'cardinal'),
 'continuum': ('dzack_research.preamble.categories.sets.cardinals', 'continuum'),
 'omega': ('dzack_research.preamble.categories.sets.cardinals', 'omega'),
 'omega0': ('dzack_research.preamble.categories.sets.cardinals', 'omega0'),
 'ordinal': ('dzack_research.preamble.categories.sets.cardinals', 'ordinal'),
 'EnumeratedByIntegers': ('dzack_research.preamble.categories.sets.enumerated',
                          'EnumeratedByIntegers'),
 'EnumeratedByNaturals': ('dzack_research.preamble.categories.sets.enumerated',
                          'EnumeratedByNaturals'),
 'EnumeratedSets': ('dzack_research.preamble.categories.sets.enumerated', 'EnumeratedSets'),
 'FourierCharacters': ('dzack_research.preamble.categories.sets.enumerated', 'FourierCharacters'),
 'FunctionEnumeratedSets': ('dzack_research.preamble.categories.sets.enumerated',
                            'FunctionEnumeratedSets'),
 'HermitePolynomials': ('dzack_research.preamble.categories.sets.enumerated', 'HermitePolynomials'),
 'InfiniteEnumeratedSets': ('dzack_research.preamble.categories.sets.enumerated',
                            'InfiniteEnumeratedSets'),
 'LaurentMonomials': ('dzack_research.preamble.categories.sets.enumerated', 'LaurentMonomials'),
 'SincTranslates': ('dzack_research.preamble.categories.sets.enumerated', 'SincTranslates'),
 'FixedSizeSelectionElement': ('dzack_research.preamble.categories.sets.fixed_size_selections',
                               'FixedSizeSelectionElement'),
 'FixedSizeSelections': ('dzack_research.preamble.categories.sets.fixed_size_selections',
                         'FixedSizeSelections'),
 'fixed_size_selections': ('dzack_research.preamble.categories.sets.fixed_size_selections',
                           'fixed_size_selections'),
 'multisets_of_size': ('dzack_research.preamble.categories.sets.fixed_size_selections',
                       'multisets_of_size'),
 'ordered_subsets_of_size': ('dzack_research.preamble.categories.sets.fixed_size_selections',
                             'ordered_subsets_of_size'),
 'IndexedFamily': ('dzack_research.preamble.categories.sets.indexed_families', 'IndexedFamily'),
 'finite_indexed_family': ('dzack_research.preamble.categories.sets.indexed_families',
                           'finite_indexed_family'),
 'indexed_family': ('dzack_research.preamble.categories.sets.indexed_families', 'indexed_family'),
 'FiniteFilteredOrderedSet': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                              'FiniteFilteredOrderedSet'),
 'FiniteOrderedSet': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                      'FiniteOrderedSet'),
 'OrderedEnumeratedSet': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                          'OrderedEnumeratedSet'),
 'finite_ordered_filter': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                           'finite_ordered_filter'),
 'finite_ordered_image': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                          'finite_ordered_image'),
 'finite_ordered_set': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                        'finite_ordered_set'),
 'ordered_enumerated_set': ('dzack_research.preamble.categories.sets.finite_ordered_sets',
                            'ordered_enumerated_set')}

__all__ = ['cartesian_product_of',
 'PowerSets',
 'ObjectSetsOfDiscreteCategories',
 'FinitePowerSets',
 'DisjointUnionsOfSets',
 'CoproductsOfSets',
 'CoproductOfSets',
 'CoproductOfFamily',
 'CoproductMorphism',
 'CartesianProductsOfSets',
 'CartesianProductOfSets',
 'CartesianProductOfFamily',
 'CartesianProductMorphism',
 'register_set_axioms',
 'placement_of',
 'UncountableSets',
 'TotallyOrderedSets',
 'PartiallyOrderedSets',
 'InfiniteSets',
 'NaturalNumber',
 'NaturalNumbers',
 'NN',
 'FinitelySupportedFunctionSets',
 'FiniteSets',
 'FixedSizeSelectionElement',
 'FixedSizeSelections',
 'CountablyInfiniteSets',
 'CountableSets',
 'Sets',
 'ConditionSet',
 'ExponentialOfSets',
 'FiniteSubsets',
 'ImageSet',
 'PowerSet',
 'Set',
 'SetInclusion',
 'SetInjection',
 'SetSurjection',
 'set_injection',
 'set_surjection',
 'SubsetsOfSize',
 'CardinalComparison',
 'Cardinalities',
 'OrdinalSemirings',
 'Ordinals',
 'aleph',
 'aleph0',
 'cardinal',
 'continuum',
 'omega',
 'omega0',
 'ordinal',
 'EnumeratedByIntegers',
 'EnumeratedByNaturals',
 'EnumeratedSets',
 'FiniteFilteredOrderedSet',
 'FiniteOrderedSet',
 'OrderedEnumeratedSet',
 'FourierCharacters',
 'FunctionEnumeratedSets',
 'HermitePolynomials',
 'InfiniteEnumeratedSets',
 'IndexedFamily',
 'LaurentMonomials',
 'SincTranslates',
 'finite_indexed_family',
 'fixed_size_selections',
 'finite_ordered_filter',
 'finite_ordered_image',
 'finite_ordered_set',
 'indexed_family',
 'multisets_of_size',
 'ordered_subsets_of_size',
 'ordered_enumerated_set']

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
