# Repo-scoped stubs; see lexicon/README.md.
from collections.abc import Callable
from typing import Any

from sage.rings.integer import Integer
from sage.structure.element import CommutativeRingElement

class Expression(CommutativeRingElement):
    # expression.pyx:6129 — calling an expression substitutes into it;
    # callable(x^2 + 1) is True, so Expression must not be narrowed away
    # by callable() guards.
    def __call__(self, *args: object, **kwds: object) -> Expression: ...
    def subs(self, *args: object, **kwds: object) -> Expression: ...
    # The head of the expression tree: add_vararg, mul_vararg, operator.pow,
    # or a symbolic function such as exp/sin/cos. None at a leaf.
    def operator(self) -> Callable[..., object] | None: ...
    def operands(self) -> list[Expression]: ...
    def variables(self) -> tuple[Expression, ...]: ...
    def is_polynomial(self, variable: Expression) -> bool: ...
    def degree(self, variable: Expression) -> Expression: ...
    def coefficient(self, variable: Expression, n: int | Integer = ...) -> Expression: ...
    def coefficients(self, variable: Expression = ..., sparse: bool = ...) -> list[object]: ...
    def numerator(self) -> Expression: ...
    def denominator(self) -> Expression: ...
    def is_infinity(self) -> bool: ...
    def __add__(self, other: Any) -> Expression: ...
    def __radd__(self, other: Any) -> Expression: ...
    def __sub__(self, other: Any) -> Expression: ...
    def __rsub__(self, other: Any) -> Expression: ...
    def __mul__(self, other: Any) -> Expression: ...
    def __rmul__(self, other: Any) -> Expression: ...
    def __truediv__(self, other: Any) -> Expression: ...
    def __rtruediv__(self, other: Any) -> Expression: ...
    def __pow__(self, other: Any) -> Expression: ...
    def __neg__(self) -> Expression: ...
    def sqrt(self) -> Expression: ...
    def simplify_full(self) -> Expression: ...
    def n(self, prec: int = ...) -> Any: ...
