r"""Archived anisotropic-vector primitive-extension data on the live lattice owner.

For a primitive anisotropic vector ``w`` the archived vector-orbit layer
retained the finite-index orthogonal sum ``Zw + w^perp -> L``, its gluing
subgroup in the discriminant form of that sum, and the quotient identification
``A_L = H^perp/H``.  These specimens keep that exact mathematical structure on
the current ``VectorPrimitiveExtension`` object.
"""

from dzack_research.preamble.all import Lattices, ZZ

ARCHIVE_RECONCILIATION = {
    "archive_module": "preamble/categories/modules/framed/formed/integrallattice/vector_orbits.sage",
    "live_owner": "src/dzack_research/preamble/categories/vector_orbits.py",
    "owner_overrides": {
        "orthogonal_group_vector_equivalence_witness": "src/dzack_research/preamble/categories/lattice_morphisms.py",
        "orthogonal_group_vector_stabilizer_generators": "src/dzack_research/preamble/categories/lattice_morphisms.py",
        "vector_primitive_extension": "src/dzack_research/preamble/categories/lattices.py",
    },
    "disposition": "reconciled-live-owner",
}


def test_archived_a2_vector_extension_has_the_expected_nontrivial_gluing() -> None:
    lattice = Lattices(ZZ)("A2")
    vector = lattice.module_generators()[0]
    extension = lattice.vector_primitive_extension(vector)

    assert extension.lattice is lattice
    assert extension.vector == vector
    assert extension.line.ambient_lattice() is lattice
    assert extension.complement.ambient_lattice() is lattice
    assert extension.line.module_rank() == 1
    assert extension.complement.module_rank() == 1
    assert extension.sum_lattice.module_rank() == 2

    # If G(A2)=[[-2,1],[1,-2]] and w=e1, then w^perp is generated by
    # e1+2e2, so Zw + w^perp has determinant-two inclusion in A2.
    assert extension.index == 2
    assert extension.gluing_subgroup.cardinality() == 2
    assert len(extension.gluing_images) == 2

    for glued in extension.gluing_images:
        assert extension.sum_form.b(
            glued, glued
        ) == extension.sum_form.bilinear_value_module().zero()


def test_archived_discriminant_classes_round_trip_through_h_perp_mod_h() -> None:
    lattice = Lattices(ZZ)("A2")
    extension = lattice.vector_primitive_extension(lattice.module_generators()[0])

    assert extension.discriminant_form.cardinality() == 3
    for discriminant_class in extension.discriminant_form.elements():
        representative = extension.representative_of(discriminant_class)
        assert extension.class_of_representative(representative) == discriminant_class
        for glued in extension.gluing_images:
            assert (
                extension.class_of_representative(representative + glued)
                == discriminant_class
            )


def test_archived_line_and_complement_discriminant_maps_land_in_the_sum_form() -> None:
    lattice = Lattices(ZZ)("A2")
    extension = lattice.vector_primitive_extension(lattice.module_generators()[0])

    line_form = extension.line.discriminant_group()
    complement_form = extension.complement.discriminant_group()
    line_map = extension.line_discriminant_inclusion
    complement_map = extension.complement_discriminant_inclusion

    assert line_map.domain() is line_form
    assert line_map.codomain() is extension.sum_form
    assert complement_map.domain() is complement_form
    assert complement_map.codomain() is extension.sum_form

    generated = extension.sum_form.subobject_generated_by(
        tuple(line_map(element) for element in line_form.module_generators())
        + tuple(
            complement_map(element)
            for element in complement_form.module_generators()
        )
    )
    assert generated.cardinality() == extension.sum_form.cardinality()
