r"""Reflection groups of hyperbolic lattices, and Vinberg's enumeration.

Vinberg's algorithm enumerates the walls of a fundamental polyhedron for
\(W(L)\).  It is a semi-decision procedure: it halts with a certificate when
the polyhedron closes, so a completed search proves reflectivity while a
bounded one proves nothing.  The tests below state what a completed search
delivers on \(U\oplus A_1\), and check Vinberg's root-length bound against the
two Bogachev-Kolpakov ternary lattices, where the bound is what makes "does
this lattice have a root" a finite question.

Sources: Vinberg, *On groups of unit elements of certain quadratic forms*,
Mat. Sb. 87 (1972); Vinberg, *Hyperbolic reflection groups*, Russian Math.
Surveys 40 (1985); Bogachev and Kolpakov, *Thin hyperbolic reflection groups*,
arXiv:2112.14642v4, sections 6.1 and 6.2.
"""

import pytest
from sage.all import ZZ as SageZZ

from dzack_research.preamble.all import HyperbolicLattices, Lattices, ZZ


def u_plus_a1():
    r"""Return \(U\oplus A_1\), of signature \((1,2)\), as a hyperbolic lattice."""
    return HyperbolicLattices(ZZ)(Lattices(ZZ)("U") + Lattices(ZZ)("A1"))


def test_a_lattice_enters_the_category_by_its_signature() -> None:
    r"""One index of inertia equal to one is the hypothesis, and it is checked."""
    lattice = u_plus_a1()
    signature = lattice.signature_pair()

    assert lattice in HyperbolicLattices(ZZ)
    assert (signature.first(), signature.second()) == (1, 2)

    definite = Lattices(ZZ)("A2")
    assert definite not in HyperbolicLattices(ZZ)
    with pytest.raises(AssertionError):
        HyperbolicLattices(ZZ)(definite)


def test_vinbergs_criterion_bounds_the_root_lengths_of_the_bogachev_kolpakov_lattices() -> None:
    r"""Every root length divides twice the last invariant factor.

    Bogachev and Kolpakov, arXiv:2112.14642v4 section 6.2, citing Vinberg: for
    a root \(r\), \(q(r)\) divides twice the last invariant factor of the
    correlation, which is the exponent of the discriminant group.  For the
    section 6.1 lattice the invariant factors are \(1, 49, 49\), so every root
    length divides \(98\); for the section 6.2 lattice they are
    \(1, 49, 2401\), so every root length divides \(4802 = 2\cdot 7^4\).  That
    bound is why the paper can say the second lattice has no roots at all: what
    would otherwise be an unbounded search is a check of four candidate
    lengths.
    """
    with_roots = HyperbolicLattices(ZZ)(Lattices.BogachevKolpakovNonReflective)
    without_roots = HyperbolicLattices(ZZ)(Lattices.BogachevKolpakovWithoutRoots)

    assert tuple(with_roots.possible_root_lengths()) == (1, 2, 7, 14, 49, 98)

    lengths = without_roots.possible_root_lengths()
    assert tuple(lengths) == tuple(SageZZ(4802).divisors())
    for candidate in (49, 98, 2401, 4802):
        assert candidate in lengths, "a candidate length the paper had to exclude"


def test_vinberg_enumeration_closes_the_polyhedron_of_u_plus_a1() -> None:
    r"""The search on \(U\oplus A_1\) completes, which certifies reflectivity.

    What a completed search delivers is the wall set of a fundamental
    polyhedron.  Each wall is the mirror of a root, so each accepted vector is
    a root of the lattice, its reflection is an involution of \(O(L)\), and its
    length obeys Vinberg's bound.  Those are the claims here; the number of
    walls is not asserted, because it depends on the controlling vector the
    engine chose.
    """
    lattice = u_plus_a1()
    roots = lattice.vinberg_simple_roots(max_decompositions=200)

    assert lattice.is_reflective(max_decompositions=200) is True
    assert roots.cardinality() >= 3, "a polyhedron in H^2 has at least three walls"

    lengths = lattice.possible_root_lengths()
    identity = lattice.O().one()
    for root in roots:
        assert root.is_root()
        assert abs(root.q()) in lengths, "Vinberg's criterion bounds the length"
        reflection = lattice.reflection(root)
        assert reflection in lattice.O()
        assert reflection * reflection == identity
        assert reflection(root) == -root


def test_the_reflection_group_is_a_subgroup_of_the_orthogonal_group() -> None:
    r"""\(W(L)\) is generated by the reflections in the walls.

    The mirrors of the walls of a fundamental polyhedron generate the whole
    reflection subgroup, so \(W(L)\) is built as a subgroup of the owned
    orthogonal group and not as an abstract Coxeter group.  Its Coxeter diagram
    is the rooted diagram on the walls, whose bonds are read from the actual
    root pairings.
    """
    lattice = u_plus_a1()
    roots = lattice.vinberg_simple_roots(max_decompositions=200)
    group = lattice.reflection_group(max_decompositions=200)
    diagram = lattice.reflection_coxeter_diagram(max_decompositions=200)

    assert group.group_generators().cardinality() == roots.cardinality()
    assert diagram.is_rooted()
    assert diagram.cardinality() == roots.cardinality()
    # The walls are roots of an integral lattice, so every dihedral angle
    # between two of them is one the crystallographic restriction allows.
    assert diagram.vinberg_invariant_matrix().is_crystallographic()


def test_a_lattice_that_represents_zero_has_a_noncompact_fundamental_domain() -> None:
    r"""\(U\oplus A_1\) is reflective and not cocompact.

    \(U\) is isotropic, so the light cone of \(L\otimes\mathbb R\) meets the
    lattice, and the fundamental polyhedron has a vertex on the boundary of
    hyperbolic space.  A polyhedron is compact exactly when it has finite
    volume and no such ideal vertex, so the domain here has finite volume and
    is not compact, which is the common hyperbolic case rather than a defect.
    """
    lattice = u_plus_a1()

    assert lattice.is_reflective(max_decompositions=200) is True
    assert lattice.is_cocompact(max_decompositions=200) is False
