r"""Anisotropic-vector primitive extensions: ``Zw + w^perp -> L`` and its gluing.

For a primitive anisotropic vector ``w`` of ``L``, the orthogonal sum
``Zw + w^perp`` has finite index in ``L``, and ``L`` is recovered from it by an
isotropic gluing subgroup of the discriminant form of the sum.
"""

from dzack_research.preamble.all import *


def test_archived_a2_vector_extension_has_the_expected_nontrivial_gluing() -> None:
    lattice = Lattices(ZZ)("A2")
    vector = lattice.module_generators()[0]
    extension = lattice.vector_primitive_extension(vector)

    assert extension.lattice is lattice
    assert extension.vector == vector
    assert extension.line.ambient_lattice() is lattice
    assert extension.complement.ambient_lattice() is lattice
    assert extension.line.module_rank() == 1
    assert extension.complement.module_rank() == 1
    assert extension.sum_lattice.module_rank() == 2

    # If G(A2)=[[-2,1],[1,-2]] and w=e1, then w^perp is generated by
    # e1+2e2, so Zw + w^perp has determinant-two inclusion in A2.
    assert extension.index == 2
    assert extension.gluing_subgroup.cardinality() == 2
    assert extension.gluing_images.cardinality() == 2

    for glued in extension.gluing_images:
        assert extension.sum_form.b(
            glued, glued
        ) == extension.sum_form.bilinear_value_module().zero()
