'Owned module hierarchy.'

from importlib import import_module as _import_module

_EXPORTS = {'Biproduct': ('dzack_research.preamble.categories.abstract_categories', 'Biproduct'),
 'Subobjects': ('dzack_research.preamble.categories.abstract_categories', 'Subobjects'),
 'TensorProduct': ('dzack_research.preamble.categories.abstract_categories', 'TensorProduct'),
 'TensorSquare': ('dzack_research.preamble.categories.abstract_categories', 'TensorSquare'),
 'BiproductModules': ('dzack_research.preamble.categories.modules.pure.modules',
                      'BiproductModules'),
 'biproduct_morphism': ('dzack_research.preamble.categories.modules.pure.modules',
                        'biproduct_morphism'),
 'FractionalIdeal': ('dzack_research.preamble.categories.modules.fractional_ideals',
                     'FractionalIdeal'),
 'FractionalIdeals': ('dzack_research.preamble.categories.modules.fractional_ideals',
                      'FractionalIdeals'),
 'Ideal': ('dzack_research.preamble.categories.modules.fractional_ideals', 'Ideal'),
 'Ideals': ('dzack_research.preamble.categories.modules.fractional_ideals', 'Ideals'),
 'FinitelyGeneratedFreeModules': ('dzack_research.preamble.categories.modules.pure.modules',
                                  'FinitelyGeneratedFreeModules'),
 'BasedFreeModule': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                     'BasedFreeModule'),
 'ring_as_module': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                    'ring_as_module'),
 'ModulesWithChosenFinitePresentation': ('dzack_research.preamble.categories.modules.pure.modules',
                                         'ModulesWithChosenFinitePresentation'),
 'FinitelyPresentedModule': ('dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules',
                             'FinitelyPresentedModule'),
 'FinitelyPresentedTorsionModules': ('dzack_research.preamble.categories.modules.pure.torsion_modules',
                                     'FinitelyPresentedTorsionModules'),
 'TorsionModule': ('dzack_research.preamble.categories.modules.pure.torsion_modules',
                   'TorsionModule'),
 'BilinearForm': ('dzack_research.preamble.categories.modules.framed.formed', 'BilinearForm'),
 'BilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                         'BilinearFormModules'),
 'DiscriminantBilinearModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'DiscriminantBilinearModules'),
 'DiscriminantModule': ('dzack_research.preamble.categories.modules.framed.formed',
                        'DiscriminantModule'),
 'DiscriminantModules': ('dzack_research.preamble.categories.modules.framed.formed',
                         'DiscriminantModules'),
 'DiscriminantQuadraticModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'DiscriminantQuadraticModules'),
 'FiberedFormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed',
                               'FiberedFormedModuleHomset'),
 'FiberedFormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'FiberedFormedModuleMorphism'),
 'FinitelyGeneratedFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'FinitelyGeneratedFormModules'),
 'FinitelyGeneratedFreeFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                      'FinitelyGeneratedFreeFormModules'),
 'FinitelyPresentedBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                          'FinitelyPresentedBilinearFormModules'),
 'FinitelyPresentedFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'FinitelyPresentedFormModules'),
 'FinitelyPresentedQuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                           'FinitelyPresentedQuadraticFormModules'),
 'FormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed',
                        'FormedModuleHomset'),
 'FormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed',
                          'FormedModuleMorphism'),
 'FormedModules': ('dzack_research.preamble.categories.modules.framed.formed', 'FormedModules'),
 'FormEmbedding': ('dzack_research.preamble.categories.modules.framed.formed', 'FormEmbedding'),
 'FormModule': ('dzack_research.preamble.categories.modules.framed.formed', 'FormModule'),
 'FormModules': ('dzack_research.preamble.categories.modules.framed.formed', 'FormModules'),
 'FreeFormModules': ('dzack_research.preamble.categories.modules.framed.formed', 'FreeFormModules'),
 'PairedModules': ('dzack_research.preamble.categories.modules.framed.formed', 'PairedModules'),
 'QuadraticForm': ('dzack_research.preamble.categories.modules.framed.formed', 'QuadraticForm'),
 'QuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                          'QuadraticFormModules'),
 'SymmetricBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'SymmetricBilinearFormModules'),
 'TorsionBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                'TorsionBilinearFormModules'),
 'TorsionFormIsometry': ('dzack_research.preamble.categories.modules.framed.formed',
                         'TorsionFormIsometry'),
 'TorsionQuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'TorsionQuadraticFormModules'),
 'fibered_formed_module_homset': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'fibered_formed_module_homset'),
 'form_embedding': ('dzack_research.preamble.categories.modules.framed.formed', 'form_embedding'),
 'formed_module_homset': ('dzack_research.preamble.categories.modules.framed.formed',
                          'formed_module_homset'),
 'FractionFieldQuotient': ('dzack_research.preamble.categories.modules.framed.fraction_field_quotients',
                           'FractionFieldQuotient'),
 'FractionFieldQuotients': ('dzack_research.preamble.categories.modules.framed.fraction_field_quotients',
                            'FractionFieldQuotients'),
 'FramedFreeModules': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                       'FramedFreeModules'),
 'FreeModule': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                'FreeModule'),
 'FreeModuleOn': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                  'FreeModuleOn'),
 'FramedModules': ('dzack_research.preamble.categories.modules.pure.modules', 'FramedModules'),
 'GradedModules': ('dzack_research.preamble.categories.modules.graded_modules', 'GradedModules'),
 'Boundaries': ('dzack_research.preamble.categories.modules.cochain_complexes', 'Boundaries'),
 'CochainComplex': ('dzack_research.preamble.categories.modules.cochain_complexes',
                    'CochainComplex'),
 'CochainComplexElement': ('dzack_research.preamble.categories.modules.cochain_complexes',
                           'CochainComplexElement'),
 'CochainComplexObject': ('dzack_research.preamble.categories.modules.cochain_complexes',
                          'CochainComplexObject'),
 'CochainComplexes': ('dzack_research.preamble.categories.modules.cochain_complexes',
                      'CochainComplexes'),
 'CochainDifferential': ('dzack_research.preamble.categories.modules.cochain_complexes',
                         'CochainDifferential'),
 'CochainHomset': ('dzack_research.preamble.categories.modules.cochain_complexes', 'CochainHomset'),
 'CochainMorphism': ('dzack_research.preamble.categories.modules.cochain_complexes',
                     'CochainMorphism'),
 'Cohomology': ('dzack_research.preamble.categories.modules.cochain_complexes', 'Cohomology'),
 'CohomologyModules': ('dzack_research.preamble.categories.modules.cochain_complexes',
                       'CohomologyModules'),
 'Cycles': ('dzack_research.preamble.categories.modules.cochain_complexes', 'Cycles'),
 'Ext': ('dzack_research.preamble.categories.modules.derived_functors', 'Ext'),
 'Tor': ('dzack_research.preamble.categories.modules.derived_functors', 'Tor'),
 'cochain_homset': ('dzack_research.preamble.categories.modules.cochain_complexes',
                    'cochain_homset'),
 'DifferentialGradedModules': ('dzack_research.preamble.categories.modules.dg_modules',
                               'DifferentialGradedModules'),
 'GradedAlgebraModules': ('dzack_research.preamble.categories.modules.dg_modules',
                          'GradedAlgebraModules'),
 'regular_dg_module': ('dzack_research.preamble.categories.modules.dg_modules',
                       'regular_dg_module'),
 'Connection': ('dzack_research.preamble.categories.modules.connections', 'Connection'),
 'ConnectionDeRhamDifferential': ('dzack_research.preamble.categories.modules.connections',
                                  'ConnectionDeRhamDifferential'),
 'ConnectionDeRhamModule': ('dzack_research.preamble.categories.modules.connections',
                            'ConnectionDeRhamModule'),
 'ConnectionHomset': ('dzack_research.preamble.categories.modules.connections', 'ConnectionHomset'),
 'ConnectionMorphism': ('dzack_research.preamble.categories.modules.connections',
                        'ConnectionMorphism'),
 'ConnectionSpace': ('dzack_research.preamble.categories.modules.connections', 'ConnectionSpace'),
 'Connections': ('dzack_research.preamble.categories.modules.connections', 'Connections'),
 'ModuleWithConnection': ('dzack_research.preamble.categories.modules.connections',
                          'ModuleWithConnection'),
 'ModulesWithFlatConnection': ('dzack_research.preamble.categories.modules.connections',
                               'ModulesWithFlatConnection'),
 'ModulesWithConnection': ('dzack_research.preamble.categories.modules.connections',
                           'ModulesWithConnection'),
 'connection_homset': ('dzack_research.preamble.categories.modules.connections',
                       'connection_homset'),
 'GroupModuleHomset': ('dzack_research.preamble.categories.modules.group_modules',
                       'GroupModuleHomset'),
 'GroupModuleMorphism': ('dzack_research.preamble.categories.modules.group_modules',
                         'GroupModuleMorphism'),
 'InternalHom': ('dzack_research.preamble.categories.modules.internal_hom', 'InternalHom'),
 'internal_hom_morphism': ('dzack_research.preamble.categories.modules.internal_hom',
                           'internal_hom_morphism'),
 'GeneralModule': ('dzack_research.preamble.categories.modules.general_modules', 'GeneralModule'),
 'GeneralModuleElement': ('dzack_research.preamble.categories.modules.general_modules',
                          'GeneralModuleElement'),
 'GeneralModuleParent': ('dzack_research.preamble.categories.modules.general_modules',
                         'GeneralModuleParent'),
 'module_from_action': ('dzack_research.preamble.categories.modules.general_modules',
                        'module_from_action'),
 'LocalizedModule': ('dzack_research.preamble.categories.modules.localizations',
                     'LocalizedModule'),
 'LocalizedModules': ('dzack_research.preamble.categories.modules.localizations',
                      'LocalizedModules'),
 'AlgebraicCorrelationMorphism': ('dzack_research.preamble.categories.modules.hodge',
                                  'AlgebraicCorrelationMorphism'),
 'CorrelationIsomorphism': ('dzack_research.preamble.categories.modules.hodge',
                            'CorrelationIsomorphism'),
 'DeterminantLine': ('dzack_research.preamble.categories.modules.hodge', 'DeterminantLine'),
 'ExteriorForms': ('dzack_research.preamble.categories.modules.hodge', 'ExteriorForms'),
 'FramingVolumeTrivialization': ('dzack_research.preamble.categories.modules.hodge',
                                 'FramingVolumeTrivialization'),
 'HodgeDiscriminant': ('dzack_research.preamble.categories.modules.hodge', 'HodgeDiscriminant'),
 'HodgeStar': ('dzack_research.preamble.categories.modules.hodge', 'HodgeStar'),
 'HodgeStarOverFractionField': ('dzack_research.preamble.categories.modules.hodge',
                                'HodgeStarOverFractionField'),
 'MultivectorHodgeStar': ('dzack_research.preamble.categories.modules.hodge',
                          'MultivectorHodgeStar'),
 'PoincareDuality': ('dzack_research.preamble.categories.modules.hodge', 'PoincareDuality'),
 'VolumeTrivialization': ('dzack_research.preamble.categories.modules.hodge',
                          'VolumeTrivialization'),
 'algebraic_correlation_morphism': ('dzack_research.preamble.categories.modules.hodge',
                                    'algebraic_correlation_morphism'),
 'correlation_isomorphism': ('dzack_research.preamble.categories.modules.hodge',
                             'correlation_isomorphism'),
 'determinant_line': ('dzack_research.preamble.categories.modules.hodge', 'determinant_line'),
 'exterior_forms': ('dzack_research.preamble.categories.modules.hodge', 'exterior_forms'),
 'framing_volume_trivialization': ('dzack_research.preamble.categories.modules.hodge',
                                   'framing_volume_trivialization'),
 'hodge_discriminant': ('dzack_research.preamble.categories.modules.hodge', 'hodge_discriminant'),
 'hodge_star': ('dzack_research.preamble.categories.modules.hodge', 'hodge_star'),
 'hodge_star_over_fraction_field': ('dzack_research.preamble.categories.modules.hodge',
                                    'hodge_star_over_fraction_field'),
 'multivector_hodge_star': ('dzack_research.preamble.categories.modules.hodge',
                            'multivector_hodge_star'),
 'poincare_duality': ('dzack_research.preamble.categories.modules.hodge', 'poincare_duality'),
 'volume_trivialization': ('dzack_research.preamble.categories.modules.hodge',
                           'volume_trivialization'),
 'FramingMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                     'FramingMorphism'),
 'ModuleEmbedding': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                     'ModuleEmbedding'),
 'ModuleHomset': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                  'ModuleHomset'),
 'SubFramingMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                        'SubFramingMorphism'),
 'sub_framing_morphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                          'sub_framing_morphism'),
 'ModuleMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                    'ModuleMorphism'),
 'framing_morphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                      'framing_morphism'),
 'module_embedding': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                      'module_embedding'),
 'module_homset': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                   'module_homset'),
 'AlternatingPower': ('dzack_research.preamble.categories.modules.powers', 'AlternatingPower'),
 'AlternatingPowerModules': ('dzack_research.preamble.categories.modules.powers',
                             'AlternatingPowerModules'),
 'DividedSquare': ('dzack_research.preamble.categories.modules.powers', 'DividedSquare'),
 'DividedSquareModules': ('dzack_research.preamble.categories.modules.powers',
                          'DividedSquareModules'),
 'DividedPower': ('dzack_research.preamble.categories.modules.powers', 'DividedPower'),
 'DividedPowerModules': ('dzack_research.preamble.categories.modules.powers',
                         'DividedPowerModules'),
 'QuadraticSquare': ('dzack_research.preamble.categories.modules.powers', 'QuadraticSquare'),
 'SymmetricPower': ('dzack_research.preamble.categories.modules.powers', 'SymmetricPower'),
 'SymmetricPowerModules': ('dzack_research.preamble.categories.modules.powers',
                           'SymmetricPowerModules'),
 'TensorPower': ('dzack_research.preamble.categories.modules.powers', 'TensorPower'),
 'TensorPowerModules': ('dzack_research.preamble.categories.modules.powers', 'TensorPowerModules'),
 'alternating_power_morphism': ('dzack_research.preamble.categories.modules.powers',
                                'alternating_power_morphism'),
 'divided_power_element': ('dzack_research.preamble.categories.modules.powers',
                           'divided_power_element'),
 'divided_power_invariant_inclusion': ('dzack_research.preamble.categories.modules.powers',
                                       'divided_power_invariant_inclusion'),
 'divided_power_morphism': ('dzack_research.preamble.categories.modules.powers',
                            'divided_power_morphism'),
 'divided_power_product': ('dzack_research.preamble.categories.modules.powers',
                           'divided_power_product'),
 'divided_square_morphism': ('dzack_research.preamble.categories.modules.powers',
                             'divided_square_morphism'),
 'divided_square_invariant_inclusion': ('dzack_research.preamble.categories.modules.powers',
                                        'divided_square_invariant_inclusion'),
 'symmetric_power_morphism': ('dzack_research.preamble.categories.modules.powers',
                              'symmetric_power_morphism'),
 'tensor_power_permutation': ('dzack_research.preamble.categories.modules.powers',
                              'tensor_power_permutation'),
 'tensor_power_polarization': ('dzack_research.preamble.categories.modules.powers',
                               'tensor_power_polarization'),
 'tensor_square_polarization': ('dzack_research.preamble.categories.modules.powers',
                                'tensor_square_polarization'),
 'FinitelyGeneratedModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'FinitelyGeneratedModules'),
 'FreeModules': ('dzack_research.preamble.categories.modules.pure.modules', 'FreeModules'),
 'FinitelyPresentedModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'FinitelyPresentedModules'),
 'FreeResolution': ('dzack_research.preamble.categories.modules.pure.modules', 'FreeResolution'),
 'InternalHomModules': ('dzack_research.preamble.categories.modules.pure.modules',
                        'InternalHomModules'),
 'LinearHomModules': ('dzack_research.preamble.categories.modules.pure.modules',
                      'LinearHomModules'),
 'Modules': ('dzack_research.preamble.categories.modules.pure.modules', 'Modules'),
 'VectorSpaces': ('dzack_research.preamble.categories.modules.pure.modules', 'VectorSpaces'),
 'free_resolution': ('dzack_research.preamble.categories.modules.pure.modules', 'free_resolution'),
 'ProjectiveModules': ('dzack_research.preamble.categories.modules.pure.modules',
                       'ProjectiveModules'),
 'TorsionModules': ('dzack_research.preamble.categories.modules.pure.torsion_modules',
                    'TorsionModules'),
 'RestrictedScalarsModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'RestrictedScalarsModules'),
 'RestrictedScalarsModuleView': ('dzack_research.preamble.categories.modules.pure.modules',
                                 'RestrictedScalarsModuleView'),
 'restrict_scalars': ('dzack_research.preamble.categories.modules.pure.modules',
                      'restrict_scalars'),
 'twist_scalar_action': ('dzack_research.preamble.categories.modules.pure.modules',
                         'twist_scalar_action'),
 'ModuleSubobjects': ('dzack_research.preamble.categories.modules.pure.modules',
                      'ModuleSubobjects'),
 'BilinearMap': ('dzack_research.preamble.categories.modules.pure.modules', 'BilinearMap'),
 'TensorProductModules': ('dzack_research.preamble.categories.modules.pure.modules',
                          'TensorProductModules'),
 'tensor_product_morphism': ('dzack_research.preamble.categories.modules.tensor_products',
                             'tensor_product_morphism')}

__all__ = ['BasedFreeModule',
 'BilinearForm',
 'BilinearMap',
 'Biproduct',
 'BiproductModules',
 'FinitelyGeneratedFreeModules',
 'FinitelyGeneratedModules',
 'FreeResolution',
 'FinitelyPresentedModule',
 'FinitelyPresentedModules',
 'FinitelyPresentedTorsionModules',
 'FinitelyPresentedBilinearFormModules',
 'FinitelyPresentedFormModules',
 'FinitelyPresentedQuadraticFormModules',
 'FractionFieldQuotient',
 'FractionFieldQuotients',
 'FractionalIdeal',
 'FractionalIdeals',
 'FramedFreeModules',
 'FramedModules',
 'FormModule',
 'FormEmbedding',
 'FormedModuleHomset',
 'FormedModuleMorphism',
 'FiberedFormedModuleHomset',
 'FiberedFormedModuleMorphism',
 'FormModules',
 'FormedModules',
 'PairedModules',
 'QuadraticForm',
 'BilinearFormModules',
 'DiscriminantBilinearModules',
 'DiscriminantModule',
 'DiscriminantModules',
 'DiscriminantQuadraticModules',
 'QuadraticFormModules',
 'RestrictedScalarsModuleView',
 'RestrictedScalarsModules',
 'SymmetricBilinearFormModules',
 'FreeFormModules',
 'FinitelyGeneratedFormModules',
 'FinitelyGeneratedFreeFormModules',
 'FramingMorphism',
 'FreeModule',
 'FreeModuleOn',
 'FreeModules',
 'GradedModules',
 'GeneralModule',
 'GeneralModuleElement',
 'GeneralModuleParent',
 'GradedAlgebraModules',
 'DifferentialGradedModules',
 'regular_dg_module',
 'CochainComplexes',
 'Boundaries',
 'CochainComplex',
 'CochainComplexElement',
 'CochainComplexObject',
 'CochainDifferential',
 'CochainHomset',
 'CochainMorphism',
 'Cohomology',
 'CohomologyModules',
 'Connection',
 'ConnectionDeRhamDifferential',
 'ConnectionDeRhamModule',
 'ConnectionHomset',
 'ConnectionMorphism',
 'ConnectionSpace',
 'Connections',
 'Cycles',
 'Ext',
 'Tor',
 'cochain_homset',
 'connection_homset',
 'GroupModuleHomset',
 'GroupModuleMorphism',
 'Ideal',
 'Ideals',
 'InternalHom',
 'InternalHomModules',
 'LinearHomModules',
 'LocalizedModules',
 'LocalizedModule',
 'ModuleHomset',
 'ModuleEmbedding',
 'ModuleMorphism',
 'ModuleWithConnection',
 'ModulesWithFlatConnection',
 'ModulesWithConnection',
 'ModulesWithChosenFinitePresentation',
 'ModuleSubobjects',
 'Subobjects',
 'Modules',
 'ProjectiveModules',
 'TorsionModules',
 'TorsionModule',
 'TorsionBilinearFormModules',
 'TorsionFormIsometry',
 'TorsionQuadraticFormModules',
 'TensorProduct',
 'TensorProductModules',
 'TensorSquare',
 'DividedSquare',
 'DividedSquareModules',
 'QuadraticSquare',
 'VectorSpaces',
 'SubFramingMorphism',
 'biproduct_morphism',
 'framing_morphism',
 'free_resolution',
 'sub_framing_morphism',
 'formed_module_homset',
 'form_embedding',
 'fibered_formed_module_homset',
 'internal_hom_morphism',
 'divided_square_morphism',
 'module_embedding',
 'module_homset',
 'module_from_action',
 'ring_as_module',
 'restrict_scalars',
 'tensor_product_morphism',
 'twist_scalar_action',
 'AlternatingPower',
 'AlternatingPowerModules',
 'DividedPower',
 'DividedPowerModules',
 'SymmetricPower',
 'SymmetricPowerModules',
 'TensorPower',
 'TensorPowerModules',
 'alternating_power_morphism',
 'divided_power_element',
 'divided_power_invariant_inclusion',
 'divided_power_morphism',
 'divided_power_product',
 'divided_square_invariant_inclusion',
 'symmetric_power_morphism',
 'tensor_power_permutation',
 'tensor_power_polarization',
 'tensor_square_polarization',
 'AlgebraicCorrelationMorphism',
 'CorrelationIsomorphism',
 'DeterminantLine',
 'ExteriorForms',
 'FramingVolumeTrivialization',
 'HodgeDiscriminant',
 'HodgeStar',
 'HodgeStarOverFractionField',
 'MultivectorHodgeStar',
 'PoincareDuality',
 'VolumeTrivialization',
 'algebraic_correlation_morphism',
 'correlation_isomorphism',
 'determinant_line',
 'exterior_forms',
 'framing_volume_trivialization',
 'hodge_discriminant',
 'hodge_star',
 'hodge_star_over_fraction_field',
 'multivector_hodge_star',
 'poincare_duality',
 'volume_trivialization']

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
