'Owned module hierarchy.'

from importlib import import_module as _import_module

_EXPORTS = {'BiproductModules': ('dzack_research.preamble.categories.modules.pure.modules',
                      'BiproductModules'),
 'FractionalIdeals': ('dzack_research.preamble.categories.modules.fractional_ideals',
                      'FractionalIdeals'),
 'FunctionModules': ('dzack_research.preamble.categories.modules.pure.function_modules',
                     'FunctionModules'),
 'FinitelyGeneratedFreeModules': ('dzack_research.preamble.categories.modules.pure.modules',
                                  'FinitelyGeneratedFreeModules'),
 'ModulesWithChosenFinitePresentation': ('dzack_research.preamble.categories.modules.pure.modules',
                                         'ModulesWithChosenFinitePresentation'),
 'FinitelyPresentedTorsionModules': ('dzack_research.preamble.categories.modules.pure.modules',
                                     'FinitelyPresentedTorsionModules'),
 'BilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                         'BilinearFormModules'),
 'DiscriminantBilinearModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'DiscriminantBilinearModules'),
 'DiscriminantModules': ('dzack_research.preamble.categories.modules.framed.formed',
                         'DiscriminantModules'),
 'DiscriminantQuadraticModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'DiscriminantQuadraticModules'),
 'FiberedFormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed',
                               'FiberedFormedModuleHomset'),
 'FiberedFormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'FiberedFormedModuleMorphism'),
 'FormedModuleHomset': ('dzack_research.preamble.categories.modules.framed.formed',
                        'FormedModuleHomset'),
 'FormedModuleMorphism': ('dzack_research.preamble.categories.modules.framed.formed',
                          'FormedModuleMorphism'),
 'FormEmbedding': ('dzack_research.preamble.categories.modules.framed.formed', 'FormEmbedding'),
 'FormModules': ('dzack_research.preamble.categories.modules.framed.formed', 'FormModules'),
 'FreeFormModules': ('dzack_research.preamble.categories.modules.framed.formed', 'FreeFormModules'),
 'PairedModules': ('dzack_research.preamble.categories.modules.framed.formed', 'PairedModules'),
 'QuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                          'QuadraticFormModules'),
 'SymmetricBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                  'SymmetricBilinearFormModules'),
 'TorsionBilinearFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                'TorsionBilinearFormModules'),
 'TorsionFormIsometry': ('dzack_research.preamble.categories.modules.framed.formed',
                         'TorsionFormIsometry'),
 'TorsionQuadraticFormModules': ('dzack_research.preamble.categories.modules.framed.formed',
                                 'TorsionQuadraticFormModules'),
 'FractionFieldQuotients': ('dzack_research.preamble.categories.modules.framed.fraction_field_quotients',
                            'FractionFieldQuotients'),
 'FramedFreeModules': ('dzack_research.preamble.categories.modules.framed.framed_free_modules',
                       'FramedFreeModules'),
 'FramedModules': ('dzack_research.preamble.categories.modules.pure.modules', 'FramedModules'),
 'GradedModules': ('dzack_research.preamble.categories.modules.graded_modules', 'GradedModules'),
 'CochainComplexElement': ('dzack_research.preamble.categories.modules.cochain_complexes',
                           'CochainComplexElement'),
 'CochainComplexObject': ('dzack_research.preamble.categories.modules.cochain_complexes',
                          'CochainComplexObject'),
 'CochainComplexes': ('dzack_research.preamble.categories.modules.cochain_complexes',
                      'CochainComplexes'),
 'CochainDifferential': ('dzack_research.preamble.categories.modules.cochain_complexes',
                         'CochainDifferential'),
 'CochainHomset': ('dzack_research.preamble.categories.modules.cochain_complexes', 'CochainHomset'),
 'CochainMorphism': ('dzack_research.preamble.categories.modules.cochain_complexes',
                     'CochainMorphism'),
 'CohomologyModules': ('dzack_research.preamble.categories.modules.cochain_complexes',
                       'CohomologyModules'),
 'DifferentialGradedAlgebraParameters': ('dzack_research.preamble.categories.modules.dg_modules',
                                         'DifferentialGradedAlgebraParameters'),
 'DifferentialGradedModules': ('dzack_research.preamble.categories.modules.dg_modules',
                               'DifferentialGradedModules'),
 'GradedAlgebraParameters': ('dzack_research.preamble.categories.modules.dg_modules',
                             'GradedAlgebraParameters'),
 'GradedAlgebraModules': ('dzack_research.preamble.categories.modules.dg_modules',
                          'GradedAlgebraModules'),
 'Connection': ('dzack_research.preamble.categories.modules.connections', 'Connection'),
 'CommutativeAlgebraParameters': ('dzack_research.preamble.categories.modules.connections',
                                  'CommutativeAlgebraParameters'),
 'ConnectionDeRhamDifferential': ('dzack_research.preamble.categories.modules.connections',
                                  'ConnectionDeRhamDifferential'),
 'ConnectionDeRhamModule': ('dzack_research.preamble.categories.modules.connections',
                            'ConnectionDeRhamModule'),
 'ConnectionHomset': ('dzack_research.preamble.categories.modules.connections', 'ConnectionHomset'),
 'ConnectionMorphism': ('dzack_research.preamble.categories.modules.connections',
                        'ConnectionMorphism'),
 'ConnectionSpace': ('dzack_research.preamble.categories.modules.connections', 'ConnectionSpace'),
 'ModulesWithFlatConnection': ('dzack_research.preamble.categories.modules.connections',
                               'ModulesWithFlatConnection'),
 'ModulesWithConnection': ('dzack_research.preamble.categories.modules.connections',
                           'ModulesWithConnection'),
 'GroupModuleHomset': ('dzack_research.preamble.categories.modules.group_modules',
                       'GroupModuleHomset'),
 'GroupModuleMorphism': ('dzack_research.preamble.categories.modules.group_modules',
                         'GroupModuleMorphism'),
 'GeneralModules': ('dzack_research.preamble.categories.modules.general_modules',
                    'GeneralModules'),
 'LocalizedModules': ('dzack_research.preamble.categories.modules.localizations',
                      'LocalizedModules'),
 'FramingMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                     'FramingMorphism'),
 'ModuleEmbedding': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                     'ModuleEmbedding'),
 'ModuleHomset': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                  'ModuleHomset'),
 'SubFramingMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                        'SubFramingMorphism'),
 'ModuleMorphism': ('dzack_research.preamble.categories.modules.module_morphisms.module_morphisms',
                    'ModuleMorphism'),
 'AlternatingPowerModules': ('dzack_research.preamble.categories.modules.powers',
                             'AlternatingPowerModules'),
 'DividedSquareModules': ('dzack_research.preamble.categories.modules.powers',
                          'DividedSquareModules'),
 'DividedPowerModules': ('dzack_research.preamble.categories.modules.powers',
                         'DividedPowerModules'),
 'SymmetricPowerModules': ('dzack_research.preamble.categories.modules.powers',
                           'SymmetricPowerModules'),
 'TensorPowerModules': ('dzack_research.preamble.categories.modules.powers', 'TensorPowerModules'),
 'FinitelyGeneratedModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'FinitelyGeneratedModules'),
 'FreeModules': ('dzack_research.preamble.categories.modules.pure.modules', 'FreeModules'),
 'FinitelyPresentedModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'FinitelyPresentedModules'),
 'FreeResolution': ('dzack_research.preamble.categories.modules.pure.modules', 'FreeResolution'),
 'InternalHomModules': ('dzack_research.preamble.categories.modules.pure.modules',
                        'InternalHomModules'),
 'LinearHomModules': ('dzack_research.preamble.categories.modules.pure.modules',
                      'LinearHomModules'),
 'Modules': ('dzack_research.preamble.categories.modules.pure.modules', 'Modules'),
 'VectorSpaces': ('dzack_research.preamble.categories.modules.pure.modules', 'VectorSpaces'),
 'ProjectiveModules': ('dzack_research.preamble.categories.modules.pure.modules',
                       'ProjectiveModules'),
 'TorsionModules': ('dzack_research.preamble.categories.modules.pure.modules',
                    'TorsionModules'),
 'RestrictedScalarsModules': ('dzack_research.preamble.categories.modules.pure.modules',
                              'RestrictedScalarsModules'),
 'RestrictedScalarsModuleView': ('dzack_research.preamble.categories.modules.pure.modules',
                                 'RestrictedScalarsModuleView'),
 'ModuleSubobjects': ('dzack_research.preamble.categories.modules.pure.modules',
                      'ModuleSubobjects'),
 'BilinearMap': ('dzack_research.preamble.categories.modules.pure.modules', 'BilinearMap'),
 'TensorProductModules': ('dzack_research.preamble.categories.modules.pure.modules',
                          'TensorProductModules'),
}

__all__ = ['BilinearMap',
 'BiproductModules',
 'FinitelyGeneratedFreeModules',
 'FinitelyGeneratedModules',
 'FreeResolution',
 'FinitelyPresentedModules',
 'FinitelyPresentedTorsionModules',
 'FractionFieldQuotients',
 'FractionalIdeals',
 'FunctionModules',
 'FramedFreeModules',
 'FramedModules',
 'FormEmbedding',
 'FormedModuleHomset',
 'FormedModuleMorphism',
 'FiberedFormedModuleHomset',
 'FiberedFormedModuleMorphism',
 'FormModules',
 'PairedModules',
 'BilinearFormModules',
 'DiscriminantBilinearModules',
 'DiscriminantModules',
 'DiscriminantQuadraticModules',
 'QuadraticFormModules',
 'RestrictedScalarsModuleView',
 'RestrictedScalarsModules',
 'SymmetricBilinearFormModules',
 'FreeFormModules',
 'FramingMorphism',
 'FreeModules',
 'GradedModules',
 'GeneralModules',
 'GradedAlgebraParameters',
 'GradedAlgebraModules',
 'DifferentialGradedAlgebraParameters',
 'DifferentialGradedModules',
 'CochainComplexes',
 'CochainComplexElement',
 'CochainComplexObject',
 'CochainDifferential',
 'CochainHomset',
 'CochainMorphism',
 'CohomologyModules',
 'Connection',
 'CommutativeAlgebraParameters',
 'ConnectionDeRhamDifferential',
 'ConnectionDeRhamModule',
 'ConnectionHomset',
 'ConnectionMorphism',
 'ConnectionSpace',
 'GroupModuleHomset',
 'GroupModuleMorphism',
 'InternalHomModules',
 'LinearHomModules',
 'LocalizedModules',
 'ModuleHomset',
 'ModuleEmbedding',
 'ModuleMorphism',
 'ModulesWithFlatConnection',
 'ModulesWithConnection',
 'ModulesWithChosenFinitePresentation',
 'ModuleSubobjects',
 'Modules',
 'ProjectiveModules',
 'TorsionModules',
 'TorsionBilinearFormModules',
 'TorsionFormIsometry',
 'TorsionQuadraticFormModules',
 'TensorProductModules',
 'DividedSquareModules',
 'VectorSpaces',
 'SubFramingMorphism',
 'AlternatingPowerModules',
 'DividedPowerModules',
 'SymmetricPowerModules',
 'TensorPowerModules',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value

def __dir__():
    return sorted((*globals(), *__all__))
