r"""$K/\mathfrak a$: the fraction field modulo a fractional ideal.

An object of this category is $\operatorname{coker}(\iota)$ for
$\iota:\mathfrak a\hookrightarrow K$ the inclusion of a fractional ideal into
$K=\operatorname{Frac}(R)$, taken in $R\text{-Mod}$.  That is the whole
definition, and it is what everything below is read off: a map out of
$K/\mathfrak a$ is a map out of $K$ that kills $\mathfrak a$, an element is a
class $x+\mathfrak a$ with $x\in K$, and a submodule is the image of a
submodule of $K$ containing $\mathfrak a$.

$\mathfrak a=(0)$ is admitted and is not a degenerate case: its cokernel is
$K$ itself, so $K$ as an $R$-module is the modulus-zero object here and needs
no separate construction.  It is the one object that is not torsion, which is
why torsion is claimed per object rather than by the category.

Sage names $\mathbb Q/n\mathbb Z$ for $R=\mathbb Z$; the fractional ideal is
$n\mathbb Z$ and the modulus is the $n$ that generates it.  These are the
value modules of the discriminant forms -- $b$ takes values in
$\mathbb Q/\mathbb Z$ and $q$ in $\mathbb Q/2\mathbb Z$ -- so the scale of a
discriminant form is a submodule of an object of this category, and this is
where such a submodule is presented.

The framing is countable and it is chosen.  $K$ is not a free $R$-module and
its canonical framing -- the counit $F_R(U(K))\twoheadrightarrow K$ of the
free-forgetful adjunction -- is indexed by the whole underlying set, which is
useless to compute with.  A divisibility-cofinal chain $d_0\mid d_1\mid\cdots$
does better: $e_n\mapsto 1/d_n$ is again surjective, because $a/b$ is the
integral multiple $a(d_n/b)$ of $1/d_n$ as soon as $b\mid d_n$, and the
indexing set is now $\mathbb N$.  Over $\mathbb Z$ the chain is $d_n=n!$.
The framing of $K/\mathfrak a$ is that framing followed by the projection
$K\twoheadrightarrow K/\mathfrak a$, and a composite of surjections is one, so
the induced generators are the classes $[1/d_n]$.

The submodules are cyclic, and that is a theorem about $R$ rather than about
$K/\mathfrak a$: over a principal ideal domain the $R$-submodule of $K$
generated by finitely many fractions and by $\mathfrak a$ is $(g)$ for $g$ a
greatest common divisor of them all, so its image is
$(g)/(n)\cong R/(n/g)$.  Outside that class of rings the classification is
false as stated -- a non-principal ideal is already a counterexample with no
element generating it -- so the ring is asked, and refuses.
"""

from sage.rings.integer_ring import ZZ as SageZZ
from typing import Protocol, Self, TYPE_CHECKING

from sage.arith.functions import lcm
from sage.arith.misc import gcd
from sage.categories.category import Category
from sage.categories.principal_ideal_domains import PrincipalIdealDomains
from sage.groups.additive_abelian.qmodnz import QmodnZ
from sage.matrix.constructor import matrix

from dzack_research.preamble.categories.modules.pure.torsion_modules import TorsionModules
from dzack_research.preamble.categories.rings.rings import OwnedCategoryOverBaseRing
from dzack_research.preamble.categories.rings.rings import engine_ring
from dzack_research.preamble.categories.rings.rings import owned_ring_view

if TYPE_CHECKING:
    from sage.categories.morphism import Morphism
    from dzack_research.preamble.lexicon import Element
    from dzack_research.preamble.lexicon import Module
    from dzack_research.preamble.lexicon import OrderedSet
    from dzack_research.preamble.lexicon import Ring
    from dzack_research.preamble.categories.modules.framed.formed.integrallattice.subobjects import Subobject
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import FramingMorphism


if TYPE_CHECKING:
    class FractionFieldQuotientParent(Protocol):
        r"""What a parent placed in ``FractionFieldQuotients(R)`` supplies."""

        # Installed on the object by the constructor: the generator $n$ of
        # the ideal quotiented out.
        _fraction_field_modulus: "Element"

        def base(self) -> "Ring": ...
        def base_ring(self) -> "Ring": ...
        def coerce_map_from(self, source: "Ring") -> "Morphism": ...
        def fraction_field(self) -> "Ring": ...
        def modulus(self) -> "Element": ...
        def divisibility_chain(self, index: "Element") -> "Element": ...
        def projection_from_fraction_field(self) -> "Morphism": ...
        def _chain_class(self, index: "Element") -> "Element": ...
        def lift(self, element: "Element") -> "Element": ...
        def subobject_on(self, module_generators: "OrderedSet") -> "Subobject": ...
        def __call__(self, x: object = ..., *args: object, **kwds: object) -> "Element": ...


class FractionFieldQuotients(OwnedCategoryOverBaseRing):
    r"""Cokernels of a fractional ideal in the fraction field of $R$."""

    @staticmethod
    def __classcall_private__(
        cls: type["FractionFieldQuotients"], base_ring: "Ring | None" = None
    ) -> "FractionFieldQuotients":
        category: "FractionFieldQuotients" = super().__classcall__(
            cls, SageZZ if base_ring is None else engine_ring(base_ring)
        )
        return category

    @classmethod
    def _repr_object_names(cls) -> str:
        return "fraction field quotients"

    def super_categories(self) -> list:
        # Framed, by the chain framing every object here declares.  Torsion is
        # *not* claimed: it holds for every proper quotient and fails for
        # $K$ itself, so the objects that have it are refined into it one by
        # one at intake rather than inheriting it from a category that would
        # be lying about one of its members.
        # The axiom category named directly: ``FramedModules(R)`` is
        # ``Modules(R).Framed()`` by unique representation, and naming the
        # class both registers the axiom and says which category is meant.
        from dzack_research.preamble.categories.modules.framed.framed_modules import FramedModules

        return [FramedModules(self.base_ring())]

    class ParentMethods:
        def base_ring(self: "FractionFieldQuotientParent") -> "Ring":
            r"""Return $R$, under the name a session names it by.

            Sage's $\mathbb Q/n\mathbb Z$ answers with the engine's
            $\mathbb Z$, which is the same ring under the other name.  The
            modules that map into this one are built over the owned view, and
            a homset compares the two base rings, so the object says which
            ring it is over in the words the rest of the preamble uses.
            """
            return owned_ring_view(self.base())

        def fraction_field(self: "FractionFieldQuotientParent") -> "Ring":
            r"""Return $K$, the field this is a quotient of."""
            return self.base_ring().fraction_field()

        def modulus(self: "FractionFieldQuotientParent") -> "Element":
            r"""Return the $n\in K$ generating the ideal quotiented out.

            A generator and not the ideal: this category's objects are
            classified over a principal ideal domain, where $\mathfrak a=(n)$,
            and the arithmetic below divides by $n$.
            """
            return self._fraction_field_modulus

        def lift(self: "FractionFieldQuotientParent", element: "Element") -> "Element":
            r"""Return a representative in $K$ of the class ``element``.

            The quotient map $K\to K/\mathfrak a$ has no section as a module
            map, so this is a choice of representative and nothing more --
            Sage's quotient-element protocol, which every quotient's elements
            answer.  What is well defined about it is what is used: the ideal
            the lifts generate together with $\mathfrak a$.
            """
            assert element.parent() is self, (
                f"{element} is not an element of {self}"
            )
            return self.fraction_field()(element.lift())

        def divisibility_chain(self: "FractionFieldQuotientParent", index: "Element") -> "Element":
            r"""Return $d_n\in R$, the $n$-th step of a divisibility-cofinal chain.

            Cofinal for divisibility means every nonzero $r\in R$ divides some
            $d_n$, and that is the only property the framing uses.  Over
            $\mathbb Z$ the factorials are such a chain, since $b\mid n!$ for
            every $n\ge b$; a general principal ideal domain has one exactly
            when it is countable, and which chain it is depends on the ring.
            So this answers for the integers and refuses elsewhere rather than
            inventing a chain for a ring it has not been told about.
            """
            assert engine_ring(self.base_ring()) is SageZZ, (
                f"the divisibility-cofinal chain implemented here is n! over "
                f"the integers, and this module is over {self.base_ring()}"
            )
            return SageZZ(index).factorial()

        def framing_morphism(self: "FractionFieldQuotientParent") -> "FramingMorphism":
            r"""Return the countable framing $F_R(\mathbb N)\twoheadrightarrow K/\mathfrak a$.

            $e_n\mapsto[1/d_n]$, which is the framing of $K$ followed by the
            projection: $\mathbb Q/0\mathbb Z$ is $K$ and gets the same
            method, and on a proper quotient the passage from the fraction
            $1/d_n$ to its class *is* the projection, which is why one
            statement frames both.

            Surjective because the chain is cofinal: $a/b\in K$ is
            $a(d_n/b)\cdot(1/d_n)$ for any $n$ with $b\mid d_n$, and a
            composite of surjections is a surjection.  Declared rather than
            searched for, as every framing in this preamble is.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.categories.modules.framed.framed_free_modules import FreeModuleOn
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import framing_morphism
            from dzack_research.preamble.categories.sets.sets import Sets

            labels = Sets.Δ[Sets.ℵ[0]]
            return framing_morphism(
                FreeModuleOn(self.base_ring(), labels),
                self,
                self._chain_class,
            )

        def projection_from_fraction_field(self: "FractionFieldQuotientParent") -> "Morphism":
            r"""Return $\pi:K\twoheadrightarrow K/\mathfrak a$, the map presenting this object.

            Sage's own declared coercion, asked for under the engine's name
            for $K$: a quotient parent already carries the map from what it is
            a quotient of, so there is nothing here to construct.  Asked for
            by name because the framing is stated through it.
            """
            projection: "Morphism" = self.coerce_map_from(
                engine_ring(self.fraction_field())
            )
            return projection

        def _chain_class(self: "FractionFieldQuotientParent", index: "Element") -> "Element":
            r"""Return $[1/d_n]=\pi(1/d_n)$, the framed generator at ``index``."""
            return self.projection_from_fraction_field()(
                ~self.fraction_field()(self.divisibility_chain(index))
            )

        def subobject_on(self: "FractionFieldQuotientParent", module_generators: "OrderedSet") -> "Subobject":
            r"""Return the submodule generated by finitely many classes.

            Cyclic, by the classification this category's docstring states:
            with $\mathfrak a=(n)$ and lifts $x_1,\dots,x_m$, the submodule of
            $K$ they generate together with $n$ is $(g)$ for
            $g=\gcd(x_1,\dots,x_m,n)$, and $(g)/(n)\cong R/(n/g)$ by
            $r\mapsto rg$.  So the source is the cyclic module of order
            $n/g$ and the inclusion sends its generator to the class of $g$.

            The subobject *is* that source carrying the inclusion, as
            everywhere else in the preamble: it is not a set of elements of
            this module, and its own module structure is the presented
            module's.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_torsion_modules import FinitelyPresentedTorsionModules
            from dzack_research.preamble.categories.modules.framed.formed.integrallattice.subobjects import Subobject
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import module_homset

            ring = self.base_ring()
            assert ring in PrincipalIdealDomains(), (
                f"{ring} is not a principal ideal domain, so a finitely "
                "generated submodule of K/a need not be cyclic and this "
                "construction does not describe it"
            )
            classes = tuple(module_generators)
            assert all(element.parent() is self for element in classes), (
                "a subobject is generated by elements of this module"
            )
            generator, order = _cyclic_presentation(
                engine_ring(ring),
                tuple(self.lift(element) for element in classes),
                self.modulus(),
            )
            source = FinitelyPresentedTorsionModules().from_relations(
                matrix(SageZZ, [[order]])
            )
            inclusion = module_homset(source, self)(
                {
                    label: self(generator)
                    for label in source.module_generating_set()
                }
            )
            return Subobject(inclusion)

        def submodule(self: "FractionFieldQuotientParent", module_generators: "OrderedSet") -> "Subobject":
            r"""Return the submodule generated by finitely many classes."""
            return self.subobject_on(module_generators)


def _cyclic_presentation(ring: "Ring", lifts: tuple, modulus: "Element") -> tuple:
    r"""Return $(g,k)$ with $(g)=\langle\text{lifts},n\rangle$ and $n=kg$.

    The greatest common divisor of finitely many elements of $K$ is taken
    over a common denominator: $\gcd(a_i/d)=\gcd(a_i)/d$, since scaling by
    $1/d$ is an isomorphism of $R$-modules $K\to K$ carrying the submodule
    generated by the $a_i$ onto the one generated by the $a_i/d$.
    """
    assert not modulus.is_zero(), (
        "a finitely generated submodule of K itself is (g), free of rank one "
        "over R, and not a cyclic torsion module; this construction describes "
        "the proper quotients only"
    )
    values = lifts + (modulus,)
    denominator = lcm([value.denominator() for value in values])
    generator = gcd([ring(value * denominator) for value in values]) / denominator
    order = modulus / generator
    assert order in ring, (
        f"{generator} does not divide the modulus {modulus}, so it does not "
        "generate a submodule containing the ideal"
    )
    return generator, ring(order)


def _record_modulus(quotient: "Module") -> None:
    r"""Carry Sage's $\mathbb Q/n\mathbb Z$ across as the ideal it quotients by.

    $\mathbb Q/n\mathbb Z$ is $\operatorname{coker}(n\mathbb Z\hookrightarrow
    \mathbb Q)$, so its ``n`` is a generator of the ideal.  Recorded before
    refinement, because the category reads it: the crossing from the engine's
    spelling to the category's happens once, here.
    """
    quotient._fraction_field_modulus = quotient.n


def _is_a_proper_quotient(quotient: "Module") -> bool:
    r"""Whether $\mathfrak a\ne 0$, which is when $K/\mathfrak a$ is torsion.

    Every class then has finite order: $x=a/b$ is killed by $bp$ when
    $\mathfrak a=(p/q)$, since $bp\cdot(a/b)=ap=(aq)(p/q)$.  For
    $\mathfrak a=0$ the module is $K$, which is torsion free, so the axiom is
    asked of the object instead of being inherited.
    """
    return not quotient.n.is_zero()


def _is_the_fraction_field(quotient: "Module") -> bool:
    r"""Whether $\mathfrak a=0$, so that the cokernel is $K$ itself."""
    return not _is_a_proper_quotient(quotient)


_FRACTION_FIELD_QUOTIENTS_INSTALLED = False


def install_fraction_field_quotients() -> None:
    r"""Refine every $\mathbb Q/n\mathbb Z$ Sage builds into this category.

    On the class, so that it does not matter who names the quotient: a
    session writing ``QQ/ZZ``, a discriminant form asking for its value
    module, and Sage's own constructor all reach one cached parent, and it is
    refined the moment it is built.

    Torsion joins on for the proper quotients only, in the same act: refining
    twice would rebuild the class from the second category alone and drop the
    first, so the object that is torsion is placed once, in the join it
    belongs to.
    """
    global _FRACTION_FIELD_QUOTIENTS_INSTALLED
    # Local: a module-level import would close a cycle; the module is built by the time this runs.
    from dzack_research.preamble.refine import hook_post_init

    if _FRACTION_FIELD_QUOTIENTS_INSTALLED:
        return
    hook_post_init(
        QmodnZ,
        FractionFieldQuotients(),
        before=_record_modulus,
        predicate=_is_the_fraction_field,
    )
    hook_post_init(
        QmodnZ,
        Category.join(
            [FractionFieldQuotients(), TorsionModules(FractionFieldQuotients().base_ring())]
        ),
        predicate=_is_a_proper_quotient,
    )
    _FRACTION_FIELD_QUOTIENTS_INSTALLED = True


install_fraction_field_quotients()
