r"""Tensor, symmetric, exterior, and divided powers of presented modules.

The constructions use one selected module presentation.  Tensor powers are
iterated instances of the canonical categorical tensor product.  The other
three are the degree pieces of the corresponding graded algebra: for
``M = F/K`` they are the free degree piece modulo the degree part of the ideal
(or divided-power ideal) generated by ``K``.
"""

from math import prod

from sage.categories.category import Category

from sage.arith.misc import binomial
from sage.categories.morphism import SetMorphism
from sage.misc.cachefunc import cached_function, cached_method

from dzack_research.preamble.categories.abstract_categories.products import (
    _finite_factor_family,
)
from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
    _presentation_from_relation_rows,
    _presentation_rows,
)
from dzack_research.preamble.categories.modules.framed.framed_free_modules import (
    FramedFreeModules,
)
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
    ModuleEmbedding,
    ModuleMor,
    ModuleMorphism,
)
from dzack_research.preamble.categories.modules.pure.modules import (
    FramedModules,
    Modules,
    ModulesWithChosenFinitePresentation,
    _module_tensor_product_with_data,
)
from dzack_research.preamble.categories.modules.tensor_products import (
    _flatten_tensor_label,
    _nested_tensor_label,
)
from dzack_research.preamble.categories.rings.ring_foundation import (
    OwnedCategoryOverBaseRing,
    OwnedRings,
    _owned_ring,
)
from dzack_research.preamble.categories.sets.coordinate_families import (
    _coordinate_family,
)
from dzack_research.preamble.categories.sets.coordinate_families import (
    _coordinate_family_from_function,
)
from dzack_research.preamble.categories.sets.coordinate_families import (
    _coordinate_pair,
)
from dzack_research.preamble.categories.sets.coordinate_families import (
    _finite_framing,
)
from dzack_research.preamble.categories.sets.finite_ordered_sets import (
    FiniteOrderedSets,
    finite_ordered_set,
)
from dzack_research.preamble.categories.sets.indexed_families import (
    IndexedFamily,
    indexed_family,
)
from dzack_research.preamble.categories.sets.set_categories import Sets
from dzack_research.preamble.tensors.tensor import tensor


class _PowerModuleInclusion(ModuleEmbedding):
    r"""The canonical inclusion of a homogeneous power piece into its graded algebra."""

    def __init__(self, parent, source, algebra, degree) -> None:
        self._power_source = source
        self._power_algebra = algebra
        self._power_degree = degree
        super().__init__(
            parent,
            lambda element: algebra.from_graded_piece(degree, source(element)),
            elementwise=True,
            lift=source._lift_from_ambient_power_algebra,
        )

    def _elementwise_linearity_derivation(self):
        return True

    def _injectivity_derivation(self):
        return True

    def _selected_lift_derivation(self):
        return True


class _PowerModuleParentMethods:
    def __init__(self, power_source, power_degree, **rest) -> None:
        self._power_source = power_source
        self._power_degree = int(power_degree)
        super().__init__(**rest)

    def power_source(self):
        return self._power_source

    def power_degree(self):
        return self._power_degree

    def _lift_from_ambient_power_algebra(self, element):
        r"""Read an ambient homogeneous element back in this power module."""
        algebra = self.ambient_power_algebra()
        if getattr(element, "parent", lambda: None)() is not algebra:
            raise TypeError("the element belongs to a different ambient algebra")
        degree = self.power_degree()
        component = algebra.homogeneous_component(element, degree)
        if algebra.from_graded_piece(degree, component) != element:
            raise ValueError("the ambient element has support outside this homogeneous degree")
        return self(component)

    def __contains__(self, element) -> bool:
        if getattr(element, "parent", lambda: None)() is self:
            return True
        if getattr(element, "parent", lambda: None)() is self.ambient_power_algebra():
            try:
                self._lift_from_ambient_power_algebra(element)
            except (TypeError, ValueError):
                return False
            return True
        return super().__contains__(element)

    @cached_method
    def inclusion(self):
        r"""Return the canonical homogeneous-piece inclusion into its power algebra."""
        algebra = self.ambient_power_algebra()
        degree = self.power_degree()
        inclusion = _PowerModuleInclusion(
            self.Mono(algebra),
            self,
            algebra,
            degree,
        )
        self.register_conversion(
            SetMorphism(
                Sets().Mor(algebra, self),
                inclusion.lift,
            )
        )
        return inclusion


class TensorPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "tensor powers of modules"

    def super_categories(self):

        return [Modules(self.base_ring())]

    class ParentMethods(_PowerModuleParentMethods):
        @cached_method
        def ambient_power_algebra(self):
            return self.power_source().tensor_algebra()


class SymmetricPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "symmetric powers of modules"

    def super_categories(self):

        return [Modules(self.base_ring())]

    class ParentMethods(_PowerModuleParentMethods):
        @cached_method
        def ambient_power_algebra(self):
            return self.power_source().symmetric_algebra()


class AlternatingPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "exterior powers of modules"

    def super_categories(self):

        return [Modules(self.base_ring())]

    class ParentMethods(_PowerModuleParentMethods):
        @cached_method
        def ambient_power_algebra(self):
            return self.power_source().exterior_algebra()


class DividedPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "divided powers of modules"

    def super_categories(self):

        return [Modules(self.base_ring())]

    class ParentMethods(_PowerModuleParentMethods):
        @cached_method
        def ambient_power_algebra(self):
            return self.power_source().divided_power_algebra()


class QuadraticModuleMorphism(ModuleMorphism):
    r"""A classifier ``Gamma^2(M) -> W``, read as the quadratic map ``M -> W``."""

    def __init__(self, parent, images, *, lift_coordinate_values=None) -> None:
        self._lift_coordinate_values = lift_coordinate_values
        super().__init__(parent, images)

    def module(self):
        return self.domain().divided_square_source()

    def __call__(self, element):
        parent = getattr(element, "parent", lambda: None)()
        if parent is self.domain():
            return self._call_(element)
        module = self.module()
        if parent is not module:
            element = module(element)
        return self._call_(self.domain().quadratic(element))

    def classifying_morphism(self):
        return self

    def has_selected_bilinear_lift(self) -> bool:
        r"""Whether this quadratic classifier retains chosen bilinear coordinates."""
        return self._lift_coordinate_values is not None

    def lift_coordinate_values(self):
        values = self._lift_coordinate_values
        if not self.has_selected_bilinear_lift():
            raise TypeError(
                "this quadratic map has no selected bilinear coordinate presentation"
            )
        return values

    def _gram_entry(self, left_label, right_label):
        return _coordinate_pair(
            self.lift_coordinate_values(), left_label, right_label
        )

    def lift_pairing(self, left, right):

        module = self.module()
        if left not in module or right not in module:
            raise TypeError(f"the coordinate lift pairs elements of {module}")
        left_coefficients = module.framing_coefficients(left)
        right_coefficients = module.framing_coefficients(right)
        target = self.codomain()
        result = target.zero()
        for left_label, left_coefficient in left_coefficients.items():
            for right_label, right_coefficient in right_coefficients.items():
                scalar = left_coefficient * right_coefficient
                if scalar:
                    result += target.scalar_multiple(
                        scalar,
                        self._gram_entry(left_label, right_label),
                    )
        return result

    def gram_tensor(self):

        if self.codomain() not in OwnedRings():
            raise TypeError("a Gram tensor here requires scalar-valued lift entries")
        labels = self.module().module_generating_set()
        size = labels.cardinality()
        if not size.is_finite():
            raise TypeError("a finite Gram tensor requires a finite module framing")
        rank = int(size.finite_value())
        return tensor(
            self.codomain(),
            (),
            (rank, rank),
            (
                self._gram_entry(labels[i], labels[j])
                for i in range(rank)
                for j in range(rank)
            ),
        )

    def polar_form(self):

        module = self.module()
        tensor_square = Modules(module.base_ring()).tensor_product((module, module))
        return tensor_square.module_category().Mor(tensor_square, self.codomain())(
            lambda left, right: self(left + right) - self(left) - self(right)
        )

    def b(self, left, right):
        return self.polar_form()(left, right)

    def polar_coordinate_values(self):
        return self.polar_form().coordinate_values()

    def pullback(self, morphism):
        if morphism.codomain() is not self.module():
            raise ValueError("the pullback map must land in the form's module")
        induced = morphism.divided_square()
        result = self * induced
        values = self._lift_coordinate_values
        pulled_values = None
        pullback_domain = morphism.domain()
        has_finite_framing = (
            pullback_domain in FramedModules(pullback_domain.base_ring())
            and pullback_domain.module_generating_set().cardinality().is_finite()
        )
        if values is not None and has_finite_framing:
            labels = _finite_framing(pullback_domain)
            pulled_values = _coordinate_family_from_function(
                labels,
                labels,
                self.codomain(),
                lambda left_label, right_label: self.lift_pairing(
                    morphism(pullback_domain.module_generator(left_label)),
                    morphism(pullback_domain.module_generator(right_label)),
                ),
                name="Pulled-back quadratic lift coordinate values",
            )
        parent = result.parent()
        return parent._from_classifying_morphism(
            result,
            lift_coordinate_values=pulled_values,
        )


class QuadraticModuleMor(ModuleMor):
    r"""The ordinary Hom ``Hom_R(Gamma^2(M),W)`` with quadratic-map syntax."""

    Element = QuadraticModuleMorphism

    def _from_classifying_morphism(self, morphism, *, lift_coordinate_values=None):
        if morphism.domain() is not self.domain() or morphism.codomain() is not self.codomain():
            raise ValueError("the quadratic classifier has the wrong endpoints")
        return self.element_class(
            self,
            morphism,
            lift_coordinate_values=lift_coordinate_values,
        )

    def from_quadratic_map(self, quadratic, *, lift_coordinate_values=None):
        square = self.domain()
        source = square.divided_square_source()

        def generator_image(selection):
            support = selection.support()
            if int(support.cardinality()) == 1:
                label = support[0]
                return quadratic(source.module_generator(label))
            left = support[0]
            right = support[1]
            return (
                quadratic(
                    source.module_generator(left)
                    + source.module_generator(right)
                )
                - quadratic(source.module_generator(left))
                - quadratic(source.module_generator(right))
            )

        return self.element_class(
            self,
            generator_image,
            lift_coordinate_values=lift_coordinate_values,
        )

    def _from_coordinate_datum(self, datum):
        source = self.domain().divided_square_source()
        labels = _finite_framing(source)
        values = _coordinate_family(
            labels,
            labels,
            self.codomain(),
            datum,
            name="Quadratic lift coordinate values",
        )
        size = int(labels.cardinality())
        for i in range(size):
            for j in range(i + 1, size):
                left = labels[i]
                right = labels[j]
                indices = values.index_set()
                lr = indices(lambda index: left if int(index) == 0 else right)
                rl = indices(lambda index: right if int(index) == 0 else left)
                if values[lr] != values[rl]:
                    raise ValueError(
                        "the bilinear lift of a quadratic form must be symmetric"
                    )

        def quadratic(element):
            coefficients = source.framing_coefficients(element)
            result = self.codomain().zero()
            indices = values.index_set()
            for left_label, left_coefficient in coefficients.items():
                for right_label, right_coefficient in coefficients.items():
                    scalar = left_coefficient * right_coefficient
                    if not scalar:
                        continue
                    pair = indices(
                        lambda index: (
                            left_label if int(index) == 0 else right_label
                        )
                    )
                    result += self.codomain().scalar_multiple(
                        scalar,
                        values[pair],
                    )
            return result

        return self.from_quadratic_map(
            quadratic,
            lift_coordinate_values=values,
        )

    def _element_constructor_(self, datum):
        if isinstance(datum, ModuleMorphism):
            return ModuleMor._element_constructor_(self, datum)

        if isinstance(datum, IndexedFamily) or hasattr(datum, "rows"):
            return self._from_coordinate_datum(datum)
        if (
            isinstance(datum, (tuple, list))
            and all(isinstance(row, (tuple, list)) for row in datum)
        ):
            return self._from_coordinate_datum(datum)
        return ModuleMor._element_constructor_(self, datum)


class DividedSquareModules(OwnedCategoryOverBaseRing):
    r"""Degree-two divided powers, classifying quadratic maps."""

    def an_object(self):
        r"""The divided square of the free module of rank one."""
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return Modules(self.base_ring()).an_object().divided_square()

    @classmethod
    def _repr_object_names(cls):
        return "divided-square modules"

    def super_categories(self):
        return [DividedPowerModules(self.base_ring())]

    class ParentMethods:
        def _module_mor_class(self):
            return QuadraticModuleMor

        def divided_square_source(self):
            return self.power_source()

        def quadratic(self, element):
            r"""Return the universal quadratic value ``gamma_2(element)``."""
            source = self.divided_square_source()

            coefficients = source.framing_coefficients(element)
            square_labels = self.module_generating_set()
            values = {}
            for label, coefficient in coefficients.items():
                if coefficient:
                    target_label = square_labels.from_multiplicities({label: 2})
                    values[target_label] = coefficient * coefficient
            source_labels = source.module_generating_set()
            for left, left_coefficient in coefficients.items():
                if not left_coefficient:
                    continue
                left_position = int(source_labels.ranking_map()(left))
                for right, right_coefficient in coefficients.items():
                    if (
                        not right_coefficient
                        or left_position >= int(source_labels.ranking_map()(right))
                    ):
                        continue
                    target_label = square_labels.from_multiplicities(
                        {left: 1, right: 1}
                    )
                    values[target_label] = left_coefficient * right_coefficient
            return self.linear_combination(values)

        def polar(self, left, right):
            r"""Return ``gamma_2(x+y)-gamma_2(x)-gamma_2(y)``."""
            return self.quadratic(left + right) - self.quadratic(left) - self.quadratic(right)

        def from_quadratic(self, quadratic, codomain):
            r"""Factor a quadratic map uniquely through the divided square."""
            source = self.divided_square_source()

            def generator_image(selection):
                support = selection.support()
                if int(support.cardinality()) == 1:
                    label = support[0]
                    return quadratic(source.module_generator(label))
                left = support[0]
                right = support[1]
                return (
                    quadratic(
                        source.module_generator(left)
                        + source.module_generator(right)
                    )
                    - quadratic(source.module_generator(left))
                    - quadratic(source.module_generator(right))
                )


            mor = self.module_category().Mor(self, codomain)
            return mor.from_quadratic_map(quadratic)


def _degree(degree) -> int:
    value = int(degree)
    if value < 0:
        raise ValueError("a graded degree is nonnegative")
    return value


def _free_degree_labels(source_labels, degree: int, flavor: str):

    if flavor in {"symmetric", "divided"}:
        return source_labels.multisets_of_size(degree)
    if flavor == "alternating":
        return source_labels.ordered_subsets_of_size(degree)
    raise ValueError(f"unknown power flavor {flavor!r}")


def _symmetric_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    lower_labels = _free_degree_labels(
        source_labels,
        degree - 1,
        "symmetric",
    )
    width = int(labels.cardinality())
    for relation in relation_rows:
        for monomial in lower_labels:
            row = [ring.zero()] * width
            for source_position, coefficient in enumerate(relation):
                if not coefficient:
                    continue
                source_label = source_labels[source_position]
                target = monomial.add_label(source_label)
                row[labels.ranking_map()(target)] += ring(coefficient)
            if any(row):
                rows.append(row)
    return rows


def _alternating_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    lower_labels = _free_degree_labels(
        source_labels,
        degree - 1,
        "alternating",
    )
    singleton_labels = _free_degree_labels(source_labels, 1, "alternating")
    width = int(labels.cardinality())
    for relation in relation_rows:
        for monomial in lower_labels:
            row = [ring.zero()] * width
            for source_position, coefficient in enumerate(relation):
                if not coefficient:
                    continue
                source_label = source_labels[source_position]
                singleton = singleton_labels.from_multiplicities({source_label: 1})
                wedge = monomial.wedge_with(singleton)
                if wedge is None:
                    continue
                target, sign = wedge
                row[labels.ranking_map()(target)] += sign * ring(coefficient)
            if any(row):
                rows.append(row)
    return rows


def _divided_product_coefficient(left, right):
    return prod(
        binomial(
            left.multiplicity(label) + right.multiplicity(label),
            left.multiplicity(label),
        )
        for label in left.support()
    )


def _divided_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    width = int(labels.cardinality())
    for relation in relation_rows:
        for divided_degree in range(1, degree + 1):
            divided_labels = _free_degree_labels(
                source_labels,
                divided_degree,
                "divided",
            )
            complementary_labels = _free_degree_labels(
                source_labels,
                degree - divided_degree,
                "divided",
            )
            for monomial in complementary_labels:
                row = [ring.zero()] * width
                for exponent in divided_labels:
                    coefficient = ring.one()
                    for source_label in exponent.support():
                        scalar = ring(
                            relation[int(source_labels.ranking_map()(source_label))]
                        )
                        coefficient *= scalar ** exponent.multiplicity(source_label)
                    if not coefficient:
                        continue
                    target = exponent.merged_with(monomial)
                    row[labels.ranking_map()(target)] += (
                        coefficient
                        * _divided_product_coefficient(exponent, monomial)
                    )
                if any(row):
                    rows.append(row)
    return rows


def _presented_degree_power(
    module,
    degree: int,
    flavor: str,
    *,
    extra_categories=(),
    extra_construction_data=None,
):

    ring = _owned_ring(module.base_ring())
    if degree == 0:

        return ring.regular_module()
    if degree == 1:
        return module

    source_labels = module.module_generating_set()
    labels = _free_degree_labels(source_labels, degree, flavor)

    if module in FramedFreeModules(ring):
        if extra_categories or extra_construction_data:
            return ring._fresh_free_module_on(
                labels,
                _extra_categories=extra_categories,
                _extra_construction_data=extra_construction_data,
            )
        return ring.free_module(labels)

    assert module in ModulesWithChosenFinitePresentation(ring), (
        f"the represented {flavor} power backend requires a free module or a chosen finite presentation"
    )


    if not source_labels.cardinality().is_finite():
        raise TypeError("a chosen finite presentation must have a finite framing")


    relation_rows = _presentation_rows(module)
    if flavor == "symmetric":
        rows = _symmetric_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    elif flavor == "alternating":
        rows = _alternating_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    elif flavor == "divided":
        rows = _divided_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    else:
        raise ValueError(f"unknown power flavor {flavor!r}")


    relation_matrix = ring.matrix_space(len(rows), int(labels.cardinality())).from_rows(tuple(tuple(row) for row in rows))
    relation_labels = Sets.Δ[len(rows) - 1]
    presentation = _presentation_from_relation_rows(
        ring,
        labels,
        relation_labels,
        relation_matrix,
    )
    return ModulesWithChosenFinitePresentation(ring)(
        presentation,
        category=Category.join(extra_categories) if extra_categories else None,
        **(extra_construction_data or {}),
    )


@cached_function(key=lambda module: id(module))
def _divided_square(module):
    r"""Return ``Gamma^2_R(M)``, the universal target for quadratic maps."""
    return _presented_degree_power(
        module,
        2,
        "divided",
        extra_categories=(
            DividedPowerModules(module.base_ring()),
            DividedSquareModules(module.base_ring()),
        ),
        extra_construction_data={
            "power_source": module,
            "power_degree": 2,
        },
    )


def _divided_square_morphism(morphism):
    r"""Return ``Gamma^2(f)`` for a module morphism ``f``."""
    source = morphism.domain().divided_square()
    target = morphism.codomain().divided_square()
    return source.from_quadratic(
        lambda element: target.quadratic(morphism(element)),
        target,
    )


def _tensor_power(module, degree):
    r"""Return the selected iterated tensor power ``M^{\otimes degree}``."""
    degree = _degree(degree)
    if degree == 0:

        return module.base_ring().regular_module()
    if degree == 1:
        return module
    return _tensor_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _tensor_power_nontrivial(module, degree):
    left = module.tensor_power(degree - 1)
    family = _finite_factor_family((left, module), name="Tensor-power factors")
    return _module_tensor_product_with_data(
        family,
        extra_categories=(TensorPowerModules(module.base_ring()),),
        extra_construction_data={
            "power_source": module,
            "power_degree": degree,
        },
    )


def _symmetric_power(module, degree):
    r"""Return ``Sym^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree <= 1:
        return _presented_degree_power(module, degree, "symmetric")
    return _symmetric_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _symmetric_power_nontrivial(module, degree):
    return _presented_degree_power(
        module,
        degree,
        "symmetric",
        extra_categories=(SymmetricPowerModules(module.base_ring()),),
        extra_construction_data={
            "power_source": module,
            "power_degree": degree,
        },
    )


def _alternating_power(module, degree):
    r"""Return ``Lambda^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree <= 1:
        return _presented_degree_power(module, degree, "alternating")
    return _alternating_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _alternating_power_nontrivial(module, degree):
    return _presented_degree_power(
        module,
        degree,
        "alternating",
        extra_categories=(AlternatingPowerModules(module.base_ring()),),
        extra_construction_data={
            "power_source": module,
            "power_degree": degree,
        },
    )


def _divided_power(module, degree):
    r"""Return the divided power ``Gamma^degree(module)``.

    Degree two is the existing universal quadratic square; higher degrees use
    the same divided-power-ideal presentation.
    """
    degree = _degree(degree)
    if degree == 2:
        return module.divided_square()
    if degree <= 1:
        return _presented_degree_power(module, degree, "divided")
    return _divided_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _divided_power_nontrivial(module, degree):
    return _presented_degree_power(
        module,
        degree,
        "divided",
        extra_categories=(DividedPowerModules(module.base_ring()),),
        extra_construction_data={
            "power_source": module,
            "power_degree": degree,
        },
    )


def _tensor_power_permutation(module, degree, positions):
    r"""Return the permutation of tensor factors specified by ``positions``."""
    degree = _degree(degree)

    positions = finite_ordered_set(positions)
    if (
        int(positions.cardinality()) != degree
        or any(int(position) < 0 or int(position) >= degree for position in positions)
    ):
        raise ValueError("positions must be a permutation of the tensor slots")
    power = module.tensor_power(degree)

    if degree == 0:
        return power.module_category().Mor(power, power).identity()
    def permuted_label(label):
        factors = _flatten_tensor_label(label, degree)
        word = indexed_family(
            Sets.Δ[degree - 1],
            lambda index: factors[
                int(positions[int(index)])
            ],
            name="Permuted tensor word",
        )
        return power.module_generator(_nested_tensor_label(module, word))

    return power.module_category().Mor(power, power)(permuted_label)


def _power_morphism(morphism, degree: int, flavor: str):

    degree = _degree(degree)
    constructors = {
        "symmetric": _symmetric_power,
        "alternating": _alternating_power,
        "divided": _divided_power,
    }
    source = constructors[flavor](morphism.domain(), degree)
    target = constructors[flavor](morphism.codomain(), degree)
    if degree == 0:
        return source.module_category().Mor(source, target).identity()
    if degree == 1:
        return morphism

    codomain_labels = morphism.codomain().module_generating_set()

    def image_of_source_label(source_label):
        if flavor == "alternating":
            polynomial = {
                codomain_labels.ordered_subsets_of_size(0)[0]:
                morphism.codomain().base_ring().one()
            }
            for source_generator_label in source_label:
                image = morphism.codomain().framing_coefficients(morphism(
                        morphism.domain().module_generator(source_generator_label)
                    ))
                next_polynomial = {}
                singleton_indices = codomain_labels.ordered_subsets_of_size(1)
                for wedge, coefficient in polynomial.items():
                    for target_label, scalar in image.items():
                        singleton = singleton_indices.from_multiplicities(
                            {target_label: 1}
                        )
                        product = wedge.wedge_with(singleton)
                        if product is None:
                            continue
                        new_wedge, sign = product
                        next_polynomial[new_wedge] = (
                            next_polynomial.get(
                                new_wedge,
                                morphism.codomain().base_ring().zero(),
                            )
                            + sign * coefficient * scalar
                        )
                polynomial = next_polynomial
            return target.linear_combination(polynomial)

        polynomial = {
            codomain_labels.multisets_of_size(0)[0]:
            morphism.codomain().base_ring().one()
        }
        accumulated_degree = 0
        for source_generator_label in source_label.support():
            power = source_label.multiplicity(source_generator_label)
            image = morphism.codomain().framing_coefficients(morphism(
                    morphism.domain().module_generator(source_generator_label)
                ))

            if flavor == "divided":
                if not image:
                    return target.zero()
                support = _ordered_coefficient_support(morphism.codomain(), image)
                local_indices = support.multisets_of_size(power)
                codomain_degree_indices = codomain_labels.multisets_of_size(power)
                factor_polynomial = {}
                for local_selection in local_indices:
                    coefficient = morphism.codomain().base_ring().one()
                    for target_label in local_selection.support():
                        coefficient *= (
                            image[target_label]
                            ** local_selection.multiplicity(target_label)
                        )
                    if not coefficient:
                        continue
                    target_selection = (
                        codomain_degree_indices.from_source_rank_positions(
                            int(codomain_labels.ranking_map()(target_label))
                            for target_label in local_selection
                        )
                    )
                    factor_polynomial[target_selection] = coefficient

                next_polynomial = {}
                for old_selection, old_coefficient in polynomial.items():
                    for factor_selection, factor_coefficient in factor_polynomial.items():
                        new_selection = old_selection.merged_with(factor_selection)
                        coefficient = (
                            old_coefficient
                            * factor_coefficient
                            * _divided_product_coefficient(
                                old_selection,
                                factor_selection,
                            )
                        )
                        next_polynomial[new_selection] = (
                            next_polynomial.get(
                                new_selection,
                                morphism.codomain().base_ring().zero(),
                            )
                            + coefficient
                        )
                polynomial = next_polynomial
                accumulated_degree += power
                continue

            for _occurrence in range(power):
                next_polynomial = {}
                for old_selection, old_coefficient in polynomial.items():
                    for target_label, scalar in image.items():
                        new_selection = old_selection.add_label(target_label)
                        next_polynomial[new_selection] = (
                            next_polynomial.get(
                                new_selection,
                                morphism.codomain().base_ring().zero(),
                            )
                            + old_coefficient * scalar
                        )
                polynomial = next_polynomial
                accumulated_degree += 1
        return target.linear_combination(polynomial)

    return source.module_category().Mor(source, target)(image_of_source_label)


def _symmetric_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "symmetric")


def _alternating_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "alternating")


def _divided_power_morphism(morphism, degree):
    degree = _degree(degree)
    if degree == 2:
        return morphism.divided_square()
    return _power_morphism(morphism, degree, "divided")


def _divided_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous divided-power elements into ``Gamma^{a+b} M``."""

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = module.divided_power_module(left_degree)
    source_right = module.divided_power_module(right_degree)
    target = module.divided_power_module(left_degree + right_degree)
    left_coefficients = source_left.framing_coefficients(left)
    right_coefficients = source_right.framing_coefficients(right)

    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    source_labels = module.module_generating_set()

    def selection_of(label, degree):
        if degree == 1:
            return source_labels.multisets_of_size(1).from_multiplicities(
                {label: 1}
            )
        return label

    result = {}
    total_degree = left_degree + right_degree
    for left_label, left_coefficient in left_coefficients.items():
        left_selection = selection_of(left_label, left_degree)
        for right_label, right_coefficient in right_coefficients.items():
            right_selection = selection_of(right_label, right_degree)
            selection = left_selection.merged_with(right_selection)
            coefficient = (
                left_coefficient
                * right_coefficient
                * _divided_product_coefficient(left_selection, right_selection)
            )
            label = (
                selection.support()[0]
                if total_degree == 1
                else selection
            )
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def _alternating_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous exterior-power elements by the wedge product."""

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = module.exterior_power(left_degree)
    source_right = module.exterior_power(right_degree)
    target = module.exterior_power(left_degree + right_degree)
    left_coefficients = source_left.framing_coefficients(left)
    right_coefficients = source_right.framing_coefficients(right)
    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    source_labels = module.module_generating_set()

    def selection_of(label, degree):
        if degree == 1:
            return source_labels.ordered_subsets_of_size(1).from_multiplicities(
                {label: 1}
            )
        return label

    result = {}
    total_degree = left_degree + right_degree
    for left_label, left_coefficient in left_coefficients.items():
        left_selection = selection_of(left_label, left_degree)
        for right_label, right_coefficient in right_coefficients.items():
            right_selection = selection_of(right_label, right_degree)
            wedge = left_selection.wedge_with(right_selection)
            if wedge is None:
                continue
            selection, sign = wedge
            coefficient = sign * left_coefficient * right_coefficient
            label = (
                selection.support()[0]
                if total_degree == 1
                else selection
            )
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def _ordered_coefficient_support(module, coefficients):

    source_labels = module.module_generating_set()
    positions = Sets.Δ[len(coefficients) - 1]

    def label_at(index):
        requested = int(index)
        for label in coefficients:
            label_rank = int(source_labels.ranking_map()(label))
            preceding = sum(
                1
                for other in coefficients
                if int(source_labels.ranking_map()(other)) < label_rank
            )
            if preceding == requested:
                return label
        raise IndexError(requested)

    return FiniteOrderedSets().from_indexed(
        positions,
        label_at,
        name="Finite coefficient support",
    )


def _divided_power_element(module, degree, element):
    r"""Return ``gamma_degree(element)`` in ``Gamma^degree(module)``."""

    degree = _degree(degree)
    if degree == 0:
        target = module.divided_power_module(0)
        return target.module_generator(0)
    if degree == 1:
        return element
    if degree == 2:
        return module.divided_power_module(2).quadratic(element)

    target = module.divided_power_module(degree)
    coefficients = module.framing_coefficients(element)
    if not coefficients:
        return target.zero()
    support = _ordered_coefficient_support(module, coefficients)
    local_labels = support.multisets_of_size(degree)
    target_labels = target.module_generating_set()
    source_labels = module.module_generating_set()
    result = {}
    for local_selection in local_labels:
        coefficient = module.base_ring().one()
        for label in local_selection.support():
            coefficient *= coefficients[label] ** local_selection.multiplicity(label)
        if not coefficient:
            continue
        target_selection = target_labels.from_source_rank_positions(
            int(source_labels.ranking_map()(label)) for label in local_selection
        )
        result[target_selection] = coefficient
    return target.linear_combination(result)


def _divided_power_invariant_inclusion(module, degree):
    r"""Return ``Gamma^n M -> M^{tensor n}`` as the symmetric orbit sum."""

    degree = _degree(degree)
    source = module.divided_power_module(degree)
    target = module.tensor_power(degree)
    source_labels = module.module_generating_set()

    def invariant(source_label):
        if degree == 0:
            return target.module_generator(0)
        if degree == 1:
            return target.module_generator(source_label)
        selection = (
            source_labels.multisets_of_size(1).from_multiplicities(
                {source_label: 1}
            )
            if degree == 1
            else source_label
        )
        support = selection.support()
        positions = Sets.Δ[degree - 1]
        word_space = Sets().product(indexed_family(positions, lambda _position: support))
        words = finite_ordered_set(word_space).filtered(
            lambda word: all(
                sum(
                    1
                    for position in positions
                    if word.component(position) == label
                )
                == selection.multiplicity(label)
                for label in support
            ),
            name="Multiset permutations",
        )
        return sum(
            (
                target.module_generator(_nested_tensor_label(module, word))
                for word in words
            ),
            target.zero(),
        )

    return source.module_category().Mor(source, target)(invariant)


def _tensor_power_polarization(module, degree):
    r"""Return ``M^{tensor n} -> Gamma^n M`` by divided-power multiplication."""

    degree = _degree(degree)
    source = module.tensor_power(degree)
    target = module.divided_power_module(degree)
    if degree == 0:
        return source.module_category().Mor(source, target).identity()
    if degree == 1:
        return source.module_category().Mor(source, target).identity()

    def polarized(source_label):
        word = _flatten_tensor_label(source_label, degree)
        iterator = iter(word)
        first_label = next(iterator)
        result = module.divided_power_element(
            1,
            module.module_generator(first_label),
        )
        current_degree = 1
        for label in iterator:
            result = module.divided_power_product(
                current_degree,
                result,
                1,
                module.module_generator(label),
            )
            current_degree += 1
        return result

    return source.module_category().Mor(source, target)(polarized)


__all__ = [
    "AlternatingPowerModules",
    "DividedPowerModules",
    "SymmetricPowerModules",
    "TensorPowerModules",
]
