r"""Tensor, symmetric, exterior, and divided powers of presented modules.

The constructions use one selected module presentation.  Tensor powers are
iterated instances of the canonical categorical tensor product.  The other
three are the degree pieces of the corresponding graded algebra: for
``M = F/K`` they are the free degree piece modulo the degree part of the ideal
(or divided-power ideal) generated by ``K``.
"""

from sage.arith.misc import binomial
from sage.misc.cachefunc import cached_function
from dzack_research.preamble.categories.rings.ring_foundation import (
    OwnedCategoryOverBaseRing,
    _engine_ring,
    _owned_ring,
)
from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
    ModuleHomset,
    ModuleMorphism,
    _coordinate_family,
    _coordinate_family_from_function,
    _coordinate_pair,
    _finite_framing,
    module_coefficients,
    module_homset,
)
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors.tensor import tensor


class TensorPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "tensor powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class SymmetricPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "symmetric powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class AlternatingPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "exterior powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class DividedPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "divided powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class QuadraticModuleMorphism(ModuleMorphism):
    r"""A classifier ``Gamma^2(M) -> W``, read as the quadratic map ``M -> W``."""

    def module(self):
        return self.domain().divided_square_source()

    def __call__(self, element):
        parent = getattr(element, "parent", lambda: None)()
        if parent is self.domain():
            return self._call_(element)
        module = self.module()
        if parent is not module:
            element = module(element)
        return self._call_(self.domain().quadratic(element))

    def classifying_morphism(self):
        return self

    def lift_coordinate_values(self):
        values = self.__dict__.get("_preamble_quadratic_lift_coordinate_values")
        if values is None:
            raise TypeError(
                "this quadratic map has no selected bilinear coordinate presentation"
            )
        return values

    def _gram_entry(self, left_label, right_label):
        return _coordinate_pair(
            self.lift_coordinate_values(), left_label, right_label
        )

    def lift_pairing(self, left, right):
        from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
            module_coefficients,
        )

        module = self.module()
        if left not in module or right not in module:
            raise TypeError(f"the coordinate lift pairs elements of {module}")
        left_coefficients = module_coefficients(left, module)
        right_coefficients = module_coefficients(right, module)
        target = self.codomain()
        result = target.zero()
        for left_label, left_coefficient in left_coefficients.items():
            for right_label, right_coefficient in right_coefficients.items():
                scalar = left_coefficient * right_coefficient
                if scalar:
                    result += target.scalar_multiple(
                        scalar,
                        self._gram_entry(left_label, right_label),
                    )
        return result

    def gram_tensor(self):
        from dzack_research.preamble.categories.rings.ring_foundation import OwnedRings
        from dzack_research.preamble.categories.sets.cardinals import cardinal
        from dzack_research.preamble.tensors.tensor import tensor

        if self.codomain() not in OwnedRings():
            raise TypeError("a Gram tensor here requires scalar-valued lift entries")
        labels = self.module().module_generating_set()
        size = cardinal(labels.cardinality())
        if not size.is_finite():
            raise TypeError("a finite Gram tensor requires a finite module framing")
        rank = int(size.finite_value())
        return tensor(
            self.codomain(),
            (),
            (rank, rank),
            (
                self._gram_entry(labels.unrank(i), labels.unrank(j))
                for i in range(rank)
                for j in range(rank)
            ),
        )

    def polar_form(self):
        from dzack_research.preamble.categories.abstract_categories.constructions import (
            TensorProduct,
        )

        module = self.module()
        return module_homset(TensorProduct(module, module), self.codomain())(
            lambda left, right: self(left + right) - self(left) - self(right)
        )

    def b(self, left, right):
        return self.polar_form()(left, right)

    def polar_coordinate_values(self):
        return self.polar_form().coordinate_values()

    def pullback(self, morphism):
        if morphism.codomain() is not self.module():
            raise ValueError("the pullback map must land in the form's module")
        induced = divided_square_morphism(morphism)
        result = self * induced
        values = self.__dict__.get("_preamble_quadratic_lift_coordinate_values")
        if values is not None:
            try:
                labels = _finite_framing(morphism.domain())
                pulled_values = _coordinate_family_from_function(
                    labels,
                    labels,
                    self.codomain(),
                    lambda left_label, right_label: self.lift_pairing(
                        morphism(morphism.domain().module_generator(left_label)),
                        morphism(morphism.domain().module_generator(right_label)),
                    ),
                    name="Pulled-back quadratic lift coordinate values",
                )
            except TypeError:
                pass
            else:
                result._preamble_quadratic_lift_coordinate_values = pulled_values
        return result


class QuadraticModuleHomset(ModuleHomset):
    r"""The ordinary Hom ``Hom_R(Gamma^2(M),W)`` with quadratic-map syntax."""

    Element = QuadraticModuleMorphism

    def from_quadratic_map(self, quadratic, *, lift_coordinate_values=None):
        square = self.domain()
        source = square.divided_square_source()

        def generator_image(selection):
            support = selection.support()
            if int(support.cardinality()) == 1:
                label = support.unrank(0)
                return quadratic(source.module_generator(label))
            left = support.unrank(0)
            right = support.unrank(1)
            return (
                quadratic(
                    source.module_generator(left)
                    + source.module_generator(right)
                )
                - quadratic(source.module_generator(left))
                - quadratic(source.module_generator(right))
            )

        result = ModuleHomset._element_constructor_(self, generator_image)
        if lift_coordinate_values is not None:
            result._preamble_quadratic_lift_coordinate_values = lift_coordinate_values
        return result

    def _from_coordinate_datum(self, datum):
        source = self.domain().divided_square_source()
        labels = _finite_framing(source)
        values = _coordinate_family(
            labels,
            labels,
            self.codomain(),
            datum,
            name="Quadratic lift coordinate values",
        )
        size = int(labels.cardinality())
        for i in range(size):
            for j in range(i + 1, size):
                left = labels.unrank(i)
                right = labels.unrank(j)
                indices = values.index_set()
                lr = indices(lambda index: left if int(index) == 0 else right)
                rl = indices(lambda index: right if int(index) == 0 else left)
                if values[lr] != values[rl]:
                    raise ValueError(
                        "the bilinear lift of a quadratic form must be symmetric"
                    )

        def quadratic(element):
            coefficients = module_coefficients(element, source)
            result = self.codomain().zero()
            indices = values.index_set()
            for left_label, left_coefficient in coefficients.items():
                for right_label, right_coefficient in coefficients.items():
                    scalar = left_coefficient * right_coefficient
                    if not scalar:
                        continue
                    pair = indices(
                        lambda index: (
                            left_label if int(index) == 0 else right_label
                        )
                    )
                    result += self.codomain().scalar_multiple(
                        scalar,
                        values[pair],
                    )
            return result

        return self.from_quadratic_map(
            quadratic,
            lift_coordinate_values=values,
        )

    def _element_constructor_(self, datum):
        if isinstance(datum, ModuleMorphism):
            return ModuleHomset._element_constructor_(self, datum)
        from dzack_research.preamble.categories.sets.indexed_families import IndexedFamily

        if isinstance(datum, IndexedFamily) or hasattr(datum, "rows"):
            return self._from_coordinate_datum(datum)
        if (
            isinstance(datum, (tuple, list))
            and all(isinstance(row, (tuple, list)) for row in datum)
        ):
            return self._from_coordinate_datum(datum)
        return ModuleHomset._element_constructor_(self, datum)


class DividedSquareModules(OwnedCategoryOverBaseRing):
    r"""Degree-two divided powers, classifying quadratic maps."""

    @classmethod
    def _repr_object_names(cls):
        return "divided-square modules"

    def super_categories(self):
        return [DividedPowerModules(self.base_ring())]

    class ParentMethods:
        def _module_homset_class(self):
            return QuadraticModuleHomset

        def divided_square_source(self):
            return self._preamble_divided_square_source

        def quadratic(self, element):
            r"""Return the universal quadratic value ``gamma_2(element)``."""
            source = self.divided_square_source()
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
                module_coefficients,
            )

            coefficients = module_coefficients(element, source)
            square_labels = self.module_generating_set()
            values = {}
            for label, coefficient in coefficients.items():
                if coefficient:
                    target_label = square_labels.from_multiplicities({label: 2})
                    values[target_label] = coefficient * coefficient
            source_labels = source.module_generating_set()
            for left, left_coefficient in coefficients.items():
                if not left_coefficient:
                    continue
                left_position = int(source_labels.rank(left))
                for right, right_coefficient in coefficients.items():
                    if (
                        not right_coefficient
                        or left_position >= int(source_labels.rank(right))
                    ):
                        continue
                    target_label = square_labels.from_multiplicities(
                        {left: 1, right: 1}
                    )
                    values[target_label] = left_coefficient * right_coefficient
            return self.linear_combination(values)

        def polar(self, left, right):
            r"""Return ``gamma_2(x+y)-gamma_2(x)-gamma_2(y)``."""
            return self.quadratic(left + right) - self.quadratic(left) - self.quadratic(right)

        def from_quadratic(self, quadratic, codomain):
            r"""Factor a quadratic map uniquely through the divided square."""
            source = self.divided_square_source()

            def generator_image(selection):
                support = selection.support()
                if int(support.cardinality()) == 1:
                    label = support.unrank(0)
                    return quadratic(source.module_generator(label))
                left = support.unrank(0)
                right = support.unrank(1)
                return (
                    quadratic(
                        source.module_generator(left)
                        + source.module_generator(right)
                    )
                    - quadratic(source.module_generator(left))
                    - quadratic(source.module_generator(right))
                )

            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
                module_homset,
            )

            homset = module_homset(self, codomain)
            constructor = getattr(homset, "from_quadratic_map", None)
            if constructor is not None:
                return constructor(quadratic)
            return homset(generator_image)


def _degree(degree) -> int:
    value = int(degree)
    if value < 0:
        raise ValueError("a graded degree is nonnegative")
    return value


def _free_degree_labels(source_labels, degree: int, flavor: str):
    from dzack_research.preamble.categories.sets.fixed_size_selections import (
        multisets_of_size,
        ordered_subsets_of_size,
    )

    if flavor in {"symmetric", "divided"}:
        return multisets_of_size(source_labels, degree)
    if flavor == "alternating":
        return ordered_subsets_of_size(source_labels, degree)
    raise ValueError(f"unknown power flavor {flavor!r}")


def _symmetric_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    lower_labels = _free_degree_labels(
        source_labels,
        degree - 1,
        "symmetric",
    )
    width = int(labels.cardinality())
    for relation in relation_rows:
        for monomial in lower_labels:
            row = [ring.zero()] * width
            for source_position, coefficient in enumerate(relation):
                if not coefficient:
                    continue
                source_label = source_labels.unrank(source_position)
                target = monomial.add_label(source_label)
                row[labels.rank(target)] += ring(coefficient)
            if any(row):
                rows.append(row)
    return rows


def _alternating_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    lower_labels = _free_degree_labels(
        source_labels,
        degree - 1,
        "alternating",
    )
    singleton_labels = _free_degree_labels(source_labels, 1, "alternating")
    width = int(labels.cardinality())
    for relation in relation_rows:
        for monomial in lower_labels:
            row = [ring.zero()] * width
            for source_position, coefficient in enumerate(relation):
                if not coefficient:
                    continue
                source_label = source_labels.unrank(source_position)
                singleton = singleton_labels.from_multiplicities({source_label: 1})
                wedge = monomial.wedge_with(singleton)
                if wedge is None:
                    continue
                target, sign = wedge
                row[labels.rank(target)] += sign * ring(coefficient)
            if any(row):
                rows.append(row)
    return rows


def _divided_product_coefficient(left, right):
    coefficient = 1
    for label in left.support():
        coefficient *= binomial(
            left.multiplicity(label) + right.multiplicity(label),
            left.multiplicity(label),
        )
    for label in right.support():
        if left.multiplicity(label) == 0:
            coefficient *= 1
    return coefficient


def _divided_relation_rows(
    relation_rows,
    source_labels,
    degree: int,
    labels,
    ring,
):
    if degree == 0:
        return []
    rows = []
    width = int(labels.cardinality())
    for relation in relation_rows:
        for divided_degree in range(1, degree + 1):
            divided_labels = _free_degree_labels(
                source_labels,
                divided_degree,
                "divided",
            )
            complementary_labels = _free_degree_labels(
                source_labels,
                degree - divided_degree,
                "divided",
            )
            for monomial in complementary_labels:
                row = [ring.zero()] * width
                for exponent in divided_labels:
                    coefficient = ring.one()
                    for source_label in exponent.support():
                        scalar = ring(
                            relation[int(source_labels.rank(source_label))]
                        )
                        coefficient *= scalar ** exponent.multiplicity(source_label)
                    if not coefficient:
                        continue
                    target = exponent.merged_with(monomial)
                    row[labels.rank(target)] += (
                        coefficient
                        * _divided_product_coefficient(exponent, monomial)
                    )
                if any(row):
                    rows.append(row)
    return rows


def _presented_degree_power(module, degree: int, flavor: str):
    from dzack_research.preamble.categories.modules.framed.framed_free_modules import (
        FramedFreeModules,
        FreeModuleOn,
    )
    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
        FinitelyPresentedModule,
        ModulesWithChosenFinitePresentation,
        _presentation_from_relation_rows,
        _presentation_matrix,
    )
    from dzack_research.preamble.categories.sets.set_categories import Sets

    ring = _owned_ring(module.base_ring())
    if degree == 0:
        from dzack_research.preamble.categories.modules.framed.framed_free_modules import (
            ring_as_module,
        )

        return ring_as_module(ring)
    if degree == 1:
        return module

    source_labels = module.module_generating_set()
    labels = _free_degree_labels(source_labels, degree, flavor)

    if module in FramedFreeModules(ring):
        return FreeModuleOn(ring, labels)

    if module not in ModulesWithChosenFinitePresentation(ring):
        raise NotImplementedError(
            f"the represented {flavor} power backend requires a free module "
            "or a chosen finite presentation"
        )

    from dzack_research.preamble.categories.sets.cardinals import cardinal

    if not cardinal(source_labels.cardinality()).is_finite():
        raise TypeError("a chosen finite presentation must have a finite framing")

    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
        _presentation_rows,
    )

    relation_rows = _presentation_rows(module)
    if flavor == "symmetric":
        rows = _symmetric_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    elif flavor == "alternating":
        rows = _alternating_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    elif flavor == "divided":
        rows = _divided_relation_rows(
            relation_rows,
            source_labels,
            degree,
            labels,
            ring,
        )
    else:
        raise ValueError(f"unknown power flavor {flavor!r}")

    from dzack_research.preamble.categories.modules.framed.framed_free_modules import MatrixSpace

    relation_matrix = MatrixSpace(
        ring,
        len(rows),
        int(labels.cardinality()),
    ).from_rows(tuple(tuple(row) for row in rows))
    relation_labels = Sets.Δ[len(rows) - 1]
    presentation = _presentation_from_relation_rows(
        ring,
        labels,
        relation_labels,
        relation_matrix,
    )
    return FinitelyPresentedModule(presentation)


@cached_function(key=lambda module: id(module))
def DividedSquare(module):
    r"""Return ``Gamma^2_R(M)``, the universal target for quadratic maps."""
    result = _presented_degree_power(module, 2, "divided")
    result._preamble_divided_square_source = module
    return refine(
        result,
        [
            DividedPowerModules(module.base_ring()),
            DividedSquareModules(module.base_ring()),
        ],
    )


QuadraticSquare = DividedSquare


def divided_square_morphism(morphism, source=None, target=None):
    r"""Return ``Gamma^2(f)`` for a module morphism ``f``."""
    if source is None:
        source = DividedSquare(morphism.domain())
    if target is None:
        target = DividedSquare(morphism.codomain())
    if source.divided_square_source() is not morphism.domain():
        raise ValueError("the source divided square has the wrong module")
    if target.divided_square_source() is not morphism.codomain():
        raise ValueError("the target divided square has the wrong module")
    return source.from_quadratic(
        lambda element: target.quadratic(morphism(element)),
        target,
    )


def TensorPower(module, degree):
    r"""Return the selected iterated tensor power ``M^{\otimes degree}``."""
    degree = _degree(degree)
    if degree == 0:
        from dzack_research.preamble.categories.modules.framed.framed_free_modules import (
            ring_as_module,
        )

        return ring_as_module(module.base_ring())
    if degree == 1:
        return module
    return _tensor_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _tensor_power_nontrivial(module, degree):
    from dzack_research.preamble.categories.abstract_categories.constructions import TensorProduct

    result = TensorProduct(TensorPower(module, degree - 1), module)
    return refine(result, TensorPowerModules(module.base_ring()))


def SymmetricPower(module, degree):
    r"""Return ``Sym^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree <= 1:
        return _presented_degree_power(module, degree, "symmetric")
    return _symmetric_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _symmetric_power_nontrivial(module, degree):
    result = _presented_degree_power(module, degree, "symmetric")
    return refine(result, SymmetricPowerModules(module.base_ring()))


def AlternatingPower(module, degree):
    r"""Return ``Lambda^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree <= 1:
        return _presented_degree_power(module, degree, "alternating")
    return _alternating_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _alternating_power_nontrivial(module, degree):
    result = _presented_degree_power(module, degree, "alternating")
    return refine(result, AlternatingPowerModules(module.base_ring()))


def DividedPower(module, degree):
    r"""Return the divided power ``Gamma^degree(module)``.

    Degree two is the existing universal quadratic square; higher degrees use
    the same divided-power-ideal presentation.
    """
    degree = _degree(degree)
    if degree == 2:
        return DividedSquare(module)
    if degree <= 1:
        return _presented_degree_power(module, degree, "divided")
    return _divided_power_nontrivial(module, degree)


@cached_function(key=lambda module, degree: (id(module), int(degree)))
def _divided_power_nontrivial(module, degree):
    result = _presented_degree_power(module, degree, "divided")
    return refine(result, DividedPowerModules(module.base_ring()))


from dzack_research.preamble.categories.modules.tensor_products import (
    _flatten_tensor_label,
    _nested_tensor_label,
)


def tensor_power_permutation(module, degree, positions):
    r"""Return the permutation of tensor factors specified by ``positions``."""
    degree = _degree(degree)
    from dzack_research.preamble.categories.sets.set_categories import Sets
    from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
    from dzack_research.preamble.categories.sets.indexed_families import indexed_family

    positions = finite_ordered_set(positions)
    if (
        int(positions.cardinality()) != degree
        or any(int(position) < 0 or int(position) >= degree for position in positions)
    ):
        raise ValueError("positions must be a permutation of the tensor slots")
    power = TensorPower(module, degree)
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    if degree == 0:
        return module_homset(power, power).identity()
    def permuted_label(label):
        factors = _flatten_tensor_label(label, degree)
        word = indexed_family(
            Sets.Δ[degree - 1],
            lambda index: factors.unrank(
                int(positions.unrank(int(index)))
            ),
            name="Permuted tensor word",
        )
        return power.module_generator(_nested_tensor_label(module, word))

    return module_homset(power, power)(permuted_label)


def _power_morphism(morphism, degree: int, flavor: str):
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
        module_homset,
    )
    from dzack_research.preamble.categories.sets.fixed_size_selections import (
        multisets_of_size,
        ordered_subsets_of_size,
    )

    degree = _degree(degree)
    constructors = {
        "symmetric": SymmetricPower,
        "alternating": AlternatingPower,
        "divided": DividedPower,
    }
    source = constructors[flavor](morphism.domain(), degree)
    target = constructors[flavor](morphism.codomain(), degree)
    if degree == 0:
        return module_homset(source, target).identity()
    if degree == 1:
        return morphism

    codomain_labels = morphism.codomain().module_generating_set()

    def image_of_source_label(source_label):
        if flavor == "alternating":
            polynomial = {
                ordered_subsets_of_size(codomain_labels, 0).unrank(0):
                morphism.codomain().base_ring().one()
            }
            for source_generator_label in source_label:
                image = module_coefficients(
                    morphism(
                        morphism.domain().module_generator(source_generator_label)
                    ),
                    morphism.codomain(),
                )
                next_polynomial = {}
                singleton_indices = ordered_subsets_of_size(codomain_labels, 1)
                for wedge, coefficient in polynomial.items():
                    for target_label, scalar in image.items():
                        singleton = singleton_indices.from_multiplicities(
                            {target_label: 1}
                        )
                        product = wedge.wedge_with(singleton)
                        if product is None:
                            continue
                        new_wedge, sign = product
                        next_polynomial[new_wedge] = (
                            next_polynomial.get(
                                new_wedge,
                                morphism.codomain().base_ring().zero(),
                            )
                            + sign * coefficient * scalar
                        )
                polynomial = next_polynomial
            return target.linear_combination(polynomial)

        polynomial = {
            multisets_of_size(codomain_labels, 0).unrank(0):
            morphism.codomain().base_ring().one()
        }
        accumulated_degree = 0
        for source_generator_label in source_label.support():
            power = source_label.multiplicity(source_generator_label)
            image = module_coefficients(
                morphism(
                    morphism.domain().module_generator(source_generator_label)
                ),
                morphism.codomain(),
            )

            if flavor == "divided":
                if not image:
                    return target.zero()
                support = _ordered_coefficient_support(morphism.codomain(), image)
                local_indices = multisets_of_size(support, power)
                codomain_degree_indices = multisets_of_size(codomain_labels, power)
                factor_polynomial = {}
                for local_selection in local_indices:
                    coefficient = morphism.codomain().base_ring().one()
                    for target_label in local_selection.support():
                        coefficient *= (
                            image[target_label]
                            ** local_selection.multiplicity(target_label)
                        )
                    if not coefficient:
                        continue
                    target_selection = (
                        codomain_degree_indices.from_source_rank_positions(
                            int(codomain_labels.rank(target_label))
                            for target_label in local_selection
                        )
                    )
                    factor_polynomial[target_selection] = coefficient

                next_polynomial = {}
                for old_selection, old_coefficient in polynomial.items():
                    for factor_selection, factor_coefficient in factor_polynomial.items():
                        new_selection = old_selection.merged_with(factor_selection)
                        coefficient = (
                            old_coefficient
                            * factor_coefficient
                            * _divided_product_coefficient(
                                old_selection,
                                factor_selection,
                            )
                        )
                        next_polynomial[new_selection] = (
                            next_polynomial.get(
                                new_selection,
                                morphism.codomain().base_ring().zero(),
                            )
                            + coefficient
                        )
                polynomial = next_polynomial
                accumulated_degree += power
                continue

            for _occurrence in range(power):
                next_polynomial = {}
                for old_selection, old_coefficient in polynomial.items():
                    for target_label, scalar in image.items():
                        new_selection = old_selection.add_label(target_label)
                        next_polynomial[new_selection] = (
                            next_polynomial.get(
                                new_selection,
                                morphism.codomain().base_ring().zero(),
                            )
                            + old_coefficient * scalar
                        )
                polynomial = next_polynomial
                accumulated_degree += 1
        return target.linear_combination(polynomial)

    return module_homset(source, target)(image_of_source_label)


def symmetric_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "symmetric")


def alternating_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "alternating")


def divided_power_morphism(morphism, degree):
    degree = _degree(degree)
    if degree == 2:
        return divided_square_morphism(morphism)
    return _power_morphism(morphism, degree, "divided")


def divided_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous divided-power elements into ``Gamma^{a+b} M``."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )
    from dzack_research.preamble.categories.sets.fixed_size_selections import multisets_of_size

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = DividedPower(module, left_degree)
    source_right = DividedPower(module, right_degree)
    target = DividedPower(module, left_degree + right_degree)
    left_coefficients = module_coefficients(left, source_left)
    right_coefficients = module_coefficients(right, source_right)

    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    source_labels = module.module_generating_set()

    def selection_of(label, degree):
        if degree == 1:
            return multisets_of_size(source_labels, 1).from_multiplicities(
                {label: 1}
            )
        return label

    result = {}
    total_degree = left_degree + right_degree
    for left_label, left_coefficient in left_coefficients.items():
        left_selection = selection_of(left_label, left_degree)
        for right_label, right_coefficient in right_coefficients.items():
            right_selection = selection_of(right_label, right_degree)
            selection = left_selection.merged_with(right_selection)
            coefficient = (
                left_coefficient
                * right_coefficient
                * _divided_product_coefficient(left_selection, right_selection)
            )
            label = (
                selection.support().unrank(0)
                if total_degree == 1
                else selection
            )
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def alternating_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous exterior-power elements by the wedge product."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )
    from dzack_research.preamble.categories.sets.fixed_size_selections import ordered_subsets_of_size

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = AlternatingPower(module, left_degree)
    source_right = AlternatingPower(module, right_degree)
    target = AlternatingPower(module, left_degree + right_degree)
    left_coefficients = module_coefficients(left, source_left)
    right_coefficients = module_coefficients(right, source_right)
    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    source_labels = module.module_generating_set()

    def selection_of(label, degree):
        if degree == 1:
            return ordered_subsets_of_size(source_labels, 1).from_multiplicities(
                {label: 1}
            )
        return label

    result = {}
    total_degree = left_degree + right_degree
    for left_label, left_coefficient in left_coefficients.items():
        left_selection = selection_of(left_label, left_degree)
        for right_label, right_coefficient in right_coefficients.items():
            right_selection = selection_of(right_label, right_degree)
            wedge = left_selection.wedge_with(right_selection)
            if wedge is None:
                continue
            selection, sign = wedge
            coefficient = sign * left_coefficient * right_coefficient
            label = (
                selection.support().unrank(0)
                if total_degree == 1
                else selection
            )
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def _ordered_coefficient_support(module, coefficients):
    from dzack_research.preamble.categories.sets.set_categories import Sets
    from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_image

    source_labels = module.module_generating_set()
    positions = Sets.Δ[len(coefficients) - 1]

    def label_at(index):
        requested = int(index)
        for label in coefficients:
            label_rank = int(source_labels.rank(label))
            preceding = sum(
                1
                for other in coefficients
                if int(source_labels.rank(other)) < label_rank
            )
            if preceding == requested:
                return label
        raise IndexError(requested)

    return finite_ordered_image(
        positions,
        label_at,
        name="Finite coefficient support",
    )


def divided_power_element(module, degree, element):
    r"""Return ``gamma_degree(element)`` in ``Gamma^degree(module)``."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )
    from dzack_research.preamble.categories.sets.fixed_size_selections import multisets_of_size

    degree = _degree(degree)
    if degree == 0:
        target = DividedPower(module, 0)
        return target.module_generator(0)
    if degree == 1:
        return element
    if degree == 2:
        return DividedPower(module, 2).quadratic(element)

    target = DividedPower(module, degree)
    coefficients = module_coefficients(element, module)
    if not coefficients:
        return target.zero()
    support = _ordered_coefficient_support(module, coefficients)
    local_labels = multisets_of_size(support, degree)
    target_labels = target.module_generating_set()
    source_labels = module.module_generating_set()
    result = {}
    for local_selection in local_labels:
        coefficient = module.base_ring().one()
        for label in local_selection.support():
            coefficient *= coefficients[label] ** local_selection.multiplicity(label)
        if not coefficient:
            continue
        target_selection = target_labels.from_source_rank_positions(
            int(source_labels.rank(label)) for label in local_selection
        )
        result[target_selection] = coefficient
    return target.linear_combination(result)


def divided_power_invariant_inclusion(module, degree):
    r"""Return ``Gamma^n M -> M^{tensor n}`` as the symmetric orbit sum."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )
    from dzack_research.preamble.categories.sets.set_categories import CartesianProductOfFamily
    from dzack_research.preamble.categories.sets.set_categories import Sets
    from dzack_research.preamble.categories.sets.finite_ordered_sets import (
        finite_ordered_filter,
        finite_ordered_set,
    )
    from dzack_research.preamble.categories.sets.fixed_size_selections import multisets_of_size

    degree = _degree(degree)
    source = DividedPower(module, degree)
    target = TensorPower(module, degree)
    source_labels = module.module_generating_set()

    def invariant(source_label):
        if degree == 0:
            return target.module_generator(0)
        if degree == 1:
            return target.module_generator(source_label)
        selection = (
            multisets_of_size(source_labels, 1).from_multiplicities(
                {source_label: 1}
            )
            if degree == 1
            else source_label
        )
        support = selection.support()
        positions = Sets.Δ[degree - 1]
        word_space = CartesianProductOfFamily(
            positions,
            lambda _position: support,
        )
        words = finite_ordered_filter(
            finite_ordered_set(word_space),
            lambda word: all(
                sum(
                    1
                    for position in positions
                    if word.component(position) == label
                )
                == selection.multiplicity(label)
                for label in support
            ),
            name="Multiset permutations",
        )
        return sum(
            (
                target.module_generator(_nested_tensor_label(module, word))
                for word in words
            ),
            target.zero(),
        )

    return module_homset(source, target)(invariant)


def tensor_power_polarization(module, degree):
    r"""Return ``M^{tensor n} -> Gamma^n M`` by divided-power multiplication."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    degree = _degree(degree)
    source = TensorPower(module, degree)
    target = DividedPower(module, degree)
    if degree == 0:
        return module_homset(source, target).identity()
    if degree == 1:
        return module_homset(source, target).identity()

    def polarized(source_label):
        word = _flatten_tensor_label(source_label, degree)
        iterator = iter(word)
        first_label = next(iterator)
        result = divided_power_element(
            module,
            1,
            module.module_generator(first_label),
        )
        current_degree = 1
        for label in iterator:
            result = divided_power_product(
                module,
                current_degree,
                result,
                1,
                module.module_generator(label),
            )
            current_degree += 1
        return result

    return module_homset(source, target)(polarized)


def divided_square_invariant_inclusion(module):
    return divided_power_invariant_inclusion(module, 2)


def tensor_square_polarization(module):
    return tensor_power_polarization(module, 2)


__all__ = [
    "AlternatingPower",
    "AlternatingPowerModules",
    "DividedPower",
    "DividedPowerModules",
    "SymmetricPower",
    "SymmetricPowerModules",
    "TensorPower",
    "TensorPowerModules",
    "alternating_power_morphism",
    "alternating_power_product",
    "divided_power_element",
    "divided_power_invariant_inclusion",
    "divided_power_morphism",
    "divided_power_product",
    "divided_square_invariant_inclusion",
    "symmetric_power_morphism",
    "tensor_power_permutation",
    "tensor_power_polarization",
    "tensor_square_polarization",
]
