r"""Tensor, symmetric, exterior, and divided powers of presented modules.

The constructions use one selected module presentation.  Tensor powers are
iterated instances of the canonical categorical tensor product.  The other
three are the degree pieces of the corresponding graded algebra: for
``M = F/K`` they are the free degree piece modulo the degree part of the ideal
(or divided-power ideal) generated by ``K``.
"""

from itertools import combinations

from sage.arith.misc import binomial
from sage.combinat.integer_vector import IntegerVectors
from dzack_research.preamble.categories.rings import (
    OwnedCategoryOverBaseRing,
    engine_ring,
    owned_ring_view,
)
from dzack_research.preamble.categories.sets import finite_ordered_set
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors import tensor


class TensorPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "tensor powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class SymmetricPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "symmetric powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class AlternatingPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "exterior powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


class DividedPowerModules(OwnedCategoryOverBaseRing):
    @classmethod
    def _repr_object_names(cls):
        return "divided powers of modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules.pure.modules import Modules

        return [Modules(self.base_ring())]


def _degree(degree) -> int:
    value = int(degree)
    if value < 0:
        raise ValueError("a graded degree is nonnegative")
    return value


def _free_degree_labels(rank: int, degree: int, flavor: str):
    if flavor in {"symmetric", "divided"}:
        return tuple(tuple(vector) for vector in IntegerVectors(degree, rank))
    if flavor == "alternating":
        return tuple(combinations(range(rank), degree))
    raise ValueError(f"unknown power flavor {flavor!r}")


def _symmetric_relation_rows(relation_rows, rank: int, degree: int, labels):
    if degree == 0:
        return []
    position = {label: index for index, label in enumerate(labels)}
    rows = []
    for relation in relation_rows:
        for monomial in _free_degree_labels(rank, degree - 1, "symmetric"):
            row = [relation.base_ring().zero()] * len(labels)
            for index, coefficient in enumerate(relation):
                if not coefficient:
                    continue
                exponent = list(monomial)
                exponent[index] += 1
                row[position[tuple(exponent)]] += coefficient
            if any(row):
                rows.append(row)
    return rows


def _alternating_relation_rows(relation_rows, rank: int, degree: int, labels):
    if degree == 0:
        return []
    position = {label: index for index, label in enumerate(labels)}
    rows = []
    for relation in relation_rows:
        for monomial in combinations(range(rank), degree - 1):
            monomial_set = set(monomial)
            row = [relation.base_ring().zero()] * len(labels)
            for index, coefficient in enumerate(relation):
                if not coefficient or index in monomial_set:
                    continue
                sign = -1 if sum(other < index for other in monomial) % 2 else 1
                label = tuple(sorted((*monomial, index)))
                row[position[label]] += sign * coefficient
            if any(row):
                rows.append(row)
    return rows


def _divided_product_coefficient(left, right):
    coefficient = 1
    for left_exponent, right_exponent in zip(left, right, strict=True):
        coefficient *= binomial(left_exponent + right_exponent, left_exponent)
    return coefficient


def _divided_relation_rows(relation_rows, rank: int, degree: int, labels):
    if degree == 0:
        return []
    position = {label: index for index, label in enumerate(labels)}
    rows = []
    for relation in relation_rows:
        ring = relation.base_ring()
        for divided_degree in range(1, degree + 1):
            gamma_terms = []
            for exponent in _free_degree_labels(rank, divided_degree, "divided"):
                coefficient = ring.one()
                for scalar, power in zip(relation, exponent, strict=True):
                    coefficient *= scalar**power
                if coefficient:
                    gamma_terms.append((exponent, coefficient))
            if not gamma_terms:
                continue
            for monomial in _free_degree_labels(
                rank, degree - divided_degree, "divided"
            ):
                row = [ring.zero()] * len(labels)
                for exponent, coefficient in gamma_terms:
                    target = tuple(
                        left + right
                        for left, right in zip(exponent, monomial, strict=True)
                    )
                    row[position[target]] += (
                        coefficient * _divided_product_coefficient(exponent, monomial)
                    )
                if any(row):
                    rows.append(row)
    return rows


def _presented_degree_power(module, degree: int, flavor: str):
    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
        FinitelyPresentedModule,
        _presentation_from_relation_rows,
        _presentation_matrix,
    )

    ring = owned_ring_view(module.base_ring())
    if degree == 0:
        from dzack_research.preamble.categories.modules.framed.finitely_generated.ring_as_module import (
            ring_as_module,
        )

        return ring_as_module(ring)
    if degree == 1:
        return module

    source_labels = tuple(module.module_generating_set())
    rank = len(source_labels)
    labels = _free_degree_labels(rank, degree, flavor)
    public_labels = finite_ordered_set(
        tuple(source_labels[index] for index in label)
        if flavor == "alternating"
        else label
        for label in labels
    )

    relations = tuple(_presentation_matrix(module).change_ring(engine_ring(ring)).rows())
    if flavor == "symmetric":
        rows = _symmetric_relation_rows(relations, rank, degree, labels)
    elif flavor == "alternating":
        rows = _alternating_relation_rows(relations, rank, degree, labels)
    elif flavor == "divided":
        rows = _divided_relation_rows(relations, rank, degree, labels)
    else:
        raise ValueError(f"unknown power flavor {flavor!r}")

    relation_matrix = (
        tensor.matrix(engine_ring(ring), rows)
        if rows
        else tensor.matrix(engine_ring(ring), 0, len(public_labels))
    )
    relation_labels = finite_ordered_set(range(len(rows)))
    presentation = _presentation_from_relation_rows(
        ring,
        public_labels,
        relation_labels,
        relation_matrix,
    )
    return FinitelyPresentedModule(presentation)


_MODULE_POWER_CACHE = {}


def _cached_module_power(flavor, module, degree):
    cached = _MODULE_POWER_CACHE.get((flavor, id(module), degree))
    if (
        cached is not None
        and getattr(cached, "_preamble_power_source_module", None) is module
        and getattr(cached, "_preamble_power_degree", None) == degree
        and getattr(cached, "_preamble_power_flavor", None) == flavor
    ):
        return cached
    return None


def _store_module_power(flavor, module, degree, result):
    result._preamble_power_source_module = module
    result._preamble_power_degree = degree
    result._preamble_power_flavor = flavor
    _MODULE_POWER_CACHE[(flavor, id(module), degree)] = result
    return result


def TensorPower(module, degree):
    r"""Return the selected iterated tensor power ``M^{\otimes degree}``."""
    degree = _degree(degree)
    if degree == 0:
        from dzack_research.preamble.categories.modules.framed.finitely_generated.ring_as_module import (
            ring_as_module,
        )

        return ring_as_module(module.base_ring())
    if degree == 1:
        return module
    cached = _cached_module_power("tensor", module, degree)
    if cached is not None:
        return cached
    from dzack_research.preamble.categories.abstract_categories import TensorProduct

    result = TensorProduct(TensorPower(module, degree - 1), module)
    result = refine(result, TensorPowerModules(module.base_ring()))
    return _store_module_power("tensor", module, degree, result)


def SymmetricPower(module, degree):
    r"""Return ``Sym^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree > 1:
        cached = _cached_module_power("symmetric", module, degree)
        if cached is not None:
            return cached
    result = _presented_degree_power(module, degree, "symmetric")
    if degree <= 1:
        return result
    result = refine(result, SymmetricPowerModules(module.base_ring()))
    return _store_module_power("symmetric", module, degree, result)


def AlternatingPower(module, degree):
    r"""Return ``Lambda^degree(module)`` from the selected module presentation."""
    degree = _degree(degree)
    if degree > 1:
        cached = _cached_module_power("alternating", module, degree)
        if cached is not None:
            return cached
    result = _presented_degree_power(module, degree, "alternating")
    if degree <= 1:
        return result
    result = refine(result, AlternatingPowerModules(module.base_ring()))
    return _store_module_power("alternating", module, degree, result)


def DividedPower(module, degree):
    r"""Return the divided power ``Gamma^degree(module)``.

    Degree two is the existing universal quadratic square; higher degrees use
    the same divided-power-ideal presentation.
    """
    degree = _degree(degree)
    if degree == 2:
        from dzack_research.preamble.categories.modules.quadratic_square import DividedSquare

        return DividedSquare(module)
    if degree > 1:
        cached = _cached_module_power("divided", module, degree)
        if cached is not None:
            return cached
    result = _presented_degree_power(module, degree, "divided")
    if degree <= 1:
        return result
    result = refine(result, DividedPowerModules(module.base_ring()))
    return _store_module_power("divided", module, degree, result)


def _flatten_tensor_label(label, degree: int):
    if degree == 1:
        return (label,)
    left, right = label
    return _flatten_tensor_label(left, degree - 1) + (right,)


def _nested_tensor_label(word):
    if not word:
        return 0
    result = word[0]
    for label in word[1:]:
        result = (result, label)
    return result


def tensor_power_permutation(module, degree, positions):
    r"""Return the permutation of tensor factors specified by ``positions``."""
    degree = _degree(degree)
    positions = tuple(int(position) for position in positions)
    if tuple(sorted(positions)) != tuple(range(degree)):
        raise ValueError("positions must be a permutation of the tensor slots")
    power = TensorPower(module, degree)
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    if degree == 0:
        return module_homset(power, power).identity()
    return module_homset(power, power)(
        lambda label: power.module_generator(
            _nested_tensor_label(
                tuple(_flatten_tensor_label(label, degree)[position] for position in positions)
            )
        )
    )


def _power_morphism(morphism, degree: int, flavor: str):
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
        module_homset,
    )

    degree = _degree(degree)
    constructors = {
        "symmetric": SymmetricPower,
        "alternating": AlternatingPower,
        "divided": DividedPower,
    }
    source = constructors[flavor](morphism.domain(), degree)
    target = constructors[flavor](morphism.codomain(), degree)
    if degree == 0:
        return module_homset(source, target).identity()
    if degree == 1:
        return morphism

    domain_labels = tuple(morphism.domain().module_generating_set())
    codomain_labels = tuple(morphism.codomain().module_generating_set())

    def image_of_source_label(source_label):
        if flavor == "alternating":
            word = tuple(source_label)
            result = {(): morphism.codomain().base_ring().one()}
            for source_generator_label in word:
                image = module_coefficients(
                    morphism(morphism.domain().module_generator(source_generator_label)),
                    morphism.codomain(),
                )
                next_result = {}
                for wedge, coefficient in result.items():
                    occupied = {codomain_labels.index(label) for label in wedge}
                    for target_label, scalar in image.items():
                        index = codomain_labels.index(target_label)
                        if index in occupied:
                            continue
                        sign = -1 if sum(other > index for other in occupied) % 2 else 1
                        new_word = tuple(
                            codomain_labels[position]
                            for position in sorted((*occupied, index))
                        )
                        next_result[new_word] = (
                            next_result.get(new_word, morphism.codomain().base_ring().zero())
                            + sign * coefficient * scalar
                        )
                result = next_result
            return target.linear_combination(result)

        exponent = tuple(source_label)
        # Start with the degree-zero divided/symmetric monomial.
        polynomial = {tuple(0 for _ in codomain_labels): morphism.codomain().base_ring().one()}
        for source_position, power in enumerate(exponent):
            if power == 0:
                continue
            image = module_coefficients(
                morphism(morphism.domain().module_generator(domain_labels[source_position])),
                morphism.codomain(),
            )
            for _ in range(power):
                next_polynomial = {}
                for old_exp, old_coefficient in polynomial.items():
                    for target_label, scalar in image.items():
                        target_position = codomain_labels.index(target_label)
                        new_exp = list(old_exp)
                        new_exp[target_position] += 1
                        new_exp = tuple(new_exp)
                        multiplier = 1
                        if flavor == "divided":
                            # Multiplication by gamma_1 contributes the new exponent.
                            multiplier = new_exp[target_position]
                        next_polynomial[new_exp] = (
                            next_polynomial.get(
                                new_exp, morphism.codomain().base_ring().zero()
                            )
                            + old_coefficient * scalar * multiplier
                        )
                polynomial = next_polynomial
            if flavor == "divided":
                # The source basis element is gamma_power(x), not x^power.
                from sage.arith.misc import factorial

                divisor = factorial(power)
                polynomial = {
                    label: coefficient / divisor
                    for label, coefficient in polynomial.items()
                }
        return target.linear_combination(polynomial)

    return module_homset(source, target)(image_of_source_label)


def symmetric_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "symmetric")


def alternating_power_morphism(morphism, degree):
    return _power_morphism(morphism, degree, "alternating")


def divided_power_morphism(morphism, degree):
    degree = _degree(degree)
    if degree == 2:
        from dzack_research.preamble.categories.modules.quadratic_square import (
            divided_square_morphism,
        )

        return divided_square_morphism(morphism)
    return _power_morphism(morphism, degree, "divided")


def divided_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous divided-power elements into ``Gamma^{a+b} M``."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = DividedPower(module, left_degree)
    source_right = DividedPower(module, right_degree)
    target = DividedPower(module, left_degree + right_degree)
    left_coefficients = module_coefficients(left, source_left)
    right_coefficients = module_coefficients(right, source_right)

    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    # Degree one uses the module's original labels rather than exponent tuples.
    source_labels = tuple(module.module_generating_set())

    def exponent_of(label, degree):
        if degree == 1:
            vector = [0] * len(source_labels)
            vector[source_labels.index(label)] = 1
            return tuple(vector)
        if degree == 2:
            # Live DividedSquare labels gamma2(i) and product(i,j).
            if label[0] == "gamma2":
                vector = [0] * len(source_labels)
                vector[source_labels.index(label[1])] = 2
                return tuple(vector)
            vector = [0] * len(source_labels)
            vector[source_labels.index(label[1])] = 1
            vector[source_labels.index(label[2])] = 1
            return tuple(vector)
        return tuple(label)

    def target_label(exponent):
        total_degree = left_degree + right_degree
        if total_degree == 1:
            return source_labels[exponent.index(1)]
        if total_degree == 2:
            occupied = [index for index, value in enumerate(exponent) if value]
            if len(occupied) == 1:
                return ("gamma2", source_labels[occupied[0]])
            return ("product", source_labels[occupied[0]], source_labels[occupied[1]])
        return tuple(exponent)

    result = {}
    for left_label, left_coefficient in left_coefficients.items():
        left_exponent = exponent_of(left_label, left_degree)
        for right_label, right_coefficient in right_coefficients.items():
            right_exponent = exponent_of(right_label, right_degree)
            exponent = tuple(
                a + b for a, b in zip(left_exponent, right_exponent, strict=True)
            )
            coefficient = (
                left_coefficient
                * right_coefficient
                * _divided_product_coefficient(left_exponent, right_exponent)
            )
            label = target_label(exponent)
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def alternating_power_product(module, left_degree, left, right_degree, right):
    r"""Multiply homogeneous exterior-power elements by the wedge product."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )

    left_degree = _degree(left_degree)
    right_degree = _degree(right_degree)
    source_left = AlternatingPower(module, left_degree)
    source_right = AlternatingPower(module, right_degree)
    target = AlternatingPower(module, left_degree + right_degree)
    left_coefficients = module_coefficients(left, source_left)
    right_coefficients = module_coefficients(right, source_right)
    if left_degree == 0:
        scalar = next(iter(left_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, right)
    if right_degree == 0:
        scalar = next(iter(right_coefficients.values()), module.base_ring().zero())
        return target.scalar_multiple(scalar, left)

    source_labels = tuple(module.module_generating_set())

    def word_of(label, degree):
        return (label,) if degree == 1 else tuple(label)

    result = {}
    for left_label, left_coefficient in left_coefficients.items():
        left_word = word_of(left_label, left_degree)
        left_positions = tuple(source_labels.index(label) for label in left_word)
        for right_label, right_coefficient in right_coefficients.items():
            right_word = word_of(right_label, right_degree)
            right_positions = tuple(source_labels.index(label) for label in right_word)
            if set(left_positions) & set(right_positions):
                continue
            inversions = sum(
                left_position > right_position
                for left_position in left_positions
                for right_position in right_positions
            )
            coefficient = left_coefficient * right_coefficient
            if inversions % 2:
                coefficient = -coefficient
            ordered_positions = tuple(sorted((*left_positions, *right_positions)))
            ordered_word = tuple(source_labels[position] for position in ordered_positions)
            label = ordered_word[0] if len(ordered_word) == 1 else ordered_word
            result[label] = result.get(label, module.base_ring().zero()) + coefficient
    return target.linear_combination(result)


def divided_power_element(module, degree, element):
    r"""Return ``gamma_degree(element)`` in ``Gamma^degree(module)``."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_coefficients,
    )

    degree = _degree(degree)
    if degree == 0:
        target = DividedPower(module, 0)
        return target.module_generator(0)
    if degree == 1:
        return element
    if degree == 2:
        return DividedPower(module, 2).quadratic(element)

    target = DividedPower(module, degree)
    coefficients = module_coefficients(element, module)
    labels = tuple(module.module_generating_set())
    result = {}
    for exponent in _free_degree_labels(len(labels), degree, "divided"):
        coefficient = module.base_ring().one()
        for label, power in zip(labels, exponent, strict=True):
            coefficient *= coefficients.get(label, module.base_ring().zero()) ** power
        if coefficient:
            result[tuple(exponent)] = coefficient
    return target.linear_combination(result)


def divided_power_invariant_inclusion(module, degree):
    r"""Return ``Gamma^n M -> M^{tensor n}`` as the symmetric orbit sum."""
    from itertools import permutations

    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    degree = _degree(degree)
    source = DividedPower(module, degree)
    target = TensorPower(module, degree)
    labels = tuple(module.module_generating_set())

    def invariant(source_label):
        if degree == 0:
            return target.module_generator(0)
        if degree == 1:
            return target.module_generator(source_label)
        if degree == 2:
            if source_label[0] == "gamma2":
                word = (source_label[1], source_label[1])
            else:
                word = (source_label[1], source_label[2])
        else:
            word = tuple(
                label
                for label, exponent in zip(labels, source_label, strict=True)
                for _ in range(int(exponent))
            )
        distinct = set(permutations(word))
        return sum(
            (target.module_generator(_nested_tensor_label(word_)) for word_ in distinct),
            target.zero(),
        )

    return module_homset(source, target)(invariant)


def tensor_power_polarization(module, degree):
    r"""Return ``M^{tensor n} -> Gamma^n M`` by divided-power multiplication."""
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        module_homset,
    )

    degree = _degree(degree)
    source = TensorPower(module, degree)
    target = DividedPower(module, degree)
    if degree == 0:
        return module_homset(source, target).identity()
    if degree == 1:
        return module_homset(source, target).identity()

    def polarized(source_label):
        word = _flatten_tensor_label(source_label, degree)
        result = divided_power_element(module, 1, module.module_generator(word[0]))
        current_degree = 1
        for label in word[1:]:
            result = divided_power_product(
                module,
                current_degree,
                result,
                1,
                module.module_generator(label),
            )
            current_degree += 1
        return result

    return module_homset(source, target)(polarized)


def divided_square_invariant_inclusion(module):
    return divided_power_invariant_inclusion(module, 2)


def tensor_square_polarization(module):
    return tensor_power_polarization(module, 2)


__all__ = [
    "AlternatingPower",
    "AlternatingPowerModules",
    "DividedPower",
    "DividedPowerModules",
    "SymmetricPower",
    "SymmetricPowerModules",
    "TensorPower",
    "TensorPowerModules",
    "alternating_power_morphism",
    "alternating_power_product",
    "divided_power_element",
    "divided_power_invariant_inclusion",
    "divided_power_morphism",
    "divided_power_product",
    "divided_square_invariant_inclusion",
    "symmetric_power_morphism",
    "tensor_power_permutation",
    "tensor_power_polarization",
    "tensor_square_polarization",
]
