r"""The divided square \(\Gamma^2(M)\), classifying quadratic maps."""

from itertools import combinations

from dzack_research.preamble.categories.rings import (
    OwnedCategoryOverBaseRing,
    engine_ring,
    owned_ring_view,
)
from dzack_research.preamble.categories.sets import finite_ordered_set
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors import tensor


class DividedSquareModules(OwnedCategoryOverBaseRing):
    r"""Chosen divided squares of finitely presented modules."""

    @classmethod
    def _repr_object_names(cls):
        return "divided squares of finitely presented modules"

    def super_categories(self):
        from dzack_research.preamble.categories.modules import FinitelyPresentedModules

        return [FinitelyPresentedModules(self.base_ring())]

    class ParentMethods:
        def divided_square_source(self):
            return self._preamble_divided_square_source

        def quadratic(self, element):
            r"""Return the universal quadratic value \(\gamma_2(element)\)."""
            source = self.divided_square_source()
            from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
                module_coefficients,
            )

            coefficients = module_coefficients(element, source)
            labels = tuple(source.module_generating_set())
            values = {
                ("gamma2", label): coefficient * coefficient
                for label, coefficient in coefficients.items()
                if coefficient
            }
            for left, right in combinations(labels, 2):
                coefficient = coefficients.get(left, source.base_ring().zero()) * coefficients.get(
                    right, source.base_ring().zero()
                )
                if coefficient:
                    values[("product", left, right)] = coefficient
            return self.linear_combination(values)

        def polar(self, left, right):
            r"""Return \(\gamma_2(x+y)-\gamma_2(x)-\gamma_2(y)\)."""
            return self.quadratic(left + right) - self.quadratic(left) - self.quadratic(right)

        def from_quadratic(self, quadratic, codomain):
            r"""Factor a quadratic map uniquely through the divided square.

            ``quadratic`` is evaluated on the selected generators and their
            pairwise sums.  The resulting linear map is checked against the
            divided-square presentation by the ordinary module Hom
            constructor, so a function that does not descend to a quadratic
            map on the presented module is rejected.
            """
            source = self.divided_square_source()
            labels = tuple(source.module_generating_set())
            values = {
                ("gamma2", label): quadratic(source.module_generator(label))
                for label in labels
            }
            values.update(
                {
                    ("product", left, right): (
                        quadratic(
                            source.module_generator(left)
                            + source.module_generator(right)
                        )
                        - quadratic(source.module_generator(left))
                        - quadratic(source.module_generator(right))
                    )
                    for left, right in combinations(labels, 2)
                }
            )
            from dzack_research.preamble.categories.modules import module_homset

            return module_homset(self, codomain)(values)


_DIVIDED_SQUARE_CACHE = {}


def DividedSquare(module):
    r"""Return \(\Gamma^2_R(M)\), the universal target for quadratic maps.

    If ``M = F/K`` with selected generators ``e_i``, ``Gamma^2(F)`` has
    generators ``gamma_2(e_i)`` and ``e_i e_j`` for ``i<j``.  The divided
    power ideal generated by each relation ``r in K`` contributes the degree
    two relations ``gamma_2(r)=0`` and ``r e_j=0``.  This presentation works
    integrally; in particular it does not divide by two.
    """
    cache_key = id(module)
    cached = _DIVIDED_SQUARE_CACHE.get(cache_key)
    if cached is not None and cached.divided_square_source() is module:
        return cached

    ring = owned_ring_view(module.base_ring())
    from dzack_research.preamble.categories.modules.framed.finitely_generated.finitely_presented_modules import (
        FinitelyPresentedModule,
        _presentation_from_relation_rows,
        _presentation_matrix,
    )

    labels = tuple(module.module_generating_set())
    square_labels = finite_ordered_set(
        [("gamma2", label) for label in labels]
        + [("product", left, right) for left, right in combinations(labels, 2)]
    )
    positions = {label: index for index, label in enumerate(square_labels)}
    source_relations = _presentation_matrix(module).change_ring(engine_ring(ring))
    rows = []
    relation_labels = []
    zero = engine_ring(ring).zero()

    for relation_index, relation in enumerate(source_relations.rows()):
        gamma_row = [zero] * len(square_labels)
        for index, label in enumerate(labels):
            coefficient = relation[index]
            if coefficient:
                gamma_row[positions[("gamma2", label)]] += coefficient * coefficient
        for left_index, right_index in combinations(range(len(labels)), 2):
            coefficient = relation[left_index] * relation[right_index]
            if coefficient:
                gamma_row[
                    positions[("product", labels[left_index], labels[right_index])]
                ] += coefficient
        rows.append(gamma_row)
        relation_labels.append(("gamma2 relation", relation_index))

        for right_index, right_label in enumerate(labels):
            product_row = [zero] * len(square_labels)
            for left_index, left_label in enumerate(labels):
                coefficient = relation[left_index]
                if not coefficient:
                    continue
                if left_index == right_index:
                    product_row[positions[("gamma2", right_label)]] += 2 * coefficient
                elif left_index < right_index:
                    product_row[
                        positions[("product", left_label, right_label)]
                    ] += coefficient
                else:
                    product_row[
                        positions[("product", right_label, left_label)]
                    ] += coefficient
            rows.append(product_row)
            relation_labels.append(("product relation", relation_index, right_label))

    relations = (
        tensor.matrix(engine_ring(ring), rows)
        if rows
        else tensor.matrix(engine_ring(ring), 0, len(square_labels))
    )
    presentation = _presentation_from_relation_rows(
        ring,
        square_labels,
        finite_ordered_set(relation_labels),
        relations,
    )
    result = FinitelyPresentedModule(presentation)
    result._preamble_divided_square_source = module
    result = refine(result, DividedSquareModules(ring))
    _DIVIDED_SQUARE_CACHE[cache_key] = result
    return result


QuadraticSquare = DividedSquare


def divided_square_morphism(morphism, source=None, target=None):
    r"""Return \(\Gamma^2(f)\) for a module morphism ``f``."""
    if source is None:
        source = DividedSquare(morphism.domain())
    if target is None:
        target = DividedSquare(morphism.codomain())
    if source.divided_square_source() is not morphism.domain():
        raise ValueError("the source divided square has the wrong module")
    if target.divided_square_source() is not morphism.codomain():
        raise ValueError("the target divided square has the wrong module")
    from dzack_research.preamble.categories.modules import module_homset

    domain = morphism.domain()
    labels = tuple(domain.module_generating_set())
    images = {
        ("gamma2", label): target.quadratic(
            morphism(domain.module_generator(label))
        )
        for label in labels
    }
    images.update(
        {
            ("product", left, right): target.polar(
                morphism(domain.module_generator(left)),
                morphism(domain.module_generator(right)),
            )
            for left, right in combinations(labels, 2)
        }
    )
    return module_homset(source, target)(images)


__all__ = [
    "DividedSquare",
    "DividedSquareModules",
    "QuadraticSquare",
    "divided_square_morphism",
]
