# Repo-scoped stubs; see lexicon/README.md.
#
# The PARI library instance of cypari2 2.2.4 (cypari2/pari_instance.pyx),
# with the members that this repository calls. Each signature is the one that
# `inspect.signature` reports for the installed module.
from cypari2.gen import Gen, PariInput

class Pari:
    def __init__(self, size: int = 8000000, sizemax: int = 0, maxprime: int = 500000) -> None: ...
    def __call__(self, s: PariInput) -> Gen: ...
    def coredisc(self, n: PariInput, flag: int = 0) -> Gen: ...
    def factor(self, x: PariInput, D: PariInput | None = None) -> Gen: ...
    def matdiagonal(self, x: PariInput) -> Gen: ...
    def matrix(self, m: int, n: int, entries: PariInput | None = None) -> Gen: ...
    def partitions(self, k: PariInput, a: PariInput | None = None, n: PariInput | None = None) -> Gen: ...
