r"""Morphisms of modules with generating sets.

Their own layer, because a morphism is not an accessory of the object it
happens to be built for: cokernels are presented by one, forms are pulled back
along one, subobjects are one, and the numerical work of this universe belongs
here rather than in any of them.  Objects hold generators and relations and
answer questions about themselves; morphisms are where coordinates, matrices
and linear systems live, so that there is one place to read when asking whether
a computation is the mathematics it claims to be.

A morphism is an assignment on the domain's generators.  What its matrix means,
and which matrix operations are legitimate, depends on which of three cases it
is in:

**free to free.**  The matrix is the morphism, entry for entry; ordinary
integer linear algebra applies, and this is where most of it is quarantined.

**free to torsion.**  The assignment still determines the map, but the matrix
does not determine its entries: a row is the image's coordinates in generators
of orders $d_1,\dots,d_n$, so the $i$-th column is defined only modulo $d_i$.
Operations that mix columns -- inversion, a determinant, a transpose fed back
in -- are not operations on the morphism, and a value read off such a product
is not a value of anything.  What survives is what is invariant under changing
each column by its own $d_i$.

**torsion to torsion.**  As above, and the domain is presented too, so an
assignment is a morphism only if it kills the relations.  That is a condition
on the assignment, checked where the assignment is made.
"""

from typing import Any

from sage.matrix.matrix0 import Matrix
from sage.modules.free_module_element import FreeModuleElement
from sage.structure.element import Vector


def _coordinate_vector(element: Any) -> FreeModuleElement:
    r"""Return ``element``'s coordinates in its own module's generating set.

    Three owned cases and no fourth: an element of a form module reports its
    coordinates, a class in a quotient reports its canonical lift, and a vector
    is already a coordinate vector -- which is the only reason a free module's
    element needs no unwrapping.  Anything else has no generating set to be
    coordinates in, and guessing by which methods it happens to answer to is
    how a foreign object gets read as though it were one of ours.
    """
    if isinstance(element, FormModuleElement):
        return element._coordinates()
    if isinstance(element, TorsionModuleElement):
        return vector(element._lift())
    assert isinstance(element, Vector), (
        f"{element} is a {type(element).__name__}, which has no generating set "
        "for its entries to be coordinates in"
    )
    return vector(element)


class ModuleMorphism:
    r"""$f: A\to B$, given as $\{a_i\mapsto f(a_i)\}$ on $A$'s generators.

    A map out of a module generated by $\{a_i\}$ is exactly that assignment, so
    the assignment is the datum and nothing else has to be supplied: $A$ is
    where the generators live and $B$ is where the images live, both read off
    the elements themselves.  The matrix -- the images' coordinates, one per
    row -- is a reading of the morphism, which is what algorithms that want
    coordinates call for.
    """

    def __init__(self, assignment: dict) -> None:
        assert assignment, "a morphism needs its values on the generators"
        sources = tuple(assignment)
        domain = sources[0].parent()
        codomain = next(iter(assignment.values())).parent()
        assert all(source.parent() is domain for source in sources), (
            "the generators assigned come from more than one module"
        )
        assert all(image.parent() is codomain for image in assignment.values()), (
            "the images land in more than one module"
        )
        generators = tuple(domain.gens())
        assert set(sources) == set(generators), (
            f"a map out of this module is an assignment on all {len(generators)} "
            f"of its generators, got {len(sources)}"
        )
        self._domain = domain
        self._codomain = codomain
        self._assignment = dict(assignment)

    def domain(self) -> Any:
        return self._domain

    def codomain(self) -> Any:
        return self._codomain

    def images(self) -> tuple:
        r"""Return $f$ on the generators, one per generator of the domain.

        Looked up rather than listed, because a generating set can repeat an
        element -- the five generators of $A_5$'s $2$-primary part span $\mathbb
        Z/2$ -- and then the assignment has fewer entries than the module has
        generators while still saying where each one goes.
        """
        return tuple(
            self._assignment[generator] for generator in self._domain.gens()
        )

    def matrix(self) -> Matrix:
        r"""Return the images' coordinates, one row per generator of the domain."""
        return matrix([_coordinate_vector(image) for image in self.images()])

    def __call__(self, x: Any) -> Any:
        r"""Return $f(x)=\sum_i a_i f(g_i)$ for $x=\sum_i a_i g_i$.

        The definition rather than a matrix product read into the codomain:
        the coefficients are $x$'s, asked of $x$, and what they multiply are
        the images, which are already elements of the codomain.  So nothing
        here has to be interpreted as belonging anywhere -- the arithmetic is
        the codomain's own.
        """
        assert x.parent() is self._domain, (
            f"{x} belongs to {x.parent()}, and this morphism is defined on "
            f"{self._domain}"
        )
        total = self._codomain.zero()
        for coefficient, image in zip(_coordinate_vector(x), self.images()):
            total += coefficient * image
        return total

    def lift(self, y: Any) -> Any:
        r"""Return an $x$ in the domain with $f(x)=y$, or fail because there is none.

        The one place a preimage is computed.  Writing $x=\sum_ia_ig_i$, the
        equation $f(x)=y$ says $aM=t$ *in the codomain*, and what that means is
        the case distinction of this module:

        - a free codomain makes it the integer system $aM=t$;
        - a torsion codomain makes it $aM\equiv t$ modulo the relations, which
          is the integer system $aM+zR=t$ in the unknowns $(a,z)$.

        Both are solved by the same routine below, the second by stacking $R$,
        and neither by a rule about which representative is canonical.  A
        canonical representative is a fact about printing and equality; that it
        also happens to be a preimage is a theorem, and one this code should
        not be quietly asserting -- so the answer here is whatever solves the
        system, and the assertion at the end is what makes it checkable.

        A choice, not a map.  $f$ being surjective does not split it, so
        nothing here is natural in $y$: two calls may legitimately differ, and
        anything computed from a lift that is not invariant under changing it
        depends on this computation and not on $y$ alone.
        """
        assert y.parent() is self._codomain, (
            f"{y} lies in {y.parent()}, and this morphism lands in "
            f"{self._codomain}"
        )
        system = self.matrix()
        relations = self._codomain_relations()
        coefficients = _solve_left_integrally(
            system.stack(relations) if relations.nrows() else system,
            _coordinate_vector(y),
        )
        x = _combination(self._domain, coefficients[: system.nrows()])
        assert self(x) == y, (
            f"{y} is not in the image of this morphism: the system is solved "
            f"by {x}, whose image is {self(x)}"
        )
        return x

    def _codomain_relations(self) -> Matrix:
        r"""Return the codomain's relations, or no rows when it is free.

        Which of the three cases this morphism is in, asked of the codomain.
        """
        codomain = self._codomain
        module = codomain.forget_form() if isinstance(codomain, FormModule) else codomain
        if isinstance(module, TorsionModule):
            return module.relation_matrix()
        return matrix(ZZ, 0, len(tuple(codomain.gens())))

    def __repr__(self) -> str:
        return (
            f"Module morphism on {len(self._assignment)} generators into "
            f"{self._codomain}"
        )


def _combination(module: Any, coefficients: Any) -> Any:
    r"""Return $\sum_i a_ig_i$ over ``module``'s generators.

    Written out rather than delegated to the object, because not every module a
    morphism can start from is one of ours: Sage's own ``linear_combination``
    takes pairs, so calling it here with a coefficient vector would mean
    something else entirely on a lattice.  Adding and scaling generators is a
    thing every module does the same way.
    """
    generators = tuple(module.gens())
    coefficients = tuple(coefficients)
    assert len(coefficients) == len(generators), (
        f"{module} has {len(generators)} generators, got {len(coefficients)} "
        "coefficients"
    )
    total = module.zero()
    for coefficient, generator in zip(coefficients, generators):
        total += module.base_ring()(coefficient) * generator
    return total


def _solve_left_integrally(system: Matrix, target: Any) -> Any:
    r"""Return an integral $a$ with $aS=t$, or fail because there is none.

    Smith form: with $D=US^{\mathsf T}V$ diagonal, $S^{\mathsf T}a=t$ becomes
    $Dw=Ut$ for $w=V^{-1}a$, which is one exact division per row.  Exactness is
    the point -- a rational solve answers a different question, and over
    $\mathbb Z$ the difference between "solvable" and "solvable after clearing
    a denominator" is the whole content.
    """
    smith, left, right = system.transpose().smith_form()
    shifted = left * vector(ZZ, target)
    width = smith.ncols()
    solution = [ZZ.zero()] * width
    for i, value in enumerate(shifted):
        divisor = smith[i, i] if i < width else ZZ.zero()
        assert divisor != 0 or value == 0, (
            f"no solution: row {i} of the system is zero but asks for {value}"
        )
        if divisor != 0:
            assert value % divisor == 0, (
                f"no integral solution: row {i} asks for {value}/{divisor}, "
                "which solves over Q and not over Z"
            )
            solution[i] = value // divisor
    return right * vector(ZZ, solution)
