r"""Lazy public aggregation for the owned abstract-category vocabulary.

The defining modules must remain independently importable.  Python executes a
package ``__init__`` before any submodule, so eager re-exports here create
artificial defining-module cycles.  Public names are resolved lazily instead.
"""

from importlib import import_module as _import_module

_EXPORTS = {
    "FunctorImageForgetfulFunctor": ("dzack_research.preamble.categories.abstract_categories.functor_images", "FunctorImageForgetfulFunctor"),
    "FunctorImageMorphism": ("dzack_research.preamble.categories.abstract_categories.functor_images", "FunctorImageMorphism"),
    "ImageOfFunctor": ("dzack_research.preamble.categories.abstract_categories.functor_images", "ImageOfFunctor"),
    "DirectSumDecomposition": ("dzack_research.preamble.categories.abstract_categories.direct_sum_objects", "DirectSumDecomposition"),
    "DirectSumObjects": ("dzack_research.preamble.categories.abstract_categories.direct_sum_objects", "DirectSumObjects"),
    "BiproductCategory": ("dzack_research.preamble.categories.abstract_categories.products", "BiproductCategory"),
    "Cocone": ("dzack_research.preamble.categories.abstract_categories.products", "Cocone"),
    "CoconeCategory": ("dzack_research.preamble.categories.abstract_categories.products", "CoconeCategory"),
    "ColimitsOfCategory": ("dzack_research.preamble.categories.abstract_categories.products", "ColimitsOfCategory"),
    "Cone": ("dzack_research.preamble.categories.abstract_categories.products", "Cone"),
    "ConeCategory": ("dzack_research.preamble.categories.abstract_categories.products", "ConeCategory"),
    "CoproductCoconeCategory": ("dzack_research.preamble.categories.abstract_categories.products", "CoproductCoconeCategory"),
    "CoproductsOfCategory": ("dzack_research.preamble.categories.abstract_categories.products", "CoproductsOfCategory"),
    "DiagramCategory": ("dzack_research.preamble.categories.abstract_categories.products", "DiagramCategory"),
    "DirectSumCategory": ("dzack_research.preamble.categories.abstract_categories.products", "DirectSumCategory"),
    "DirectedSystem": ("dzack_research.preamble.categories.abstract_categories.products", "DirectedSystem"),
    "FiniteOrdinalCategory": ("dzack_research.preamble.categories.abstract_categories.products", "FiniteOrdinalCategory"),
    "FiniteSequenceDiagram": ("dzack_research.preamble.categories.abstract_categories.products", "FiniteSequenceDiagram"),
    "InverseSystem": ("dzack_research.preamble.categories.abstract_categories.products", "InverseSystem"),
    "LimitsOfCategory": ("dzack_research.preamble.categories.abstract_categories.products", "LimitsOfCategory"),
    "ParallelPairCategory": ("dzack_research.preamble.categories.abstract_categories.products", "ParallelPairCategory"),
    "ParallelPairDiagram": ("dzack_research.preamble.categories.abstract_categories.products", "ParallelPairDiagram"),
    "PosetCategory": ("dzack_research.preamble.categories.abstract_categories.products", "PosetCategory"),
    "ProductConeCategory": ("dzack_research.preamble.categories.abstract_categories.products", "ProductConeCategory"),
    "ProductsOfCategory": ("dzack_research.preamble.categories.abstract_categories.products", "ProductsOfCategory"),
    "RestrictedDiagram": ("dzack_research.preamble.categories.abstract_categories.products", "RestrictedDiagram"),
    "SelectedColimitConstruction": ("dzack_research.preamble.categories.abstract_categories.products", "SelectedColimitConstruction"),
    "SelectedLimitConstruction": ("dzack_research.preamble.categories.abstract_categories.products", "SelectedLimitConstruction"),
    "Span": ("dzack_research.preamble.categories.abstract_categories.products", "Span"),
    "SpanCategory": ("dzack_research.preamble.categories.abstract_categories.products", "SpanCategory"),
    "TensorProductCategory": ("dzack_research.preamble.categories.abstract_categories.products", "TensorProductCategory"),
    "common_category_of": ("dzack_research.preamble.categories.abstract_categories.products", "common_category_of"),
    "coproduct_cocone_category": ("dzack_research.preamble.categories.abstract_categories.products", "coproduct_cocone_category"),
    "product_cone_category": ("dzack_research.preamble.categories.abstract_categories.products", "product_cone_category"),
    "restrict_diagram": ("dzack_research.preamble.categories.abstract_categories.products", "restrict_diagram"),
    "Cat": ("dzack_research.preamble.categories.abstract_categories.cat", "Cat"),
    "CategoryFunctorMorphism": ("dzack_research.preamble.categories.abstract_categories.cat", "CategoryFunctorMorphism"),
    "CategoryObject": ("dzack_research.preamble.categories.abstract_categories.cat", "CategoryObject"),
    "FunctorCategory": ("dzack_research.preamble.categories.abstract_categories.cat", "FunctorCategory"),
    "NaturalTransformationMorphism": ("dzack_research.preamble.categories.abstract_categories.cat", "NaturalTransformationMorphism"),
    "AutCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "AutCategoryConstruction"),
    "AutCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "AutCategoryOf"),
    "CategoricalHomset": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "CategoricalHomset"),
    "CategoryPacket": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "CategoryPacket"),
    "CategoryPacketMethods": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "CategoryPacketMethods"),
    "EndCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "EndCategoryConstruction"),
    "EndCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "EndCategoryOf"),
    "EpiCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "EpiCategoryConstruction"),
    "EpiCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "EpiCategoryOf"),
    "HomCategories": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "HomCategories"),
    "HomCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "HomCategoryConstruction"),
    "HomCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "HomCategoryOf"),
    "IsoCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "IsoCategoryConstruction"),
    "IsoCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "IsoCategoryOf"),
    "MonoCategoryConstruction": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "MonoCategoryConstruction"),
    "MonoCategoryOf": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "MonoCategoryOf"),
    "category_packet": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "category_packet"),
    "common_category": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "common_category"),
    "Isomorphism": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "Isomorphism"),
    "IsoArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "IsoArrowCategory"),
    "EndArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "EndArrowCategory"),
    "AutomorphismArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "AutomorphismArrowCategory"),
    "EndofunctorAlgebras": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "EndofunctorAlgebras"),
    "OppositeMorphism": ("dzack_research.preamble.categories.abstract_categories.category_constructions", "OppositeMorphism"),
    "ProductMorphism": ("dzack_research.preamble.categories.abstract_categories.category_constructions", "ProductMorphism"),
    "ArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "ArrowCategory"),
    "CategoricalIsomorphism": ("dzack_research.preamble.categories.abstract_categories.hom_categories", "CategoricalIsomorphism"),
    "CommutativeSquare": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "CommutativeSquare"),
    "CoreCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "CoreCategory"),
    "CosliceCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "CosliceCategory"),
    "CoveredObjectCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "CoveredObjectCategory"),
    "CoveringObjectCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "CoveringObjectCategory"),
    "EpimorphismArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "EpimorphismArrowCategory"),
    "MonomorphismArrowCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "MonomorphismArrowCategory"),
    "SliceCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "SliceCategory"),
    "SubobjectCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "SubobjectCategory"),
    "SubobjectHomset": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "SubobjectHomset"),
    "SubobjectMorphism": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "SubobjectMorphism"),
    "SuperobjectCategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "SuperobjectCategory"),
    "WideSubcategory": ("dzack_research.preamble.categories.abstract_categories.arrow_categories", "WideSubcategory"),
}

__all__ = [
    "FunctorImageForgetfulFunctor",
    "FunctorImageMorphism",
    "ImageOfFunctor",
    "DirectSumDecomposition",
    "DirectSumObjects",
    "BiproductCategory",
    "Cocone",
    "CoconeCategory",
    "ColimitsOfCategory",
    "Cone",
    "ConeCategory",
    "CoproductCoconeCategory",
    "CoproductsOfCategory",
    "DiagramCategory",
    "DirectSumCategory",
    "DirectedSystem",
    "FiniteOrdinalCategory",
    "FiniteSequenceDiagram",
    "InverseSystem",
    "LimitsOfCategory",
    "ParallelPairCategory",
    "ParallelPairDiagram",
    "PosetCategory",
    "ProductConeCategory",
    "ProductsOfCategory",
    "RestrictedDiagram",
    "SelectedColimitConstruction",
    "SelectedLimitConstruction",
    "Span",
    "SpanCategory",
    "TensorProductCategory",
    "common_category_of",
    "coproduct_cocone_category",
    "product_cone_category",
    "restrict_diagram",
    "Cat",
    "CategoryFunctorMorphism",
    "CategoryObject",
    "FunctorCategory",
    "NaturalTransformationMorphism",
    "AutCategoryConstruction",
    "AutCategoryOf",
    "CategoricalHomset",
    "CategoryPacket",
    "CategoryPacketMethods",
    "EndCategoryConstruction",
    "EndCategoryOf",
    "EpiCategoryConstruction",
    "EpiCategoryOf",
    "HomCategories",
    "HomCategoryConstruction",
    "HomCategoryOf",
    "IsoCategoryConstruction",
    "IsoCategoryOf",
    "MonoCategoryConstruction",
    "MonoCategoryOf",
    "category_packet",
    "common_category",
    "Isomorphism",
    "IsoArrowCategory",
    "EndArrowCategory",
    "AutomorphismArrowCategory",
    "EndofunctorAlgebras",
    "OppositeMorphism",
    "ProductMorphism",
    "ArrowCategory",
    "CategoricalIsomorphism",
    "CommutativeSquare",
    "CoreCategory",
    "CosliceCategory",
    "CoveredObjectCategory",
    "CoveringObjectCategory",
    "EpimorphismArrowCategory",
    "MonomorphismArrowCategory",
    "SliceCategory",
    "SubobjectCategory",
    "SubobjectHomset",
    "SubobjectMorphism",
    "SuperobjectCategory",
    "WideSubcategory",
]


def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    value = getattr(_import_module(module_name), attribute)
    globals()[name] = value
    return value


def __dir__():
    return sorted((*globals(), *__all__))
