from dzack_research.preamble.all import *

VERTICES = [[0, 0], [1, 0], [0, 1]]


def lattice():
    return ZZ ^ 2


def triangle():
    r"""$\operatorname{conv}\{0, e_1, e_2\} \subset \mathbb R^2$ with vertices in $\mathbb Z^2$."""
    return ConvexPolytopes(lattice())(VERTICES)


def test_the_order_of_the_vertices_does_not_matter() -> None:
    assert ConvexPolytopes(lattice())([[1, 0], [0, 1], [0, 0]]) == triangle()


def test_the_categories_of_the_triangle() -> None:
    polytope = triangle()
    assert polytope in ConvexPolytopes(lattice())
    assert polytope in ConvexPolygons(lattice())
    assert polytope in LatticePolytopes(lattice())
    assert polytope in LatticePolygons(lattice())


def test_the_invariants_of_the_triangle() -> None:
    polytope = triangle()
    assert polytope.dimension() == 2
    assert polytope.n_vertices() == 3
    assert polytope.facets().cardinality() == 3
    assert polytope.volume() == 1/2
    assert polytope.normalized_volume() == 1
    assert polytope.is_lattice_polytope()


def test_the_lattice_points_of_the_triangle() -> None:
    r"""The three vertices are all its lattice points, all on the boundary; Pick: $A = i + b/2 - 1 = 0 + 3/2 - 1$."""
    polytope = triangle()
    assert polytope.n_integral_points() == 3
    assert polytope.n_interior_points() == 0
    assert polytope.n_boundary_points() == 3
    assert polytope.contains_point([0, 0])
    assert not polytope.contains_point([1, 1])


def test_the_ehrhart_polynomial_of_the_triangle() -> None:
    r"""$|t\Delta \cap \mathbb Z^2| = \binom{t+2}{2}$: $6$ points in $2\Delta$."""
    assert triangle().ehrhart_polynomial()(2) == 6


def test_the_triangle_is_smooth_and_not_reflexive() -> None:
    r"""Each vertex cone is generated by a basis of $\mathbb Z^2$; the origin is not interior, so not reflexive."""
    polytope = triangle()
    assert polytope.is_smooth()
    assert not polytope.is_reflexive()


def test_the_toric_variety_of_the_triangle_is_the_projective_plane() -> None:
    assert triangle().toric_variety().is_isomorphic_to(ProjectiveSpaces(QQ)(2))
