from dzack_research.preamble.all import *


def galois():
    return AbsoluteGaloisGroup(GF(5))


def test_the_field_construction_agrees() -> None:
    assert GF(5).absolute_galois_group() == galois()


def test_the_categories_of_the_absolute_galois_group() -> None:
    group = galois()
    assert group in Groups()
    assert group in ProfiniteGroups()
    assert group in AbsoluteGaloisGroups()
    assert group in AbsoluteGaloisGroupsOfFiniteFields()


def test_the_absolute_galois_group_of_a_finite_field_is_zhat() -> None:
    r"""$\operatorname{Gal}(\overline{\mathbb F}_5/\mathbb F_5) \cong \hat{\mathbb Z}$, topologically generated by Frobenius;
    $|\hat{\mathbb Z}| = |\prod_p \mathbb Z_p| = 2^{\aleph_0}$."""
    group = galois()
    assert group.is_profinite()
    assert group.is_abelian()
    assert not group.is_finite()
    assert group.cardinality() == continuum
    assert group.topological_group_generators().cardinality() == 1
    assert group.characteristic() == 5


def test_frobenius() -> None:
    group = galois()
    frobenius = group.frobenius()
    assert frobenius in group
    assert frobenius != group.one()
    assert frobenius * frobenius.inverse() == group.one()


def test_the_finite_quotients() -> None:
    r"""The open subgroup $3\hat{\mathbb Z}$ fixes $\mathbb F_{125}$."""
    assert galois().finite_extension(3).cardinality() == 125


def test_the_absolute_galois_group_has_one_endomorphism_category() -> None:
    group = galois()
    endomorphisms = group.Mor(group)
    identity = endomorphisms.identity()
    assert endomorphisms in Cat()
    assert group.Mor(group) is endomorphisms
    assert identity * identity == identity
