r"""The affine algebraic de Rham functor and its degree-zero adjunction."""
from sage.misc.cachefunc import cached_function

from dzack_research.preamble.categories.algebras.algebras import (
    Algebras,
)
from dzack_research.preamble.categories.algebras.differential_graded_algebras import (
    DifferentialGradedAlgebras,
)
from dzack_research.preamble.categories.functors.core import Adjunction, Functor
from dzack_research.preamble.categories.rings.ring_foundation import _owned_ring


def _exterior_word(label, degree):
    if degree == 0:
        return ()
    if degree == 1:
        return (label,)
    return tuple(label)


def _extend_degree_zero_map(source_dga, target_dga, algebra_morphism):
    r"""Extend ``A -> B^0`` uniquely to ``DR(A) -> B`` on the live algebras."""
    source_algebra = source_dga.de_rham_source_algebra()
    if algebra_morphism.domain() is not source_algebra:
        raise ValueError("the degree-zero map has the wrong de Rham source")
    if algebra_morphism.codomain() is not target_dga.degree_zero_algebra():
        raise ValueError("the degree-zero map must land in the target DGA's degree zero")

    source_exterior = source_dga.extension_algebra()

    def image(element):
        represented = source_dga.realize(element)
        result = target_dga.zero()
        for degree, component in represented.homogeneous_components().items():
            source_piece = source_exterior.graded_piece(degree)
            for label, coefficient in source_piece.framing_coefficients(component).items():
                coefficient_image = target_dga.from_degree_zero(
                    algebra_morphism(source_algebra(coefficient))
                )
                term = coefficient_image
                for differential_label in _exterior_word(label, degree):
                    # The Kähler differential module frames ``da`` by the
                    # label ``("d", a)`` (``KahlerDifferentialModules
                    # .differential_generator``); read ``a`` from that datum.
                    match differential_label:
                        case ("d", generator_label):
                            source_generator = source_algebra.algebra_generator(
                                generator_label
                            )
                        case _:
                            raise ValueError(
                                "the represented de Rham exterior basis is not generated by Kähler differentials"
                            )
                    mapped_generator = target_dga.from_degree_zero(
                        algebra_morphism(source_generator)
                    )
                    term *= target_dga.d(mapped_generator)
                result += term
        return result

    return DifferentialGradedAlgebras(source_dga.base_ring()).Mor(
        source_dga,
        target_dga,
    )(image)


class _DeRhamFunctor(Functor):
    r"""``DR_R : CAlg_R -> SCDGA_R^{>=0}`` on represented affine algebras."""

    def __init__(self, base_ring) -> None:
        self._base_ring = _owned_ring(base_ring)
        super().__init__(
            Algebras(self._base_ring).Associative().Unital().Commutative(),
            DifferentialGradedAlgebras(self._base_ring).Supercommutative().Alternating(),
        )

    def base_ring(self):
        return self._base_ring

    def _apply_object(self, algebra):
        return algebra.de_rham_algebra()

    def _apply_morphism(self, morphism):
        source = self(morphism.domain())
        target = self(morphism.codomain())
        return _extend_degree_zero_map(source, target, morphism)

    def _repr_(self):
        return f"Algebraic de Rham functor over {self.base_ring()}"


class _DegreeZeroDGAFunctor(Functor):
    r"""Degree zero ``(-)^0 : SCDGA_R^{>=0} -> CAlg_R``."""

    def __init__(self, base_ring) -> None:
        self._base_ring = _owned_ring(base_ring)
        super().__init__(
            DifferentialGradedAlgebras(self._base_ring).Supercommutative().Alternating(),
            Algebras(self._base_ring).Associative().Unital().Commutative(),
        )

    def base_ring(self):
        return self._base_ring

    def _apply_object(self, dga):
        r"""Read the degree-zero algebra at its DGA owner, without restricting to de Rham images."""
        return dga.degree_zero_algebra()

    def _apply_morphism(self, morphism):
        source_dga = morphism.domain()
        target_dga = morphism.codomain()
        source = self(source_dga)
        target = self(target_dga)
        return Algebras(source.base_ring()).Associative().Unital().Mor(source, target)(
            {
                label: target_dga.degree_zero_element(
                    morphism(
                        source_dga.from_degree_zero(source.algebra_generator(label))
                    )
                )
                for label in source.algebra_generating_set()
            }
        )

    def _repr_(self):
        return f"Degree-zero DGA functor over {self.base_ring()}"


class _DeRhamAdjunction(Adjunction):
    r"""The adjunction ``DR_R ⊣ (-)^0``.

    On the represented algebras the Hom-set bijection is the universal
    extension of an algebra map ``A -> B^0`` by ``da |-> d_B(a)``.
    """

    def __init__(self, base_ring) -> None:
        self._base_ring = _owned_ring(base_ring)
        super().__init__(_DeRhamFunctor(self._base_ring), _DegreeZeroDGAFunctor(self._base_ring))

    def base_ring(self):
        return self._base_ring

    def _unit_component(self, algebra):
        degree_zero = self.right_adjoint()(self.left_adjoint()(algebra))
        return Algebras(algebra.base_ring()).Associative().Unital().Mor(algebra, degree_zero)(
            {label: degree_zero.algebra_generator(label) for label in algebra.algebra_generating_set()}
        )

    def _counit_component(self, dga):
        degree_zero = self.right_adjoint()(dga)
        source = self.left_adjoint()(degree_zero)
        identity = Algebras(degree_zero.base_ring()).Associative().Unital().Mor(degree_zero, degree_zero).identity()
        return _extend_degree_zero_map(source, dga, identity)


    def _repr_(self):
        return f"Algebraic de Rham/degree-zero adjunction over {self.base_ring()}"


@cached_function
def _de_rham_functor(base_ring) -> _DeRhamFunctor:
    return _DeRhamFunctor(base_ring)


@cached_function
def _degree_zero_dga_functor(base_ring) -> _DegreeZeroDGAFunctor:
    return _DegreeZeroDGAFunctor(base_ring)


@cached_function
def _de_rham_adjunction(base_ring) -> _DeRhamAdjunction:
    return _DeRhamAdjunction(base_ring)


__all__ = []
