r"""``DefiniteLattices`` — integral lattices whose form is definite.

The category exists to carry what only a definite form supports: a length.
Its ``Subobjects`` axiom is where reduction lives, because reducing means
choosing shorter generators for a submodule, and that is a statement about an
inclusion rather than about a lattice on its own.

EXAMPLES::

    sage: from dzack_research.preamble import catalogue
    sage: from dzack_research.preamble.categories import DefiniteLattices
    sage: Lattices.E8 in DefiniteLattices()
    True
"""

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dzack_research.preamble.lexicon import Module

from typing import Protocol, TYPE_CHECKING

from sage.categories.category import Category
from sage.categories.subobjects import SubobjectsCategory
from sage.matrix.constructor import matrix
from sage.matrix.special import identity_matrix
from sage.rings.integer_ring import ZZ as SageZZ

if TYPE_CHECKING:
    from dzack_research.preamble.categories.modules.module_morphisms.module_morphisms import (
        ModuleMorphism,
    )

    class DefiniteSubobjectParent(Protocol):
        r"""What reduction asks of a subobject: its inclusion."""

        def embedding(self) -> "ModuleMorphism": ...


class DefiniteLattices(Category):
    r"""Category of definite integral lattices.

    Definite and not positive definite: this project writes the root lattices
    negative definite, so pinning the sign here would put $E_8$ outside the
    category that reduction is defined on.  The sign is read where it matters,
    which is at the standard target below.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "definite integral lattices"

    def super_categories(self) -> list:
        # Local: a module-level import here would close a cycle; by call time this module is built.
        from dzack_research.preamble.categories.modules.framed.formed.integrallattice.integral_lattices import IntegralLattices
        return [IntegralLattices()]

    class Subobjects(SubobjectsCategory):
        r"""Submodules of a definite lattice, framed by their inclusion."""

        class ParentMethods:
            def LLL(self: "DefiniteSubobjectParent") -> "Module":
                r"""Return this subobject on an LLL reduced framing.

                The same submodule of the same ambient, generated by shorter
                and more nearly orthogonal vectors.  What is reduced is the
                inclusion's matrix: its rows are the generators of $S$ written
                in the ambient's framing, so the arrow carries the reduction
                and no call site rebuilds an embedding out of rows it reduced
                itself.

                The target must be $I_{n,0}$ or $I_{0,n}$.  Reduction reads
                those rows as vectors and compares their lengths, which is
                only what they mean when the ambient's form is the standard
                one; over any other definite form the same rows are
                coordinates and their entries are not lengths.  $I_{0,n}$ is
                admitted because $S$ and $S(-1)$ have the same short vectors.
                """
                # Local: a module-level import here would close a cycle; by call time this module is built.
                from dzack_research.preamble.categories.modules.framed.formed.integrallattice.subobjects import Subobject
                from dzack_research.preamble.categories.sets.sets import finite_ordered_set
                from dzack_research.preamble.utilities import zipsum
                inclusion = self.embedding()
                ambient = inclusion.codomain()
                gram = matrix(SageZZ, ambient.gram_matrix())
                standard = identity_matrix(SageZZ, gram.nrows())
                assert gram == standard or gram == -standard, (
                    f"{ambient} is not $I_(n,0)$ or $I_(0,n)$, so the rows of "
                    "an inclusion into it are coordinates and not vectors"
                )
                # A new subobject and not a new arrow out of $S$: the reduced
                # generators induce a different form on the domain, so the
                # old domain is not one this arrow could preserve.  A row of
                # the reduced matrix is one generator's image in the ambient.
                #
                # Not ``subobject_on``: it puts a generating set into the
                # normal form of its rows, which is the framing this replaces.
                reduced = finite_ordered_set(tuple(
                    zipsum(row, ambient.module_generators(), ambient.zero())
                    for row in inclusion.matrix().LLL().rows()
                ))
                sub = ambient._sub_form_module(
                    matrix([[left.b(right) for right in reduced] for left in reduced]),
                    reduced,
                )
                return Subobject(sub.Hom(ambient)({
                    generator: generator for generator in reduced
                }))
