r"""``HyperbolicLattices`` — hyperbolic integral lattices supporting root enumeration.

Refine a hyperbolic (``n``, 1) integral lattice into this category to gain::

    vinberg_algorithm(v0, use_coxiter, output, max_roots, max_decompositions, verbose)
    get_isotropic_type(isotropic_element)   # classify by divisibility and $e^*\in A_L$

EXAMPLES::

    sage: from dzack_research.preamble import catalogue
    sage: from dzack_research.preamble.categories import HyperbolicLattices
    sage: L = Lattices.U.direct_sum([Lattices.E8])  # E10, signature (1, 9)
    sage: refine(L, HyperbolicLattices())
    sage: L in HyperbolicLattices()
    True
"""

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dzack_research.preamble.lexicon import Element

from typing import TYPE_CHECKING

from sage.categories.category import Category
from sage.misc.abstract_method import abstract_method

if TYPE_CHECKING:
    from collections.abc import Callable

    from dzack_research.preamble.lexicon import GramMatrix, RingElement, SignaturePair
    from tqdm.auto import tqdm

    from typing import Protocol

    class HyperbolicLatticeParent(Protocol):
        r"""What Vinberg's algorithm asks of a hyperbolic lattice."""

        def signature_pair(self) -> "SignaturePair": ...
        def twist(self, scale: "RingElement") -> "HyperbolicLatticeParent": ...
        def gram_matrix(self) -> "GramMatrix": ...
        def module_generators(self) -> tuple: ...
        def zero(self) -> "Element": ...
        def _vinberg_progress(
            self,
            total: int | None,
        ) -> tuple["Callable[[int, int], None]", "tqdm"]: ...


class HyperbolicLattices(Category):
    r"""Category of hyperbolic integral lattices (signature ``(n, 1)``).

    Provides one Vinberg root enumeration implementation (via the vendored
    ``vinal`` clone). Isotropic-element classification is inherited from
    ``IntegralLattices``.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "hyperbolic integral lattices"

    def super_categories(self) -> list:
        # Local: a module-level import here would close a cycle; by call time this module is built.
        from dzack_research.preamble.categories.modules.framed.formed.integrallattice.integral_lattices import IntegralLattices
        return [IntegralLattices()]

    class ParentMethods:
        r"""Methods available on hyperbolic lattices refined into this category."""

        @abstract_method
        def weyl_group(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return $W(L)\le O(L)$, the subgroup generated by the
            reflections in the roots of $L$.

            The category's stated contract: this is the owned name for the
            notion, and no implementation exists yet -- producing one is the
            open work of the Vinberg surface, whose root enumeration
            (:meth:`vinberg_algorithm`) is the input the generators come
            from.
            """

        @abstract_method
        def fundamental_chamber(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return a fundamental polyhedron of $W(L)$ acting on the
            hyperbolic space of $L\otimes\mathbb R$.

            The category's stated contract; the walls are the mirrors of
            the roots Vinberg's algorithm enumerates.
            """

        @abstract_method
        def is_reflective(self: "HyperbolicLatticeParent") -> bool:
            r"""Return whether $W(L)$ has finite index in $O(L)$ --
            equivalently, whether the fundamental polyhedron has finite
            volume.

            The category's stated contract: Vinberg's criterion decides it
            when the root enumeration terminates, and that wiring is the
            open work.

            Hypothesis on the signature: in signature $(1,1)$ the domain is
            a half-line in $H^1$, of infinite covolume, so a
            fundamental-polyhedron termination check can never fire
            (observed on the vendored ``vinal`` fork, commit ``c817ecc``);
            :meth:`vinberg_algorithm` warns rather than terminates there.
            """

        def vinberg_algorithm(
            self: "HyperbolicLatticeParent",
            v0: "Element | None" = None,
            use_coxiter: bool = False,
            output: "Element | None" = None,
            max_roots: int | None = None,
            max_decompositions: int | None = None,
            verbose: bool = False,
        ) -> list["Element"]:
            r"""Enumerate roots using the vendored Vinberg algorithm.

            Requires the ``vinal`` clone in ``computations/vendor/``.

            Parameters
            ----------
            v0 : vector, optional
                Starting vector (default: the last basis vector).
            use_coxiter : bool
                Whether to use CoxIter for covolume checking.
            output : optional
                Output target (passed to ``VinAl``).
            max_roots : int, optional
                Bound on the number of roots.
            max_decompositions : int, optional
                Bound on the number of decompositions.
            verbose : bool
                Show a ``tqdm`` progress bar.

            Returns
            -------
            list
                The enumerated roots, as elements of this lattice.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.utilities import zipsum
            # ``vinal`` diagonalizes and asserts exactly one negative entry, so
            # it wants signature (n, 1).  This repo's convention is negative
            # definite, making its hyperbolic lattices (1, n) -- those are the
            # ones needing the twist, and their roots come back negated.
            pos, neg = self.signature_pair()
            match pos, neg:
                case _, 1:
                    source = self
                    negate_roots = False
                case 1, _:
                    source = self.twist(-1)
                    negate_roots = True
                case _:
                    assert False, (
                    f"Vinberg's algorithm needs signature (1, n) or (n, 1); "
                    f"this lattice has ({pos}, {neg})"
                    )

            from vinal import VinAl

            algorithm = VinAl(source.gram_matrix(), v0, use_coxiter, output)

            report, bar = (
                self._vinberg_progress(max_decompositions) if verbose else (None, None)
            )
            from contextlib import ExitStack

            with ExitStack() as cleanup:
                if bar is not None:
                    cleanup.callback(bar.close)
                complete = algorithm.FindRoots(
                    max_roots=max_roots,
                    max_decompositions=max_decompositions,
                    progress=report,
                )

            if not complete:
                import warnings

                warnings.warn(
                    f"Vinberg search did not establish the fundamental polyhedron: "
                    f"{len(algorithm.roots)} root(s) found, but finite covolume was never "
                    f"confirmed. For signature (n, 1) with n=1 the criterion is "
                    f"unreachable (half-line in H^1, infinite volume).",
                    RuntimeWarning,
                    stacklevel=2r,
                )
            # What comes back is coordinates: the algorithm was handed a Gram
            # matrix and knows nothing else, so reading its output as elements
            # of this lattice is a step someone has to take, and this is it.
            roots = [
                zipsum(
            root,
            self.module_generators(),
            self.zero(),
        )
                for root in algorithm.roots
            ]
            return [-root for root in roots] if negate_roots else roots

        @staticmethod
        def _vinberg_progress(
            total: int | None,
        ) -> tuple["Callable[[int, int], None]", "tqdm"]:
            r"""Return a progress callback and tqdm bar for Vinberg search."""
            from tqdm.auto import tqdm

            bar = tqdm(
                total=int(total) if total is not None else None,
                unit=" decomp",
                desc="Vinberg search",
                postfix={"roots": 0},
                leave=True,
            )

            def report(decompositions: int, roots: int) -> None:
                bar.n = int(decompositions)
                bar.set_postfix(roots=int(roots), refresh=False)
                bar.refresh()

            return report, bar
