r"""``HyperbolicLattices`` — hyperbolic integral lattices supporting root enumeration.

Refine a hyperbolic (``n``, 1) integral lattice into this category to gain::

    vinberg_algorithm(v0, use_coxiter, output, max_roots, max_decompositions, verbose)
    get_isotropic_type(isotropic_element)   # classify by divisibility and $e^*\in A_L$

EXAMPLES::

    sage: from dzack_research.preamble import catalogue
    sage: from dzack_research.preamble.categories import HyperbolicLattices
    sage: L = Lattices.U.direct_sum([Lattices.E8])  # E10, signature (1, 9)
    sage: refine(L, HyperbolicLattices())
    sage: L in HyperbolicLattices()
    True
"""

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dzack_research.preamble.lexicon import Element

from typing import TYPE_CHECKING

from dzack_research.preamble.owned_category_bases import Category
from sage.misc.abstract_method import abstract_method

if TYPE_CHECKING:
    from collections.abc import Callable

    from dzack_research.preamble.lexicon import GramMatrix, OrderedSet, RingElement, SignaturePair
    from tqdm.auto import tqdm

    from typing import Protocol

    class HyperbolicLatticeParent(Protocol):
        r"""What Vinberg's algorithm asks of a hyperbolic lattice."""

        def signature_pair(self) -> "SignaturePair": ...
        def twist(self, scale: "RingElement") -> "HyperbolicLatticeParent": ...
        def gram_matrix(self) -> "GramMatrix": ...
        def module_generators(self) -> tuple: ...
        def zero(self) -> "Element": ...
        def _vinberg_progress(
            self,
            total: int | None,
        ) -> tuple["Callable[[int, int], None]", "tqdm"]: ...


class HyperbolicLattices(Category):
    r"""Category of hyperbolic integral lattices (signature ``(n, 1)``).

    Provides one Vinberg root enumeration implementation (via the vendored
    ``vinal`` clone). Isotropic-element classification is inherited from
    ``IntegralLattices``.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "hyperbolic integral lattices"

    def super_categories(self) -> list:
        # Local: a module-level import here would close a cycle; by call time this module is built.
        from dzack_research.preamble.categories.modules.framed.formed.integrallattice.integral_lattices import IntegralLattices
        return [IntegralLattices()]

    class ParentMethods:
        r"""Methods available on hyperbolic lattices refined into this category."""

        def weyl_group(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return $W(L)\le O(L)$, the subgroup generated by the
            reflections in the roots of $L$.

            The category's stated contract: this is the owned name for the
            notion, and no implementation exists yet -- producing one is the
            open work of the Vinberg surface, whose root enumeration
            (:meth:`vinberg_algorithm`) is the input the generators come
            from.
            """
            assert False, (
                "$W(L)$ is the category's stated contract and its open work: the generators are the reflections in the roots vinberg_algorithm enumerates, and no implementation exists yet"
            )


        def fundamental_chamber(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return a fundamental polyhedron of $W(L)$ acting on the
            hyperbolic space of $L\otimes\mathbb R$.

            The category's stated contract; the walls are the mirrors of
            the roots Vinberg's algorithm enumerates.
            """
            assert False, (
                "the fundamental polyhedron is the category's stated contract and its open work: its walls are the mirrors of the roots vinberg_algorithm enumerates, and no implementation exists yet"
            )


        def dominant_cone(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return the dominant cone of $W(L)$ inside $L\otimes\mathbb R$.

            The closed cone cut out by the walls of
            :meth:`fundamental_chamber`: the vectors whose pairing against
            every simple root has the sign the convention fixes.  The
            category's stated contract.  The object lives in the
            base-changed parent $L\otimes\mathbb R$, not in $L$ -- a cone is
            closed under positive real scaling, so $L$ has no cone in it,
            only the rank-one sublattices $\mathbb Z v$ that meet one.
            """
            assert False, (
                "the dominant cone is the category's stated contract and its open work; it lives in the base-changed parent L tensor RR, which the preamble has no cone surface for yet"
            )


        def chamber_complex(self: "HyperbolicLatticeParent") -> "Parent":
            r"""Return the chamber complex of $W(L)$ acting on
            $L\otimes\mathbb R$.

            The $W(L)$-translates of :meth:`fundamental_chamber`, with their
            faces, as one complex.  The category's stated contract; the union
            of the translates is the Tits cone, and $W(L)$ acts properly
            discontinuously on its interior.
            """
            assert False, (
                "the chamber complex is the category's stated contract and its open work; it needs fundamental_chamber and a complex surface, neither of which the preamble owns yet"
            )


        def isotropic_elements_below_height(
            self: "HyperbolicLatticeParent",
            timelike: "Element",
            height: "RingElement",
        ) -> "OrderedSet":
            r"""Return the isotropic elements $v$ of $L$ with
            $\lvert b(v, \mathrm{timelike})\rvert \le \mathrm{height}$.

            The category's stated contract, and the enumeration a light-cone
            walk needs.  It is not covered by
            ``IntegralLattices.enumerate_short_vectors``, which is a
            positive-definite algorithm: on a Lorentzian lattice the set
            $\{v : q(v) = 0\}$ is infinite, and a bound on the norm bounds
            nothing.  The chosen timelike element is what makes the set
            finite, so it is a required argument rather than a default.
            """
            assert False, (
                "the height-bounded isotropic enumeration is the category's stated contract and its open work; enumerate_short_vectors is a positive-definite algorithm and cannot answer it"
            )


        def is_reflective(self: "HyperbolicLatticeParent") -> bool:
            r"""Return whether $W(L)$ has finite index in $O(L)$ --
            equivalently, whether the fundamental polyhedron has finite
            volume.

            Decided by Allcock's edgewalk (the
            ``LORENTZ_FundDomain_AllcockEdgewalk`` engine behind
            :func:`engines.lorentz_edgewalk_fundamental_domain`), which
            terminates on every input -- unlike Vinberg root enumeration
            (:meth:`vinberg_algorithm`), which halts only when the lattice
            *is* reflective.  The engine's convention is signature
            $(n, 1)$; this repo's negative-definite convention makes its
            hyperbolic lattices $(1, n)$, and the twist by $-1$ is the
            transport between the two, written out rather than assumed.
            Reflectivity is twist-invariant: $O(L) = O(L(-1))$ and the
            reflections correspond.

            Hypothesis on the signature: in signature $(1,1)$ the domain is
            a half-line in $H^1$, of infinite covolume, so no
            fundamental-polyhedron criterion can fire (observed on the
            vendored ``vinal`` fork, commit ``c817ecc``); the same guard
            applies here.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.categories.modules.framed.formed.integrallattice.engines import lorentz_edgewalk_fundamental_domain

            positive, negative = self.signature_pair()
            match positive, negative:
                case _, 1:
                    source = self
                case 1, _:
                    source = self.twist(-1)
                case _:
                    assert False, (
                        f"reflectivity is a hyperbolic question; "
                        f"this lattice has signature ({positive}, {negative})"
                    )
            assert source.signature_pair() != (1, 1), (
                "in signature (1,1) the domain is a half-line in H^1, of "
                "infinite covolume; reflectivity is not decided here"
            )
            return bool(
                lorentz_edgewalk_fundamental_domain(
                    source.gram_matrix()
                )["is_reflective"]
            )

        def vinberg_algorithm(
            self: "HyperbolicLatticeParent",
            v0: "Element | None" = None,
            use_coxiter: bool = False,
            output: "Element | None" = None,
            max_roots: int | None = None,
            max_decompositions: int | None = None,
            verbose: bool = False,
        ) -> list["Element"]:
            r"""Enumerate roots using the vendored Vinberg algorithm.

            Requires the ``vinal`` clone in ``computations/vendor/``.

            Parameters
            ----------
            v0 : vector, optional
                Starting vector (default: the last basis vector).
            use_coxiter : bool
                Whether to use CoxIter for covolume checking.
            output : optional
                Output target (passed to ``VinAl``).
            max_roots : int, optional
                Bound on the number of roots.
            max_decompositions : int, optional
                Bound on the number of decompositions.
            verbose : bool
                Show a ``tqdm`` progress bar.

            Returns
            -------
            list
                The enumerated roots, as elements of this lattice.
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.utilities import zipsum
            # ``vinal`` diagonalizes and asserts exactly one negative entry, so
            # it wants signature (n, 1).  This repo's convention is negative
            # definite, making its hyperbolic lattices (1, n) -- those are the
            # ones needing the twist, and their roots come back negated.
            pos, neg = self.signature_pair()
            match pos, neg:
                case _, 1:
                    source = self
                    negate_roots = False
                case 1, _:
                    source = self.twist(-1)
                    negate_roots = True
                case _:
                    assert False, (
                    f"Vinberg's algorithm needs signature (1, n) or (n, 1); "
                    f"this lattice has ({pos}, {neg})"
                    )

            from vinal import VinAl

            algorithm = VinAl(source.gram_matrix(), v0, use_coxiter, output)

            report, bar = (
                self._vinberg_progress(max_decompositions) if verbose else (None, None)
            )
            from contextlib import ExitStack

            with ExitStack() as cleanup:
                if bar is not None:
                    cleanup.callback(bar.close)
                complete = algorithm.FindRoots(
                    max_roots=max_roots,
                    max_decompositions=max_decompositions,
                    progress=report,
                )

            if not complete:
                import warnings

                warnings.warn(
                    f"Vinberg search did not establish the fundamental polyhedron: "
                    f"{len(algorithm.roots)} root(s) found, but finite covolume was never "
                    f"confirmed. For signature (n, 1) with n=1 the criterion is "
                    f"unreachable (half-line in H^1, infinite volume).",
                    RuntimeWarning,
                    stacklevel=2r,
                )
            # What comes back is coordinates: the algorithm was handed a Gram
            # matrix and knows nothing else, so reading its output as elements
            # of this lattice is a step someone has to take, and this is it.
            roots = [
                zipsum(
            root,
            self.module_generators(),
            self.zero(),
        )
                for root in algorithm.roots
            ]
            return [-root for root in roots] if negate_roots else roots

        def allcock_edgewalk(self: "HyperbolicLatticeParent") -> dict:
            r"""Return fundamental-domain data for $W(L)$ from Allcock's
            edgewalk (the ``polyhedral_common`` engine).

            A second producer of the object :meth:`vinberg_algorithm`
            enumerates: the engine walks the edges of a fundamental
            polyhedron of the reflection subgroup $W(L)\le O(L)$, and --
            unlike Vinberg root enumeration -- terminates on every input, so
            the ``is_reflective`` field is a decision rather than a wait.
            The signature transport matches :meth:`vinberg_algorithm`: the
            engine wants $(n,1)$, this repo's hyperbolic lattices are
            $(1,n)$, and the twist relates the two.  Root signs are returned
            as the engine chose them; $s_r=s_{-r}$, so the reflection group,
            the chamber, and reflectivity do not depend on that choice.

            Returned keys:

            * ``simple_roots`` -- the simple roots as elements of this
              lattice;
            * ``vertices`` -- triples ``(generator, incident_roots, square)``
              per polyhedron vertex, the square recomputed by this lattice's
              own form (an ideal vertex has square $0$ in either convention);
            * ``is_reflective`` -- whether $W(L)$ has finite index in
              $O(L)$, the engine's decision;
            * ``polyhedron_isometry_generators`` -- generators of the finite
              isometry group of the polyhedron, as elements of
              $\mathrm{Aut}(L)$ (an isometry of $L(-1)$ is an isometry of
              $L$ on the same images, so no transport applies to them).
            """
            # Local: a module-level import here would close a cycle; by call time this module is built.
            from dzack_research.preamble.categories.modules.framed.formed.integrallattice.engines import lorentz_edgewalk_fundamental_domain
            from dzack_research.preamble.utilities import zipsum

            pos, neg = self.signature_pair()
            match pos, neg:
                case _, 1:
                    source = self
                case 1, _:
                    source = self.twist(-1)
                case _:
                    assert False, (
                        f"the edgewalk needs signature (1, n) or (n, 1); "
                        f"this lattice has ({pos}, {neg})"
                    )

            record = lorentz_edgewalk_fundamental_domain(source.gram_matrix())

            def element_of(row: tuple) -> "Element":
                return zipsum(row, self.module_generators(), self.zero())

            simple_roots = tuple(
                element_of(row) for row in record["simple_root_rows"]
            )
            vertices = tuple(
                (
                    element_of(generator_row),
                    tuple(element_of(row) for row in incident_rows),
                    element_of(generator_row).q(),
                )
                for generator_row, incident_rows, _engine_norm in record["vertices"]
            )
            automorphisms = self.Aut()
            polyhedron_isometry_generators = tuple(
                automorphisms._isometry_on_rows(generator.rows())
                for generator in record["isometry_generator_rows"]
            )
            return {
                "simple_roots": simple_roots,
                "vertices": vertices,
                "is_reflective": record["is_reflective"],
                "polyhedron_isometry_generators": polyhedron_isometry_generators,
            }

        def is_cocompact(self: "HyperbolicLatticeParent") -> bool:
            r"""Return whether $W(L)$ acts cocompactly on the hyperbolic
            space of $L\otimes\mathbb R$.

            A vertex of the fundamental polyhedron is either an ordinary
            point of $H^n$ -- inside the light cone, so of nonzero square --
            or an ideal point on $\partial H^n$, which is isotropic.  The
            polyhedron is compact exactly when it has finite volume and no
            ideal vertex, so this reads the two facts off one edgewalk:
            reflectivity (finite covolume) and the absence of an isotropic
            vertex.  Stated on the squares rather than on their sign, the
            criterion is convention-free: the twist by $-1$ that carries
            this repo's $(1,n)$ lattices into the engine's $(n,1)$ negates
            every vertex square and fixes which of them vanish.

            Not cocompact does not mean infinite covolume: a reflective
            lattice with an ideal vertex has a finite-volume noncompact
            fundamental domain, which is the generic hyperbolic case.

            The signature hypothesis is :meth:`is_reflective`'s: in
            signature $(1,1)$ the domain is a half-line in $H^1$ and no
            fundamental-polyhedron criterion fires, so the question is
            refused rather than answered.
            """
            assert self.signature_pair() != (1, 1), (
                "in signature (1,1) the domain is a half-line in H^1; "
                "cocompactness is not decided here"
            )
            domain = self.allcock_edgewalk()
            if not domain["is_reflective"]:
                return False
            return all(
                square != 0 for _generator, _incident_roots, square in domain["vertices"]
            )

        @staticmethod
        def _vinberg_progress(
            total: int | None,
        ) -> tuple["Callable[[int, int], None]", "tqdm"]:
            r"""Return a progress callback and tqdm bar for Vinberg search."""
            from tqdm.auto import tqdm

            bar = tqdm(
                total=int(total) if total is not None else None,
                unit=" decomp",
                desc="Vinberg search",
                postfix={"roots": 0},
                leave=True,
            )

            def report(decompositions: int, roots: int) -> None:
                bar.n = int(decompositions)
                bar.set_postfix(roots=int(roots), refresh=False)
                bar.refresh()

            return report, bar
