r"""Isometries of integral lattices."""

from typing import Self, TYPE_CHECKING

from sage_lattice_category_spike.objects.cardinals import Cardinal
from sage_lattice_category_spike.objects.morphism_matrices import matrix_group
from sage.categories.category import Category
from sage.sets.totally_ordered_finite_set import TotallyOrderedFiniteSet

if TYPE_CHECKING:
    # The ordered-set noun is type-only: the preamble loads into one
    # shared namespace and nothing named OrderedSet may bind there.
    from sage_lattice_category_spike.lexicon import OrderedSet


class LatticeIsometries(Category):
    r"""Invertible lattice homomorphisms."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "lattice isometries"

    def super_categories(self) -> list:
        return [LatticeHomomorphisms()]

    class ParentMethods:
        def __call__(self: Self, images: "dict | FormMorphism") -> "Morphism":
            if isinstance(images, FormMorphism):
                # A homset is a parent and its morphisms are its elements, so
                # being handed one is a parent constructing an element it
                # already has.  Coercion discovery and ``an_element`` both ask
                # for exactly this; declaring it again through framing labels
                # would only rebuild what was passed in.
                assert images.domain() is self.domain(), (
                    f"{images} is not an isometry of {self.domain()}"
                )
                return images
            morphism = LatticeHomomorphisms.ParentMethods.__call__(
                self,
                images,
            )
            determinant = morphism.matrix().det()
            assert determinant in (1, -1), (
                f"an integral isometry has unit determinant, got {determinant}"
            )
            return refine(morphism, LatticeIsometries())

        def one(self: Self) -> "ModuleAutomorphism":
            return self(
                {
                    label: self.domain().module_generator(label)
                    for label in self.domain().module_generating_set()
                }
            )

        def an_element(self: Self) -> "ModuleAutomorphism":
            r"""Return the identity.

            Sage's generic ``_an_element_`` probes with ``self(0)``,
            ``self(1)`` and so on, which for an isometry group means
            declaring a lattice morphism from an integer.  A group has a
            distinguished element and this is it.
            """
            return self.one()

        def subgroup_on(self: Self, group_generators: "Set") -> "ModuleAutomorphismGroup":
            r"""Return the subgroup generated by a *set* of isometries."""
            assert all(generator in self for generator in group_generators), (
                "each subgroup generator must belong to this isometry group"
            )
            return LatticeIsometrySubgroup(self, group_generators)

    class MorphismMethods:
        def to_matrix(self: Self) -> "MorphismMatrix":
            return self.matrix()

        def is_identity(self: Self) -> bool:
            return self.matrix().is_one()

        def is_involution(self: Self) -> bool:
            return (self * self).is_identity()

        def __mul__(self: Self, other: object) -> "Element":
            assert (
                isinstance(other, FormMorphism)
                and other.parent() is self.parent()
            ), "composition is internal to one isometry group"
            return self.parent()(
                {
                    label: self(other(other.domain().module_generator(label)))
                    for label in other.domain().module_generating_set()
                }
            )

        def inverse(self: Self) -> "ModuleAutomorphism":
            inverse_matrix = self.matrix().inverse().change_ring(ZZ)
            return self.parent()(
                {
                    label: zipsum(
            row,
            self.domain().module_generators(),
            self.domain().zero(),
        )
                    for label, row in zip(
                        self.domain().module_generating_set(),
                        inverse_matrix.rows(),
                    )
                }
            )

        def cyclic_subgroup(self: Self) -> "Group":
            r"""Return \(\langle f\rangle\le O(L)\), the subgroup this generates.

            A group in its own right, and the \(G\) of the construction that
            names elements and takes what they generate; the action of that
            \(G\) on \(L\) is its own ``inclusion()``.  It is not the abstract \(C_n\):
            a caller who means an abstract group and a possibly unfaithful
            \(\rho\) constructs both, and hands \(\rho\) to ``with_action``.
            """
            return self.parent().subgroup_on({self})

        def _libgap_(self: Self) -> "GapElement":
            r"""Return this isometry inside its group's GAP model.

            A character is a function on a group, and when that group is a
            literal subgroup of \(O(L)\) its elements are these isometries;
            declaring where they sit in GAP is what makes GAP's characters
            functions on them rather than on a parallel set of matrices a
            caller would have to translate for.  This is the conversion
            protocol ``ClassFunction`` evaluates through.
            """
            return self.parent()._defining_matrix_group()(self.matrix()).gap()

        gap = _libgap_


class LatticeIsometrySubgroup(FiniteAutomorphismSubgroup, FormAutomorphismGroup):
    r"""The subgroup of \(O(L)\) generated by a set of isometries.

    Generated, not finite.  An isometry of an indefinite lattice can have
    infinite order, and finite-order isometries can generate an infinite
    group -- two reflections whose product has infinite order generate an
    infinite dihedral group.  So the generating set is what this object
    knows, finite generation is what it carries, and finiteness is a
    question put to GAP, never a constructor invariant.
    """

    def __init__(self, supergroup: "Group", group_generators: "Set") -> None:
        lattice = supergroup.domain()
        assert supergroup.codomain() is lattice, (
            "an isometry group is an endomorphism homset"
        )
        FormAutomorphismGroup.__init__(self, lattice)
        # A subgroup of \(O(L)\) is a group, and that is the whole placement.
        # Not ``Groups().Finite()``: refining into the finite subcategory
        # asserts a theorem, and one that is generally hard -- it needs
        # \(O(L)\) computed, or a definiteness hypothesis.  Cardinality is
        # not a reason to reach for it, being total on sets already.
        refine(self, [LatticeHomomorphisms(), LatticeIsometries(), Groups()])
        assert group_generators, "a generated subgroup needs a generator"
        assert all(
            generator.parent() is supergroup for generator in group_generators
        ), "each subgroup generator must belong to the stated isometry group"
        self._group_generators = finite_ordered_set(
            [
                self(
                    {
                        label: generator(lattice.module_generator(label))
                        for label in lattice.module_generating_set()
                    }
                )
                for generator in group_generators
            ]
        )

    def group_generators(self) -> TotallyOrderedFiniteSet:
        return self._group_generators

    @cached_method
    def _matrix_group(self) -> "MatrixGroup":
        r"""Return this subgroup as a GAP-backed matrix group.

        \(O(L)=\{M\in GL_n(R):M^tG_LM=G_L\}\) is cut out of a matrix group by
        a condition, so a subgroup of it is a matrix group on the generators'
        matrices.  Everything below defers here.

        Deciding finiteness and order of a subgroup given by generators is
        Schreier--Sims and coset enumeration -- mature algorithms this repo
        must call, never restate.  The spike reached the same delegation in
        ``morphisms/isometry_groups.py``.
        """
        return matrix_group(
            generator.matrix() for generator in self._group_generators
        )

    def is_finite(self) -> bool:
        r"""Return whether this subgroup is finite, as decided by GAP."""
        return bool(self._matrix_group().is_finite())

    def cardinality(self) -> "Cardinal":
        r"""Return \(|G|\), as computed by GAP."""
        return Cardinal(self._matrix_group().order())

    def order(self) -> "Cardinal":
        r"""Return \(|G|\).  The order of a group is its cardinality."""
        return self.cardinality()

    def __iter__(self):
        assert self.is_finite(), (
            f"{self} is infinite, so it cannot be enumerated"
        )
        lattice = self.domain()
        for element in self._matrix_group():
            yield self(
                {
                    label: zipsum(
                        element.matrix().row(index),
                        lattice.module_generators(),
                        lattice.zero(),
                    )
                    for index, label in enumerate(
                        lattice.module_generating_set()
                    )
                }
            )

    def __contains__(self, element: "Element") -> bool:
        r"""Return whether ``element`` lies in this subgroup.

        Membership is the one operation always available on a group carved
        out of \(GL_n(R)\) by a condition, so it is decided directly rather
        than by searching an enumeration.
        """
        return (
            isinstance(element, FormMorphism)
            and element.domain() is self.domain()
            # ``matrix`` converts through ``MorphismMatrix._matrix_``, the
            # owned protocol.  Asking the group directly would let Sage's
            # containment swallow the failed conversion and answer False for
            # an element that is present.
            and matrix(element.matrix()) in self._matrix_group()
        )

    def _repr_(self) -> str:
        return (
            f"Subgroup of O({self.domain()}) generated by "
            f"{self._group_generators.cardinality()} isometries"
        )
