r"""Lazy Weyl chamber complexes generated from exact root half-space cones."""

from sage.structure.sage_object import SageObject

from dzack_research.preamble.categories.abstract_categories.objects import OwnedCategory
from dzack_research.preamble.categories.chamber_systems import ChamberSystems
from dzack_research.preamble.categories.sets.indexed_families import finite_indexed_family


class ChamberAdjacency(SageObject):
    r"""One wall crossing between two chambers, with its actual transporter."""

    def __init__(self, source, target, wall_root, transporter) -> None:
        if transporter.domain() is not source.ambient_lattice():
            raise ValueError("a chamber adjacency transporter has the wrong domain")
        if transporter.codomain() is not target.ambient_lattice():
            raise ValueError("a chamber adjacency transporter has the wrong codomain")
        transported = source.transport(transporter)
        if tuple(transported.wall_roots()) != tuple(target.wall_roots()):
            raise ValueError("the chamber adjacency transporter does not carry the source walls to the target walls")
        self._source = source
        self._target = target
        self._wall_root = wall_root
        self._transporter = transporter

    def source(self):
        return self._source

    def target(self):
        return self._target

    def wall_root(self):
        return self._wall_root

    def transporter(self):
        return self._transporter

    def shared_wall_covector(self):
        source = self.source().ambient_lattice()
        return source.algebraic_correlation_morphism()(self.wall_root())

    def shared_face(self):
        r"""Return the actual codimension-one cone common to the adjacent chambers."""
        return self.source().face_on_covector(self.shared_wall_covector())

    def _repr_(self):
        return f"Chamber adjacency across {self.wall_root()}"


class WeylChamberComplexes(OwnedCategory):
    r"""Locally finite chamber systems generated by simple reflections."""

    @classmethod
    def _repr_object_names(cls):
        return "Weyl chamber complexes"

    def super_categories(self):
        return [ChamberSystems()]

    class ParentMethods:
        def __init__(self, fundamental_chamber, **rest) -> None:
            if fundamental_chamber.wall_roots() is None:
                raise ValueError("a Weyl chamber complex needs retained simple roots")
            self._fundamental_chamber = fundamental_chamber
            super().__init__(**rest)

        def fundamental_chamber(self):
            return self._fundamental_chamber

        def lattice(self):
            return self._fundamental_chamber.ambient_lattice()

        def wall_roots(self):
            return self._fundamental_chamber.wall_roots()

        def type_set(self):
            r"""Return the chamber-system types, indexed by the simple walls."""
            return self.wall_roots()

        def weyl_group(self):
            return self._fundamental_chamber.weyl_group()

        def simple_reflections(self):
            lattice = self.lattice()
            roots = self.wall_roots()
            return finite_indexed_family(
                roots,
                lambda root: lattice.reflection(root),
                name="Simple reflections of the chamber complex",
            )

        def transporter_from_word(self, word):
            r"""Return the Weyl isometry represented by a finite word in simple walls.

            ``word`` is syntactic ingress: each entry is either one retained
            root or its integer position in the retained root family.  The
            sequence is immediately consumed into the actual lattice
            isometry, so no Python sequence is retained as mathematical data.
            """
            roots = self.wall_roots()
            result = self.lattice().O().one()
            reflections = self.simple_reflections()
            for entry in word:
                root = entry
                if root not in roots:
                    root = roots[int(entry)]
                result = reflections[root] * result
            return result

        def chamber_from_word(self, word):
            return self.fundamental_chamber().transport(
                self.transporter_from_word(word)
            )

        def fundamental_adjacencies(self):
            r"""Return the chambers adjacent to the fundamental chamber, indexed by walls."""
            chamber = self.fundamental_chamber()
            reflections = self.simple_reflections()
            return finite_indexed_family(
                self.wall_roots(),
                lambda root: ChamberAdjacency(
                    chamber,
                    chamber.transport(reflections[root]),
                    root,
                    reflections[root],
                ),
                name="Fundamental wall adjacencies",
            )

        def _repr_(self):
            return f"Weyl chamber complex of {self.lattice()}"


__all__ = [
    "ChamberAdjacency",
    "WeylChamberComplexes",
]
