"""Linear-algebra computations for the Höhn--Mason Leech source transcription.

The archived-source parser remains in ``lattice-database``.  This preamble
module owns all coordinate changes, Gram comparisons, induced actions and
finite matrix-group computations used to validate the transcription against
lattice cards.
"""

from __future__ import annotations

from sage.groups.matrix_gps.finitely_generated import MatrixGroup
from sage.matrix.constructor import matrix
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.rational_field import QQ as SageQQ


def _rational(rows):
    return matrix(SageQQ, rows)


def _integral_rows(value):
    """Return integer rows when ``value`` is integral, else ``None``."""
    if any(entry.denominator() != 1 for entry in value.list()):
        return None
    return tuple(
        tuple(int(value[row, column]) for column in range(value.ncols()))
        for row in range(value.nrows())
    )


def leech_gram(inner_product_rows, basis_rows):
    """Return the Gram matrix in the printed Leech basis."""
    inner = _rational(inner_product_rows)
    basis = _rational(basis_rows)
    return basis * inner * basis.transpose()


def coordinates(leech_basis_rows, rows):
    """Return ``rows`` in coordinates of the printed Leech basis."""
    return _rational(rows) * _rational(leech_basis_rows).inverse()


def action_matrices(leech_basis_rows, coinvariant_basis_rows, stabilizer_generators):
    """Return the induced matrices on the coinvariant source basis."""
    basis = coordinates(leech_basis_rows, coinvariant_basis_rows)
    inverse = (basis * basis.transpose()).inverse()
    return tuple(
        basis * _rational(generator) * basis.transpose() * inverse
        for generator in stabilizer_generators
    )


def actions_are_integral(
    leech_basis_rows, coinvariant_basis_rows, stabilizer_generators
) -> bool:
    """Whether every stabilizer generator preserves the integral coinvariant sublattice."""
    return all(
        _integral_rows(action) is not None
        for action in action_matrices(
            leech_basis_rows, coinvariant_basis_rows, stabilizer_generators
        )
    )


def embedding_matrix(
    leech_basis_rows,
    leech_record_basis_rows,
    coinvariant_basis_rows,
    record_basis_rows,
):
    """Return the integral inclusion matrix from the record basis to the Leech record basis."""
    coinvariant = coordinates(leech_basis_rows, coinvariant_basis_rows)
    image = (
        _rational(leech_record_basis_rows).inverse()
        * coinvariant.transpose()
        * _rational(record_basis_rows)
    )
    rows = _integral_rows(image)
    if rows is None:
        raise ValueError("the record basis does not give an integral Leech-lattice embedding")
    return rows


def automorphism_matrices(
    leech_basis_rows,
    coinvariant_basis_rows,
    stabilizer_generators,
    record_basis_rows,
):
    """Return the integral stabilizer-generator matrices in the selected record basis."""
    basis = _rational(record_basis_rows)
    result = []
    for action in action_matrices(
        leech_basis_rows, coinvariant_basis_rows, stabilizer_generators
    ):
        rows = _integral_rows(basis.inverse() * action.transpose() * basis)
        if rows is None:
            raise ValueError("a stabilizer generator does not preserve the selected record lattice")
        result.append(rows)
    return tuple(result)


def generated_group_order(generators) -> int:
    """Return the order of the finite group generated by the integral matrices."""
    matrices = tuple(matrix(SageZZ, generator) for generator in generators)
    if not matrices:
        return 1
    return int(MatrixGroup(matrices).order())


def leech_record_basis_isometry(
    inner_product_rows,
    leech_basis_rows,
    record_basis_rows,
    record_lattice,
) -> bool:
    """Whether the stored record basis is a unimodular isometry to the printed Leech lattice."""
    gram = leech_gram(inner_product_rows, leech_basis_rows)
    basis = _rational(record_basis_rows)
    integral = _integral_rows(basis)
    if integral is None or abs(int(matrix(SageZZ, integral).det())) != 1:
        return False
    target_gram = matrix(
        SageQQ,
        [
            [record_lattice.gram_tensor()[i, j] for j in range(int(record_lattice.module_rank()))]
            for i in range(int(record_lattice.module_rank()))
        ],
    )
    return basis.transpose() * gram * basis == target_gram


def complementary_orthogonal_sublattices(
    inner_product_rows,
    leech_basis_rows,
    first_basis_rows,
    second_basis_rows,
) -> bool:
    """Whether two printed sublattice bases are integral, orthogonal and complementary in rank."""
    gram = leech_gram(inner_product_rows, leech_basis_rows)
    first = coordinates(leech_basis_rows, first_basis_rows)
    second = coordinates(leech_basis_rows, second_basis_rows)
    return (
        _integral_rows(first) is not None
        and _integral_rows(second) is not None
        and first.rank() + second.rank() == gram.nrows()
        and first * gram * second.transpose() == matrix(SageQQ, first.nrows(), second.nrows())
    )


def stabilizers_fix_second_and_preserve_gram(
    inner_product_rows,
    leech_basis_rows,
    second_basis_rows,
    stabilizer_generators,
) -> bool:
    """Whether every stored stabilizer generator is a Leech isometry fixing the second sublattice."""
    gram = leech_gram(inner_product_rows, leech_basis_rows)
    second = coordinates(leech_basis_rows, second_basis_rows)
    for generator_rows in stabilizer_generators:
        generator = _rational(generator_rows)
        if generator * gram * generator.transpose() != gram or second * generator != second:
            return False
    return True


def record_basis_isometry(
    inner_product_rows,
    leech_basis_rows,
    coinvariant_basis_rows,
    record_basis_rows,
    twist: int,
    record_lattice,
) -> bool:
    """Whether the selected record basis identifies its twist with the printed coinvariant lattice."""
    gram = leech_gram(inner_product_rows, leech_basis_rows)
    coinvariant = coordinates(leech_basis_rows, coinvariant_basis_rows)
    basis = _rational(record_basis_rows)
    integral = _integral_rows(basis)
    if integral is None or abs(int(matrix(SageZZ, integral).det())) != 1:
        return False
    rank = int(record_lattice.module_rank())
    record_gram = matrix(
        SageQQ,
        [[record_lattice.gram_tensor()[i, j] for j in range(rank)] for i in range(rank)],
    )
    return basis.transpose() * (coinvariant * gram * coinvariant.transpose()) * basis == int(twist) * record_gram
