r"""Hyperbolic lattices and the reflection algorithms that run on them.

A lattice is hyperbolic when its form has exactly one negative index of
inertia, so that the real points \(L\otimes\mathbb R\) carry a light cone and
\(O(L)\) acts on the hyperbolic space of one of its two halves.  The mirror of
a root \(r\) is the hyperplane \(r^{\perp}\), and the reflection subgroup
\(W(L)\leq O(L)\) is generated by the reflections in the roots.

Vinberg's algorithm (Vinberg, *On groups of unit elements of certain quadratic
forms*, Mat. Sb. 87 (1972); *Hyperbolic reflection groups*, Russian Math.
Surveys 40 (1985)) enumerates the walls of a fundamental polyhedron for
\(W(L)\), starting from a chosen controlling vector.  It is a semi-decision
procedure: it halts with a certificate when the polyhedron closes, which is to
say when \(W(L)\) has finite covolume, and runs forever otherwise.  So
:meth:`is_reflective` here answers ``True`` or ``Unknown`` and never ``False``:
a bounded search that did not close proves nothing.

This repository's convention makes root squares negative, so its hyperbolic
lattices have signature \((1,n)\).  The engine's convention is \((n,1)\), and
the twist by \(-1\) is the transport between them; it is written out at each
site rather than assumed, and the roots come back negated because negating the
form reverses every half-space condition \(b(x,r)\leq 0\).
"""

from sage.arith.misc import divisors
from sage.matrix.constructor import matrix as engine_matrix
from sage.misc.cachefunc import cached_method
from sage.misc.unknown import Unknown
from sage.modules.free_module_element import vector as engine_vector

from dzack_research.preamble.categories.lattices import Lattices
from dzack_research.preamble.categories.rings.ring_foundation import OwnedCategoryOverBaseRing
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.engine_capabilities import engine_capabilities
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors.tensor import _engine_component_matrix


def _vinal_is_available() -> bool:
    from importlib.util import find_spec

    return find_spec("vinal") is not None


def _vinal_vinberg_roots(gram, controlling_vector, max_roots, max_decompositions):
    r"""Run Vinberg's algorithm on a Gram matrix of signature \((n,1)\).

    Returns the completeness flag of the search and the coordinate rows of the
    accepted roots.  ``vinal`` is Bogachev and Perepechko's implementation of
    the algorithm; ``FindRoots`` reports whether the fundamental polyhedron was
    established, which is the algorithm's own termination criterion.
    """
    from vinal import VinAl

    algorithm = VinAl(gram, controlling_vector, False, None)
    complete = algorithm.FindRoots(
        max_roots=max_roots, max_decompositions=max_decompositions
    )
    return bool(complete), tuple(tuple(root) for root in algorithm.roots)


engine_capabilities.register(
    "vinberg_root_enumeration",
    "vinal",
    _vinal_vinberg_roots,
    available=_vinal_is_available,
)


class HyperbolicLattices(OwnedCategoryOverBaseRing):
    r"""Lattices whose form has exactly one negative index of inertia.

    A lattice enters this category by being handed to it:
    ``HyperbolicLattices(ZZ)(L)`` checks the signature and refines ``L``,
    returning the same object with the reflection algorithms available on it.
    """

    @classmethod
    def _repr_object_names(cls):
        return "hyperbolic lattices"

    def an_object(self):
        r"""The hyperbolic plane \(U\), of signature \((1,1)\)."""
        return self(Lattices(self.base_ring())("U"))

    def super_categories(self):
        return [Lattices(self.base_ring())]

    def _call_(self, lattice):
        r"""Return ``lattice`` refined into this category.

        The hypothesis is the signature: exactly one index of inertia is
        negative, or exactly one is positive.  Both spellings are hyperbolic,
        and which of them occurs is a convention about the sign of the form,
        not a fact about the geometry.
        """
        signature = lattice.signature_pair()
        positive, negative = signature.first(), signature.second()
        assert 1 in (positive, negative), (
            f"a hyperbolic lattice has exactly one index of inertia equal to "
            f"one; this lattice has signature ({positive}, {negative})"
        )
        return refine(lattice, self)

    class ParentMethods:
        def possible_root_lengths(self):
            r"""Return the values \(\lvert q(r)\rvert\) a root of this lattice can take.

            Vinberg's criterion: for a root \(r\) the crystallographic
            condition \(2b(x,r)/q(r)\in R\) for all \(x\in L\) forces \(q(r)\)
            to divide twice the last invariant factor of the correlation
            \(L\to L^{\vee}\), which is the exponent of the discriminant group
            \(A_L\).  The bound is what turns "does this lattice have a root of
            such a length" into a finite question.

            Stated here because it is the bound Vinberg's algorithm searches
            under; the hypothesis it actually needs is nondegeneracy, not
            hyperbolicity.
            """
            correlation = _engine_component_matrix(self.gram_tensor())
            invariant_factors = correlation.elementary_divisors()
            assert invariant_factors[-1] != 0, (
                "the root-length bound needs a nondegenerate correlation; this "
                "lattice has a radical, so its discriminant group is infinite "
                "and no finite set of lengths bounds its roots"
            )
            return finite_ordered_set(tuple(divisors(2 * invariant_factors[-1])))

        def _engine_gram_of_signature_n_1(self):
            r"""Return a Gram matrix in the engine's \((n,1)\) convention.

            Returns the matrix together with whether the form was negated to
            reach that convention, since a negated form reverses every
            half-space condition and so negates the roots.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            match positive, negative:
                case _, 1:
                    return _engine_component_matrix(self.gram_tensor()), False
                case 1, _:
                    return _engine_component_matrix(self.twist(-1).gram_tensor()), True
                case _:
                    assert False, (
                        f"the reflection algorithms need signature (1, n) or "
                        f"(n, 1); this lattice has ({positive}, {negative})"
                    )

        @cached_method
        def _vinberg_search(self, controlling_vector, max_roots, max_decompositions):
            r"""Run Vinberg's algorithm and return completeness with the roots."""
            gram, negated = self._engine_gram_of_signature_n_1()
            coordinates = (
                None if controlling_vector is None else list(controlling_vector.to_vector())
            )
            complete, rows = engine_capabilities.compute(
                "vinberg_root_enumeration",
                gram,
                coordinates,
                max_roots,
                max_decompositions,
            )
            roots = tuple(self(tuple(row)) for row in rows)
            return complete, tuple(-root for root in roots) if negated else roots

        def vinberg_simple_roots(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the roots Vinberg's algorithm accepted.

            The accepted roots are the outward normals of the walls of a
            fundamental polyhedron for \(W(L)\), taken in the order the
            algorithm's height function on the controlling vector produces
            them.  A search that ran to completion returns the whole wall set;
            a search stopped by ``max_roots`` or ``max_decompositions`` returns
            what it had, and :meth:`is_reflective` is then ``Unknown``.

            The controlling vector is the point of the hyperbolic space the
            enumeration measures height from.  Omitted, the engine picks one of
            negative square for itself.
            """
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return finite_ordered_set(roots)

        def is_reflective(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) has finite index in \(O(L)\), or ``Unknown``.

            Vinberg's algorithm establishes the fundamental polyhedron exactly
            when it has finite volume, so a completed search is a proof that
            the lattice is reflective.  A search that a bound stopped is not a
            proof of anything, and an unbounded search on a non-reflective
            lattice does not return, so this answers ``True`` or ``Unknown``
            and never ``False``.  Deciding non-reflectivity needs Allcock's
            edgewalk, which terminates on every input; see
            :meth:`allcock_edgewalk`.

            In signature \((1,1)\) the criterion is unreachable: the domain is
            a half-line in \(H^1\), of infinite volume, and the question is
            refused rather than answered.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            assert (positive, negative) != (1, 1), (
                "in signature (1,1) the fundamental domain is a half-line in "
                "H^1, of infinite volume, so no polyhedron criterion decides "
                "reflectivity"
            )
            complete, _roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return True if complete else Unknown

        def reflection_group(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return \(W(L)\leq O(L)\), generated by the reflections in the roots.

            The mirrors of the walls of a fundamental polyhedron generate the
            whole reflection subgroup (Vinberg 1972), so the generators are the
            reflections in the roots :meth:`vinberg_simple_roots` returns, and
            the result is a subgroup of the owned orthogonal group rather than
            an abstract Coxeter group.  Its Coxeter presentation is read from
            :meth:`reflection_coxeter_diagram`.

            On a search that did not complete, the group generated is a
            subgroup of \(W(L)\) and need not be all of it; ask
            :meth:`is_reflective` for the certificate.
            """
            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return self.O().subgroup([self.reflection(root) for root in roots])

        def reflection_coxeter_diagram(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the Coxeter diagram of the fundamental polyhedron.

            One vertex per wall, rooted in the accepted roots, so the diagram
            carries the exact pairings and separates parallel walls from
            divergent ones.  It is the diagram of \(W(L)\) as a Coxeter group
            when the search completed.
            """
            from dzack_research.preamble.categories.coxeter_diagrams import CoxeterDiagrams

            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return CoxeterDiagrams().from_roots(tuple(roots))

        def _chamber_vertex_squares(
            self, controlling_vector, max_roots, max_decompositions
        ):
            r"""Return the squares of the vertices of the fundamental polyhedron.

            The chamber is \(\{x : b(x,r)\leq 0\text{ for every wall } r\}\),
            which in coordinates is the cone dual to the one spanned by the
            rows \(rG\).  Its extreme rays are the vertices of the polyhedron,
            and the square of a ray decides its kind: negative inside the light
            cone, so an ordinary point of hyperbolic space, and zero on the
            cone, so an ideal point of the boundary.
            """
            from sage.geometry.cone import Cone

            gram = _engine_component_matrix(self.gram_tensor())
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            wall_normals = [engine_vector(root.to_vector()) * gram for root in roots]
            chamber = Cone(wall_normals).dual()
            return tuple(
                (engine_matrix(ray) * gram * engine_matrix(ray).transpose())[0][0]
                for ray in chamber.rays()
            )

        def is_cocompact(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) acts cocompactly, or ``Unknown``.

            A fundamental polyhedron is compact exactly when it has finite
            volume and no ideal vertex.  Finite volume is
            :meth:`is_reflective`; an ideal vertex is a vertex of square zero,
            lying on the light cone rather than inside it.  Stated on the
            squares rather than on their sign, the criterion does not depend on
            which sign convention the form carries.

            Not cocompact does not mean infinite covolume: a reflective lattice
            with an ideal vertex has a finite-volume noncompact fundamental
            domain, which is the common hyperbolic case.
            """
            reflective = self.is_reflective(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            if reflective is not True:
                return Unknown
            return all(
                square != 0
                for square in self._chamber_vertex_squares(
                    controlling_vector, max_roots, max_decompositions
                )
            )

        def fundamental_chamber(self):
            r"""Return the fundamental polyhedron of \(W(L)\) in \(L\otimes\mathbb R\).

            The category's stated contract, and its open work.  The walls are
            the mirrors of the roots :meth:`vinberg_simple_roots` enumerates,
            so the polyhedron is given by half-spaces, and the owned polytope
            surface (``categories/schemes/polytopes.py``) constructs a convex
            polytope from its vertices only.  Building this needs a
            half-space-presented polyhedron over \(L\otimes\mathbb R\), which
            the preamble does not own; :meth:`is_cocompact` reads the one fact
            that can be had without it.
            """
            assert False, (
                "the fundamental polyhedron needs a half-space-presented "
                "polyhedron over L tensor RR; the owned polytope surface "
                "builds a polytope from its vertices and cannot state a "
                "chamber by its walls"
            )

        def dominant_cone(self):
            r"""Return the dominant cone of \(W(L)\) inside \(L\otimes\mathbb R\).

            The closed cone cut out by the walls of
            :meth:`fundamental_chamber`.  The category's stated contract; it
            waits on the same half-space-presented surface.  The object lives
            in the base-changed parent \(L\otimes\mathbb R\) and not in \(L\),
            a cone being closed under positive real scaling.
            """
            assert False, (
                "the dominant cone lives in L tensor RR and needs the same "
                "half-space-presented surface as fundamental_chamber"
            )

        def chamber_complex(self):
            r"""Return the complex of \(W(L)\)-translates of the fundamental chamber.

            The category's stated contract.  The union of the translates is the
            Tits cone, on whose interior \(W(L)\) acts properly
            discontinuously.  It needs :meth:`fundamental_chamber` and a
            complex surface, and the preamble owns neither.
            """
            assert False, (
                "the chamber complex needs fundamental_chamber and a complex "
                "surface, neither of which the preamble owns"
            )

        def isotropic_elements_below_height(self, timelike, height):
            r"""Return the isotropic \(v\in L\) with \(\lvert b(v,t)\rvert\leq h\).

            The category's stated contract, and the enumeration a walk along
            the light cone needs.  On a hyperbolic lattice \(\{v : q(v)=0\}\)
            is infinite and a bound on the square bounds nothing, so the
            chosen timelike element is what makes the set finite and is a
            required argument.

            What is missing is the orthogonal complement of ``timelike`` as a
            subobject of \(L\): the complement is definite, the two bounds
            confine \(v\) to a finite region of it, and the definite
            short-vector enumeration then answers.  The live lattice surface
            has that enumeration and no operation producing the complement of a
            vector as a lattice with its inclusion.
            """
            assert False, (
                "the height-bounded isotropic enumeration needs the orthogonal "
                "complement of the timelike vector as a definite sublattice "
                "with its inclusion, which the live lattice surface does not "
                "produce; the definite short-vector enumeration cannot be "
                "applied to a hyperbolic lattice directly"
            )

        def allcock_edgewalk(self):
            r"""Return fundamental-domain data from Allcock's edgewalk.

            The category's stated contract.  A second producer of the object
            Vinberg's algorithm enumerates, walking the edges of a fundamental
            polyhedron; unlike Vinberg root enumeration it terminates on every
            input, so it decides reflectivity rather than semi-deciding it.
            The realization is the ``LORENTZ_FundDomain_AllcockEdgewalk``
            program of ``polyhedral_common``, which is not installed here, and
            no other available engine answers.
            """
            assert False, (
                "Allcock's edgewalk is realized by the "
                "LORENTZ_FundDomain_AllcockEdgewalk program of "
                "polyhedral_common, which is not installed; without it "
                "reflectivity is semi-decided by Vinberg's algorithm and "
                "non-reflectivity is not decided at all"
            )


__all__ = ["HyperbolicLattices"]
