r"""Hyperbolic lattices and the reflection algorithms that run on them.

A lattice is hyperbolic when its form has exactly one negative index of
inertia, so that the real points \(L\otimes\mathbb R\) carry a light cone and
\(O(L)\) acts on the hyperbolic space of one of its two halves.  The mirror of
a root \(r\) is the hyperplane \(r^{\perp}\), and the reflection subgroup
\(W(L)\leq O(L)\) is generated by the reflections in the roots.

Vinberg's algorithm (Vinberg, *On groups of unit elements of certain quadratic
forms*, Mat. Sb. 87 (1972); *Hyperbolic reflection groups*, Russian Math.
Surveys 40 (1985)) enumerates the walls of a fundamental polyhedron for
\(W(L)\), starting from a chosen controlling vector.  It is a semi-decision
procedure: it halts with a certificate when the polyhedron closes, which is to
say when \(W(L)\) has finite covolume, and runs forever otherwise.  So
:meth:`is_reflective` here answers ``True`` or ``Unknown`` and never ``False``:
a bounded search that did not close proves nothing.

This repository's convention makes root squares negative, so its hyperbolic
lattices have signature \((1,n)\).  The engine's convention is \((n,1)\), and
the twist by \(-1\) is the transport between them; it is written out at each
site rather than assumed, and the roots come back negated because negating the
form reverses every half-space condition \(b(x,r)\leq 0\).
"""

from sage.arith.misc import divisors
from sage.matrix.constructor import matrix as engine_matrix
from sage.misc.cachefunc import cached_method
from sage.misc.unknown import Unknown
from sage.modules.free_module_element import vector as engine_vector
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.lattices import Lattices
from dzack_research.preamble.categories.rings.ring_foundation import (
    OwnedCategoryOverBaseRing,
    _own_ring,
)
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.engine_capabilities import engine_capabilities
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors.tensor import _engine_component_matrix


_VINAL_PROVISIONING = (
    "install VinAl into the Sage environment with "
    "`sage -pip install git+https://github.com/dzackgarza/vinal`"
)

_EDGEWALK_PROVISIONING = (
    "build polyhedral_common (github.com/MathieuDutSik/polyhedral_common) and "
    "put LORENTZ_ReflectiveEdgewalk on PATH"
)


def _vinal_is_available() -> bool:
    from importlib.util import find_spec

    return find_spec("vinal") is not None


def _vinal_vinberg_roots(gram, controlling_vector, max_roots, max_decompositions):
    r"""Run Vinberg's algorithm on a Gram matrix of signature \((n,1)\).

    Returns the completeness flag of the search and the coordinate rows of the
    accepted roots.  ``vinal`` is Bogachev and Perepechko's implementation of
    the algorithm; ``FindRoots`` reports whether the fundamental polyhedron was
    established, which is the algorithm's own termination criterion.
    """
    from vinal import VinAl

    algorithm = VinAl(gram, controlling_vector, False, None)
    complete = algorithm.FindRoots(
        max_roots=max_roots, max_decompositions=max_decompositions
    )
    return bool(complete), tuple(tuple(root) for root in algorithm.roots)


def _edgewalk_is_available() -> bool:
    from py_polyhedral.binaries import binary_available

    return binary_available("LORENTZ_ReflectiveEdgewalk")


def _polyhedral_common_edgewalk(gram):
    r"""Run Allcock's edgewalk on a Gram matrix of signature \((n,1)\).

    Returns the reflectivity decision and the coordinate rows of the simple
    roots.  ``LORENTZ_ReflectiveEdgewalk`` is the driver of
    ``polyhedral_common`` that calls ``StandardEdgewalkAnalysis`` with early
    termination on a non-reflective input, so the decision is total and the
    simple roots are reported exactly when the fundamental polyhedron exists.
    """
    from py_polyhedral.binaries import lorentzian_reflective_edgewalk

    record = lorentzian_reflective_edgewalk([list(row) for row in gram.rows()])
    reflective = bool(record["is_reflective"])
    rows = record["ListSimpleRoots"] if reflective else ()
    return reflective, tuple(tuple(row) for row in rows)


engine_capabilities.register(
    "vinberg_root_enumeration",
    "vinal",
    _vinal_vinberg_roots,
    available=_vinal_is_available,
    provisioning=_VINAL_PROVISIONING,
)

engine_capabilities.register(
    "lorentzian_edgewalk_fundamental_domain",
    "polyhedral-common-via-py-polyhedral",
    _polyhedral_common_edgewalk,
    available=_edgewalk_is_available,
    provisioning=_EDGEWALK_PROVISIONING,
)


class HyperbolicLattices(OwnedCategoryOverBaseRing):
    r"""Lattices whose form has exactly one negative index of inertia.

    A lattice enters this category by being handed to it:
    ``HyperbolicLattices(ZZ)(L)`` checks the signature and refines ``L``,
    returning the same object with the reflection algorithms available on it.
    """

    @classmethod
    def _repr_object_names(cls):
        return "hyperbolic lattices"

    def an_object(self):
        r"""The hyperbolic plane \(U\), of signature \((1,1)\)."""
        return self(Lattices(self.base_ring())("U"))

    def super_categories(self):
        return [Lattices(self.base_ring())]

    def _call_(self, lattice):
        r"""Return ``lattice`` refined into this category.

        The hypothesis is the signature: exactly one index of inertia is
        negative, or exactly one is positive.  Both spellings are hyperbolic,
        and which of them occurs is a convention about the sign of the form,
        not a fact about the geometry.
        """
        signature = lattice.signature_pair()
        positive, negative = signature.first(), signature.second()
        assert 1 in (positive, negative), (
            f"a hyperbolic lattice has exactly one index of inertia equal to "
            f"one; this lattice has signature ({positive}, {negative})"
        )
        return refine(lattice, self)

    class ParentMethods:
        def possible_root_lengths(self):
            r"""Return the values \(\lvert q(r)\rvert\) a root of this lattice can take.

            Vinberg's criterion: for a root \(r\) the crystallographic
            condition \(2b(x,r)/q(r)\in R\) for all \(x\in L\) forces \(q(r)\)
            to divide twice the last invariant factor of the correlation
            \(L\to L^{\vee}\), which is the exponent of the discriminant group
            \(A_L\).  The bound is what turns "does this lattice have a root of
            such a length" into a finite question.

            Stated here because it is the bound Vinberg's algorithm searches
            under; the hypothesis it actually needs is nondegeneracy, not
            hyperbolicity.
            """
            correlation = _engine_component_matrix(self.gram_tensor())
            invariant_factors = correlation.elementary_divisors()
            assert invariant_factors[-1] != 0, (
                "the root-length bound needs a nondegenerate correlation; this "
                "lattice has a radical, so its discriminant group is infinite "
                "and no finite set of lengths bounds its roots"
            )
            return finite_ordered_set(tuple(divisors(2 * invariant_factors[-1])))

        def _engine_gram_of_signature_n_1(self):
            r"""Return a Gram matrix in the engine's \((n,1)\) convention.

            Returns the matrix together with whether the form was negated to
            reach that convention, since a negated form reverses every
            half-space condition and so negates the roots.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            match positive, negative:
                case _, 1:
                    return _engine_component_matrix(self.gram_tensor()), False
                case 1, _:
                    return _engine_component_matrix(self.twist(-1).gram_tensor()), True
                case _:
                    assert False, (
                        f"the reflection algorithms need signature (1, n) or "
                        f"(n, 1); this lattice has ({positive}, {negative})"
                    )

        @cached_method
        def _vinberg_search(self, controlling_vector, max_roots, max_decompositions):
            r"""Run Vinberg's algorithm and return completeness with the roots.

            The algorithm is stated for a lattice over any totally real ring of
            integers, where a root row is a vector over that ring and the
            height comparison is made in every real embedding.  The available
            realization works over the integers only, so the wider case is a
            stated absence rather than a silent coercion.
            """
            assert self.base_ring() is _own_ring(SageZZ), (
                "the available realization of Vinberg's algorithm works over "
                "the integers; over a totally real ring of integers the "
                "algorithm is the same and the root rows carry entries of that "
                "ring.  Bottinelli's VinbergsAlgorithmNF "
                "(github.com/bottine/VinbergsAlgorithmNF) computes them, and "
                "no realization registered here does"
            )
            gram, negated = self._engine_gram_of_signature_n_1()
            coordinates = (
                None if controlling_vector is None else list(controlling_vector.to_vector())
            )
            complete, rows = engine_capabilities.compute(
                "vinberg_root_enumeration",
                gram,
                coordinates,
                max_roots,
                max_decompositions,
            )
            roots = tuple(self(tuple(row)) for row in rows)
            return complete, tuple(-root for root in roots) if negated else roots

        def vinberg_simple_roots(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the roots Vinberg's algorithm accepted.

            The accepted roots are the outward normals of the walls of a
            fundamental polyhedron for \(W(L)\), taken in the order the
            algorithm's height function on the controlling vector produces
            them.  A search that ran to completion returns the whole wall set;
            a search stopped by ``max_roots`` or ``max_decompositions`` returns
            what it had, and :meth:`is_reflective` is then ``Unknown``.

            The controlling vector is the point of the hyperbolic space the
            enumeration measures height from.  Omitted, the engine picks one of
            negative square for itself.
            """
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return finite_ordered_set(roots)

        def is_reflective(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) has finite index in \(O(L)\), or ``Unknown``.

            Vinberg's algorithm establishes the fundamental polyhedron exactly
            when it has finite volume, so a completed search is a proof that
            the lattice is reflective.  A search that a bound stopped is not a
            proof of anything, and an unbounded search on a non-reflective
            lattice does not return, so this answers ``True`` or ``Unknown``
            and never ``False``.  Deciding non-reflectivity needs Allcock's
            edgewalk, which terminates on every input; see
            :meth:`edgewalk_is_reflective`.

            In signature \((1,1)\) the criterion is unreachable: the domain is
            a half-line in \(H^1\), of infinite volume, and the question is
            refused rather than answered.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            assert (positive, negative) != (1, 1), (
                "in signature (1,1) the fundamental domain is a half-line in "
                "H^1, of infinite volume, so no polyhedron criterion decides "
                "reflectivity"
            )
            complete, _roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return True if complete else Unknown

        def reflection_group(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return \(W(L)\leq O(L)\), generated by the reflections in the roots.

            The mirrors of the walls of a fundamental polyhedron generate the
            whole reflection subgroup (Vinberg 1972), so the generators are the
            reflections in the roots :meth:`vinberg_simple_roots` returns, and
            the result is a subgroup of the owned orthogonal group rather than
            an abstract Coxeter group.  Its Coxeter presentation is read from
            :meth:`reflection_coxeter_diagram`.

            On a search that did not complete, the group generated is a
            subgroup of \(W(L)\) and need not be all of it; ask
            :meth:`is_reflective` for the certificate.
            """
            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return self.O().subgroup([self.reflection(root) for root in roots])

        def reflection_coxeter_diagram(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the Coxeter diagram of the fundamental polyhedron.

            One vertex per wall, rooted in the accepted roots, so the diagram
            carries the exact pairings and separates parallel walls from
            divergent ones.  It is the diagram of \(W(L)\) as a Coxeter group
            when the search completed.
            """
            from dzack_research.preamble.categories.coxeter_diagrams import CoxeterDiagrams

            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return CoxeterDiagrams().from_roots(tuple(roots))

        def _chamber_vertex_squares(
            self, controlling_vector, max_roots, max_decompositions
        ):
            r"""Return the squares of the vertices of the fundamental polyhedron.

            The chamber is \(\{x : b(x,r)\leq 0\text{ for every wall } r\}\),
            which in coordinates is the cone dual to the one spanned by the
            rows \(rG\).  Its extreme rays are the vertices of the polyhedron,
            and the square of a ray decides its kind: negative inside the light
            cone, so an ordinary point of hyperbolic space, and zero on the
            cone, so an ideal point of the boundary.
            """
            from sage.geometry.cone import Cone

            gram = _engine_component_matrix(self.gram_tensor())
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            wall_normals = [engine_vector(root.to_vector()) * gram for root in roots]
            chamber = Cone(wall_normals).dual()
            return tuple(
                (engine_matrix(ray) * gram * engine_matrix(ray).transpose())[0][0]
                for ray in chamber.rays()
            )

        def is_cocompact(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) acts cocompactly, or ``Unknown``.

            A fundamental polyhedron is compact exactly when it has finite
            volume and no ideal vertex.  Finite volume is
            :meth:`is_reflective`; an ideal vertex is a vertex of square zero,
            lying on the light cone rather than inside it.  Stated on the
            squares rather than on their sign, the criterion does not depend on
            which sign convention the form carries.

            Not cocompact does not mean infinite covolume: a reflective lattice
            with an ideal vertex has a finite-volume noncompact fundamental
            domain, which is the common hyperbolic case.
            """
            reflective = self.is_reflective(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            if reflective is not True:
                return Unknown
            return all(
                square != 0
                for square in self._chamber_vertex_squares(
                    controlling_vector, max_roots, max_decompositions
                )
            )

        def fundamental_chamber(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the exact root-half-space cone cut out by Vinberg's walls.

            The chamber is ``{x : b(r,x) >= 0 for every accepted wall r}``.
            It retains those roots and their actual correlation covectors; the
            completion flag records whether the Vinberg search established the
            full wall set or only a bounded exploration prefix.
            """
            from dzack_research.preamble.categories.polyhedral_cones import (
                rational_polyhedral_cone,
            )

            complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            correlation = self.algebraic_correlation_morphism()
            return rational_polyhedral_cone(
                self,
                tuple(correlation(root) for root in roots),
                wall_roots=roots,
                complete=complete,
            )

        def dominant_cone(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the closed dominant cone defined by the selected simple roots."""
            return self.fundamental_chamber(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )

        def chamber_complex(self):
            r"""Return the complex of Weyl translates of the fundamental chamber.

            The fundamental chamber is now owned exactly.  The remaining
            operation is a locally finite complex of its translates with face
            incidences and stabilizers; no such complex owner exists yet.
            """
            assert False, (
                "the exact fundamental chamber exists, but the chamber complex "
                "still needs an owned locally finite polyhedral-complex surface"
            )

        def isotropic_elements_below_height(self, timelike, height):
            r"""Return the isotropic \(v\in L\) with \(\lvert b(v,t)\rvert\leq h\).

            Put \(d=q(t)\) and \(a=b(v,t)\).  Then

            \[
              w=dv-at\in t^\perp, \qquad q(w)=-a^2d,
            \]

            and conversely \(v=(w+at)/d\) whenever that quotient is integral.
            Thus the height bound leaves only the finitely many integers
            \(-h\leq a\leq h\); for each one the possible \(w\)'s form one
            finite shell in the definite lattice \(t^\perp\).  The final
            divisibility check is exactly the condition that the rational
            reconstruction lies back in \(L\).
            """
            integers = _own_ring(SageZZ)
            assert self.base_ring() is integers, (
                "the exact height enumeration currently uses integral shells over ZZ"
            )
            if timelike.parent() is not self:
                timelike = self(timelike)
            height = integers(height)
            assert height >= integers.zero(), "a height bound is nonnegative"

            square = timelike.q()
            assert square != integers.zero(), "a timelike vector has nonzero square"
            complement = timelike.orthogonal_complement()
            assert complement.is_definite(), (
                "the chosen vector is timelike exactly when its orthogonal complement is definite"
            )
            inclusion = complement.inclusion()

            isotropic = []
            for height_value in range(-int(height), int(height) + 1):
                pairing = integers(height_value)
                target_square = -(pairing * pairing * square)
                match pairing == integers.zero():
                    case True:
                        shell = (complement.zero(),)
                    case False:
                        shell = complement.vectors_of_square(target_square)
                for perpendicular in shell:
                    numerator = inclusion(perpendicular) + pairing * timelike
                    coordinates = numerator.to_tuple()
                    if not all(square.divides(coordinate) for coordinate in coordinates):
                        continue
                    candidate = self(
                        tuple(coordinate // square for coordinate in coordinates)
                    )
                    if candidate.q() != integers.zero():
                        raise ArithmeticError(
                            "the height-shell reconstruction produced a non-isotropic vector"
                        )
                    if self.b(candidate, timelike) != pairing:
                        raise ArithmeticError(
                            "the height-shell reconstruction produced the wrong pairing"
                        )
                    isotropic.append(candidate)
            return finite_ordered_set(tuple(isotropic))

        @cached_method
        def _edgewalk(self):
            r"""Run Allcock's edgewalk and return the decision with the roots.

            A second producer of the object Vinberg's algorithm enumerates,
            walking the edges of a fundamental polyhedron rather than growing
            it from a controlling vector.  It takes no controlling vector and
            no bound, because it terminates on every input.

            The engine works in signature \((n,1)\), so the roots come back
            negated whenever the transport negated the form, exactly as in
            :meth:`_vinberg_search`.
            """
            assert self.base_ring() is _own_ring(SageZZ), (
                "the available realization of the edgewalk carries its root "
                "coordinates in a fixed integral type, so it walks the "
                "polyhedron of an integral lattice; no realization registered "
                "here walks one over a wider ring"
            )
            gram, negated = self._engine_gram_of_signature_n_1()
            reflective, rows = engine_capabilities.compute(
                "lorentzian_edgewalk_fundamental_domain",
                gram,
            )
            roots = tuple(self(tuple(row)) for row in rows)
            return reflective, tuple(-root for root in roots) if negated else roots

        def edgewalk_is_reflective(self) -> bool:
            r"""Return whether \(W(L)\) has finite index in \(O(L)\).

            A decision, unlike :meth:`is_reflective`: the edgewalk terminates
            on every input, reporting the fundamental polyhedron when there is
            one and the obstruction when there is not, so this answers ``True``
            or ``False`` and never ``Unknown``.  The two methods answer the
            same mathematical question and are kept apart because they prove
            different things, not because they use different engines.
            """
            reflective, _roots = self._edgewalk()
            return reflective

        def edgewalk_simple_roots(self):
            r"""Return the simple roots of the polyhedron the edgewalk walked.

            The outward normals of the walls of a fundamental polyhedron for
            \(W(L)\), the same wall set :meth:`vinberg_simple_roots` produces
            from a completed search.  A non-reflective lattice has no such
            polyhedron, and the set is then empty; ask
            :meth:`edgewalk_is_reflective` to tell that case from a lattice
            whose polyhedron has no walls.
            """
            _reflective, roots = self._edgewalk()
            return finite_ordered_set(roots)


__all__ = ["HyperbolicLattices"]
