r"""Hyperbolic lattices and the reflection algorithms that run on them.

A lattice is hyperbolic when its form has exactly one negative index of
inertia, so that the real points \(L\otimes\mathbb R\) carry a light cone and
\(O(L)\) acts on the hyperbolic space of one of its two halves.  The mirror of
a root \(r\) is the hyperplane \(r^{\perp}\), and the reflection subgroup
\(W(L)\leq O(L)\) is generated by the reflections in the roots.

Vinberg's algorithm (Vinberg, *On groups of unit elements of certain quadratic
forms*, Mat. Sb. 87 (1972); *Hyperbolic reflection groups*, Russian Math.
Surveys 40 (1985)) enumerates the walls of a fundamental polyhedron for
\(W(L)\), starting from a chosen controlling vector.  It is a semi-decision
procedure: it halts with a certificate when the polyhedron closes, which is to
say when \(W(L)\) has finite covolume, and runs forever otherwise.  So
:meth:`is_reflective` here answers ``True`` or ``Unknown`` and never ``False``:
a bounded search that did not close proves nothing.

This repository's convention makes root squares negative, so its hyperbolic
lattices have signature \((1,n)\).  The engine's convention is \((n,1)\), and
the twist by \(-1\) is the transport between them; it is written out at each
site rather than assumed, and the roots come back negated because negating the
form reverses every half-space condition \(b(x,r)\leq 0\).
"""

from importlib.util import find_spec
from pathlib import Path

from sage.arith.misc import divisors
from sage.matrix.constructor import matrix as engine_matrix
from sage.misc.cachefunc import cached_method
from sage.misc.unknown import Unknown
from sage.modules.free_module_element import vector as engine_vector
from sage.rings.integer_ring import ZZ as SageZZ
from sage.rings.qqbar import AA as SageAA
from sage.rings.rational_field import QQ as SageQQ
from sage.structure.sage_object import SageObject

from dzack_research.preamble.categories.lattices import Lattices
from dzack_research.preamble.categories._lattice import signature_pair
from dzack_research.preamble.categories.rings.ring_foundation import _owned_engine_element
from dzack_research.preamble.categories.rings.ring_foundation import (
    OwnedCategoryOverBaseRing,
    _engine_element,
    _engine_ring,
    _own_ring,
)
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.engine_capabilities import engine_capabilities
from dzack_research.preamble.refine import refine
from dzack_research.preamble.tensors.tensor import _engine_component_matrix

_VINAL_PROVISIONING = (
    "install VinAl into the Sage environment with "
    "`sage -pip install git+https://github.com/dzackgarza/vinal`"
)

_EDGEWALK_PROVISIONING = (
    "build polyhedral_common (github.com/MathieuDutSik/polyhedral_common) and "
    "put LORENTZ_ReflectiveEdgewalk on PATH"
)

_VINBERG_NF_PROJECT = (
    Path(__file__).resolve().parents[4]
    / "src.bak"
    / "backends"
    / "external"
    / "vinbergs_algorithm"
    / "references"
    / "VinbergsAlgorithmNF"
)

_VINBERG_NF_PROVISIONING = (
    "install github.com/dzackgarza/sage-julia-bridge into Sage's environment, "
    "make Julia available to that bridge, and instantiate the pinned "
    f"VinbergsAlgorithmNF project at {_VINBERG_NF_PROJECT}"
)

_VINBERG_NF_ADAPTER_SOURCE = r'''
module DzackResearchVinbergNFAdapter
using Hecke
using VinbergsAlgorithmNF
const VA = VinbergsAlgorithmNF

_qq(pair) = QQ(BigInt(pair[1])) // QQ(BigInt(pair[2]))

function _field(polynomial_coefficients)
    polynomial_ring, x = Hecke.polynomial_ring(QQ, "x")
    polynomial = polynomial_ring(0)
    for (index, coefficient) in enumerate(polynomial_coefficients)
        polynomial += _qq(coefficient) * x^(index - 1)
    end
    return Hecke.number_field(polynomial, "a")
end

function _element(field, generator, coefficients)
    value = field(0)
    for (index, coefficient) in enumerate(coefficients)
        value += field(_qq(coefficient)) * generator^(index - 1)
    end
    return value
end

function _pair(value)
    q = QQ(value)
    return [string(numerator(q)), string(denominator(q))]
end

function _serialize(field, value)
    degree = Hecke.degree(field)
    return [_pair(coeff(value, index)) for index in 0:degree-1]
end

function vinberg_roots(
    polynomial_coefficients,
    gram_coefficients,
    selected_primitive_approximation,
    count,
)
    field, generator = _field(polynomial_coefficients)
    degree = Hecke.degree(field)
    if degree != 2
        error("the represented VinbergsAlgorithmNF adapter currently supports real quadratic fields")
    end

    places = Hecke.infinite_places(field)
    if length(places) != 2
        error("the represented VinbergsAlgorithmNF adapter requires a totally real quadratic field")
    end
    target = parse(BigFloat, selected_primitive_approximation)
    first = BigFloat(Hecke.conjugates_real(generator, 128)[1])
    second = BigFloat(Hecke.conjugates_real(generator, 128)[2])
    swap = abs(second - target) < abs(first - target)
    linear_coefficient = _qq(polynomial_coefficients[2])
    selected_generator = swap ? -linear_coefficient - generator : generator

    dimension = length(gram_coefficients)
    flat = Any[]
    for row in gram_coefficients
        if length(row) != dimension
            error("the Vinberg Gram matrix is not square")
        end
        append!(flat, [_element(field, selected_generator, entry) for entry in row])
    end
    gram = Hecke.matrix(field, dimension, dimension, flat)
    data = VA.VinbergData(field, gram)
    status, (roots, _dict, _diagram) = VA.next_n_roots!(data, n = Int(count))

    inverse_generator = selected_generator
    serialized = Any[]
    for root in roots
        row = Any[]
        for entry in root
            if swap
                coefficients = [coeff(entry, index) for index in 0:degree-1]
                entry = _element(field, inverse_generator, [_pair(c) for c in coefficients])
            end
            push!(row, _serialize(field, entry))
        end
        push!(serialized, row)
    end
    return [Bool(status), serialized]
end
end
'''


def _vinberg_nf_available() -> bool:
    return find_spec("sage_julia_bridge") is not None and _VINBERG_NF_PROJECT.is_dir()


def _rational_pair(value):
    value = SageQQ(value)
    return (int(value.numerator()), int(value.denominator()))


def _framing_coordinates(element):
    r"""Return ordered framing coefficients at a private engine boundary."""
    parent = element.parent()
    coefficients = parent.framing_coefficients(element)
    zero = parent.base_ring().zero()
    return tuple(
        coefficients.get(label, zero)
        for label in parent.module_generating_set()
    )


def _number_field_coefficients(field_engine, value):
    value = field_engine(value)
    degree = int(field_engine.degree())
    coefficients = tuple(value.list())
    return tuple(
        _rational_pair(coefficients[index] if index < len(coefficients) else SageQQ.zero())
        for index in range(degree)
    )


def _vinberg_nf_bridge():
    from sage_julia_bridge import julia

    if not julia.sage("isdefined(Main, :DzackResearchVinbergNFAdapter)"):
        old_project = julia.sage("Base.active_project()")
        julia.eval(f'import Pkg; Pkg.activate("{_VINBERG_NF_PROJECT}")')
        try:
            julia.eval("using Hecke; using VinbergsAlgorithmNF")
            julia.eval(_VINBERG_NF_ADAPTER_SOURCE)
        finally:
            if old_project:
                julia.eval(f'import Pkg; Pkg.activate("{Path(old_project).parent}")')
    return julia


def _vinberg_nf_roots(polynomial, gram, selected_primitive_approximation, count):
    result = _vinberg_nf_bridge().call(
        "DzackResearchVinbergNFAdapter.vinberg_roots",
        polynomial,
        gram,
        selected_primitive_approximation,
        int(count),
    )
    complete, roots = result
    return bool(complete), tuple(tuple(entry for entry in row) for row in roots)


engine_capabilities.register(
    "number_field_vinberg_root_enumeration",
    "VinbergsAlgorithmNF-via-sage-julia-bridge",
    _vinberg_nf_roots,
    available=_vinberg_nf_available,
    provisioning=_VINBERG_NF_PROVISIONING,
)


def _signature_at_real_embedding(lattice, embedding):
    order = lattice.base_ring()
    field = order.fraction_field()
    rank = int(lattice.module_rank())
    rows = []
    for i in range(rank):
        row = []
        for j in range(rank):
            entry = field(lattice.gram_tensor()[i, j])
            image = embedding(entry)
            row.append(SageAA(_engine_element(embedding.codomain(), image)))
        rows.append(row)
    eigenvalues = engine_matrix(SageAA, rows).eigenvalues()
    positive = sum(value > 0 for value in eigenvalues)
    negative = sum(value < 0 for value in eigenvalues)
    radical = sum(value == 0 for value in eigenvalues)
    if radical:
        raise ValueError(
            f"{lattice} is degenerate at the real place {embedding}: the form has {radical} "
            f"zero eigenvalues there, and Vinberg's algorithm needs a nondegenerate form "
            f"at every real place"
        )
    return signature_pair(int(positive), int(negative))


class NumberFieldVinbergLattice(SageObject):
    r"""A lattice over ``O_K`` together with its distinguished hyperbolic real place.

    This is the arithmetic convention used by Bottinelli's
    ``VinbergsAlgorithmNF``: at the distinguished place the form has signature
    ``(n,1)``, while every other real conjugate is positive definite.  It is
    deliberately a different equipped object from :class:`HyperbolicLattices`,
    whose integral ``ZZ`` convention negates the form so roots have negative
    square.
    """

    def __init__(self, lattice, real_embedding) -> None:
        order = lattice.base_ring()
        field = order.fraction_field()
        real_algebraics = _own_ring(SageAA)
        assert int(field.degree()) == 2, (
            f"cannot run Vinberg's algorithm on {lattice} over {field}: the algorithm "
            f"holds over any totally real field, but the available implementation "
            f"(VinbergsAlgorithmNF) handles real quadratic fields only, and {field} has "
            f"degree {field.degree()}"
        )
        signature = field.signature()
        if int(signature.second()) != 0:
            raise ValueError(
                f"cannot run Vinberg's algorithm on {lattice}: its field of fractions "
                f"{field} must be totally real, but it has signature {signature}"
            )
        assert int(field.class_number()) == 1, (
            f"cannot run Vinberg's algorithm on {lattice} over {field}: the available "
            f"implementation (VinbergsAlgorithmNF) takes gcds of elements, which is "
            f"correct only when O_K is a principal ideal domain, and {field} has class "
            f"number {field.class_number()}"
        )
        if _engine_ring(order) != _engine_ring(field).ring_of_integers():
            raise ValueError(
                f"cannot run Vinberg's algorithm on {lattice}: it must be a lattice over "
                f"the ring of integers of {field}, but its base ring is {order}"
            )
        if real_embedding.domain() is not field or real_embedding.codomain() is not real_algebraics:
            raise ValueError(
                f"{real_embedding} cannot be the hyperbolic real place of {lattice}: it "
                f"must be an embedding {field} -> {real_algebraics}, but it is a map "
                f"{real_embedding.domain()} -> {real_embedding.codomain()}"
            )

        embeddings = field.embeddings(real_algebraics)
        if real_embedding not in embeddings:
            raise ValueError(
                f"{real_embedding} cannot be the hyperbolic real place of {lattice}: it is "
                f"not one of the real embeddings {embeddings} of {field}"
            )
        selected_position = embeddings.ranking_map()(real_embedding)
        selected_signature = _signature_at_real_embedding(lattice, real_embedding)
        rank = int(lattice.module_rank())
        if (
            selected_signature.first() != rank - 1
            or selected_signature.second() != 1
        ):
            raise ValueError(
                f"{lattice} is not hyperbolic at the real place {real_embedding}: it must "
                f"have signature ({rank - 1}, 1) there, but has {selected_signature}"
            )
        other_signatures = finite_ordered_set(tuple(
            _signature_at_real_embedding(lattice, embeddings[position])
            for position in embeddings.index_set()
            if position != selected_position
        ))
        if any(
            other.first() != rank or other.second() != 0
            for other in other_signatures
        ):
            raise ValueError(
                f"cannot run Vinberg's algorithm on {lattice} with hyperbolic place "
                f"{real_embedding}: at every other real place the form must be positive "
                f"definite, of signature ({rank}, 0), but the signatures there are "
                f"{other_signatures}"
            )

        self._lattice = lattice
        self._real_embedding = real_embedding
        self._selected_signature = selected_signature
        self._other_signatures = other_signatures

    def lattice(self):
        return self._lattice

    def real_embedding(self):
        return self._real_embedding

    def signature_at_selected_place(self):
        return self._selected_signature

    def other_signatures(self):
        return self._other_signatures

    def _serialized_field(self):
        field = self.lattice().base_ring().fraction_field()
        engine = _engine_ring(field)
        degree = int(engine.degree())
        coefficients = tuple(engine.defining_polynomial().list())
        return tuple(
            _rational_pair(
                coefficients[index]
                if index < len(coefficients)
                else SageQQ.zero()
            )
            for index in range(degree + 1)
        )

    def _serialized_gram(self):
        lattice = self.lattice()
        order = lattice.base_ring()
        field = order.fraction_field()
        field_engine = _engine_ring(field)
        order_engine = _engine_ring(order)
        rank = int(lattice.module_rank())
        return tuple(
            tuple(
                _number_field_coefficients(
                    field_engine,
                    field_engine(
                        order_engine(
                            _engine_element(order, lattice.gram_tensor()[i, j])
                        )
                    ),
                )
                for j in range(rank)
            )
            for i in range(rank)
        )

    def _selected_primitive_approximation(self):
        field = self.lattice().base_ring().fraction_field()
        image = self.real_embedding()(field.primitive_element())
        backend = _engine_element(_own_ring(SageAA), image)
        return str(backend.n(128))

    def _cross_root(self, serialized_row):
        lattice = self.lattice()
        order = lattice.base_ring()
        field = order.fraction_field()
        field_engine = _engine_ring(field)
        order_engine = _engine_ring(order)
        generator = field_engine.gen()
        coefficients = []
        for serialized_entry in serialized_row:
            value = field_engine.zero()
            for exponent, pair in enumerate(serialized_entry):
                numerator, denominator = pair
                value += SageQQ(numerator) / SageQQ(denominator) * generator**exponent
            integral = order_engine(value)
            coefficients.append(_owned_engine_element(order, integral))
        root = lattice(tuple(coefficients))
        if root.q() <= 0:
            raise ArithmeticError(
                f"VinbergsAlgorithmNF returned {root} as a root of {lattice}, but a root must "
                f"have positive square and q({root}) = {root.q()}"
            )
        return root

    def vinberg_simple_roots(self, *, count):
        r"""Return ``(complete, roots)`` from the pinned number-field Vinberg engine."""
        if int(count) <= 0:
            raise ValueError(
                f"cannot ask Vinberg's algorithm on {self.lattice()} for {count} simple "
                f"roots: the number of roots must be positive"
            )
        complete, rows = engine_capabilities.compute(
            "number_field_vinberg_root_enumeration",
            self._serialized_field(),
            self._serialized_gram(),
            self._selected_primitive_approximation(),
            int(count),
        )
        roots = finite_ordered_set(tuple(self._cross_root(row) for row in rows))
        return complete, roots

    def __repr__(self) -> str:
        return f"Number-field Vinberg lattice ({self.lattice()}, {self.real_embedding()})"


def _vinal_is_available() -> bool:
    from importlib.util import find_spec

    return find_spec("vinal") is not None


def _vinal_vinberg_roots(gram, controlling_vector, max_roots, max_decompositions):
    r"""Run Vinberg's algorithm on a Gram matrix of signature \((n,1)\).

    Returns the completeness flag of the search and the coordinate rows of the
    accepted roots.  ``vinal`` is Bogachev and Perepechko's implementation of
    the algorithm; ``FindRoots`` reports whether the fundamental polyhedron was
    established, which is the algorithm's own termination criterion.
    """
    from vinal import VinAl

    algorithm = VinAl(gram, controlling_vector, False, None)
    complete = algorithm.FindRoots(
        max_roots=max_roots, max_decompositions=max_decompositions
    )
    return bool(complete), tuple(tuple(root) for root in algorithm.roots)


def _edgewalk_is_available() -> bool:
    from py_polyhedral.binaries import binary_available

    return binary_available("LORENTZ_ReflectiveEdgewalk")


def _polyhedral_common_edgewalk(gram):
    r"""Run Allcock's edgewalk and normalize its full fundamental-domain record.

    ``LORENTZ_ReflectiveEdgewalk`` calls ``StandardEdgewalkAnalysis`` and its
    Python serializer returns the simple roots, orbit representatives of the
    polyhedron vertices, the reflectivity decision, and generators of the
    finite isometry group of the Coxeter polyhedron.  This adapter verifies
    the integral root/isometry data against ``gram`` before it crosses into
    owned lattice objects.
    """
    from py_polyhedral.binaries import lorentzian_reflective_edgewalk

    record = lorentzian_reflective_edgewalk([list(row) for row in gram.rows()])
    reflective = bool(record["is_reflective"])
    match reflective:
        case True:
            simple_root_rows = tuple(
                tuple(SageZZ(entry) for entry in row)
                for row in record["ListSimpleRoots"]
            )
        case False:
            simple_root_rows = ()
    for row in simple_root_rows:
        root = engine_matrix(SageZZ, [row])
        square = (root * gram * root.transpose())[0, 0]
        match square == 0:
            case True:
                raise ArithmeticError(
                    f"Allcock's edgewalk returned the simple root {row} for the Gram matrix "
                    f"{gram.rows()}, but it is isotropic, and a root must have nonzero square"
                )
            case False:
                pass
        pairings = gram * root.transpose()
        match any((2 * entry[0]) % square != 0 for entry in pairings.rows()):
            case True:
                raise ArithmeticError(
                    f"Allcock's edgewalk returned the simple root {row} of square {square} "
                    f"for the Gram matrix {gram.rows()}, but its reflection does not "
                    f"preserve the lattice: 2 b(x, r) / q(r) is not an integer for every "
                    f"basis vector x"
                )
            case False:
                pass

    vertices = tuple(
        (
            tuple(SageZZ(entry) for entry in vertex["gen"]),
            tuple(
                tuple(SageZZ(entry) for entry in row)
                for row in vertex["l_roots"]
            ),
        )
        for vertex in record["ListVertices"]
    )
    isometry_rows = tuple(
        tuple(tuple(SageZZ(entry) for entry in row) for row in generator)
        for generator in record["GrpIsomCoxMatr"]
    )
    for rows in isometry_rows:
        generator = engine_matrix(SageZZ, rows)
        match generator * gram * generator.transpose() == gram:
            case True:
                pass
            case False:
                raise ArithmeticError(
                    f"Allcock's edgewalk returned {rows} as an isometry of the Coxeter "
                    f"polyhedron, but it does not preserve the form with Gram matrix "
                    f"{gram.rows()}"
                )
    return {
        "simple_root_rows": simple_root_rows,
        "vertices": vertices,
        "is_reflective": reflective,
        "isometry_generator_rows": isometry_rows,
    }


engine_capabilities.register(
    "vinberg_root_enumeration",
    "vinal",
    _vinal_vinberg_roots,
    available=_vinal_is_available,
    provisioning=_VINAL_PROVISIONING,
)

engine_capabilities.register(
    "lorentzian_edgewalk_fundamental_domain",
    "polyhedral-common-via-py-polyhedral",
    _polyhedral_common_edgewalk,
    available=_edgewalk_is_available,
    provisioning=_EDGEWALK_PROVISIONING,
)


class AllcockEdgewalkReport(SageObject):
    r"""Owned fundamental-domain data returned by Allcock's edgewalk.

    Each vertex orbit representative of the fundamental polyhedron is the
    ray of ``L tensor QQ`` it spans, a rational polyhedral cone whose wall
    roots are the roots of the walls through the vertex.  The vertex is
    ideal exactly when that ray is isotropic.
    """

    def __init__(
        self,
        lattice,
        *,
        reflective,
        simple_roots,
        vertices,
        isometry_generators,
    ) -> None:
        self._lattice = lattice
        self._reflective = bool(reflective)
        self._simple_roots = finite_ordered_set(tuple(simple_roots))
        self._vertices = finite_ordered_set(tuple(vertices))
        self._isometry_generators = finite_ordered_set(tuple(isometry_generators))

    def lattice(self):
        return self._lattice

    def is_reflective(self) -> bool:
        return self._reflective

    def simple_roots(self):
        return self._simple_roots

    def vertices(self):
        return self._vertices

    def polyhedron_isometry_generators(self):
        return self._isometry_generators

    @cached_method
    def polyhedron_isometry_group(self):
        return self.lattice().O().subgroup(self.polyhedron_isometry_generators())

    def __repr__(self) -> str:
        return f"Allcock edgewalk report for {self.lattice()}"


class HyperbolicLattices(OwnedCategoryOverBaseRing):
    r"""Lattices whose form has exactly one negative index of inertia.

    A lattice enters this category by being handed to it:
    ``HyperbolicLattices(ZZ)(L)`` checks the signature and refines ``L``,
    returning the same object with the reflection algorithms available on it.
    """

    @classmethod
    def _repr_object_names(cls):
        return "hyperbolic lattices"

    def an_object(self):
        r"""The hyperbolic plane \(U\), of signature \((1,1)\)."""
        return self(Lattices(self.base_ring())("U"))

    def super_categories(self):
        return [Lattices(self.base_ring())]

    def _call_(self, lattice):
        r"""Return ``lattice`` refined into this category.

        The hypothesis is the signature: exactly one index of inertia is
        negative, or exactly one is positive.  Both spellings are hyperbolic,
        and which of them occurs is a convention about the sign of the form,
        not a fact about the geometry.
        """
        signature = lattice.signature_pair()
        positive, negative = signature.first(), signature.second()
        assert 1 in (positive, negative), (
            f"{lattice} is not a hyperbolic lattice: a hyperbolic lattice has "
            f"signature (1, n) or (n, 1), but {lattice} has signature "
            f"({positive}, {negative})"
        )
        return refine(lattice, self)

    class ParentMethods:
        def possible_root_lengths(self):
            r"""Return the values \(\lvert q(r)\rvert\) a root of this lattice can take.

            Vinberg's criterion: for a root \(r\) the crystallographic
            condition \(2b(x,r)/q(r)\in R\) for all \(x\in L\) forces \(q(r)\)
            to divide twice the last invariant factor of the correlation
            \(L\to L^{\vee}\), which is the exponent of the discriminant group
            \(A_L\).  The bound is what turns "does this lattice have a root of
            such a length" into a finite question.

            Stated here because it is the bound Vinberg's algorithm searches
            under; the hypothesis it actually needs is nondegeneracy, not
            hyperbolicity.
            """
            correlation = _engine_component_matrix(self.gram_tensor())
            invariant_factors = correlation.elementary_divisors()
            assert invariant_factors[-1] != 0, (
                f"the possible root lengths of {self} are not bounded: the bound needs a "
                f"nondegenerate form, but {self} has a nonzero radical, so its "
                f"discriminant group is infinite"
            )
            return finite_ordered_set(
                tuple(
                    self.base_ring()(int(length))
                    for length in divisors(2 * invariant_factors[-1])
                )
            )

        def _engine_gram_of_signature_n_1(self):
            r"""Return a Gram matrix in the engine's \((n,1)\) convention.

            Returns the matrix together with whether the form was negated to
            reach that convention, since a negated form reverses every
            half-space condition and so negates the roots.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            match positive, negative:
                case _, 1:
                    return _engine_component_matrix(self.gram_tensor()), False
                case 1, _:
                    return _engine_component_matrix(self.twist(-1).gram_tensor()), True
                case _:
                    assert False, (
                        f"cannot run a reflection algorithm on {self}: it needs signature "
                        f"(1, n) or (n, 1), but {self} has signature ({positive}, {negative})"
                    )

        @cached_method
        def _vinberg_search(self, controlling_vector, max_roots, max_decompositions):
            r"""Run Vinberg's algorithm and return completeness with the roots.

            The algorithm is stated for a lattice over any totally real ring of
            integers, where a root row is a vector over that ring and the
            height comparison is made in every real embedding.  The available
            realization works over the integers only, so the wider case is a
            stated absence rather than a silent coercion.
            """
            assert self.base_ring() is _own_ring(SageZZ), (
                f"cannot run Vinberg's algorithm on {self} over {self.base_ring()}: the "
                f"algorithm holds over any totally real ring of integers, but the "
                f"available implementation works over ZZ only.  Bottinelli's "
                f"VinbergsAlgorithmNF (github.com/bottine/VinbergsAlgorithmNF) handles "
                f"the wider case, and it is not connected here"
            )
            gram, negated = self._engine_gram_of_signature_n_1()
            coordinates = (
                None if controlling_vector is None else list(_framing_coordinates(controlling_vector))
            )
            complete, rows = engine_capabilities.compute(
                "vinberg_root_enumeration",
                gram,
                coordinates,
                max_roots,
                max_decompositions,
            )
            roots = tuple(self(tuple(row)) for row in rows)
            return complete, tuple(-root for root in roots) if negated else roots

        def vinberg_simple_roots(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the roots Vinberg's algorithm accepted.

            The accepted roots are the outward normals of the walls of a
            fundamental polyhedron for \(W(L)\), taken in the order the
            algorithm's height function on the controlling vector produces
            them.  A search that ran to completion returns the whole wall set;
            a search stopped by ``max_roots`` or ``max_decompositions`` returns
            what it had, and :meth:`is_reflective` is then ``Unknown``.

            The controlling vector is the point of the hyperbolic space the
            enumeration measures height from.  Omitted, the engine picks one of
            negative square for itself.
            """
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return finite_ordered_set(roots)

        def vinberg_algorithm(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the roots accepted by Vinberg's algorithm.

            This is the archived public mathematical name for the same owned
            root family exposed by :meth:`vinberg_simple_roots`.  Historical
            engine controls such as progress output and CoxIter selection are
            not part of the mathematical operation and are deliberately not
            restored at the public boundary.
            """
            return self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )

        def is_reflective(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) has finite index in \(O(L)\), or ``Unknown``.

            Vinberg's algorithm establishes the fundamental polyhedron exactly
            when it has finite volume, so a completed search is a proof that
            the lattice is reflective.  A search that a bound stopped is not a
            proof of anything, and an unbounded search on a non-reflective
            lattice does not return, so this answers ``True`` or ``Unknown``
            and never ``False``.  Deciding non-reflectivity needs Allcock's
            edgewalk, which terminates on every input; see
            :meth:`edgewalk_is_reflective`.

            In signature \((1,1)\) the criterion is unreachable: the domain is
            a half-line in \(H^1\), of infinite volume, and the question is
            refused rather than answered.
            """
            signature = self.signature_pair()
            positive, negative = signature.first(), signature.second()
            assert (positive, negative) != (1, 1), (
                f"cannot decide whether {self} is reflective: it has signature (1, 1), "
                f"where the fundamental domain is a half-line in H^1 of infinite "
                f"volume, so no polyhedron criterion applies"
            )
            complete, _roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            return True if complete else Unknown

        def reflection_group(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return \(W(L)\leq O(L)\), generated by the reflections in the roots.

            The mirrors of the walls of a fundamental polyhedron generate the
            whole reflection subgroup (Vinberg 1972), so the generators are the
            reflections in the roots :meth:`vinberg_simple_roots` returns, and
            the result is a subgroup of the owned orthogonal group rather than
            an abstract Coxeter group.  Its Coxeter presentation is read from
            :meth:`reflection_coxeter_diagram`.

            On a search that did not complete, the group generated is a
            subgroup of \(W(L)\) and need not be all of it; ask
            :meth:`is_reflective` for the certificate.
            """
            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return self.O().subgroup([self.reflection(root) for root in roots])

        def weyl_group(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the reflection/Weyl subgroup \(W(L)\leq O(L)\).

            ``weyl_group`` is the archived public vocabulary for the same
            subgroup now constructed by :meth:`reflection_group`; retaining
            both names does not create a second group or a second root
            enumeration.
            """
            return self.reflection_group(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )

        def reflection_coxeter_diagram(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the Coxeter diagram of the fundamental polyhedron.

            One vertex per wall, rooted in the accepted roots, so the diagram
            carries the exact pairings and separates parallel walls from
            divergent ones.  It is the diagram of \(W(L)\) as a Coxeter group
            when the search completed.
            """
            from dzack_research.preamble.categories.coxeter_diagrams import CoxeterDiagrams

            roots = self.vinberg_simple_roots(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return CoxeterDiagrams().from_roots(tuple(roots))

        def _chamber_vertex_squares(
            self, controlling_vector, max_roots, max_decompositions
        ):
            r"""Return the squares of the vertices of the fundamental polyhedron.

            The chamber is \(\{x : b(x,r)\leq 0\text{ for every wall } r\}\),
            which in coordinates is the cone dual to the one spanned by the
            rows \(rG\).  Its extreme rays are the vertices of the polyhedron,
            and the square of a ray decides its kind: negative inside the light
            cone, so an ordinary point of hyperbolic space, and zero on the
            cone, so an ideal point of the boundary.
            """
            from sage.geometry.cone import Cone

            gram = _engine_component_matrix(self.gram_tensor())
            _complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            wall_normals = [engine_vector(_framing_coordinates(root)) * gram for root in roots]
            chamber = Cone(wall_normals).dual()
            return tuple(
                (engine_matrix(ray) * gram * engine_matrix(ray).transpose())[0][0]
                for ray in chamber.rays()
            )

        def is_cocompact(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return whether \(W(L)\) acts cocompactly, or ``Unknown``.

            A fundamental polyhedron is compact exactly when it has finite
            volume and no ideal vertex.  Finite volume is
            :meth:`is_reflective`; an ideal vertex is a vertex of square zero,
            lying on the light cone rather than inside it.  Stated on the
            squares rather than on their sign, the criterion does not depend on
            which sign convention the form carries.

            Not cocompact does not mean infinite covolume: a reflective lattice
            with an ideal vertex has a finite-volume noncompact fundamental
            domain, which is the common hyperbolic case.
            """
            reflective = self.is_reflective(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            if reflective is not True:
                return Unknown
            return all(
                square != 0
                for square in self._chamber_vertex_squares(
                    controlling_vector, max_roots, max_decompositions
                )
            )

        @cached_method
        def positive_cone_component(self, timelike):
            r"""Return the chosen component of ``{x:q(x)>0}`` containing ``timelike``."""
            from dzack_research.preamble.categories.hyperbolic_geometry import (
                _positive_cone_component,
            )

            return _positive_cone_component(self, timelike)

        @cached_method
        def hyperbolic_space(self, timelike):
            r"""Return the projectivization of the positive-cone component containing ``timelike``."""
            return self.positive_cone_component(timelike).projectivization()

        def fundamental_chamber(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the exact root-half-space cone cut out by Vinberg's walls.

            The chamber is ``{x : b(r,x) >= 0 for every accepted wall r}``.
            It retains those roots and their actual correlation covectors; the
            completion flag records whether the Vinberg search established the
            full wall set or only a bounded exploration prefix.
            """
            complete, roots = self._vinberg_search(
                controlling_vector, max_roots, max_decompositions
            )
            correlation = self.algebraic_correlation_morphism()
            return self.rational_polyhedral_cone(
                tuple(correlation(root) for root in roots),
                wall_roots=roots,
                complete=complete,
            )

        def coxeter_polyhedron(
            self, timelike, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Projectivize the exact root chamber in the component selected by ``timelike``."""
            chamber = self.fundamental_chamber(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )
            return self.hyperbolic_space(timelike).projectivize_cone(chamber)

        def dominant_cone(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the closed dominant cone defined by the selected simple roots."""
            return self.fundamental_chamber(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            )

        def chamber_complex(
            self, controlling_vector=None, *, max_roots=None, max_decompositions=None
        ):
            r"""Return the lazy Weyl complex generated by the exact fundamental chamber.

            The object does not enumerate the generally infinite chamber set.
            It retains the fundamental chamber, the simple reflections and the
            exact wall-crossing transporters, and materializes any chamber from
            a finite simple-reflection word.
            """
            return self.fundamental_chamber(
                controlling_vector,
                max_roots=max_roots,
                max_decompositions=max_decompositions,
            ).chamber_complex()

        def isotropic_elements_below_height(self, timelike, height):
            r"""Return the isotropic \(v\in L\) with \(\lvert b(v,t)\rvert\leq h\).

            Put \(d=q(t)\) and \(a=b(v,t)\).  Then

            \[
              w=dv-at\in t^\perp, \qquad q(w)=-a^2d,
            \]

            and conversely \(v=(w+at)/d\) whenever that quotient is integral.
            Thus the height bound leaves only the finitely many integers
            \(-h\leq a\leq h\); for each one the possible \(w\)'s form one
            finite shell in the definite lattice \(t^\perp\).  The final
            divisibility check is exactly the condition that the rational
            reconstruction lies back in \(L\).
            """
            integers = _own_ring(SageZZ)
            assert self.base_ring() is integers, (
                f"cannot enumerate isotropic vectors of {self} by height: the "
                f"enumeration works only over ZZ, and {self} is over {self.base_ring()}"
            )
            if timelike.parent() is not self:
                timelike = self(timelike)
            height = integers(height)
            assert height >= integers.zero(), (
                f"cannot enumerate isotropic vectors of {self} below height {height}: "
                f"the height bound must be nonnegative"
            )

            square = timelike.q()
            assert square != integers.zero(), (
                f"{timelike} is not timelike in {self}: a timelike vector has nonzero "
                f"square, and q({timelike}) = 0"
            )
            complement = timelike.orthogonal_complement()
            assert complement.is_definite(), (
                f"{timelike} is not timelike in {self}: a vector is timelike exactly when "
                f"its orthogonal complement is definite, and {complement} is not definite"
            )
            inclusion = complement.inclusion()

            isotropic = []
            for height_value in range(-int(height), int(height) + 1):
                pairing = integers(height_value)
                target_square = -(pairing * pairing * square)
                match pairing == integers.zero():
                    case True:
                        shell = (complement.zero(),)
                    case False:
                        shell = complement.vectors_of_square(target_square)
                for perpendicular in shell:
                    numerator = inclusion(perpendicular) + pairing * timelike
                    coordinates = _framing_coordinates(numerator)
                    if not all(square.divides(coordinate) for coordinate in coordinates):
                        continue
                    candidate = self(
                        tuple(coordinate // square for coordinate in coordinates)
                    )
                    if candidate.q() != integers.zero():
                        raise ArithmeticError(
                            f"the isotropic vectors of {self} at height {pairing} from "
                            f"{timelike} were computed wrongly: the candidate {candidate} "
                            f"has square {candidate.q()}, not 0"
                        )
                    if self.b(candidate, timelike) != pairing:
                        raise ArithmeticError(
                            f"the isotropic vectors of {self} at height {pairing} from "
                            f"{timelike} were computed wrongly: the candidate {candidate} "
                            f"has pairing {self.b(candidate, timelike)} with {timelike}, "
                            f"not {pairing}"
                        )
                    isotropic.append(candidate)
            return finite_ordered_set(tuple(isotropic))

        @cached_method
        def _edgewalk(self):
            r"""Run Allcock's edgewalk and return the decision with the roots.

            A second producer of the object Vinberg's algorithm enumerates,
            walking the edges of a fundamental polyhedron rather than growing
            it from a controlling vector.  It takes no controlling vector and
            no bound, because it terminates on every input.

            The engine works in signature \((n,1)\), so the roots come back
            negated whenever the transport negated the form, exactly as in
            :meth:`_vinberg_search`.
            """
            assert self.base_ring() is _own_ring(SageZZ), (
                f"cannot run Allcock's edgewalk on {self}: the available implementation "
                f"works only for lattices over ZZ, and {self} is over {self.base_ring()}"
            )
            gram, negated = self._engine_gram_of_signature_n_1()
            record = engine_capabilities.compute(
                "lorentzian_edgewalk_fundamental_domain",
                gram,
            )
            roots = tuple(self(tuple(row)) for row in record["simple_root_rows"])
            match negated:
                case True:
                    roots = tuple(-root for root in roots)
                case False:
                    pass

            from dzack_research.preamble.categories.polyhedral_cones import (
                RationalPolyhedralCones,
            )

            vertices = []
            for generator_row, incident_rows in record["vertices"]:
                incident = tuple(self(tuple(row)) for row in incident_rows)
                match negated:
                    case True:
                        incident = tuple(-root for root in incident)
                    case False:
                        pass
                vertices.append(
                    RationalPolyhedralCones(self).from_rays(
                        (self(tuple(generator_row)),), wall_roots=incident
                    )
                )

            automorphisms = self.O()
            isometry_generators = tuple(
                automorphisms(tuple(self(tuple(row)) for row in rows))
                for rows in record["isometry_generator_rows"]
            )
            return AllcockEdgewalkReport(
                self,
                reflective=record["is_reflective"],
                simple_roots=roots,
                vertices=tuple(vertices),
                isometry_generators=isometry_generators,
            )

        def allcock_edgewalk(self):
            r"""Return Allcock's full owned fundamental-domain report."""
            return self._edgewalk()

        def edgewalk_is_reflective(self) -> bool:
            r"""Return whether \(W(L)\) has finite index in \(O(L)\).

            A decision, unlike :meth:`is_reflective`: the edgewalk terminates
            on every input, reporting the fundamental polyhedron when there is
            one and the obstruction when there is not, so this answers ``True``
            or ``False`` and never ``Unknown``.  The two methods answer the
            same mathematical question and are kept apart because they prove
            different things, not because they use different engines.
            """
            return self._edgewalk().is_reflective()

        def edgewalk_simple_roots(self):
            r"""Return the simple roots of the polyhedron the edgewalk walked.

            The outward normals of the walls of a fundamental polyhedron for
            \(W(L)\), the same wall set :meth:`vinberg_simple_roots` produces
            from a completed search.  A non-reflective lattice has no such
            polyhedron, and the set is then empty; ask
            :meth:`edgewalk_is_reflective` to tell that case from a lattice
            whose polyhedron has no walls.
            """
            return self._edgewalk().simple_roots()


__all__ = [
    "AllcockEdgewalkReport",
    "HyperbolicLattices",
    "NumberFieldVinbergLattice",
]
