r"""Finite discriminant stabilizer for the degree-2 Enriques polarization.

This is the finite target associated with

    S_En = U(2) + E_8(2) = 2B,  B = U + E_8(-1),

and the K3-side degree-2 Enriques polarization vector ``h=e+f`` in the ``U(2)``
summand.  The discriminant group is identified with ``B/2B``.  The quadratic form is
encoded by

    Q(v) = B(v,v) mod 4,

which represents ``2 q_S(v/2 + S_En)``.

The group computed below is the full finite automorphism group of this discriminant
quadratic form, realized as the subgroup of ``GL(B/2B)`` preserving all fibers of
``Q``.  The final stabilizer is the stabilizer of the discriminant class ``h/2``.

This computes the finite stabilizer target for the discriminant-action description of
``Gamma_En,2``.  The integral stabilizer of ``h`` in ``O(S_En)=O(B)`` has complement
``h^perp = <e-f> + E_8(-1)``, so it has order ``2 |W(E_8)|``.  The finite stabilizer
below is larger by a factor of ``68``; it is a finite container, not the actual image
of the integral stabilizer.

The same integral image acts on the discriminant group of the explicit Coble
Heegner complement

    delta^perp = <2> + U(2) + E_8(2).

Writing this lattice as ``2B_Co`` with ``B_Co=<1>+U+E_8(-1)``, the induced finite
action fixes the ``<1>`` coordinate and acts through the actual image of
``Stab_{O(S_En)}(h)`` on the remaining ``U+E_8(-1)`` coordinates.

The script also checks the finite gluing condition for the full stabilizer of the
Heegner line.  The class of ``(u+v)/2`` is fixed by the full finite orthogonal group
of ``A_TCo``, and the induced action on its orthogonal complement is the full
orthogonal group of the lower ``U+E_8(-1)`` discriminant form.

For the Coble-side stabilizer-centralizer comparison, the algebraic lattice is

    S_Co = 2B_SCo,  B_SCo = <-1> + U + E_8(-1),

and the K3-side Coble polarization is represented by ``tilde_h=e+f`` in the ``U(2)``
summand.  The coordinate anti-isometry from ``A_SCo`` to ``A_TCo`` sends this class to
the same bitmask in ``A_TCo``.  The finite Coble-side stabilizer is therefore the
stabilizer of that class in ``O(A_TCo,q_T)``.

The integral Coble-side stabilizer has the same finite image as the Enriques-induced
subgroup computed above.  In ``B_SCo``, the orthogonal complement of ``tilde_h`` is
``<-1> + <-2> + E_8(-1)``.  The rank-one factors are distinguished by norm and
divisibility, and the ``E_8`` factor has Weyl group ``W(E_8)``.  On the discriminant
group, the sign of the ``<-1>`` factor is trivial, the sign of the ``<-2>`` factor is
the swap of the two ``U`` coordinates fixing ``e+f``, and the ``E_8`` factor acts by
the simple-root reflections.  Thus its finite image is generated by the same matrices
as the Enriques-induced image.
"""

from sage.all import (
    GF,
    GL,
    ZZ,
    Permutation,
    PermutationGroup,
    WeylGroup,
    block_diagonal_matrix,
    identity_matrix,
    matrix,
    vector,
)
from sage.libs.gap.libgap import libgap

F = GF(2)
RANK = 10
TCO_RANK = 11
H_BITS = 0b11
HTILDE_CO_BITS = 0b110

E8 = matrix(
    ZZ,
    [
        [2, -1, 0, 0, 0, 0, 0, 0],
        [-1, 2, -1, 0, 0, 0, 0, 0],
        [0, -1, 2, -1, 0, 0, 0, 0],
        [0, 0, -1, 2, -1, 0, 0, 0],
        [0, 0, 0, -1, 2, -1, 0, -1],
        [0, 0, 0, 0, -1, 2, -1, 0],
        [0, 0, 0, 0, 0, -1, 2, 0],
        [0, 0, 0, 0, -1, 0, 0, 2],
    ],
)

GRAM_B = block_diagonal_matrix(
    matrix(ZZ, [[0, 1], [1, 0]]),
    -E8,
)
GRAM_TCO_B = block_diagonal_matrix(
    matrix(ZZ, [[1]]),
    matrix(ZZ, [[0, 1], [1, 0]]),
    -E8,
)
GRAM_SCO_B = block_diagonal_matrix(
    matrix(ZZ, [[-1]]),
    matrix(ZZ, [[0, 1], [1, 0]]),
    -E8,
)


def residue_vector(bits, rank=RANK):
    r"""Return the element of ``B/2B`` encoded by an integer bitmask."""
    return vector(ZZ, [(bits >> i) & 1 for i in range(rank)])


def quadratic_value(bits, gram=GRAM_B, rank=RANK):
    r"""Return ``B(v,v) mod 4`` for a residue vector ``v in B/2B``."""
    v = residue_vector(bits, rank)
    return int((v * gram * v.column())[0]) % 4


def act_bits(bits, g, rank=RANK):
    r"""Return the bitmask for the right action of ``g in GL(B/2B)``."""
    v = vector(F, [(bits >> i) & 1 for i in range(rank)])
    w = v * g
    return sum((1 << i) for i, entry in enumerate(w) if int(entry))


def reflection_matrix(root):
    r"""Return the row-action reflection in a norm ``-2`` root of ``B``."""
    root_col = vector(ZZ, root).column()
    root_row = matrix(ZZ, [root])
    return identity_matrix(ZZ, RANK) + GRAM_B * root_col * root_row


def integral_stabilizer_generators():
    r"""Return generators for the action of ``Stab_{O(S_En)}(h)`` on ``B/2B``."""
    swap = identity_matrix(ZZ, RANK)
    swap[0, 0] = 0
    swap[1, 1] = 0
    swap[0, 1] = 1
    swap[1, 0] = 1

    simple_roots = []
    for i in range(8):
        root = [0] * RANK
        root[2 + i] = 1
        simple_roots.append(root)

    return [swap.change_ring(F)] + [
        reflection_matrix(root).change_ring(F) for root in simple_roots
    ]


def induced_tco_generator(g):
    r"""Embed a generator into the finite action on ``A_TCo``.

    Coordinates are ordered as ``<1>`` followed by ``U+E_8(-1)``.  The first
    coordinate is the class of ``(u+v)/2`` in the Coble Heegner complement, and the
    induced Enriques-side discriminant action fixes it.
    """
    induced = identity_matrix(F, TCO_RANK)
    for row in range(RANK):
        for col in range(RANK):
            induced[1 + row, 1 + col] = g[row, col]
    return induced


def finite_orthogonal_group(rank, gram):
    r"""Return the finite permutation group preserving all ``Q`` fibers."""
    general_linear_group = GL(rank, F)
    action_generators = [
        Permutation([act_bits(bits, g, rank) + 1 for bits in range(1 << rank)])
        for g in general_linear_group.gens()
    ]
    orthogonal_group = PermutationGroup(action_generators).gap()
    for value in range(4):
        fiber = [
            bits + 1
            for bits in range(1 << rank)
            if quadratic_value(bits, gram, rank) == value
        ]
        orthogonal_group = libgap.Stabilizer(
            orthogonal_group,
            libgap(fiber),
            libgap.OnSets,
        )
    return orthogonal_group


def main():
    r"""Compute the finite orthogonal group and the stabilizer of ``h/2``."""
    general_linear_group = GL(RANK, F)
    action_generators = [
        Permutation([act_bits(bits, g) + 1 for bits in range(1 << RANK)])
        for g in general_linear_group.gens()
    ]
    permutation_action = PermutationGroup(action_generators)

    fibers = {
        value: [bits + 1 for bits in range(1 << RANK) if quadratic_value(bits) == value]
        for value in range(4)
    }

    orthogonal_group = permutation_action.gap()
    for value in range(4):
        orthogonal_group = libgap.Stabilizer(
            orthogonal_group,
            libgap(fibers[value]),
            libgap.OnSets,
        )

    h_stabilizer = libgap.Stabilizer(
        orthogonal_group,
        libgap(H_BITS + 1),
        libgap.OnPoints,
    )
    integral_image = PermutationGroup(
        [
            Permutation([act_bits(bits, g) + 1 for bits in range(1 << RANK)])
            for g in integral_stabilizer_generators()
        ]
    ).gap()
    tco_image = PermutationGroup(
        [
            Permutation(
                [
                    act_bits(bits, induced_tco_generator(g), TCO_RANK) + 1
                    for bits in range(1 << TCO_RANK)
                ]
            )
            for g in integral_stabilizer_generators()
        ]
    ).gap()
    tco_fibers = {
        value: [
            bits + 1
            for bits in range(1 << TCO_RANK)
            if quadratic_value(bits, GRAM_TCO_B, TCO_RANK) == value
        ]
        for value in range(4)
    }
    tco_isotropic_orbits = libgap.OrbitsDomain(
        tco_image,
        libgap(tco_fibers[0]),
        libgap.OnPoints,
    )
    tco_orthogonal_group = finite_orthogonal_group(TCO_RANK, GRAM_TCO_B)
    tco_eta_stabilizer = libgap.Stabilizer(
        tco_orthogonal_group,
        libgap(2),
        libgap.OnPoints,
    )
    coble_htilde_stabilizer = libgap.Stabilizer(
        tco_orthogonal_group,
        libgap(HTILDE_CO_BITS + 1),
        libgap.OnPoints,
    )
    coble_htilde_isotropic_orbits = libgap.OrbitsDomain(
        coble_htilde_stabilizer,
        libgap(tco_fibers[0]),
        libgap.OnPoints,
    )
    tco_lower_points = [(bits << 1) + 1 for bits in range(1 << RANK)]
    tco_lower_action = libgap.Image(
        libgap.ActionHomomorphism(
            tco_eta_stabilizer,
            libgap(tco_lower_points),
            libgap.OnPoints,
        )
    )
    integral_h_stabilizer_order = 2 * ZZ(WeylGroup(["E", 8], prefix="s").cardinality())

    print("fiber_sizes", {value: len(fibers[value]) for value in range(4)})
    print("orthogonal_group_order", orthogonal_group.Size())
    print("h_bits", H_BITS)
    print("h_q_mod4", quadratic_value(H_BITS))
    print("h_stabilizer_order", h_stabilizer.Size())
    print("integral_h_stabilizer_order", integral_h_stabilizer_order)
    print(
        "finite_container_index_over_integral_stabilizer",
        ZZ(h_stabilizer.Size()) // integral_h_stabilizer_order,
    )
    print("integral_image_order", integral_image.Size())
    print(
        "finite_container_index_over_integral_image",
        ZZ(h_stabilizer.Size()) // ZZ(integral_image.Size()),
    )
    print("tco_fiber_sizes", {value: len(tco_fibers[value]) for value in range(4)})
    print("tco_induced_image_order", tco_image.Size())
    print(
        "tco_isotropic_orbit_lengths",
        sorted(int(orbit.Length()) for orbit in tco_isotropic_orbits),
    )
    print(
        "tco_isotropic_representatives_as_bits",
        sorted(int(orbit[0]) - 1 for orbit in tco_isotropic_orbits),
    )
    print("tco_full_orthogonal_group_order", tco_orthogonal_group.Size())
    print("tco_eta_stabilizer_order", tco_eta_stabilizer.Size())
    print("tco_eta_stabilizer_image_on_lower_order", tco_lower_action.Size())
    print("sco_htilde_bits", HTILDE_CO_BITS)
    print("sco_htilde_q_mod4", quadratic_value(HTILDE_CO_BITS, GRAM_SCO_B, TCO_RANK))
    print(
        "coble_htilde_finite_stabilizer_order",
        coble_htilde_stabilizer.Size(),
    )
    print(
        "coble_htilde_stabilizer_contains_enriques_image",
        libgap.IsSubgroup(coble_htilde_stabilizer, tco_image),
    )
    print("coble_integral_htilde_image_order", tco_image.Size())
    # Migration correction (2026-08-20): the source printed the Python
    # literal ``True`` here, in the same output stream as computed group
    # orders, for a claim its docstring only *argues* (in B_SCo the
    # complement of htilde_Co is <-1> + <-2> + E8(-1), whose finite image is
    # generated by the same matrices).  A claim this script does not compute
    # is labeled as such, never printed as a computed result.
    print(
        "coble_integral_htilde_image_equals_enriques_image",
        "argued-not-computed (see docstring)",
    )
    print(
        "coble_htilde_stabilizer_index_over_enriques_image",
        ZZ(coble_htilde_stabilizer.Size()) // ZZ(tco_image.Size()),
    )
    print(
        "coble_htilde_isotropic_orbit_lengths",
        sorted(int(orbit.Length()) for orbit in coble_htilde_isotropic_orbits),
    )
    print(
        "coble_htilde_isotropic_representatives_as_bits",
        sorted(int(orbit[0]) - 1 for orbit in coble_htilde_isotropic_orbits),
    )


if __name__ == "__main__":
    main()
