# Origin: gitclones/integral_lattice/cat/src/abc_specs/w_categories/hom_categories/abstract_arrows.py
# Copied 2026-08-20 by the integral_lattice enrichment migration
# (PLAN-corpora-audit-registry, sections R3/R4). Content below is unmodified.
#
# This is a DESIGN RECORD: it states an intended interface, not the built
# preamble. Divergences and recorded errors are listed in the INDEX.md of
# this corpus.

"""
Arrow mixins for n-cells in any category.

Hierarchy:
- _Arrow: Base for ANY morphism (1-cell, 2-cell, n-cell)
- _EndoArrow: Arrow with source == target
- _AutoArrow: Invertible EndoArrow

Then specialized:
- _OneMorphism: _Arrow + 1-cell specific methods
- _TwoMorphism: _Arrow + 2-cell specific methods (horizontal/vertical composition)
"""

from src.local_typing import *

from src._types import BoolProof, CategoryABCs, SageType

# =============================================================================
# Arrow: Base for ANY morphism in ANY category
# =============================================================================

class _Arrow(ABC):
    """
    Base mixin for any morphism (arrow) in any category.

    Works for 1-cells, 2-cells, n-cells in any category.
    These are intrinsic properties of an arrow, not dependent on the ambient system.
    """

    # === Core Arrow Structure ===

    @final
    @abstractmethod
    def domain(self) -> Any:
        """The source (domain) of this arrow."""
        ...

    @final
    @abstractmethod
    def codomain(self) -> Any:
        """The target (codomain) of this arrow."""
        ...

    # === Predicates ===

    @final
    @abstractmethod
    def is_identity(self) -> BoolProof:
        """Is this the identity arrow?"""
        ...

    @final
    @abstractmethod
    def is_invertible(self) -> BoolProof:
        """Does this arrow have a two-sided inverse?"""
        ...

    @final
    @abstractmethod
    def is_endomorphism(self) -> BoolProof:
        """source() == target()."""
        ...

    @final
    @abstractmethod
    def is_automorphism(self) -> BoolProof:
        """Invertible endomorphism."""
        ...
    
    @final
    @abstractmethod
    def is_equivalence(self) -> BoolProof:
        """Is this arrow an equivalence?"""
        ...

class _EndoArrow(_Arrow, ABC):
    """
    Endo-arrow: source == target.

    Has monoid structure under composition.
    """

    @final
    @abstractmethod
    def order(self) -> SageType.NN_U_infty:
        """Smallest n > 0 with f^n = id, or ∞."""
        ...

    @final
    @abstractmethod
    def is_idempotent(self) -> BoolProof:
        """f ∘ f == f."""
        ...

    @final
    @abstractmethod
    def is_nilpotent(self) -> BoolProof:
        """∃n: f^n == zero_morphism."""
        ...

    @final
    @abstractmethod
    def is_unipotent(self) -> BoolProof:
        """∃n: (f - id)^n == zero_morphism."""
        ...

    @final
    @abstractmethod
    def is_involution(self) -> BoolProof:
        """f ∘ f == id."""
        ...

    @final
    @abstractmethod
    def is_finite_order(self) -> BoolProof:
        """order() < ∞."""
        ...
    
    @final
    @abstractmethod
    def is_infinite_order(self) -> BoolProof:
        """order() = ∞."""
        ...

    @final
    @abstractmethod
    def to_power(self, n: SageType.NN) -> Self:
        """fⁿ."""
        ...

    @final
    def to_free_monoid(self) -> SageType.Monoid:
        """The free monoid generated by this arrow."""
        ...

class _AutoArrow(_EndoArrow, ABC):
    """
    Auto-arrow: invertible endo-arrow.

    Has group structure under composition.
    """

    @final
    @abstractmethod
    def inverse(self) -> Self:
        """The inverse arrow."""
        ...

    @final
    def to_free_group(self) -> SageType.Group: # type: ignore[cython]
        """The free group generated by this arrow."""
        ...

class OneArrow(_Arrow):
    """Export methods specific to 1-cells."""

    @final
    @abstractmethod
    def to_callable(self) -> Callable[[Any], Any]:
        """Return a callable f: X → Y representing the morphism."""
        ...

    @final
    @abstractmethod
    def to_dict(self) -> Mapping[Any, Any]:
        """Return a dict representing the morphism."""
        ...

    @final
    @abstractmethod
    def to_relation(self) -> frozenset[tuple[Any, Any]]:
        """Return a relation R ⊂ X×Y representing the morphism."""
        ...

    @final
    @abstractmethod
    def to_graph_of_function(self) -> frozenset[tuple[Any, Any]]:
        """Return the graph {(x, f(x)) | x ∈ X} ⊂ X×Y."""
        ...

    @final
    @abstractmethod
    def to_list(self) -> Sequence[Any]:
        """Return [f(x_i) for x_i in X]."""
        ...

    @final
    @abstractmethod
    def to_tuple(self) -> tuple[Any, ...]:
        """tuple(to_list())."""
        ...

    @final
    @abstractmethod
    def to_permutation(self) -> SageType.Permutation:
        """Convert to permutation if applicable."""
        ...

    @final
    @abstractmethod
    def to_matrix(self) -> SageType.Matrix:

     """Predicates specific to 1-cells (not applicable to 2-cells)."""

    @final
    @abstractmethod
    def is_constant(self) -> BoolProof:
        """f(x) = c for all x ∈ X."""
        ...

    @final
    @abstractmethod
    def is_injective(self) -> BoolProof:
        """f(x) = f(y) implies x = y."""
        ...

    @final
    @abstractmethod
    def is_surjective(self) -> BoolProof:
        """For all y ∈ Y, exists x with f(x) = y."""
        ...

    @final
    @abstractmethod
    def is_bijective(self) -> BoolProof:
        """Injective and surjective."""
        ...

    @final
    @abstractmethod
    def is_monomorphism(self) -> BoolProof:
        """Left-cancellable: fg = fh implies g = h."""
        ...

    @final
    @abstractmethod
    def is_epimorphism(self) -> BoolProof:
        """Right-cancellable: gf = hf implies g = h."""
        ...

    @final
    @abstractmethod
    def is_isomorphism(self) -> BoolProof:
        """Has two-sided inverse."""
        ...

    @final
    @abstractmethod
    def is_left_invertible(self) -> BoolProof:
        """Has left inverse (section)."""
        ...

    @final
    @abstractmethod
    def is_right_invertible(self) -> BoolProof:
        """Has right inverse (retraction)."""
        ...

    def image(self) -> Any:
        """
        The image im(f) of f: x -> y is the limit of the diagram

        x -> y ⨿_x y -> y ⨿_x y -> y ⨿_x y ⨿_x y -> ...

        which reduces to the equalizer of the cokernel pair for 1-categories.
        Equivalently, if x and y have elements, this can be written

        im(f) = {y ∈ Y | Fib_y(f) ≠ ∅} = {y ∈ Y | ∃x ∈ X s.t. f(x) = y}
        """
        ...

    def coimage(self) -> Any:
        """
        The coimage coim(f) of f: x -> y is the colimit of the diagram

        .... -> x ×_y x ×_y x -> x ×_y x -> x
    
        which reduces to the coequalizer of the kernel pair for 1-categories.
        Equivalently, if x and y have elements, this can be written
        
        coim(f) = X/ker(f) 
        
        """
        ...

    def kernel(self) -> Any:
        """ker(f) := {x ∈ X | f(x) = *} where * is the terminal object of Y."""
        ...

    def cokernel(self) -> Any:
        """coker(f) := Y/im(f) := Cofib(f) := * ⨿_x y"""
        ...


class OneEndoArrow(OneArrow, _EndoArrow, ABC):
    """
    Endomorphism for 1-cells: f: X → X.

    Has monoid structure under composition.
    """

    @final
    @abstractmethod
    def fixed_points(self) -> Any:
        """{x ∈ X | f(x) = x} as a subobject."""
        ...


class OneAutoArrow(OneEndoArrow, _AutoArrow, ABC):
    """
    Automorphism for 1-cells: invertible f: X → X.

    Has group structure under composition.
    """
    ...


# =============================================================================
# 2-Arrow: Arrow + 2-cell specific methods
# =============================================================================

class TwoArrow(_Arrow, ABC):
    """
    2-arrow: arrow between 1-arrows.

    Adds horizontal and vertical composition (not available for 1-cells).
    """

    @final
    @abstractmethod
    def horizontal_compose(self, other: Self) -> Self:
        """Horizontal composition (whiskering): α ⋆ β."""
        ...

    @final
    @abstractmethod
    def vertical_compose(self, other: Self) -> Self:
        """Vertical composition: α ∘ β."""
        ...


class TwoEndoArrow(TwoArrow, _EndoArrow, ABC):
    """
    Endo-2-arrow: 2-cell α: f ⇒ f.

    Has monoid structure under vertical composition.
    """
    ...
    ...

class TwoAutoArrow(TwoEndoArrow, _AutoArrow, ABC):
    """
    Auto-2-arrow: invertible 2-cell α: f ⇒ f.

    Has group structure under vertical composition.
    """
    ...
    ...
