# Repo-scoped stubs; see lexicon/README.md.
from typing import Any

from sage.rings.integer import Integer

def ceil(x: Any) -> Integer: ...
def floor(x: Any) -> Integer: ...
def sqrt(x: Any) -> Any: ...
