#!/usr/bin/env bash
# Fail unless every proved theorem rests on Lean's three standard axioms, and no
# `sorry` appears outside a statement file.
#
# The mechanism is the one `anthropics/fermats-last-theorem` puts in its default
# build target: the axiom set is a build failure, never a claim in prose.  There
# it reads
#
#   /-- info: 'fermat_last_theorem' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#   #guard_msgs in
#   #print axioms fermat_last_theorem
#
# This script generates the equivalent guard for every theorem in Solutions/ and
# runs it, so the check does not have to be remembered per node.
#
# Usage: verification/check_axioms.sh [workspace]
#   workspace defaults to the repo's formalization/prove2me_workspace

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
workspace="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../prove2me_workspace" && pwd)}"

if [ ! -d "$workspace/.lake" ]; then
  echo "no built Lean workspace at $workspace — run lake build there first" >&2
  exit 2
fi

status=0

# 1. sorry may appear only in Theorems/, where a statement waits for its proof.
while IFS= read -r f; do
  if grep -qE '(^|[^[:alnum:]_])sorry([^[:alnum:]_]|$)' "$f"; then
    echo "FAIL sorry outside a statement file: ${f#"$here"/}" >&2
    status=1
  fi
done < <(find "$here/Definitions" "$here/Solutions" -name '*.lean' 2>/dev/null)

# 2. every `theorem solution` in Solutions/ gets an axiom guard.
guard="$workspace/Solutions/GeneratedAxiomCheck.lean"
{
  echo "-- generated by verification/check_axioms.sh; do not edit"
  find "$here/Solutions" -name 'Sol_*.lean' 2>/dev/null | sort | while IFS= read -r f; do
    base="$(basename "$f" .lean)"
    echo "import Solutions.$base"
  done
  find "$here/Solutions" -name 'Sol_*.lean' 2>/dev/null | sort | while IFS= read -r f; do
    ns="$(grep -oE '^namespace [A-Za-z0-9_.]+' "$f" | head -1 | cut -d' ' -f2 || true)"
    [ -n "$ns" ] || continue
    echo "/-- info: '$ns.solution' depends on axioms: [propext, Classical.choice, Quot.sound] -/"
    echo "#guard_msgs in"
    echo "#print axioms $ns.solution"
  done
} > "$guard"

n=$(grep -c '#print axioms' "$guard" || true)
if [ "$n" -eq 0 ]; then
  echo "no proved solutions yet; sorry-check passed over $(find "$here/Definitions" "$here/Solutions" -name '*.lean' 2>/dev/null | wc -l) file(s)"
  exit "$status"
fi

echo "checking axioms of $n solution(s)"
( cd "$workspace" && lake build Solutions.GeneratedAxiomCheck ) || status=1
exit "$status"
