from importlib import import_module

from dzack_research.preamble.categories.group.g_sets import (
    FiniteGSet,
    FiniteGSets,
    GSets,
    GSetHomset,
    GSetMorphism,
    OrbitClass,
    OrbitSet,
    Torsors,
    fixed_point_set,
    g_set_homset,
    trivial_g_set,
)
from dzack_research.preamble.categories.group.group_morphisms import (
    GroupAutomorphism,
    GroupAutomorphismGroup,
    GroupHomomorphism,
    GroupHomset,
    IndexedFreeGroupHomomorphism,
    IndexedFreeGroupHomset,
    group_homset,
)
from dzack_research.preamble.categories.group.cyclic_subgroups import (
    CyclicSubgroup,
    cyclic_subgroup,
)
from dzack_research.preamble.categories.group.groups import (
    AbelianGroups,
    FiniteAbelianGroups,
    FiniteGroups,
    FinitelyGeneratedGroups,
    FinitelyPresentedGroups,
    Groups,
    GroupsWithChosenFiniteGeneratingSet,
    GroupsWithChosenFinitePresentation,
    OwnedAbelianGroups,
    OwnedFiniteAbelianGroups,
    OwnedFiniteGroups,
    OwnedFinitelyGeneratedGroups,
    OwnedFinitelyPresentedGroups,
    OwnedGroups,
    groups,
    refine_group,
)
from dzack_research.preamble.categories.group.submonoids import (
    Submonoids,
    generated_submonoid,
    predicate_submonoid,
)
from dzack_research.preamble.categories.group.predicate_subgroups import (
    PredicateSubgroups,
    centralizer,
    predicate_subgroup,
)

_PROFINITE_EXPORTS = frozenset(
    {
        "AbsoluteDecompositionGroup",
        "AbsoluteGaloisGroup",
        "AbsoluteGaloisGroupElement",
        "AbsoluteGaloisGroups",
        "AbsoluteGaloisGroupsOfFiniteFields",
        "AbsoluteGaloisSliceAutomorphism",
        "AbsoluteInertiaGroup",
        "ContinuousGroupHomset",
        "CyclotomicCharacter",
        "DecompositionGroupConjugacyClass",
        "ElementConjugacyClass",
        "ExactFieldHomset",
        "ExactFieldMorphism",
        "FiniteElementConjugacyClass",
        "FiniteGaloisAutomorphism",
        "FiniteGaloisExtension",
        "FiniteGaloisQuotient",
        "FiniteGaloisSubgroup",
        "FrobeniusConjugacyClass",
        "FrobeniusElement",
        "GaloisRestrictionMap",
        "InertiaGroupConjugacyClass",
        "LiftCoset",
        "OpenAbsoluteGaloisSubgroup",
        "OpenAbsoluteGaloisSubgroups",
        "OpenGaloisSubgroupConjugacyClass",
        "OpenSubgroupInclusion",
        "PrimeProlongation",
        "ProfiniteCharacter",
        "ProfiniteGroups",
        "QuadraticCharacter",
        "RestrictedProfiniteCharacter",
        "absolute_galois_group",
        "absolute_galois_group_category",
        "continuous_group_homset",
        "exact_embeddings",
        "exact_field_homset",
        "exact_field_morphism",
        "extensions_along",
        "field_generators",
        "finite_decomposition_group",
        "finite_frobenius_class",
        "finite_inertia_group",
        "first_exact_embedding",
        "open_absolute_galois_subgroup",
        "restrict_along",
    }
)


def __getattr__(name: str):
    if name not in _PROFINITE_EXPORTS:
        raise AttributeError(name)
    module = import_module("dzack_research.preamble.categories.group.profinite")
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "AbsoluteDecompositionGroup",
    "AbsoluteGaloisGroup",
    "AbsoluteGaloisGroupElement",
    "AbsoluteGaloisGroups",
    "AbsoluteGaloisGroupsOfFiniteFields",
    "AbsoluteGaloisSliceAutomorphism",
    "AbsoluteInertiaGroup",
    "AbelianGroups",
    "ContinuousGroupHomset",
    "CyclicSubgroup",
    "CyclotomicCharacter",
    "DecompositionGroupConjugacyClass",
    "ElementConjugacyClass",
    "ExactFieldHomset",
    "ExactFieldMorphism",
    "FiniteAbelianGroups",
    "FiniteElementConjugacyClass",
    "FiniteGSet",
    "FiniteGSets",
    "FiniteGaloisAutomorphism",
    "FiniteGaloisExtension",
    "FiniteGaloisQuotient",
    "FiniteGaloisSubgroup",
    "FiniteGroups",
    "FinitelyGeneratedGroups",
    "FinitelyPresentedGroups",
    "FrobeniusConjugacyClass",
    "FrobeniusElement",
    "GSets",
    "GSetHomset",
    "GSetMorphism",
    "GroupAutomorphism",
    "GroupAutomorphismGroup",
    "GroupHomomorphism",
    "GroupHomset",
    "GaloisRestrictionMap",
    "IndexedFreeGroupHomomorphism",
    "IndexedFreeGroupHomset",
    "InertiaGroupConjugacyClass",
    "LiftCoset",
    "OpenAbsoluteGaloisSubgroup",
    "OpenAbsoluteGaloisSubgroups",
    "OpenGaloisSubgroupConjugacyClass",
    "OpenSubgroupInclusion",
    "Groups",
    "GroupsWithChosenFiniteGeneratingSet",
    "GroupsWithChosenFinitePresentation",
    "OwnedAbelianGroups",
    "OwnedFiniteAbelianGroups",
    "OwnedFiniteGroups",
    "OwnedFinitelyGeneratedGroups",
    "OwnedFinitelyPresentedGroups",
    "OwnedGroups",
    "OrbitClass",
    "OrbitSet",
    "PredicateSubgroups",
    "PrimeProlongation",
    "ProfiniteCharacter",
    "ProfiniteGroups",
    "QuadraticCharacter",
    "RestrictedProfiniteCharacter",
    "Submonoids",
    "Torsors",
    "absolute_galois_group",
    "absolute_galois_group_category",
    "centralizer",
    "cyclic_subgroup",
    "continuous_group_homset",
    "exact_embeddings",
    "exact_field_homset",
    "exact_field_morphism",
    "extensions_along",
    "field_generators",
    "finite_decomposition_group",
    "finite_frobenius_class",
    "finite_inertia_group",
    "first_exact_embedding",
    "fixed_point_set",
    "g_set_homset",
    "generated_submonoid",
    "group_homset",
    "groups",
    "open_absolute_galois_subgroup",
    "predicate_subgroup",
    "predicate_submonoid",
    "refine_group",
    "restrict_along",
    "trivial_g_set",
]
