"""Lazy public aggregation for the owned group-theoretic vocabulary.

Defining modules remain independently importable; public names are loaded only
when requested so this package initializer is a dependency leaf.
"""

from importlib import import_module as _import_module

_EXPORTS = {'EquivariantMorphism': ('dzack_research.preamble.categories.group.g_objects', 'EquivariantMorphism'),
 'GObjectHomset': ('dzack_research.preamble.categories.group.g_objects', 'GObjectHomset'),
 'GObjects': ('dzack_research.preamble.categories.group.g_objects', 'GObjects'),
 'FiniteGSets': ('dzack_research.preamble.categories.group.g_sets', 'FiniteGSets'),
 'GSets': ('dzack_research.preamble.categories.group.g_sets', 'GSets'),
 'GSetHomset': ('dzack_research.preamble.categories.group.g_sets', 'GSetHomset'),
 'GSetMorphism': ('dzack_research.preamble.categories.group.g_sets', 'GSetMorphism'),
 'OrbitSets': ('dzack_research.preamble.categories.group.g_sets', 'OrbitSets'),
 'Torsors': ('dzack_research.preamble.categories.group.g_sets', 'Torsors'),
 'FiniteGroupClassFunction': ('dzack_research.preamble.categories.group.class_functions',
                              'FiniteGroupClassFunction'),
 'CyclicGroups': ('dzack_research.preamble.categories.group.cyclic_subgroups', 'CyclicGroups'),
 'AbelianGroups': ('dzack_research.preamble.categories.group.groups', 'AbelianGroups'),
 'AdditiveGroups': ('dzack_research.preamble.categories.group.magmas', 'AdditiveGroups'),
 'FiniteAbelianGroups': ('dzack_research.preamble.categories.group.groups', 'FiniteAbelianGroups'),
 'FiniteGroups': ('dzack_research.preamble.categories.group.groups', 'FiniteGroups'),
 'FinitelyGeneratedGroups': ('dzack_research.preamble.categories.group.groups',
                             'FinitelyGeneratedGroups'),
 'FinitelyPresentedGroups': ('dzack_research.preamble.categories.group.groups',
                             'FinitelyPresentedGroups'),
 'GroupAutomorphism': ('dzack_research.preamble.categories.group.groups', 'GroupAutomorphism'),
 'GroupAutomorphismGroup': ('dzack_research.preamble.categories.group.groups',
                            'GroupAutomorphismGroup'),
 'GroupHomomorphism': ('dzack_research.preamble.categories.group.groups', 'GroupHomomorphism'),
 'GroupHomset': ('dzack_research.preamble.categories.group.groups', 'GroupHomset'),
 'Groups': ('dzack_research.preamble.categories.group.groups', 'Groups'),
 'GroupsWithChosenFiniteGeneratingSet': ('dzack_research.preamble.categories.group.groups',
                                         'GroupsWithChosenFiniteGeneratingSet'),
 'GroupsWithChosenFinitePresentation': ('dzack_research.preamble.categories.group.groups',
                                        'GroupsWithChosenFinitePresentation'),
 'GroupsWithChosenFreeBasis': ('dzack_research.preamble.categories.group.groups',
                               'GroupsWithChosenFreeBasis'),
 'InfiniteGroups': ('dzack_research.preamble.categories.group.groups', 'InfiniteGroups'),
 'IndexedFreeGroupHomomorphism': ('dzack_research.preamble.categories.group.groups',
                                  'IndexedFreeGroupHomomorphism'),
 'IndexedFreeGroupHomset': ('dzack_research.preamble.categories.group.groups',
                            'IndexedFreeGroupHomset'),
 'OwnedAbelianGroups': ('dzack_research.preamble.categories.group.groups', 'OwnedAbelianGroups'),
 'OwnedFiniteAbelianGroups': ('dzack_research.preamble.categories.group.groups',
                              'OwnedFiniteAbelianGroups'),
 'OwnedFiniteGroups': ('dzack_research.preamble.categories.group.groups', 'OwnedFiniteGroups'),
 'OwnedFinitelyGeneratedGroups': ('dzack_research.preamble.categories.group.groups',
                                  'OwnedFinitelyGeneratedGroups'),
 'OwnedFinitelyPresentedGroups': ('dzack_research.preamble.categories.group.groups',
                                  'OwnedFinitelyPresentedGroups'),
 'OwnedGroups': ('dzack_research.preamble.categories.group.groups', 'OwnedGroups'),
 'OwnedInfiniteGroups': ('dzack_research.preamble.categories.group.groups', 'OwnedInfiniteGroups'),
 'Subgroups': ('dzack_research.preamble.categories.group.groups', 'Subgroups'),
 'groups': ('dzack_research.preamble.categories.group.groups', 'groups'),
 '_own_group': ('dzack_research.preamble.categories.group.groups', '_own_group'),
 'PredicateSubgroups': ('dzack_research.preamble.categories.group.predicate_subgroups',
                        'PredicateSubgroups'),
 'AbsoluteDecompositionGroup': ('dzack_research.preamble.categories.group.profinite',
                                'AbsoluteDecompositionGroup'),
 'AbsoluteGaloisGroup': ('dzack_research.preamble.categories.group.profinite',
                         'AbsoluteGaloisGroup'),
 'AbsoluteGaloisGroupElement': ('dzack_research.preamble.categories.group.profinite',
                                'AbsoluteGaloisGroupElement'),
 'AbsoluteGaloisGroups': ('dzack_research.preamble.categories.group.profinite',
                          'AbsoluteGaloisGroups'),
 'AbsoluteGaloisGroupsOfFiniteFields': ('dzack_research.preamble.categories.group.profinite',
                                        'AbsoluteGaloisGroupsOfFiniteFields'),
 'AbsoluteGaloisSliceAutomorphism': ('dzack_research.preamble.categories.group.profinite',
                                     'AbsoluteGaloisSliceAutomorphism'),
 'AbsoluteInertiaGroup': ('dzack_research.preamble.categories.group.profinite',
                          'AbsoluteInertiaGroup'),
 'CyclotomicCharacter': ('dzack_research.preamble.categories.group.profinite',
                         'CyclotomicCharacter'),
 'DecompositionGroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                                      'DecompositionGroupConjugacyClass'),
 'ElementConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                           'ElementConjugacyClass'),
 'ExactFieldMorphism': ('dzack_research.preamble.categories.group.profinite', 'ExactFieldMorphism'),
 'FiniteElementConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                                 'FiniteElementConjugacyClass'),
 'FiniteGaloisAutomorphism': ('dzack_research.preamble.categories.group.profinite',
                              'FiniteGaloisAutomorphism'),
 'FiniteGaloisExtension': ('dzack_research.preamble.categories.group.profinite',
                           'FiniteGaloisExtension'),
 'FiniteGaloisQuotient': ('dzack_research.preamble.categories.group.profinite',
                          'FiniteGaloisQuotient'),
 'FiniteGaloisSubgroup': ('dzack_research.preamble.categories.group.profinite',
                          'FiniteGaloisSubgroup'),
 'FrobeniusConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                             'FrobeniusConjugacyClass'),
 'FrobeniusElement': ('dzack_research.preamble.categories.group.profinite', 'FrobeniusElement'),
 'GaloisRestrictionMap': ('dzack_research.preamble.categories.group.profinite',
                          'GaloisRestrictionMap'),
 'InertiaGroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                                'InertiaGroupConjugacyClass'),
 'LiftCoset': ('dzack_research.preamble.categories.group.profinite', 'LiftCoset'),
 'OpenAbsoluteGaloisSubgroup': ('dzack_research.preamble.categories.group.profinite',
                                'OpenAbsoluteGaloisSubgroup'),
 'OpenAbsoluteGaloisSubgroups': ('dzack_research.preamble.categories.group.profinite',
                                 'OpenAbsoluteGaloisSubgroups'),
 'OpenGaloisSubgroupConjugacyClass': ('dzack_research.preamble.categories.group.profinite',
                                      'OpenGaloisSubgroupConjugacyClass'),
 'OpenSubgroupInclusion': ('dzack_research.preamble.categories.group.profinite',
                           'OpenSubgroupInclusion'),
 'PrimeProlongation': ('dzack_research.preamble.categories.group.profinite', 'PrimeProlongation'),
 'ProfiniteCharacter': ('dzack_research.preamble.categories.group.profinite', 'ProfiniteCharacter'),
 'ProfiniteGroups': ('dzack_research.preamble.categories.group.profinite', 'ProfiniteGroups'),
 'QuadraticCharacter': ('dzack_research.preamble.categories.group.profinite', 'QuadraticCharacter'),
 'RestrictedProfiniteCharacter': ('dzack_research.preamble.categories.group.profinite',
                                  'RestrictedProfiniteCharacter'),
}

__all__ = ['AbsoluteDecompositionGroup',
 'AbsoluteGaloisGroup',
 'AbsoluteGaloisGroupElement',
 'AbsoluteGaloisGroups',
 'AbsoluteGaloisGroupsOfFiniteFields',
 'AbsoluteGaloisSliceAutomorphism',
 'AbsoluteInertiaGroup',
 'AbelianGroups',
 'AdditiveGroups',
 'CyclicGroups',
 'CyclotomicCharacter',
 'DecompositionGroupConjugacyClass',
 'ElementConjugacyClass',
 'EquivariantMorphism',
 'ExactFieldMorphism',
 'FiniteAbelianGroups',
 'FiniteElementConjugacyClass',
 'FiniteGSets',
 'FiniteGaloisAutomorphism',
 'FiniteGaloisExtension',
 'FiniteGaloisQuotient',
 'FiniteGaloisSubgroup',
 'FiniteGroups',
 'FiniteGroupClassFunction',
 'FinitelyGeneratedGroups',
 'FinitelyPresentedGroups',
 'FrobeniusConjugacyClass',
 'FrobeniusElement',
 'GObjectHomset',
 'GObjects',
 'GSets',
 'GSetHomset',
 'GSetMorphism',
 'GroupAutomorphism',
 'GroupAutomorphismGroup',
 'GroupHomomorphism',
 'GroupHomset',
 'GaloisRestrictionMap',
 'IndexedFreeGroupHomomorphism',
 'IndexedFreeGroupHomset',
 'InertiaGroupConjugacyClass',
 'LiftCoset',
 'OpenAbsoluteGaloisSubgroup',
 'OpenAbsoluteGaloisSubgroups',
 'OpenGaloisSubgroupConjugacyClass',
 'OpenSubgroupInclusion',
 'Groups',
 'GroupsWithChosenFiniteGeneratingSet',
 'GroupsWithChosenFinitePresentation',
 'GroupsWithChosenFreeBasis',
 'InfiniteGroups',
 'OwnedAbelianGroups',
 'OwnedFiniteAbelianGroups',
 'OwnedFiniteGroups',
 'OwnedFinitelyGeneratedGroups',
 'OwnedFinitelyPresentedGroups',
 'OwnedGroups',
 'OwnedInfiniteGroups',
 'Subgroups',
 'OrbitSets',
 'PredicateSubgroups',
 'PrimeProlongation',
 'ProfiniteCharacter',
 'ProfiniteGroups',
 'QuadraticCharacter',
 'RestrictedProfiniteCharacter',
 'Torsors',
 'groups',
]

def __getattr__(name):
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(name) from error
    module = _import_module(module_name)
    value = getattr(module, attribute)
    globals()[name] = value
    # Importing a direct child installs the child module under its basename on
    # this package.  Restore any public alias that deliberately uses that same
    # name (notably ``groups = OwnedGroups``) instead of leaking the module.
    basename = module_name.rsplit(".", 1)[-1]
    exported_alias = _EXPORTS.get(basename)
    if exported_alias is not None and exported_alias[0] == module_name:
        globals()[basename] = getattr(module, exported_alias[1])
    return value

def __dir__():
    return sorted((*globals(), *__all__))
