r"""Cyclic groups: groups generated by a single chosen element."""

from sage.misc.cachefunc import cached_method
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.abstract_categories.cat import Cat
from dzack_research.preamble.categories.abstract_categories.objects import OwnedCategory
from dzack_research.preamble.categories.group.groups import (
    FiniteAbelianGroups,
    FiniteGroups,
    GroupsWithChosenFiniteGeneratingSet,
    OwnedAbelianGroups,
    Subgroups,
    _owned_group,
)
from dzack_research.preamble.categories.rings.ring_foundation import _own_ring
from dzack_research.preamble.categories.sets.cardinals import cardinal
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.owned_category import _object_of


__all__ = ["CyclicGroups"]


class CyclicGroups(OwnedCategory):
    r"""Groups generated by one chosen element.

    The generator is the datum: a cyclic group is one for which such an element
    exists, and an object of this category has selected one.  Everything below
    is computed by walking that generator.
    """

    def an_object(self):
        r"""``<s> <= C_2``, generated by the nonidentity element."""
        from dzack_research.preamble.categories.group.groups import OwnedGroups

        group = OwnedGroups().C(2)
        (element,) = tuple(group.group_generators())
        return self(element)

    @classmethod
    def _repr_object_names(cls):
        return "cyclic groups"

    def super_categories(self):
        return [OwnedAbelianGroups(), GroupsWithChosenFiniteGeneratingSet()]

    def _call_(self, generator, *, placements=(), **level_data):
        r"""Construct the cyclic subgroup from its selected generator.

        The generator determines both the ambient group and the subgroup
        construction.  The returned object is a facade of that ambient group,
        so its elements remain the ambient elements rather than a parallel
        abstract cyclic-group model.
        """
        supergroup = _owned_group(generator.parent())
        placement = [self, Subgroups(supergroup), *placements]
        if supergroup in FiniteGroups():
            placement.append(FiniteAbelianGroups())
        return _object_of(
            Cat().meet(placement),
            supergroup=supergroup,
            group_generator=supergroup(generator),
            **level_data,
        )

    class ParentMethods:
        def __init__(self, group_generator, **rest) -> None:
            self._group_generator = group_generator
            super().__init__(**rest)

        def group_generator(self):
            r"""Return the element this group is generated by."""
            return self._group_generator

        @cached_method
        def group_generators(self):
            if self.group_generator() == self.supergroup().one():
                return finite_ordered_set(())
            return finite_ordered_set((self.group_generator(),))

        def number_of_group_generators(self):
            return _own_ring(SageZZ)(int(self.group_generators().cardinality()))

        def one(self):
            return self.supergroup().one()

        def is_finite(self):
            r"""Whether ``<g>`` is finite: always in a finite group, else exactly when ``g`` has finite order."""
            if self.supergroup() in FiniteGroups():
                return True
            return cardinal(self.group_generator().order()).is_finite()

        def is_abelian(self):
            return True

        @cached_method
        def _finite_elements(self):
            r"""The powers ``1, g, g^2, ...`` of the generator up to its order."""
            assert self.is_finite() is True, (
                "enumerating a cyclic subgroup requires its order to be decided finite"
            )
            ambient = self.supergroup()
            identity = ambient.one()
            generator = self.group_generator()
            bound = (
                ambient.order()
                if ambient in FiniteGroups()
                else generator.order()
            )
            elements = [identity]
            current = identity
            for _ in range(int(bound)):
                current = generator * current
                if current == identity:
                    return tuple(elements)
                elements.append(current)
            raise ArithmeticError("a subgroup generator did not close within the ambient group order")

        def order(self):
            if self.is_finite() is True:
                if self.supergroup() not in FiniteGroups():
                    return self.group_generator().order()
                ambient_order = self.supergroup().order()
                return ambient_order.parent()(len(self._finite_elements()))
            return self.cardinality()

        def cardinality(self):
            if self.is_finite() is True:
                return cardinal(self.order())
            assert False, (
                "cardinality is defined for every cyclic subgroup, but this represented "
                "subgroup does not decide whether its order is finite"
            )

        def __iter__(self):
            return iter(self._finite_elements())

        def __contains__(self, element):
            ambient = self.supergroup()
            if element not in ambient:
                return False
            if self.is_finite() is True:
                return any(element == candidate for candidate in self._finite_elements())
            if element == ambient.one() or element == self.group_generator():
                return True
            assert False, (
                "membership in an infinite cyclic subgroup beyond the identity and its "
                "generator is the discrete-logarithm question, and no decision is represented here"
            )

        def _element_constructor_(self, datum):
            element = self.supergroup()(datum)
            if element not in self:
                raise ValueError(f"{element} is not in {self}")
            return element

        def _repr_(self):
            return f"<{self.group_generator()}> <= {self.supergroup()}"
