r"""Cyclic groups: groups generated by a single chosen element."""

from sage.misc.cachefunc import cached_method
from sage.misc.unknown import Unknown
from sage.rings.integer_ring import ZZ as SageZZ

from dzack_research.preamble.categories.abstract_categories.cat import Cat
from dzack_research.preamble.categories.abstract_categories.objects import OwnedCategory
from dzack_research.preamble.categories.group.groups import (
    FiniteAbelianGroups,
    FiniteGroups,
    GroupsWithChosenFiniteGeneratingSet,
    OwnedAbelianGroups,
    Subgroups,
    _owned_group,
)
from dzack_research.preamble.categories.rings.ring_foundation import _own_ring
from dzack_research.preamble.categories.sets.cardinals import cardinal
from dzack_research.preamble.categories.sets.finite_ordered_sets import finite_ordered_set
from dzack_research.preamble.owned_category import object_of


def cyclic_subgroup(generator):
    r"""Return the literal cyclic subgroup ``<g> <= G`` generated by ``g``.

    This notebook notation delegates to :class:`CyclicGroups`, which owns the
    selected generator and ambient subgroup placement.
    """
    return CyclicGroups()(generator)


__all__ = ["CyclicGroups", "cyclic_subgroup"]


class CyclicGroups(OwnedCategory):
    r"""Groups generated by one chosen element.

    The generator is the datum: a cyclic group is one for which such an element
    exists, and an object of this category has selected one.  Everything below
    is computed by walking that generator.
    """

    def an_object(self):
        r"""``<s> <= C_2``, generated by the nonidentity element."""
        from dzack_research.preamble.categories.group.groups import OwnedGroups

        group = OwnedGroups().C(2)
        (element,) = tuple(group.group_generators())
        return self(element)

    @classmethod
    def _repr_object_names(cls):
        return "cyclic groups"

    def super_categories(self):
        return [OwnedAbelianGroups(), GroupsWithChosenFiniteGeneratingSet()]

    def _call_(self, generator):
        r"""Construct the cyclic subgroup from its selected generator.

        The generator determines both the ambient group and the subgroup
        construction.  The returned object is a facade of that ambient group,
        so its elements remain the ambient elements rather than a parallel
        abstract cyclic-group model.
        """
        supergroup = _owned_group(generator.parent())
        placement = [self, Subgroups(supergroup)]
        if supergroup in FiniteGroups():
            placement.append(FiniteAbelianGroups())
        return object_of(
            Cat().meet(placement),
            supergroup=supergroup,
            generator=supergroup(generator),
        )

    class ParentMethods:
        def __init__(self, generator, **rest) -> None:
            self._generator = generator
            super().__init__(**rest)

        def generator(self):
            r"""Return the element this group is generated by."""
            return self._generator

        selected_generator = generator

        @cached_method
        def group_generators(self):
            if self.generator() == self.supergroup().one():
                return finite_ordered_set(())
            return finite_ordered_set((self.generator(),))

        def number_of_group_generators(self):

            return _own_ring(SageZZ)(int(self.group_generators().cardinality()))

        def one(self):
            return self.supergroup().one()

        def is_finite(self):

            if self.supergroup() in FiniteGroups():
                return True
            try:
                from sage.rings.infinity import Infinity

                order = self.generator().order()
            except (AttributeError, NotImplementedError, TypeError, ValueError):
                return Unknown
            return False if order == Infinity else True

        def is_abelian(self):
            return True

        @cached_method
        def _finite_elements(self):
            if self.is_finite() is not True:
                raise NotImplementedError(
                    "enumerating a cyclic subgroup requires its order to be decided finite"
                )
            ambient = self.supergroup()
            identity = ambient.one()
            generator = self.generator()
            bound = (
                ambient.order()
                if ambient in FiniteGroups()
                else self.generator().order()
            )
            elements = [identity]
            current = identity
            for _ in range(int(bound)):
                current = generator * current
                if current == identity:
                    return tuple(elements)
                elements.append(current)
            raise ArithmeticError("a subgroup generator did not close within the ambient group order")

        def order(self):
            if self.is_finite() is True:
                if self.supergroup() not in FiniteGroups():
                    return self.generator().order()
                ambient_order = self.supergroup().order()
                return ambient_order.parent()(len(self._finite_elements()))
            return self.cardinality()

        def cardinality(self):
            if self.is_finite() is True:
                return cardinal(self.order())
            assert False, (
                "cardinality is defined for every cyclic subgroup, but this represented "
                "subgroup does not decide whether its order is finite"
            )

        def __iter__(self):
            return iter(self._finite_elements())

        def __contains__(self, element):
            ambient = self.supergroup()
            try:
                if element not in ambient:
                    return False
            except TypeError:
                return False
            if self.is_finite() is True:
                return any(element == candidate for candidate in self._finite_elements())
            if element == ambient.one() or element == self.generator():
                return True
            raise NotImplementedError(
                "membership in this infinite-or-undecided cyclic subgroup is not computed"
            )

        def _element_constructor_(self, datum):
            element = self.supergroup()(datum)
            if element not in self:
                raise ValueError(f"{element} is not in {self}")
            return element

        def _repr_(self):
            return f"<{self.generator()}> <= {self.supergroup()}"
