r"""Owned categories of groups."""

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from sage_lattice_category_spike.lexicon import Cardinal
    from sage_lattice_category_spike.lexicon import Group
    from sage_lattice_category_spike.lexicon import Module
    from sage_lattice_category_spike.lexicon import OrderedSet

from typing import Any
if TYPE_CHECKING:
    from typing import Callable

from sage_lattice_category_spike.objects.sets import Sets
if TYPE_CHECKING:
    from sage.categories.morphism import Morphism

from typing import Self

from sage.misc.cachefunc import cached_method
from sage.categories.category import Category
from sage.categories.finite_groups import FiniteGroups as SageFiniteGroups
from sage.misc.abstract_method import abstract_method
from sage.categories.groups import Groups as SageGroups
from sage.categories.homset import Hom
from sage.categories.morphism import SetMorphism
from sage.categories.rings import Rings
from sage.groups.abelian_gps.abelian_group import AbelianGroup_class
from sage.groups.finitely_presented import FinitelyPresentedGroup
from sage.groups.free_group import FreeGroup_class
from sage.groups.matrix_gps.named_group import NamedMatrixGroup_generic
from sage.groups.matrix_gps.named_group_gap import NamedMatrixGroup_gap
from sage.groups.perm_gps.permgroup import PermutationGroup_generic
from sage.misc.latex import latex
from sage.misc.unknown import Unknown
from dzack_research.preamble.categories.rings.rings import ℤ
from sage.rings.integer_ring import ZZ as SageZZ
from sage.sets.totally_ordered_finite_set import TotallyOrderedFiniteSet
from sage.structure.element import Element
from sage.structure.parent import Parent


def _engine_answer(group: "Group", question: str) -> "Any":
    r"""Return the engine's answer to ``question``, or ``Unknown``.

    Asked of the class Sage built rather than of ``group``, because the owned
    node sits in front of that class: asking the object would find the owned
    method that called this one.

    Sage says "I cannot decide" in two ways -- no such method, and a method
    that raises ``NotImplementedError`` -- and neither is mathematics.  Both
    become ``Unknown``, which carries the same information as a value.  Any
    other exception is a defect and is left to raise.

    ``super`` and not the class, because what is wanted is a *bound* answer:
    a cached method reached through its class is a descriptor and not a
    function of the group.
    """
    try:
        answer = getattr(super(OwnedGroups.ParentMethods, group), question)
    except AttributeError:
        return Unknown
    try:
        return answer()
    except NotImplementedError:
        return Unknown


def _finiteness(group: "Group") -> "bool | Unknown":
    r"""Return whether ``group`` is finite, as a value.

    The group's own answer wherever it has one, so a category that decides
    finiteness -- ``LatticeIsometries`` puts the question to GAP -- is the one
    that answers.  A group placed in no owned node has not got
    :meth:`OwnedGroups.ParentMethods.is_finite` yet, which is why the decline
    is caught here too.
    """
    try:
        return group.is_finite()
    except NotImplementedError:
        return Unknown


class OwnedGroups(Category):
    r"""Groups whose notebook-facing methods are owned by the preamble."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "groups"

    def super_categories(self) -> list:
        return [SageGroups()]

    class ParentMethods:
        def group_generators(self: Self) -> "OrderedSet":
            r"""Return \(S\), the images in \(G\) of the generating morphism.

            Honest elements of this group, and an ordered set of them: the
            enumeration the group lists them in is the order, and it is
            placed rather than rebuilt, which would discard it.  Finiteness
            is not part of it -- a group is not finitely generated by being
            a group -- so an infinite generating set survives being asked.

            Dropping the identity needs the set enumerated, so it happens at
            the finitely generated node and not here.
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.refine import refine

            family = SageGroups().ParentMethods.group_generators(self)
            if family.category().is_subcategory(Sets().TotallyOrdered()):
                return family
            return refine(family, Sets().TotallyOrdered())

        def number_of_group_generators(self: Self) -> "Cardinal":
            r"""Return \(|S|\), which is a cardinal and may be infinite."""
            return self.group_generators().cardinality()

        def is_finitely_generated(self: Self) -> "bool | Unknown":
            r"""Return whether \(G\) admits a finite generating set.

            Total: ``True``, ``False``, or ``Unknown``, never an exception.
            Sage answers this with two different exception types -- no such
            method, and a method that declines to decide -- and neither
            carries mathematics, so callers would have to catch to learn
            what is true.

            Layered, because no single signal is sound.  Sage's
            ``FinitelyGenerated`` is a declaration rather than a decision, so
            its ``True`` is evidence and its ``False`` is not: the free group
            on two generators stands outside it.  A finite group generates
            itself.  Failing both, the group is asked, and if it cannot say,
            the answer is ``Unknown``.
            """
            if self in SageGroups().FinitelyGenerated():
                return True
            if _finiteness(self) is True:
                return True
            if self.has_computed_group_generators() is True:
                return True
            if self.group_generators_are_computable() is True:
                return True
            if self.is_arithmetic_group() is True:
                return True
            return Unknown

        def is_finite(self: Self) -> "bool | Unknown":
            r"""Return whether \(|G|\) is finite, as a value.

            A group placed in the finite groups category is finite, and that
            is the end of the question -- the placement is the statement, and
            a group carrying it needs no procedure run over it.  Sage's own
            procedure computes the order to decide, which for such a group is
            asking the cardinality to decide its own finiteness.

            Otherwise the group is asked.  A procedure that declines to decide
            is saying it does not know, which is what ``Unknown`` is for:
            ``Sp_4(\ZZ)`` reaches here, and the exception Sage raises instead
            says nothing about the group.
            """
            if self in SageFiniteGroups():
                return True
            return _engine_answer(self, "is_finite")

        def ngens(self: Self) -> "Integer | Unknown":
            r"""Return the size of the generating set the engine holds.

            Sage answers for a group whose generators it can produce and
            raises ``AttributeError`` for one it cannot, so a caller has to
            catch to learn that nobody knows the generators.  That is the
            same fact ``Unknown`` states as a value.

            The preamble's own word is
            :meth:`number_of_group_generators`, which says which structure is
            generated; this spelling is kept because it is the one Sage's
            callers already type.
            """
            return _engine_answer(self, "ngens")

        def is_arithmetic_group(self: Self) -> "bool | Unknown":
            r"""Return whether \(G\) is the \(\ZZ\)-points of an algebraic group.

            Arithmetic groups are finitely generated -- Borel and
            Harish-Chandra -- and that theorem is the only evidence available
            for \(Sp_{2n}(\ZZ)\), whose generating set Hua and Reiner exhibit
            and Sage cannot produce.

            The witness is a *named* classical group, one carrying a degree
            and a ring rather than a list of generators, whose scalars are the
            integers: \(SL_n\), \(GL_n\), \(Sp_{2n}\) and \(O(q)\) over
            \(\ZZ\) are each the integral points of a linear algebraic group
            defined over \(\QQ\).  Over any other ring the construction says
            nothing -- \(SO_3(\QQ)\) is not arithmetic and not finitely
            generated -- so the answer is ``Unknown`` and not ``False``: a
            group Sage built some other way may be arithmetic, and nothing
            here decides it.
            """
            if (
                isinstance(self, NamedMatrixGroup_generic)
                and self.base_ring() is SageZZ
            ):
                return True
            return Unknown

        def group_generators_are_computable(self: Self) -> "bool | Unknown":
            r"""Return whether some algorithm produces a generating set.

            Asked of this object's resolution order with the owned nodes'
            own answer discounted.  ``OwnedGroups`` gives *every* group it
            holds a ``group_generators`` that reads the group's ``gens``, so
            asking the object whether the method is there finds the
            preamble's own and says yes about a group -- \(SO_3(\QQ)\) --
            whose generating set nobody can produce.  What is left is the
            engine's method, or a category that computes one, as
            ``LatticeIsometries`` does from the Gram matrix.

            True does not promise the computation is cheap -- ``O(L)`` for a
            definite lattice is computable and slow.  It promises only that
            asking is meaningful.  Absence is ``Unknown``: no algorithm in
            this engine is not the same as no algorithm.
            """
            generic = (
                OwnedGroups.ParentMethods,
                OwnedFinitelyGeneratedGroups.ParentMethods,
            )
            for holder in type(self).__mro__:
                if holder in generic:
                    continue
                if "group_generators" in vars(holder) or "gens" in vars(holder):
                    return True
            return Unknown

        def has_computed_group_generators(self: Self) -> "bool | Unknown":
            r"""Return whether a generating set is already in hand.

            The one case that is free.  A group given by generators and
            relations, or carved out of \(GL_n(R)\) on stated matrices,
            answers ``True`` and no computation follows.
            """
            for stored in ("_group_generators", "_gens"):
                if self.__dict__.get(stored) is not None:
                    return True
            return Unknown


class OwnedFinitelyGeneratedGroups(Category):
    r"""Groups admitting a surjection \(F(S)\twoheadrightarrow G\), \(S\) finite.

    Finite generation is a property of a *morphism* -- the existence of that
    surjection -- and not of a stored list of elements.  Stated this way the
    next axiom has something to be the kernel of.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated groups"

    def super_categories(self) -> list:
        r"""Return the owned node and Sage's own finite-generation axiom.

        Sage's axiom is stated here rather than claimed again at each
        construction: a group placed in this category *is* finitely generated
        in Sage's vocabulary, and a reader who asks in Sage's words gets the
        preamble's answer.  A parallel axiom would split every later reader
        into two who disagree about the same group.
        """
        return [OwnedGroups(), SageGroups().FinitelyGenerated()]

    class ParentMethods:
        def group_generators(self: Self) -> TotallyOrderedFiniteSet:
            r"""Return \(S\), which the axiom makes a *finite* ordered set.

            The same generating set, with the finiteness the axiom supplies.
            The enumeration is handed over as the order rather than re-sorted,
            so a family indexed \(1,\dots,n\) keeps its indexing.

            The identity is dropped, which is only possible where the set can
            be enumerated: \(\langle S\rangle=\langle S\setminus\{1\}\rangle\)
            for every \(S\), so it never generates anything, and the trivial
            group is generated by \(\emptyset\) rather than by \(\{1\}\).
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.sets.sets import finite_ordered_set

            identity = self.one()
            return finite_ordered_set(
                tuple(
                    generator
                    for generator in SageGroups().ParentMethods.group_generators(
                        self
                    )
                    if generator != identity
                )
            )

        def _latex_(self: Self) -> str:
            r"""Return the group displayed by a finite generating set."""
            group_generators = self.group_generators()
            if not group_generators:
                return r"\{1\}"
            entries = ", ".join(str(latex(generator)) for generator in group_generators)
            return rf"\left\langle {entries} \right\rangle"


def _presentation_of(group: "Group") -> tuple:
    r"""Return \((F(S), R)\) for a finitely presented group.

    \(C_2\), \(S_2\), \(\langle x\mid x^2\rangle\) and \(\mathbb Z/2\) are the
    same finitely presented group, so each of them has generators and
    relations to hand over and none of them is *interpreted as* anything.
    What differs is only where the type it arrived as keeps them, and this is
    the one place that says so.  A type that cannot say is rejected here
    rather than answered with a guess.

    A group the preamble built has no Sage type to read a presentation off, so
    the owned category asks it instead: membership in
    :class:`OwnedFinitelyPresentedGroups` is the promise that
    ``presented_group`` answers, which is what makes this a routing decision
    and not a probe for a method that may or may not be there.  \(O(L)\) is
    the case, computing its presentation from its own matrix-group model.

    The match below is for groups that arrived as a Sage type and are asked
    through a wrapper, which hands over the engine rather than itself.
    """
    if group in OwnedFinitelyPresentedGroups():
        presented = group.presented_group()
        return presented.free_group(), tuple(presented.relations())

    match group:
        case FreeGroup_class():
            return group, ()
        case FinitelyPresentedGroup():
            return group.free_group(), tuple(group.relations())
        case PermutationGroup_generic():
            presented = group.as_finitely_presented_group()
            return presented.free_group(), tuple(presented.relations())
        case AbelianGroup_class():
            presented = group.permutation_group().as_finitely_presented_group()
            return presented.free_group(), tuple(presented.relations())
        case _:
            assert False, (
                f"{group} does not say where its presentation is kept"
            )


class OwnedFinitelyPresentedGroups(Category):
    r"""Finitely generated groups whose defining surjection has
    finitely generated kernel.

    Strictly stronger than finite generation: there are finitely generated
    groups admitting no finite presentation.  Strictly weaker than finiteness:
    \(O(L)\) for indefinite \(L\) is finitely presented and infinite.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely presented groups"

    def super_categories(self) -> list:
        return [OwnedFinitelyGeneratedGroups()]

    class ParentMethods:
        @abstract_method
        def presented_group(self: Self) -> "Group":
            r"""Return a finitely presented group presenting this one.

            The axiom's obligation, demanded of every object placed here: a
            group is finitely presented by exhibiting a presentation, and this
            is where it says which one.  ``presenting_free_group`` and
            ``defining_relations`` are the two halves read off the answer, so
            an object implements this and never those.

            A group that arrived as a Sage type is asked through a wrapper,
            which hands ``_presentation_of`` the engine; the engine is not
            placed in this category and reaches the type-based route instead.
            """

        def presenting_free_group(self: Self) -> "Group":
            r"""Return \(F(S)\), the free group the relations are words in."""
            free_group, _ = _presentation_of(self)
            # Finitely generated with no probe needed: the alphabet is finite
            # by construction, and it is the surjection's own generating set.
            if not free_group.category().is_subcategory(
                OwnedFinitelyGeneratedGroups()
            ):
                free_group._refine_category_(OwnedFinitelyGeneratedGroups())
            return free_group

        def defining_relations(self: Self) -> "OrderedSet":
            r"""Return the relations of this group's presentation.

            The relations generate the kernel of \(F(S)\twoheadrightarrow G\),
            so they are a set of words in \(F(S)\) -- not the words themselves
            repeated, and not an ordering the presentation depends on.
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.sets.sets import finite_ordered_set

            _, relations = _presentation_of(self)
            return finite_ordered_set(relations)

        def _latex_(self: Self) -> str:
            r"""Return the group displayed by a presentation \(\langle S\mid R\rangle\).

            \(S\) is the generating set of \(F(S)\), not of \(G\): the
            relations are words in \(F(S)\), and the presenting map need not
            be injective -- in the trivial group every generator has the same
            image, so \(G\)'s own generating set is a single element and names
            none of the letters the relations are written in.  That is what
            distinguishes this from
            :meth:`OwnedFinitelyGeneratedGroups.ParentMethods._latex_`, which
            displays the set \(G\) is generated by.
            """
            generators = ", ".join(
                str(latex(generator))
                for generator in self.presenting_free_group().group_generators()
            )
            relations = ", ".join(
                str(latex(relation)) for relation in self.defining_relations()
            )
            if not generators:
                return r"\{1\}"
            if not relations:
                return rf"\left\langle {generators} \right\rangle"
            return (
                rf"\left\langle {generators} \;\middle|\; {relations} \right\rangle"
            )


class AbelianGroupEndomorphism(Element):
    r"""An endomorphism of an abelian group.

    A map, held as one.  Images of a generating set would be a presentation,
    and endomorphisms are wanted here for groups that have no distinguished
    one -- a permutation group has no coordinates to read an exponent off.
    """

    def __init__(self, parent: "Parent", mapping: "Callable") -> None:
        Element.__init__(self, parent)
        self._mapping = mapping

    def __call__(self, element: "Element") -> "Element":
        return self._mapping(element)

    def _add_(self, other: "AbelianGroupEndomorphism") -> "AbelianGroupEndomorphism":
        r"""Return \(f+g:x\mapsto f(x)g(x)\).

        A homomorphism exactly because the target is abelian:
        \((f+g)(xy)=f(x)f(y)g(x)g(y)\), and the middle pair commutes past
        each other to give \((f+g)(x)(f+g)(y)\).  This is the whole reason
        the endomorphism ring is a ring, and the reason it is built here.
        """
        return self.parent()(lambda element: self(element) * other(element))

    def _neg_(self) -> "AbelianGroupEndomorphism":
        return self.parent()(lambda element: self(element) ** -1)

    def _mul_(self, other: "AbelianGroupEndomorphism") -> "AbelianGroupEndomorphism":
        r"""Return the composite \(f\circ g\), the ring's multiplication."""
        return self.parent()(lambda element: self(other(element)))


class AbelianGroupEndomorphismRing(Parent):
    r"""\(\operatorname{End}(A)\) for \(A\) abelian, as a ring.

    Endomorphisms of any group compose, so they always form a monoid; they
    add only when the target is abelian.  So this is a ring precisely for the
    groups this category holds, and Sage builds no such ring for them --
    ``End(AbelianGroup([3]))`` is not in ``Rings()`` and declines to construct
    a morphism from generator images at all.
    """

    Element = AbelianGroupEndomorphism

    def __init__(self, group: "Group") -> None:
        assert group.is_abelian(), (
            f"{group} is not abelian, so its endomorphisms do not add"
        )
        self._group = group
        Parent.__init__(self, category=Rings())

    def domain(self) -> "Group":
        return self._group

    def codomain(self) -> "Group":
        return self._group

    def _element_constructor_(self, mapping: "Callable") -> AbelianGroupEndomorphism:
        return self.element_class(self, mapping)

    def one(self) -> AbelianGroupEndomorphism:
        return self(lambda element: element)

    def zero(self) -> AbelianGroupEndomorphism:
        return self(lambda element: self._group.one())

    def __hash__(self) -> int:
        return hash((type(self), self._group))

    def __eq__(self, other: object) -> bool:
        return type(other) is type(self) and self._group == other._group

    def _repr_(self) -> str:
        return f"Endomorphism ring of {self._group}"


class OwnedAbelianGroups(Category):
    r"""Abelian groups.

    \(\mathrm{Ab}\) and \(\mathbb Z\text{-Mod}\) are isomorphic categories.
    That is not the statement that a group parent already is a module: a
    \(\mathbb Z\)-module is a pair \((S,\rho)\) and \(\rho\) is structure, so
    it has to be put there.  What the isomorphism says is that there is no
    choice in putting it -- see :meth:`as_module`.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "abelian groups"

    def super_categories(self) -> list:
        return [OwnedGroups()]

    class ParentMethods:
        @cached_method
        def endomorphism_ring(self: Self) -> AbelianGroupEndomorphismRing:
            r"""Return \(\operatorname{End}(A)\), a ring because \(A\) is abelian."""
            return AbelianGroupEndomorphismRing(self)

        @cached_method
        def integer_action(self: Self) -> "Morphism":
            r"""Return the unique \(\rho:\mathbb Z\to\operatorname{End}(A)\).

            \(\mathbb Z\) is initial in rings, so there is exactly one ring
            morphism out of it into any ring, and \(\operatorname{End}(A)\) is
            a ring.  That is the whole content of
            \(\mathrm{Ab}\cong\mathbb Z\text{-Mod}\): the action exists and
            nothing about it is chosen.  It sends \(n\) to the \(n\)-th power
            map, which is what \(\rho(n)=n\cdot 1\) unwinds to.
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.rings.rings import own_ring

            endomorphisms = self.endomorphism_ring()
            # \(\ZZ\) named as the session names it: \(\rho\)'s domain is the
            # ring of scalars a notebook asks about, and no arithmetic runs on
            # it here -- the action is a map of sets on the nose.
            return SetMorphism(
                Hom(ℤ, endomorphisms, Rings()),
                lambda exponent: endomorphisms(
                    lambda element: element**exponent
                ),
            )

        @cached_method
        def as_module(self: Self) -> "Module":
            r"""Return this group as a \(\mathbb Z\)-module.

            The elements are unchanged -- this group's own -- and \(\rho\) is
            what is added.  Presenting the module by invariant factors instead
            would answer with a different set of elements, and would choose a
            decomposition where the isomorphism asks for none.
            """
            # Local: a module-level import would close a cycle; the module is built by the time this runs.
            from dzack_research.preamble.categories.modules.scalar_actions import module_over_ring

            return module_over_ring(self.integer_action())


class OwnedFiniteGroups(Category):
    r"""Finite groups whose notebook-facing methods are owned by the preamble."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finite groups"

    def super_categories(self) -> list:
        return [OwnedGroups(), SageFiniteGroups()]


def _answers_abelian(group: "Group") -> bool:
    r"""Return whether ``group`` decides commutativity.

    Sage's free groups raise rather than answer, and a free group of rank one
    is abelian -- so a group declining the question is not a group that is
    nonabelian.  Placing on a witness and not on a default is the difference.
    """
    try:
        return bool(group.is_abelian())
    except NotImplementedError:
        return False


def refine_group(group: "Group") -> "Group":
    r"""Put ``group`` in the owned category, and return it.

    The generator probes live on the owned node, so a group reaches them by
    being refined into it -- and every group the preamble receives, whatever
    built it, is a group the preamble may have to ask.
    """
    if not group.category().is_subcategory(OwnedGroups()):
        group._refine_category_(OwnedGroups())
    return group


def _group_categories(group: "Group") -> list:
    r"""Return the owned categories ``group``'s presentation witnesses.

    Each axiom is claimed only when the group carries the witness the
    definition asks for, never when a theorem would be needed:

    * finitely generated -- a finite generating set, which *is* the surjection
      \(F(S)\twoheadrightarrow G\);
    * finitely presented -- a finite presentation, or finiteness, whose
      multiplication table is one;
    * abelian -- commutativity, as decided by the group.

    A group that answers none of these is still a group, and is placed as one.
    """
    categories = [OwnedGroups()]
    if _finiteness(group) is True:
        categories.append(OwnedFiniteGroups())
    # The probe, not ``ngens`` directly: a group that cannot answer must not
    # take the placement down with it, and Unknown is the honest outcome for
    # one whose generators nobody knows how to produce.
    if OwnedGroups.ParentMethods.is_finitely_generated(group) is True:
        categories.append(OwnedFinitelyGeneratedGroups())
    if (
        _finiteness(group) is True
        or isinstance(group, (FinitelyPresentedGroup, FreeGroup_class))
    ):
        categories.append(OwnedFinitelyPresentedGroups())
    if _answers_abelian(group):
        categories.append(OwnedAbelianGroups())
    return categories


class OwnedGroup(Parent):
    r"""The group a Sage group presents, as an owned object.

    Constructed from the Sage group rather than refined onto it.  Refining
    reassigns ``__class__`` on a parent this preamble did not build and cannot
    answer for: the object keeps whatever data Sage gave it, gains methods that
    ask for data an owned constructor would have stored, and fails at the first
    one that does.  Construction has no such gap -- the categories are settled
    here, from :func:`_group_categories`, so there is nothing left to refine.

    The elements are the Sage group's own.  A group's underlying set does not
    change by being placed, and the multiplication that makes it a group is the
    one the engine already computes.

    The engine crosses the boundary once, here, and is private afterwards.
    Handing it back out would make every method below optional: a caller who
    can reach the Sage group asks it directly, in Sage's nouns, and the owned
    object stops being where the group's questions are answered.
    """

    def __init__(self, engine: "Group") -> None:
        assert engine in SageGroups(), f"{engine} is not a group"
        # Refined on intake, so every question below is asked in the
        # preamble's words rather than translated at each call site.
        if not engine.category().is_subcategory(OwnedGroups()):
            engine._refine_category_(OwnedGroups())
        self._engine = engine
        Parent.__init__(self, category=_group_categories(engine))

    def _element_constructor_(self, value: "Element") -> "Element":
        return self._engine(value)

    def __contains__(self, value: object) -> bool:
        return value in self._engine

    def __iter__(self):
        return iter(self._engine)

    def one(self) -> "Element":
        return self._engine.one()

    def an_element(self) -> "Element":
        return self._engine.an_element()

    def group_generators(self) -> "OrderedSet":
        r"""Return the generating set, answered at this group's own placement.

        The bare noun ``gens`` is not this object's word.  A generating set
        belongs to a structure, and which structure it generates is the whole
        content: these generate under the group law, not linearly.

        Asked at the node *this* object sits at, not at the engine's.  The
        engine is placed only in the category of groups, so delegating to it
        would answer a finitely generated group with the general set -- and
        the identity would survive, which at the finitely generated node it
        does not.
        """
        engine = self._engine
        if self in OwnedFinitelyGeneratedGroups():
            return OwnedFinitelyGeneratedGroups.ParentMethods.group_generators(
                engine
            )
        return OwnedGroups.ParentMethods.group_generators(engine)

    def number_of_group_generators(self) -> "Integer":
        r"""Return \(|S|\) for the presentation's generating set \(S\)."""
        return self._engine.number_of_group_generators()

    def has_computed_group_generators(self) -> "bool | Unknown":
        r"""Return the engine's answer, since the generators are stored there.

        The generic probe reads the group's own storage, and this object
        stores an engine rather than generators -- so a permutation group
        given by generators would look, through the wrapper, like a group
        whose generators nobody has produced, and every equivariance check
        over them would decline for a computation that costs nothing.
        """
        return self._engine.has_computed_group_generators()

    def presenting_free_group(self) -> "Group":
        r"""Return \(F(S)\), the free group the relations are words in."""
        return OwnedFinitelyPresentedGroups.ParentMethods.presenting_free_group(
            self._engine
        )

    def defining_relations(self) -> "OrderedSet":
        r"""Return the relations of this group's presentation."""
        return OwnedFinitelyPresentedGroups.ParentMethods.defining_relations(
            self._engine
        )

    def cardinality(self) -> "Cardinal":
        return self._engine.cardinality()

    def is_finite(self) -> bool:
        return self._engine.is_finite()

    def is_abelian(self) -> bool:
        return self._engine.is_abelian()

    def _presentation_data(self) -> tuple:
        r"""Return \((|S|, \{\text{relators}\})\), the presentation's identity.

        The relators as Tietze words, which read them by generator position
        rather than by name: naming the generator \(x\) instead of \(a\) is a
        choice of alphabet, not a different group, exactly as a module's names
        are an index-set identification and stay out of its identity.
        """
        data = self.__dict__.get("_presentation_identity")
        if data is None:
            free_group, relations = _presentation_of(self._engine)
            data = (
                free_group.rank(),
                frozenset(relation.Tietze() for relation in relations),
            )
            self._presentation_identity = data
        return data

    def __hash__(self) -> int:
        r"""Hash on \(|G|\), an invariant equal groups share and cheap to get.

        The presentation is not hashed: for a group handed over as
        permutations it is a computation, and hashing is not where a
        computation belongs.  Equal groups have equal cardinality, so this
        keeps the contract while leaving the presentation to ``__eq__``.
        """
        return hash((type(self), self.cardinality()))

    def __eq__(self, other: object) -> bool:
        r"""Return whether the two are the same finitely presented group.

        Equal generating sets and equal sets of relations, and nothing about
        how each arrived: \(C_2\) as permutations, \(S_2\), \(\ZZ/2\) and
        \(\langle x\mid x^2\rangle\) are one group, and the whole point of
        owning the category is that they compare as one.
        """
        return (
            type(other) is type(self)
            and self._presentation_data() == other._presentation_data()
        )

    def _repr_(self) -> str:
        return repr(self._engine)


def own_group(group: "Group") -> OwnedGroup:
    r"""Return the owned group ``group`` presents."""
    return OwnedGroup(group)


# The Sage constructors a session builds groups with.  Each is the outermost
# ``__init__`` of its family, so the instance is complete when the hook runs.
# The classical groups have two: a GAP-backed one is not built by running the
# generic constructor and then adding GAP, so neither reaches the other.
_GROUP_CONSTRUCTIONS = (
    NamedMatrixGroup_generic,
    NamedMatrixGroup_gap,
    FreeGroup_class,
    AbelianGroup_class,
)


def _witnesses_finite_generation(group: "Group") -> bool:
    r"""Return whether ``group``'s own structure establishes finite generation."""
    return group.is_finitely_generated() is True


_GROUPS_INSTALLED = False


def install_groups() -> None:
    r"""Refine every group a session constructs into the owned nodes.

    Construction *is* intake here: once the preamble is loaded the session is
    inside its universe, and a group built in that session is a group the
    preamble may be asked about.  Sage's classes offer no other moment --
    the interesting groups are built on demand, and none of them passes
    through a preamble constructor first.

    Two registrations, in this order, because the second's evidence lives on
    the first: the owned node is what supplies ``is_finitely_generated``, and
    only a group that answers it with ``True`` carries the axiom.  A group
    that cannot say stays outside and answers ``Unknown``, which is the whole
    difference between this and a declaration.
    """
    global _GROUPS_INSTALLED
    # Local: a module-level import would close a cycle; the module is built by the time this runs.
    from dzack_research.preamble.refine import hook_post_init

    if _GROUPS_INSTALLED:
        return
    for construction in _GROUP_CONSTRUCTIONS:
        hook_post_init(construction, OwnedGroups())
        hook_post_init(
            construction,
            OwnedFinitelyGeneratedGroups(),
            predicate=_witnesses_finite_generation,
        )
    _GROUPS_INSTALLED = True


install_groups()
