r"""Owned categories of groups."""

from typing import Self

from sage.categories.category import Category
from sage.categories.finite_groups import FiniteGroups as SageFiniteGroups
from sage.categories.groups import Groups as SageGroups
from sage.categories.homset import Hom
from sage.categories.morphism import SetMorphism
from sage.categories.rings import Rings
from sage.groups.finitely_presented import FinitelyPresentedGroup
from sage.groups.free_group import FreeGroup_class
from sage.misc.latex import latex
from sage.sets.totally_ordered_finite_set import TotallyOrderedFiniteSet
from sage.structure.element import Element
from sage.structure.parent import Parent


class OwnedGroups(Category):
    r"""Groups whose notebook-facing methods are owned by the preamble."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "groups"

    def super_categories(self) -> list:
        return [SageGroups()]

    class ParentMethods:
        def group_generators(self) -> TotallyOrderedFiniteSet:
            """Return the generating set as `group_generators`."""
            return finite_ordered_set(SageGroups().ParentMethods.group_generators(self))

        def _latex_(self: Self) -> str:
            r"""Return the group displayed by its distinguished group_generators."""
            group_generators = self.group_generators()
            if not group_generators:
                return r"\{1\}"
            entries = ", ".join(str(latex(generator)) for generator in group_generators)
            return rf"\left\langle {entries} \right\rangle"


class OwnedFinitelyGeneratedGroups(Category):
    r"""Groups admitting a surjection \(F(S)\twoheadrightarrow G\), \(S\) finite.

    Finite generation is a property of a *morphism* -- the existence of that
    surjection -- and not of a stored list of elements.  Stated this way the
    next axiom has something to be the kernel of.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely generated groups"

    def super_categories(self) -> list:
        return [OwnedGroups()]


class OwnedFinitelyPresentedGroups(Category):
    r"""Finitely generated groups whose defining surjection has
    finitely generated kernel.

    Strictly stronger than finite generation: there are finitely generated
    groups admitting no finite presentation.  Strictly weaker than finiteness:
    \(O(L)\) for indefinite \(L\) is finitely presented and infinite.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finitely presented groups"

    def super_categories(self) -> list:
        return [OwnedFinitelyGeneratedGroups()]

    class ParentMethods:
        def _latex_(self: Self) -> str:
            r"""Return the group displayed by a presentation \(\langle S\mid R\rangle\).

            The generators are the presentation's, in its order: two of them
            may be equal in the group -- every generator is, when the group is
            trivial -- and a presentation still names both.  That is what
            distinguishes this from :meth:`OwnedGroups.ParentMethods._latex_`,
            which displays the *set* a group is generated by.
            """
            generators = ", ".join(
                str(latex(generator)) for generator in self.gens()
            )
            relations = ", ".join(
                str(latex(relation)) for relation in self.defining_relations()
            )
            if not generators:
                return r"\{1\}"
            if not relations:
                return rf"\left\langle {generators} \right\rangle"
            return (
                rf"\left\langle {generators} \;\middle|\; {relations} \right\rangle"
            )


class AbelianGroupEndomorphism(Element):
    r"""An endomorphism of an abelian group.

    A map, held as one.  Images of a generating set would be a presentation,
    and endomorphisms are wanted here for groups that have no distinguished
    one -- a permutation group has no coordinates to read an exponent off.
    """

    def __init__(self, parent: "Parent", mapping: "Callable") -> None:
        Element.__init__(self, parent)
        self._mapping = mapping

    def __call__(self, element: "Element") -> "Element":
        return self._mapping(element)

    def _add_(self, other: "AbelianGroupEndomorphism") -> "AbelianGroupEndomorphism":
        r"""Return \(f+g:x\mapsto f(x)g(x)\).

        A homomorphism exactly because the target is abelian:
        \((f+g)(xy)=f(x)f(y)g(x)g(y)\), and the middle pair commutes past
        each other to give \((f+g)(x)(f+g)(y)\).  This is the whole reason
        the endomorphism ring is a ring, and the reason it is built here.
        """
        return self.parent()(lambda element: self(element) * other(element))

    def _neg_(self) -> "AbelianGroupEndomorphism":
        return self.parent()(lambda element: self(element) ** -1)

    def _mul_(self, other: "AbelianGroupEndomorphism") -> "AbelianGroupEndomorphism":
        r"""Return the composite \(f\circ g\), the ring's multiplication."""
        return self.parent()(lambda element: self(other(element)))


class AbelianGroupEndomorphismRing(Parent):
    r"""\(\operatorname{End}(A)\) for \(A\) abelian, as a ring.

    Endomorphisms of any group compose, so they always form a monoid; they
    add only when the target is abelian.  So this is a ring precisely for the
    groups this category holds, and Sage builds no such ring for them --
    ``End(AbelianGroup([3]))`` is not in ``Rings()`` and declines to construct
    a morphism from generator images at all.
    """

    Element = AbelianGroupEndomorphism

    def __init__(self, group: "Group") -> None:
        assert group.is_abelian(), (
            f"{group} is not abelian, so its endomorphisms do not add"
        )
        self._group = group
        Parent.__init__(self, category=Rings())

    def domain(self) -> "Group":
        return self._group

    def codomain(self) -> "Group":
        return self._group

    def _element_constructor_(self, mapping: "Callable") -> AbelianGroupEndomorphism:
        return self.element_class(self, mapping)

    def one(self) -> AbelianGroupEndomorphism:
        return self(lambda element: element)

    def zero(self) -> AbelianGroupEndomorphism:
        return self(lambda element: self._group.one())

    def __hash__(self) -> int:
        return hash((type(self), self._group))

    def __eq__(self, other: object) -> bool:
        return type(other) is type(self) and self._group == other._group

    def _repr_(self) -> str:
        return f"Endomorphism ring of {self._group}"


class OwnedAbelianGroups(Category):
    r"""Abelian groups.

    \(\mathrm{Ab}\) and \(\mathbb Z\text{-Mod}\) are isomorphic categories.
    That is not the statement that a group parent already is a module: a
    \(\mathbb Z\)-module is a pair \((S,\rho)\) and \(\rho\) is structure, so
    it has to be put there.  What the isomorphism says is that there is no
    choice in putting it -- see :meth:`as_module`.
    """

    @classmethod
    def _repr_object_names(cls) -> str:
        return "abelian groups"

    def super_categories(self) -> list:
        return [OwnedGroups()]

    class ParentMethods:
        @cached_method
        def endomorphism_ring(self: Self) -> AbelianGroupEndomorphismRing:
            r"""Return \(\operatorname{End}(A)\), a ring because \(A\) is abelian."""
            return AbelianGroupEndomorphismRing(self)

        @cached_method
        def integer_action(self: Self) -> "Morphism":
            r"""Return the unique \(\rho:\mathbb Z\to\operatorname{End}(A)\).

            \(\mathbb Z\) is initial in rings, so there is exactly one ring
            morphism out of it into any ring, and \(\operatorname{End}(A)\) is
            a ring.  That is the whole content of
            \(\mathrm{Ab}\cong\mathbb Z\text{-Mod}\): the action exists and
            nothing about it is chosen.  It sends \(n\) to the \(n\)-th power
            map, which is what \(\rho(n)=n\cdot 1\) unwinds to.
            """
            endomorphisms = self.endomorphism_ring()
            return SetMorphism(
                Hom(ZZ, endomorphisms, Rings()),
                lambda exponent: endomorphisms(
                    lambda element: element**exponent
                ),
            )

        @cached_method
        def as_module(self: Self) -> "Module":
            r"""Return this group as a \(\mathbb Z\)-module.

            The elements are unchanged -- this group's own -- and \(\rho\) is
            what is added.  Presenting the module by invariant factors instead
            would answer with a different set of elements, and would choose a
            decomposition where the isomorphism asks for none.
            """
            return module_over_ring(self.integer_action())


class OwnedFiniteGroups(Category):
    r"""Finite groups whose notebook-facing methods are owned by the preamble."""

    @classmethod
    def _repr_object_names(cls) -> str:
        return "finite groups"

    def super_categories(self) -> list:
        return [OwnedGroups(), SageFiniteGroups()]


def _answers_abelian(group: "Group") -> bool:
    r"""Return whether ``group`` decides commutativity.

    Sage's free groups raise rather than answer, and a free group of rank one
    is abelian -- so a group declining the question is not a group that is
    nonabelian.  Placing on a witness and not on a default is the difference.
    """
    try:
        return bool(group.is_abelian())
    except NotImplementedError:
        return False


def _group_categories(group: "Group") -> list:
    r"""Return the owned categories ``group``'s presentation witnesses.

    Each axiom is claimed only when the group carries the witness the
    definition asks for, never when a theorem would be needed:

    * finitely generated -- a finite generating set, which *is* the surjection
      \(F(S)\twoheadrightarrow G\);
    * finitely presented -- a finite presentation, or finiteness, whose
      multiplication table is one;
    * abelian -- commutativity, as decided by the group.

    A group that answers none of these is still a group, and is placed as one.
    """
    categories = [OwnedGroups()]
    if group.is_finite():
        categories.append(OwnedFiniteGroups())
    if group.ngens() < Infinity:
        categories.append(OwnedFinitelyGeneratedGroups())
    if (
        group.is_finite()
        or isinstance(group, (FinitelyPresentedGroup, FreeGroup_class))
    ):
        categories.append(OwnedFinitelyPresentedGroups())
    if _answers_abelian(group):
        categories.append(OwnedAbelianGroups())
    return categories


class OwnedGroup(Parent):
    r"""The group a Sage group presents, as an owned object.

    Constructed from the Sage group rather than refined onto it.  Refining
    reassigns ``__class__`` on a parent this preamble did not build and cannot
    answer for: the object keeps whatever data Sage gave it, gains methods that
    ask for data an owned constructor would have stored, and fails at the first
    one that does.  Construction has no such gap -- the categories are settled
    here, from :func:`_group_categories`, so there is nothing left to refine.

    The elements are the Sage group's own.  A group's underlying set does not
    change by being placed, and the multiplication that makes it a group is the
    one the engine already computes.

    The engine crosses the boundary once, here, and is private afterwards.
    Handing it back out would make every method below optional: a caller who
    can reach the Sage group asks it directly, in Sage's nouns, and the owned
    object stops being where the group's questions are answered.
    """

    def __init__(self, engine: "Group") -> None:
        assert engine in SageGroups(), f"{engine} is not a group"
        self._engine = engine
        Parent.__init__(self, category=_group_categories(engine))

    def _element_constructor_(self, value: "Element") -> "Element":
        return self._engine(value)

    def __contains__(self, value: object) -> bool:
        return value in self._engine

    def __iter__(self):
        return iter(self._engine)

    def one(self) -> "Element":
        return self._engine.one()

    def an_element(self) -> "Element":
        return self._engine.an_element()

    def gens(self) -> tuple:
        return self._engine.gens()

    def ngens(self) -> "Integer":
        return self._engine.ngens()

    def defining_relations(self) -> "OrderedSet":
        r"""Return the relations of the presentation this group was given.

        The relations generate the kernel of \(F(S)\twoheadrightarrow G\),
        so they are a set of words in \(F(S)\) -- not the words themselves
        repeated, and not an ordering the presentation depends on.
        """
        return finite_ordered_set(self._engine.relations())

    def cardinality(self) -> "Cardinal":
        return self._engine.cardinality()

    def is_finite(self) -> bool:
        return self._engine.is_finite()

    def is_abelian(self) -> bool:
        return self._engine.is_abelian()

    def __hash__(self) -> int:
        return hash((type(self), self._engine))

    def __eq__(self, other: object) -> bool:
        return type(other) is type(self) and self._engine == other._engine

    def _repr_(self) -> str:
        return repr(self._engine)


def own_group(group: "Group") -> OwnedGroup:
    r"""Return the owned group ``group`` presents."""
    return OwnedGroup(group)
