"""The owned operation spine below groups."""

from sage.categories.morphism import Morphism

from dzack_research.preamble.categories.abstract_categories.mor_categories import (
    CategoricalMor,
    MorCategoryConstruction,
)
from dzack_research.preamble.categories.abstract_categories.objects import OwnedCategory
from dzack_research.preamble.owned_category_bases import CategoryWithAxiom


class Magmas(OwnedCategory):
    def super_categories(self):
        from dzack_research.preamble.categories.sets.set_categories import Sets

        return [Sets()]

    class SubcategoryMethods:
        def Commutative(self):
            r"""Return this category with the axiom ``xy = yx``.

            Commutativity is a property of the operation, so it is stated once
            here, at the level that introduces the operation, and every
            subcategory reaches it.
            """
            return self._with_axiom("Commutative")


class MonoidMorCategoryConstruction(MorCategoryConstruction):
    r"""The fixed-endpoint Mor categories of owned monoids."""

    def fixed_category_class(self):
        return MonoidMor


class Semigroups(OwnedCategory):
    def super_categories(self):
        return [Magmas()]


class Monoids(OwnedCategory):
    def super_categories(self):
        return [Semigroups()]

    class ElementMethods:
        def _pow_int(self, exponent):
            r"""Integer powers by repeated squaring, from the monoid law."""
            from sage.arith.power import generic_power

            return generic_power(self, exponent)

    class ParentMethods:
        def generated_submonoid(
            self, generators, *, description=None, structure_data=None
        ):
            r"""Return the represented submonoid generated by ``generators``."""
            from dzack_research.preamble.categories.group.submonoids import (
                _generated_submonoid,
            )

            return _generated_submonoid(
                self,
                generators,
                description=description,
                structure_data=structure_data,
            )

        def predicate_submonoid(
            self, predicate, description, *, structure_data=None
        ):
            r"""Return the represented submonoid cut out by ``predicate``."""
            from dzack_research.preamble.categories.group.submonoids import (
                _predicate_submonoid,
            )

            return _predicate_submonoid(
                self,
                predicate,
                description,
                structure_data=structure_data,
            )

    _MorCategory = MonoidMorCategoryConstruction

    def Mor(self, domain, codomain):
        if domain not in self or codomain not in self:
            raise TypeError("a monoid Mor requires two monoids")
        return self.MorCategory().Of(domain, codomain)



class AdditiveMagmas(OwnedCategory):
    def super_categories(self):
        from dzack_research.preamble.categories.sets.set_categories import Sets

        return [Sets()]

    class SubcategoryMethods:
        def AdditiveCommutative(self):
            r"""Return this category with the axiom ``x + y = y + x``."""
            return self._with_axiom("AdditiveCommutative")


class AdditiveSemigroups(OwnedCategory):
    def super_categories(self):
        return [AdditiveMagmas()]


class AdditiveMonoids(OwnedCategory):
    def super_categories(self):
        return [AdditiveSemigroups()]

    class ParentMethods:
        def monoidal_unit(self):
            return self.zero()


class AdditiveGroups(OwnedCategory):
    def an_object(self):
        r"""The additive group of the owned integers."""
        from sage.rings.integer_ring import ZZ as SageZZ

        from dzack_research.preamble.categories.rings.ring_foundation import _own_ring

        return _own_ring(SageZZ)

    def super_categories(self):
        return [AdditiveMonoids()]

    class AdditiveCommutative(CategoryWithAxiom):
        """Additive groups whose addition is commutative."""

        class _MorCategory(MorCategoryConstruction):
            def fixed_category_class(self):
                from dzack_research.preamble.categories.group.additive_mors import (
                    AdditiveMor,
                )

                return AdditiveMor

        @classmethod
        def _repr_object_names(cls):
            return "commutative additive groups"


class MonoidMorphism(Morphism):
    """A morphism in the owned category of monoids."""

    def __init__(self, parent, function) -> None:
        Morphism.__init__(self, parent)
        if not callable(function):
            raise TypeError("a monoid morphism requires an exact element map")
        self._function = function

    def __call__(self, element):
        return self._call_(element)

    def _call_(self, element):
        return self.codomain()(self._function(self.domain()(element)))

    def _composition(self, right):
        r"""``self ∘ right`` for a monoid morphism ``right``.

        Sage's ``Map.__mul__`` has checked that ``right`` is a map into this
        morphism's domain; a map outside the monoid Mor is not composed here.
        """
        if right.domain() not in Monoids() or not right.parent().mor_family().base_category().is_subcategory(Monoids()):
            return NotImplemented
        mor = self.parent().mor_family().Of(right.domain(), self.codomain())
        return mor(lambda element: self(right(element)))


class MonoidMor(CategoricalMor):
    r"""The owned fixed Mor category ``Mor_Mon(A,B)``."""

    Element = MonoidMorphism

    def __init__(self, family, domain, codomain) -> None:
        super().__init__(family, domain, codomain)

    def _element_constructor_(self, function):
        if isinstance(function, MonoidMorphism):
            if function.domain() is not self.domain() or function.codomain() is not self.codomain():
                raise ValueError("the monoid morphism has the wrong source or target")
            if function.parent() is self:
                return function
            function = function.__call__
        return self.element_class(self, function)

    def identity(self):
        if self.domain() is not self.codomain():
            raise ValueError("identity is defined only on a monoid endomorphism Mor object")
        return self(lambda element: element)
