r"""``Pic P^n = Cl P^n = Z``, generated by the hyperplane class.

Hartshorne, *Algebraic Geometry*: ``Cl P^n_k = Z`` generated by a hyperplane
(II.6.4); ``Cl X = Pic X`` for ``X`` noetherian, integral, separated and
locally factorial (II.6.16); hence ``Pic P^n_k = Z`` generated by ``O(1)``
(II.6.17); ``Cl(X x P^n) = Cl X x Z`` (II, Exercise 6.1), which with
``Cl(Spec Z) = 0`` gives ``Pic P^n_Z = Z``.
"""

from dzack_research.preamble.all import *  # noqa: F401,F403


def test_the_picard_group_of_projective_space_over_Q_is_free_on_the_hyperplane_class() -> None:
    r"""``Pic P^n_Q`` is free for ``n = 1, 2, 3``, with the hyperplane class a nonzero element."""
    for dimension in (1, 2, 3):
        space = ProjectiveSpaces(QQ)(dimension)
        picard = space.picard_group()

        assert picard in PicardGroups()
        assert picard.picard_scheme() is space
        assert picard.is_free()
        assert picard.hyperplane_class() != picard.zero()


def test_the_picard_group_of_projective_space_over_Q_has_rank_one() -> None:
    r"""``Pic P^n_Q = Z`` for ``n = 1, 2, 3``."""
    for dimension in (1, 2, 3):
        assert ProjectiveSpaces(QQ)(dimension).picard_group().module_rank() == 1


def test_the_class_group_of_the_projective_plane_has_rank_one() -> None:
    r"""``Cl P^2_Q = Z`` (II.6.4)."""
    assert ProjectiveSpaces(QQ)(2).class_group().module_rank() == 1


def test_the_comparison_from_picard_to_class_group_is_linear_on_the_hyperplane() -> None:
    r"""``Pic P^2 -> Cl P^2`` sends ``[O(1)]`` to the nonzero class ``[H]``, and ``3[O(1)]`` to ``3[H]``."""
    plane = ProjectiveSpaces(QQ)(2)
    picard = plane.picard_group()
    comparison = plane.picard_to_class_group_morphism()
    hyperplane = picard.hyperplane_class()

    assert comparison.domain() is picard
    assert comparison.codomain() is plane.class_group()
    assert comparison(hyperplane) != plane.class_group().zero()
    assert comparison(3 * hyperplane) == 3 * comparison(hyperplane)


def test_the_comparison_from_picard_to_class_group_is_bijective() -> None:
    r"""``P^2_Q`` is regular, hence locally factorial, so ``Pic -> Cl`` is an isomorphism (II.6.16)."""
    comparison = ProjectiveSpaces(QQ)(2).picard_to_class_group_morphism()

    assert comparison.is_injective()
    assert comparison.is_surjective()


def test_the_picard_group_of_projective_space_has_no_torsion() -> None:
    r"""``Pic P^2_Q = Z`` is torsion-free."""
    assert ProjectiveSpaces(QQ)(2).picard_group().torsion_submodule().cardinality() == 1


def test_the_picard_group_of_projective_space_over_a_finite_field_is_Z() -> None:
    r"""``Pic P^2_{F_5} = Z`` (II.6.17 holds over every field)."""
    assert ProjectiveSpaces(GF(5))(2).picard_group().module_rank() == 1


def test_the_picard_group_of_projective_space_over_the_integers_is_Z() -> None:
    r"""``Cl(P^2_Z) = Cl(Spec Z) x Z = Z``, and ``P^2_Z`` is regular, so ``Pic P^2_Z = Z``."""
    picard = ProjectiveSpaces(ZZ)(2).picard_group()

    assert picard.module_rank() == 1
    assert picard.torsion_submodule().cardinality() == 1
