# Origin: gitclones/integral_lattice/cat/src/abc_specs/w_categories/two_category_interface/nontrivial_two_category.py
# Copied 2026-08-20 by the integral_lattice enrichment migration
# (PLAN-corpora-audit-registry, sections R3/R4). Content below is unmodified.
#
# This is a DESIGN RECORD: it states an intended interface, not the built
# preamble. Divergences and recorded errors are listed in the INDEX.md of
# this corpus.


from __future__ import annotations
from src.local_typing import *
from src._types import CategoryABCs
from .two_category_mixins import *
from src.abc_specs.w_categories.hom_categories.abstract_arrows import *
from .minimal_two_category import MinimalCategory
from .two_category_mixins import Hom_Constructors

@dataclass
class _Nontrivial_Two_Category_ABC(
    MinimalCategory, 
    # Minimal category mixins:
    # - Required_Sage_Methods
    # - Basic_Metadata
    # - Object_And_Morphism_Classes
    # - Predicates_On_This_Category
    # - Ambient_Category_Interactions
    # - Equivalence_Of_Self_With_Other_Checks
    # - Self_With_Other_Operators
    Hom_Constructors, # E.g. self.Hom_C(x,y) := Hom_C(x,y)
    Predicates_On_Objects, # E.g. self.is_terminal_object_C(x) := (x == *C)
    Limit_C_Classes, # E.g. self.product_class() must be defined for products in
    Internal_Object_And_Morphism_Constructors,
    Object_Enumerating_And_Sampling,
    ABC):
    
    @final
    @abstractmethod
    def forgetful_functor_to_set(self) -> CategoryABCs.Functor:
        """The forgetful functor U: C -> Set."""
        ...
    
@dataclass
class _Element_ABC(ABC):
    """
    An element in a category.
    """

    as_empty_cell: CategoryABCs.Cell

    def parent_object(self) -> CategoryABCs.Object:
        """The object containing this element."""
        ...
        
@dataclass
class _Object_ABC(
    Basic_Metadata,
    Ambient_Category_Interactions,
    Self_With_Other_Operators,
    Equivalence_Of_Self_With_Other_Checks,
    Element_Enumerating_And_Sampling,
    ABC
    ):
    """
    An object in a category.
    """
    
    as_zero_cell: CategoryABCs.Cell

    def amb(self) -> CategoryABCs.Nontrivial_TwoCategory:
        """The category containing this point."""
        ...

    def cyclic_subobject_generated_by(self, x: Element) -> Self:
        """Return the subobject generated by the given element."""
        ...
    
    def subobject_generated_by(self, xs: Sequence[Element]) -> Self:
        """Return the subobject generated by the given elements."""
        ...


# Elements and Objects
Element = _Element_ABC
Object = _Object_ABC

# Categories
Nontrivial_TwoCategory = _Nontrivial_Two_Category_ABC